[translation]
10004-FullNameTh = "โซระซากิ ฮินะ"
10004-FamilyNameTh = "โซระซากิ"
10004-PersonalNameTh = "ฮินะ"
10004-SchoolYearTh = "ชั้นปีที่ 3"
10004-CharacterAgeTh = "17 ปี"
10004-BirthdayTh = "19 ก.พ."
10004-HobbyTh = "พักผ่อน, นอนหลับ"
10004-WeaponNameTh = "Destroyer of Denouement"
10004-WeaponDescTh = "ปืนกลอเนกประสงค์ที่เป็นเหมือนอวัยวะส่วนหนึ่งของฮินะ\n\nผู้ที่แหกกฎโรงเรียนหรือทำลายความสงบ จะถูกกำจัดอย่างไร้ความปรานี"
10004-ProfileIntroductionTh = "ประธานคณะกรรมการวินัย แห่งสถาบันเกเฮนน่า\n\nปกติแล้วฮินะเป็นสาวน้อยจอมขี้เกียจ แต่หากเจอประเด็นที่เกี่ยวข้องกับกฎ ข้อบังคับของโรงเรียนก็จะเข้มงวด สมกับเป็นประธานคณะกรรมการวินัย เธอชอบพูดว่า 'ขี้เกียจ' จนติดเป็นนิสัย แต่ในสนามรบเธอจะตัดสินสถานการณ์ โดยปราศจากความลังเล ทำให้ศัตรูของเกเฮนน่า ต่างหวาดกลัวการปรากฏตัวของเธอ"
10004-CharacterSSRNewTh = "น่ารำคาญจริงๆ แต่ก็คงต้องทำสินะ\nเพราะนั่นคือหน้าที่ของฉัน"
