[translation]
10015-StatusMessageTh = "อาริสึจากชมรมพัฒนาเกมมิลเลเนียม"
10015-FullNameTh = "เทนโด อาริสึ"
10015-FamilyNameTh = "เทนโด"
10015-PersonalNameTh = "อาริสึ"
10015-SchoolYearTh = "ชั้นปีที่ 1"
10015-CharacterAgeTh = "?? ปี"
10015-BirthdayTh = "25 มี.ค."
10015-HobbyTh = "เล่นเกม RPG"
10015-WeaponNameTh = "Supernova: The Sword of Light"
10015-WeaponDescTh = "ปืนเรลกันขนาดมหึมาที่อาริสึได้มาจากชมรมวิศวกรรม\n\nเนื่องจากขนาดและน้ำหนักมหาศาลจึงทำให้นักเรียนทั่วไป\nไม่สามารถพกติดตัวไปได้"
10015-ProfileIntroductionTh = "สมาชิกชมรมพัฒนาเกมแห่งโรงเรียนวิทย์มิลเลเนียม\n\nเด็กสาวที่ถูกพบในซากปรักหักพัง ไม่สามารถคาดเดาข้อมูลเกี่ยวกับเธอได้ แม้แต่อายุก็ตาม เธอสนุกกับการเล่นเกมตามมิโดริกับโมโมอิ และผันตัวเป็นผู้คลั่งไคล้เกมตัวยง คำพูดของเธอส่วนมากมาจากเกมที่เล่น"
10015-CharacterSSRNewTh = "ฉันเฝ้ารอการเรียกหาจากคุณมานานแล้วค่ะ"
