[translation]
10012-StatusMessageJp = "Healthy body healthy mind"
10012-FullNameJp = "Otohana Sumire"
10012-FamilyNameJp = "Otohana"
10012-PersonalNameJp = "Sumire"
10012-SchoolYearJp = "2nd Year"
10012-CharacterAgeJp = "16 years old"
10012-BirthdayJp = "August 20th"
10012-HobbyJp = "Gardening, working out"
10012-WeaponNameJp = "Modern Millennium Dumbbell"
10012-WeaponDescJp = "A semi-automatic shotgun that Sumire uses regularly when exercising.\n\nCan improve one's health by doing a push-up with each shot fired."
10012-ProfileIntroductionJp = "Leader of the Millennium Athletic Training Club.\n\nAn athletic girl with a passion for physical training. She is very much a jock and believes all problems can be solved with muscles and exercise."
10012-CharacterSSRNewJp = "Shall we start today's training?"
