[translation]
10019-StatusMessageJp = "et omnia vanitas"
10019-FullNameJp = "Shirasu Azusa"
10019-FamilyNameJp = "Shirasu"
10019-PersonalNameJp = "Azusa"
10019-SchoolYearJp = "2nd Year"
10019-CharacterAgeJp = "16 years old"
10019-BirthdayJp = "December 26th"
10019-HobbyJp = "None"
10019-WeaponNameJp = "Et Omnia Vanitas"
10019-WeaponDescJp = "A gun cherished by Azusa.\n\nThe engraving on its barrel means, \"Vanity of vanities: All is in vain\"."
10019-ProfileIntroductionJp = "The ice queen of Trinity's Make-Up Work Club.\n\nAfter dropping out of school, she ended up at Trinity and is studying again. Despite being lonely, Azusa distances herself from others to avoid causing trouble—a source of concern for the other Make-Up Work Club members."
10019-CharacterSSRNewJp = "All is futile, and life has no meaning.\nThough part of me wants to trust you."
