[translation]
10017-StatusMessageEn = "Mustache, it's a mustache!"
10017-FullNameEn = "Renkawa Cherino"
10017-FamilyNameEn = "Renkawa"
10017-PersonalNameEn = "Cherino"
10017-SchoolYearEn = "3rd Year"
10017-CharacterAgeEn = "Unknown"
10017-BirthdayEn = "October 27th"
10017-HobbyEn = "Doling out demerits, purges, snowball fights"
10017-WeaponNameEn = "Chistka"
10017-WeaponDescEn = "A pistol Cherino uses to purge dissenters.\n\nCherino simply aims the pistol and shouts, \"Purge!\" And just like that, it's done—without even pulling the trigger."
10017-ProfileIntroductionEn = "Student council president of Red Winter Academy.\n\nGreedy and obsessed with power, she loses her position in a revolution once a week but somehow always regains her authority. Cherino believes her power comes from the fake mustache she wears as a symbol of authority."
10017-CharacterSSRNewEn = "Feel the glory of facing me!"
