[translation]
10027-StatusMessageEn = "Currently undercover."
10027-FullNameEn = "Kakudate Karin"
10027-FamilyNameEn = "Kakudate"
10027-PersonalNameEn = "Karin"
10027-SchoolYearEn = "2nd Year"
10027-CharacterAgeEn = "16 years old"
10027-BirthdayEn = "February 2nd"
10027-HobbyEn = "Cleaning"
10027-WeaponNameEn = "Big Eye"
10027-WeaponDescEn = "A massive sniper rifle used exclusively by Karin.\n\nIt's so accurate that one could shoot down a dashing rabbit with it."
10027-ProfileIntroductionEn = "A C&C agent on the front lines.\n\nShe is focused only on accomplishing the mission without complaint or concern for her outfit.\nStill, the longer-than-normal stares from others are a bit bothersome."
10027-CharacterSSRNewEn = "There's no mission I can't accomplish."
