[translation]
10024-StatusMessageTw = "正在縱貫奇普托斯中"
10024-FullNameTw = "砂狼白子"
10024-FamilyNameTw = "砂狼"
10024-PersonalNameTw = "白子"
10024-SchoolYearTw = "2年級"
10024-CharacterAgeTw = "16歲"
10024-BirthdayTw = "5月16日"
10024-HobbyTw = "慢跑、體力訓練、公路自行車"
10024-WeaponNameTw = "WHITE FANG 465"
10024-WeaponDescTw = "白子的愛用突擊步槍。\n\n為了能承受在屋外的長距離移動，小心翼翼整備的同時也做了各式各樣的改造。"
10024-ProfileIntroductionTw = "阿拜多斯高中所屬，換上了騎行用的正式裝束，阿拜多斯對策委員會的突擊隊長。\n\n脫下平常的制服，鼓起幹勁換上騎行服的他，總覺得看起來比平常還要開朗。目標雖然是誇張的「縱貫奇普托斯」，但不知是否因為有著值得信賴的夥伴，本人看來並沒有不安和擔心的樣子。"
10024-CharacterSSRNewTw = "那麼，老師。我到了會馬上連絡你哦"
