[translation]
10027-StatusMessageTw = "任務中"
10027-FullNameTw = "角楯花凛"
10027-FamilyNameTw = "角楯"
10027-PersonalNameTw = "花凛"
10027-SchoolYearTw = "2年級"
10027-CharacterAgeTw = "16歲"
10027-BirthdayTw = "2月2日"
10027-HobbyTw = "清掃"
10027-WeaponNameTw = "Hawkeye"
10027-WeaponDescTw = "花凜專用的反器材狙擊步槍。\n\n就算是飛舞於空中的「白兔」也能精確無比地擊落。"
10027-ProfileIntroductionTw = "千年科學學園所屬，直接參加這次作戰最前線的「C&C」特務。\n\n嘴裡雖說著「如果是為了任務的話」，仍然興沖沖地換裝。不過，卻比平時更在意周圍的人投來的視線。"
10027-CharacterSSRNewTw = "無論是什麼樣的任務，對我來說都無所謂"
