[translation]
10022-FullNameTw = "空崎陽奈"
10022-FamilyNameTw = "空崎"
10022-PersonalNameTw = "陽奈"
10022-SchoolYearTw = "3年級"
10022-CharacterAgeTw = "17歲"
10022-BirthdayTw = "2月19日"
10022-HobbyTw = "睡眠、休息"
10022-WeaponNameTw = "終幕：Destroyer"
10022-WeaponDescTw = "陽奈對待它有如對待自己手足的機槍。\n\n即使面對大海，也改變不了它的威力。"
10022-ProfileIntroductionTw = "格黑娜學園所屬，為了夏季合宿而來到海邊的風紀委員長。\n\n基本上怕麻煩的他，還是為了訓練而無奈地來到海邊。他幾乎沒有在海邊玩耍過，泳衣和泳圈看起來都是以前的東西。即使說著「因為很浪費」這樣的理由，卻還是對自己仍能穿下那件泳衣而打心底感到有些在意。不過無論是什麼樣的打扮、季節或是地點，都無法改變他對風紀的嚴謹。"
10022-CharacterSSRNewTw = "就算是夏天，要做的事也沒有改變"
