[translation]
10035-StatusMessageEn = "AFK"
10035-FullNameEn = "Kozeki Ui"
10035-FamilyNameEn = "Kozeki"
10035-PersonalNameEn = "Ui"
10035-SchoolYearEn = "3rd Year"
10035-CharacterAgeEn = "17 years old"
10035-BirthdayEn = "April 23rd"
10035-HobbyEn = "Reading, Curating, Researching"
10035-WeaponNameEn = "Volume Suppressor"
10035-WeaponDescEn = "A silencer rifle that Ui takes out when she can't stand the noise around her anymore. It lives up to its name, and silences its targets swiftly and effectively."
10035-ProfileIntroductionEn = "Trinity Library Committee's Director.\n\nA girl said to love books more than people that especially likes old books that clearly have history. She normally spends her time cooped up in Trinity's old library, curating the ancient texts."
10035-CharacterSSRNewEn = "P-Please, keep it down..."
