[translation]
10031-StatusMessageEn = "Looking forward to the new year."
10031-FullNameEn = "Rikuhachima Aru"
10031-FamilyNameEn = "Rikuhachima"
10031-PersonalNameEn = "Aru"
10031-SchoolYearEn = "2nd Year"
10031-CharacterAgeEn = "16 years old"
10031-BirthdayEn = "March 12th"
10031-HobbyEn = "Studying management"
10031-WeaponNameEn = "Wine Red Admire"
10031-WeaponDescEn = "A semi-automatic sniper rifle with an antique design cherished by Aru.\n\nAccording to Aru, her hard-boiled nature culminates just as her years of experience do with the upcoming New Year."
10031-ProfileIntroductionEn = "The eternal boss of Problem Solver 68.\n\nAru spends a lot of money on getting her hair done and renting an outfit to wear to the New Year's event in the hopes that her fixer agency will prosper in the new year.Perhaps because she feels more confident than usual, she has been putting on the air of a dignified boss, walking and talking in a nonchalant and carefree way."
10031-CharacterSSRNewEn = "Heeheehee. This is the first commission of the year, right?\nOkay, I'll give it my best."
