[translation]
10034-StatusMessageJp = "Take one step at a time."
10034-FullNameJp = "Mizuha Mimori"
10034-FamilyNameJp = "Mizuha"
10034-PersonalNameJp = "Mimori"
10034-SchoolYearJp = "2nd Year"
10034-CharacterAgeJp = "16 years old"
10034-BirthdayJp = "March 15th"
10034-HobbyJp = "Reading shoujo manga, homemaking"
10034-WeaponNameJp = "Soft Resolution"
10034-WeaponDescJp = "An automatic pistol that Mimori usually carries around.\n\nShe bought it when she first dreamed of becoming an elegant lady. She cherishes it, always having it by her side."
10034-ProfileIntroductionJp = "Hyakkiyako Academy Inner Discipline Club's kind vice president.\n\nA popular girl because she always has a gentle smile and is kind to everyone. The childhood friend of Tsubaki, the president of the Inner Discipline Club. She joined the club to fulfill her dream of becoming an elegant lady like the ones in the shoujo manga she used to read when she was young. She continues to train diligently by cooking and cleaning to make her dream come true."
10034-CharacterSSRNewJp = "I still have a long way to go...\nbut I'll show you the results of my training."
