[translation]
10037-StatusMessageJp = "The impure must be purged!"
10037-FullNameJp = "Ikekura Marina"
10037-FamilyNameJp = "Ikekura"
10037-PersonalNameJp = "Marina"
10037-SchoolYearJp = "2nd Year"
10037-CharacterAgeJp = "16 years old"
10037-BirthdayJp = "November 4th"
10037-HobbyJp = "Marching, Charging"
10037-WeaponNameJp = "Gray Balalaika"
10037-WeaponDescJp = "A submachine gun with a drum magazine adored by Marina.\n\nCan smash those that doubt the Red Winter Office's authority with alacrity."
10037-ProfileIntroductionJp = "Chairwoman of the Security Committee in charge of Red Winter Academy's safety.\n\nThough she's known as a cold-hearted disciplinarian, the truth is she just blindly follows President Cherino's orders. She likes the word \"charge\" and is the first to run off when a problem occurs within Red Winter Academy, but often loses her way due to her terrible sense of direction."
10037-CharacterSSRNewJp = "Running away doesn't help one bit!"
