[translation]
10030-StatusMessageTw = "尋求未知的視野"
10030-FullNameTw = "火宮千夏"
10030-FamilyNameTw = "火宮"
10030-PersonalNameTw = "千夏"
10030-SchoolYearTw = "1年級"
10030-CharacterAgeTw = "15歲"
10030-BirthdayTw = "8月22日"
10030-HobbyTw = "讀哲學書"
10030-WeaponNameTw = "Support Pointer"
10030-WeaponDescTw = "千夏愛用的手槍。\n\n小型便於攜帶，很適合溫泉浴場之類的潛入任務。"
10030-ProfileIntroductionTw = "格黑娜學園所屬，因為任務偶然來到赤冬溫泉浴場的格黑娜風紀委員會的救護擔當。\n\n從下訂新醫藥品，到處理格黑娜溫泉開發部。即使身在溫泉浴場，令他煩惱的問題依然堆積如山。即使如此，不知是不是因為溫泉浴場美麗的景色和悠閒的氣氛，使他的表情比以往還要柔和。"
10030-CharacterSSRNewTw = "……至少今天，悠閒地度過吧"
