[translation]
10047-StatusMessageTh = "แสงระยิบระยับ อยู่ที่ไหนกันนะ?"
10047-FullNameTh = "วาราคุ ชิเซะ"
10047-FamilyNameTh = "วาราคุ"
10047-PersonalNameTh = "ชิเซะ"
10047-SchoolYearTh = "ชั้นปีที่ 2"
10047-CharacterAgeTh = "16 ปี"
10047-BirthdayTh = "13 ก.ค."
10047-HobbyTh = "แต่งกลอนไฮกุ"
10047-WeaponNameTh = "Type 575 Grenade Launcher"
10047-WeaponDescTh = "ปืนยิงระเบิดที่ชิเซะใช้เป็นประจำ\n\nเพื่อเป็นส่วนหนึ่งของการทำงานในฤดูร้อนนี้ ชิเซะยอมรับ\nข้อเสนอของคุณครู และสลักกลอนไฮกุที่แต่งขึ้นเองลง\nบนกระสุน เป็นของล้ำค่าของชิเซะที่ไม่มีวางขายที่ไหน"
10047-ProfileIntroductionTh = "เด็กสาวเดนปาซังแห่งชมรมหยินหยางที่ชอบยืนเหม่ออยู่เหมือนเดิม แม้จะอยู่ท่ามกลางแสงแดดในฤดูร้อน\n\nพอเปลี่ยนเป็นชุดว่ายน้ำ พลังแห่งไอดอล(?) ของเธอก็เพิ่มสูงขึ้น\nเสียงกรี๊ดและแรงเชียร์จากแฟนๆ ที่ชื่นชมเธอก็ร้อนแรงราวกับแสงแดด\nในฤดูร้อน แต่ชิเซะก็ดูเหมือนจะไม่ได้สนใจอะไรมากนัก\nในวันนี้ชิเซะเอง ก็ได้มาใช้ช่วงเวลาฤดูร้อนอย่างมีความสุขกับคุณครู และใช้เวลาอย่างสนุกสนานไปกับการจิ้มหลังคุณเต่าอยู่ริมทะเล"
10047-CharacterSSRNewTh = "ทะเลนี่มีเรื่องสนุกๆ เยอะแยะเลยน้า~"
