[translation]
10049-StatusMessageTw = "放學後的甜點部成員"
10049-FullNameTw = "杏山千紗"
10049-FamilyNameTw = "杏山"
10049-PersonalNameTw = "千紗"
10049-SchoolYearTw = "1年級"
10049-CharacterAgeTw = "15歲"
10049-BirthdayTw = "8月5日"
10049-HobbyTw = "「平凡地」吃甜點"
10049-WeaponNameTw = "馬比諾吉昂"
10049-WeaponDescTw = "和千紗度過許多歲月的機關槍。\n\n一詢問名字的由來，千紗就會露出苦悶的表情。"
10049-ProfileIntroductionTw = "三一綜合學園所屬，個性溫和安靜的放學後的甜點部成員。\n\n不常表現自己，大部分時間都只會默默跟在其他成員後面。\n總是被周遭的怪異行為拖累，但同時也認為這些時光很寶貴。"
10049-CharacterSSRNewTw = "啊，老師。\n竟然在這種地方見到真巧呢"
