[translation]
10040-StatusMessageEn = "I wanna be a full-fledged ninja..."
10040-FullNameEn = "Ono Tsukuyo"
10040-FamilyNameEn = "Ono"
10040-PersonalNameEn = "Tsukuyo"
10040-SchoolYearEn = "1st Year"
10040-CharacterAgeEn = "15 years old"
10040-BirthdayEn = "April 5th"
10040-HobbyEn = "Disguising as a tree, hiding"
10040-WeaponNameEn = "Tsukuyo-Style Submachine Gun"
10040-WeaponDescEn = "A submachine gun cherished by Tsukuyo.\n\nTsukuyo isn't very familiar with guns, so Michiru and Izuna helped modify it bit by bit. She now considers it an irreplaceable precious treasure because of their efforts."
10040-ProfileIntroductionEn = "A girl from the Hyakkiyako Ninjutsu Research Club.\n\nTsukuyo is insecure about her towering height, as she was teased relentlessly for it as a child. She is timid and has a hard time speaking up, but also determinedly follows her goals once she's made a decision. While she doesn't know much about ninjas, she does her best for Michiru and Izuna so she won't let them down."
10040-CharacterSSRNewEn = "I-I'm just a tall, good-for-nothing... But I want to do my best to help, Sensei!"
