[translation]
10040-StatusMessageTh = "หวังว่าฉันจะกลายเป็นนินจาได้ในเร็วๆ นี้..."
10040-FullNameTh = "โอโนะ สึคุโยะ"
10040-FamilyNameTh = "โอโนะ"
10040-PersonalNameTh = "สึคุโยะ"
10040-SchoolYearTh = "ชั้นปีที่ 1"
10040-CharacterAgeTh = "15 ปี"
10040-BirthdayTh = "5 เม.ย."
10040-HobbyTh = "แปลงร่างเป็นต้นไม้, ฝึกกลั้นหายใจอย่างลับๆ"
10040-WeaponNameTh = "Tsukuyo-Style Submachine Gun"
10040-WeaponDescTh = "ปืนกลมือที่สึคุโยะหวงแหน\n\nปืนกลมือที่มิจิรุและอิซุนะช่วยกันปรับแต่ง เพื่อสึคุโยะที่ไม่ค่อยคุ้นเคยเรื่องปืนเท่าไร ดังนั้นปืนด้ามนี้จึงเป็นสมบัติสำคัญของสึคุโยะ ที่ไม่มีอะไรมาทดแทนได้"
10040-ProfileIntroductionTh = "เด็กสาวชมรมวิจัยศาสตร์นินจาแห่งสหพันธ์เฮียกคิยาโค\n\nสึคุโยะมักถูกล้อเลียนเรื่องขนาดตัวที่ใหญ่กว่าคนอื่นๆ มาตั้งแต่เด็ก ทำให้เธอค่อนข้างอ่อนไหวมากเรื่องขนาดตัวของเธอ ปกติสึคุโยะจะค่อนข้างเก็บตัว และพูดคุยกับคนอื่นได้ไม่เก่งเท่าไร แต่ถ้าเธอตัดสินใจที่จะทำอะไรบางอย่างแล้ว เธอก็จะมุ่งมั่นทำให้สำเร็จ ถึงเธอจะไม่ค่อยรู้เรื่องเกี่ยวกับศาสตร์นินจามากนัก แต่ก็เข้ากับมิจิรุที่ยอมรับในตัวเธอ และอิซุนะได้อย่างดี"
10040-CharacterSSRNewTh = "ถะ...ถึงฉันจะตัวใหญ่แบบนี้... แต่ฉันจะพยายาม\nสุดความสามารถเพื่อทำประโยชน์ให้คุณครูค่ะ!"
