[translation]
10042-StatusMessageJp = "I've been learning the language of flowers lately."
10042-FullNameJp = "Hakari Atsuko"
10042-FamilyNameJp = "Hakari"
10042-PersonalNameJp = "Atsuko"
10042-SchoolYearJp = "1st Year"
10042-CharacterAgeJp = "15 years old"
10042-BirthdayJp = "January 20th"
10042-HobbyJp = "Gardening"
10042-WeaponNameJp = "Scorpius"
10042-WeaponDescJp = "A submachine gun Atsuko uses.\n\nIt has strong firepower and a short barrel, making it suitable for close combat."
10042-ProfileIntroductionJp = "A mysterious member of the Arius Squad who always wears a gas mask. Atsuko's mask isn't necessarily meant for disguise but rather a gas mask she wears for protection and safety. The squad leader, Saori, calls her Hime. Very little is known of who she is."
10042-CharacterSSRNewJp = "I wish there were flowers on this path."
