[translation]
10053-StatusMessageEn = "The Kivotos Halo Festival is underway!"
10053-FullNameEn = "Hayase Yuuka"
10053-FamilyNameEn = "Hayase"
10053-PersonalNameEn = "Yuuka"
10053-SchoolYearEn = "2nd Year"
10053-CharacterAgeEn = "16 years old"
10053-BirthdayEn = "March 14th"
10053-HobbyEn = "Doing calculations"
10053-WeaponNameEn = "Logic & Reason"
10053-WeaponDescEn = "A pair of machine guns used by Yuuka..\n\nYuuka is never without her logic or reason. Hopefully they won't weigh her down during the event..."
10053-ProfileIntroductionEn = "The Seminar treasurer, changed into gym clothes to participate in the Kivotos Halo Festival.\n\nDespite having already suffered from a heavy workload preparing for the big event, all she needed was a good night's rest to be back in tip-top condition. As a member of Seminar, Yuuka wants to focus on being a calm, rational representative of the council and ambassador to Kivotos, but the competitiveness of her fellow students is more infectious than she would ever admit."
10053-CharacterSSRNewEn = "Perfectly prepared for this year's Kivotos Halo Festival!"
