[translation]
10068-StatusMessageTw = "「The ♠ of Vigilante」"
10068-FullNameTw = "宇沢澪紗"
10068-FamilyNameTw = "宇沢"
10068-PersonalNameTw = "澪紗"
10068-SchoolYearTw = "1年級"
10068-CharacterAgeTw = "15歲"
10068-BirthdayTw = "5月31日"
10068-HobbyTw = "申請決鬥、自我介紹"
10068-WeaponNameTw = "SHOOTING☆STAR"
10068-WeaponDescTw = "澪紗珍惜的散彈槍。\n\n精心客製化而成的槍身，無論是誰都看得出是澪紗的槍。與可愛的外觀不同，能看見在無數戰場中征戰過的痕跡。"
10068-ProfileIntroductionTw = "出沒在三一的各個角落，進行著治安維持活動的三一綜合學園所屬，自衛隊的成員。\n\n由於會說一些難以捉摸的話，有時會被誤會是惡作劇通報，但其實比任何人都認真進行著自衛隊的活動。自我介紹時報上的名號似乎每次都會逐漸改變。"
10068-CharacterSSRNewTw = "追尋正義之人的身邊……有我在……沒錯，我就是超級巨星。\n宇沢澪紗，在此登場！"
