[translation]
10069-StatusMessageEn = "The Black Tortoise Promenade is open!"
10069-FullNameEn = "Akeshiro Rumi"
10069-FamilyNameEn = "Akeshiro"
10069-PersonalNameEn = "Rumi"
10069-SchoolYearEn = "3rd Year"
10069-CharacterAgeEn = "17 years old"
10069-BirthdayEn = "March 5th"
10069-HobbyEn = "Cooking, Food Product Development"
10069-WeaponNameEn = "Learn the Old, Know the New"
10069-WeaponDescEn = "Rumi's favorite submachine gun.\n\nNamed after an old idiom that goes, \"learn from the old to know the new.\" Rumi has always seemed more interested in the \"new\" aspect."
10069-ProfileIntroductionEn = "President of the Black Tortoise Promenade, a food district in Shanhaijing Academy.\n\nPossessing exceptional operational skills, Rumi has grown the Black Tortoise Promenade from a run-of-the-mill food alley into one of the most sought-after food districts in Kivotos. This has made her a thorn in the side of the Shanhaijing Student Council, who is wary of the growth of independent factions. Rumi denies this and claims she isn't interested in anything other than cooking and advancing the promenade."
10069-CharacterSSRNewEn = "Is anyone hungry?"
