[translation]
10071-StatusMessageJp = "I'll let my results speak for me."
10071-FullNameJp = "Tsukiyuki Miyako"
10071-FamilyNameJp = "Tsukiyuki"
10071-PersonalNameJp = "Miyako"
10071-SchoolYearJp = "1st Year"
10071-CharacterAgeJp = "15 years old"
10071-BirthdayJp = "January 7th"
10071-HobbyJp = "Watching bunny videos"
10071-WeaponNameJp = "RABBIT Type 31 Submachine Gun"
10071-WeaponDescJp = "A submachine gun Miyako received from the SRT Academy.\nIt's incredibly reliable and can operate effectively in hot and humid environments."
10071-ProfileIntroductionJp = "The RABBIT Squad leader, who has come to a remote fishing village on an undercover operation.\n\nShe has come to the seaside town disguised as a tourist to investigate the boxed lunches distributed to convenience stores.\nWith the hostile reactions from the residents and the fishy smell wafting through town, it's not exactly a tourist's dream. But still, she can't resist dressing for the beach with a cute swimsuit!"
10071-CharacterSSRNewJp = "This is RABBIT 1. We've just arrived at the ocean."
