[translation]
10073-StatusMessageTw = "出差中"
10073-FullNameTw = "古関憂"
10073-FamilyNameTw = "古関"
10073-PersonalNameTw = "憂"
10073-SchoolYearTw = "3年級"
10073-CharacterAgeTw = "17歲"
10073-BirthdayTw = "4月23日"
10073-HobbyTw = "讀書、管理書、古書研究"
10073-WeaponNameTw = "消音器"
10073-WeaponDescTw = "久違外出時也一起陪同的憂的狙擊步槍。\n\n明明是在安靜的無人島，卻莫名地經常用上。"
10073-ProfileIntroductionTw = "在與修女會的交易下，前來調查遺跡的三一綜合學園所屬，圖書委員會的委員長。\n\n雖然不喜歡在戶外活動身體，但出於對古書、遺跡和遺物的喜好，對調查工作似乎相當認真。"
10073-CharacterSSRNewTw = "哈啊，哈啊……好熱……\n糟透了……"
