[translation]
10079-StatusMessageTh = "กำลังหากู้ด"
10079-FullNameTh = "มิซากะ มิโคโตะ"
10079-FamilyNameTh = "มิซากะ"
10079-PersonalNameTh = "มิโคโตะ"
10079-SchoolYearTh = "ชั้นปีที่ 2"
10079-CharacterAgeTh = "14 ปี"
10079-BirthdayTh = "2 พ.ค."
10079-HobbyTh = "ยืนอ่านนิตยสารในร้านสะดวกซื้อ, สะสมกู้ดเกโคตะ"
10079-WeaponNameTh = "Gunbolt"
10079-WeaponDescTh = "ปืนประจำตัวที่ชมรมวิศวกรรมประดิษฐ์ให้มิซากะ มิโคโตะ\n\nมีการเพิ่มฟังก์ชันพิเศษไว้สำหรับมิโคโตะ ผู้มีพลังด้านไฟฟ้าโดยเฉพาะ"
10079-ProfileIntroductionTh = "นักเรียนมัธยมจากโรงเรียนมัธยมต้นโทคิวะได\n\nท่ามกลางเมืองแห่งการศึกษาที่มีผู้มีพลังมากมาย มิโคโตะเป็นหนึ่งในผู้ที่มีพลัง\nเลเวล 5 ที่มีอยู่เพียง 7 คนเท่านั้น มีพลังในการใช้และควบคุมไฟฟ้า ที่ทรงพลังได้\nอย่างอิสระ (อิเล็กโทรมาสเตอร์) แต่หลังจากย้ายมาที่คิโวทอส เธอก็พบกับ\nความลำบากในการใช้พลังนี้ มิโคโตะเป็นมิตรกับทุกคน ความอ่อนหวานของเธอ\nทำให้เธอมีความสัมพันธ์ที่ดีกับนักเรียนคนอื่นๆ นอกจากนี้เธอยังเป็นแฟนตัวยงของ\nตัวละครกบ <เกโคตะ> อีกด้วย"
10079-CharacterSSRNewTh = "มาอยู่ที่นี่ก็เจอเรื่องยุ่งยากเหมือนเดิมเลยจริงๆ"
