[translation]
10071-StatusMessageTw = "用結果來證明"
10071-FullNameTw = "月雪都子"
10071-FamilyNameTw = "月雪"
10071-PersonalNameTw = "都子"
10071-SchoolYearTw = "1年級"
10071-CharacterAgeTw = "15歲"
10071-BirthdayTw = "1月7日"
10071-HobbyTw = "動物影片鑑賞"
10071-WeaponNameTw = "RABBIT-31式短機關槍"
10071-WeaponDescTw = "都子被SRT特殊學園配給的制式衝鋒槍。\n\n是把以高可靠度聞名的槍，在高溫潮濕的海邊也能有效率地完成作戰。"
10071-ProfileIntroductionTw = "為了潛入作戰而造訪漁村的SRT特殊學園所屬，RABBIT小隊的小隊長。\n\n為了調查蝦子從便利商店的便當消失的原因而換上了泳裝。儘管潛入地點的漁村是個與觀光相去甚遠的可疑場所，似乎依然無法捨棄可愛的泳裝。"
10071-CharacterSSRNewTw = "這裡是RABBIT1。\n已經抵達海邊"
