[translation]
10077-StatusMessageEn = "The Justice Task Force's door is always open!"
10077-FullNameEn = "Nakamasa Ichika"
10077-FamilyNameEn = "Nakamasa"
10077-PersonalNameEn = "Ichika"
10077-SchoolYearEn = "2nd Year"
10077-CharacterAgeEn = "16 years old"
10077-BirthdayEn = "November 11th"
10077-HobbyEn = "Helping others and trying new things"
10077-WeaponNameEn = "Red Dragon"
10077-WeaponDescEn = "Ichika and this assault rifle have been together through thick and thin.\n\nDespite its unassuming appearance, it is capable of unleashing intense power."
10077-ProfileIntroductionEn = "A member of the Justice Task Force with a relaxed demeanor.\n\nAs a member of the task force, she excels at promoting cooperation and coordination. She's even on good terms with the students of the other academies. While she is known for her easy-going demeanor and friendliness, these traits don't come naturally to her and require a lot of work. "
10077-CharacterSSRNewEn = "Oh? It's not time for us to meet yet, is it? Were you waiting?"
