[translation]
10084-StatusMessageTw = "我正傾聽你的聲音"
10084-FullNameTw = "音瀬小玉"
10084-FamilyNameTw = "音瀬"
10084-PersonalNameTw = "小玉"
10084-SchoolYearTw = "3年級"
10084-CharacterAgeTw = "17歲"
10084-BirthdayTw = "1月5日"
10084-HobbyTw = "無線通訊、竊聽"
10084-WeaponNameTw = "Echo Link"
10084-WeaponDescTw = "小玉隨身攜帶的手槍。\n\n這把手槍能將擊發的聲響抑制到極限，即使在寧靜的山中，也能在不引起野生動物警戒的情況下執行作戰。"
10084-ProfileIntroductionTw = "適逢寒冬而換上溫暖衣物的貝里塔斯的成員。\n\n在千尋的勸說下勉強來到戶外，但在想到這是能錄製平常很難錄到的環境音的難得機會後顯得有點興奮。雖然喜歡能在自然環境中錄到的各種聲音，但最喜歡的果然還是老師的聲音。"
10084-CharacterSSRNewTw = "我一直在等待老師的腳步聲靠近"
