[translation]
10086-FullNameTw = "空崎陽奈"
10086-FamilyNameTw = "空崎"
10086-PersonalNameTw = "陽奈"
10086-SchoolYearTw = "3年級"
10086-CharacterAgeTw = "17歲"
10086-BirthdayTw = "2月19日"
10086-HobbyTw = "睡眠、休息"
10086-WeaponNameTw = "終幕：Destroyer"
10086-WeaponDescTw = "陽奈視同手足的多功能機關槍。\n\n平時只要有人違反校規或擾亂風紀，就會無差別地進行連坐處罰，相當冷酷無情的物品。不過這次特別蘊含著對自己的嚴格要求，以及對某個人的心意。"
10086-ProfileIntroductionTw = "為了參加派對特別換上禮服，格黑娜學園所屬的風紀委員長。\n\n雖然是任何事都嫌麻煩的怕麻煩少女，不過一聽老師說很期待格黑娜特別派對，便下定決心要比平常稍微努力一點。一有空就會認真練習要獻給老師的鋼琴演奏，散發出比平時更加青澀純真的少女心，但本人並沒有意識到這件事。"
10086-CharacterSSRNewTw = "為了你，我會努力"
