[translation]
10085-StatusMessageTh = "กำลังปรับอาเธน่า 3 / ระวังสแปม"
10085-FullNameTh = "โอมาการิ ฮาเระ"
10085-FamilyNameTh = "โอมาการิ"
10085-PersonalNameTh = "ฮาเระ"
10085-SchoolYearTh = "ชั้นปีที่ 2"
10085-CharacterAgeTh = "16 ปี"
10085-BirthdayTh = "19 เม.ย."
10085-HobbyTh = "เล่นเกม, ดูหนัง"
10085-WeaponNameTh = "Auto Aimer"
10085-WeaponDescTh = "ปืนไรเฟิลจู่โจมแบบบุลพัปที่ฮาเระใช้\n\nมีฟังก์ชั่นจุดไฟที่ทำให้สามารถจุดไฟได้ง่ายๆ แม้อยู่กลางแจ้ง พร้อมอุปกรณ์ช่วยเล็งเป้าอัตโนมัติเมื่อมีสัตว์ดุร้ายปรากฏตัว แต่พอหมีโผล่มาจริงๆ ก็ตกใจและใช้ปืนได้ไม่เต็มประสิทธิภาพ"
10085-ProfileIntroductionTh = "สมาชิกเวอริทัสที่แต่งตัวอย่างอบอุ่นรับฤดูหนาว\n\nหลังจากอยู่แต่ในอาคารที่สะดวกสบายมานาน เธอก็ได้ออกมายังที่ตั้ง\nแคมป์ที่แทบจะไม่มีสัญญาณอินเทอร์เน็ต พลังงานเลยลดลงกว่าปกติ เธอพอรับมือต่อความไม่สะดวกสบายส่วนใหญ่ที่จะเจอกลางแจ้งได้ แต่อย่างเดียวที่รับมือไม่ได้คือการไม่ดื่มเครื่องชูกำลัง"
10085-CharacterSSRNewTh = "ต่อให้จะหนาวแค่ไหน\nแต่มอนสเตอร์แม็กซ์ก็ต้องกินแบบเย็นๆ"
