[translation]
10086-FullNameTh = "โซระซากิ ฮินะ"
10086-FamilyNameTh = "โซระซากิ"
10086-PersonalNameTh = "ฮินะ"
10086-SchoolYearTh = "ชั้นปีที่ 3"
10086-CharacterAgeTh = "17 ปี"
10086-BirthdayTh = "19 ก.พ."
10086-HobbyTh = "พักผ่อน, นอนหลับ"
10086-WeaponNameTh = "Destroyer of Denouement"
10086-WeaponDescTh = "ปืนกลอเนกประสงค์ที่เป็นเหมือนอวัยวะส่วนหนึ่งของฮินะ\n\nเดิมทีเป็นสิ่งที่แสดงให้เห็นถึงความน่ากลัวของการถูกลงโทษ\nเมื่อฝ่าฝืนกฎและทำลายความสงบภายในโรงเรียน แต่ครั้งนี้\nเป็นสิ่งที่ใช้เพิ่มความเข้มงวดต่อตนเอง เพื่อทุ่มเททำ\nบางอย่างให้ใครบางคน"
10086-ProfileIntroductionTh = "ประธานคณะกรรมการวินัยเกเฮนน่าที่เปลี่ยนเป็นชุดเดรส\nเพื่อเข้าร่วมงานปาร์ตี้\n\nถึงเธอจะเป็นเด็กสาวจอมเกียจคร้าน แต่เมื่อได้ยินว่าคุณครูกำลังตั้งตารอ\nงานปาร์ตี้สุดพิเศษแห่งเกเฮนน่าอย่างมาก ทำให้เธอตั้งใจมากกว่าปกติ\nเล็กน้อยในเวลาว่าง เธอจึงหมั่นฝึกซ้อมการแสดงเปียโนเพื่อคุณครู ความมุ่งมั่นทุ่มเททำให้จิตวิญญาณสาวน้อยของเธอค่อยๆ ผลิบานอย่างช้าๆ โดยที่ตนเองไม่รู้ตัว"
10086-CharacterSSRNewTh = "ฉันจะพยายาม... เพื่อคุณ"
