[translation]
10084-StatusMessageTh = "ฉันกำลังตั้งใจฟังคุณอยู่ค่ะ"
10084-FullNameTh = "โอโทเซะ โคทามะ"
10084-FamilyNameTh = "โอโทเซะ"
10084-PersonalNameTh = "โคทามะ"
10084-SchoolYearTh = "ชั้นปีที่ 3"
10084-CharacterAgeTh = "17 ปี"
10084-BirthdayTh = "5 ม.ค."
10084-HobbyTh = "สื่อสารไร้สาย, ดักฟัง"
10084-WeaponNameTh = "Echo Link"
10084-WeaponDescTh = "ปืนพกที่โคทามะพกติดตัวอยู่ตลอดเวลา\n\nปืนพกกระบอกนี้เก็บเสียงเมื่อยิงได้ถึงขีดสุด แม้อยู่ในภูเขาที่เงียบสงบก็สามารถใช้ได้ โดยไม่ทำให้พวกสัตว์ป่าตื่นกลัว"
10084-ProfileIntroductionTh = "สมาชิกเวอริทัสที่เปลี่ยนมาใส่ชุดที่อบอุ่นรับฤดูหนาว\n\nเธอออกมาข้างนอกด้วยการชักชวนเชิงบังคับจากจิฮิโระ แต่เมื่อคิดว่า\nนี่เป็นโอกาสหายากที่จะได้บันทึกเสียง ASMR ที่หาบันทึกได้ไม่ง่ายใน\nชีวิตประจำวัน เธอก็ตื่นเต้นอยู่หน่อยๆ\nโคทามะชอบเสียงทุกชนิดในธรรมชาติที่สามารถบันทึกได้ แต่เสียงที่\nชอบที่สุดคือเสียงพูดของคุณครู"
10084-CharacterSSRNewTh = "ฉันกำลังฟังเสียงฝีเท้า\nที่เข้ามาใกล้ขึ้นเรื่อยๆ ของคุณครูอยู่ค่ะ"
