[translation]
10096-StatusMessageEn = "Service, sensitivity, and sincerity."
10096-FullNameEn = "Ogata Kanna"
10096-FamilyNameEn = "Ogata"
10096-PersonalNameEn = "Kanna"
10096-SchoolYearEn = "3rd Year"
10096-CharacterAgeEn = "17 years old"
10096-BirthdayEn = "September 7th"
10096-HobbyEn = "Consuming detective-themed media"
10096-WeaponNameEn = "Valkyrie Service Pistol No.17"
10096-WeaponDescEn = "Kanna's service pistol from the Valkyrie Police School. It has been carefully waterproofed for field use."
10096-ProfileIntroductionEn = "Director of the Public Peace Bureau at the Valkyrie Police School, dispatched as a lifeguard.\n\nHer quick judgment, situational awareness, and swimming skills are all above average, but her distinctively fierce appearance makes public interactions challenging."
10096-CharacterSSRNewEn = "In case of an emergency, contact me immediately. I'll be there in a flash."
