[translation]
10097-StatusMessageTh = "ต้องใช้มิสไซล์... มิสไซล์อันใหญ่ๆ..."
10097-FullNameTh = "คาเซะคุระ โมเอะ"
10097-FamilyNameTh = "คาเซะคุระ"
10097-PersonalNameTh = "โมเอะ"
10097-SchoolYearTh = "ชั้นปีที่ 1"
10097-CharacterAgeTh = "15 ปี"
10097-BirthdayTh = "13 ก.ย."
10097-HobbyTh = "เล่นดอกไม้ไฟ"
10097-WeaponNameTh = "RABBIT Type 224 Pistol"
10097-WeaponDescTh = "ปืนพกรุ่นมาตรฐานที่โมเอะได้รับมาจากสถาบันพิเศษ SRT\n\nเฟรมทำมาจากโลหะผสมโมลิบดีนัมที่ทนทาน สามารถยิงติดต่อกันได้อย่างรวดเร็ว แม้อยู่ในชายหาดที่มีอุณหภูมิและความชื้นสูง"
10097-ProfileIntroductionTh = "โอเปอเรเตอร์ของกองทหาร RABBIT ที่มาทำปฏิบัติการแฝงตัวในหมู่บ้าน\nชาวประมงที่อยู่ห่างไกล\n\nเธอตื่นเต้นที่จะได้ทดสอบการใช้อาวุธหลายๆ แบบในสภาพแวดล้อมที่ต่าง\nจากปกติ ในครั้งนี้โมเอะใส่ชุดว่ายน้ำในดีไซน์ที่แตกต่างจากสมาชิกคนอื่น แต่เธอบอกว่านี่เป็นส่วนหนึ่งของความพินาศที่ศัตรูต้องเจอ"
10097-CharacterSSRNewTh = "นี่คือ RABBIT 3\nสรุปว่าจะให้ใช้มิสไซล์ได้ตอนไหนน่ะ?"
