[translation]
10097-StatusMessageTw = "需要導彈……超大的導彈……"
10097-FullNameTw = "風倉萌"
10097-FamilyNameTw = "風倉"
10097-PersonalNameTw = "萌"
10097-SchoolYearTw = "1年級"
10097-CharacterAgeTw = "15歲"
10097-BirthdayTw = "9月13日"
10097-HobbyTw = "煙火"
10097-WeaponNameTw = "RABBIT-224式手槍"
10097-WeaponDescTw = "SRT特殊學園配發給萌的制式手槍。\n\n外框以堅硬的鉬合金製成，即使在高溫潮濕的海邊也能快速連續射擊。"
10097-ProfileIntroductionTw = "為了潛入作戰而造訪漁村的SRT特殊學園所屬，RABBIT小隊的報務員。\n\n因為能在和平時截然不同的環境下測試武器而顯得十分興奮。與其他小隊成員不同，身穿的泳裝帶著幾分危險的氣息，但他本人表示這也是毀滅的一環。"
10097-CharacterSSRNewTw = "這裡是RABBIT3。\n可以發射導彈嗎～？"
