[translation]
10095-StatusMessageJp = "I'll put in my all today as well."
10095-FullNameJp = "Saiba Midori"
10095-FamilyNameJp = "Saiba"
10095-PersonalNameJp = "Midori"
10095-SchoolYearJp = "1st Year"
10095-CharacterAgeJp = "15 years old"
10095-BirthdayJp = "December 8th"
10095-HobbyJp = "Drawing"
10095-WeaponNameJp = "Fresh Inspiration"
10095-WeaponDescJp = "Midori's rifle.\n\nShe claims she has to carry the perfect gun to become the perfect maid."
10095-ProfileIntroductionJp = "Illustrator for the Game Development Department at Millennium Science School, currently in disguise as a C&C member.\n\nDespite claiming that she wore the maid uniform entirely against her will, since the situation is what it is, she treats her duty with diligence. "
10095-CharacterSSRNewJp = "If I have to, I can be the perfect maid. Please look forward to it, Master."
