[translation]
10105-StatusMessageTh = "ขอให้พลังจงสถิตอยู่กับเพลงนี้"
10105-FullNameTh = "อิโอจิ มารี"
10105-FamilyNameTh = "อิโอจิ"
10105-PersonalNameTh = "มารี"
10105-SchoolYearTh = "ชั้นปีที่ 1"
10105-CharacterAgeTh = "15 ปี"
10105-BirthdayTh = "12 ก.ย."
10105-HobbyTh = "สวดภาวนา, การคิดไตร่ตรอง"
10105-WeaponNameTh = "Piety"
10105-WeaponDescTh = "ปืนพกที่มารีพกติดตัวไว้แม้ตอนนี้เธอจะเป็นไอดอล\n\nมาพร้อมดีไซน์ที่มีเอกลักษณ์ เข้ากับชุดไอดอลเหมือนเป็นเซ็ตเดียวกัน"
10105-ProfileIntroductionTh = "หัวหน้าวงไอดอล <แอนทีก เซราฟิม> แห่งทรีนิตี้\n\nมารีเริ่มทุกอย่างจากความต้องการที่จะช่วยเหลือคนอื่นเท่านั้น แต่สุดท้ายก็ได้กลายเป็นไอดอลที่ไปยืนร้องเพลงบนเวทีขึ้นมาจริงๆ แม้ในตอนที่ไม่ได้ใส่ชุดไอดอล เธอก็ยังมี \"ความพยายามเพื่อ\nทำให้ทุกคนสนุก\" ซึ่งนี่อาจเป็นพรสวรรค์ 'ไอดอล' ในตัวเธอก็ได้"
10105-CharacterSSRNewTh = "ที่จริง... ฉันก็ใฝ่ฝันอยากเป็นไอดอลค่ะ"
