[translation]
10100-StatusMessageTh = "เปิดตี้ปั่นจักรยาน... (2/5)"
10100-FullNameTh = "สึนาโอกามิ ชิโรโกะ "
10100-FamilyNameTh = "สึนาโอกามิ"
10100-PersonalNameTh = "ชิโรโกะ"
10100-SchoolYearTh = "ชั้นปีที่ 3"
10100-CharacterAgeTh = "17 ปี"
10100-BirthdayTh = "16 พ.ค."
10100-HobbyTh = "วิ่งจ็อกกิ้ง, ฝึกร่างกาย, ปั่นจักรยาน"
10100-WeaponNameTh = "BLACK FANG 465"
10100-WeaponDescTh = "ปืนไรเฟิลจู่โจมที่ชิโรโกะใช้เป็นประจำ\n\nมีร่องรอยการซ่อมแซมอยู่หลายจุดเพราะผ่านการใช้งานมานาน แต่ก็ได้รับการบำรุงรักษาอย่างดี จึงใช้งานได้อย่างไม่มีปัญหา"
10100-ProfileIntroductionTh = "ชิโรโกะจากโลกอื่นที่เข้ามายังโลกนี้พร้อมกับเพลนาพาเทส\n\nเธอคือตัวตนเดียวกับชิโรโกะที่อยู่ในโลกนี้ แต่ก็เป็นตัวตนในอนาคตที่โต\nกว่าปัจจุบัน เธอหวงแหนอะบิดอสไม่ต่างจากชิโรโกะในโลกนี้ และบางครั้ง\nก็จะแสดงด้านที่คาดไม่ถึงออกมาเพื่อฟื้นฟูโรงเรียนและเขตปกครองตนเอง"
10100-CharacterSSRNewTh = "บางทีฉันเองก็อาจจะ...\nไม่เป็นอะไรก็ได้  "
