[translation]
10109-StatusMessageJp = "Beyond the darkness"
10109-FullNameJp = "Ushio Noa"
10109-FamilyNameJp = "Ushio"
10109-PersonalNameJp = "Noa"
10109-SchoolYearJp = "2nd Year"
10109-CharacterAgeJp = "16 years old"
10109-BirthdayJp = "April 13th"
10109-HobbyJp = "Reading, recitation"
10109-WeaponNameJp = "Secretary on Record"
10109-WeaponDescJp = "A pistol equipped with Noa's conversion kit. This multi-use pistol is perfect for both weighing down papers and late-night reading, Noa's favorite pastime."
10109-ProfileIntroductionJp = "Seminar's secretary, who's put on pajamas to enjoy a cozy rest. This secretary's holidays are usually quiet, as she tends to operate in solitude. However, the moments she spends with other Seminar members are the exception. No matter how ridiculous the commotions and misunderstandings her adorable underclassmen and warm-hearted colleagues cause, Noa silently watches and records the scenes, always accompanied by a light smile."
10109-CharacterSSRNewJp = "Darkness has no color..."
