[translation]
10112-StatusMessageEn = "Being the best guide for you!"
10112-FullNameEn = "Ichinose Asuna"
10112-FamilyNameEn = "Ichinose"
10112-PersonalNameEn = "Asuna"
10112-SchoolYearEn = "3rd Year"
10112-CharacterAgeEn = "17 years old"
10112-BirthdayEn = "March 24th"
10112-HobbyEn = "Carrying out assaults"
10112-WeaponNameEn = "Surprise Party"
10112-WeaponDescEn = "Asuna's assault rifle.\n\nThe name is quite lively, though unrelated to the mission."
10112-ProfileIntroductionEn = "A C&C Agent deployed to help facilitate the Millennium Expo.\n\nHaving changed into a school uniform, she works as both an event guide and a security officer. Her unpredictable actions and unique, cheerful personality make her very popular as a guide."
10112-CharacterSSRNewEn = "Let's do lots of fun things!"
