[translation]
10117-StatusMessageTh = "↑↑↓↓←→←→"
10117-FullNameTh = "ทาจิบานะ ฮิคาริ"
10117-FamilyNameTh = "ทาจิบานะ"
10117-PersonalNameTh = "ฮิคาริ"
10117-SchoolYearTh = "ชั้นปีที่ 1"
10117-CharacterAgeTh = "15 ปี"
10117-BirthdayTh = "14 มิ.ย."
10117-HobbyTh = "ฝึกขับรถไฟแบบประหลาดๆ, สังเกตมด"
10117-WeaponNameTh = "Ticket Punch"
10117-WeaponDescTh = "ปืนพกของฮิคาริ มาพร้อมประสิทธิภาพเต็มเปี่ยมในการ\nรับมือผู้โดยสารไร้มารยาทที่ก่อความวุ่นวายบนรถไฟ\n\nน่าแปลกใจที่ได้รับการบำรุงรักษาให้สะอาดเกลี้ยงเกลาอยู่ตลอด"
10117-ProfileIntroductionTh = "ผู้บริหารสังกัดศูนย์ควบคุมกลางแห่งสถาบันการรถไฟไฮแลนเดอร์\n\nฮิคาริมีพรสวรรค์เป็นเลิศในการขับรถไฟ จึงได้รับคัดเลือกให้เป็นผู้บริหาร\nร่วมกับโนโซมิ น้องสาวฝาแฝดของเธอ แต่เรื่องงานเอกสารหรืองานบริหาร\nนั้นกลับไม่ได้เรื่องเลย ฮิคาริเป็นคนซื่อสัตย์ต่อความปรารถนาของตัวเอง\nมาก เธอก็เลยมักจะก่อเรื่องสารพัดแบบไม่สนไม่แคร์คนอื่น"
10117-CharacterSSRNewTh = "ฮิคาริมาแล้ว"
