[translation]
10123-StatusMessageTh = "พวกเราเพิ่งตื่นจากเทพนิยาย"
10123-FullNameTh = "ยูริโซโนะ เซอา"
10123-FamilyNameTh = "ยูริโซโนะ"
10123-PersonalNameTh = "เซอา"
10123-SchoolYearTh = "ชั้นปีที่ 3"
10123-CharacterAgeTh = "17 ปี"
10123-BirthdayTh = "29 ก.ย."
10123-HobbyTh = "ไขปริศนา, อ่านหนังสือ"
10123-WeaponNameTh = "Keen Illumination"
10123-WeaponDescTh = "ปืนพกที่เซอาใช้เป็นประจำ\n\nแม้จะอยู่ในเสื้อผ้าที่สบายตัวมากขึ้น แต่ศิลปะในการพูด และอานุภาพในการยิงอันเป็นเอกลักษณ์ก็ไม่ถดถอย มาพร้อมรูปลักษณ์ใหม่และวิธีทำลายล้างอย่างกล้าหาญ"
10123-ProfileIntroductionTh = "สมาชิกสภาน้ำชาและหัวหน้ากลุ่ม <ซางตุส> ที่ปลีกตัวมาใช้ช่วง\nวันหยุดฤดูร้อนอย่างอิสระ\n\nด้วยบุคลิกที่เป็นคนปรับตัวเร็ว จึงวางภาระความรับผิดชอบและความ\nตั้งใจในฐานะสภาน้ำชาแล้วมาผ่อนคลายได้อย่างเต็มที่ เซอาเลือก\nที่จะไม่ข่มใจตัวเองเป็นพิเศษ ในช่วงวันหยุดนี้และทำพฤติกรรมที่\nถือว่าผิดปกติสำหรับเธอ จนผู้คนรอบข้างรู้สึกประหลาดใจ"
10123-CharacterSSRNewTh = "ฮุฮุ สิ่งที่เปลี่ยนไปไม่ได้มีแค่รูปลักษณ์ภายนอกนะคะ"
