[translation]
10121-StatusMessageEn = "It's my summer sea debut!"
10121-FullNameEn = "Kadenokouji Yukari"
10121-FamilyNameEn = "Kadenokouji"
10121-PersonalNameEn = "Yukari"
10121-SchoolYearEn = "1st Year"
10121-CharacterAgeEn = "15 years old"
10121-BirthdayEn = "June 16th"
10121-HobbyEn = "Praying, finding new snacks"
10121-WeaponNameEn = "Hyakkaryouran Rifle - A Girl's Determination"
10121-WeaponDescEn = "Yukari's standard-issue Hyakkaryouran rifle.\n\nIt's her most precious possession, so she's thoroughly waterproofed it."
10121-ProfileIntroductionEn = "A member of the Hyakkaryouran Resolution Council who is ready for the summer!\n\nShe's thrilled to be attending the Hyakkiyako Water Festival with her favorite seniors. Even at the beach, her boundless energy and bright personality shine through."
10121-CharacterSSRNewEn = "I'll shall be perfectly perfect, even at the beach!"
