[translation]
10132-StatusMessageTw = "終有一天，我會成為當之無愧的忍者！"
10132-FullNameTw = "大野月夜"
10132-FamilyNameTw = "大野"
10132-PersonalNameTw = "月夜"
10132-SchoolYearTw = "1年級"
10132-CharacterAgeTw = "15歲"
10132-BirthdayTw = "4月5日"
10132-HobbyTw = "替身術、隱藏氣息"
10132-WeaponNameTw = "月夜流衝鋒槍"
10132-WeaponDescTw = "月夜珍視的衝鋒槍。即使帶著它登上舞台，也沒有另外特別裝飾。\n\n因為三千留和伊樹菜幫忙裝飾的每一個部分，已經讓它比任何東西都更美麗。"
10132-ProfileIntroductionTw = "百鬼夜行聯合學園所屬，忍術研究部的成員。\n\n受僱擔任時裝秀的保鑣，沒想到竟意外成為模特兒出道。原本一直是心結的身高，在模特兒業界反而成了優勢。因此為了兼顧模特兒和社團活動而感到左右為難。"
10132-CharacterSSRNewTw = "我、我真的\n有當模特兒的才能嗎……？"
