[translation]
13000-StatusMessageEn = "Enjoying some hot tea."
13000-FullNameEn = "Murokasa Akane"
13000-FamilyNameEn = "Murokasa"
13000-PersonalNameEn = "Akane"
13000-SchoolYearEn = "2nd Year"
13000-CharacterAgeEn = "16 years old"
13000-BirthdayEn = "April 1st"
13000-HobbyEn = "Cleaning"
13000-WeaponNameEn = "Silent Solution"
13000-WeaponDescEn = "A pistol that Akane always carries with her.\n\nIt contrasts with the explosives she usually uses, AKA the \"Noisy Solution\"."
13000-ProfileIntroductionEn = "An agent of C&C, a secret organization of the Millennium School. Akane operates under the call sign Zero-Three. She became known as the Master Cleaner for her modus operandi of infiltrating the enemy camp and clearing it out with explosives, all while wearing her signature gentle smile."
