[translation]
13003-StatusMessageTw = "減肥中……"
13003-FullNameTw = "羽川蓮實"
13003-FamilyNameTw = "羽川"
13003-PersonalNameTw = "蓮實"
13003-SchoolYearTw = "3年級"
13003-CharacterAgeTw = "17歲"
13003-BirthdayTw = "12月12日"
13003-HobbyTw = "讀書、觀察人類"
13003-WeaponNameTw = "Impalement"
13003-WeaponDescTw = "蓮實喜歡的狙擊步槍。\n\n修長且古典的外觀以及與之相反的強大威力跟主人如出一轍。"
13003-ProfileIntroductionTw = "三一綜合學園所屬，實現正義部的第二把交椅。\n\n代替象徵狂亂的部長弦生，擔任實現正義部的戰術指揮官。\n因此，雖然第一眼看起來是沉穩知性、「這就是三一的學生」的模範學生，但他也毫無疑問是實現正義部的一員。\n比任何人都冷靜，偶爾也會做出魯莽的舉動。"
