[translation]
13009-StatusMessageTw = "好睏……"
13009-FullNameTw = "春日椿"
13009-FamilyNameTw = "春日"
13009-PersonalNameTw = "椿"
13009-SchoolYearTw = "2年級"
13009-CharacterAgeTw = "16歲"
13009-BirthdayTw = "2月3日"
13009-HobbyTw = "午睡"
13009-WeaponNameTw = "安眠的同伴Ⅱ"
13009-WeaponDescTw = "椿所使用的衝鋒槍。\n\n選擇了小巧便攜的尺寸，以免妨礙平日的修行。\n順帶一提，安眠的同伴Ｉ是裝在盾牌裡的枕頭。"
13009-ProfileIntroductionTw = "百鬼夜行聯合學園所屬，修行部的部長。\n\n平常修行的目的就是為了「睡得更安穩、更完全地熟睡」。因此無論坐著還是站著，甚至連用餐時都能邊吃邊睡。\n綽號為「睡美人」。雖然總是一副在打瞌睡的樣子，但是一到了晚上，就會為了保護大街而暗中活躍。"
