[translation]
13002-StatusMessageEn = "Looking 4 buffet recs"
13002-FullNameEn = "Wanibuchi Akari"
13002-FamilyNameEn = "Wanibuchi"
13002-PersonalNameEn = "Akari"
13002-SchoolYearEn = "3rd Year"
13002-CharacterAgeEn = "17 years old"
13002-BirthdayEn = "December 9th"
13002-HobbyEn = "Eating contests"
13002-WeaponNameEn = "Mark of Gluttony"
13002-WeaponDescEn = "Akari's favorite assault rifle.\n\nThis greedy glutton's assault rifle has various firearm accessories, including a grenade launcher."
13002-ProfileIntroductionEn = "A member of the Gehenna Gourmet Research Society.\n\nDon't let her charming appearance fool you. A glutton with a massive appetite, she's the reigning champion of various competitive eating contests across Kivotos. She possesses a mild-mannered and kind personality, but she can prank as well as any other student at Gehenna Academy."
