[translation]
13002-StatusMessageJp = "Looking 4 buffet recs"
13002-FullNameJp = "Wanibuchi Akari"
13002-FamilyNameJp = "Wanibuchi"
13002-PersonalNameJp = "Akari"
13002-SchoolYearJp = "3rd Year"
13002-CharacterAgeJp = "17 years old"
13002-BirthdayJp = "December 9th"
13002-HobbyJp = "Eating contests"
13002-WeaponNameJp = "Mark of Gluttony"
13002-WeaponDescJp = "Akari's favorite assault rifle.\n\nThis greedy glutton's assault rifle has various firearm accessories, including a grenade launcher."
13002-ProfileIntroductionJp = "A member of the Gehenna Gourmet Research Society.\n\nDon't let her charming appearance fool you. A glutton with a massive appetite, she's the reigning champion of various competitive eating contests across Kivotos. She possesses a mild-mannered and kind personality, but she can prank as well as any other student at Gehenna Academy."
