[translation]
13004-StatusMessageEn = "Have a great day!"
13004-FullNameEn = "Izayoi Nonomi"
13004-FamilyNameEn = "Izayoi"
13004-PersonalNameEn = "Nonomi"
13004-SchoolYearEn = "2nd Year"
13004-CharacterAgeEn = "16 years old"
13004-BirthdayEn = "September 1st"
13004-HobbyEn = "Shopping"
13004-WeaponNameEn = "Mini No. 5"
13004-WeaponDescEn = "A machine gun used by Nonomi.\n\nContrary to its name, Mini No. 5 is anything but light."
13004-ProfileIntroductionEn = "A member of the Abydos Foreclosure Task Force.\n\nA friendly, pleasant girl that provides the Foreclosure Task Force with much-needed emotional support to balance out the extreme personalities of its other members. Though she doesn't show it, she comes from a wealthy family and pays for nearly all of the Foreclosure Task Force's snacks out of her own pocket."
13004-CharacterSSRNewEn = "Finally, it's time for me to make my move!"
