[translation]
13001-StatusMessageTh = "ถ้าเจอก้อนเมฆก็บอกกันนะ"
13001-FullNameTh = "วาราคุ ชิเซะ"
13001-FamilyNameTh = "วาราคุ"
13001-PersonalNameTh = "ชิเซะ"
13001-SchoolYearTh = "ชั้นปีที่ 2"
13001-CharacterAgeTh = "16 ปี"
13001-BirthdayTh = "13 ก.ค."
13001-HobbyTh = "แต่งกลอนไฮกุ"
13001-WeaponNameTh = "Type 575 Grenade Launcher"
13001-WeaponDescTh = "ปืนยิงระเบิดที่ชิเซะใช้เป็นประจำ\n\nกระสุนปืนที่มีกลอนไฮกุของชิเซะคิดขึ้นสลักเอาไว้\nปัจจุบันมีขายเป็นสินค้าของชมรมหยินหยาง"
13001-ProfileIntroductionTh = "เด็กสาวเดนปาซัง อยู่ในชมรมหยินหยาง ของสหพันธ์เฮียกคิยาโค\n\nเธอชื่นชอบในวัฒนธรรมดั้งเดิม จึงเข้ามาอยู่ในชมรมหยินหยาง บรรยากาศรอบตัวรวมทั้งรูปลักษณ์ของเธอ เหมือนจะแผ่รัศมีความลึกลับพิเศษออกมา เธอจึงเป็นที่อิจฉาในหมู่นักเรียนเฮียกคิยาโค แต่เจ้าตัวไม่รู้ว่าตกเป็นที่อิจฉาอยู่"
