[translation]
13014-StatusMessageTw = "在海邊享受青春吧！"
13014-FullNameTw = "不破蓮華"
13014-FamilyNameTw = "不破"
13014-PersonalNameTw = "蓮華"
13014-SchoolYearTw = "2年級"
13014-CharacterAgeTw = "16歲"
13014-BirthdayTw = "7月23日"
13014-HobbyTw = "輕小說閱讀、鍛鍊"
13014-WeaponNameTw = "百花繚亂制式步槍─青春的火花"
13014-WeaponDescTw = "蓮華愛用的步槍。\n\n只要有值得信賴的戰友在，要奪下祭典的優勝也不成問題。"
13014-ProfileIntroductionTw = "為了迎接夏天而換上泳裝的百鬼夜行聯合學園所屬，百花繚亂紛爭調停委員會的突擊隊長。\n\n為了和部員們一起享受夏日青春而參加了百夜水上祭。其炙熱的勝負欲與燃燒的熱情，任何人都無法阻擋。"
