[translation]
16006-StatusMessageTw = "前往尋找夏天美食之旅！"
16006-FullNameTw = "獅子堂泉"
16006-FamilyNameTw = "獅子堂"
16006-PersonalNameTw = "泉"
16006-SchoolYearTw = "2年級"
16006-CharacterAgeTw = "16歲"
16006-BirthdayTw = "5月11日"
16006-HobbyTw = "製作古怪食物、吃古怪食物"
16006-WeaponNameTw = "Daily Cutlery"
16006-WeaponDescTw = "泉使用的重量級機槍。\n\n為了夏日美食，它能赴湯蹈火，在所不辭！防水性也相當完美。"
16006-ProfileIntroductionTw = "格黑娜學園所屬，在悶熱的夏天仍食欲旺盛的美食研究會貪吃少女。\n\n右手持西瓜，左手拿冰桶。即使如此，為了追求更多的夏日美食，他仍動身來到了海邊。既然是夏天，「巧克力口味的蒲燒鰻魚」、「激辣刨冰」、「沾上薄荷巧克力的西瓜」等季節限定奇怪菜單自然是不能缺少。包含那種獵奇事物在內，追求任何食物的熱情，甚至比夏天的炎熱還更加猛烈。"
