[translation]
16007-StatusMessageEn = "Do you have time to hear about the great Cherino?"
16007-FullNameEn = "Sashiro Tomoe"
16007-FamilyNameEn = "Sashiro"
16007-PersonalNameEn = "Tomoe"
16007-SchoolYearEn = "3rd Year"
16007-CharacterAgeEn = "17 years old"
16007-BirthdayEn = "November 10th"
16007-HobbyEn = "Rallying"
16007-WeaponNameEn = "Vernost"
16007-WeaponDescEn = "A long sniper rifle used by Tomoe.\n\nEquipped with a high-res telescopic sight making it possible to spot targets from afar and dispose of any insubordinate who doubts the authority of President Cherino."
16007-ProfileIntroductionEn = "The chief secretary of the Red Winter Office and President Cherino's closest aide.\n\nA speaking master who can wrap up and deliver just about any message. She gives regular speeches at the academy to inspire loyalty to President Cherino. Cherino believes Tomoe is loyal because she is smitten by her charisma, but in fact, Tomoe simply finds Cherino adorable."
