[translation]
16003-StatusMessageTh = "ขอให้วันนี้เป็นวันที่สงบสุข"
16003-FullNameTh = "โมริซึกิ สึซึมิ"
16003-FamilyNameTh = "โมริซึกิ"
16003-PersonalNameTh = "สึซึมิ"
16003-SchoolYearTh = "ชั้นปีที่ 2"
16003-CharacterAgeTh = "16 ปี"
16003-BirthdayTh = "31 ส.ค."
16003-HobbyTh = "ลาดตระเวน, เดินเล่น"
16003-WeaponNameTh = "Safety"
16003-WeaponDescTh = "ปืนไรเฟิลจู่โจมที่เป็นอาวุธของสึซึมิ\n\nสำหรับสึซึมิที่ออกลาดตระเวนคนเดียวเป็นประจำ อาวุธของเธอนับเป็นคู่หูที่สำคัญของเธอเลยทีเดียว"
16003-ProfileIntroductionTh = "สมาชิกกลุ่มรักษาความสงบ ดูแลความปลอดภัยของนักเรียนทรีนิตี้ \n\nเธอเริ่มออกลาดตระเวนตามถนนอย่างจริงจัง เพราะนักเรียนทรีนิตี้มักถูกนักเรียน จากโรงเรียนอื่นมารังแกอยู่บ่อยๆ\nด้วยบุคลิกที่สุขุมรักในความยุติธรรม เธอถึงถูกเข้าใจผิดว่าเป็นคนเย็นชา แต่แท้จริงแล้วเธอก็มีด้านที่อ่อนโยนเหมือนกัน"
