[translation]
16004-StatusMessageTw = "HAJIMEMASITE！"
16004-FullNameTw = "朝比奈菲娜"
16004-FamilyNameTw = "朝比奈"
16004-PersonalNameTw = "菲娜"
16004-SchoolYearTw = "1年級"
16004-CharacterAgeTw = "17歲"
16004-BirthdayTw = "11月3日"
16004-HobbyTw = "看任俠電影"
16004-WeaponNameTw = "無仁義交互射擊"
16004-WeaponDescTw = "菲娜的持有的機關槍。\n\n彷彿在跳舞一般使用這把槍的菲娜所放出的熱量十分驚人，他本人也表示內心十分翻騰。"
16004-ProfileIntroductionTw = "百鬼夜行聯合學園所屬，對任俠充滿著憧憬的少女。\n\n總是一副開朗爽快的樣子，是能從幫助他人獲得快樂的類型的女孩子。\n對於任俠的知識全都是由電影中獲得，因此各種地方都有些奇怪……\n是個筆直地朝著心中的任俠之路前進的少女。"
