[translation]
16007-StatusMessageTw = "想了解潔莉諾會長的豐功偉業嗎？"
16007-FullNameTw = "佐城智惠"
16007-FamilyNameTw = "佐城"
16007-PersonalNameTw = "智惠"
16007-SchoolYearTw = "3年級"
16007-CharacterAgeTw = "17歲"
16007-BirthdayTw = "11月10日"
16007-HobbyTw = "煽動"
16007-WeaponNameTw = "忠誠心"
16007-WeaponDescTw = "智惠所使用的狙擊步槍。\n\n裝載著高倍率的瞄具，可以從相當遠的距離找出懷疑潔莉諾會長權威的叛亂分子。"
16007-ProfileIntroductionTw = "赤冬聯邦學園所屬，赤冬事務局的秘書室長同時也是潔莉諾的第一親信。\n\n無論什麼事，只要他說出口都會變成事實的話術達人，定期前往各個地方灌輸對潔莉諾會長的忠誠心。潔莉諾認為智惠是「被自己的魅力感化而有忠誠心」的，但事實上智惠只是盲目地寵愛潔莉諾。"
