[translation]
16008-StatusMessageJp = "Coffee with donuts!"
16008-FullNameJp = "Nemugaki Fubuki"
16008-FamilyNameJp = "Nemugaki"
16008-PersonalNameJp = "Fubuki"
16008-SchoolYearJp = "1st Year"
16008-CharacterAgeJp = "15 years old"
16008-BirthdayJp = "October 21st"
16008-HobbyJp = "Crosswords, radio listening"
16008-WeaponNameJp = "Valkyrie Standard Rifle No. 14"
16008-WeaponDescJp = "A standard rifle that Fubuki received from Valkyrie Police School.\n\nIt's pretty powerful, but it doesn't function properly because Fubuki has neglected to take care of it."
16008-ProfileIntroductionJp = "A laid-back administrative advisor of Valkyrie Police School.\n\nShe entered Valkyrie longing for a laid-back, easygoing life as a civil servant. She remains negligent, enjoying life as it is without being swayed by money or fame even when a case is sent to the Public Safety Bureau. Her favorite activity is eating donuts while listening to the radio."
