[translation]
16012-StatusMessageJp = "Don't bother me while I'm eating!"
16012-FullNameJp = "Akashi Junko"
16012-FamilyNameJp = "Akashi"
16012-PersonalNameJp = "Junko"
16012-SchoolYearJp = "1st Year"
16012-CharacterAgeJp = "15 years old"
16012-BirthdayJp = "December 27th"
16012-HobbyJp = "Food touring"
16012-WeaponNameJp = "Diner's Outlaw"
16012-WeaponDescJp = "Two assault rifles wielded by Junko.\n\nThey punish anyone who dares to get in the way of their owner's enjoyment of gourmet food."
16012-ProfileIntroductionJp = "Junko is wearing a kimono for the new year.\n\nShe went through the trouble of putting on a new outfit, and has been looking forward to New Year's food. Once she starts eating, she won't tolerate interruption."
