[translation]
16010-StatusMessageEn = "I really wish we had more time to practice..."
16010-FullNameEn = "Nekozuka Hibiki"
16010-FamilyNameEn = "Nekozuka"
16010-PersonalNameEn = "Hibiki"
16010-SchoolYearEn = "1st Year"
16010-CharacterAgeEn = "15 years old"
16010-BirthdayEn = "April 2nd"
16010-HobbyEn = "Cosplay, shopping"
16010-WeaponNameEn = "Fancy Light"
16010-WeaponDescEn = "Hibiki's favorite mortar.\n\nWhen she's cheering, she puts it in a caddie to make it easier to carry."
16010-ProfileIntroductionEn = "A member of the Engineering Department who puts on a cheerleader outfit for game days.\n\nHibiki's sewing skills are sharp thanks to her love of cosplay, so she designs and makes special event outfits for all the members of the Engineering Department. She made this particular cheerleader outfit a long time ago, so it seems to be a bit small in some places."
