[translation]
16017-StatusMessageJp = "Life is disaster"
16017-FullNameJp = "Utsumi Aoba"
16017-FamilyNameJp = "Utsumi"
16017-PersonalNameJp = "Aoba"
16017-SchoolYearJp = "2nd Year"
16017-CharacterAgeJp = "16 years old"
16017-BirthdayJp = "July 19th"
16017-HobbyJp = "Fantasizing, being passive aggressive"
16017-WeaponNameJp = "Hasty Expectations"
16017-WeaponDescJp = "Aoba's shotgun.\n\nIts name really captures her motto, \"Have no expectations.\" It's well-suited for blasting almost anything out of her way."
16017-ProfileIntroductionJp = "Engineer from Highlander Railroad Academy's Freight Logistics Department.\n\nShe's very shy and introverted but surprisingly has quite the sharp tongue. But it's easy to miss her malevolent messages because of her tendency to mutter them under her breath. She's always suffering from heavy workloads and unfair treatment, so there is no end to her many complaints."
