[translation]
16018-StatusMessageTh = "แก๊งหมวกกันน็อกป๋อมแป๋มรับสมัครสมาชิกจำนวนมาก!"
16018-FullNameTh = "โคะมาคาเสะ ราบุ"
16018-FamilyNameTh = "โคะมาคาเสะ"
16018-PersonalNameTh = "ราบุ"
16018-SchoolYearTh = "ลาออกกลางคัน"
16018-CharacterAgeTh = "16 ปี"
16018-BirthdayTh = "6 พ.ค."
16018-HobbyTh = "เช็ดหมวกกันน็อก, ตรวจค้นใต้ตู้หยอดเหรียญ"
16018-WeaponNameTh = "Pinch Hitter"
16018-WeaponDescTh = "ปืนลูกซองของราบุ\n\nถึงจะถูกกวัดแกว่งเหมือนไม้เบสบอลจนเก่าและสึกหรอ แต่ก็ได้รับการดูแลรักษาอย่างพิถีพิถัน"
16018-ProfileIntroductionTh = "หัวหน้าแก๊งหมวกกันน็อกป๋อมแป๋ม\n\nราบุเป็นหัวหน้าที่ลูกน้องให้ความไว้วางใจ เธอพยายามทำอะไรใหม่ๆ อยู่เสมอ แต่ดูเหมือนว่าโชคจะไม่เข้าข้างนัก"
