[translation]
16016-StatusMessageTw = "請多多支持救護騎士團！"
16016-FullNameTw = "蒼森美禰"
16016-FamilyNameTw = "蒼森"
16016-PersonalNameTw = "美禰"
16016-SchoolYearTw = "3年級"
16016-CharacterAgeTw = "17歲"
16016-BirthdayTw = "11月23日"
16016-HobbyTw = "收集醫療用品"
16016-WeaponNameTw = "救護的證明"
16016-WeaponDescTw = "美禰愛用的散彈槍。\n\n就好比偶像活動是救護騎士團任務的延續一般，或許這把槍也同樣是偶像道具的延續。"
16016-ProfileIntroductionTw = "三一綜合學園所屬，偶像團體「Antique Seraphim」的成員。\n\n為了成為更加貼近大眾的救護騎士團團長，自願參加了偶像活動。儘管其剛正不阿的個性依舊一如既往，但對於自己喜歡可愛事物的一面似乎多少坦率了一些。"
