[translation]
20007-StatusMessageEn = "Get pumped up for the live concert in Kivotos!"
20007-FullNameEn = "Hatsune Miku"
20007-FamilyNameEn = "Hatsune"
20007-PersonalNameEn = "Miku"
20007-CharacterAgeEn = "16 years old"
20007-BirthdayEn = "August 31st"
20007-HobbyEn = "Singing, dancing"
20007-WeaponNameEn = "Concert T-Shirt Cannon"
20007-WeaponDescEn = "A gigantic t-shirt gun Miku uses to launch merchandise into the crowd at concerts.\n\nThere are diodes and other things embedded in the surface, and they sparkle beautifully with her music."
20007-ProfileIntroductionEn = "A virtual idol with a cheerful personality who loves to sing.\n\nOriginally, she only existed virtually online with no physical body, but she came to exist in the real world just in time for her live performance with the help of Kivotos' technology. She has quite a few hidden fans in Kivotos due to her ability to sing across time and space."
20007-CharacterSSRNewEn = "Please listen to my song!"
