[translation]
20009-StatusMessageJp = "There's no such thing as a bad mustache!"
20009-FullNameJp = "Renkawa Cherino"
20009-FamilyNameJp = "Renkawa"
20009-PersonalNameJp = "Cherino"
20009-SchoolYearJp = "3rd Year"
20009-CharacterAgeJp = "Unknown"
20009-BirthdayJp = "October 27th"
20009-HobbyJp = "Doling out demerits, purges, snowball fights"
20009-WeaponNameJp = "Chistka"
20009-WeaponDescJp = "A pistol Cherino uses to purge dissenters.\n\nTomoe modified some of its materials to prevent it from rusting, even in high temperature and humidity."
20009-ProfileIntroductionJp = "The president of Red Winter Federal Academy who came to Hot Springs Resort No. 227 to enjoy a vacation.\n\nAt first, she was planning to demolish the resort that Spec Ops built without her permission, but satisfied with the hospitality of Nodoka and the Spec Ops students, she's decided to extend her stay indefinitely. She doesn't really enjoy getting into the hot springs despite how much she likes resting at the resort and eating its food."
20009-CharacterSSRNewJp = "Kneel before the magnificence of Purginator No. 1!"
