[translation]
20017-StatusMessageEn = "Life is a series of suffering..."
20017-FullNameEn = "Tsuchinaga Hiyori"
20017-FamilyNameEn = "Tsuchinaga"
20017-PersonalNameEn = "Hiyori"
20017-SchoolYearEn = "2nd Year"
20017-CharacterAgeEn = "16 years old"
20017-BirthdayEn = "January 8th"
20017-HobbyEn = "Collecting magazines"
20017-WeaponNameEn = "Identity"
20017-WeaponDescEn = "A massive sniper rifle Hiyori uses.\n\nIts 20mm bullets that accurately target enemies prove their power on the battlefield wherever bullets rain."
20017-ProfileIntroductionEn = "An Arius Squad member that gives a gloomy impression.\n\nHiyori follows other Arius students around, always crying about her latest heavy burden. She has low self-esteem and a negative personality. She tends to be pessimistic about everything in the world, and believes the only purpose of life is suffering."
20017-CharacterSSRNewEn = "Oh, I got lucky today. Heehee..."
