[translation]
20019-StatusMessageTh = "เริ่มต้นวันดีๆ วันใหม่ไปด้วยกัน..."
20019-FullNameTh = "มุโรคาสะ อาคาเนะ"
20019-FamilyNameTh = "มุโรคาสะ"
20019-PersonalNameTh = "อาคาเนะ"
20019-SchoolYearTh = "ชั้นปีที่ 2"
20019-CharacterAgeTh = "16 ปี"
20019-BirthdayTh = "1 เม.ย."
20019-HobbyTh = "ทำความสะอาด"
20019-WeaponNameTh = "Silent Solution"
20019-WeaponDescTh = "ปืนพกที่อาคาเนะพกติดตัวเป็นประจำ\n\nไม่มีอะไรที่เหมาะกับภารกิจแฝงตัวเท่ากับปืนกระบอกนี้แล้ว"
20019-ProfileIntroductionTh = "สายลับของ C&C ที่มาในชุดบันนี่เกิร์ลเพื่อทำภารกิจแฝงตัว\n\nถึงจะอยู่ในสถานการณ์ที่ไม่คุ้นเคย แต่อาคาเนะก็เตรียมตัวอย่างดีสำหรับ\nการปฏิบัติภารกิจแฝงตัวในชุดบันนี่เกิร์ล เช่น การเตรียมระเบิด C4\nสำหรับกำจัดสิ่งกีดขวางต่างๆ แต่ว่าอาจเป็นเพราะใส่ชุดที่ไม่คุ้นเคย\nทำให้เธอรู้สึกตื่นเต้นเล็กน้อย จึงเก็บซ่อนสีหน้าที่เขินอายเอาไว้ไม่มิด"
20019-CharacterSSRNewTh = "สาวใช้ของนายท่าน...\nไม่สิ ตอนนี้ต้องบอกว่า\nเป็นกระต่ายน้อยของนายท่านสินะคะ?"
