[translation]
20029-StatusMessageEn = "I think something good's going to happen today."
20029-FullNameEn = "Mizuha Mimori"
20029-FamilyNameEn = "Mizuha"
20029-PersonalNameEn = "Mimori"
20029-SchoolYearEn = "2nd Year"
20029-CharacterAgeEn = "16 years old"
20029-BirthdayEn = "March 15th"
20029-HobbyEn = "Reading shoujo manga, homemaking"
20029-WeaponNameEn = "Soft Resolution"
20029-WeaponDescEn = "Mimori's automatic pistol.\n\nHer training to become a proper lady never ceases, even when she's at the beach in the summer."
20029-ProfileIntroductionEn = "The vice president of the Inner Discipline Club has changed into a swimsuit for the summer.\n\nShe's known for her gentle smile and kind demeanor, but dressing in swimwear has her a little more excited than usual."
20029-CharacterSSRNewEn = "If only we could freeze this moment in time..."
