[translation]
20028-StatusMessageTh = "อยู่ระหว่างทำงานนอกสถานที่ กรุณาฝากข้อความไว้นะคะ!"
20028-FullNameTh = "วาคาบะ ฮินาตะ"
20028-FamilyNameTh = "วาคาบะ"
20028-PersonalNameTh = "ฮินาตะ"
20028-SchoolYearTh = "ชั้นปีที่ 3"
20028-CharacterAgeTh = "17 ปี"
20028-BirthdayTh = "17 พ.ค."
20028-HobbyTh = "สวดอธิษฐาน, ทำความสะอาด"
20028-WeaponNameTh = "Reverence"
20028-WeaponDescTh = "ปืนพกของฮินาตะที่ไม่เคยอยู่ห่างกายแม้แต่ในฤดูร้อน\n\nส่วนใหญ่จะเอาไว้ใช้ในงานจิปาถะ เช่น เก็บผลไม้\nจากต้นไม้ที่อยู่สูงๆ"
20028-ProfileIntroductionTh = "เด็กสาวจากชมรมซิสเตอร์ที่เดินทางไปยังเกาะเพื่อช่วยเหลือการสำรวจ\nซากโบราณสถาน\n\nถึงจะอยู่ในสถานที่และสถานการณ์ที่ต่างจากปกติ แต่ฮินาตะก็ยังคง\nช่วยเหลือ และดูแลคนรอบข้างอย่างดีเหมือนเดิม ลมทะเลที่พัดเอื่อยๆ บนเกาะ ทำให้ฮินาตะรู้สึกผ่อนคลายขึ้นเล็กน้อยโดยไม่รู้ตัว"
20028-CharacterSSRNewTh = "หนักหรือเปล่าคะ?\nฉันช่วยถือสัมภาระให้มั้ยคะ?"
