[translation]
20030-StatusMessageJp = "The correlation between exercise and gastronomy"
20030-FullNameJp = "Kurodate Haruna"
20030-FamilyNameJp = "Kurodate"
20030-PersonalNameJp = "Haruna"
20030-SchoolYearJp = "3rd Year"
20030-CharacterAgeJp = "17 years old"
20030-BirthdayJp = "March 1st"
20030-HobbyJp = "Foodie touring, making foodie lists"
20030-WeaponNameJp = "Ideal"
20030-WeaponDescJp = "Haruna's sniper rifle.\n\nShe's always scoping out good food, even while exercising."
20030-ProfileIntroductionJp = "Haruna has changed into her gym clothes for the Kivotos Halo Festival.\n\nNo matter where she is, Haruna's quest for food never ends. This time, she's set her eyes on the culinary delights that can only be found at Kivotos' biggest athletic event. Maybe it's because of the excitement in the air, but she seems even more friendly than usual. "
20030-CharacterSSRNewJp = "The more you move, the more appetite you'll work up. Shall we?"
