[translation]
20035-StatusMessageTh = "ถึงจะง่วง... แต่ก็ต้องนำทาง..."
20035-FullNameTh = "คาซึกะ สึบากิ"
20035-FamilyNameTh = "คาซึกะ"
20035-PersonalNameTh = "สึบากิ"
20035-SchoolYearTh = "ชั้นปีที่ 2"
20035-CharacterAgeTh = "16 ปี"
20035-BirthdayTh = "3 ก.พ."
20035-HobbyTh = "นอนกลางวัน"
20035-WeaponNameTh = "Sleeping Companion Ⅱ"
20035-WeaponDescTh = "ปืนกลมือของสึบากิ\n\nปืนขนาดเล็กและสวยงามที่ไม่เป็นอุปสรรคในการฝึกฝน และดูจะมีประโยชน์พอตัวเมื่อมาฝึกเป็นไกด์"
20035-ProfileIntroductionTh = "หัวหน้าชมรมฝึกฝนที่ฝึกการนอนหลับได้ทุกที่ทุกเวลา\n\nเธอได้เริ่มบทบาทใหม่ในฐานะไกด์ทัศนศึกษาในเฮียกคิยาโค แต่การฝึกฝน\nเรื่องการนอนก็เป็นสิ่งที่หยุดไม่ได้อยู่ดี ถึงบางครั้งจะง่วง หรือบางครั้ง\nจะพาเข้าประเด็นอย่างหลักแหลม แต่เธอก็ทำหน้าที่ทั้งสองได้ อย่างไม่บกพร่อง"
20035-CharacterSSRNewTh = "ทุกคน... ทางนี้...\nต่อแถวกันมาเลย..."
