[translation]
20035-StatusMessageTw = "雖然很睏……但要導覽……"
20035-FullNameTw = "春日椿"
20035-FamilyNameTw = "春日"
20035-PersonalNameTw = "椿"
20035-SchoolYearTw = "2年級"
20035-CharacterAgeTw = "16歲"
20035-BirthdayTw = "2月3日"
20035-HobbyTw = "午睡"
20035-WeaponNameTw = "安眠的同伴Ⅱ"
20035-WeaponDescTw = "椿的衝鋒槍。\n\n不會妨礙平日修行的小槍，在擔任導覽員時也能派上大用場。"
20035-ProfileIntroductionTw = "從不停止隨時隨地都能入睡修行的百鬼夜行聯合學園所屬，修行部的部長。\n\n雖然在修學旅行中擔任百鬼夜行的導覽員，似乎仍不打算放棄對睡眠的修行。時而打瞌睡，時而敏銳地指出關鍵，泰然自若地兼顧著兩邊的工作。"
20035-CharacterSSRNewTw = "大家……這邊哦……\n排好隊排好隊……"
