[translation]
20038-StatusMessageTw = "正在休息兼探訪中"
20038-FullNameTw = "佐城智惠"
20038-FamilyNameTw = "佐城"
20038-PersonalNameTw = "智惠"
20038-SchoolYearTw = "3年級"
20038-CharacterAgeTw = "17歲"
20038-BirthdayTw = "11月10日"
20038-HobbyTw = "煽動"
20038-WeaponNameTw = "忠誠心"
20038-WeaponDescTw = "智惠使用的狙擊步槍。\n\n儘管本人聲稱不想在交流會時使用，但也必須視時機和情況而定……"
20038-ProfileIntroductionTw = "為了迎接與山海經的交流會而換上旗袍的赤冬聯邦學園所屬，擔任秘書室長的智惠。\n\n雖然對與赤冬截然不同的山海經的環境感到陌生，依然能快速適應並融入所處的氛圍。\n對於新穿上的服裝比起陌生，更多是感到好奇。在這次的交流會當中，或許也該關注其犀利的口才和敏銳的洞察力。"
20038-CharacterSSRNewTw = "嶄新的土地，新穎的服裝……\n那麼，該從哪裡開始說起呢？"
