[translation]
20041-StatusMessageEn = "Tasklist"
20041-FullNameEn = "Tsukatsuki Rio"
20041-FamilyNameEn = "Tsukatsuki"
20041-PersonalNameEn = "Rio"
20041-SchoolYearEn = "3rd Year"
20041-CharacterAgeEn = "17 years old"
20041-BirthdayEn = "June 6th"
20041-HobbyEn = "Designing"
20041-WeaponNameEn = "Policy Maker"
20041-WeaponDescEn = "Rio's self-defense pistol.\n\nAlthough she's not a particularly good shot, she carries it everywhere with her, reasoning that it would be foolish not to carry a gun in Kivotos."
20041-ProfileIntroductionEn = "President of Seminar, the student council of Millennium School.\n\nHer desires for peace, in Millennium and the world, drive her to do whatever she thinks is necessary. As a result, she became known as everyone's \"big sister.\" Her stylistic and aesthetic tastes are quite unique. Her Avant Guard robot corps, which is known only to a few students, exemplifies those tastes."
20041-CharacterSSRNewEn = "We'll meet again in a place where light doesn't shine."
