[translation]
20045-StatusMessageTw = "今天的導覽員就是我！"
20045-FullNameTw = "朝比奈菲娜"
20045-FamilyNameTw = "朝比奈"
20045-PersonalNameTw = "菲娜"
20045-SchoolYearTw = "1年級"
20045-CharacterAgeTw = "17歲"
20045-BirthdayTw = "11月3日"
20045-HobbyTw = "看任俠電影"
20045-WeaponNameTw = "無仁義交互射擊"
20045-WeaponDescTw = "菲娜的持有的機關槍。\n\n彷彿在跳舞一般使用這把槍的菲娜所放出的熱量十分驚人，他本人也表示內心十分翻騰。"
20045-ProfileIntroductionTw = "百鬼夜行聯合學園所屬，在修學旅行中擔任導覽員的菲娜。\n\n即使成為導覽員，其特有的活潑開朗、積極樂觀的個性依然沒有改變，並將這些特質投入了導覽員的工作之中，是名節慶營運管理部的熱血成員。不過為了避免他將任俠體驗與修學旅行搞混，還是稍微注意一下比較好。"
20045-CharacterSSRNewTw = "任俠，在此登場！"
