[translation]
20053-StatusMessageTw = "「少女忍法帖 小小三千留」禮服特輯上傳完成！"
20053-FullNameTw = "千鳥三千留"
20053-FamilyNameTw = "千鳥"
20053-PersonalNameTw = "三千留"
20053-SchoolYearTw = "3年級"
20053-CharacterAgeTw = "17歲"
20053-BirthdayTw = "2月22日"
20053-HobbyTw = "開發新的自創忍術、影片製作"
20053-WeaponNameTw = "三千留流溢流散彈槍"
20053-WeaponDescTw = "三千留一直愛用的散彈槍。\n\n雖然一向保持備戰狀態，不過這次卻不知為何，似乎與主人一起變得稍微文靜了一點。"
20053-ProfileIntroductionTw = "百鬼夜行聯合學園所屬，忍術研究部的部長。\n\n受僱擔任時裝秀的警備員，因此穿上了禮服。在經歷許多初體驗的同時，努力以忍者的姿態應對。"
20053-CharacterSSRNewTw = "這也是忍者的服裝……！\n請多指教囉！"
