[translation]
20053-StatusMessageTh = "<วิถีนินจาสาว มิจิรุจจี้> ในชุดเดรส อัปโหลดพร้อมให้ชมแล้ว!"
20053-FullNameTh = "จิโดริ มิจิรุ"
20053-FamilyNameTh = "จิโดริ"
20053-PersonalNameTh = "มิจิรุ"
20053-SchoolYearTh = "ชั้นปีที่ 3"
20053-CharacterAgeTh = "17 ปี"
20053-BirthdayTh = "22 ก.พ."
20053-HobbyTh = "คิดค้นวิชานินจาใหม่, ถ่ายวิดีโอ"
20053-WeaponNameTh = "Michiru-Style Overflow Shotgun"
20053-WeaponDescTh = "ปืนลูกซองที่มิจิรุใช้เป็นประจำ\n\nแม้จะอยู่ในสภาวะพร้อมต่อสู้อยู่เสมอ แต่ครั้งนี้ดูเหมือนจะสงบเสงี่ยมลงเล็กน้อยตามเจ้าของ"
20053-ProfileIntroductionTh = "หัวหน้าชมรมวิจัยศาสตร์นินจาของสหพันธ์เฮียกคิยาโค\n\nมิจิรุได้มาใส่ชุดเดรสเพราะถูกว่าจ้างให้เป็นบอดี้การ์ดในงานแฟชั่นโชว์ ถึงจะต้องเผชิญกับสิ่งใหม่ๆ มากมาย แต่มิจิรุก็พยายามรับมือกับสิ่งเหล่านั้น\nให้สมกับการเป็นนินจา"
20053-CharacterSSRNewTh = "นี่ก็เป็นอีกชุดของนินจานะ...!\nฝากติดตามกันด้วยล่ะ!"
