[translation]
23001-StatusMessageEn = "Let today be okay (T_T)"
23001-FullNameEn = "Aikiyo Fuuka"
23001-FamilyNameEn = "Aikiyo"
23001-PersonalNameEn = "Fuuka"
23001-SchoolYearEn = "2nd Year"
23001-CharacterAgeEn = "16 years old"
23001-BirthdayEn = "April 30th"
23001-HobbyEn = "Cooking homestyle dishes, packing bento lunches"
23001-WeaponNameEn = "Lunch Club Defense Gun Type A"
23001-WeaponDescEn = "A submachine gun Fuuka carries everywhere.\n\nIt was originally intended to control the occasional troublemakers in the dining hall, but those troublemakers usually quiet down before Fuuka gets to use it."
23001-ProfileIntroductionEn = "A member of the School Lunch Club that manages Gehenna Academy's dining hall.\n\nA kind and earnest student, making her a bit of a rarity at Gehenna. She prepares and serves hundreds of meals every morning for the students of Gehenna. She's a good cook, but her skills are written off due to the dining hall's lack of manpower. Still, she refuses to give up and is constantly looking for ways to improve the menu."
