[translation]
23003-StatusMessageEn = "DM me if it's important."
23003-FullNameEn = "Omagari Hare"
23003-FamilyNameEn = "Omagari"
23003-PersonalNameEn = "Hare"
23003-SchoolYearEn = "2nd Year"
23003-CharacterAgeEn = "16 years old"
23003-BirthdayEn = "April 19th"
23003-HobbyEn = "Video games, watching movies"
23003-WeaponNameEn = "Auto Aimer"
23003-WeaponDescEn = "An assault rifle used by Hare.\n\nEquipped with various cutting-edge features such as automatic target aiming, but Hare never seems to use them."
23003-ProfileIntroductionEn = "An engineer of Veritas, the hacker group of Millennium Science School.\n\nAn unprecedented genius even amongst the brilliant minds at Millennium. Most of the school's cutting-edge technology was developed by her. Even with all these achievements, she remains humble, friendly, and considerate towards her peers."
