[translation]
23005-StatusMessageTw = "珍惜常識的對策委員會"
23005-FullNameTw = "奥空綾音"
23005-FamilyNameTw = "奥空"
23005-PersonalNameTw = "綾音"
23005-SchoolYearTw = "1年級"
23005-CharacterAgeTw = "15歲"
23005-BirthdayTw = "11月12日"
23005-HobbyTw = "寫家計簿、收集古董"
23005-WeaponNameTw = "Common Sense"
23005-WeaponDescTw = "綾音持有的有著可愛裝飾的手槍。\n\n只要不要在綾音面前反覆作出沒有常識的言行，幾乎沒有見到的機會。"
23005-ProfileIntroductionTw = "阿拜多斯高中所屬，阿拜多斯對策委員會認真的書記。\n\n是重視原則與規定的類型，正為了復興阿拜多斯高中而一心一意地努力著。"
