[translation]
23006-StatusMessageTh = "เรากำลังเปิดร้านเฮียกคิยาโค!"
23006-FullNameTh = "คาวาวะ ชิซุโกะ"
23006-FamilyNameTh = "คาวาวะ"
23006-PersonalNameTh = "ชิซุโกะ"
23006-SchoolYearTh = "ชั้นปีที่ 2"
23006-CharacterAgeTh = "16 ปี"
23006-BirthdayTh = "7 ก.ค."
23006-HobbyTh = "ต้อนรับลูกค้า, แสดงเป็นไอดอล"
23006-WeaponNameTh = "Sakura Bonbon"
23006-WeaponDescTh = "ปืนลูกซองแบบโยนลำ (ปั้มแอ็กชั่น) ที่ชิซุโกะใช้\n\nชิซุโกะบอกว่า \"ปืนนี้เป็นปืนที่มีกลิ่นหอมอ่อนๆ เหมือนกับขนมอันมิตสึขึ้นชื่อของร้านเฮียกคิยาโค และเป็นปืนที่มีกระบอกเดียวในโลก\" "
23006-ProfileIntroductionTh = "หัวหน้าชมรมจัดงานเทศกาล ของสหพันธ์เฮียกคิยาโค\n\nมาสคอตประจำร้านชาดั้งเดิม ของสหพันธ์เฮียกคิยาโค\nปกติเธอจะแสร้งเป็นเด็กโก๊ะๆ ในคราบไอดอล ทำให้เธอยิ่งขายของได้ดี แต่ทั้งหมดก็เป็นแค่การแสดง ความจริงแล้วเธอคือเด็กเจ้าบทบาท ที่ทำงานได้ทุกอย่างเพื่อยอดขายของร้าน และเพื่อความสำเร็จของเทศกาล แต่อย่างไรเธอก็ไม่อาจซ่อนอารมณ์ทางสีหน้าได้ คุณครูกับเพื่อนสนิทของเธอ จึงจับไต๋ได้ทั้งหมด"
