[translation]
26009-StatusMessageJp = "403 Forbidden"
26009-FullNameJp = "Hanaoka Yuzu"
26009-FamilyNameJp = "Hanaoka"
26009-PersonalNameJp = "Yuzu"
26009-SchoolYearJp = "1st Year"
26009-CharacterAgeJp = "16 years old"
26009-BirthdayJp = "August 12th"
26009-HobbyJp = "Making video games"
26009-WeaponNameJp = "Nyan's Dash"
26009-WeaponDescJp = "Yuzu's grenade launcher.\n\nIt had to be designed to be able to fire grenades under any circumstances, considering her habit of trying to fight from the safety of her box."
26009-ProfileIntroductionJp = "The president of the Millennium Game Development Department. She began wearing a maid uniform after being mistaken for a C&C member.\n\nThe new outfit might not have transformed her into an outgoing extrovert, but it did give her the confidence to leave her room! With scary and unfamiliar events occurring all around her, Yuzu does her best to overcome each obstacle with the Game Development Department's support."
