[translation]
26004-StatusMessageJp = "Return by due date pls"
26004-FullNameJp = "Endou Shimiko"
26004-FamilyNameJp = "Endou"
26004-PersonalNameJp = "Shimiko"
26004-SchoolYearJp = "1st Year"
26004-CharacterAgeJp = "15 years old"
26004-BirthdayJp = "November 30th"
26004-HobbyJp = "Reading, making bookmarks"
26004-WeaponNameJp = "Library Ruler"
26004-WeaponDescJp = "A rifle used by Shimiko.\n\nIt's her reliable disciplinary sidekick for when things get rowdy in the library."
26004-ProfileIntroductionJp = "Librarian of the Trinity Library Committee.\n\nA bookworm and a bibliophile, she is one of the few students who has read every single tome in Trinity Library. She loves recommending books as much as she does reading them, and has a habit of making book recommendations to people she's just met based on their preferences."
