[translation]
26015-StatusMessageTw = "因公出差中！"
26015-FullNameTw = "仲正一花"
26015-FamilyNameTw = "仲正"
26015-PersonalNameTw = "一花"
26015-SchoolYearTw = "2年級"
26015-CharacterAgeTw = "16歲"
26015-BirthdayTw = "11月11日"
26015-HobbyTw = "幫助他人、嘗試各種挑戰"
26015-WeaponNameTw = "Red Dragon"
26015-WeaponDescTw = "與一花同甘共苦的突擊步槍。\n\n雖然外觀因勤於保養而顯得整潔，但因為使用方式較為粗獷，槍身各處仍留有損傷痕跡。"
26015-ProfileIntroductionTw = "在海邊也努力保持從容的三一綜合學園所屬，實現正義部的成員。\n\n雖然他一向以親切、從容的形象為人所知，但由於和人生中最棘手的天敵重逢，正面臨著耐心的考驗。或許也正因如此，他的情感表達似乎在無意間比平時更加坦率。"
