[translation]
26014-StatusMessageTh = "อยู่ระหว่างภารกิจพิเศษ"
26014-FullNameTh = "คาคุดาเตะ คาริน"
26014-FamilyNameTh = "คาคุดาเตะ"
26014-PersonalNameTh = "คาริน"
26014-SchoolYearTh = "ชั้นปีที่ 2"
26014-CharacterAgeTh = "16 ปี"
26014-BirthdayTh = "2 ก.พ."
26014-HobbyTh = "ทำความสะอาด"
26014-WeaponNameTh = "Big Eye"
26014-WeaponDescTh = "ปืนไรเฟิลซุ่มยิงประจำตัวของคาริน\n\nสอยทุกเป้าหมายให้ร่วงได้อย่างแม่นยำ"
26014-ProfileIntroductionTh = "สายลับ C&C ที่ถูกส่งมาเป็นไกด์ในงานมิลเลเนียม เอ็กซ์โป\n\nคารินไม่ได้ทำแค่ภารกิจของไกด์ แต่ยังช่วยคุ้มกันนักเรียนในยาม\nฉุกเฉินอีกด้วย แม้จะใส่ชุดนักเรียนธรรมดา แต่เธอก็แอบตื่นเต้น เพราะเป็นชุดที่ไม่ได้ใส่บ่อยนัก เมื่อทำงานของชมรม ความใจดีอัน\nเป็นเอกลักษณ์ทำให้นักเรียนคนอื่นที่ไม่คุ้นเคยกับเธอในตอนแรก\nหันมาสนิทสนมกับเธอได้อย่างรวดเร็ว"
