[translation]
10004-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10004-CVGroup_CharacterGet_Idle1-1 = "Nice to meet you. I'm the head prefect, Hina, though I sincerely hope that went without saying."
10004-CVGroup_Cafe_Idle1-1 = "Cute stuff..."
10004-CVGroup_Cafe_Idle2-1 = "If only I could take a nap..."
10004-CVGroup_Cafe_Idle3-1 = "Thankfully, there are no pressing concerns."
10004-CVGroup_Cafe_Idle4-1 = "You don't mind if I take it easy, do you?"
10004-CVGroup_Cafe_Idle5-1 = "This is a little embarrassing..."
10004-CVGroup_WeaponGet_Idle1-1 = "Every story has an ending. I'll see it through with you."
10004-CVGroup_UIEventFieldMission_Enter1-1 = "Ah, Sensei. There's a whole pile of tasks to be done. I was hoping you'd lend a hand."
10004-CVGroup_UIEventFieldMission_Enter1-2 = "Would you mind helping me out a little bit?"
10004-CVGroup_UIEventFieldMission_Enter2-1 = "Welcome, Sensei."
10004-CVGroup_UIEventFieldMission_Enter2-2 = "The party aside, there's something else I must do as part of the Prefect Team."
10004-CVGroup_UIEventFieldMission_Idle1-1 = "Seems the work is never done, no matter how much you finish."
10004-CVGroup_UIEventFieldMission_Idle1-2 = "Hm? You feel that in your bones? Heehee. So you work a lot, as well..."
10004-CVGroup_UIEventFieldMission_Idle2-1 = "I have no plans to stop working."
10004-CVGroup_UIEventFieldMission_Idle2-2 = "I am Gehenna's head prefect, after all."
10004-CVGroup_UIEventFieldMission_Buy1-1 = "Ah, thank you."
10004-CVGroup_UIEventFieldMission_Buy1-2 = "This is a small gift for your help. Please, take it."
10004-CVGroup_UIEventFieldMission_Buy2-1 = "Perfect. As expected of you, Sensei. I think I can rest easy now..."
10004-CVGroup_UIEventFieldMission_Buy2-2 = "This is a small gift for your help. Here."
10004-CVGroup_UIEventFieldMission_Interaction1-1 = "That's all for today, I suppose. Good job, Sensei."
10004-CVGroup_UIEventFieldMission_Interaction1-2 = "If it's all right... Would you like to grab a cup of tea together?"
