[translation]
10004-CVGroup_UITitle_Idle1-1 = "블루 아카이브"
10004-CVGroup_CharacterGet_Idle1-1 = "선도부장, 히나다. 내 이름은 알고 있겠지만…. 잘 부탁해."
10004-CVGroup_Cafe_Idle1-1 = "귀여운 물건…."
10004-CVGroup_Cafe_Idle2-1 = "낮잠 자고 싶지만…."
10004-CVGroup_Cafe_Idle3-1 = "큰 문제는 없는 것 같네. 다행히."
10004-CVGroup_Cafe_Idle4-1 = "느긋하게 있어도 되겠지?"
10004-CVGroup_Cafe_Idle5-1 = "조금 민망한데…"
10004-CVGroup_WeaponGet_Idle1-1 = "어떤 이야기라도 끝은 있어. 내가 그 마지막까지 지켜봐줄게."
10004-CVGroup_UIEventFieldMission_Enter1-1 = "아, 선생님. 마침 해결해 줬으면 하는 일이 쌓여 있어."
10004-CVGroup_UIEventFieldMission_Enter1-2 = "좀 도와줄 수 있을까?"
10004-CVGroup_UIEventFieldMission_Enter2-1 = "어서 와. 선생님."
10004-CVGroup_UIEventFieldMission_Enter2-2 = "파티와는 별개로 선도부로서 해야 할 일이 있어."
10004-CVGroup_UIEventFieldMission_Idle1-1 = "일이라는 건, 늘 해도해도 끝나지 않는 법이네."
10004-CVGroup_UIEventFieldMission_Idle1-2 = "응? 정말, 진심으로 공감한다고? 후훗, 선생님도 고생이구나…."
10004-CVGroup_UIEventFieldMission_Idle2-1 = "일에서 손을 뗄 생각은 없어."
10004-CVGroup_UIEventFieldMission_Idle2-2 = "나는, 게헨나의 선도부장이니까."
10004-CVGroup_UIEventFieldMission_Buy1-1 = "아, 고마워."
10004-CVGroup_UIEventFieldMission_Buy1-2 = "이건 도와준 답례. 받아줘."
10004-CVGroup_UIEventFieldMission_Buy2-1 = "역시 선생님. 완벽했어. 덕분에 안심할 수 있을 것 같아…."
10004-CVGroup_UIEventFieldMission_Buy2-2 = "이건 도와준 답례야. 자."
10004-CVGroup_UIEventFieldMission_Interaction1-1 = "오늘은 여기까지, 인가. 수고했어. 선생님."
10004-CVGroup_UIEventFieldMission_Interaction1-2 = "괜찮다면…. 잠시 함께 차라도 마시지 않을래?"
