[translation]
10004-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10004-CVGroup_CharacterGet_Idle1-1 = "ฉันคือฮินะ ประธานคณะกรรมการวินัย\nคงจะเคยได้ยินชื่อของฉันมาแล้วใช่มั้ย? ฝากตัวด้วยนะ"
10004-CVGroup_Cafe_Idle1-1 = "ของน่ารักพวกนี้..."
10004-CVGroup_Cafe_Idle2-1 = "อยากนอนกลางวันจัง..."
10004-CVGroup_Cafe_Idle3-1 = "ถือว่าโชคดีที่ไม่มีปัญหาใหญ่อะไร ดีแล้วละ"
10004-CVGroup_Cafe_Idle4-1 = "แบบนี้แอบไปผ่อนคลายสักหน่อยก็คงได้สินะ?"
10004-CVGroup_Cafe_Idle5-1 = "น่าอายจัง..."
10004-CVGroup_WeaponGet_Idle1-1 = "ทุกเรื่องราวย่อมมีตอนจบ\nคุณครูจะช่วยเขียนเรื่องราวตอนจบไปกับฉันได้มั้ย"
10004-CVGroup_UIEventFieldMission_Enter1-1 = "อ่า คุณครู ฉันมีหลายเรื่องเลยที่\nอยากให้ช่วยคลี่คลายให้หน่อย"
10004-CVGroup_UIEventFieldMission_Enter1-2 = "พอจะช่วยหน่อยได้มั้ย?"
10004-CVGroup_UIEventFieldMission_Enter2-1 = "เข้ามาสิ คุณครู"
10004-CVGroup_UIEventFieldMission_Enter2-2 = "ฉันมีเรื่องอื่นนอกเหนือจากปาร์ตี้\nที่ต้องทำในฐานะคณะกรรมการวินัย"
10004-CVGroup_UIEventFieldMission_Idle1-1 = "งานเป็นสิ่งที่ต่อให้ทำมากเท่าไรๆ ก็ไม่หมดสักทีน่ะ"
10004-CVGroup_UIEventFieldMission_Idle1-2 = "หืม? รู้สึกเหมือนกันเลยงั้นเหรอ?\nฮุฮุ คุณครูก็เหนื่อยเหมือนกันสินะ..."
10004-CVGroup_UIEventFieldMission_Idle2-1 = "ฉันไม่คิดจะวางมือจากงานหรอก"
10004-CVGroup_UIEventFieldMission_Idle2-2 = "ก็ฉันเป็นประธานกรรมการวินัยของเกเฮนน่านี่นะ"
10004-CVGroup_UIEventFieldMission_Buy1-1 = "อ่า ขอบคุณนะ"
10004-CVGroup_UIEventFieldMission_Buy1-2 = "นี่เป็นการตอบแทนที่ช่วยกัน\nช่วยรับไว้ด้วยนะ"
10004-CVGroup_UIEventFieldMission_Buy2-1 = "คุณครูทำได้สมบูรณ์แบบจริงๆ\nขอบคุณที่ทำให้วางใจได้นะ..."
10004-CVGroup_UIEventFieldMission_Buy2-2 = "นี่เป็นการตอบแทนที่ช่วย รับไปสิ"
10004-CVGroup_UIEventFieldMission_Interaction1-1 = "วันนี้น่าจะหมดแค่นี้นะ\nขอบคุณนะ คุณครู"
10004-CVGroup_UIEventFieldMission_Interaction1-2 = "ถ้าไม่ติดอะไร...\nไปดื่มชาด้วยกันสักหน่อยมั้ย?"
