[translation]
10003-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10003-CVGroup_CharacterGet_Idle1-1 = "Ahaha... I'm still new to this kind of thing, so please be patient with me."
10003-CVGroup_Cafe_Idle1-1 = "Peroro merch..."
10003-CVGroup_Cafe_Idle2-1 = "Ahaha... I wonder."
10003-CVGroup_Cafe_Idle3-1 = "It might be okay if we all came together next time."
10003-CVGroup_Cafe_Idle4-1 = "I think something like this could be fun too!"
10003-CVGroup_Cafe_Idle5-1 = "Hmm... I wonder..."
10003-CVGroup_WeaponGet_Idle1-1 = "This weapon...really?! With this, I can gain a bit more confidence, right?!"
