[translation]
10001-CVGroup_UIEventMission_Enter1-1 = "你回來啦，老師。\n很高興再次見到你。"
10001-CVGroup_UIEventMission_Enter2-1 = "哈呃……好睏……"
10001-CVGroup_UIEventMission_Idle1-1 = "你說這件衣服……不會冷嗎？"
10001-CVGroup_UIEventMission_Idle1-2 = "唔嗯，很通風，我很喜歡。"
10001-CVGroup_UIEventMission_Idle2-1 = "這件衣服雖然很涼快，\n但是彈殼總是會彈進衣服裡…"
10001-CVGroup_UIEventMission_Idle2-2 = "真是令人頭大。"
10001-CVGroup_UIEventMission_Buy1-1 = "比想像中……還早結束呢。"
10001-CVGroup_UIEventMission_Buy2-1 = "證明完畢。"
10001-CVGroup_UITitle_Idle1-1 = "蔚藍～檔案。"
10001-CVGroup_CharacterGet_Idle1-1 = "接下來要做什麼？\n告訴我吧，老師。"
10001-CVGroup_Cafe_Idle1-1 = "怎麼回事？\n感覺心裡有點悸動。"
10001-CVGroup_Cafe_Idle2-1 = "這是最近的流行呀？"
10001-CVGroup_Cafe_Idle3-1 = "哼嗯…"
10001-CVGroup_Cafe_Idle4-1 = "在這個的話把衣服脫掉也……不行？"
10001-CVGroup_Cafe_Idle5-1 = "好美的空間。\n雖然我其實不太懂。"
10001-CVGroup_WeaponGet_Idle1-1 = "新手也能容易上手的……\n多用途戰術執行工具。"
