[translation]
10011-CVGroup_UITitle_Idle1-1 = "蔚藍檔案～"
10011-CVGroup_CharacterGet_Idle1-1 = "我是培育支援部梅花園的教官，旬。\n我家的孩子們就拜託你囉，\n老．師？"
10011-CVGroup_Cafe_Idle1-1 = "呵呵，下次把大家\n帶來這裡一起上課吧？"
10011-CVGroup_Cafe_Idle2-1 = "明明還沒到午覺時間…\n卻有點想睡了…"
10011-CVGroup_Cafe_Idle3-1 = "梨花有好好地\n照顧孩子們嗎…"
10011-CVGroup_Cafe_Idle4-1 = "哎呀，真可愛…"
10011-CVGroup_Cafe_Idle5-1 = "呵呵，真討人喜歡～"
10011-CVGroup_WeaponGet_Idle1-1 = "雖然不想使用它……\n不過愛的鞭策有時也是必要的。"
