[translation]
10017-CVGroup_UITitle_Idle1-1 = "蔚藍檔案～！……咦？"
10017-CVGroup_CharacterGet_Idle1-1 = "赤冬聯邦學園書記長大駕光臨！\n這是你的榮幸，同志！"
10017-CVGroup_Cafe_Idle1-1 = "唔呣，很好很好。\n書記長很滿意。"
10017-CVGroup_Cafe_Idle2-1 = "唔呣，沒有異常。"
10017-CVGroup_Cafe_Idle3-1 = "耶嘿，書記長大駕光臨哦。"
10017-CVGroup_Cafe_Idle4-1 = "今天也很和平，非常好！\n這都是多虧了咱啊！"
10017-CVGroup_Cafe_Idle5-1 = "（鬍子……沒有掉下來吧？）"
10017-CVGroup_WeaponGet_Idle1-1 = "咱很喜歡哦……這正是咱的權威！咱的力量！咱的鬍子！\n漸漸變得令人畏懼了呢……不過不用擔心，同志。\n咱永遠都是你的同伴！"
10017-CVGroup_UIEventLobby_Enter1-1 = "現在，開始肅清！"
10017-CVGroup_UIEventLobby_Enter2-1 = "呵呵呵，革命的時間到了！"
10017-CVGroup_UIEventLobby_Idle1-1 = "這次的伊凡．庫帕拉也讓人非常期待！"
10017-CVGroup_UIEventLobby_Idle2-1 = "需要我的幫忙嗎，同志？"
10017-CVGroup_UIEventLobby_Idle3-1 = "竟然存在懷疑這鬍子權威的學生……"
10017-CVGroup_UIEventLobby_Idle3-2 = "全部肅清，肅清！"
10017-CVGroup_UIEventLobby_Idle4-1 = "為了這次的伊凡．庫帕拉，準備了一個很大，該怎麼說……"
10017-CVGroup_UIEventLobby_Idle4-2 = "……巨無霸的布丁喔！"
10017-CVGroup_UIEventLobby_Idle4-3 = "肅清結束後，大家一起分著吃吧。"
