[translation]
10010-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10010-CVGroup_CharacterGet_Idle1-1 = "ฉันคือสึนาโอกามิ ชิโรโกะ\nคณะกรรมการแผนงานชั้นปีที่ 2 โรงเรียนอะบิดอส ฝากตัวด้วยนะ"
10010-CVGroup_Cafe_Idle1-1 = "ที่นี่กว้างจัง...\nเหมาะกับการใช้ออกกำลังกายเลยแฮะ"
10010-CVGroup_Cafe_Idle2-1 = "อืม..."
10010-CVGroup_Cafe_Idle3-1 = "จุดหมายต่อไปคือที่ไหนนะ?"
10010-CVGroup_Cafe_Idle4-1 = "หลังเลิกเรียน คุณครูจะทำอะไรนะ?"
10010-CVGroup_Cafe_Idle5-1 = "จะว่าไปนี่มันเวลาตรวจสภาพปืนนี่นา"
10010-CVGroup_WeaponGet_Idle1-1 = "ตอนนี้ฉันแข็งแรงขึ้นกว่าเดิมบ้างแล้วนะ?\nอืม... ถ้าเป็นกำลังให้กับทุกคนได้ละก็..."
