[translation]
10017-CVGroup_UITitle_Idle1-1 = "Blue Archive~!! เอ๋...?"
10017-CVGroup_CharacterGet_Idle1-1 = "ผู้นำแห่งสหภาพเรดวินเทอร์ปรากฏตัวแล้ว!\nถือว่าเป็นเกียรติของเธอนะสหาย!"
10017-CVGroup_Cafe_Idle1-1 = "อืม ดีเลยๆ\nถูกใจผู้นำคนนี้มากเลย"
10017-CVGroup_Cafe_Idle2-1 = "อืม ไม่มีอะไรผิดปกติแฮะ"
10017-CVGroup_Cafe_Idle3-1 = "อะแฮ่ม\nหลีกทางให้ท่านผู้นี้ด้วย"
10017-CVGroup_Cafe_Idle4-1 = "วันนี้ก็สงบสุขดีจัง\nที่สงบสุขแบบนี้ก็เพราะเราเลยนะ"
10017-CVGroup_Cafe_Idle5-1 = "(หนวดเรายังอยู่ดีใช่มั้ย...?)"
10017-CVGroup_WeaponGet_Idle1-1 = "ถูกใจมากเลยละ อำนาจของเรา! พลังของเรา!\nหนวดของเรา! ตอนนี้คงจะค่อยๆ กลัวขึ้นมาแล้วสินะ...\nแต่ไม่ต้องกังวลหรอกสหาย เราจะคอยอยู่กับสหายตลอดเอง"
10017-CVGroup_UIEventLobby_Enter1-1 = "ถ้างั้นจากนี้... จะเริ่มทำการกวาดล้าง!"
10017-CVGroup_UIEventLobby_Enter2-1 = "ฮุฮุ... ถึงเวลาแห่งการปฏิวัติแล้ว!"
10017-CVGroup_UIEventLobby_Idle1-1 = "งานเทศกาลอีวาน คูปาลา\nก็น่าตื่นเต้นเหมือนกัน!"
10017-CVGroup_UIEventLobby_Idle2-1 = "หืม?\nต้องการให้เราช่วยงั้นเหรอสหาย?"
10017-CVGroup_UIEventLobby_Idle3-1 = "ยังมีพวกนักเรียนที่สงสัยในอำนาจของหนวดอยู่อีกงั้นเหรอ..."
10017-CVGroup_UIEventLobby_Idle3-2 = "กวาดล้างให้หมดทุกคนเลย!"
10017-CVGroup_UIEventLobby_Idle4-1 = "เทศกาลอีวาน คูปาลาครั้งนี้...\nเราได้เตรียมพุดดิ้งยักษ์..."
10017-CVGroup_UIEventLobby_Idle4-2 = "ขนาดใหญ่มากๆ เอาไว้ด้วย!"
10017-CVGroup_UIEventLobby_Idle4-3 = "พอกวาดล้างเสร็จแล้ว\nเรามาแบ่งพุดดิ้งกินกันเถอะ"
