[translation]
10015-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10015-CVGroup_CharacterGet_Idle1-1 = "ผู้กล้าเอ๋ย... ขอแสงสว่างจงสถิตอยู่กับท่าน"
10015-CVGroup_Cafe_Idle1-1 = "ตอนนี้คงต้องเตรียมพร้อมสำหรับเล่นเกมวนใหม่อีกครั้งแล้วละค่ะ"
10015-CVGroup_Cafe_Idle2-1 = "อาริสึเองก็อยากดื่มกาแฟเหมือนกันค่ะ"
10015-CVGroup_Cafe_Idle3-1 = "เวลาพักผ่อนสำคัญมากนะคะ\nเพราะจะได้ฟื้นฟู HP ยังไงล่ะคะ"
10015-CVGroup_Cafe_Idle4-1 = "วันนี้อยากไปลงดันเจี้ยนกับคุณครูอีกสักครั้งค่ะ\nแล้วจะส่งข้อความไปนะคะ"
10015-CVGroup_Cafe_Idle5-1 = "อาริสึอยากให้คุณครูลูบหัวอาริสึจังเลยค่ะ\nผิวหนังเทียมของอาริสึจะรู้สึกร้อนๆ ขึ้นมาเลยค่ะ"
10015-CVGroup_WeaponGet_Idle1-1 = "นี่คือ... ดาบวิเศษในตำนาน...\nไม่สิ ปืนนี่นา"
