[translation]
10022-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10022-CVGroup_CharacterGet_Idle1-1 = "Gehenna Head Prefect Hina reporting. I assure you this outfit is merely for summer training."
10022-CVGroup_Cafe_Idle1-1 = "I hope this swimsuit will not cause any issues."
10022-CVGroup_Cafe_Idle2-1 = "I'm getting a little tired. Perhaps due to the training."
10022-CVGroup_Cafe_Idle3-1 = "Cute swimsuits aren't my style."
10022-CVGroup_Cafe_Idle4-1 = "It's nice and cool here. Perfect for summer training."
10022-CVGroup_Cafe_Idle5-1 = "Shall I start planning the next training session?"
10022-CVGroup_WeaponGet_Idle1-1 = "This, for me...? Thank you. I won't let you down, no matter what."
10022-CVGroup_UIEventLobby_Enter1-1 = "Welcome, Sensei. We're ready for summer camp. Let me know if you need anything."
10022-CVGroup_UIEventLobby_Enter2-1 = "Oh, you're here, Sensei. Did you get to check the summer camp schedule?"
10022-CVGroup_UIEventLobby_Enter2-2 = "So hot today... Stay hydrated."
10022-CVGroup_UIEventLobby_Idle1-1 = "It's summer. The heat and humidity are leaving me lethargic..."
10022-CVGroup_UIEventLobby_Idle1-2 = "...but it all comes with the territory of training."
10022-CVGroup_UIEventLobby_Idle2-1 = "Dangers are always lurking at the beach."
10022-CVGroup_UIEventLobby_Idle2-2 = "You never know when and where accidents will occur. Be careful."
10022-CVGroup_UIEventLobby_Idle2-3 = "Um... You can call me if you need me."
10022-CVGroup_UIEventLobby_Idle3-1 = "I never expected to spend summer camp training with you."
10022-CVGroup_UIEventLobby_Idle3-2 = "That's...somewhat new and refreshing."
10022-CVGroup_UIEventLobby_Idle4-1 = "This outfit is suitable for summer training."
10022-CVGroup_UIEventLobby_Idle4-2 = "There's no sense in throwing out things that are still good."
10022-CVGroup_UIEventLobby_Idle4-3 = "I just thought that this would be effective. That's all."
10022-CVGroup_UIEventMission_Enter1-1 = "The summer training camp will begin now."
10022-CVGroup_UIEventMission_Idle1-1 = "It's annoying, but it's part of training."
10022-CVGroup_UIEventMission_Idle2-1 = "It's hot and annoying..."
10022-CVGroup_UIEventMission_Buy1-1 = "I'm seeing real effects from the boot camp."
10022-CVGroup_UIEventMission_Interaction1-1 = "Operation successful. It was simple. But maybe it wasn't enough for training..."
