[translation]
10027-CVGroup_UITitle_Idle1-1 = "蔚藍檔案。"
10027-CVGroup_CharacterGet_Idle1-1 = "無論是什麼服裝，該做的事都沒有改變。\n執行被賦予的任務……僅此而已。"
10027-CVGroup_Cafe_Idle1-1 = "很乾淨的地方，\n還不錯"
10027-CVGroup_Cafe_Idle2-1 = "……總覺得，\n感覺到很多視線"
10027-CVGroup_Cafe_Idle3-1 = "話說回來這件服裝……\n沒有問老師感想呢……"
10027-CVGroup_Cafe_Idle4-1 = "嗯……？\n在那裡的，難道是……？"
10027-CVGroup_Cafe_Idle5-1 = "……沒有能做的事。\n不過，偶爾有這種時間也不錯，嗎。"
10027-CVGroup_WeaponGet_Idle1-1 = "收到這麼好的東西的話，從下次開始就更不能失誤了呢。\n……沒問題。老師的背後，就交給我。"
10027-CVGroup_UIEventLobby_Enter1-1 = "準備已經完成。\n出發吧，老師。"
10027-CVGroup_UIEventLobby_Enter2-1 = "……快到作戰時間了？"
10027-CVGroup_UIEventLobby_Enter2-2 = "沒問題，我隨時可以出發。"
10027-CVGroup_UIEventLobby_Idle1-1 = "……嗯，怎麼了？\n是和作戰有關的事嗎？"
10027-CVGroup_UIEventLobby_Idle2-1 = "你看，快要到出發時間了……\n那種事等等再說。"
10027-CVGroup_UIEventLobby_Idle3-1 = "要出發的時候和我說一聲。\n我已經準備好了。"
10027-CVGroup_UIEventLobby_Idle4-1 = "……嗯？老師，你剛才叫我嗎？"
10027-CVGroup_UIEventLobby_Enter3-1 = "不能掉以輕心。\n畢竟流逝的時間是不等人的。"
10027-CVGroup_UIEventLobby_Enter4-1 = "差不多要結束了呢……"
10027-CVGroup_UIEventLobby_Enter4-2 = "我隨時都做好了準備，交給我吧。"
10027-CVGroup_UIEventLobby_Enter5-1 = "收尾要確實做到最後。"
10027-CVGroup_UIEventLobby_Enter5-2 = "老師，有什麼我能幫忙的嗎？"
10027-CVGroup_UIEventShop_Enter1-1 = "是作戰的報酬啊……"
10027-CVGroup_UIEventShop_Enter1-2 = "先大致確認一下內容物吧。"
10027-CVGroup_UIEventShop_Enter2-1 = "這個，得考慮效率才行……\n但我不擅長面對數字啊……"
10027-CVGroup_UIEventShop_Idle1-1 = "咦，要我幫你計算……？"
10027-CVGroup_UIEventShop_Idle1-2 = "老，老師也知道我不擅長數學吧……！？"
10027-CVGroup_UIEventShop_Idle2-1 = "抱歉，計算之類的事，我有點幫不上忙……"
10027-CVGroup_UIEventShop_Buy1-1 = "啊啊，是個不錯的選擇。"
10027-CVGroup_UIEventShop_Buy2-1 = "選擇了那個啊。\n嗯，我覺得很好。"
10027-CVGroup_UIEventShop_Buy3-1 = "嗯，不錯。"
10027-CVGroup_UIEventShop_Buy4-1 = "不愧是老師，判斷的很好。"
10027-CVGroup_UIEventShop_Enter3-1 = "老師，你看。\n看來似乎還來的及呢。"
