[translation]
10031-CVGroup_UITitle_Idle1-1 = "Bluuue Archive"
10031-CVGroup_CharacterGet_Idle1-1 = "Heehee. Can I still prove useful to you this year? There's no other choice. Stay by my side and watch what I accomplish this year."
10031-CVGroup_Cafe_Idle1-1 = "Whew. Business is really going to pick up in the new year."
10031-CVGroup_Cafe_Idle2-1 = "It's important I keep my composure as a leader."
10031-CVGroup_Cafe_Idle3-1 = "Are bosses usually expected to give their employees cash gifts for New Year's?!"
10031-CVGroup_Cafe_Idle4-1 = "I'm nervous because it's an expensive kimono... If I'm not careful..."
10031-CVGroup_Cafe_Idle5-1 = "So tired... Hmm? Where did my employees go?"
10031-CVGroup_WeaponGet_Idle1-1 = "This is what you call turning it up to eleven...right?"
10031-CVGroup_UIEventLobby_Enter1-1 = "Welcome, Sensei. I've been waiting for you."
10031-CVGroup_UIEventLobby_Enter1-2 = "With a new year, comes new business."
10031-CVGroup_UIEventLobby_Enter1-3 = "Heehee. I can hire you for a temp role, Sensei."
10031-CVGroup_UIEventLobby_Enter2-1 = "Your hands are freezing, Sensei!"
10031-CVGroup_UIEventLobby_Enter2-2 = "Proper rest is even more important when you're busy."
10031-CVGroup_UIEventLobby_Idle1-1 = "My new year's wish... For Problem Solver 68 to become the biggest organization in Kivotos!"
10031-CVGroup_UIEventLobby_Idle1-2 = "How did this happen...?"
10031-CVGroup_UIEventLobby_Idle2-1 = "New year, new Problem Solver 68!"
10031-CVGroup_UIEventLobby_Idle2-2 = "Sensei! We're going to make this the best year yet!"
10031-CVGroup_UIEventLobby_Idle3-1 = "Don't worry, Sensei. As long as Problem Solver 68 is together..."
10031-CVGroup_UIEventLobby_Idle3-2 = "...we can overcome any obstacle."
10031-CVGroup_UIEventLobby_Idle3-3 = "Huh? P-P-Plans?! No... I-I didn't have anything in particular..."
10031-CVGroup_UIEventLobby_Idle4-1 = "*sigh* It devolved into utter chaos."
10031-CVGroup_UIEventLobby_Idle4-2 = "If any of our employees were hurt..."
10031-CVGroup_UIEventLobby_Enter3-1 = "I didn't expect the commotion to get this boisterous. *sigh* It's unexpected..."
10031-CVGroup_UIEventLobby_Enter4-1 = "...Coming this far actually makes me want to do it more."
10031-CVGroup_UIEventLobby_Enter4-2 = "Since this is how it is, Problem Solver 68 will stay until the end!"
10031-CVGroup_UIEventLobby_Enter4-3 = "Sensei, you'll be cooperating as well, right?"
10031-CVGroup_UIEventLobby_Enter5-1 = "It ended up being KAITEN FX Mk.1! What the heck?!"
10031-CVGroup_UIEventLobby_Enter5-2 = "It's so ridiculous. I don't even know what to say..."
10031-CVGroup_UIEventLobby_Enter5-3 = "*sigh* Well, it's no use crying over spilled milk..."
10031-CVGroup_UIEventLobby_Enter5-4 = "Sensei, I'm tired. Do you want to grab a meal next time?"
10031-CVGroup_UIEventShop_Enter1-1 = "Welcome, Sensei. Work preparations are complete."
10031-CVGroup_UIEventShop_Enter2-1 = "Problem Solver 68 has prepared a lot for the new year."
10031-CVGroup_UIEventShop_Enter2-2 = "Take your time and choose."
10031-CVGroup_UIEventShop_Idle1-1 = "Heehee, what do you think? Aren't they such catchy, cool items?"
10031-CVGroup_UIEventShop_Idle1-2 = "These are all the hidden powers of Problem Solver 68! ♪"
10031-CVGroup_UIEventShop_Idle2-1 = "Sensei, is there anything that catches your attention?"
10031-CVGroup_UIEventShop_Idle2-2 = "...A photo of everyone in Problem Solver 68 wearing kimonos?"
10031-CVGroup_UIEventShop_Idle2-3 = "W-We wouldn't have something like that!!"
10031-CVGroup_UIEventShop_Buy1-1 = "You have good taste, as expected. Well done, Sensei."
10031-CVGroup_UIEventShop_Buy2-1 = "Wow, good choice! I knew it."
10031-CVGroup_UIEventShop_Buy2-2 = "It's a really good item, so use it well."
10031-CVGroup_UIEventShop_Buy3-1 = "I can't believe you chose that. Not bad. You're fit to be my business partner, Sensei."
10031-CVGroup_UIEventShop_Buy4-1 = "Oh, that one's cool, right? I've been wanting to buy one for the office..."
10031-CVGroup_UIEventShop_Buy4-2 = "N-No! I'm not saying you have to buy me one!"
10031-CVGroup_UIEventShop_Enter3-1 = "*sigh* The chaos has finally died down."
10031-CVGroup_UIEventShop_Enter3-2 = "Heehee. But we're still open for business."
10031-CVGroup_UIEventShop_Enter3-3 = "So take your time looking around, Sensei. ♪"
