[translation]
10031-CVGroup_UITitle_Idle1-1 = "蔚藍檔案。"
10031-CVGroup_CharacterGet_Idle1-1 = "哼哼，今年也想委託我？\n真是沒辦法呢，老師這個人。\n我的活躍，今年也在身邊見證吧。"
10031-CVGroup_Cafe_Idle1-1 = "唔……才剛新年，\n錢包就好輕……"
10031-CVGroup_Cafe_Idle2-1 = "作為領導人重要的東西，\n那就是從容唷。"
10031-CVGroup_Cafe_Idle3-1 = "咦，社長一般，\n必須給社員紅包才行嗎！？"
10031-CVGroup_Cafe_Idle4-1 = "高價的和服，\n會讓人緊張呢……\n得小心走路才行……"
10031-CVGroup_Cafe_Idle5-1 = "累了呢……\n話說回來，我家的社員在哪？"
10031-CVGroup_WeaponGet_Idle1-1 = "這就是所謂的，如虎添翼呢。\n……沒說錯吧？"
10031-CVGroup_UIEventLobby_Enter1-1 = "哎呀，老師。我在等你哦。"
10031-CVGroup_UIEventLobby_Enter1-2 = "既然才剛過新年就發生了必須解決的事件……"
10031-CVGroup_UIEventLobby_Enter1-3 = "呵呵，就請老師也幫個忙吧？"
10031-CVGroup_UIEventLobby_Enter2-1 = "老師的手，摸起來真冷呢？"
10031-CVGroup_UIEventLobby_Enter2-2 = "…就算工作很多，不好好休息也是不行的唷？"
10031-CVGroup_UIEventLobby_Idle1-1 = "我只是想在新年祈求便利屋68的事業鴻圖大展而已……"
10031-CVGroup_UIEventLobby_Idle1-2 = "事情怎麼會變成這樣……"
10031-CVGroup_UIEventLobby_Idle2-1 = "今年是我們便利屋68更加脫胎換骨的一年。"
10031-CVGroup_UIEventLobby_Idle2-2 = "來，努力成就飛躍性的一年吧！"
10031-CVGroup_UIEventLobby_Idle3-1 = "別擔心，老師。只要有我們便利屋68在，"
10031-CVGroup_UIEventLobby_Idle3-2 = "不管面臨什麼障礙，我們一定都能克服。"
10031-CVGroup_UIEventLobby_Idle3-3 = "……咦？計畫？\n不，那，那倒是還沒有……"
10031-CVGroup_UIEventLobby_Idle4-1 = "呼，總覺得事情越來越嚴重了呢。"
10031-CVGroup_UIEventLobby_Idle4-2 = "……我們的社員們應該沒有受傷吧？"
10031-CVGroup_UIEventLobby_Enter3-1 = "居然會演變成這麼大的騷動……\n唉，真是出乎我的預料……"
10031-CVGroup_UIEventLobby_Enter4-1 = "……既然事已至此，我下定決心了。"
10031-CVGroup_UIEventLobby_Enter4-2 = "我們便利屋68，事到如今就奉陪到最後吧！"
10031-CVGroup_UIEventLobby_Enter4-3 = "啊，當然老師也會幫忙的對吧？"
10031-CVGroup_UIEventLobby_Enter5-1 = "到頭來那個「KAITEN FX Mk.1」是什麼東西啊！？"
10031-CVGroup_UIEventLobby_Enter5-2 = "已經無言到一句話都說不出來了……"
10031-CVGroup_UIEventLobby_Enter5-3 = "唉……算了，對已經結束的事情再說三道四也沒用……"
10031-CVGroup_UIEventLobby_Enter5-4 = "老師，反正也累了，等等一起去吃個飯怎麼樣？"
10031-CVGroup_UIEventShop_Enter1-1 = "歡迎你，老師。\n工作的準備非常完美唷。"
10031-CVGroup_UIEventShop_Enter2-1 = "我們便利屋68，為了新年做了各種準備。"
10031-CVGroup_UIEventShop_Enter2-2 = "慢慢挑選吧。"
10031-CVGroup_UIEventShop_Idle1-1 = "呵呵，怎麼樣呀？這些東西棒到讓人目不轉睛對吧？"
10031-CVGroup_UIEventShop_Idle1-2 = "要說這是我們便利屋68的實力也不為過哦♪"
10031-CVGroup_UIEventShop_Idle2-1 = "老師，有什麼特別吸引你的東西嗎？"
10031-CVGroup_UIEventShop_Idle2-2 = "……便利屋68的大家身穿和服拍的團體照？"
10031-CVGroup_UIEventShop_Idle2-3 = "才，才沒有那種東西！？"
10031-CVGroup_UIEventShop_Buy1-1 = "不愧是你，很有眼光呢，老師。真了不起。"
10031-CVGroup_UIEventShop_Buy2-1 = "哎呀，居然選了那個，真不愧是你呢。"
10031-CVGroup_UIEventShop_Buy2-2 = "因為是非常好的東西，還請好好使用哦？"
10031-CVGroup_UIEventShop_Buy3-1 = "居然選了那個，很有一套嘛老師。\n這才能稱得上是我的合夥人。"
10031-CVGroup_UIEventShop_Buy4-1 = "很棒對吧，那個東西！\n我也想自己買一個放在事務所裡……"
10031-CVGroup_UIEventShop_Buy4-2 = "啊，不是，我沒有強求你買的意思……！"
10031-CVGroup_UIEventShop_Enter3-1 = "呼……亂哄哄的新年總算是平靜下來了呢。"
10031-CVGroup_UIEventShop_Enter3-2 = "呵呵，不過這裡依然還在營業中哦。"
10031-CVGroup_UIEventShop_Enter3-3 = "來，請冷靜地好好逛逛吧，老師♪"
