[translation]
10039-CVGroup_UITitle_Idle1-1 = "브, 블루…… 아카이브……"
10039-CVGroup_CharacterGet_Idle1-1 = "SRT 특수학원, RABBIT 소대의 카스미자와 미유입니다……\n저…… 이만 돌아가면…… 안 되겠죠……?"
10039-CVGroup_Cafe_Idle1-1 = "아, 저기……"
10039-CVGroup_Cafe_Idle2-1 = "(먼저 말을 걸고 싶은데…… 너무 무서워……)"
10039-CVGroup_Cafe_Idle3-1 = "(따듯한 코코아나 한 잔 마셨으면……)"
10039-CVGroup_Cafe_Idle4-1 = "(역시 나 같은 못난이는 이런 장소에 어울리지 않아……)"
10039-CVGroup_Cafe_Idle5-1 = "뭐, 뭔가, 엄폐물은……?"
10039-CVGroup_WeaponGet_Idle1-1 = "RABBIT 39식 소총, 수령했습니다. …역시, 조금 무겁네요…."
