[translation]
10032-CVGroup_UITitle_Idle1-1 = "블루 아카이브!"
10032-CVGroup_CharacterGet_Idle1-1 = "아하핫! 기다렸지, 선생님! 올해도 자안-뜩, 나랑 놀아주기야~?"
10032-CVGroup_Cafe_Idle1-1 = "다 같이 모여서 하네츠키 하고 싶다아~"
10032-CVGroup_Cafe_Idle2-1 = "선생님하고 뭘 하고 놀까~나~♪"
10032-CVGroup_Cafe_Idle3-1 = "웃으면 복이 온대~♪"
10032-CVGroup_Cafe_Idle4-1 = "장난감~ 발-견~♪"
10032-CVGroup_Cafe_Idle5-1 = "선생님한테 어리광 부리면, 세뱃돈 받을 수 있지 않으려나~?"
10032-CVGroup_WeaponGet_Idle1-1 = "아하핫~ 좋아좋아! 이거라면 좀 더 재밌게 놀 수 있을지도~!"
10032-CVGroup_UIEventLobby_Enter1-1 = "앗, 선생님. 찾았다! 새해가 되어서도 일이라니, 여전하네! 선생님!"
10032-CVGroup_UIEventLobby_Enter2-1 = "와-오! 새해가 되자마자 이렇게 만나다니, 깜짝 놀랐어! 선생님!"
10032-CVGroup_UIEventLobby_Enter2-2 = "자, 하이파이브!"
10032-CVGroup_UIEventLobby_Idle1-1 = "아핫, 아루 쨩 왠지 큰일인 모양이네~ 뭐, 나야 재미있으니까 괜찮지만!"
10032-CVGroup_UIEventLobby_Idle2-1 = "난데없이 새전함 도둑이라니~ 새해부터 이렇게나 시끄러운 게, 정말 최고라니깐~!"
10032-CVGroup_UIEventLobby_Idle3-1 = "으응~! 역시 가만히 있기만 한 건 지루해! 가자! 선생님!"
10032-CVGroup_UIEventLobby_Idle4-1 = "이렇게 올해도 여러 소동이 일어날 거 같지만."
10032-CVGroup_UIEventLobby_Idle4-2 = "아루 쨩도 카요코 쨩도 하루카 쨩도. 모두 선생님을 의지하고 있으니, 잘 부탁해♪"
10032-CVGroup_UIEventLobby_Idle4-3 = "응? 나? 글쎄 어떨 거라고 생각해?"
10032-CVGroup_UIEventLobby_Idle4-4 = "어떨까나~?"
10032-CVGroup_UIEventLobby_Enter3-1 = "자, 선생님. 오늘은 어떤 장난감을 가지고 놀까?"
10032-CVGroup_UIEventLobby_Enter3-2 = "하네츠키? 후쿠와라이? 다루마 떨구기! 쿠후훗♪"
10032-CVGroup_UIEventLobby_Enter4-1 = "흐응~ 슬슬 장난감도 질려버렸고. 지금부터는 선생님을 가지고 놀아야지!"
10032-CVGroup_UIEventLobby_Enter4-2 = "어때? 좋은 생각이지?"
10032-CVGroup_UIEventLobby_Enter5-1 = "아~ 재밌었다! 어때, 선생님도 즐거웠어?"
10032-CVGroup_UIEventLobby_Enter5-2 = "올해도 이런 식으로, 즐거운 일이 잔뜩이었으면 좋겠네!"
10032-CVGroup_UIEventBoxGachaShop_Enter1-1 = "무츠키 쨩의 특별 교환소에 어서 와~!"
10032-CVGroup_UIEventBoxGachaShop_Enter2-1 = "안녕~! 선생님! 복주머니, 가지고 있지? 얼른 까보자!"
10032-CVGroup_UIEventBoxGachaShop_Idle1-1 = "자자, 어떤 게 나오려나~? 두근두근!"
10032-CVGroup_UIEventBoxGachaShop_Idle2-1 = "응? 왜 그렇게 보고 있느냐고?"
10032-CVGroup_UIEventBoxGachaShop_Idle2-2 = "그야, 복주머니를 까는 건 몇 번을 해도 재밌잖아!"
10032-CVGroup_UIEventBoxGachaShop_BoxGachaPrize1-1 = "와-오! 이런 게 들어있었다니 무츠키 쇼크! 부럽다아~"
10032-CVGroup_UIEventBoxGachaShop_BoxGachaPrize1-2 = "나도 가지고 싶다아~"
10032-CVGroup_UIEventBoxGachaShop_BoxGachaPrize2-1 = "응! 좋은 물건이잖아! 선생님!"
10032-CVGroup_UIEventBoxGachaShop_BoxGachaPrize2-2 = "이건 전부 내 덕분일지도? 고마워해도 된다구? 쿠흐흣!"
10032-CVGroup_UIEventBoxGachaShop_BoxGachaPrize3-1 = "앗, 당첨이려나? 아하핫. 모처럼 내가 뽑아준 거니까."
10032-CVGroup_UIEventBoxGachaShop_BoxGachaPrize3-2 = "나라고 생각하고 소중하게 써야 해~?"
10032-CVGroup_UIEventBoxGachaShop_Enter3-1 = "앗, 선생님! 안녕~! 새해맞이 이벤트는 끝나버렸지만…"
10032-CVGroup_UIEventBoxGachaShop_Enter3-2 = "아직 완전 부족해! 남은 복주머니가 있다면 전부 까버리자!"
