[translation]
10044-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10044-CVGroup_CharacterGet_Idle1-1 = "We're finally at the beach! Sensei! Let's enjoy it!"
10044-CVGroup_Cafe_Idle1-1 = "I'm so happy that everyone is enjoying themselves!"
10044-CVGroup_Cafe_Idle2-1 = "Huh? That's..."
10044-CVGroup_Cafe_Idle3-1 = "It's crowded!"
10044-CVGroup_Cafe_Idle4-1 = "Should I sit down and rest?"
10044-CVGroup_Cafe_Idle5-1 = "It's so nice and cool here..."
10044-CVGroup_WeaponGet_Idle1-1 = "Wow! Thank you! I appreciate you so much... I'll try my best to be more helpful to you!"
10044-CVGroup_UIEventLobby_Enter1-1 = "Welcome to our resort!"
10044-CVGroup_UIEventLobby_Enter1-2 = "Heehee! ☆"
10044-CVGroup_UIEventLobby_Enter2-1 = "Summer! The beach! This is a vacation site for sure!"
10044-CVGroup_UIEventLobby_Idle1-1 = "Yes! Sensei, did you call me? ☆"
10044-CVGroup_UIEventLobby_Idle2-1 = "It's a little hot. Are you feeling okay?"
10044-CVGroup_UIEventLobby_Idle3-1 = "Heehee, I got excited for some reason."
10044-CVGroup_UIEventLobby_Idle4-1 = "It's nice to sweat it out like this sometimes. ☆"
10044-CVGroup_UIEventLobby_Enter3-1 = "I'm slowly getting warmed up!"
10044-CVGroup_UIEventLobby_Enter4-1 = "Let's push a little harder!"
10044-CVGroup_UIEventLobby_Enter5-1 = "I'm so satisfied!"
10044-CVGroup_UIEventLobby_Enter5-2 = "Did you enjoy it too?"
10044-CVGroup_UIEventBoxGachaShop_Enter1-1 = "Ta-da! Welcome! ☆"
10044-CVGroup_UIEventBoxGachaShop_Enter1-2 = "...Something along those lines. Heehee, did I look too excited?"
10044-CVGroup_UIEventBoxGachaShop_Enter2-1 = "Heehee. What's gonna come out?"
10044-CVGroup_UIEventBoxGachaShop_Idle1-1 = "If you keep doing that, I'm gonna pick one myself!"
10044-CVGroup_UIEventBoxGachaShop_Idle2-1 = "Hahahaha! It tickles!"
10044-CVGroup_UIEventBoxGachaShop_BoxGachaPrize1-1 = "Wow! I knew it, Sensei!"
10044-CVGroup_UIEventBoxGachaShop_BoxGachaPrize2-1 = "Wow, amazing! Should we pick again?"
10044-CVGroup_UIEventBoxGachaShop_BoxGachaPrize3-1 = "It could be...something incredible!"
10044-CVGroup_UIEventBoxGachaShop_Enter3-1 = "It's time to clean up! ☆"
