[translation]
10041-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10041-CVGroup_CharacterGet_Idle1-1 = "Misaki of the Arius Squad. In other words, the hound who lost its master. I'm under your command now."
10041-CVGroup_Cafe_Idle1-1 = "How noisy."
10041-CVGroup_Cafe_Idle2-1 = "So many unfamiliar things..."
10041-CVGroup_Cafe_Idle3-1 = "...What's fun about that?"
10041-CVGroup_Cafe_Idle4-1 = "I'm not interested."
10041-CVGroup_Cafe_Idle5-1 = "...What are you doing?"
10041-CVGroup_WeaponGet_Idle1-1 = "I won't question it, but...I've never received a gift like this. You're strange, Sensei. I'll trust you with my power, for now."
