[translation]
10048-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10048-CVGroup_CharacterGet_Idle1-1 = "Saori of the Arius Squad. I owe you a lot. I'll do what I can to repay my debt. Looking forward to working with you."
10048-CVGroup_Cafe_Idle1-1 = "Hmm..."
10048-CVGroup_Cafe_Idle2-1 = "I still haven't adjusted to places like this..."
10048-CVGroup_Cafe_Idle3-1 = "What's this...?"
10048-CVGroup_Cafe_Idle4-1 = "I don't quite understand though..."
10048-CVGroup_Cafe_Idle5-1 = "I see. I think I get it..."
10048-CVGroup_WeaponGet_Idle1-1 = "How...can you trust me? After all that's happened... Aren't you worried I might betray you? I don't understand what you're thinking...but I'll do my best to not let you down."
