[translation]
10047-CVGroup_UITitle_Idle1-1 = "蔚藍～～檔案？"
10047-CVGroup_CharacterGet_Idle1-1 = "剛才…在海邊發現了唰唰走著的梭子蟹先生。\n老師，要一起去看嗎？"
10047-CVGroup_Cafe_Idle1-1 = "真涼快～"
10047-CVGroup_Cafe_Idle2-1 = "哇，這是…\n冰淇淋？"
10047-CVGroup_Cafe_Idle3-1 = "在這附近，蓋一個\n梭子蟹先生的家吧。"
10047-CVGroup_Cafe_Idle4-1 = "手帕OK，鏟子OK…\n嗯，這樣就能堆一座沙堡了。"
10047-CVGroup_Cafe_Idle5-1 = "想要和陰陽部的大家一起在沙堆上玩倒桿比賽。"
10047-CVGroup_WeaponGet_Idle1-1 = "這是要給我的嗎？哇～謝謝～\n那下次就輪到我囉～？我的回禮，請你期待哦～"
10047-CVGroup_UIEventLobby_Enter1-1 = "啊，在等你唷，老師～"
10047-CVGroup_UIEventLobby_Enter1-2 = "……咦？我在等什麼咧？"
10047-CVGroup_UIEventLobby_Enter2-1 = "歡迎光臨，歡迎來到大海之家～"
10047-CVGroup_UIEventLobby_Enter2-2 = "……這樣對嗎？"
10047-CVGroup_UIEventLobby_Idle1-1 = "大家好像都很忙……那就老師和我一起玩吧？"
10047-CVGroup_UIEventLobby_Idle2-1 = "這麼說來佳穗有說，如果感到危險的話……"
10047-CVGroup_UIEventLobby_Idle2-2 = "就立刻發射防犯用的榴彈。"
10047-CVGroup_UIEventLobby_Idle3-1 = "啊，其實為了預防中暑……"
10047-CVGroup_UIEventLobby_Idle3-2 = "來，抹茶彈珠汽水。"
10047-CVGroup_UIEventLobby_Idle3-3 = "老師也來喝吧？"
10047-CVGroup_UIEventLobby_Idle4-1 = "老師，你叫我嗎？\n我剛才也在心中呼喚了你。"
10047-CVGroup_UIEventLobby_Idle4-2 = "真巧呢～"
10047-CVGroup_UIEventLobby_Enter3-1 = "大家好像都很開心呢～\n嗯，有精神是好事。"
10047-CVGroup_UIEventLobby_Enter4-1 = "大家好像都很努力呢。\n那，我也要努力。"
10047-CVGroup_UIEventLobby_Enter5-1 = "咦，已經結束了嗎？\n那老師，大家一起玩水吧？"
10047-CVGroup_UIEventMission_Enter1-1 = "要做的事真多～\n老師也很辛苦呢～？"
10047-CVGroup_UIEventMission_Enter2-1 = "啊，老師。目標清單……？\n我拿到了這個東西。老師，想要嗎？"
10047-CVGroup_UIEventMission_Buy1-1 = "哇啊，好厲害……！"
10047-CVGroup_UIEventMission_Buy2-1 = "老師，很努力呢。好棒好棒。"
10047-CVGroup_UIEventMission_Idle1-1 = "戳戳，也是工作嗎？\n那，我也要戳戳老師。"
10047-CVGroup_UIEventMission_Idle2-1 = "不可以偷懶～\n剛剛仁耶部長是這麼說的。"
10047-CVGroup_UIEventMission_Interaction1-1 = "這樣，今天的工作就結束了嗎？\n那現在開始，要玩什麼呢？"
