[translation]
10043-CVGroup_UITitle_Idle1-1 = "Heehee. Blue Archive!"
10043-CVGroup_CharacterGet_Idle1-1 = "Even under the scorching sun, or in ice-cold water...I'll follow you anywhere. So this summer, please don't leave me, my darling ♥"
10043-CVGroup_Cafe_Idle1-1 = "This place is cool. Heeheehee... ♥"
10043-CVGroup_Cafe_Idle2-1 = "This outfit... I can't wait to show you..."
10043-CVGroup_Cafe_Idle3-1 = "*sigh* ...Where are you now...?"
10043-CVGroup_Cafe_Idle4-1 = "It's kind of noisy here..."
10043-CVGroup_Cafe_Idle5-1 = "I feel a gaze... Could it be from Sensei? Heeheehee..."
10043-CVGroup_WeaponGet_Idle1-1 = "You prepared this for me...? I swear...I will destroy anything that gets in our way, no matter what. Heehee, heeheehee... ♥"
