[translation]
10046-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10046-CVGroup_CharacterGet_Idle1-1 = "นายท่าน! ฤดูร้อนค่ะ ทะเลค่ะ! อิซุนะค่ะ!\nมาเล่นสนุกด้วยกันกับอิซุนะเยอะๆ เลยนะคะ นินนิน~!"
10046-CVGroup_Cafe_Idle1-1 = "ต่อไปพวกเราจะทำอะไรดีนะ?\nตีแตงโม? หรือเล่นสาดน้ำ~?\nอิซุนะอยากเล่นทั้งหมดเลยค่ะ~"
10046-CVGroup_Cafe_Idle2-1 = "อิซุนะ อิซุนะ นินนิน~"
10046-CVGroup_Cafe_Idle3-1 = "ตอนนี้ท่านหัวหน้ากับท่านสึคุโยะจะทำอะไรกันอยู่นะ~?"
10046-CVGroup_Cafe_Idle4-1 = "เคล็ดวิชานินจาอิซุนะฉบับฤดูร้อนเสร็จสมบูรณ์แล้วค่ะ\nอิซุนะควรรีบคิดเคล็ดวิชาฉบับฤดูหนาวไว้แล้วล่ะ"
10046-CVGroup_Cafe_Idle5-1 = "แอร์นี่ยอดเลยนะคะ! ในฤดูร้อนก็ยังให้ลมเย็นแบบนี้ได้ตลอด\nนะ...แน่นอนว่าถ้าเป็นนินจาละก็ร้อนแค่ไหนก็ทนได้อยู่แล้วละค่ะ~!"
10046-CVGroup_WeaponGet_Idle1-1 = "นายท่านอุตส่าห์เตรียมอุปกรณ์นินจาสำหรับฤดูร้อนมาให้อิซุนะ...!\nอิซุนะดีใจมากค่ะ นายท่าน จากนี้ไปอิซุนะจะพยายามเต็มที่\nเพื่อตอบแทนนายท่านค่ะ ฮิฮิฮิ!"
10046-CVGroup_UIEventLobby_Enter1-1 = "นายท่าน~ ทางนี้~ ทางนี้ค่ะ~!\nที่ตรงนี้อิซุนะจองไว้เรียบร้อยแล้วค่ะ!"
10046-CVGroup_UIEventLobby_Enter2-1 = "อ๊ะ กำลังรออยู่เลยค่ะ! นายท่าน!\nอิซุนะเตรียมพร้อมแล้วค่ะ! สั่งการมาได้เลยค่า!"
10046-CVGroup_UIEventLobby_Idle1-1 = "ร้านสาขาริมทะเลฐานทัพภารกิจครั้งนี้ค่ะ...!"
10046-CVGroup_UIEventLobby_Idle1-2 = "พอเรียกว่าฐานทัพ... รู้สึกเหมือนเป็นนินจาเลยค่ะ!"
10046-CVGroup_UIEventLobby_Idle2-1 = "ลั้ลลัลลา~ ที่ร้านริมทะเลมีอาหารเยอะแยะเลยค่ะ!"
10046-CVGroup_UIEventLobby_Idle2-2 = "นายท่านชอบทานอะไรคะ? บิงซู? หรือว่าทาโกะยากิ?"
10046-CVGroup_UIEventLobby_Idle2-3 = "อิซุนะน่ะ ถ้าได้กินกับนายท่านละก็ อร่อยทุกอย่างเลยค่ะ~!"
10046-CVGroup_UIEventLobby_Idle3-1 = "ภาพลักษณ์ที่เผชิญหน้าต่อไป\nไม่ว่าจะเจอเรื่องอันตรายหรือเรื่องลำบากแค่ไหน..."
10046-CVGroup_UIEventLobby_Idle3-2 = "หรือว่าท่านชิซุโกะจะเป็นนินจากันนะคะ?"
10046-CVGroup_UIEventLobby_Idle4-1 = "ไม่ว่าเรื่องอะไรก็ออกคำสั่งมาได้เลยค่ะ!"
10046-CVGroup_UIEventLobby_Idle4-2 = "เดี๋ยวฉันจะคลี่คลายแบบ \"ฟึ่บฟึ่บฟึ่บ\" เหมือนนินจาเลยค่ะ!"
10046-CVGroup_UIEventLobby_Enter3-1 = "คราวนี้ไม่ได้มีแค่อิซุนะกับนายท่านเท่านั้น\nแต่ยังมีอีกหลายๆ คนช่วยด้วยค่ะ!"
10046-CVGroup_UIEventLobby_Enter3-2 = "ดูจะสนุกแล้วก็ร่าเริงมากเลยนะคะ นายท่าน!"
10046-CVGroup_UIEventLobby_Enter4-1 = "(กลืนน้ำลาย...) ภารกิจร่วมกับนายท่านจบลงแค่เท่านี้แล้วเหรอคะ...!"
10046-CVGroup_UIEventLobby_Enter4-2 = "อิซุนะก็จะพยายามเพื่อไม่ให้แพ้ทุกๆ คนค่ะ นินนิน!"
10046-CVGroup_UIEventLobby_Enter5-1 = "ฤดูร้อนคราวนี้มีเรื่องยิ่งใหญ่เต็มไปหมดเลยค่ะ!\nจนตาของอิซุนะหมุนติ้วๆ ไม่หยุดเลยค่ะ"
10046-CVGroup_UIEventLobby_Enter5-2 = "แต่ว่าอิซุนะเอง... ก็สนุกในทุกๆ วันเลยค่ะ! ฮิฮิฮิ!\nขอบคุณค่ะ! นายท่าน!"
