[translation]
10057-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10057-CVGroup_CharacterGet_Idle1-1 = "ฮุฮุ ขอให้มีความสุขในวันปีใหม่นะคะ\nออกไปค้นหาอาหารแห่งจิตใจใหม่ๆ\nพร้อมกับชุดกิโมโนฟุริโซเดะนี่กันเถอะค่ะ"
10057-CVGroup_Cafe_Idle1-1 = "สิ่งที่ยอดเยี่ยมสำหรับอาหารคือการที่ทุกสิ่งทุกอย่าง\nรวมอยู่ในนั้นแล้วยังไงล่ะคะ"
10057-CVGroup_Cafe_Idle2-1 = "ทั้งเสื้อผ้าและสถานที่ไม่ว่าจะดูยังไง\nทั้งสองอย่างก็เป็นสิ่งสำคัญสำหรับอาหารเลิศรสสินะคะ"
10057-CVGroup_Cafe_Idle3-1 = "ช่วงเวลาแบบนี้... มักมีอาหารพิเศษหลายอย่าง...\nฮุฮุ ฉันตั้งตารอเลยละค่ะ"
10057-CVGroup_Cafe_Idle4-1 = "ฉันชินกับชุดฟุริโซเดะแล้วละค่ะ"
10057-CVGroup_Cafe_Idle5-1 = "ถ้าครั้งนี้พวกเราค้นพบอาหารที่ยอดเยี่ยมก็คงจะดีนะคะ"
10057-CVGroup_WeaponGet_Idle1-1 = "อาหารพิเศษที่ได้ลิ้มรสในเทศกาลพิเศษ คงพิเศษขึ้นมาอีกระดับเลยค่ะ\nและปืนด้ามนี้ก็จะทำให้ฉันได้เข้าใกล้... เส้นทางของอาหารเลิศรส\nแล้วก็คุณครูด้วยค่ะ ไม่ว่าเมื่อไรก็ขอบคุณเสมอๆ เลยนะคะคุณครู"
10057-CVGroup_UIEventLobby_Enter1-1 = "เชิญค่ะคุณครู ตายจริง..\nวันปีใหม่แบบนี้ก็ทำงานด้วยเหรอคะ?\nบางครั้งเวลาพักผ่อนก็สำคัญนะคะ"
10057-CVGroup_UIEventLobby_Enter1-2 = "เอาละ มาดื่มชากับฉันสักหน่อยนะคะ"
10057-CVGroup_UIEventLobby_Enter2-1 = "ฮุฮุฮุ ได้เจอกับคุณครูตั้งแต่วันปีใหม่แบบนี้\nดีใจจังเลยค่ะ"
10057-CVGroup_UIEventLobby_Enter2-2 = "ฉันน่ะ ไม่ว่าเมื่อไรก็เตรียมพร้อมเสมอค่ะ"
10057-CVGroup_UIEventLobby_Idle1-1 = "ฮุฮุฮุ เรียกฉันเหรอคะ คุณครู?"
10057-CVGroup_UIEventLobby_Idle2-1 = "ถ้ามาจั๊กจี้ฉันแบบนั้นบ่อยๆ ถ้าเครื่องติดมันจะลำบากนะคะ"
10057-CVGroup_UIEventLobby_Idle2-2 = "ไม่นึกเลยนะคะว่าคุณครูจะชอบเล่นซุกซนแบบนี้น่ะค่ะ?"
10057-CVGroup_UIEventLobby_Idle3-1 = "จริงอยู่ที่การใส่ฟุริโซเดะ\nก็มีเรื่องที่ยุ่งยากอยู่ค่ะ"
10057-CVGroup_UIEventLobby_Idle3-2 = "แต่ว่านี่ก็เพื่อเส้นทางของอาหารรสเลิศค่ะ"
10057-CVGroup_UIEventLobby_Idle4-1 = "เพื่อเข้าถึงสุดยอดรสชาติจะต้องเตรียมใจ\nไม่หวั่นไหวกับอะไรทั้งนั้นค่ะ"
10057-CVGroup_UIEventLobby_Idle4-2 = "ไม่ว่าใคร... ก็ขัดขวางพวกเราไม่ได้ค่ะ ฮุฮุฮุ"
10057-CVGroup_UIEventLobby_Enter3-1 = "ถึงสถานการณ์จะยุ่งยากนิดหน่อยก็เถอะค่ะ..."
10057-CVGroup_UIEventLobby_Enter3-2 = "จิตใจที่ใฝ่หาอาหารเลิศรสของฉันไม่สั่นคลอน\nเพราะเรื่องแค่นี้หรอกค่ะ"
10057-CVGroup_UIEventLobby_Enter4-1 = "ฉันหวังว่าทุกคนจะทำให้ดีที่สุด"
10057-CVGroup_UIEventLobby_Enter4-2 = "ฉันจะชิมอาหารด้วยความจริงใจ\nและความกระตือรือร้นค่ะ"
10057-CVGroup_UIEventLobby_Enter5-1 = "ถึงเวลาจะผ่านไป เรื่องราวต่างๆ ก็คงจะถูกลืมใช่มั้ยคะ"
10057-CVGroup_UIEventLobby_Enter5-2 = "แต่ถ้าฉันกับคุณครูจำได้... มันจะไม่เป็นอะไรค่ะ"
10057-CVGroup_UIEventLobby_Enter5-3 = "ค่ะ ต้องไม่เป็นไรแน่ค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Enter1-1 = "คุณครูเอง... ก็มาเสี่ยงทายโอะมิกุจิเหรอคะ...?\nเชิญทางนี้เลยค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Enter1-2 = "ฮุฮุฮุ ไม่ต้องร้อนใจขนาดนั้นก็ได้ค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Enter2-1 = "ฮุฮุฮุ... ฉันเพิ่งเคยทำงานแบบนี้เลยค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Enter2-2 = "ไม่รู้ทำไม แต่สนุกมากเลยค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Idle1-1 = "เจอของที่หาอยู่หรือยังคะ?"
10057-CVGroup_UIEventFortuneGachaShop_Idle1-2 = "ฮุฮุฮุ ถ้าเป็นชิ้นนั้นละก็อาจจะอยู่ใกล้ๆ ก็ได้นะคะ?"
10057-CVGroup_UIEventFortuneGachaShop_Idle2-1 = "การหายใจเข้าลึกๆ และทำใจเย็นๆ\nก็เป็นเรื่องสำคัญเหมือนกันนะคะ"
10057-CVGroup_UIEventFortuneGachaShop_Idle2-2 = "ก็เหมือนกับขนมหวานที่ทานในอาหารคอร์สค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck5-1 = "ตายจริง โชคดีครั้งใหญ่เลยนี่คะ!\nสมกับที่เป็นคุณครูจริงๆ ดวงดีสุดๆ ไปเลยละค่ะ!"
10057-CVGroup_UIEventFortuneGachaShop_Luck5-2 = "ฉันเตรียมสินค้าพิเศษเอาไว้\nให้คุณครูที่เสี่ยงทายได้โชคดีครั้งใหญ่แล้วค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck4-1 = "ถ้าเสี่ยงทายได้โชคดีมาก แสดงว่าโชคกำลังมาแล้วค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck4-2 = "ขอให้ปีนี้เป็นปีที่สุดปังอีกหนึ่งปีนะคะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck3-1 = "โชคดีกลาง... ไม่เป็นไรนะคะ\nสินค้าสำหรับโชคดีกลาง อยู่ด้านนี้ค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck2-1 = "โชคดีเล็ก... ก็ไม่ได้แย่เลยนะคะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck2-2 = "ได้ยินว่าสิ่งสำคัญสำหรับการเรียกโชคดีให้มาหา\nคือการรวบรวมสิ่งเล็กๆ ไว้ด้วยกันค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck1-1 = "โชคดีนิดนึง... จะกลับมาเป็นโชคดีมากในภายหลังค่ะ..."
10057-CVGroup_UIEventFortuneGachaShop_Luck1-2 = "โชคดีสินะคะ\nค่ะ เชิญทางนี้เลยค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck0-1 = "ไม่เป็นไรค่ะ ผลเสี่ยงทายโอะมิกุจิ\nคือการทำนายดวงปัจจุบันค่ะ"
10057-CVGroup_UIEventFortuneGachaShop_Luck0-2 = "ในอนาคต... จะกลายเป็นโชคดีค่ะ..."
10057-CVGroup_UIEventFortuneGachaShop_Luck0-3 = "...คะ? ได้รับการปลอบใจจากฉันแล้ว\nมันทั้งสุขและเศร้าเลยเหรอคะ...?\nคะ... คือว่าเรื่องนั้น..."
10057-CVGroup_UIEventFortuneGachaShop_Enter3-1 = "คุณครูคะ ถ้าโอะมิกุจิละก็...\nยังเสี่ยงทายได้อยู่นะคะ\nอย่าลืมมาเสี่ยงทายนะคะ"
