[translation]
10051-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10051-CVGroup_CharacterGet_Idle1-1 = "หัวหน้ากองเชียร์ของมิลเลเนียม ชิราอิชิ อุทาฮะ\nขอส่งแรงเชียร์ให้ทุกคนด้วยความมุ่งมั่นที่ร้อนแรง และตรรกะที่สุขุม"
10051-CVGroup_Cafe_Idle1-1 = "เป็นสถานที่ที่เต็มไปด้วยความมุ่งมั่นจริงๆ นะ"
10051-CVGroup_Cafe_Idle2-1 = "ถ้าตั้งกองเชียร์ที่นี่ จะส่งเสียงเชียร์ไปได้ถึงที่ไหนกันนะ?"
10051-CVGroup_Cafe_Idle3-1 = "อยากลองทำแปรอักษรที่นี่ดูจังเลย..."
10051-CVGroup_Cafe_Idle4-1 = "(ฮุฮุ คิดวิธีเชียร์สนุกๆ ได้แล้วละ)"
10051-CVGroup_Cafe_Idle5-1 = "รู้สึกเหมือน... เสียงเชียร์ดังไม่พอเลย"
10051-CVGroup_WeaponGet_Idle1-1 = "เพียงแค่รู้สึกถึงความร้อนแรง ก็ปลุกไฟในตัวของไมสเตอร์ได้แล้วละ"
10051-CVGroup_UIEventLobby_Enter1-1 = "เอาละ มารวมพลังเพื่อ <ฮาโลเฟสติวัล> ที่ยอดเยี่ยมกันเลย!"
10051-CVGroup_UIEventLobby_Enter2-1 = "แบบนี้จะน่าสนุกมั้ยนะ..."
10051-CVGroup_UIEventLobby_Enter2-2 = "ไม่สิ ถ้าเป็นเรื่องเกียรติยศของมิลเลเนียมแล้วละก็"
10051-CVGroup_UIEventLobby_Enter2-3 = "ชมรมวิศวกรรมของเราก็ต้องไปช่วยอยู่แล้ว"
10051-CVGroup_UIEventLobby_Enter3-1 = "อืม การเตรียมตัวเพื่อ <ฮาโลเฟสติวัล> กำลังไปได้สวยเลยนะ"
10051-CVGroup_UIEventLobby_Enter4-1 = "ใกล้ถึงวันเปิดงาน <ฮาโลเฟสติวัล> แล้วละ"
10051-CVGroup_UIEventLobby_Enter4-2 = "ชักตื่นเต้นจนจะทนไม่ไหวแล้วแฮะ"
10051-CVGroup_UIEventLobby_Enter5-1 = "ทำได้ดีมากคุณครู แล้วฉันจะไปรอบนอัฒจันทร์เชียร์นะ"
10051-CVGroup_UIEventLobby_Idle1-1 = "ฉันยังไม่ชินกับการเชียร์เลย..."
10051-CVGroup_UIEventLobby_Idle1-2 = "แต่ก็ช่วยไม่ได้จะทำให้ดีที่สุดแล้วกัน"
10051-CVGroup_UIEventLobby_Idle1-3 = "มีคติชมรมวิศวกรรมบอกไว้ว่า"
10051-CVGroup_UIEventLobby_Idle1-4 = "ต้องทำภารกิจที่ได้รับมาให้สำเร็จน่ะ!"
10051-CVGroup_UIEventLobby_Idle2-1 = "จะว่าไป... ไม่เห็นนักบัญชีจอมเฮี้ยบของเซมิน่าเลยแฮะ"
10051-CVGroup_UIEventLobby_Idle2-2 = "หวังว่าคงไม่ได้เจ็บป่วยตรงไหนนะ"
10051-CVGroup_UIEventLobby_Idle3-1 = "(หวังว่าทุกคนจะมีความสุขกับเทศกาลนะ...)"
10051-CVGroup_UIEventLobby_Idle4-1 = "ถึงปกติจะไม่ได้มีเรื่องให้ขยับตัวเท่าไรก็เถอะ"
10051-CVGroup_UIEventLobby_Idle4-2 = "แต่พละกำลังของโคโทริกับฮิบิกิลดลงขนาดนี้เชียว..."
10051-CVGroup_UIEventLobby_Idle4-3 = "หลังจบงานเทศกาลคงต้องไปห้องชมรมวิศวกรรม"
10051-CVGroup_UIEventLobby_Idle4-4 = "แล้วสร้างหุ่นยนต์ฝึกพละกำลังแล้วดีมั้ยนะ?"
