[translation]
10050-CVGroup_UITitle_Idle1-1 = "블루 아카이브!"
10050-CVGroup_CharacterGet_Idle1-1 = "훈육지원부 '매화원'의 코코나입니다!\n아, 아닙니다! 이래도 어엿한 교관이라구요!?"
10050-CVGroup_Cafe_Idle1-1 = "이건, 도대체……?"
10050-CVGroup_Cafe_Idle2-1 = "뭔가 이상한 물건이 많네요."
10050-CVGroup_Cafe_Idle3-1 = "이거, 매화원에도 놓아 두고 싶은데……"
10050-CVGroup_Cafe_Idle4-1 = "슌 언니, 어디로 가 버렸을까……?"
10050-CVGroup_Cafe_Idle5-1 = "아이들의 교육에 좋겠어요."
10050-CVGroup_WeaponGet_Idle1-1 = "때로는 엄격하게, 때로는 상냥하게……\n해야 할 때 제대로 할 수 있는 것이, 좋은 교관이라고 생각합니다. 저도, 할 거예요!"
