[translation]
10060-CVGroup_UITitle_Idle1-1 = "Bluuue! Archiiive! ♪"
10060-CVGroup_CharacterGet_Idle1-1 = "Yay! What do you want me to work on? Where should I dig? I can excavate whatever you want!"
10060-CVGroup_Cafe_Idle1-1 = "Wow! So this is your...?"
10060-CVGroup_Cafe_Idle2-1 = "Not...these hot springs, right?"
10060-CVGroup_Cafe_Idle3-1 = "Well, since this place is yours, I'll make it an exception."
10060-CVGroup_Cafe_Idle4-1 = "Huh? Is that...? *gasp*"
10060-CVGroup_Cafe_Idle5-1 = "There sure are a lot of people! It's bustling. I like it!"
10060-CVGroup_WeaponGet_Idle1-1 = "What? You're giving me this? Why? Um, I don't understand... But I guess I'll just keep working hard! Hahaha!"
