[translation]
10074-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10074-CVGroup_CharacterGet_Idle1-1 = "The refreshing water feels so good. Sensei, do you like playing...in the water?"
10074-CVGroup_Cafe_Idle1-1 = "Oh my, that person..."
10074-CVGroup_Cafe_Idle2-1 = "What a cute place..."
10074-CVGroup_Cafe_Idle3-1 = "I think we'll get in trouble if we play in the water here."
10074-CVGroup_Cafe_Idle4-1 = "Heehee, I feel someone's eyes on me. ♡"
10074-CVGroup_Cafe_Idle5-1 = "May I get closer?"
10074-CVGroup_WeaponGet_Idle1-1 = "Life changes everyone, but the old me would never have imagined today's me. And it's all thanks to you, Sensei."
10074-CVGroup_UIEventLobby_Enter1-1 = "Shall we get started?"
10074-CVGroup_UIEventLobby_Enter2-1 = "This is the start of a fun summer event. Heehee!"
10074-CVGroup_UIEventLobby_Enter3-1 = "Ah... Is it too late to turn back...?"
10074-CVGroup_UIEventLobby_Enter4-1 = "We're almost there."
10074-CVGroup_UIEventLobby_Enter4-2 = "It's a little lonely..."
10074-CVGroup_UIEventLobby_Enter5-1 = "Let's look around to see if we missed anything."
10074-CVGroup_UIEventLobby_Idle1-1 = "Huh? What is it?"
10074-CVGroup_UIEventLobby_Idle2-1 = "Wow, Sensei, I've never seen this side of you. ♥"
10074-CVGroup_UIEventLobby_Idle3-1 = "You're going to remember everything you did here, Sensei?"
10074-CVGroup_UIEventLobby_Idle3-2 = "Just be ready...when you return. ♥"
10074-CVGroup_UIEventLobby_Idle4-1 = "Heeheehee... ♥"
10074-CVGroup_UIEventMission_Enter1-1 = "I'm excited to see what's in store for the future."
10074-CVGroup_UIEventMission_Enter2-1 = "Everyone is waiting for you, Sensei."
10074-CVGroup_UIEventMission_Idle1-1 = "Ah, something like that...in a place like this... ♥"
10074-CVGroup_UIEventMission_Idle2-1 = "Sensei, did something happen?"
10074-CVGroup_UIEventMission_Buy1-1 = "Wow, this is quite..."
10074-CVGroup_UIEventMission_Buy2-1 = "This was definitely worth all the hard work."
