[translation]
10078-CVGroup_UITitle_Idle1-1 = "블루 아카이브~!! 와핫핫핫!"
10078-CVGroup_CharacterGet_Idle1-1 = "와~핫핫핫! 거기에 온천이 있으니까 우리들이 있다!\n아니, 비록 온천이 없어도 우리들이 있다!\n자, 발파 준비는 다 돼 있다고!"
10078-CVGroup_Cafe_Idle1-1 = "오? 여기라면 꽤……?"
10078-CVGroup_Cafe_Idle2-1 = "여기다 온천을 만들면……."
10078-CVGroup_Cafe_Idle3-1 = "……이런, 위험하군. 곤란한 놈들이 있네."
10078-CVGroup_Cafe_Idle4-1 = "여기서도 또 숨어야 되는 건가?"
10078-CVGroup_Cafe_Idle5-1 = "음…… 심심하군…… 공부나 좀 해볼까."
10078-CVGroup_WeaponGet_Idle1-1 = "선생님…. 정말로 괜찮겠어? 나랑 함께하는 거, 꽤 고생길이라고?\n충고는 했다? 어떻게 되든 난 모르니까 말이야! 와핫핫핫핫!"
10078-CVGroup_UIEventLobby_Enter1-1 = "와핫핫하-! 또 보는구만, 선생님!"
10078-CVGroup_UIEventLobby_Enter2-1 = "선생님! 여기다, 여기! 기다리고 있었다고~?"
10078-CVGroup_UIEventLobby_Enter3-1 = "딱~ 바쁠 때 아닌가?"
10078-CVGroup_UIEventLobby_Enter3-2 = "보자, 좀 거들어 주지."
10078-CVGroup_UIEventLobby_Enter4-1 = "자~, 업무 종료 시간이 다가온다!"
10078-CVGroup_UIEventLobby_Enter4-2 = "너무 느긋하게 있을 여유는 없다고! 가자!"
10078-CVGroup_UIEventLobby_Enter5-1 = "고생 많았어, 선생님. 마지막으로 한 번 싹 훑어볼까?"
10078-CVGroup_UIEventLobby_Idle1-1 = "음? 뭐 할 말 있어?"
10078-CVGroup_UIEventLobby_Idle2-1 = "내가 반격하지 않을 거라고 생각하고 마음대로 하다니…… 각오하라고!"
10078-CVGroup_UIEventLobby_Idle3-1 = "그건 재촉하는 건가?"
10078-CVGroup_UIEventLobby_Idle3-2 = "……나중에 제~대로 책임, 질 수 있겠지?"
10078-CVGroup_UIEventLobby_Idle4-1 = "와핫핫핫하! 간지럼피우지 말라고! 간지러워!"
10078-CVGroup_UIEventShop_Enter1-1 = "자. 뭘 찾으시나?"
10078-CVGroup_UIEventShop_Enter2-1 = "자! 여기는 뭐든지 있어! 없는 것 말고는! 와핫핫핫!"
10078-CVGroup_UIEventShop_Enter3-1 = "곧 가게 마감이니까! 있는 만큼 가져가~!"
10078-CVGroup_UIEventShop_Idle1-1 = "응? 왜 그러지?"
10078-CVGroup_UIEventShop_Idle2-1 = "한눈팔면 다 팔려버린다!"
10078-CVGroup_UIEventShop_Buy1-1 = "음, 역시 그걸로 했구나. 선생님은 좋은 심미안을 가지고 있군."
10078-CVGroup_UIEventShop_Buy2-1 = "훌륭하구만!"
10078-CVGroup_UIEventShop_Buy3-1 = "과연! 그것도 나쁘지 않아!"
10078-CVGroup_UIEventShop_Buy4-1 = "그걸 갖고 싶었구나!"
