[translation]
10077-CVGroup_UITitle_Idle1-1 = "블루 아카이브~."
10077-CVGroup_CharacterGet_Idle1-1 = "어라, 데리러 와주신 검까? 말해줬으면 제가 갔을 텐데~\n다시 한번, 트리니티 종합학원 정의실현부의 이치카임다. 잘부탁드림다!"
10077-CVGroup_Cafe_Idle1-1 = "오, 여김까? 선생님의 카페!"
10077-CVGroup_Cafe_Idle2-1 = "과연. 이런 취향이셨군요……."
10077-CVGroup_Cafe_Idle3-1 = "여긴 평화로워서 좋네요!"
10077-CVGroup_Cafe_Idle4-1 = "편해진다……"
10077-CVGroup_Cafe_Idle5-1 = "정리라도 좀 도울까요……."
10077-CVGroup_WeaponGet_Idle1-1 = "뭐랄까……. 참. 이렇게 좋게 봐 주시는 건 당연히 감사함다만, 제게 그럴 가치가 있는지는…….\n그래도…… 기쁘네요. 정말로."
10077-CVGroup_UIEventLobby_Enter1-1 = "어서 오십쇼~! 이쪽은 준비만전임다!"
10077-CVGroup_UIEventLobby_Enter2-1 = "자, 슬슬 시작함다!"
10077-CVGroup_UIEventLobby_Enter3-1 = "앞으로 반, 남았을까요?"
10077-CVGroup_UIEventLobby_Enter4-1 = "거의 다 왔슴다. 도울 수 있는 것이 있다면 뭐든지 말해주십쇼!"
10077-CVGroup_UIEventLobby_Enter5-1 = "그럼, 쭉- 한번 둘러보겠슴다!"
10077-CVGroup_UIEventLobby_Idle1-1 = "네. 저 여기 있슴다."
10077-CVGroup_UIEventLobby_Idle2-1 = "음…? 아까부터 왜 그러심까?"
10077-CVGroup_UIEventLobby_Idle3-1 = "그런 장난은 좋지 않슴다~. 히히."
10077-CVGroup_UIEventLobby_Idle4-1 = "하하, 선생님.\n그렇게 몇 번이고 부르지 않으셔도 저는 여기서 상시 대기하고 있슴다."
10077-CVGroup_UIEventMission_Enter1-1 = "헉! 선생님! 딱 좋은 타이밍에!"
10077-CVGroup_UIEventMission_Enter2-1 = "리스트 체크 하실거죠? 이쪽에 준비해놨슴다!"
10077-CVGroup_UIEventMission_Idle1-1 = "앗! 뭐 하시는 검까, 선생님! 똑같은 짓 해버리는 수가 있어요?"
10077-CVGroup_UIEventMission_Idle2-1 = "…다음엔, 각오해 두십쇼!"
10077-CVGroup_UIEventMission_Buy1-1 = "네! 확인 완료임다~!"
10077-CVGroup_UIEventMission_Buy2-1 = "그검까? 정리해 두겠슴다!"
10077-CVGroup_UIEventMission_Interaction1-1 = "오늘은 이걸로 끝! 하핫! 선생님. 이제는 뭐 하실 검까?"
