[translation]
10073-CVGroup_UITitle_Idle1-1 = "브, 블루 아카이브……."
10073-CVGroup_CharacterGet_Idle1-1 = "으, 으으…. 그렇잖아도 밖은 싫은데….\n덥고 습하고…. 이래서 여름은…."
10073-CVGroup_Cafe_Idle1-1 = "아…. 여기도 사람이 잔뜩…."
10073-CVGroup_Cafe_Idle2-1 = "어디 혼자 조용히 있을 곳이…."
10073-CVGroup_Cafe_Idle3-1 = "이 모습 때문인지, 평소보다 정신없네…."
10073-CVGroup_Cafe_Idle4-1 = "하아…. 진짜."
10073-CVGroup_Cafe_Idle5-1 = "그래도 뭐… 여기 분위기는 나쁘지 않은 것 같기도."
10073-CVGroup_WeaponGet_Idle1-1 = "저. 새삼스러울지도 모릅니다만 이렇게까지 해주실만한 가치가…\n정말, 저에게 있는 것일까요…?\n죄송합니다, 이런 소리 하지 않기로 했죠. 최대한 해보겠습니다. 선생님의 바람이니까요."
10073-CVGroup_UIEventLobby_Enter1-1 = "여기에요, 선생님. 조사 준비는 다 해두었습니다."
10073-CVGroup_UIEventLobby_Enter2-1 = "여름은 무덥고……. 서 있는 것만으로, 힘에 겨워요…."
10073-CVGroup_UIEventLobby_Enter3-1 = "이제 절반 정도 왔나……."
10073-CVGroup_UIEventLobby_Enter4-1 = "곧 있으면, 이곳에서의 조사도 끝이네요."
10073-CVGroup_UIEventLobby_Enter5-1 = "마, 만약을 위해… 확인해 보시죠."
10073-CVGroup_UIEventLobby_Idle1-1 = "서, 선생님? 왜, 왜 그러시죠?"
10073-CVGroup_UIEventLobby_Idle1-2 = "제 얼굴에 뭔가 묻어 있나요...?"
10073-CVGroup_UIEventLobby_Idle2-1 = "갑자기 그렇게 부르셔도……."
10073-CVGroup_UIEventLobby_Idle3-1 = "필요한 게 있으시면, 말로 해 주세요……."
10073-CVGroup_UIEventLobby_Idle4-1 = "밖은, 좋아하지 않아도……."
10073-CVGroup_UIEventLobby_Idle4-2 = "단둘이 있을 수 있었고… 나쁘지만은 않네요."
10073-CVGroup_UIEventMission_Enter1-1 = "그럼, 조사 내용을 정리해 볼까요."
10073-CVGroup_UIEventMission_Enter2-1 = "여러가지, 알게 됐네요."
10073-CVGroup_UIEventMission_Idle1-1 = "음… 아직 뭔가 더 조사하실 거라도?"
10073-CVGroup_UIEventMission_Idle2-1 = "저, 저를 조사해도, 아무것도 안나와요…!"
10073-CVGroup_UIEventMission_Buy1-1 = "이건……. 의미가 있겠네요."
10073-CVGroup_UIEventMission_Buy2-1 = "역시, 선생님."
