[translation]
10073-CVGroup_UITitle_Idle1-1 = "蔚，蔚藍檔案……"
10073-CVGroup_CharacterGet_Idle1-1 = "唔，唔唔……我本來就已經不喜歡外面了……\n又熱又潮濕……所以才說夏天就是……"
10073-CVGroup_Cafe_Idle1-1 = "啊…這裡也全都是人…"
10073-CVGroup_Cafe_Idle2-1 = "有沒有…可以安靜獨處的地方…"
10073-CVGroup_Cafe_Idle3-1 = "不知道是不是因為這身服裝，感覺比平常更難以冷靜…"
10073-CVGroup_Cafe_Idle4-1 = "唉…真是的。"
10073-CVGroup_Cafe_Idle5-1 = "不過…這裡的氣氛，好像也不壞。"
10073-CVGroup_WeaponGet_Idle1-1 = "那個……事到如今說這些可能有點晚了……\n我真的，有讓你……為我付出這麼多的價值嗎……？\n……對不起，已經約好不再說這種話了對吧。\n我會盡己所能的。因為那是老師的願望。"
10073-CVGroup_UIEventLobby_Enter1-1 = "在這裡，老師。\n調查準備，已經完成了。"
10073-CVGroup_UIEventLobby_Enter2-1 = "夏天，又悶又熱……光，光是站著，就很費力了……"
10073-CVGroup_UIEventLobby_Enter3-1 = "這樣一來，就剩下一半了……"
10073-CVGroup_UIEventLobby_Enter4-1 = "再過不久，這裡的調查也要結束了呢。"
10073-CVGroup_UIEventLobby_Enter5-1 = "以，以防萬一……請確認一下。"
10073-CVGroup_UIEventLobby_Idle1-1 = "老，老師？怎，怎麼了？"
10073-CVGroup_UIEventLobby_Idle1-2 = "我的臉上，沾到什麼東西了嗎……？"
10073-CVGroup_UIEventLobby_Idle2-1 = "就算突然，叫我也……"
10073-CVGroup_UIEventLobby_Idle3-1 = "……有事的話，請用說的……"
10073-CVGroup_UIEventLobby_Idle4-1 = "外面，雖然我不是很喜歡……"
10073-CVGroup_UIEventLobby_Idle4-2 = "但可以兩人獨處……也不是什麼壞事。"
10073-CVGroup_UIEventMission_Enter1-1 = "那麼，來統整調查內容吧。"
10073-CVGroup_UIEventMission_Enter2-1 = "各種事情，都越來越明瞭了。"
10073-CVGroup_UIEventMission_Idle1-1 = "那個……還有什麼想調查的事嗎？"
10073-CVGroup_UIEventMission_Idle2-1 = "就，就算調查我，也不會有結果的唷……！"
10073-CVGroup_UIEventMission_Buy1-1 = "這個……似乎有某種意義呢。"
10073-CVGroup_UIEventMission_Buy2-1 = "不愧是您，老師。"
