[translation]
10080-CVGroup_UITitle_Idle1-1 = "蔚藍檔案。"
10080-CVGroup_CharacterGet_Idle1-1 = "哎呀，我應該有自我介紹過了才對……\n難道你不記得了嗎？唔呵呵。"
10080-CVGroup_Cafe_Idle1-1 = "哎呀，這裡的裝潢\n還挺可愛的嘛？"
10080-CVGroup_Cafe_Idle2-1 = "挺有品味的。"
10080-CVGroup_Cafe_Idle3-1 = "很多看起來很有趣的人呢。"
10080-CVGroup_Cafe_Idle4-1 = "總覺得……\n好像能平靜下來。"
10080-CVGroup_Cafe_Idle5-1 = "因為這裡是個\n令人放心的地方嗎……\n真不錯。"
10080-CVGroup_WeaponGet_Idle1-1 = "你也真是個奇怪的人呢。啊啊，我不是負面的意思。\n……一般來說無法讀心的對象，我是不會相信的……\n暫且先歸為「不會起疑的程度」吧？"
10080-CVGroup_UIEventLobby_Enter1-1 = "我在等你哦，老師。\n那麼就開始吧？"
10080-CVGroup_UIEventLobby_Enter2-1 = "需要我幫點忙嗎？"
10080-CVGroup_UIEventLobby_Enter2-2 = "這畢竟跟我們有關，我會幫忙的哦☆"
10080-CVGroup_UIEventLobby_Enter3-1 = "還順利嗎～？"
10080-CVGroup_UIEventLobby_Enter4-1 = "差不多能看見終點了嗎？"
10080-CVGroup_UIEventLobby_Enter5-1 = "有沒有還沒做完的事，最好再確認一次哦☆"
10080-CVGroup_UIEventLobby_Idle1-1 = "嘿～？居然做這種事啊？"
10080-CVGroup_UIEventLobby_Idle2-1 = "不是還有其他該做的事嗎？"
10080-CVGroup_UIEventLobby_Idle3-1 = "……我的忍耐也是有極限的喔☆"
10080-CVGroup_UIEventLobby_Idle4-1 = "……哎呀哎呀。這樣沒問題嗎？"
10080-CVGroup_UIEventMission_Enter1-1 = "來確認一下進度吧。"
10080-CVGroup_UIEventMission_Enter2-1 = "是來確認的吧。\n需要我幫點忙嗎？"
10080-CVGroup_UIEventMission_Idle1-1 = "「放棄」這個詞，感覺你似乎不知道呢？"
10080-CVGroup_UIEventMission_Idle2-1 = "嘿～？"
10080-CVGroup_UIEventMission_Buy1-1 = "還挺努力的嘛？\n值得稱讚哦☆"
10080-CVGroup_UIEventMission_Buy2-1 = "多少有幫上忙嘛？"
