[translation]
10080-CVGroup_UITitle_Idle1-1 = "블루 아카이브."
10080-CVGroup_CharacterGet_Idle1-1 = "어머, 자기소개는 했는데... 혹시 기억 안 나? 후훗."
10080-CVGroup_Cafe_Idle1-1 = "어머나, 꽤 귀여운 인테리어네?"
10080-CVGroup_Cafe_Idle2-1 = "센스 있네."
10080-CVGroup_Cafe_Idle3-1 = "재미있어 보이는 친구들이 많네?"
10080-CVGroup_Cafe_Idle4-1 = "왠지…… 진정될지도."
10080-CVGroup_Cafe_Idle5-1 = "신경 쓸 게 없는 곳이라 그런지, 나쁘지 않네."
10080-CVGroup_WeaponGet_Idle1-1 = "당신도 참 특이한 사람이네. 뭐, 나쁜 뜻으로 한 말은 아니야.\n보통은 머릿속을 읽지 않는 사람 따위, 믿지 않지만…….\n……'의심하지 않는 정도'로는 해 둘까?"
10080-CVGroup_UIEventLobby_Enter1-1 = "왔어, 선생님? 그럼 시작해볼까?"
10080-CVGroup_UIEventLobby_Enter2-1 = "뭐 도와줄까?"
10080-CVGroup_UIEventLobby_Enter2-2 = "이건 우리의 이야기니까, 협력할게☆"
10080-CVGroup_UIEventLobby_Enter3-1 = "잘 돼가는 중이야?"
10080-CVGroup_UIEventLobby_Enter4-1 = "슬슬 끝이 보이기 시작했나?"
10080-CVGroup_UIEventLobby_Enter5-1 = "못다한 일은 없는지, 다시 한번 확인해 보는 게 좋을 거야☆"
10080-CVGroup_UIEventLobby_Idle1-1 = "헤에~? 그렇게 나오는 거구나."
10080-CVGroup_UIEventLobby_Idle2-1 = "해야 할 게 따로 있으실 텐데?"
10080-CVGroup_UIEventLobby_Idle3-1 = "…내 참을성에도 한계가 있다구☆"
10080-CVGroup_UIEventLobby_Idle4-1 = "어라라……. 이거, 괜찮은 거야?"
10080-CVGroup_UIEventMission_Enter1-1 = "진행상황 한 번, 확인해 볼까?"
10080-CVGroup_UIEventMission_Enter2-1 = "확인하러 왔구나. 뭐 도와줄까?"
10080-CVGroup_UIEventMission_Idle1-1 = "포기, 라는 말을 모르는 타입인가 봐?"
10080-CVGroup_UIEventMission_Idle2-1 = "헤에…….?"
10080-CVGroup_UIEventMission_Buy1-1 = "꽤 열심히 했네? 칭찬해줄게☆"
10080-CVGroup_UIEventMission_Buy2-1 = "조금은 도움이 되지 않을까?"
