[translation]
10080-CVGroup_UITitle_Idle1-1 = "Blue Archive."
10080-CVGroup_CharacterGet_Idle1-1 = "Oh my, I've already introduced myself... Don't you remember? Heehee."
10080-CVGroup_Cafe_Idle1-1 = "Oh, the interior is darling!"
10080-CVGroup_Cafe_Idle2-1 = "Very sensible."
10080-CVGroup_Cafe_Idle3-1 = "And there are so many interesting friends here."
10080-CVGroup_Cafe_Idle4-1 = "Maybe...this isn't so dreadful."
10080-CVGroup_Cafe_Idle5-1 = "There's no need to overthink things while I'm here. No, this isn't so bad."
10080-CVGroup_WeaponGet_Idle1-1 = "You really are something else. Oh, I don't mean that in a bad way. I usually don't trust people whose thoughts I haven't read, but...let's just say that I don't find you suspicious."
10080-CVGroup_UIEventLobby_Enter1-1 = "Hello, Sensei. Shall we get started?"
10080-CVGroup_UIEventLobby_Enter2-1 = "What can I do for you?"
10080-CVGroup_UIEventLobby_Enter2-2 = "This is our story, so we may as well cooperate. ☆"
10080-CVGroup_UIEventLobby_Enter3-1 = "How do you do?"
10080-CVGroup_UIEventLobby_Enter4-1 = "Is the end in sight?"
10080-CVGroup_UIEventLobby_Enter5-1 = "Just to be thorough, why don't we check again? ☆"
10080-CVGroup_UIEventLobby_Idle1-1 = "Eeeh? So that's how you're playing it."
10080-CVGroup_UIEventLobby_Idle2-1 = "I'm sure you have something else you should be worrying about, no?"
10080-CVGroup_UIEventLobby_Idle3-1 = "...Even my patience has its limits. ☆"
10080-CVGroup_UIEventLobby_Idle4-1 = "Uh-oh... Is this all right?"
10080-CVGroup_UIEventMission_Enter1-1 = "Shall we take a look at your progress?"
10080-CVGroup_UIEventMission_Enter2-1 = "You're here to check in, I see. How may I help?"
10080-CVGroup_UIEventMission_Idle1-1 = "You're not the type of person who knows when to quit, hm?"
10080-CVGroup_UIEventMission_Idle2-1 = "Ehhh...?"
10080-CVGroup_UIEventMission_Buy1-1 = "I can tell that you've put the work in. Well done. ☆"
10080-CVGroup_UIEventMission_Buy2-1 = "Wouldn't this be a little useful?"
