[translation]
10088-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10088-CVGroup_CharacterGet_Idle1-1 = "สวัสดี ฉันไม่ค่อยชินกับชุดนี้เท่าไร\nถ้ามันดูแปลกๆ ก็ขอโทษนะ ฝากตัวด้วยนะครู"
10088-CVGroup_Cafe_Idle1-1 = "เซนส์ไม่เลวเลยนะเนี่ย"
10088-CVGroup_Cafe_Idle2-1 = "รู้สึกเหมือนมีคนจ้องอยู่เลย..."
10088-CVGroup_Cafe_Idle3-1 = "ฮึ่ม... ครูชอบอะไรแบบนี้สินะ?"
10088-CVGroup_Cafe_Idle4-1 = "รู้สึกสบายใจขึ้นมาเลย"
10088-CVGroup_Cafe_Idle5-1 = "มีที่ให้นั่งพักบ้างมั้ยนะ"
10088-CVGroup_WeaponGet_Idle1-1 = "บางทีฉันก็คิดว่าที่ผ่านมาได้รับอะไรตั้งมากมาย...\nแต่จะตอบแทนกลับดีๆ ได้บ้างมั้ย แต่ว่า...\nบางทีวันนั้นอาจจะไม่มาถึงก็ได้ งั้นฉันจะบอกไว้ก่อน\nขอบคุณนะครู ต่อไปฉันก็จะพยายามนะ"
10088-CVGroup_UIEventLobby_Enter1-1 = "กำลังรออยู่เลย\nครู ให้ฉันทำอะไรดี?"
10088-CVGroup_UIEventLobby_Enter2-1 = "อ่า... ฉันกำลังตามหาอยู่พอดีเลย ครู"
10088-CVGroup_UIEventLobby_Enter3-1 = "งานยุ่งกว่าที่คิดเลยนะ\nมารีบทำกันเถอะ ครู"
10088-CVGroup_UIEventLobby_Enter4-1 = "เวลาแทบจะไม่พอแล้วนะ\nแต่ไม่ต้องกังวลหรอก ฉันจะช่วยเอง"
10088-CVGroup_UIEventLobby_Enter5-1 = "จะเริ่มจัดการให้เรียบร้อยละนะ"
10088-CVGroup_UIEventLobby_Idle1-1 = "หืม...? เรียกฉันเหรอ?"
10088-CVGroup_UIEventLobby_Idle2-1 = "ครู... นี่ไม่ใช่เวลามาแกล้งกันเล่นนะ"
10088-CVGroup_UIEventLobby_Idle3-1 = "เฮ้อ... ถ้าจะเล่นน่ะ ก็รอให้งานเสร็จก่อน"
10088-CVGroup_UIEventLobby_Idle4-1 = "แต่ถ้าจะแกล้งกัน ฉันก็ไม่ว่าอะไรหรอก..."
10088-CVGroup_UIEventLobby_Idle4-2 = "ตอนนี้ฉันอยากให้หยุดได้แล้วละ"
10088-CVGroup_UIEventShop_Enter1-1 = "ต้องการเสบียงใช่มั้ย? นี่ไง"
10088-CVGroup_UIEventShop_Enter2-1 = "ถ้าอยากได้อะไรก็บอกนะ\nแล้วฉันจะเอามาให้"
10088-CVGroup_UIEventShop_Enter3-1 = "งานเสร็จแล้ว... ว่าแต่ ลืมอะไรรึเปล่า?"
10088-CVGroup_UIEventShop_Idle1-1 = "ถ้าบอกดีๆ แล้วฉันจะไปหามาให้"
10088-CVGroup_UIEventShop_Idle2-1 = "ครู ทำแบบนั้น... มันจั๊กจี้นิดหน่อยนะ"
10088-CVGroup_UIEventShop_Buy1-1 = "ต้องการอันนั้นสินะ"
10088-CVGroup_UIEventShop_Buy2-1 = "อยู่ตรงนี้นี่เอง\nฉันว่ามันจะช่วยได้แน่นอนเลย"
10088-CVGroup_UIEventShop_Buy3-1 = "โล่งอกไปทีนะที่มีอะไรดีๆ พอดี"
10088-CVGroup_UIEventShop_Buy4-1 = "เลือกได้ดีเลยละ"
10088-CVGroup_UIEventMission_Enter1-1 = "ฉันจัดการงานที่ทำอยู่ตอนนี้เรียบร้อยแล้ว\nมาดูด้วยกันสิครู"
10088-CVGroup_UIEventMission_Enter2-1 = "มาดูความคืบหน้าเหรอ?"
10088-CVGroup_UIEventMission_Idle1-1 = "ไม่รู้จักยอมแพ้เลยนะ ครูน่ะ"
10088-CVGroup_UIEventMission_Idle2-1 = "ได้ทำงานกับคุณครูนี่ดีจังเลย..."
10088-CVGroup_UIEventMission_Buy1-1 = "อืม คลี่คลายได้แล้ว"
10088-CVGroup_UIEventMission_Buy2-1 = "ไม่เลวเลยนะ"
10088-CVGroup_UIEventMission_Interaction1-1 = "งั้นก็จบงานวันนี้แล้ว"
