[translation]
10086-CVGroup_UITitle_Idle1-1 = "블루 아카이브."
10086-CVGroup_CharacterGet_Idle1-1 = "게헨나 학원 소속, 선도부장 소라사키 히나.\n그……. 선생님이 골라준 드레스를 입어, 봤는데.어울리, 려나……?"
10086-CVGroup_Cafe_Idle1-1 = "드레스 차림이면, 진정이 되질 않네……."
10086-CVGroup_Cafe_Idle2-1 = "어딘가 앉아서, 연습해 두고 싶은 참인데……."
10086-CVGroup_Cafe_Idle3-1 = "모두 반짝이고 있구나."
10086-CVGroup_Cafe_Idle4-1 = "후우, 어쩐지 조금 지쳤어……."
10086-CVGroup_Cafe_Idle5-1 = "선도부장으로서, 정신 똑바로 차려야겠지."
10086-CVGroup_WeaponGet_Idle1-1 = "이것을, 내게…. 고마워. 선생님.\n언제나 당신이 내게 주는 말, 신뢰. 그 올곧은 마음에, 나도 올곧게 답하고 싶어.\n그러니까 부디, 마지막까지 지켜봐 줘."
10086-CVGroup_UIEventLobby_Enter1-1 = "어서 와. 선생님."
10086-CVGroup_UIEventLobby_Enter1-2 = "판데모니움 소사이어티 때문에, 고생이겠지만…."
10086-CVGroup_UIEventLobby_Enter1-3 = "괜찮다면 도와줬으면 좋겠어."
10086-CVGroup_UIEventLobby_Enter2-1 = "왔구나. 선생님."
10086-CVGroup_UIEventLobby_Enter2-2 = "또 다시 부탁을 해서 미안해."
10086-CVGroup_UIEventLobby_Enter2-3 = "…신경 쓸 필요 없다고? 후후. 선생님답네."
10086-CVGroup_UIEventLobby_Enter3-1 = "아직도 계속되고 있구나…."
10086-CVGroup_UIEventLobby_Enter3-2 = "뭐, 간단히 끝나면 판데모니움 소사이어티가 아니겠지."
10086-CVGroup_UIEventLobby_Enter4-1 = "이렇게 계속하는데도 아직 끝나지 않는구나."
10086-CVGroup_UIEventLobby_Enter4-2 = "게걸스럽다고 할지. 탐욕스럽다고 할지."
10086-CVGroup_UIEventLobby_Enter4-3 = "뭐, 이쪽도 져줄 생각은 없지만."
10086-CVGroup_UIEventLobby_Enter5-1 = "드디어 끝났네."
10086-CVGroup_UIEventLobby_Enter5-2 = "떠들썩했던 날들도, 이렇게 막을 내리는 거구나."
10086-CVGroup_UIEventLobby_Enter5-3 = "…여러 가지 일이 있었지만."
10086-CVGroup_UIEventLobby_Enter5-4 = "조금이라도 선생님이 즐거웠다면 다행이야. 정말로."
10086-CVGroup_UIEventLobby_Idle1-1 = "판데모니움 소사이어티와 트러블이 있을 때마다 곤혹스럽지만…."
10086-CVGroup_UIEventLobby_Idle1-2 = "이번엔 선생님이 있어 줘서 다행이야."
10086-CVGroup_UIEventLobby_Idle2-1 = "갑작스럽게 파티 개최라니…"
10086-CVGroup_UIEventLobby_Idle2-2 = "정말 무슨 생각을 하고 있는 걸까."
10086-CVGroup_UIEventLobby_Idle2-3 = "……평소엔 알고 있느냐 하면, 그건 또 아니지만."
10086-CVGroup_UIEventLobby_Idle3-1 = "어떤 일이 있건, 선도부가 해야 할 일은 달라지지 않아."
10086-CVGroup_UIEventLobby_Idle3-2 = "늘 있는 일이니까."
10086-CVGroup_UIEventLobby_Idle4-1 = "이런 소동, 게헨나에서는 늘 있는 일이긴 해."
10086-CVGroup_UIEventLobby_Idle4-2 = "응? 게헨나가…… 무서워?"
10086-CVGroup_UIEventLobby_Idle4-3 = "그, 그 정도까진 아니라고 생각하는데…."
