[translation]
10087-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10087-CVGroup_CharacterGet_Idle1-1 = "Heehee. Oh, Sensei. How's my dress? Do give your honest opinion. I only need it as a reference."
10087-CVGroup_Cafe_Idle1-1 = "Right now, I'm a spy. Heehee."
10087-CVGroup_Cafe_Idle2-1 = "I wonder where President Hina is?"
10087-CVGroup_Cafe_Idle3-1 = "This outfit is quite comfortable and easy to move in. ...It does feel a bit cold."
10087-CVGroup_Cafe_Idle4-1 = "Phew. I hope there's no trouble, at least for today."
10087-CVGroup_Cafe_Idle5-1 = "(Heehee. I should take my time with this...)"
10087-CVGroup_WeaponGet_Idle1-1 = "Thank you for your continued support. As you know, Sensei... I, Amau Ako, have never let you down. Not now, and not ever. I look forward to continue working with you."
10087-CVGroup_UIEventLobby_Enter1-1 = "Welcome, Sensei."
10087-CVGroup_UIEventLobby_Enter1-2 = "Are you ready?"
10087-CVGroup_UIEventLobby_Enter1-3 = "Be prepared. Stay strong."
10087-CVGroup_UIEventLobby_Enter2-1 = "All the proper preparations are in place."
10087-CVGroup_UIEventLobby_Enter2-2 = "As the Senior Administrator of Gehenna's Prefect Team..."
10087-CVGroup_UIEventLobby_Enter2-3 = "Now is the time to take a stand."
10087-CVGroup_UIEventLobby_Enter3-1 = "You think this won't be resolved easily?"
10087-CVGroup_UIEventLobby_Enter3-2 = "Well, I can't simply give up."
10087-CVGroup_UIEventLobby_Enter4-1 = "Seriously! You are persistent!"
10087-CVGroup_UIEventLobby_Enter4-2 = "Phew, yeah, all right!"
10087-CVGroup_UIEventLobby_Enter4-3 = "With that, I should be ready to fight until the end!"
10087-CVGroup_UIEventLobby_Enter4-4 = "Now, please, Sensei! Let's go!"
10087-CVGroup_UIEventLobby_Enter5-1 = "It's finally over..."
10087-CVGroup_UIEventLobby_Enter5-2 = "Wow. There really was a lot going on today..."
10087-CVGroup_UIEventLobby_Enter5-3 = "It feels like all the tension has been completely drained out of me."
10087-CVGroup_UIEventLobby_Enter5-4 = "...Would you like to head back and grab a cup of coffee, Sensei?"
10087-CVGroup_UIEventLobby_Idle1-1 = "As for the party..."
10087-CVGroup_UIEventLobby_Idle1-2 = "How is this all going to turn out?"
10087-CVGroup_UIEventLobby_Idle2-1 = "Well, it doesn't matter..."
10087-CVGroup_UIEventLobby_Idle2-2 = "Whatever happens, the Prefect Team..."
10087-CVGroup_UIEventLobby_Idle2-3 = "No, I will be there to solve it!"
10087-CVGroup_UIEventLobby_Idle3-1 = "Right now, I'm just a spy backing Head Prefect Hina."
10087-CVGroup_UIEventLobby_Idle3-2 = "I've been holding back. Maybe it's time that I showed off my true skills."
10087-CVGroup_UIEventLobby_Idle3-3 = "Heehee. Look forward to it."
10087-CVGroup_UIEventLobby_Idle4-1 = "And here I thought it would be quiet this year..."
10087-CVGroup_UIEventLobby_Idle4-2 = "But I guess that'd be too much to ask for in Gehenna. Phew."
10087-CVGroup_UIEventMission_Enter1-1 = "Welcome, Sensei."
10087-CVGroup_UIEventMission_Enter1-2 = "I had something I was hoping that you could solve for me."
10087-CVGroup_UIEventMission_Enter1-3 = "Could you help me?"
10087-CVGroup_UIEventMission_Enter2-1 = "Heehee. No running away, now! Especially after coming this far."
10087-CVGroup_UIEventMission_Enter2-2 = "Yup, your to-do list is filled to the brim. ♪"
10087-CVGroup_UIEventMission_Idle1-1 = "That's right. If you're thinking of playing hooky, you better think again."
10087-CVGroup_UIEventMission_Idle1-2 = "I'll be right next to you. Carefully monitoring... I mean assisting you."
10087-CVGroup_UIEventMission_Idle2-1 = "I can understand the desire to do anything but the task right before you."
10087-CVGroup_UIEventMission_Idle2-2 = "However, that extra stuff can wait until after your work is done."
10087-CVGroup_UIEventMission_Idle2-3 = "You follow?"
10087-CVGroup_UIEventMission_Buy1-1 = "Hmm... Not bad."
10087-CVGroup_UIEventMission_Buy1-2 = "A fine reward for fine work. It's only natural."
10087-CVGroup_UIEventMission_Buy2-1 = "Oh my... You solved it in a single try?"
10087-CVGroup_UIEventMission_Buy2-2 = "Wow... I'm impressed. Truly. As expected of you, Sensei."
10087-CVGroup_UIEventMission_Interaction1-1 = "There. That's the end of today's tasks."
10087-CVGroup_UIEventMission_Interaction1-2 = "Great work, Sensei."
