[translation]
10085-CVGroup_UITitle_Idle1-1 = "蔚藍，檔案。"
10085-CVGroup_CharacterGet_Idle1-1 = "收不到電波的這種情況……\n對駭客來說是很殘酷的環境，但身為貝里塔斯的成員，不會就這樣放棄。"
10085-CVGroup_Cafe_Idle1-1 = "這裡很溫暖，真棒…"
10085-CVGroup_Cafe_Idle2-1 = "（穿成那樣…不會冷嗎…？）"
10085-CVGroup_Cafe_Idle3-1 = "來杯妖怪MAX。\n不用攪拌…也不要搖晃。"
10085-CVGroup_Cafe_Idle4-1 = "（太舒服了…真想永遠待在這裡…）"
10085-CVGroup_Cafe_Idle5-1 = "（好多名字很怪的Wi-Fi…）"
10085-CVGroup_WeaponGet_Idle1-1 = "我在爬山時再次感覺到了槍的重量……\n下次就來嘗試改造成輕量型的吧。"
10085-CVGroup_UIEventLobby_Enter1-1 = "好冷……想趕快回到溫暖的室內……"
10085-CVGroup_UIEventLobby_Enter2-1 = "竟然在這種時期露營……"
10085-CVGroup_UIEventLobby_Enter2-2 = "副部長，真過分。"
10085-CVGroup_UIEventLobby_Enter3-1 = "這裡……根本沒什麼……能做的事……"
10085-CVGroup_UIEventLobby_Enter4-1 = "附，附近有熊出沒……？"
10085-CVGroup_UIEventLobby_Enter4-2 = "待在這裡真的沒問題嗎？"
10085-CVGroup_UIEventLobby_Enter5-1 = "雖然有點辛苦，但偶爾感受這種經驗也不……"
10085-CVGroup_UIEventLobby_Enter5-2 = "我，我是說偶爾，真的偶爾就好……！"
10085-CVGroup_UIEventLobby_Idle1-1 = "最近的便利商店……在那座山的另一邊……"
10085-CVGroup_UIEventLobby_Idle2-1 = "（Wi-Fi……消失了？）"
10085-CVGroup_UIEventLobby_Idle3-1 = "熱的能量飲料……"
10085-CVGroup_UIEventLobby_Idle3-2 = "平常不會考慮，但只限今天的話，或許還能接受……"
10085-CVGroup_UIEventLobby_Idle4-1 = "老師也真辛苦呢。\n明明都年底了，還被抓來這種地方。"
10085-CVGroup_UIEventLobby_Idle4-2 = "咦？現在的狀況也挺愉快的……？"
10085-CVGroup_UIEventLobby_Idle4-3 = "……果然老師是陽角嗎。"
10085-CVGroup_UIEventShop_Enter1-1 = "……老師也是被副部長叫來的嗎？"
10085-CVGroup_UIEventShop_Enter1-2 = "不介意的話，幫我個小忙，可以嗎……？"
10085-CVGroup_UIEventShop_Enter2-1 = "唔，唔啊！\n……啊，老師……"
10085-CVGroup_UIEventShop_Enter2-2 = "抱歉，我以為是熊……"
10085-CVGroup_UIEventShop_Enter3-1 = "收拾必須確實完成。"
10085-CVGroup_UIEventShop_Enter3-2 = "不然之後副部長要是生氣可就不好了。"
10085-CVGroup_UIEventShop_Idle1-1 = "採集……如果這是遊戲，只要點一下就行了說……"
10085-CVGroup_UIEventShop_Idle2-1 = "怎麼了？衣服沾到什麼了嗎？"
10085-CVGroup_UIEventShop_Buy1-1 = "也對，這樣應該可行。"
10085-CVGroup_UIEventShop_Buy2-1 = "要給我這個？"
10085-CVGroup_UIEventShop_Buy2-2 = "謝謝，我也把收集到的給你。"
10085-CVGroup_UIEventShop_Buy3-1 = "已經收集這麼多了？"
10085-CVGroup_UIEventShop_Buy3-2 = "……老師你，原來有露營的才能啊……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Enter1-1 = "啊，老師。我正在煮咖哩。"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Enter2-1 = "看著正在咕嘟咕嘟的鍋子……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Enter2-2 = "莫名有種安穩的感覺……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Enter3-1 = "咖哩已經準備好了……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Enter3-2 = "如果其他想加入的材料就告訴我吧。"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Idle1-1 = "嗯……這樣能順利煮好嗎？"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Idle1-2 = "老師，可以幫我試試味道嗎？"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Idle2-1 = "為了增加咖哩的風味，似乎能加入巧克力……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Idle2-2 = "……既然如此，加入能量飲料應該也……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Luck4-1 = "啊…！超好吃的！"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Luck4-2 = "咖哩居然能有這種味道……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Luck3-1 = "嗯，這個很好吃。"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Luck2-1 = "和即食咖哩相比，還算普通好吃吧。"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Luck1-1 = "是，是讓人印象深刻的味道呢……"
10085-CVGroup_UIEventFortuneGachashop_Cooking_Luck0-1 = "唔……抱歉，這我沒辦法吃……"
