[translation]
10081-CVGroup_UITitle_Idle1-1 = "蔚藍～～～檔案，的說！"
10081-CVGroup_CharacterGet_Idle1-1 = "小女子名叫勘解由小路紫！\n身為榮譽百花繚亂的一員……\n我會為了老師，誠心誠意地竭盡全力！"
10081-CVGroup_Cafe_Idle1-1 = "呼呣呼呣原來如此，\n這裡就是夏～萊……！\n……真是個雅緻的地方！"
10081-CVGroup_Cafe_Idle2-1 = "雖然一大早就開始鍛鍊…\n呼啊，睏意突然來襲了。"
10081-CVGroup_Cafe_Idle3-1 = "（總覺得，有股不尋常的氣息……夏～萊或許是伏魔殿也說不定！）"
10081-CVGroup_Cafe_Idle4-1 = "嘿咻。身為百花繚亂的一員，若是不能擔任眾人的模範…"
10081-CVGroup_Cafe_Idle5-1 = "哼哼～哼～♪\n紫快速進擊～！"
10081-CVGroup_WeaponGet_Idle1-1 = "咦？要把這個，給小女子……？\n是信賴的象徵……？也就是信物嗎！？\n既然如此，小女子為了不讓老師失望，今後也會讓傳說延續下去！"
