[translation]
10097-CVGroup_UITitle_Idle1-1 = "블루 아카이브!"
10097-CVGroup_CharacterGet_Idle1-1 = "RABBIT 3, 현장에 도착~\n쿠히히… 바다 위에서라면, 마음껏 폭탄을 사용해도 괜찮겠지?"
10097-CVGroup_Cafe_Idle1-1 = "어딘가에 수류탄이 떨어져 있지 않으려나…"
10097-CVGroup_Cafe_Idle2-1 = "하아… 지쳤다…"
10097-CVGroup_Cafe_Idle3-1 = "파멸의 향기가…"
10097-CVGroup_Cafe_Idle4-1 = "쿠히히… 이 버튼은 어디에 연결되어 있으려나…"
10097-CVGroup_Cafe_Idle5-1 = "이 카페의 방화벽은 쓸데없이 튼튼하단 말이지…"
10097-CVGroup_WeaponGet_Idle1-1 = "RABBIT 224식 권총, 수령 완료.\n그나저나 나는 물에 들어갈 일도 없는데, 방수 처리도 해야 하는 거야? 귀찮게시리…"
10097-CVGroup_UIEventLobby_Enter1-1 = "이곳이 새우로 유명한 야토우라 마을…"
10097-CVGroup_UIEventLobby_Enter1-2 = "직접 와보는 건 처음이네."
10097-CVGroup_UIEventLobby_Enter2-1 = "도대체 이 마을에서 무슨 일이 벌어지고 있는 거야?"
10097-CVGroup_UIEventLobby_Enter3-1 = "<깊은 곳의 존재들> 말이야…"
10097-CVGroup_UIEventLobby_Enter3-2 = "그 소문이 사실이라면 엄청나게 큰 폭탄에도 견딜 수 있으려나?"
10097-CVGroup_UIEventLobby_Enter4-1 = "그 쿠사야라는 거, 발효만으로도 그렇게 강렬한 향기가 나는 거야?"
10097-CVGroup_UIEventLobby_Enter4-2 = "한 번 만들어 보고 싶은 걸… 쿠히히"
10097-CVGroup_UIEventLobby_Enter5-1 = "후후. 이제 다시"
10097-CVGroup_UIEventLobby_Enter5-2 = "맛있는 바질 새우 샌드위치를 맛볼 수 있으려나?"
10097-CVGroup_UIEventLobby_Idle1-1 = "안개 탓인가…?"
10097-CVGroup_UIEventLobby_Idle1-2 = "여름인데도 조금 서늘한 느낌이네…"
10097-CVGroup_UIEventLobby_Idle2-1 = "으음, 확실히. 어디선가 파멸의 향기가 느껴지는 걸…"
10097-CVGroup_UIEventLobby_Idle3-1 = "SRT의 작전이라지만,"
10097-CVGroup_UIEventLobby_Idle3-2 = "그래도 여름 바다에 나오니 조금은 기분 전환이 되는 것 같네."
10097-CVGroup_UIEventLobby_Idle4-1 = "이 튜브가 수상해 보인다고?"
10097-CVGroup_UIEventLobby_Idle4-2 = "뭐, 평범하게 물놀이할 때 쓰는 튜브는 아니지. 후후…"
