[translation]
10091-CVGroup_UITitle_Idle1-1 = "아, 아……. 블루 아카이브."
10091-CVGroup_CharacterGet_Idle1-1 = "보컬이라니…… 뭐, 이렇게 된 이상 열심히 할게. 잘 부탁해, 선생님."
10091-CVGroup_Cafe_Idle1-1 = "우와……. 사람 많아! 괜찮아? 여기."
10091-CVGroup_Cafe_Idle2-1 = "여기서 부르면 튀겠지?"
10091-CVGroup_Cafe_Idle3-1 = "좀 불렀더니, 배고파졌네."
10091-CVGroup_Cafe_Idle4-1 = "튀지는 않지? ……뭐, 너무 신경 쓰는 건가."
10091-CVGroup_Cafe_Idle5-1 = "다들, 어디 있는 거야."
10091-CVGroup_WeaponGet_Idle1-1 = "정말, 설마 이렇게 될 줄이야.\n후후… 새삼스럽지만, 선생님을 만나서 정말 다행이다.\n……감사합니다."
10091-CVGroup_UIEventLobby_Enter1-1 = "어서 와, 선생님!"
10091-CVGroup_UIEventLobby_Enter1-2 = "연습 좀 도와줄 수 있어?"
10091-CVGroup_UIEventLobby_Enter2-1 = "아, 아. 아아아~."
10091-CVGroup_UIEventLobby_Enter2-2 = "……!? 으, 으에엑!? 선생님!? 언제부터……!"
10091-CVGroup_UIEventLobby_Enter3-1 = "잘 되고 있는 느낌이…… 들기도 하고,"
10091-CVGroup_UIEventLobby_Enter3-2 = "아닌 거 같기도 하고……."
10091-CVGroup_UIEventLobby_Enter4-1 = "집중, 집중!"
10091-CVGroup_UIEventLobby_Enter4-2 = "아직 안 끝났어!"
10091-CVGroup_UIEventLobby_Enter5-1 = "후우……."
10091-CVGroup_UIEventLobby_Enter5-2 = "선생님. 그……."
10091-CVGroup_UIEventLobby_Enter5-3 = "어, 어땠어……?"
10091-CVGroup_UIEventLobby_Idle1-1 = "……? 마이크에 관심 있어?"
10091-CVGroup_UIEventLobby_Idle1-2 = "선생님도 한 곡, 부를래?"
10091-CVGroup_UIEventLobby_Idle2-1 = "응? 뭐 필요한 거라도 있어?"
10091-CVGroup_UIEventLobby_Idle3-1 = "정말… 또 건드리네…."
10091-CVGroup_UIEventLobby_Idle3-2 = "이번에야말로 화낸다?"
10091-CVGroup_UIEventLobby_Idle4-1 = "아아, 정말!"
10091-CVGroup_UIEventLobby_Idle4-2 = "볼일이 있으면, 제대로 말로 해!"
10091-CVGroup_UIEventMission_Enter1-1 = "안녕하세요, 오늘도 상황 보러 왔어?"
10091-CVGroup_UIEventMission_Enter2-1 = "진행 상태를 보러 온 거지?"
10091-CVGroup_UIEventMission_Idle1-1 = "나만 보지 말고, 제대로 집중해."
10091-CVGroup_UIEventMission_Idle2-1 = "어허! 안 돼."
10091-CVGroup_UIEventMission_Buy1-1 = "응. 체크했어."
10091-CVGroup_UIEventMission_Buy2-1 = "오오, 잘됐네."
10091-CVGroup_UIEventMission_Interaction1-1 = "오늘은 이것으로 끝! 수고했어, 선생님."
