[translation]
10094-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10094-CVGroup_CharacterGet_Idle1-1 = "คิดยังไงกับเมดเหรอ คุณครู?\nนี่น่าจะเป็นหัวข้อสนทนาที่ดีที่สุดเลยว่ามั้ย?"
10094-CVGroup_Cafe_Idle1-1 = "คาเฟ่... เมด... \nเหมือนมันจะเกี่ยวข้องกัน แต่ก็ไม่เกี่ยวกัน..."
10094-CVGroup_Cafe_Idle2-1 = "ถ้าฉันทำงานที่นี่... ก็ต้องถูพื้นนี่ทั้งหมดเลยสินะ... อึก..."
10094-CVGroup_Cafe_Idle3-1 = "เค้ก... ชาแดง... น่าอร่อยจัง...\nเอ๋? ฉันเหรอที่ต้องเป็นคนไปเตรียมมา?"
10094-CVGroup_Cafe_Idle4-1 = "อยากไปแอบหลับที่ไหนสักที่จัง..."
10094-CVGroup_Cafe_Idle5-1 = "การท่องเที่ยวของเมดที่เริ่มจากคาเฟ่!\nพล็อตเรื่องประมาณนี้ดีมั้ยนะ...?"
10094-CVGroup_WeaponGet_Idle1-1 = "ฟังนะคุณครู! สิ่งสำคัญที่สุดสำหรับเมดก็คือไอเทม!\nเพื่อลักลอบ เพื่อระเบิด ล้วงความลับ และเพื่อสันติสุขของโลก...\nถ้าจะทำเรื่องแบบนั้นก็ต้องมีไอเทมดีๆ นะ!"
10094-CVGroup_UIEventLobby_Enter1-1 = "มาแล้ว! เห็นแล้ว! แล้วก็ชนะแล้ว... มั้ยนะ?"
10094-CVGroup_UIEventLobby_Enter1-2 = "เอาเป็นว่า! เมดไซบะ โมโมอิได้เวลาออกโรงแล้ว!"
10094-CVGroup_UIEventLobby_Enter2-1 = "อ๊ะ คุณครู! ทำไมไม่เตรียมตัว...!"
10094-CVGroup_UIEventLobby_Enter2-2 = "เอ๋...? เดี๋ยวสิ เดี๋ยวๆ รอกันก่อนสิ คุณครู!"
10094-CVGroup_UIEventLobby_Enter3-1 = "แงงง... งานเยอะจังเลย!"
10094-CVGroup_UIEventLobby_Enter3-2 = "คิดไม่ถึงเลยว่าจะเป็นแบบนี้..."
10094-CVGroup_UIEventLobby_Enter4-1 = "ไม่เข้าใจ ไม่เข้าใจเลย..."
10094-CVGroup_UIEventLobby_Enter4-2 = "โจร? ประมูล? งานศิลปะ?\nนี่มันอะไรกัน! พล็อตเกมเหรอ!?"
10094-CVGroup_UIEventLobby_Enter5-1 = "ถึงจะเกิดเรื่องมากมาย แต่เหล่าผู้กล้าก็ปราบคนชั่ว"
10094-CVGroup_UIEventLobby_Enter5-2 = "และกลับมายังฐานของตัวเองได้อย่างองอาจ...!"
10094-CVGroup_UIEventLobby_Enter5-3 = "ก็จบประมาณนั้นละ คุณครู พยายามได้ดีมากเลย!"
10094-CVGroup_UIEventLobby_Idle1-1 = "หืม? อยากเห็นฉันตอนทำงานเมดเหรอ...?"
10094-CVGroup_UIEventLobby_Idle1-2 = "ก็นะ ก็ฉันใส่ชุดเมดอยู่แล้วนี่! อื้ม!"
10094-CVGroup_UIEventLobby_Idle2-1 = "ทำไมวิชาเมดไม่มีให้โดดงาน แล้วนอนกลางวันเลยนะ?"
10094-CVGroup_UIEventLobby_Idle2-2 = "คุณครูไม่คิดเหรอว่านี่คือปัญหาน่ะ?"
10094-CVGroup_UIEventLobby_Idle3-1 = "จริงสิ! นี่ คุณครู รู้อะไรหรือเปล่า? ว่าคฤหาสน์หลังนี้น่ะ..."
10094-CVGroup_UIEventLobby_Idle3-2 = "ซ่อนความลับสุดยอดเอาไว้เลยนะ!\nลางสังหรณ์ของฉันบอกมาอย่างนั้นน่ะ!"
10094-CVGroup_UIEventLobby_Idle4-1 = "จะ... จั๊กจี้นะ! คุณครู!\nฉันเป็นคนบ้าจี้นะ!"
10094-CVGroup_UIEventLobby_Idle4-2 = "แต่ก็ใช่ว่าจะไม่ชอบหรอก!"
