[translation]
10091-CVGroup_UITitle_Idle1-1 = "อ่า... อ่า... Blue Archive"
10091-CVGroup_CharacterGet_Idle1-1 = "ฉันได้ร้องนำเหรอเนี่ย... ก็ได้ ในเมื่อเป็นแบบนี้แล้ว\n ฉันจะพยายามแล้วกัน รบกวนด้วยนะคุณครู"
10091-CVGroup_Cafe_Idle1-1 = "ว้าว... คนเยอะจัง! ที่นี่จะโอเคมั้ยนะ?"
10091-CVGroup_Cafe_Idle2-1 = "ถ้าฉันร้องเพลงที่นี่ คงดึงดูดสายตาอยู่เนอะ?"
10091-CVGroup_Cafe_Idle3-1 = "พอใช้พลังร้องไปนิดหน่อย ก็เริ่มหิวซะแล้ว"
10091-CVGroup_Cafe_Idle4-1 = "ยังไม่สะดุดตาใครใช่มั้ย? เฮ้อ... ฉันคิดมากไปมั้ยนะ"
10091-CVGroup_Cafe_Idle5-1 = "ทุกคนไปอยู่ไหนกันน่ะ"
10091-CVGroup_WeaponGet_Idle1-1 = "จริงๆ เลยเชียว คิดไม่ถึงเลยว่าจะเป็นแบบนี้\nฮุฮุ... ถึงจะไม่เคยบอกมาก่อนก็เถอะ\nแต่ฉันโชคดีจริงๆ ที่ได้เจอคุณครู ขอบคุณนะคะ..."
10091-CVGroup_UIEventLobby_Enter1-1 = "เข้ามาสิ คุณครู!"
10091-CVGroup_UIEventLobby_Enter1-2 = "พอจะช่วยซ้อมดนตรีหน่อยได้มั้ย?"
10091-CVGroup_UIEventLobby_Enter2-1 = "อ่า... อ่า อ้าาา~"
10091-CVGroup_UIEventLobby_Enter2-2 = "วะ... เหวออออ!? คุณครู!? มาตั้งแต่ตอนไหน...!"
10091-CVGroup_UIEventLobby_Enter3-1 = "ฉันรู้สึกว่า... กำลังเป็นไปได้ด้วยดี"
10091-CVGroup_UIEventLobby_Enter3-2 = "แต่ก็เหมือนจะไม่ดีด้วย..."
10091-CVGroup_UIEventLobby_Enter4-1 = "ตั้งใจหน่อย ตั้งใจ!"
10091-CVGroup_UIEventLobby_Enter4-2 = "ยังไม่จบแค่นี้หรอกนะ!"
10091-CVGroup_UIEventLobby_Enter5-1 = "ฮู้ว..."
10091-CVGroup_UIEventLobby_Enter5-2 = "คุณครู... คือ..."
10091-CVGroup_UIEventLobby_Enter5-3 = "ปะ... เป็นไงบ้าง...?"
10091-CVGroup_UIEventLobby_Idle1-1 = "สนใจไมโครโฟนขึ้นมาเหรอ...?"
10091-CVGroup_UIEventLobby_Idle1-2 = "คุณครูอยากร้องสักเพลงมั้ย?"
10091-CVGroup_UIEventLobby_Idle2-1 = "หืม? มีอะไรที่อยากได้งั้นเหรอ?"
10091-CVGroup_UIEventLobby_Idle3-1 = "จริงๆ เลย... มากวนกันอีกแล้ว..."
10091-CVGroup_UIEventLobby_Idle3-2 = "ครั้งนี้ฉันจะโกรธแล้วนะ"
10091-CVGroup_UIEventLobby_Idle4-1 = "อ่า... จริงๆ เลย!"
10091-CVGroup_UIEventLobby_Idle4-2 = "ถ้ามีธุระจะคุย ก็บอกกันดีๆ สิ!"
10091-CVGroup_UIEventMission_Enter1-1 = "สวัสดี วันนี้ก็มาดูสถานการณ์เหรอ?"
10091-CVGroup_UIEventMission_Enter2-1 = "มาดูความคืบหน้าใช่มั้ย?"
10091-CVGroup_UIEventMission_Idle1-1 = "อย่าเอาแต่มองฉันสิ มีสมาธิหน่อย"
10091-CVGroup_UIEventMission_Idle2-1 = "เดี๋ยวเหอะ! ไม่ได้นะ"
10091-CVGroup_UIEventMission_Buy1-1 = "อื้อ โอเค"
10091-CVGroup_UIEventMission_Buy2-1 = "โอ้ ดีเลยนะ"
10091-CVGroup_UIEventMission_Interaction1-1 = "วันนี้จบแค่นี้!\nทำได้ดีมากเลยคุณครู"
