[translation]
10106-CVGroup_UITitle_Idle1-1 = "Blue Archive"
10106-CVGroup_CharacterGet_Idle1-1 = "ฮุฮุฮุ ตกใจเหรอคะ?\nฉันในตอนนี้ต่างกับเมื่อก่อนอย่างแน่นอนค่ะ"
10106-CVGroup_Cafe_Idle1-1 = "ระ... หรือรู้อยู่แล้วว่าเป็นฉันคะ...?"
10106-CVGroup_Cafe_Idle2-1 = "ในเมื่อเป็นแบบนี้แล้ว งั้นก็ขอร้องสักเพลงนะคะ...!"
10106-CVGroup_Cafe_Idle3-1 = "ไม่รู้ทำไมถึงไม่หายตื่นเต้นเลยค่ะ"
10106-CVGroup_Cafe_Idle4-1 = "ฮุฮุ... โล่งใจขึ้นมาหน่อยนะคะ"
10106-CVGroup_Cafe_Idle5-1 = "คนคนนั้น... มองฉันอยู่หรือเปล่าคะ?"
10106-CVGroup_WeaponGet_Idle1-1 = "ให้สิ่งนั้นกับฉันเหรอ...?\nไม่ค่ะ ไม่ว่าจะลุคไหน ฉันก็คือฉันค่ะ\nพูดถูกแล้วละค่ะ ฉันจะรับไว้ค่ะ\nขอบคุณนะคะ คุณครู"
10106-CVGroup_UIEventLobby_Enter1-1 = "อ่า~ อ่า~ อ่า อ่า~"
10106-CVGroup_UIEventLobby_Enter1-2 = "อ๊ะ... คะ... คุณครู!?"
10106-CVGroup_UIEventLobby_Enter2-1 = "ขอบคุณที่มานะคะ คุณครู"
10106-CVGroup_UIEventLobby_Enter2-2 = "ซะ... ซากุระโกะ ดีใจมากเลยค่ะ"
10106-CVGroup_UIEventLobby_Enter3-1 = "ผ่านมาครึ่งทางแล้วสินะคะ"
10106-CVGroup_UIEventLobby_Enter4-1 = "มีคำกล่าวที่ว่าเวลาแห่งความสนุกนั้นผ่านไปในพริบตา..."
10106-CVGroup_UIEventLobby_Enter4-2 = "แต่ฉันรู้สึกเหมือนกับว่ามันผ่านไปเร็วมากจริงๆ ค่ะ"
10106-CVGroup_UIEventLobby_Enter5-1 = "ฮุฮุ รู้สึกเสียดายอะไรงั้นเหรอคะ?"
10106-CVGroup_UIEventLobby_Enter5-2 = "บังเอิญจังเลยนะคะ… ฉันก็เหมือนกันค่ะ"
10106-CVGroup_UIEventLobby_Idle1-1 = "หืม? ทำไมเหรอคะ?"
10106-CVGroup_UIEventLobby_Idle1-2 = "จะ... จับมือ... เหรอคะ?"
10106-CVGroup_UIEventLobby_Idle2-1 = "รู้สึกใกล้ชิดกับทุกๆ คน มากกว่าตอนที่ใส่ชุดซิสเตอร์เลยค่ะ"
10106-CVGroup_UIEventLobby_Idle2-2 = "ฮุฮุุ ชุดนี้ดีจังเลยนะคะ"
10106-CVGroup_UIEventLobby_Idle3-1 = "เอ่อ… มีธุระอะไรหรือเปล่าคะ?"
10106-CVGroup_UIEventLobby_Idle3-2 = "ถ้าเรียกกันหลายๆ ครั้ง ฉันก็ไม่รู้ว่าควรจะทำยังไงดีเลยค่ะ"
10106-CVGroup_UIEventLobby_Idle4-1 = "มีท่าเต้นลับที่กำลังฝึกอยู่ด้วยค่ะ..."
10106-CVGroup_UIEventLobby_Idle4-2 = "ถะ... ถ้าคุณครูสะดวกจะลองชมสักหน่อยมั้ยคะ?"
10106-CVGroup_UIEventMission_Enter1-1 = "ฉันจัดรายการงานของคุณครูเอาไว้แล้วค่ะ"
10106-CVGroup_UIEventMission_Enter2-1 = "มาแล้วเหรอคะ คุณครู"
10106-CVGroup_UIEventMission_Idle1-1 = "ว่าแต่ว่าคุณครู… ตอนนี้เราอยู่กันแค่สองคนนะคะ"
10106-CVGroup_UIEventMission_Idle1-2 = "คะ? ปะ... เปล่านะคะ... ฉันแค่พูดไปเฉยๆ เอง"
10106-CVGroup_UIEventMission_Idle1-3 = "ไม่ได้มีความหมายพิเศษอะไร... เลย..."
10106-CVGroup_UIEventMission_Idle2-1 = "ชุดนั้นเหมาะดีงั้นเหรอคะ...? ฮุฮุ ขอบคุณค่ะ"
10106-CVGroup_UIEventMission_Buy1-1 = "ค่ะ ตรวจสอบเรียบร้อยค่ะ"
10106-CVGroup_UIEventMission_Buy2-1 = "ดีจังเลยนะคะ"
10106-CVGroup_UIEventMission_Interaction1-1 = "ขอบคุณที่ทำงานอย่างหนักค่ะ คุณครู"
10106-CVGroup_UIEventMission_Interaction1-2 = "ของขวัญตอบแทนให้คุณครูคนขยัน...\nละ... ล้อเล่นค่ะ"
