[translation]
10107-CVGroup_UITitle_Idle1-1 = "블루~ 아카이브~!"
10107-CVGroup_CharacterGet_Idle1-1 = "호외요, 호외! 만마전의 서기, 모토미야 치아키가 샬레에 찾아왔습니다~!"
10107-CVGroup_Cafe_Idle1-1 = "신기한 장소네요~!"
10107-CVGroup_Cafe_Idle2-1 = "이건, 좋은 기삿거리가 될지도 모르겠네요!"
10107-CVGroup_Cafe_Idle3-1 = "아! 저분과도 친구가 되고 싶어요~!"
10107-CVGroup_Cafe_Idle4-1 = "여기다가 <주간 만마전> 스탠드를 놓는다면……."
10107-CVGroup_Cafe_Idle5-1 = "아, 이건 이부키 쨩이 좋아할 것 같네요~!"
10107-CVGroup_WeaponGet_Idle1-1 = "너무 기뻐요! 특종을 잡았을 때처럼, 아니면 그 이상으로!"
10107-CVGroup_UIEventLobby_Enter1-1 = "와아~! 재밌는 게 잔뜩~!"
10107-CVGroup_UIEventLobby_Enter2-1 = "선생님! 여기에요! 제 옆자리!"
10107-CVGroup_UIEventLobby_Enter2-2 = "선생님 자리, 맡아놨습니다~!"
10107-CVGroup_UIEventLobby_Enter3-1 = "파티 분위기가 무르익었네요!"
10107-CVGroup_UIEventLobby_Enter3-2 = "선생님도 즐기고 계신가요~?"
10107-CVGroup_UIEventLobby_Enter4-1 = "슬슬 즐거운 파티도 끝나가네요!"
10107-CVGroup_UIEventLobby_Enter4-2 = "후회 없이 즐기도록 할까요!"
10107-CVGroup_UIEventLobby_Enter5-1 = "이런저런 일들이 있었지만, 결론적으로는…"
10107-CVGroup_UIEventLobby_Enter5-2 = "완~전 즐거운 파티였네요!"
10107-CVGroup_UIEventLobby_Idle1-1 = "네? 부르셨나요~?!"
10107-CVGroup_UIEventLobby_Idle2-1 = "다음 호에 쓸만한 사진, 건져볼까요~!"
10107-CVGroup_UIEventLobby_Idle3-1 = "선생님, 아~ 해보세요!"
10107-CVGroup_UIEventLobby_Idle3-2 = "짠! 만마전 특제 초콜릿이랍니다!"
10107-CVGroup_UIEventLobby_Idle3-3 = "어때요? 달콤해서 맛있죠!"
10107-CVGroup_UIEventLobby_Idle4-1 = "즐거운 음악도, 맛있는 음식도 좋지만…"
10107-CVGroup_UIEventLobby_Idle4-2 = "역시, 선생님이 함께 있으니 뭔가 다르네요!"
