[translation]
10106-CVGroup_UITitle_Idle1-1 = "블루-아카이브."
10106-CVGroup_CharacterGet_Idle1-1 = "후후후, 놀라셨습니까? 지금의 저는, 이전과 분명 다를 겁니다."
10106-CVGroup_Cafe_Idle1-1 = "혹, 혹시 저인걸 눈치채고 있는 것일까요……?"
10106-CVGroup_Cafe_Idle2-1 = "이왕 이렇게 된 거, 차라리 한 곡을……!"
10106-CVGroup_Cafe_Idle3-1 = "왠지 들뜬 기분이 가라앉질 않습니다."
10106-CVGroup_Cafe_Idle4-1 = "후후…… 조금 개운하네요."
10106-CVGroup_Cafe_Idle5-1 = "저 분…… 혹시 절 보고 계신 걸까요?"
10106-CVGroup_WeaponGet_Idle1-1 = "저에게, 그걸…? 아뇨, 어떤 모습이든 저는 저입니다.\n맞는 말씀입니다. 잘 받겠습니다. 감사합니다, 선생님."
10106-CVGroup_UIEventLobby_Enter1-1 = "아~ 아~ 아아~"
10106-CVGroup_UIEventLobby_Enter1-2 = "앗… 서, 선생님!?"
10106-CVGroup_UIEventLobby_Enter2-1 = "와주셔서 감사합니다, 선생님."
10106-CVGroup_UIEventLobby_Enter2-2 = "사, 사쿠라코, 기뻐요!"
10106-CVGroup_UIEventLobby_Enter3-1 = "벌써 반이나 지났네요. 으음……."
10106-CVGroup_UIEventLobby_Enter4-1 = "즐거운 시간은 눈 깜짝할 사이라고는 하지만…"
10106-CVGroup_UIEventLobby_Enter4-2 = "너무나도 한순간에 지나가 버린 것 같은 기분입니다."
10106-CVGroup_UIEventLobby_Enter5-1 = "후후, 미련이 남으시나요?"
10106-CVGroup_UIEventLobby_Enter5-2 = "우연이네요. …저도 그런데."
10106-CVGroup_UIEventLobby_Idle1-1 = "응? 왜 그러시죠?"
10106-CVGroup_UIEventLobby_Idle1-2 = "아, 악수……인가요?"
10106-CVGroup_UIEventLobby_Idle2-1 = "수녀복을 입었을 때보다 모두와 더 가까워진 것 같아요."
10106-CVGroup_UIEventLobby_Idle2-2 = "후훗, 이 복장도 좋군요."
10106-CVGroup_UIEventLobby_Idle3-1 = "그…… 용무가 있으신 걸까요?"
10106-CVGroup_UIEventLobby_Idle3-2 = "몇번이나 부르시면 ……그게, 뭘 하면 좋을지 모르겠습니다."
10106-CVGroup_UIEventLobby_Idle4-1 = "연습 중인 비장의 안무가 있습니다만……"
10106-CVGroup_UIEventLobby_Idle4-2 = "괜, 괜찮으시면 보시겠어요?"
10106-CVGroup_UIEventMission_Enter1-1 = "선생님의 업무를 정리해 두었습니다."
10106-CVGroup_UIEventMission_Enter2-1 = "잘 찾아오셨습니다, 선생님."
10106-CVGroup_UIEventMission_Idle1-1 = "그러고보니, 선생님… 지금, 단둘이 있네요."
10106-CVGroup_UIEventMission_Idle1-2 = "네? 아, 아니… 말 그대로의 의미고,"
10106-CVGroup_UIEventMission_Idle1-3 = "특별히 깊은 의미는 없습니다….만……"
10106-CVGroup_UIEventMission_Idle2-1 = "그 옷, 잘 어울린다구요…? 후후, 감사합니다."
10106-CVGroup_UIEventMission_Buy1-1 = "네, 확인하였습니다."
10106-CVGroup_UIEventMission_Buy2-1 = "아주 좋네요."
10106-CVGroup_UIEventMission_Interaction1-1 = "고생하셨습니다, 선생님."
10106-CVGroup_UIEventMission_Interaction1-2 = "열심히 한 선생님께 보상을… 막, 막이래."
