[translation]
10109-CVGroup_UITitle_Idle1-1 = "蔚藍檔案。"
10109-CVGroup_CharacterGet_Idle1-1 = "我前來紀錄老師的每一天了。\n我是擔任千年科學學園．研討會書記的生塩乃愛。\n今晚也請多多指教哦。呵呵。"
10109-CVGroup_Cafe_Idle1-1 = "（這裡就彷彿其他世界一般……充滿了孤獨與寂寞）"
10109-CVGroup_Cafe_Idle2-1 = "（稍微聆聽一下夜晚的寂靜吧）"
10109-CVGroup_Cafe_Idle3-1 = "呼啊……嗯……稍微，有點累了。"
10109-CVGroup_Cafe_Idle4-1 = "稍微休息一下再出發吧。"
10109-CVGroup_Cafe_Idle5-1 = "（剛才，好像聽到了小雪醬的笑聲……？）"
10109-CVGroup_WeaponGet_Idle1-1 = "這個轉換套件，能依照使用者的意願改變型態。\n……跟我有點類似呢。呵呵。"
10109-CVGroup_UIEventLobby_Enter1-1 = "呵呵，居然能像這樣在半夜的千年與老師"
10109-CVGroup_UIEventLobby_Enter1-2 = "見面……有種久違了的感覺呢。"
10109-CVGroup_UIEventLobby_Enter2-1 = "晚安，老師。\n呵呵，這個嗎？"
10109-CVGroup_UIEventLobby_Enter2-2 = "我和研討會的各位正在舉辦睡衣派對。"
10109-CVGroup_UIEventLobby_Enter3-1 = "……老師，你是不是隱瞞了什麼？"
10109-CVGroup_UIEventLobby_Enter3-2 = "盯……"
10109-CVGroup_UIEventLobby_Enter4-1 = "呵呵，雖然在意料之外，不過越來越有趣了呢。"
10109-CVGroup_UIEventLobby_Enter5-1 = "老師，你要休息了嗎？"
10109-CVGroup_UIEventLobby_Enter5-2 = "如果還沒的話能請你……再多陪陪我們嗎？"
10109-CVGroup_UIEventLobby_Enter5-3 = "畢竟冬天的夜晚……是很漫長的。"
10109-CVGroup_UIEventLobby_Idle1-1 = "穿著睡衣在深夜的校園裡走動……"
10109-CVGroup_UIEventLobby_Idle1-2 = "有種在做壞事的感覺，真讓人興奮呢。"
10109-CVGroup_UIEventLobby_Idle2-1 = "雖然對桌遊的規則有所了解……"
10109-CVGroup_UIEventLobby_Idle2-2 = "但實際遊玩的經驗……卻屈指可數……"
10109-CVGroup_UIEventLobby_Idle3-1 = "優香醬……雖然嘴上那麼說，但我認為他還挺開心的。"
10109-CVGroup_UIEventLobby_Idle3-2 = "好久沒看見他那麼充滿幹勁的表情了。"
10109-CVGroup_UIEventLobby_Idle4-1 = "（雖然很想讓莉央會長也參加派對……）"
10109-CVGroup_UIEventTreasure_Enter1-1 = "現在，我正在整理派對用的桌遊……"
10109-CVGroup_UIEventTreasure_Enter2-1 = "比想像中還雜亂……"
10109-CVGroup_UIEventTreasure_Enter2-2 = "老師，能請你助我一臂之力嗎？"
10109-CVGroup_UIEventTreasure_Enter3-1 = "派對雖然結束了，"
10109-CVGroup_UIEventTreasure_Enter3-2 = "但如果有感興趣的桌遊，還請不必客氣。"
10109-CVGroup_UIEventTreasure_Enter4-1 = "已經很晚了唷？"
10109-CVGroup_UIEventTreasure_Enter4-2 = "……但如果是老師的請求，我願意陪同。"
10109-CVGroup_UIEventTreasure_Idle1-1 = "桌遊也有很多種類呢。"
10109-CVGroup_UIEventTreasure_Idle2-1 = "用過的東西要放回原位，明明已經再三提過了……"
10109-CVGroup_UIEventTreasure_FindTreasure1-1 = "啊啊，在那邊啊。"
10109-CVGroup_UIEventTreasure_FindTreasure2-1 = "這個形狀，難道說……"
10109-CVGroup_UIEventTreasure_GetTreasure1-1 = "哎呀，似乎挺有趣的呢。"
10109-CVGroup_UIEventTreasure_GetTreasure2-1 = "這個……該怎麼玩呢？"
10109-CVGroup_UIEventTreasure_RoundRenewal1-1 = "好的，下一個。\n整理整頓，還會繼續唷。"
10109-CVGroup_UIEventMission_Enter1-1 = "啊，老師，如果有空的話，"
10109-CVGroup_UIEventMission_Enter1-2 = "能請你協助派對的準備嗎？"
10109-CVGroup_UIEventMission_Enter2-1 = "我正在決定睡衣派對的職責分配。"
10109-CVGroup_UIEventMission_Idle1-1 = "是，請儘管說。"
10109-CVGroup_UIEventMission_Idle2-1 = "綁起頭髮雖然方便……但脖子後面有點涼涼的……"
10109-CVGroup_UIEventMission_Idle2-2 = "3次……我指的是老師看向這裡的次數。"
10109-CVGroup_UIEventMission_Buy1-1 = "呵呵，真是個好主意，老師。"
10109-CVGroup_UIEventMission_Buy2-1 = "原來如此，剛才的我會列入參考的。"
10109-CVGroup_UIEventMission_Interaction1-1 = "今天這樣就足夠了。感謝你的協助。"
