[translation]
10104-CVGroup_UITitle_Idle1-1 = "Blue... Archive..."
10104-CVGroup_CharacterGet_Idle1-1 = "ผู้จัดการและผู้พิทักษ์ของสำนักงานใหญ่ ย่านการค้าเทพเต่าดำ\nโรงเรียนมัธยมซานไห่จิง คายามะ เรย์โจว์ค่ะ\nขอฝากตัวด้วยนะคะ คุณครู"
10104-CVGroup_Cafe_Idle1-1 = "การจัดการโลจิสติกส์ของที่นี่เป็นยังไงบ้างนะคะ..."
10104-CVGroup_Cafe_Idle2-1 = "ได้เรียนรู้ความแตกต่างของที่นี่กับย่านการค้าเทพเต่าดำเลยนะคะ"
10104-CVGroup_Cafe_Idle3-1 = "ลองสำรวจตลาดดูดีมั้ยนะ"
10104-CVGroup_Cafe_Idle4-1 = "(ถ้าจะบุกเบิกการตลาดของย่านการค้าเทพเต่าดำที่นี่ละก็...)"
10104-CVGroup_Cafe_Idle5-1 = "มีที่ตรงไหนที่ยืดเหยียดร่างกายได้บ้างมั้ยนะ..."
10104-CVGroup_WeaponGet_Idle1-1 = "คนมักพูดกันว่าใช้ปืนกับกระสุนแก้ปัญหาได้...\nแต่ถ้าเพื่อคุณครูที่คอยสนับสนุนฉันอยู่ละก็!\nฉันจะผสานการใช้ปืนกับหมัด... ให้ได้ในสักวันหนึ่งค่ะ!"
10104-CVGroup_UIEventLobby_Enter1-1 = "เชิญเลยค่ะ คุณครู ใกล้จะเปิดเทศกาลเงาจันทร์แล้วค่ะ"
10104-CVGroup_UIEventLobby_Enter2-1 = "ขอบคุณที่มานะคะ"
10104-CVGroup_UIEventLobby_Enter2-2 = "ขอให้สนุกกับเทศกาลเงาจันทร์ที่ซานไห่จิงภูมิใจนะคะ"
10104-CVGroup_UIEventLobby_Enter3-1 = "ถึงจะเป็นสถานการณ์ที่คาดไม่ถึง..."
10104-CVGroup_UIEventLobby_Enter3-2 = "แต่สำหรับมังกรดำ ย่านการค้าฯ และซานไห่จิงแล้ว..."
10104-CVGroup_UIEventLobby_Enter3-3 = "การมีอยู่ของคุณครูเป็นแรงใจให้พวกเรามากๆ ค่ะ"
10104-CVGroup_UIEventLobby_Enter4-1 = "เทศกาลเงาจันทร์เปิดได้อย่างราบรื่นเลยนะคะ"
10104-CVGroup_UIEventLobby_Enter4-2 = "เรื่องวุ่นวายนั่น เอาเป็นว่าอย่าเพิ่งใส่ใจเลยค่ะ..."
10104-CVGroup_UIEventLobby_Enter5-1 = "งานเทศกาลเป็นอย่างไรบ้างคะ?"
10104-CVGroup_UIEventLobby_Enter5-2 = "ซานไห่จิงกับย่านการค้าเทพเต่าดำ\nรอให้คุณครูมาเยือนทุกเมื่อเลยนะคะ"
10104-CVGroup_UIEventLobby_Idle1-1 = "เทศกาลเงาจันทร์คืองานที่จะได้โชว์ฝีมือของ\nย่านการค้าเทพเต่าดำค่ะ"
10104-CVGroup_UIEventLobby_Idle1-2 = "คุณครูพักผ่อนเถอะค่ะ"
10104-CVGroup_UIEventLobby_Idle2-1 = "ถ้าแกล้งกัน ฉันจะตอบกลับด้วยภาษาทางร่างกายนะคะ"
10104-CVGroup_UIEventLobby_Idle2-2 = "ฉันล้อเล่นค่ะ คุณครูจะแกล้งฉันเท่าไรก็ได้ค่ะ"
10104-CVGroup_UIEventLobby_Idle2-3 = "แต่ถ้าทำเยอะเกินไป ฉันจะลำบากนะคะเอาแต่พอดีเถอะค่ะ"
10104-CVGroup_UIEventLobby_Idle3-1 = "มีเรื่องอะไรเหรอคะคุณครู?"
10104-CVGroup_UIEventLobby_Idle3-2 = "คะ...? แค่ลองเรียกดูงั้นเหรอคะ...?"
10104-CVGroup_UIEventLobby_Idle3-3 = "ถ้าเรียกร้องความสนใจหลายๆ ครั้งแบบนี้\nระวังต่อไปไม่มีใครเชื่อนะคะ"
10104-CVGroup_UIEventLobby_Idle3-4 = "แม้ว่าฉันจะเชื่อใจคุณครูอยู่เสมอก็เถอะค่ะ..."
10104-CVGroup_UIEventLobby_Idle4-1 = "ฉะ... ฉันไม่ค่อยบ้าจี้น่ะค่ะ"
10104-CVGroup_UIEventLobby_Idle4-2 = "จะ... จริงนะคะ ทำไปก็ไม่มีประโยชน์หรอกค่ะ\nเพราะงั้น หยุดนะ...!"
10104-CVGroup_UIEventLobby_Idle4-3 = "อะฮ่าฮ่าฮ่าฮ่า!"
10104-CVGroup_UIEventLobby_Idle4-4 = "หยุดเถอะค่ะ... ฉันขอละ"
10104-CVGroup_UIEventShop_Enter1-1 = "ฉันดูแลร้านได้ค่อนข้างดีค่ะ"
10104-CVGroup_UIEventShop_Enter1-2 = "ถ้างั้น... วันนี้อยากได้อะไรเหรอคะ?"
10104-CVGroup_UIEventShop_Enter2-1 = "เพียงแค่มาบอกกัน ย่านการค้าเทพเต่าดำก็จะไปให้ค่ะ"
10104-CVGroup_UIEventShop_Enter2-2 = "สักวันหนึ่ง แม้จะต้องไปถึงสุดขอบคิโวทอสก็ตาม!"
10104-CVGroup_UIEventShop_Enter3-1 = "ไม่ได้ลืมของอะไรใช่มั้ยคะ?"
10104-CVGroup_UIEventShop_Enter3-2 = "ค่อยๆ ดูของให้หมดจะได้ไม่เสียดายภายหลังนะคะ"
10104-CVGroup_UIEventShop_Idle1-1 = "ของลึกลับของย่านการค้าเทพเต่าดำ? เมนูที่ซ่อนอยู่...?"
10104-CVGroup_UIEventShop_Idle1-2 = "อืม... ไม่มีของแบบนั้นหรอกค่ะ..."
10104-CVGroup_UIEventShop_Idle1-3 = "ถึงจะทำสีหน้าแบบนั้นก็เถอะค่ะ..."
10104-CVGroup_UIEventShop_Idle2-1 = "ถ้าต้องการอะไรก็บอกฉันได้ตลอดค่ะ"
10104-CVGroup_UIEventShop_Idle2-2 = "แต่ของที่หมดแล้ว ฉันก็ช่วยไม่ได้นะคะ..."
10104-CVGroup_UIEventShop_Buy1-1 = "ค่ะ นี่คือของที่ฉันแนะนำค่ะ"
10104-CVGroup_UIEventShop_Buy2-1 = "หาของไปใช้เองที่บ้านหรือเอาไปเป็นของขวัญคะ?"
10104-CVGroup_UIEventShop_Buy3-1 = "ขอบคุณทุกครั้งเลยนะคะ!"
10104-CVGroup_UIEventShop_Buy3-2 = "ฉันพูดคำนี้อยู่บ่อยๆ แต่พอได้พูดกับคุณครู ก็แปลกใหม่ดีนะคะ"
10104-CVGroup_UIEventShop_Buy4-1 = "ท่านประธานก็พูดอย่างนี้บ่อยๆ ค่ะ"
10104-CVGroup_UIEventShop_Buy4-2 = "บอกว่าถ้าได้อะไรมาฟรีๆ คนนั้นก็จะเป็นของขวัญค่ะ"
10104-CVGroup_UIEventShop_Buy4-3 = "แต่ถ้าคุณครูเป็นของขวัญละก็..."
10104-CVGroup_UIEventShop_Buy4-4 = "ปะ... เปล่าค่ะ ไม่มีอะไรหรอกค่ะ"
