[translation]
10117-CVGroup_UITitle_Idle1-1 = "蔚藍檔案～"
10117-CVGroup_CharacterGet_Idle1-1 = "高地人鐵道學園～\n橘光……登場～"
10117-CVGroup_Cafe_Idle1-1 = "哦～感覺有很多能玩的……"
10117-CVGroup_Cafe_Idle2-1 = "老師～你在哪～？"
10117-CVGroup_Cafe_Idle3-1 = "今天決定摸魚～"
10117-CVGroup_Cafe_Idle4-1 = "沒有點心嗎～？\n果汁呢～？"
10117-CVGroup_Cafe_Idle5-1 = "沒有好玩的事嗎～？"
10117-CVGroup_WeaponGet_Idle1-1 = "要給我嗎～？\n謝謝～作為回報，我會保護老師的～"
10117-CVGroup_UIEventLobby_Enter1-1 = "歡迎～"
10117-CVGroup_UIEventLobby_Enter1-2 = "準備完畢～"
10117-CVGroup_UIEventLobby_Enter2-1 = "老師～大危機～"
10117-CVGroup_UIEventLobby_Enter2-2 = "Help me～快幫幫我～"
10117-CVGroup_UIEventLobby_Enter3-1 = "發車準備～沒有問題～"
10117-CVGroup_UIEventLobby_Enter3-2 = "老師～要加速囉～"
10117-CVGroup_UIEventLobby_Enter4-1 = "已經結束了～？還想再玩～"
10117-CVGroup_UIEventLobby_Enter5-1 = "真開心呢～再一起玩吧。"
10117-CVGroup_UIEventLobby_Idle1-1 = "咦～？想跟光一起玩嗎？"
10117-CVGroup_UIEventLobby_Idle2-1 = "好癢哦～"
10117-CVGroup_UIEventLobby_Idle2-2 = "嗚嗚，我要報仇～！"
10117-CVGroup_UIEventLobby_Idle3-1 = "請給我摸摸，誇誇我嘛～"
10117-CVGroup_UIEventLobby_Idle3-2 = "誇誇我～雖然我什麼都沒做就是了。"
10117-CVGroup_UIEventLobby_Idle4-1 = "要吃點心嗎～？等一下哦～"
10117-CVGroup_UIEventLobby_Idle4-2 = "啊……全部都被我吃光了……\nSorry～"
10117-CVGroup_UIEventShop_Enter1-1 = "Train shop～想要什麼呀～？"
10117-CVGroup_UIEventShop_Enter2-1 = "歡迎光臨～歡迎參觀～是這樣嗎？"
10117-CVGroup_UIEventShop_Enter3-1 = "路線會一直延續下去哦～商店也一起～"
10117-CVGroup_UIEventShop_Idle1-1 = "推薦？唔嗯……"
10117-CVGroup_UIEventShop_Idle1-2 = "要自己選才對～"
10117-CVGroup_UIEventShop_Idle2-1 = "光也想玩，但在忍耐～老師也忍耐一下吧～"
10117-CVGroup_UIEventShop_Buy1-1 = "哦～那個很棒吧～"
10117-CVGroup_UIEventShop_Buy2-1 = "真有品味～咻～咻～"
10117-CVGroup_UIEventShop_Buy3-1 = "老師，真聰明～"
10117-CVGroup_UIEventShop_Buy4-1 = "也買給光！也買給光嘛！"
