[translation]
10111-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
10111-CVGroup_CharacterGet_Idle1-1 = "มิคาโมะ เนรุ จากโรงเรียนวิทย์มิลเลเนียม\nเพิ่งมาถึงเมื่อกี้เลย... หืม? ชุดนี้น่ะเหรอ? มันแปลกรึไง?"
10111-CVGroup_Cafe_Idle1-1 = "(นั่นอะไรน่ะ? อย่างเจ๋งเลย!)"
10111-CVGroup_Cafe_Idle2-1 = "อืม ก็ไม่แย่เท่าไรนะ พักผ่อนสักหน่อยมั้ย?"
10111-CVGroup_Cafe_Idle3-1 = "พอไม่มีเสื้อคลุมก็รู้สึกว่างเปล่าแฮะ"
10111-CVGroup_Cafe_Idle4-1 = "ครูจะมาเมื่อไรนะ..."
10111-CVGroup_Cafe_Idle5-1 = "เฟอร์นิเจอร์อันนี้ถูกใจฉันจัง ยกไปวางไว้ที่ห้องชมรมดีมั้ยนะ?"
10111-CVGroup_WeaponGet_Idle1-1 = "มาคิดๆ ดูมันก็ไม่ใช่วันที่มีอะไรพิเศษ\nแต่ทำไมรู้สึกพิเศษก็ไม่รู้นะ เอาเถอะ...\nไม่เป็นไรหรอกน่า! ครูกับฉัน เราคนกันเองอยู่แล้ว!"
10111-CVGroup_UIEventLobby_Enter1-1 = "เฮ้! ครู! ทางนี้ ทางนี้!"
10111-CVGroup_UIEventLobby_Enter2-1 = "โธ่ ครู ทำไมมาช้าแบบนี้เนี่ย?"
10111-CVGroup_UIEventLobby_Enter3-1 = "เอาละๆ! ตั้งสติเข้า!"
10111-CVGroup_UIEventLobby_Enter4-1 = "ทนอีกหน่อยนะ"
10111-CVGroup_UIEventLobby_Enter4-2 = "ไว้เสร็จงานแล้ว ฉันจะมาเล่นด้วย!"
10111-CVGroup_UIEventLobby_Enter5-1 = "ฮ่า! สนุกจังเลยเนอะ ว่ามั้ย?"
10111-CVGroup_UIEventLobby_Idle1-1 = "หืม? เรียกฉันเหรอ?\nถ้าเรียกมาแล้วก็ต้องพูดสิ"
10111-CVGroup_UIEventLobby_Idle2-1 = "หืม? แค่ลองจิ้มดูงั้นเหรอ?\nอะไรของเค้าเนี่ย..."
10111-CVGroup_UIEventLobby_Idle3-1 = "เฮ้อ... ทำตัวเหมือนเป็นเด็กไปได้"
10111-CVGroup_UIEventLobby_Idle4-1 = "ฉันจะจำไว้นะ ต่อไปฉันจะมาจิ้มบ้าง\nเตรียมตัวโดนไว้เลย"
