[translation]
10119-CVGroup_UITitle_Idle1-1 = "蔚藍檔案。"
10119-CVGroup_CharacterGet_Idle1-1 = "百鬼夜行聯合學園，百花繚亂紛爭調停委員會──御稜名草。\n這股力量，是為了守護大家而存在的。"
10119-CVGroup_Cafe_Idle1-1 = "如果是菖蒲的話……會怎麼度過呢。"
10119-CVGroup_Cafe_Idle2-1 = "真的能待在這裡嗎……"
10119-CVGroup_Cafe_Idle3-1 = "（這是……烤雞……？）"
10119-CVGroup_Cafe_Idle4-1 = "雖然有點熱……但對大家來說肯定很舒服吧。"
10119-CVGroup_Cafe_Idle5-1 = "有點頭暈……休息一下吧。"
10119-CVGroup_WeaponGet_Idle1-1 = "……這把槍，是沒有資格就不能持有的東西。\n沒錯──讓御稜名草持有它的意義，我想老師應該很清楚。\n即使如此……你還是願意託付給我，願意相信我的話……我也會試著傾盡全力掙扎的。"
