[translation]
10111-CVGroup_UITitle_Idle1-1 = "蔚藍檔案！"
10111-CVGroup_CharacterGet_Idle1-1 = "千年科學學園的美甘寧瑠，已經抵達囉……\n啊？這套衣服？有什麼奇怪的嗎？"
10111-CVGroup_Cafe_Idle1-1 = "（那是什麼？好帥！）"
10111-CVGroup_Cafe_Idle2-1 = "嗯，還不錯。\n稍微休息一下吧。"
10111-CVGroup_Cafe_Idle3-1 = "有種靜不下來的感覺……是因為沒穿外衣嗎？"
10111-CVGroup_Cafe_Idle4-1 = "老師他什麼時候會來呢……？"
10111-CVGroup_Cafe_Idle5-1 = "哦，這個挺不錯的嘛！\n都想裝飾在部室裡了。"
10111-CVGroup_WeaponGet_Idle1-1 = "雖然仔細想想其實跟平常完全沒兩樣……總～覺得有股特別的感覺。\n……算了，反正我跟老師又不是別人，沒必要在意這種事吧！"
10111-CVGroup_UIEventLobby_Enter1-1 = "喲～老師！這邊，這邊！"
10111-CVGroup_UIEventLobby_Enter2-1 = "啊，這不是老師嗎！你遲到囉！"
10111-CVGroup_UIEventLobby_Enter3-1 = "好了，打起精神來吧！"
10111-CVGroup_UIEventLobby_Enter4-1 = "就剩一點了不是嗎？"
10111-CVGroup_UIEventLobby_Enter4-2 = "結束之後會陪你玩的，再忍耐一下吧！"
10111-CVGroup_UIEventLobby_Enter5-1 = "哈～！真開心！老師你呢？"
10111-CVGroup_UIEventLobby_Idle1-1 = "怎麼啦？有事的話就趕緊說吧。"
10111-CVGroup_UIEventLobby_Idle2-1 = "啊？只是戳戳看而已？\n什麼意思啊……"
10111-CVGroup_UIEventLobby_Idle3-1 = "……唉，做那種像小孩一樣的事。"
10111-CVGroup_UIEventLobby_Idle4-1 = "哈哈！下次就輪到我囉。\n做好覺悟吧。"
