[translation]
10129-CVGroup_UITitle_Idle1-1 = "Blue... Ar... chive..."
10129-CVGroup_CharacterGet_Idle1-1 = "นะ... นี่เป็นส่วนหนึ่งของงานกลุ่มรักษาความสงบค่ะ\nฉันจะพยายามเพื่อความปลอดภัยของทรีนิตี้กับคุณครูค่ะ"
10129-CVGroup_Cafe_Idle1-1 = "ที่นี่เงียบสงบจังเลยนะคะ...\nเป็นเรื่องที่ดีจริงๆ ค่ะ"
10129-CVGroup_Cafe_Idle2-1 = "(คนคนนั้น... พยายามคุยกับฉันงั้นเหรอ?)"
10129-CVGroup_Cafe_Idle3-1 = "(หะ... หัวข้อสนทนา...\nเมื่อคืนก็เตรียมมาแล้วนี่นา...!)"
10129-CVGroup_Cafe_Idle4-1 = "(ฉันควรเปลี่ยนชุดแล้วค่อยมาใช่มั้ยคะ...?)"
10129-CVGroup_Cafe_Idle5-1 = "หาทางออกเรียบร้อยค่ะ"
10129-CVGroup_WeaponGet_Idle1-1 = "คือว่า... ฉันคิดว่าของตกแต่งน่ารักๆ...\nมันจะเข้ากับฉันหรือเปล่าน่ะค่ะ"
10129-CVGroup_UIEventLobby_Enter1-1 = "ถะ... ถ้าจ้องกันมากไป ฉันจะประหม่านะคะ..."
10129-CVGroup_UIEventLobby_Enter2-1 = "นี่ก็เพื่อการแฝงตัวเท่านั้นค่ะ"
10129-CVGroup_UIEventLobby_Enter2-2 = "ถึงจะคิดว่าเป็นชุดที่สวยเลยก็เถอะ..."
10129-CVGroup_UIEventLobby_Enter3-1 = "เหมือนผู้ชมจะหลั่งไหลเข้ามามากขึ้นเลยนะคะ..."
10129-CVGroup_UIEventLobby_Enter4-1 = "ทุกคนดูชื่นชอบกันจังเลยนะคะ"
10129-CVGroup_UIEventLobby_Enter4-2 = "ไม่ว่าจะเป็นการช่วยรูปแบบไหน แต่ก็โล่งอกที่ได้ช่วยนะคะ"
10129-CVGroup_UIEventLobby_Enter5-1 = "ทำให้ฉันมั่นใจในตัวเองมากขึ้นเลยค่ะ"
10129-CVGroup_UIEventLobby_Enter5-2 = "ขอบคุณนะคะ คุณครู"
10129-CVGroup_UIEventLobby_Enter5-3 = "ภารกิจแฝงตัวเสร็จแล้ว แต่การลาดตระเวนยังดำเนินต่อไปค่ะ"
10129-CVGroup_UIEventLobby_Enter5-4 = "ต่อไปก็หวังว่าจะได้เจอกันอีกบ่อยๆ นะคะ"
10129-CVGroup_UIEventLobby_Idle1-1 = "อย่าดึงกันสิคะ! ฉันไม่ใช่พร็อพนะคะ!"
10129-CVGroup_UIEventLobby_Idle2-1 = "ตามมาตราที่ 6 ของกฎหมายเวทมนตร์\nอืม... แล้วก็..."
10129-CVGroup_UIEventLobby_Idle2-2 = "ฉันไม่ชินกับบทพูด ก็เลยจำไม่ค่อยได้ค่ะ"
10129-CVGroup_UIEventLobby_Idle3-1 = "ว้ายย! คะ... คิกคิก! อ๊ะ... อ๊าย...! จั๊กจี้ค่ะ...!"
10129-CVGroup_UIEventLobby_Idle3-2 = "ฉันเป็นคนบ้าจี้นะคะ...!"
10129-CVGroup_UIEventLobby_Idle4-1 = "บรรยากาศนี้ของสวนสนุก ฉันชอบจังเลยค่ะ"
10129-CVGroup_UIEventLobby_Idle4-2 = "ก็เพราะมัน... สงบสุขสุดๆ เลยน่ะค่ะ"
10129-CVGroup_UIEventShop_Enter1-1 = "ชะ... เชิญค่ะคุณครู..."
10129-CVGroup_UIEventShop_Enter2-1 = "มีอะไรที่ต้องการหรือเปล่าคะ..."
10129-CVGroup_UIEventShop_Enter3-1 = "เป็นการลาดตระเวนที่น่าจดจำเลยค่ะ\nขอบคุณนะคะ"
10129-CVGroup_UIEventShop_Idle1-1 = "หวังว่าจะเจอของที่ต้องการนะคะ"
10129-CVGroup_UIEventShop_Idle2-1 = "นึกถึงเรื่องที่ร้านสะดวกซื้อเลยนะคะ"
10129-CVGroup_UIEventShop_Buy1-1 = "ค่ะ ทางนี้เลยค่ะ"
10129-CVGroup_UIEventShop_Buy2-1 = "ค่ะ นี่ค่ะ"
10129-CVGroup_UIEventShop_Buy3-1 = "ขอบคุณที่ให้ความร่วมมือขอบคุณนะคะ"
10129-CVGroup_UIEventShop_Buy4-1 = "ขอให้เป็นประโยชน์กับคุณครูนะคะ"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter1-1 = "เป็นเครื่องที่เก่าเลยนะคะ\nแต่ฉันไม่รู้นะคะว่ายังใช้งานได้หรือเปล่า...?"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter1-2 = "ถ้าใส่เหรียญก็จะใช้งานได้สินะคะ"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter2-1 = "ค่อยยังชั่วหน่อยนะคะที่คุณเรอิสะกำลังสนุกเลย"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter2-2 = "อยากให้ได้การ์ดระดับที่หายากๆ จังเลยค่ะ"
10129-CVGroup_UIEventFortuneGachashop_Card_Enter3-1 = "ถึงเวลาปิดแล้วสินะคะ\nลองเช็กดูนะคะว่ามีเหรียญเหลือหรือเปล่า"
10129-CVGroup_UIEventFortuneGachashop_Card_Idle1-1 = "ฉันรู้สึกถึงสายตาที่มองมาจากรอบๆ ตั้งแต่เมื่อกี้แล้ว..."
10129-CVGroup_UIEventFortuneGachashop_Card_Idle2-1 = "รีบเลือกเข้าเถอะค่ะ ก่อนจะถูกเพ่งเล็งมากกว่านี้"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck4-1 = "สีรุ้งสินะคะ มันดี... หรือเปล่าคะ?"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck3-1 = "สีชมพู... สินะคะ"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck2-1 = "สีทองสินะคะ"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck1-1 = "สีเหมือนท้องฟ้าเลยนี่คะ สดชื่นจังเลยค่ะ"
10129-CVGroup_UIEventFortuneGachashop_Card_Luck0-1 = "สีดำ... ลางไม่ดีเท่าไรเลยค่ะ"
