[translation]
10128-CVGroup_UITitle_Idle1-1 = "Blue Archive! ค่ะ!"
10128-CVGroup_CharacterGet_Idle1-1 = "เป็นตัวเลือกที่ยอดเยี่ยมเลยค่ะ คุณลูกค้า... ไม่สิ คุณครู!\nลืมแนะนำตัวไปเลย... ฉันวากาสะ ฟุยุ ชั้นปีที่ 2\nจากสถาบันศิลปะไวลด์ฮันต์ค่ะ ช่วยจำฉันไว้ด้วยนะคะ!"
10128-CVGroup_Cafe_Idle1-1 = "อะไรกัน นี่เป็นสถานที่ที่เหมาะกับ\nการพูดคุยธุรกิจเลยนี่?"
10128-CVGroup_Cafe_Idle2-1 = "ถ้าจะติดตั้งจอโปรเจคเตอร์\nจะติดตรงไหนดีนะ..."
10128-CVGroup_Cafe_Idle3-1 = "(เมล็ดกาแฟรสชาติใช้ได้เลย ลองนำเข้าดูดีมั้ยนะ?)"
10128-CVGroup_Cafe_Idle4-1 = "ว่าแต่... คุณครูไม่มาเหรอ"
10128-CVGroup_Cafe_Idle5-1 = "(ตะ... ตรงโน้นคือฝ่ายดูแลหอพักหรือเปล่า? ทำไงดีล่ะ? ต้องหนีมั้ยเนี่ย?"
10128-CVGroup_WeaponGet_Idle1-1 = "ไว้สักวันหนึ่งฉันจะมาตอบแทนนะคะ...!\nก็นี่เป็นธุรกิจนี่คะ! เพราะงั้นก็...\nช่วยอยู่ข้างกันจนถึงตอนนั้นด้วยนะคะ"
10128-CVGroup_UIEventLobby_Enter1-1 = "ขอกล่าวทักทายค่ะ! ฉันคือหัวหน้าฝ่ายธุรกิจ\nชมรมการค้าพิเศษ วากาสะ ฟุยุค่ะ!"
10128-CVGroup_UIEventLobby_Enter2-1 = "ถ้าต้องการของอะไร\nก็มาสอบถามได้ไม่ต้องเกรงใจนะคะ"
10128-CVGroup_UIEventLobby_Enter3-1 = "ฮุ... ฮุฮุ... ฮุ...\nงะ... งานแค่นี้น่ะฉันรับมือไหวอยู่แล้วค่ะ"
10128-CVGroup_UIEventLobby_Enter4-1 = "(ทำไมเป็นแบบนี้ล่ะ? ทำอะไรผิดเนี่ย?\nนี่มันพังแล้วใช่มั้ยคะ? ใช่มั้ยคะ? ใช่ใช่มั้ยคะ?!)"
10128-CVGroup_UIEventLobby_Enter5-1 = "ฮุ... ฮุฮุ... คงต้องหลีกเลี่ยง\nงานแบบนี้ไปสักพักแล้วละค่ะ..."
10128-CVGroup_UIEventLobby_Idle1-1 = "ค่ะ ใช่แล้วค่ะ ฉันคือหน้าตาของชมรมเองค่ะ"
10128-CVGroup_UIEventLobby_Idle2-1 = "แอบนัดพบ รับงาน แล้วก็เจรจากับลูกค้า...\nค่ะ นั่นคือบทบาทของฉันค่ะ"
10128-CVGroup_UIEventLobby_Idle3-1 = "แน่นอนว่าถ้าไม่มีการซัพพอร์ตจากมิโยะกับริตสึจังละก็\nฉันก็คงเป็นแค่นักเรียนโรงเรียนศิลปะธรรมดาๆ คนหนึ่งค่ะ"
10128-CVGroup_UIEventLobby_Idle4-1 = "ศิลปะเป็นสิ่งที่... ไม่ง่ายเลยนะคะ"
10128-CVGroup_UIEventShop_Enter1-1 = "มีเวลาและสินค้าในสต๊อกเหลือเฟือเลยค่ะ\nค่อยๆ ดูได้เลยนะคะ"
10128-CVGroup_UIEventShop_Enter2-1 = "มีของที่หาอยู่หรือเปล่าคะ?"
10128-CVGroup_UIEventShop_Enter3-1 = "ยังเหลือเวลาอีกหน่อยจนกว่าจะปิดร้านค่ะ\nค่อยๆ เลือกของดูนะคะ"
10128-CVGroup_UIEventShop_Idle1-1 = "มีของที่อยากได้ต่างหากงั้นเหรอคะ?\nงั้นมาบอกฉันทางนี้สิคะ..."
10128-CVGroup_UIEventShop_Idle2-1 = "ฮะฮ่า! จะ... จิ้มกันแบบนั้น\nก็ไม่ลดราคาให้หรอกนะคะ?"
10128-CVGroup_UIEventShop_Buy1-1 = "สายตาเฉียบคมมากเลยค่ะ"
10128-CVGroup_UIEventShop_Buy2-1 = "ฉันก็เล็งสินค้านั้นอยู่เหมือนกันค่ะ"
10128-CVGroup_UIEventShop_Buy3-1 = "เปลี่ยนของและขอคืนเงินไม่ได้นะคะ?"
10128-CVGroup_UIEventShop_Buy4-1 = "เลือกได้ยอดเยี่ยมเลยค่ะ\nอยากให้ห่อสินค้าให้ด้วยมั้ยคะ?"
