[translation]
10122-CVGroup_UITitle_Idle1-1 = "블루아카이브~ 아하하☆"
10122-CVGroup_CharacterGet_Idle1-1 = "미소노 미카, 다시 한번 등장~☆ 같은 느낌이려나.\n그럼, 이번에도 잘 부탁해. 선생님!"
10122-CVGroup_Cafe_Idle1-1 = "아하핫, 이상해~"
10122-CVGroup_Cafe_Idle2-1 = "흐응~ 다들 이런 식으로 샬레를 방문하는구나."
10122-CVGroup_Cafe_Idle3-1 = "(다들 자기만의 고민이 있겠지? 나처럼……)"
10122-CVGroup_Cafe_Idle4-1 = "선생님, 언제 오려나……"
10122-CVGroup_Cafe_Idle5-1 = "이거, 내가 써도 되는 걸까?"
10122-CVGroup_WeaponGet_Idle1-1 = "이걸…… 내게? 거짓말~! ……에, 정말로?\n하아…… 선생님, 정말 치사하네. 항상 시치미 뗀 얼굴로 이런다니까.\n반칙이라구...... 나도 뭔가 보답하고 싶은데………"
10122-CVGroup_UIEventLobby_Enter1-1 = "얏호- 선생님. 즐기고 있어?"
10122-CVGroup_UIEventLobby_Enter2-1 = "으음. 선생님은 어떻게 대처하려나, 이런 상황……"
10122-CVGroup_UIEventLobby_Enter3-1 = "뭔가 생각과는 조금 다른 전개지만……"
10122-CVGroup_UIEventLobby_Enter3-2 = "그래도, 어떻게든 되려나~!"
10122-CVGroup_UIEventLobby_Enter4-1 = "긴장을 놓지 말아야겠네."
10122-CVGroup_UIEventLobby_Enter4-2 = "무슨 일이 또 일어날지 모르니까 말야."
10122-CVGroup_UIEventLobby_Enter5-1 = "후아~ 어쨌든 마무리가 됐네."
10122-CVGroup_UIEventLobby_Enter5-2 = "선생님이 없었다면 어떻게 되었을지……"
10122-CVGroup_UIEventLobby_Enter5-3 = "생각하기도 싫어……"
10122-CVGroup_UIEventLobby_Idle1-1 = "선생님과 함께라서 다행이다~"
10122-CVGroup_UIEventLobby_Idle1-2 = "알고 있겠지만,"
10122-CVGroup_UIEventLobby_Idle1-3 = "나 좀 덤벙대는 부분이 있으니까…."
10122-CVGroup_UIEventLobby_Idle2-1 = "응? 무슨 일 있어?"
10122-CVGroup_UIEventLobby_Idle2-2 = "미카가 필요하다거나~?"
10122-CVGroup_UIEventLobby_Idle3-1 = "아하하, 가, 간지러워 선생님!"
10122-CVGroup_UIEventLobby_Idle3-2 = "괜찮겠어~? 나도 한다~?"
10122-CVGroup_UIEventLobby_Idle4-1 = "선생님……? 슬슬 멈춰줬으면…… 하는데."
10122-CVGroup_UIEventLobby_Idle4-2 = "아, 싫진 않아! 전혀!"
10122-CVGroup_UIEventLobby_Idle4-3 = "하지만…… 착각해 버릴 것 같아서."
10122-CVGroup_UIEventMission_Enter1-1 = "우와, 할 일 많아……"
10122-CVGroup_UIEventMission_Enter2-1 = "모처럼 바다에 왔는데…… 아직도 일해……?"
10122-CVGroup_UIEventMission_Idle1-1 = "귀찮아……"
10122-CVGroup_UIEventMission_Idle1-2 = "포상이 있다면, 할 마음이 생길지도~"
10122-CVGroup_UIEventMission_Idle2-1 = "후후, 선생님……"
10122-CVGroup_UIEventMission_Idle2-2 = "잠깐만 땡땡이칠래? 어때?"
10122-CVGroup_UIEventMission_Buy1-1 = "와-오! 역시 선생님이네☆"
10122-CVGroup_UIEventMission_Buy2-1 = "응, 좋아! 기세를 타버렸다구!"
10122-CVGroup_UIEventMission_Interaction1-1 = "휴~ 오늘 할 일은 이걸로 끝이네."
10122-CVGroup_UIEventMission_Interaction1-2 = "선생님, 이제…… 어떡할까?"
10122-CVGroup_UIEventMission_Interaction1-3 = "난…… 특별히 예정은, 없는데."
