[translation]
10122-CVGroup_UITitle_Idle1-1 = "Blue Archive! Ahaha! ☆"
10122-CVGroup_CharacterGet_Idle1-1 = "Once more, I, Misono Mika, have arrived! Looking forward to working with you again, Sensei! ☆"
10122-CVGroup_Cafe_Idle1-1 = "Ahaha, so weird!"
10122-CVGroup_Cafe_Idle2-1 = "Hm, so everyone takes turns visiting Schale like this."
10122-CVGroup_Cafe_Idle3-1 = "(They must all have their own worries, right? Just like me...)"
10122-CVGroup_Cafe_Idle4-1 = "I wonder when Sensei will get here..."
10122-CVGroup_Cafe_Idle5-1 = "Can I use this?"
10122-CVGroup_WeaponGet_Idle1-1 = "This is...for me? You're kidding! Seriously? *sigh* You're so unfair, Sensei. You always do this kind of stuff like it's nothing. It's just not fair... I really wanted to repay you for everything..."
10122-CVGroup_UIEventLobby_Enter1-1 = "Yahoo! Are you having fun, Sensei?"
10122-CVGroup_UIEventLobby_Enter2-1 = "Hmm. What would Sensei do...?"
10122-CVGroup_UIEventLobby_Enter3-1 = "Things aren't going quite how I expected..."
10122-CVGroup_UIEventLobby_Enter3-2 = "I'm sure it'll work out, one way or another!"
10122-CVGroup_UIEventLobby_Enter4-1 = "I shouldn't let my guard down."
10122-CVGroup_UIEventLobby_Enter4-2 = "There's no telling what'll happen next."
10122-CVGroup_UIEventLobby_Enter5-1 = "Phew! Things wrapped up, somehow!"
10122-CVGroup_UIEventLobby_Enter5-2 = "I wonder how it would've played out if you weren't here, Sensei."
10122-CVGroup_UIEventLobby_Enter5-3 = "I don't even want to think about it..."
10122-CVGroup_UIEventLobby_Idle1-1 = "I'm glad you were with me."
10122-CVGroup_UIEventLobby_Idle1-2 = "I'm sure you already know this..."
10122-CVGroup_UIEventLobby_Idle1-3 = "...but I can be a bit clumsy."
10122-CVGroup_UIEventLobby_Idle2-1 = "Hm? Did something happen?"
10122-CVGroup_UIEventLobby_Idle2-2 = "Something that may require my help?"
10122-CVGroup_UIEventLobby_Idle3-1 = "Ahaha, th-that tickles, Sensei!"
10122-CVGroup_UIEventLobby_Idle3-2 = "You sure about that? I might retaliate, you know!"
10122-CVGroup_UIEventLobby_Idle4-1 = "Sensei...? I'm starting to wish...that you'd stop."
10122-CVGroup_UIEventLobby_Idle4-2 = "Ah, I don't hate it! Not at all!"
10122-CVGroup_UIEventLobby_Idle4-3 = "But...I might misunderstand."
10122-CVGroup_UIEventMission_Enter1-1 = "Whoa, so much to do..."
10122-CVGroup_UIEventMission_Enter2-1 = "You're working...at the beach...?"
10122-CVGroup_UIEventMission_Idle1-1 = "What a bother..."
10122-CVGroup_UIEventMission_Idle1-2 = "I could be convinced...with a reward!"
10122-CVGroup_UIEventMission_Idle2-1 = "Fufu, Sensei..."
10122-CVGroup_UIEventMission_Idle2-2 = "What do you think about playing hooky?"
10122-CVGroup_UIEventMission_Buy1-1 = "Wow! I'd expect nothing less from you, Sensei!"
10122-CVGroup_UIEventMission_Buy2-1 = "Okay, great! We're picking up the pace!"
10122-CVGroup_UIEventMission_Interaction1-1 = "Phew! That should be everything for today!"
10122-CVGroup_UIEventMission_Interaction1-2 = "What should we do now, Sensei?"
10122-CVGroup_UIEventMission_Interaction1-3 = "I...didn't plan anything in particular."
