[translation]
13003-CVGroup_UITitle_Idle1-1 = "블루 아카이브."
13003-CVGroup_CharacterGet_Idle1-1 = "정의실현부의 하네카와 하스미. 선생님의 지시를 기다리고 있습니다."
13003-CVGroup_Cafe_Idle1-1 = "저도 언젠간 귀여운 짧은 치마를…"
13003-CVGroup_Cafe_Idle2-1 = "이 공간, 마음에 드네요. 자주 오고 싶어집니다."
13003-CVGroup_Cafe_Idle3-1 = "가끔씩은 이런 여유도 괜찮군요."
13003-CVGroup_Cafe_Idle4-1 = "맛있어 보이는 게 있지만… 참아야합니다."
13003-CVGroup_Cafe_Idle5-1 = "정의실현부의 원칙은 심플합니다. 불의를 용서치 않는거죠."
13003-CVGroup_WeaponGet_Idle1-1 = "선생님께서 주신 이 힘……. 소중하게 쓰겠습니다."
