[translation]
13005-CVGroup_UITitle_Idle1-1 = "블루 아카이브."
13005-CVGroup_CharacterGet_Idle1-1 = "화난 건 아니니 오해하진 마. 선생.\n얼굴이 무섭다는 말은 자주 들으니까."
13005-CVGroup_Cafe_Idle1-1 = "하아…. 걱정이네."
13005-CVGroup_Cafe_Idle2-1 = "흠, 조금은 흥미가 생기는데."
13005-CVGroup_Cafe_Idle3-1 = "앞으로의 계획은… 뭐, 괜찮으려나."
13005-CVGroup_Cafe_Idle4-1 = "의외로… 귀엽다고? 흠. 재미없는… 농담이네."
13005-CVGroup_Cafe_Idle5-1 = "뭐, 무섭게 생겼다는 건 알고 있어."
13005-CVGroup_WeaponGet_Idle1-1 = "선생의 결정에 이견은 없지만 말야.\n하아… 아무것도 아니야.\n기대하는 만큼 열심히 노력해 볼게."
