[translation]
13006-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
13006-CVGroup_CharacterGet_Idle1-1 = "Ta-da! I'm finally here! All right, Sensei, let's have some fun!"
13006-CVGroup_Cafe_Idle1-1 = "As long as it's fun, it's okay."
13006-CVGroup_Cafe_Idle2-1 = "Hmm? That doesn't look half-bad either!"
13006-CVGroup_Cafe_Idle3-1 = "Heehee! ♥"
13006-CVGroup_Cafe_Idle4-1 = "One head pat, please!"
13006-CVGroup_Cafe_Idle5-1 = "Let's play together!"
13006-CVGroup_WeaponGet_Idle1-1 = "Sensei! Look! Look! This weapon seems really powerful, and it's cute!"
