[translation]
16005-CVGroup_UITitle_Idle1-1 = "Bluuue Archive!"
16005-CVGroup_CharacterGet_Idle1-1 = "Keheehee! Oh... S-Sensei?"
16005-CVGroup_Cafe_Idle1-1 = "I-Is it really okay for me to be here?"
16005-CVGroup_Cafe_Idle2-1 = "H-Huh?! Sensei?!"
16005-CVGroup_Cafe_Idle3-1 = "Y-You see...um... Ugh... Ahhh!"
16005-CVGroup_Cafe_Idle4-1 = "I'm more at ease on the battlefield..."
16005-CVGroup_Cafe_Idle5-1 = "A place like this... I-I...!"
16005-CVGroup_WeaponGet_Idle1-1 = "Heeheeheehee... No doubt... Heeheeheeheeheeheehee!!!"
16005-CVGroup_UIEventLobby_Enter1-1 = "S-Sensei, um... It's n-nice to meet you!"
16005-CVGroup_UIEventLobby_Enter2-1 = "(I wonder what Sensei thinks about how I look...)"
16005-CVGroup_UIEventLobby_Enter2-2 = "Wh-Whoa!"
16005-CVGroup_UIEventLobby_Idle1-1 = "Oh... Um... Uh..."
16005-CVGroup_UIEventLobby_Idle2-1 = "I...I'm ready, Sensei."
16005-CVGroup_UIEventLobby_Idle3-1 = "(What to do, what to do...? What am I going to do?!)"
16005-CVGroup_UIEventLobby_Idle4-1 = "Ts-Tsurugi!"
16005-CVGroup_UIEventLobby_Idle4-2 = "Let's go!"
