[translation]
16009-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
16009-CVGroup_CharacterGet_Idle1-1 = "ฮุฮุฮุ... ขอโทษที่ให้รอนานนะ!\nหัวหน้าชมรมวิจัยศาสตร์นินจา! จิโดริ มิจิรุ...\nมาปรากฏตัวที่นี่แล้ว! ฝากตัวด้วยนะ ท่านอาจารย์!"
16009-CVGroup_Cafe_Idle1-1 = "เอาละ ต่อไปจะอัปวิดีโอแบบไหนลงช่องดีนะ?"
16009-CVGroup_Cafe_Idle2-1 = "<วิถีนินจาสาว มิจิรุจจี้>... เป้าหมายผู้ติดตาม 100 คน!"
16009-CVGroup_Cafe_Idle3-1 = "อ๊ะ คิดเคล็ดวิชาใหม่ขึ้นมาได้แล้วละ!"
16009-CVGroup_Cafe_Idle4-1 = "เอ๋...? <คามาโบโกะ ภาควายุสลาตัน> เล่มใหม่ วางขายเมื่อไรนะ?"
16009-CVGroup_Cafe_Idle5-1 = "ทะ... ที่ไหนๆ ก็มีนักเรียนเต็มไปหมด\nไม่ค่อยอยากเข้าไปใกล้เลย..."
16009-CVGroup_WeaponGet_Idle1-1 = "ว้าว... ให้ของแบบนี้กับข้าน้อย...?! ระ...รู้สึกเกรงใจนิดหน่อย...\nอื้ม... ไว้ใจได้เลย ท่านอาจารย์! ถ้างั้นข้าน้อยจะแสดงให้ดู... เคล็ดวิชานินจา!"
16009-CVGroup_UIEventLobby_Enter1-1 = "อ๊ะ! ทะ... ท่านอาจารย์...!\nตอนนี้พวกข้าน้อยกำลังทำกิจกรรมชมรมอยู่แหละ!"
16009-CVGroup_UIEventLobby_Enter1-2 = "เอ้า เอาละๆ! มาจัดการกันให้เสร็จเร็วๆ กันดีกว่า!"
16009-CVGroup_UIEventLobby_Enter2-1 = "ว้าว... รู้สึกเหมือนจะเกิดเรื่องวุ่นวายครั้งใหญ่เลยนะ..."
16009-CVGroup_UIEventLobby_Enter2-2 = "ทะ...ท่านอาจารย์ ไม่เป็นไรใช่มั้ย?\nพวกข้าน้อยเชื่อมั่นในท่านอาจารย์นะ"
16009-CVGroup_UIEventLobby_Enter3-1 = "อึก! เวลาล่วงเลยมาขนาดนี้แล้วเหรอ... มันไม่ช้าไปใช่มั้ยนะ...?"
16009-CVGroup_UIEventLobby_Enter3-2 = "อ๊ะ เจ้าพวกปีศาจ... น่ารำคาญจริงๆ เลยเชียว...!"
16009-CVGroup_UIEventLobby_Enter4-1 = "ข้าน้อยจะไม่ยอมแพ้จนถึงที่สุดเลย...!\nทั้งเรื่องขึ้นทะเบียนชมรมและเรื่องการเพิ่มผู้ติดตาม"
16009-CVGroup_UIEventLobby_Enter4-2 = "ช่องวิดีโอ <วิถีนินจาสาวมิจิรุจจี้> ให้ได้ 100 คนด้วย!"
16009-CVGroup_UIEventLobby_Enter5-1 = "เฮ้อ... ในที่สุดก็จบสักที ตอนนี้ก็กลับได้แล้วใช่มั้ย?"
16009-CVGroup_UIEventLobby_Enter5-2 = "เฮ้อ... อยากรีบกลับไปดูหนังนินจาจังเลย..."
16009-CVGroup_UIEventLobby_Enter5-3 = "หนังเกรดบี... ที่ดูแล้วไม่ต้องคิดอะไรมาก"
16009-CVGroup_UIEventLobby_Idle1-1 = "พวกปีศาจออกอาละวาด แถมยังถูกพวกชมรมหยินหยางกดดันอีก..."
16009-CVGroup_UIEventLobby_Idle1-2 = "พวกแพนเดโมเนียม โซไซตี้ น่ารำคาญชะมัด... นี่มันอะไรกันเนี่ย..."
16009-CVGroup_UIEventLobby_Idle2-1 = "หา?! ทะ...ท่านอาจารย์?! ทำอะไรน่ะ?!"
16009-CVGroup_UIEventLobby_Idle2-2 = "ถะ...ถ้าจู่ๆ มาจิ้มกันแบบนี้ มันตกใจนะ...?!"
16009-CVGroup_UIEventLobby_Idle3-1 = "นินจาน่ะ... คือผู้ที่ไม่ยอมแพ้"
16009-CVGroup_UIEventLobby_Idle3-2 = "ผู้ที่พยายามจนถึงที่สุดไม่ว่าจะเกิดอะไรขึ้น\nก็จะต้องทำภารกิจให้สำเร็จ"
16009-CVGroup_UIEventLobby_Idle3-3 = "ชมรมวิจัยศาสตร์นินจาของเรา...\nก็จะแสดงความมุ่งมั่นให้เห็นเอง!"
16009-CVGroup_UIEventLobby_Idle4-1 = "จัดการภารกิจของชมรมหยินหยางให้เรียบร้อย"
16009-CVGroup_UIEventLobby_Idle4-2 = "คราวนี้ก็คงจะได้รับการยอมรับเป็นชมรมทางการซะที!"
