[translation]
16007-CVGroup_UITitle_Idle1-1 = "Blue Archive"
16007-CVGroup_CharacterGet_Idle1-1 = "ยินดีที่ได้พบค่ะคุณครู\nคุณครูสนใจจะฟังเรื่องความสุดยอด\nของประธานเชริโน่ผู้ยิ่งใหญ่หน่อยมั้ยคะ?"
16007-CVGroup_Cafe_Idle1-1 = "คำพูดส่งเสริมจะต้องเริ่ม\nจากเรื่องเล็กๆ ค่อยๆ ปลูกฝังไป..."
16007-CVGroup_Cafe_Idle2-1 = "ฮุฮุ ของชิ้นเล็กน่ารักๆ\nดูเหมาะกับท่านประธานนะคะ"
16007-CVGroup_Cafe_Idle3-1 = "ที่นี่... อบอุ่นดีจังเลยนะคะ"
16007-CVGroup_Cafe_Idle4-1 = "คราวหน้าฉันจะต้องมาที่นี่กับประธานเชริโน่ให้ได้...!"
16007-CVGroup_Cafe_Idle5-1 = "เอ๋? รู้สึกเหมือนเห็นเงาของท่านประธาน..."
16007-CVGroup_WeaponGet_Idle1-1 = "ปืนสำหรับฉันเหรอคะ...?\nฮุฮุ ขอบคุณนะคะ คุณครู"
16007-CVGroup_UIEventBoxGachaShop_Enter1-1 = "ยินดีต้อนรับสู่สำนักเลขาธิการสหภาพเรดวินเทอร์ค่ะ คุณครู"
16007-CVGroup_UIEventBoxGachaShop_Enter2-1 = "ไม่ทราบว่าคุณครูพบตุ๊กตาแม่ลูกดกแบบพิเศษ\nของประธานเชริโน่ในเขตโรงเรียนของเรามั้ยคะ?"
16007-CVGroup_UIEventBoxGachaShop_Enter2-2 = "นำมาแลกที่นี่ได้นะคะ!"
16007-CVGroup_UIEventBoxGachaShop_Enter3-1 = "คุณครูสนุกกับงานเทศกาลรึเปล่าคะ?"
16007-CVGroup_UIEventBoxGachaShop_Enter3-2 = "ถ้าคุณครูพบตุ๊กตาแม่ลูกดกของท่านประธานละก็...\nรบกวนนำมาให้ฉันด้วยนะคะ!"
16007-CVGroup_UIEventBoxGachaShop_Enter4-1 = "งานเทศกาลครั้งนี้... อีกไม่นานก็จะจบลงแล้วนะคะ"
16007-CVGroup_UIEventBoxGachaShop_Enter4-2 = "น่าเสียดายจัง..."
16007-CVGroup_UIEventBoxGachaShop_Enter5-1 = "วันนี้เป็นวันสุดท้ายของงานเทศกาลอีวานคูปาลาค่ะ"
16007-CVGroup_UIEventBoxGachaShop_Enter5-2 = "ตรวจสอบให้ละเอียดจะได้แน่ใจว่าไม่ลืมอะไรไว้นะคะ!"
16007-CVGroup_UIEventBoxGachaShop_Enter6-1 = "ถึงงานเทศกาลจะจบไปแล้ว แต่สามารถนำตุ๊กตาแม่ลูกดกที่เหลืออยู่"
16007-CVGroup_UIEventBoxGachaShop_Enter6-2 = "มาแลกที่นี่ได้ตลอดเลยนะคะ"
16007-CVGroup_UIEventBoxGachaShop_Idle1-1 = "ตุ๊กตาแม่ลูกดกที่หน้าตาเหมือนท่านประธาน\nฉันเป็นคนออกแบบเองค่ะ"
16007-CVGroup_UIEventBoxGachaShop_Idle1-2 = "ฮุฮุ... น่ารักใช่มั้ยคะ?"
16007-CVGroup_UIEventBoxGachaShop_Idle2-1 = "ตุ๊กตาแม่ลูกดกน่ารักๆพวกนั้น...\nพอได้มองตุ๊กตาตัวน้อยๆ แบบนั้นแล้ว..."
16007-CVGroup_UIEventBoxGachaShop_Idle2-2 = "ก็รู้สึกปวดใจเหมือนกันนะคะ"
16007-CVGroup_UIEventBoxGachaShop_BoxGachaPrize1-1 = "ถูกรางวัลแล้วค่ะ ยินดีด้วยค่ะ!"
16007-CVGroup_UIEventBoxGachaShop_BoxGachaPrize2-1 = "อุ๊ย ถูกรางวัลด้วยค่ะ! คุณครูนี่โชคดีจริงๆ เลยนะคะ"
16007-CVGroup_UIEventBoxGachaShop_BoxGachaPrize3-1 = "ฮุฮุ ตาถึงมากเลยค่ะ กรุณาใช้มันอย่างดีด้วยนะคะ!"
16007-CVGroup_UIEventBoxGachaShop_BoxGachaPrize4-1 = "เป็นของขวัญน่ารักเหมือนท่านประธานเลยค่ะ!"
