[translation]
16006-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
16006-CVGroup_CharacterGet_Idle1-1 = "Summer! It's summer, Sensei! Come eat delicious food with me this summer!"
16006-CVGroup_Cafe_Idle1-1 = "Traditional summer foods. Shaved ice... Somen... Grilled sweetfish... Yum!"
16006-CVGroup_Cafe_Idle2-1 = "Next time we go to the beach, Sensei... We're eating 100 pieces of takoyaki!"
16006-CVGroup_Cafe_Idle3-1 = "They're a must for summer! Yakisoba, zarusoba, and nagashisomen!"
16006-CVGroup_Cafe_Idle4-1 = "It's so nice and cool here..."
16006-CVGroup_Cafe_Idle5-1 = "Swimsuit? Check. Stocked ice cooler? Check. I officially have everything ready for summer!"
16006-CVGroup_WeaponGet_Idle1-1 = "An equipment just for summer?! You got it for me?! Yay! I'm so happy!! Thank you!!"
16006-CVGroup_UIEventShop_Enter1-1 = "Oh, it's Sensei! Well, welcome to the Beach Shack!"
16006-CVGroup_UIEventShop_Enter2-1 = "Welcome, Sensei! I've been waiting for you!"
16006-CVGroup_UIEventShop_Idle1-1 = "Yes! Take a gander! Lots of tasty things!"
16006-CVGroup_UIEventShop_Idle2-1 = "Hey, Sensei! This one... Huh?"
16006-CVGroup_UIEventShop_Idle2-2 = "Come on, don't look at me! Look around the shop!"
16006-CVGroup_UIEventShop_Idle3-1 = "Um! N-Nothing for free, even if you keep poking me!"
16006-CVGroup_UIEventShop_Enter3-1 = "We're almost halfway to the end of the day! Enjoy while you can!"
16006-CVGroup_UIEventShop_Enter4-1 = "The end is close! Keep at it!"
16006-CVGroup_UIEventShop_Enter5-1 = "Sensei! Today's the store's last day. Did you get everything you want?"
16006-CVGroup_UIEventShop_Enter6-1 = "We're closed! Thank you everyone!"
16006-CVGroup_UIEventShop_Enter6-2 = "Thought that was it? Heehee. Don't worry. There's still some time left!"
16006-CVGroup_UIEventShop_Enter6-3 = "Remember to check one last time if you forgot anything!"
16006-CVGroup_UIEventShop_Buy1-1 = "Wow! I knew it, Sensei!"
16006-CVGroup_UIEventShop_Buy2-1 = "You chose that? Hmm... Good choice!"
