[translation]
16017-CVGroup_UITitle_Idle1-1 = "蔚，蔚藍檔案……這樣就行了嗎……？"
16017-CVGroup_CharacterGet_Idle1-1 = "我，我是高地人鐵道學園……\n內，內海青葉……\n不多指教，也沒關係的……"
16017-CVGroup_Cafe_Idle1-1 = "大，大家都帶著笑容……\n人生，快快樂樂的真不錯呢……"
16017-CVGroup_Cafe_Idle2-1 = "這裡……真寬廣呢……\n要是我們的值班室也能有這樣的空間……"
16017-CVGroup_Cafe_Idle3-1 = "我，我可以待在這裡嗎……？"
16017-CVGroup_Cafe_Idle4-1 = "（總覺得好像染上了油臭味……真是糟透了）"
16017-CVGroup_Cafe_Idle5-1 = "冷靜下來深呼吸……嘶，呼……"
16017-CVGroup_WeaponGet_Idle1-1 = "如，如果有礙眼的人……\n只，只要用這個\n射穿他就行了吧……？"
16017-CVGroup_UIEventLobby_Enter1-1 = "謝，謝謝您願意過來……"
16017-CVGroup_UIEventLobby_Enter1-2 = "有，有大人在的話……讓人，比較安心。"
16017-CVGroup_UIEventLobby_Enter2-1 = "平常並不是這樣的！只是這次比較特殊……"
16017-CVGroup_UIEventLobby_Enter2-2 = "啊……不對，好像也不能這麼說就是了……"
16017-CVGroup_UIEventLobby_Enter2-3 = "但，但也沒到修羅場這麼誇張……\n大概吧……我也不知道。"
16017-CVGroup_UIEventLobby_Enter3-1 = "唔唔……總，總覺得好像變成麻煩的事了……"
16017-CVGroup_UIEventLobby_Enter3-2 = "各位幹部……相信他們應該沒問題吧……？"
16017-CVGroup_UIEventLobby_Enter4-1 = "呼……都，都走到這一步了，應該已經沒事了吧……？"
16017-CVGroup_UIEventLobby_Enter5-1 = "唉……總算結束了……"
16017-CVGroup_UIEventLobby_Enter5-2 = "老師也真的……辛苦了。"
16017-CVGroup_UIEventLobby_Idle1-1 = "怎，怎麼了？"
16017-CVGroup_UIEventLobby_Idle1-2 = "咦……難，難道我做了什麼嗎……？"
16017-CVGroup_UIEventLobby_Idle2-1 = "總，總覺得有點可疑……"
16017-CVGroup_UIEventLobby_Idle2-2 = "希望會沒事……"
16017-CVGroup_UIEventLobby_Idle3-1 = "為，為什麼幹部們總是那樣呢……"
16017-CVGroup_UIEventLobby_Idle3-2 = "一點也不關注現場的情況……"
16017-CVGroup_UIEventLobby_Idle4-1 = "……怎，怎麼了嗎？"
16017-CVGroup_UIEventLobby_Idle4-2 = "很，很癢耶……那邊，不太能……呀啊。"
16017-CVGroup_UIEventMission_Enter1-1 = "雖然不覺得會真的結束……"
16017-CVGroup_UIEventMission_Enter2-1 = "有，有老師在真是太好了……"
16017-CVGroup_UIEventMission_Enter2-2 = "該說是可靠……還是安心呢……"
16017-CVGroup_UIEventMission_Enter2-3 = "耶嘿嘿。"
16017-CVGroup_UIEventMission_Idle1-1 = "就，就算摸我也不會發生什麼哦！？"
16017-CVGroup_UIEventMission_Idle2-1 = "得，得想想辦法才行……唔唔……"
16017-CVGroup_UIEventMission_Buy1-1 = "哇，哇啊……"
16017-CVGroup_UIEventMission_Buy2-1 = "太，太厲害了吧！？"
16017-CVGroup_UIEventMission_Interaction1-1 = "這，這就是……大人的力量……"
