[translation]
16011-CVGroup_UITitle_Idle1-1 = "蔚藍檔案。"
16011-CVGroup_CharacterGet_Idle1-1 = "哎呀，老師。在這裡也碰面了呢。\n我是三一綜合學園，實現正義部的羽川蓮實。\n這次由我代表三一擔任實行委員。請老師多多指教。"
16011-CVGroup_Cafe_Idle1-1 = "…這地方整裡得真好呢。"
16011-CVGroup_Cafe_Idle2-1 = "這裡明明不是競賽場，我這身服裝會不會很奇怪…？"
16011-CVGroup_Cafe_Idle3-1 = "那…那個是…？"
16011-CVGroup_Cafe_Idle4-1 = "跟平常不一樣，有點想跑步了呢。"
16011-CVGroup_Cafe_Idle5-1 = "（唔…減肥的大敵…)"
16011-CVGroup_WeaponGet_Idle1-1 = "謝謝您，老師。簡直像是得到錦旗一樣的感覺。\n只要老師陪在我的身邊，我今後也不會輸的。\n所以以後也請多多指教囉。"
16011-CVGroup_UIEventLobby_Enter1-1 = "讓您久等了，老師。準備好了嗎？"
16011-CVGroup_UIEventLobby_Enter2-1 = "正好比賽要開始了。一起去吧。"
16011-CVGroup_UIEventLobby_Enter3-1 = "氣氛相當熱烈呢。"
16011-CVGroup_UIEventLobby_Enter3-2 = "這樣的話，「晄輪大祭」……可以算是成功了吧。"
16011-CVGroup_UIEventLobby_Enter4-1 = "晄輪大祭也迎來了最後階段。"
16011-CVGroup_UIEventLobby_Enter4-2 = "堅持到最後吧。"
16011-CVGroup_UIEventLobby_Enter5-1 = "託老師的福，「晄輪大祭」取得了巨大的成功。"
16011-CVGroup_UIEventLobby_Enter5-2 = "真的辛苦您了。"
16011-CVGroup_UIEventLobby_Idle1-1 = "老，老師……"
16011-CVGroup_UIEventLobby_Idle2-1 = "就，就算這樣盯著我看……"
16011-CVGroup_UIEventLobby_Idle3-1 = "差不多該出發了……"
16011-CVGroup_UIEventLobby_Idle4-1 = "有什麼需要的嗎？"
16011-CVGroup_UIEventMission_Enter1-1 = "要確認比賽紀錄嗎？"
16011-CVGroup_UIEventMission_Enter2-1 = "我整理了進展狀況。\n要確認一下嗎？"
16011-CVGroup_UIEventMission_Idle1-1 = "那個……現在您看到的已經是全部了。"
16011-CVGroup_UIEventMission_Idle2-1 = "還有其他想確認的事嗎……？"
16011-CVGroup_UIEventMission_Buy1-1 = "已確認。\n很棒的記錄呢。"
16011-CVGroup_UIEventMission_Buy2-1 = "這個……說不定是新紀錄。"
16011-CVGroup_UIEventMission_Interaction1-1 = "今天的記錄到此結束。"
