[translation]
16013-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
16013-CVGroup_CharacterGet_Idle1-1 = "ฉันมาเพื่อจับตาดูคุณครูโดยเฉพาะ!\nเรื่องลามกเป็นสิ่งต้องห้าม! ห้ามเด็ดขาด!\nฉันจะไม่ยกโทษให้อย่างเด็ดขาด...!"
16013-CVGroup_Cafe_Idle1-1 = "ฮือ... คนเยอะจัง..."
16013-CVGroup_Cafe_Idle2-1 = "นะ...นั่นมัน...!?"
16013-CVGroup_Cafe_Idle3-1 = "ระ...หรือว่า มีแค่ฉันที่แต่งตัวแบบนี้กันนะ...?!"
16013-CVGroup_Cafe_Idle4-1 = "คุณครู...อยู่ไหนน่ะ..."
16013-CVGroup_Cafe_Idle5-1 = "ฉะ...ฉันไม่ได้ใส่ชุดนี้ เพราะชอบหรอกนะ!"
16013-CVGroup_WeaponGet_Idle1-1 = "นะ...นี่มัน อืม... มะ...ไม่ได้สิ คงต้องพูดให้ถูกต้องแล้วละ...\nขะ...ขอบคุณนะ คุณครู! จากนี้ไป ฉันก็จะพยายามให้มากขึ้น!\nคะ...แค่นี้ก็พอแล้วใช่มั้ย? ฉันเองก็พูดคำว่าขอบคุณเป็น\nเหมือนกันแหละน่า!"
16013-CVGroup_UIEventLobby_Enter1-1 = "ไม่มีเวลามารีรออยู่นะคุณครู! รีบไปกันเถอะ!"
16013-CVGroup_UIEventLobby_Enter2-1 = "อยู่กับฉันทั้งคน ไม่มีอะไรที่ทำลวกๆ หรอก!"
16013-CVGroup_UIEventLobby_Enter3-1 = "ฮุฮุ ไร้ปัญหา!"
16013-CVGroup_UIEventLobby_Enter4-1 = "พยายามเข้านะ! เหลืออีกไม่เยอะแล้ว!"
16013-CVGroup_UIEventLobby_Enter5-1 = "แค่เผื่อไว้ก่อนน่ะ ลองตรวจสอบดูอีกรอบมั้ย?"
16013-CVGroup_UIEventLobby_Idle1-1 = "ฮะ... เฮือก!? ตกใจหมดเลย... ฉันตกใจนะ คุณครู!"
16013-CVGroup_UIEventLobby_Idle2-1 = "ทะ... ทำอะไรตั้งแต่เมื่อกี้แล้ว... อย่าเอาแต่เรียกสิ"
16013-CVGroup_UIEventLobby_Idle3-1 = "อ่า... จริงๆ เลย! ถ้ามีธุระอะไร ก็บอกกันดีๆ สิ!"
16013-CVGroup_UIEventLobby_Idle4-1 = "อื้อ มีอะไรเหรอ?"
