[translation]
16015-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
16015-CVGroup_CharacterGet_Idle1-1 = "คุณครู... ฉันจะให้ดูภาพลักษณ์ของฉันที่เปลี่ยนไปค่ะ!"
16015-CVGroup_Cafe_Idle1-1 = "สถานที่สวยๆ...!"
16015-CVGroup_Cafe_Idle2-1 = "ทุกคนดูยอดเยี่ยม!"
16015-CVGroup_Cafe_Idle3-1 = "ถ้าฉันซ้อมที่นี่จะเป็นการรบกวนคนอื่นรึเปล่านะ...?"
16015-CVGroup_Cafe_Idle4-1 = "ชักจะหิวนิดหน่อยแล้วสิ..."
16015-CVGroup_Cafe_Idle5-1 = "ทุกคนจะชอบเพลงแบบไหนกันนะ?"
16015-CVGroup_WeaponGet_Idle1-1 = "ไม่คิดเลยนะคะว่าจะมีวันแบบนี้\n เรื่องแบบนี้เกิดขึ้นได้จริงๆ สินะคะ ดีใจจังเลยค่ะ"
16015-CVGroup_UIEventLobby_Enter1-1 = "เชิญค่ะคุณครู! ฉันกำลังรออยู่เลยค่ะ!"
16015-CVGroup_UIEventLobby_Enter2-1 = "คุณครู! ถ้าสะดวกละก็ ช่วยดูผลการฝึกซ้อมให้หน่อยนะคะ!"
16015-CVGroup_UIEventLobby_Enter3-1 = "ราบรื่นดีเลยค่ะ! ฉันเองก็จะพยายามนะคะ!"
16015-CVGroup_UIEventLobby_Enter4-1 = "ฉันจะพยายามจนถึงที่สุดเลยค่ะ! ช่วยเฝ้ามองฉันด้วยนะคะคุณครู!"
16015-CVGroup_UIEventLobby_Enter5-1 = "ฮ่า... โล่งจัง! คุณครูว่าเป็นยังไงบ้างคะ?"
16015-CVGroup_UIEventLobby_Idle1-1 = "คุณครู? เรียกฉันเหรอคะ...?"
16015-CVGroup_UIEventLobby_Idle2-1 = "อะ... เอ๋..."
16015-CVGroup_UIEventLobby_Idle2-2 = "ถ้าเอาแต่จิ้มกันอย่างนี้ละก็..."
16015-CVGroup_UIEventLobby_Idle3-1 = "จะ... จั๊กจี้นะคะ คุณครู..."
16015-CVGroup_UIEventLobby_Idle3-2 = "อะฮ่ะฮ่า..."
16015-CVGroup_UIEventLobby_Idle4-1 = "จริงๆ เลยเชียว~! เดี๋ยวฉันเอาคืนบ้างนะคะ!"
16015-CVGroup_UIEventMiniGameMission_Enter1-1 = "สวัสดีค่ะคุณครู! ฉันกำลังรออยู่เลยค่ะ!"
16015-CVGroup_UIEventMiniGameMission_Enter2-1 = "มาแล้วเหรอคะคุณครู! ฉันสรุปความคืบหน้าเอาไว้ให้แล้วค่ะ!"
16015-CVGroup_UIEventMiniGameMission_Idle1-1 = "คะ...คุณครู...!"
16015-CVGroup_UIEventMiniGameMission_Idle2-1 = "ยะ... อย่ามองฉันสิคะ ไปดูตรงนั้นค่ะ..."
16015-CVGroup_UIEventMiniGameMission_Buy1-1 = "ค่ะ! อยู่ตรงนี้ค่ะ!"
16015-CVGroup_UIEventMiniGameMission_Buy2-1 = "ตรวจสอบเรียบร้อยค่ะ!"
16015-CVGroup_UIEventMission_Interaction1-1 = "วันนี้เสร็จแค่นี้ค่ะ!\nยอดเยี่ยมเลยค่ะ!"
