[translation]
20003-CVGroup_UITitle_Idle1-1 = "Blue Archive"
20003-CVGroup_CharacterGet_Idle1-1 = "นักเรียนชั้นปีที่ 1 ชมรมทวงความยุติธรรม มาที่นี่ตามคำสั่งแล้วค่ะ\nถึงฉันยังไม่โตเป็นผู้ใหญ่ แต่ก็จะพยายามทำให้เต็มที่ค่ะ"
20003-CVGroup_Cafe_Idle1-1 = "ตกแต่งแบบนี้... รุ่นพี่ซึรุกิอาจจะไม่ชอบก็ได้นะ..."
20003-CVGroup_Cafe_Idle2-1 = "ปีกของรุ่นพี่ฮาสุมิดูนุ่มฟูเหมือนของตกแต่งอันนี้เลย"
20003-CVGroup_Cafe_Idle3-1 = "เยือกเย็นเหมือนน้ำ..."
20003-CVGroup_Cafe_Idle4-1 = "คอของรุ่นพี่ซึรุกิจะไม่เป็นอะไรใช่มั้ยนะ...?"
20003-CVGroup_Cafe_Idle5-1 = "บางที สถานที่แบบนี้ก็... ไม่ได้แย่เท่าไรนะ"
20003-CVGroup_Cafe_Idle6-1 = "สวยจังเลย ฮุฮุ"
20003-CVGroup_WeaponGet_Idle1-1 = "นี่ก็คือความยุติธรรม... ที่แท้จริง..."
