[translation]
20001-CVGroup_UITitle_Idle1-1 = "Blue Archive"
20001-CVGroup_CharacterGet_Idle1-1 = "ที่จริงนายท่านของฉันคือมิลเลเนียม\nแต่ว่าวันนี้... คุณครูคือนายท่านของฉัน"
20001-CVGroup_Cafe_Idle1-1 = "ถึงเวลาเรียนคณิตศาสตร์แล้ว...\nเฮ้อ... ตัวเลขน่าเบื่อที่สุด"
20001-CVGroup_Cafe_Idle2-1 = "ที่นี่งดงามจริงๆ... สักวันฉันก็จะงดงาม...\nอ๊ะ? คงไม่ได้ยินใช่มั้ยนะ?!"
20001-CVGroup_Cafe_Idle3-1 = "บางครั้งเวลาพักผ่อนก็สำคัญนะ"
20001-CVGroup_Cafe_Idle4-1 = "ของน่ารักๆ เหรอ? ชอบสิ\nเรื่องนั้นมัน... มีปัญหาอะไรงั้นเหรอ?"
20001-CVGroup_Cafe_Idle5-1 = "รุ่นพี่เนรุกับรุ่นพี่อาสึนะมักจะอยู่แนวหน้าเสมอ\nฉันน่ะเหรอ? ฉันก็คอยปกป้องพวกเขาจากทางด้านหลังยังไงล่ะ"
20001-CVGroup_WeaponGet_Idle1-1 = "การแพ้ชนะของการต่อสู้วัดกันที่ชั้นเชิงของอาวุธสินะ\nคุณครู คอยดูฝีมือของฉันให้ดีล่ะ"
