[translation]
20017-CVGroup_UITitle_Idle1-1 = "Blue Archive."
20017-CVGroup_CharacterGet_Idle1-1 = "Heehee... Finally, I made it. It's gonna be really hard, right? But I've learned that's just life... I'm Hiyori. Nice to meet you..."
20017-CVGroup_Cafe_Idle1-1 = "Heehee... Excuse me."
20017-CVGroup_Cafe_Idle2-1 = "There's a lot of nice furniture here..."
20017-CVGroup_Cafe_Idle3-1 = "This looks nice. That's nice too... Everything is nice..."
20017-CVGroup_Cafe_Idle4-1 = "Heehee... Sorry to inconvenience you. Excuse me."
20017-CVGroup_Cafe_Idle5-1 = "I have a good feeling about this...I think...maybe not..."
20017-CVGroup_WeaponGet_Idle1-1 = "I know that you're trying to make me work as your servant. Heehee...I have no choice, so I'll accept."
