[translation]
20010-CVGroup_UITitle_Idle1-1 = "蔚藍檔案。"
20010-CVGroup_CharacterGet_Idle1-1 = "歡迎來到227號溫泉浴場，老師。\n我和香，身為溫泉浴場的女將，將會誠心誠意款待老師！"
20010-CVGroup_Cafe_Idle1-1 = "要是227號溫泉浴場也有這種家具就太好了。"
20010-CVGroup_Cafe_Idle2-1 = "這間咖啡廳無論何時都很多人……\n到底有什麼祕訣呢？"
20010-CVGroup_Cafe_Idle3-1 = "嗚喔……\n看起來很高級的東西……"
20010-CVGroup_Cafe_Idle4-1 = "（咦？剛才老師明明還在這附近啊……）"
20010-CVGroup_Cafe_Idle5-1 = "（舊校舍……還不想回去……）"
20010-CVGroup_WeaponGet_Idle1-1 = "我反而希望在溫泉浴場使用這個武器的機會能少一點……\n不過真的需要的時候……我會好好使用！"
20010-CVGroup_UIEventLobby_Enter1-1 = "歡迎光臨。\n歡迎來到227號溫泉浴場！"
20010-CVGroup_UIEventLobby_Enter2-1 = "啊哇哇！老，老師！？\n咦，請問今天有預約嗎……！？"
20010-CVGroup_UIEventLobby_Idle1-1 = "不只能賺錢，還能飽覽許多漂亮的景色……"
20010-CVGroup_UIEventLobby_Idle1-2 = "溫泉浴場，最棒了呢！"
20010-CVGroup_UIEventLobby_Idle2-1 = "怎麼了嗎，老師？\n有什麼備品不夠了嗎？"
20010-CVGroup_UIEventLobby_Idle3-1 = "呵呵……現在的我和從前的我已經完全不一樣了唷！"
20010-CVGroup_UIEventLobby_Idle4-1 = "呵呵，現在的我游刃有餘到……"
20010-CVGroup_UIEventLobby_Idle4-2 = "餐後的布丁可以吃兩個！"
20010-CVGroup_UIEventLobby_Enter3-1 = "從溫泉浴場開始營運，轉眼間已經一周了。"
20010-CVGroup_UIEventLobby_Enter3-2 = "我是不是也快要培養出身為女將的風采了呢……！"
20010-CVGroup_UIEventLobby_Enter4-1 = "溫泉浴場的營運居然會是件這麼困難的事……"
20010-CVGroup_UIEventLobby_Enter4-2 = "真是讓人意想不到。"
20010-CVGroup_UIEventLobby_Enter5-1 = "雖然溫泉浴場已經不在了……\n但我是不會因為這點小事就氣餒的！"
20010-CVGroup_UIEventShop_Enter1-1 = "溫泉商品也準備了很多唷！"
20010-CVGroup_UIEventShop_Enter2-1 = "如果有用不到的東西，\n可以在這裡和別的商品進行交換！"
20010-CVGroup_UIEventShop_Idle1-1 = "老師？怎麼了嗎？"
20010-CVGroup_UIEventShop_Idle2-1 = "就，就算是老師，免費給您也……！"
20010-CVGroup_UIEventShop_Buy1-1 = "謝謝惠顧！"
20010-CVGroup_UIEventShop_Buy2-1 = "一直以來很謝謝你，老師。"
20010-CVGroup_UIEventShop_Buy3-1 = "感謝您今天的惠顧！"
20010-CVGroup_UIEventShop_Buy4-1 = "這，這麼好的東西，我真的，可以收下嗎……？"
20010-CVGroup_UIEventShop_Enter3-1 = "雖然遺憾，但是227號溫泉浴場的營業已經結束了……"
