[translation]
20016-CVGroup_UITitle_Idle1-1 = "Blue... Archive~"
20016-CVGroup_CharacterGet_Idle1-1 = "เฮ้อ ทำไมถึงกลายเป็นแบบนี้ได้คะ?\nแต่ในเมื่อเป็นแบบนี้แล้ว ก็คงต้องทำสินะคะ"
20016-CVGroup_Cafe_Idle1-1 = "สถานที่ที่จะอ่านหนังสือได้อย่างเงียบๆ..."
20016-CVGroup_Cafe_Idle2-1 = "อา... ขี้เกียจจัง..."
20016-CVGroup_Cafe_Idle3-1 = "พวกเรื่องวุ่นวายต่างๆ มันค่อนข้าง..."
20016-CVGroup_Cafe_Idle4-1 = "สถานที่ที่จะซ่อนตัวได้..."
20016-CVGroup_Cafe_Idle5-1 = "ถ้าเป็นที่นี่คงไม่ถูกเจอตัวแน่ๆ"
20016-CVGroup_WeaponGet_Idle1-1 = "เฮ้อ จริงๆ เลย ถ้าแบบนี้...\nฉันก็คงจะต้องตั้งใจทำแล้วสินะคะ"
20016-CVGroup_UIEventLobby_Enter1-1 = "จริงๆ เลย มีปัญหาเยอะแยะเลยนะคะ"
20016-CVGroup_UIEventLobby_Enter2-1 = "เฮ้อ... ไม่ไหวจริงๆ ด้วยค่ะ"
20016-CVGroup_UIEventLobby_Enter3-1 = "เวลาผ่านไปขนาดนี้แล้ว\nคุณครูจะยอมมาตามเวลาที่ฉันขอได้รึเปล่าคะ"
20016-CVGroup_UIEventLobby_Enter4-1 = "รู้สึกเหมือนจัดการทุกอย่างแล้ว...\nแต่ว่าเราจะวางใจจนกว่าจะเสร็จงานไม่ได้ค่ะ"
20016-CVGroup_UIEventLobby_Enter4-2 = "ถึงฉันจะไม่ชอบงานที่น่ารำคาญก็เถอะ"
20016-CVGroup_UIEventLobby_Enter5-1 = "เหมือนว่าจะจัดการเรื่องวุ่นวายได้แล้วนะคะ\nเหนื่อยหน่อยนะคะ คุณครู"
20016-CVGroup_UIEventLobby_Idle1-1 = "งานแลกเปลี่ยนคราวนี้\nกลายเป็นงานที่วุ่นวายไปซะแล้วค่ะ"
20016-CVGroup_UIEventLobby_Idle2-1 = "เฮ้อ... อยากให้คิดถึงหน้าที่ของคน\nที่ต้องคอยเก็บกวาดงานบ้างจังเลยค่ะ"
20016-CVGroup_UIEventLobby_Idle3-1 = "ทำไมถึงมาที่เขตปกครองตนเอง\nของคนอื่นแล้วสร้างความวุ่นวาย..."
20016-CVGroup_UIEventLobby_Idle4-1 = "เรื่องแบบนี้ ในฐานะผู้ดูแลกลาง\nมันน่าปวดหัวมากเลยค่ะ"
20016-CVGroup_UIEventMission_Enter1-1 = "นี่เป็นปัญหาที่จะต้องแก้ไขสินะคะ"
20016-CVGroup_UIEventMission_Enter2-1 = "รบกวนตรวจสอบรายการด้วยนะคะ คุณครู"
20016-CVGroup_UIEventMission_Idle1-1 = "ถึงจะน่ารำคาญสักหน่อย\nแต่มีคุณครูอยู่ด้วยแบบนี้ ค่อยยังชั่วหน่อยค่ะ"
20016-CVGroup_UIEventMission_Idle2-1 = "เหนื่อย~ จัง~ เลย~"
20016-CVGroup_UIEventMission_Buy1-1 = "ฮู่ว... ผ่านไปได้อีกเรื่องหนึ่งแล้วนะคะ"
20016-CVGroup_UIEventMission_Buy2-1 = "แก้ไขได้แล้วเหรอคะ? ขอบคุณมากค่ะ"
20016-CVGroup_UIEventMission_Interaction1-1 = "เท่านี้ก็คงแก้ไขได้เรียบร้อยแล้วนะคะ\nขอบคุณมากค่ะ"
