[translation]
20029-CVGroup_UITitle_Idle1-1 = "블루 아카이브~"
20029-CVGroup_CharacterGet_Idle1-1 = "여름…… 바다…… 즐거움으로 가득하네요, 선생님.\n물론 수행도 잊지 않았어요."
20029-CVGroup_Cafe_Idle1-1 = "여러분이 편히 쉴 수 있는 장소를 만들어 볼까요?"
20029-CVGroup_Cafe_Idle2-1 = "시원한 곳이네요. 쉬기에 좋겠어요."
20029-CVGroup_Cafe_Idle3-1 = "다들 즐기고 있는 것 같네요. 다행이에요."
20029-CVGroup_Cafe_Idle4-1 = "츠바키 쨩과 카에데 쨩은, 뭘 하고 있을까요……"
20029-CVGroup_Cafe_Idle5-1 = "저도 모르게 축 늘어지는 게…… 여름…… 무섭네요!"
20029-CVGroup_WeaponGet_Idle1-1 = "이렇게 멋진 선물을 받다니……\n가슴에서 넘쳐흐르는 제 마음을, 말로 잘 전하고 싶습니다만…… 정리가 잘 안 돼서…\n그…… 감사합니다, 선생님."
20029-CVGroup_UIEventLobby_Enter1-1 = "아, 어서 오세요. 선생님."
20029-CVGroup_UIEventLobby_Enter1-2 = "바다의 집이랍니다. 열심히 준비했어요."
20029-CVGroup_UIEventLobby_Enter2-1 = "기다리고 있었어요. 선생님."
20029-CVGroup_UIEventLobby_Enter2-2 = "후후. 마츠리운영관리부 여러분을 돕는 것도 보람찬 일이네요."
20029-CVGroup_UIEventLobby_Enter3-1 = "리조트 사냥… 엄청난 일이 되어 가고 있네요…"
20029-CVGroup_UIEventLobby_Enter3-2 = "아뇨. 이럴 때일수록 마음을 다잡아야겠지요."
20029-CVGroup_UIEventLobby_Enter4-1 = "처음에는, 불안하지 않았다면 거짓말이었겠지만…"
20029-CVGroup_UIEventLobby_Enter4-2 = "이것도 다, 선생님이 있어주신 덕분이네요."
20029-CVGroup_UIEventLobby_Enter5-1 = "여름 바다의 추억이라는 건… 멋진 단어네요."
20029-CVGroup_UIEventLobby_Enter5-2 = "이번은 특별히, 더 그랬던 것 같아요."
20029-CVGroup_UIEventLobby_Idle1-1 = "선생님? 부르셨나요?"
20029-CVGroup_UIEventLobby_Idle1-2 = "언제든지 말씀해 주세요."
20029-CVGroup_UIEventLobby_Idle2-1 = "꽤 덥네요… 열사병 조심하세요, 선생님."
20029-CVGroup_UIEventLobby_Idle2-2 = "여차하면 제가 돌봐 드릴게요."
20029-CVGroup_UIEventLobby_Idle3-1 = "시즈코 쨩… 괜찮을까요? 조금, 걱정이 되네요."
20029-CVGroup_UIEventLobby_Idle4-1 = "사건을 해결하는 것은… 어려울 것 같기도 하지만,"
20029-CVGroup_UIEventLobby_Idle4-2 = "모두와 협력하면, 분명 괜찮겠죠."
20029-CVGroup_UIEventLobby_Idle5-1 = "지금이야말로 수행의 성과를 보여줄 때, 일지도 모르겠네요."
