[translation]
20022-CVGroup_UITitle_Idle1-1 = "블루 아카이브."
20022-CVGroup_CharacterGet_Idle1-1 = "해넘이 국수는 드셨나요. 선생님?\n올해에는 선생님도 저도, 무탈한 한 해가 되었으면 좋겠네요."
20022-CVGroup_Cafe_Idle1-1 = "요리에서는 확실하게 계량하는 것이 중요하답니다."
20022-CVGroup_Cafe_Idle2-1 = "이 기모노…… 예쁘네."
20022-CVGroup_Cafe_Idle3-1 = "올해의 새해 첫 꿈은…… 뭐였더라?"
20022-CVGroup_Cafe_Idle4-1 = "부디 올해는, 평온한 나날이 계속되기를……."
20022-CVGroup_Cafe_Idle5-1 = "여기에선 조금 쉴 수 있으려나……"
20022-CVGroup_WeaponGet_Idle1-1 = "신기하죠? 선생님만 계시면, 무엇이든 할 수 있을 것 같아요.\n올해에도 힘내겠습니다. 지켜봐 주세요."
20022-CVGroup_UIEventLobby_Enter1-1 = "안녕하세요. 선생님! 새해의 소원은 정하셨나요?"
20022-CVGroup_UIEventLobby_Enter1-2 = "저도 옆에서 같이 빌어 드릴게요!"
20022-CVGroup_UIEventLobby_Enter2-1 = "춥지 않으세요? 따뜻한 식사라도 어떠신가요?"
20022-CVGroup_UIEventLobby_Idle1-1 = "네, 선생님? 무슨 일이세요?"
20022-CVGroup_UIEventLobby_Idle2-1 = "이 스쿠터는 여러 용도에 사용하고 있어요."
20022-CVGroup_UIEventLobby_Idle2-2 = "이것마저 없어져 버리면… 어쩌죠…"
20022-CVGroup_UIEventLobby_Idle3-1 = "오세치 이외의 새해 요리에도 도전해 보고 싶어요!"
20022-CVGroup_UIEventLobby_Idle3-2 = "네, 뭐, 그걸 다 먹으면… 살이 찌겠지만요."
20022-CVGroup_UIEventLobby_Idle4-1 = "새해 소원… 까지는 아니지만,"
20022-CVGroup_UIEventLobby_Idle4-2 = "올해에는 급식실이 무사했으면 좋겠네요…"
20022-CVGroup_UIEventLobby_Enter3-1 = "네…지금이야말로 요리 솜씨를 보여줄 때군요!"
20022-CVGroup_UIEventLobby_Enter3-2 = "저, 열심히 할 테니까… 지켜봐 주시면 감사하겠습니다."
20022-CVGroup_UIEventLobby_Enter4-1 = "왠지 엄청난 일이 되어버렸지만, 제가 하는 일은 변하지 않아요."
20022-CVGroup_UIEventLobby_Enter4-2 = "그저 최선을 다하는 것, 그것뿐입니다."
20022-CVGroup_UIEventLobby_Enter4-3 = "게다가… 선생님께서 곁에 있어 주시니 마음이 든든해요!"
20022-CVGroup_UIEventLobby_Enter5-1 = "무사히 마무리되어서 다행이에요."
20022-CVGroup_UIEventLobby_Enter5-2 = "그…… 제 요리, 입맛에 맞으셨나요?"
20022-CVGroup_UIEventShop_Enter1-1 = "선생님, 어서 오세요. 상가 분들이 여러 가지 물품을 준비해 주셨어요."
20022-CVGroup_UIEventShop_Enter2-1 = "가게를 보는 건 처음이네요. 에헤헤."
20022-CVGroup_UIEventShop_Idle1-1 = "괜찮아요. 걱정하지 마세요."
20022-CVGroup_UIEventShop_Idle1-2 = "창고 관리라면, 나름대로 자신이 있으니까요."
20022-CVGroup_UIEventShop_Idle2-1 = "네? 급양부 특제 요리, 말씀이신가요……?"
20022-CVGroup_UIEventShop_Idle2-2 = "혹시 괜찮으시다면 만들어 드릴까요?"
20022-CVGroup_UIEventShop_Buy1-1 = "아, 그거라면 잠시만 기다려주세요."
20022-CVGroup_UIEventShop_Buy2-1 = "그건, 가장 추천하는 상품입니다!"
20022-CVGroup_UIEventShop_Buy3-1 = "앗… 네. 이거 말씀하시는 거죠?"
20022-CVGroup_UIEventShop_Buy4-1 = "마음에 드셨어요? 또 와 주세요!"
20022-CVGroup_UIEventShop_Enter3-1 = "축제도 요리대회도 끝났네요."
20022-CVGroup_UIEventShop_Enter3-2 = "저는 내일을 위한 준비가 남아 있습니다만… 선생님은 차분히 둘러보다 가세요."
