[translation]
20036-CVGroup_UITitle_Idle1-1 = "블루 아카이브!"
20036-CVGroup_CharacterGet_Idle1-1 = "\"최고의 휴가\"로 만들겠어! 타협은 없다고!"
20036-CVGroup_Cafe_Idle1-1 = "흐응…… 다들 바빠 보이네."
20036-CVGroup_Cafe_Idle2-1 = "갑자기 물총싸움이 하고 싶네."
20036-CVGroup_Cafe_Idle3-1 = "바비큐 할까?"
20036-CVGroup_Cafe_Idle4-1 = "……청소 좀 해둘까."
20036-CVGroup_Cafe_Idle5-1 = "후우……. 시원하다."
20036-CVGroup_WeaponGet_Idle1-1 = "이렇게 놀기만 해도 괜찮은 건가...\n선, 선생님이 괜찮다고 했으니까! 제대로 책임져!?"
20036-CVGroup_UIEventLobby_Enter1-1 = "자, 선생님! 시간이 없어! 빨리 가자고!"
20036-CVGroup_UIEventLobby_Enter2-1 = "아, 선생님! 이쪽이야, 이쪽!"
20036-CVGroup_UIEventLobby_Idle1-1 = "응? 왜? 해야 할 거 있어?"
20036-CVGroup_UIEventLobby_Idle2-1 = "선생님……. 뭐하는거야?"
20036-CVGroup_UIEventLobby_Idle3-1 = "그거, 재밌어하는 거야? 어?"
20036-CVGroup_UIEventLobby_Idle4-1 = "이상한 짓 좀 하지 말고, 해야할 걸 해! 얼른!"
