[translation]
20040-CVGroup_UITitle_Idle1-1 = "蔚藍，檔案～"
20040-CVGroup_CharacterGet_Idle1-1 = "讓你久等了吧，老師。\n我就是萬魔殿的情報部長，京極皐月。\n呵呵，請多指教。"
20040-CVGroup_Cafe_Idle1-1 = "來進行夏萊的情報蒐集吧。"
20040-CVGroup_Cafe_Idle2-1 = "哼～嗯？\n挺不賴的嘛。"
20040-CVGroup_Cafe_Idle3-1 = "讓那些孩子們潛入這裡……"
20040-CVGroup_Cafe_Idle4-1 = "有別於我們的審問技術，\n真令人在意呢……"
20040-CVGroup_Cafe_Idle5-1 = "催眠術的練習台……\n有人會願意擔任嗎？"
20040-CVGroup_WeaponGet_Idle1-1 = "哎呀，準備得真周到呢。\n呵呵，相當有幫助哦，老師。"
20040-CVGroup_UIEventLobby_Enter1-1 = "歡迎你，老師。\n想看什麼儘管看吧。"
20040-CVGroup_UIEventLobby_Enter2-1 = "這可是我們萬魔殿準備的派對。"
20040-CVGroup_UIEventLobby_Enter2-2 = "老師肯定會喜歡的。"
20040-CVGroup_UIEventLobby_Enter3-1 = "哎呀，進度似乎不太順利呢。"
20040-CVGroup_UIEventLobby_Enter3-2 = "算了，反正真琴醬會想辦法解決的吧？"
20040-CVGroup_UIEventLobby_Enter4-1 = "沒想到能在這裡得到老師的幫助。"
20040-CVGroup_UIEventLobby_Enter4-2 = "呵呵，拜託你囉，老師？"
20040-CVGroup_UIEventLobby_Enter5-1 = "派對就到此結束了。"
20040-CVGroup_UIEventLobby_Enter5-2 = "你看？就跟我說的一樣，總會有辦法的吧？"
20040-CVGroup_UIEventLobby_Idle1-1 = "哼嗯～一直那樣調戲我……"
20040-CVGroup_UIEventLobby_Idle1-2 = "有什麼需要嗎？"
20040-CVGroup_UIEventLobby_Idle2-1 = "老師你，想要什麼呢？"
20040-CVGroup_UIEventLobby_Idle3-1 = "呵呵，老師……試著對我施加催眠吧。"
20040-CVGroup_UIEventLobby_Idle3-2 = "當然這對我不管……"
20040-CVGroup_UIEventLobby_Idle3-3 = "嗯？不用了？"
20040-CVGroup_UIEventLobby_Idle3-4 = "呵呵，別那麼說嘛……來來來。"
20040-CVGroup_UIEventLobby_Idle4-1 = "再那樣心不在焉的話，可能會被真琴醬纏上哦？"
20040-CVGroup_UIEventLobby_Idle4-2 = "來，過來這邊吧。"
