[translation]
20049-CVGroup_UITitle_Idle1-1 = "Blue, Archive"
20049-CVGroup_CharacterGet_Idle1-1 = "It's so hot and humid. What do we do now?"
20049-CVGroup_Cafe_Idle1-1 = "I'm bored..."
20049-CVGroup_Cafe_Idle2-1 = "(What...is that?)"
20049-CVGroup_Cafe_Idle3-1 = "So this is how people spend their free time..."
20049-CVGroup_Cafe_Idle4-1 = "Like I said, not interested. Seriously."
20049-CVGroup_Cafe_Idle5-1 = "(I wonder...what Sensei's doing now.)"
20049-CVGroup_WeaponGet_Idle1-1 = "I wonder if I'd even use it here... \"It's up to me how I use it\"? *sigh* You always have a way with words. Fine... Thank you."
20049-CVGroup_UIEventLobby_Enter1-1 = "Ah, you're here. ...I'm enjoying things at my own pace."
20049-CVGroup_UIEventLobby_Enter2-1 = "So this is the ocean..."
20049-CVGroup_UIEventLobby_Enter3-1 = "Sigh... I want to go somewhere quiet."
20049-CVGroup_UIEventLobby_Enter3-2 = "Please do something, Sensei."
20049-CVGroup_UIEventLobby_Enter4-1 = "What's with this crowd...? I guess they seem harmless."
20049-CVGroup_UIEventLobby_Enter5-1 = "It's over... Yeah, wasn't too bad. I'll give you that."
20049-CVGroup_UIEventLobby_Idle1-1 = "What's wrong, Sensei?"
20049-CVGroup_UIEventLobby_Idle1-2 = "Well, regardless of what you say, I don't plan on being entertained."
20049-CVGroup_UIEventLobby_Idle2-1 = "(...Maybe it'll be a new experience.)"
20049-CVGroup_UIEventLobby_Idle3-1 = "Wh-What the...? Why are you poking me? I'm not a stuffed animal!"
20049-CVGroup_UIEventLobby_Idle4-1 = "...You're bored? Why don't you go watch something at the outdoor stage?"
20049-CVGroup_UIEventLobby_Idle4-2 = "Me? I'm not interested...\nUnless you want to go..."
20049-CVGroup_UIEventLobby_Idle4-3 = "Then I'll go with you."
