[translation]
20045-CVGroup_UITitle_Idle1-1 = "Blue Archive"
20045-CVGroup_CharacterGet_Idle1-1 = "Asahina Pina from Allied Hyakkiyako Academy Festival Operations Department! I'll guide you!"
20045-CVGroup_Cafe_Idle1-1 = "Wow... It looks like an office from a gangster movie. How cool!"
20045-CVGroup_Cafe_Idle2-1 = "(This TV... I can watch movies on it!)"
20045-CVGroup_Cafe_Idle3-1 = "This atmosphere... I have experienced it before!"
20045-CVGroup_Cafe_Idle4-1 = "There are many cool people... Pina can't lose!"
20045-CVGroup_Cafe_Idle5-1 = "The sight of people relaxing makes me sleepy too!"
20045-CVGroup_WeaponGet_Idle1-1 = "I think I've leveled up by one— No! By 500 levels!"
20045-CVGroup_UIEventLobby_Enter1-1 = "Welcome tooo...Hyakkiyako!"
20045-CVGroup_UIEventLobby_Enter2-1 = "Welcome to Hyakkiyako!"
20045-CVGroup_UIEventLobby_Enter3-1 = "Sensei! Are you enjoying yourself?"
20045-CVGroup_UIEventLobby_Enter4-1 = "I've grown accustomed to do this! I shall do my utmost to the very end!"
20045-CVGroup_UIEventLobby_Enter5-1 = "Sensei! Please come find Hyakkiyako and Pina next time as well!"
20045-CVGroup_UIEventLobby_Idle1-1 = "Ta-da! Leave the guiding to me!"
20045-CVGroup_UIEventLobby_Idle2-1 = "Let's take much care to not get lost!"
20045-CVGroup_UIEventLobby_Idle3-1 = "It's very lively with you here!"
20045-CVGroup_UIEventLobby_Idle4-1 = "I'm glad that everyone's having fun!"
