[translation]
20052-CVGroup_UITitle_Idle1-1 = "蔚藍，檔案。呣呵呵。"
20052-CVGroup_CharacterGet_Idle1-1 = "印刷、裝訂、管理、流通──\n與書本相關的事宜，歡迎向赤冬出版部部長，\n荒槇八雲洽談。呣呵呵。"
20052-CVGroup_Cafe_Idle1-1 = "那麼……新的銷路在……"
20052-CVGroup_Cafe_Idle2-1 = "這裡，溫暖得令人安心呢……"
20052-CVGroup_Cafe_Idle3-1 = "要是在那邊設個販售區……呣呵呵。"
20052-CVGroup_Cafe_Idle4-1 = "最近的文學，就跟平台商業一樣呢。"
20052-CVGroup_Cafe_Idle5-1 = "那麼，今天的銷售額是……？"
20052-CVGroup_WeaponGet_Idle1-1 = "笨蛋和剪刀都取決於如何使用……\n看來今後似乎能讓人「確實」遵守契約了呢……呣呵呵。"
20052-CVGroup_UIEventLobby_Enter1-1 = "沒有風險就沒有報酬。"
20052-CVGroup_UIEventLobby_Enter1-2 = "那麼，開始處理事業吧。"
20052-CVGroup_UIEventLobby_Enter2-1 = "就趁現在，讓您見識一下吧。"
20052-CVGroup_UIEventLobby_Enter2-2 = "能在不毛之地赤冬存活下來的，我們出版部的手腕！"
20052-CVGroup_UIEventLobby_Enter2-3 = "……與手腕相比，"
20052-CVGroup_UIEventLobby_Enter2-4 = "生存能力這個詞，或許更加貼切呢。"
20052-CVGroup_UIEventLobby_Enter3-1 = "來了呢……氣勢來了呢！"
20052-CVGroup_UIEventLobby_Enter3-2 = "身為出版部長，這可是無論如何都要拿下的哦！"
20052-CVGroup_UIEventLobby_Enter4-1 = "為什麼會變成這樣……"
20052-CVGroup_UIEventLobby_Enter4-2 = "雖然……原因我好像也知道就是了……"
20052-CVGroup_UIEventLobby_Enter4-3 = "還不能放棄唷……！"
20052-CVGroup_UIEventLobby_Enter5-1 = "哎呀～剛才一度還不知道會變成什麼樣子呢……"
20052-CVGroup_UIEventLobby_Enter5-2 = "能順利結束真是太好了～\n……咦，檢討會是嗎？"
20052-CVGroup_UIEventLobby_Enter5-3 = "呃……那個改天再來……是不行的嗎……？"
20052-CVGroup_UIEventLobby_Idle1-1 = "身為創作者的各位……"
20052-CVGroup_UIEventLobby_Idle1-2 = "明明擁有創造事物的能力，"
20052-CVGroup_UIEventLobby_Idle1-3 = "卻對將其推廣出去這件事──"
20052-CVGroup_UIEventLobby_Idle1-4 = "不感興趣的例子，還挺多的呢……"
20052-CVGroup_UIEventLobby_Idle2-1 = "書……文章是很重要的東西。"
20052-CVGroup_UIEventLobby_Idle2-2 = "因為它是能以最低限度的投入，引出最大限度輸出的──"
20052-CVGroup_UIEventLobby_Idle2-3 = "蘊藏著「可能性」的商品啊……！"
20052-CVGroup_UIEventLobby_Idle3-1 = "從零開始創造某樣事物，是件很了不起的事。"
20052-CVGroup_UIEventLobby_Idle3-2 = "將其化為可能的才能也是如此。"
20052-CVGroup_UIEventLobby_Idle3-3 = "……"
20052-CVGroup_UIEventLobby_Idle3-4 = "真不錯呢，那種才能。"
20052-CVGroup_UIEventLobby_Idle3-5 = "我打從心底……這麼認為哦。"
20052-CVGroup_UIEventLobby_Idle4-1 = "對於三一的各位學生們，我抱持著由衷的感謝哦？"
20052-CVGroup_UIEventLobby_Idle4-2 = "……請別用那種眼神看我嘛。"
20052-CVGroup_UIEventLobby_Idle4-3 = "我是真～的，打從心底這麼想的呀。"
20052-CVGroup_UIEventShop_Enter1-1 = "您覺得事業的基礎是什麼呢？\n物品……？交換……？"
20052-CVGroup_UIEventShop_Enter1-2 = "當然，是錢對吧！"
20052-CVGroup_UIEventShop_Enter2-1 = "您來得正好！"
20052-CVGroup_UIEventShop_Enter2-2 = "歡迎來到資金與商品流通的事業現場！"
20052-CVGroup_UIEventShop_Enter2-3 = "呣呵呵，那麼，還請慢慢挑選。"
20052-CVGroup_UIEventShop_Enter3-1 = "有時架子的深處也會沉睡著寶物。"
20052-CVGroup_UIEventShop_Enter3-2 = "還請務必仔～細看到最後唷，老師。"
20052-CVGroup_UIEventShop_Enter3-3 = "啊啊，當然要仔細看我也沒關係哦？"
20052-CVGroup_UIEventShop_Idle1-1 = "就算找我搭話，也絕對不會變便宜的哦？"
20052-CVGroup_UIEventShop_Idle1-2 = "在一項折扣決定之前，背後可是有數不清的交涉和……"
20052-CVGroup_UIEventShop_Idle1-3 = "……政治性的交易在進行呢。"
20052-CVGroup_UIEventShop_Idle2-1 = "我還真沒想像過呢，居然有一天會和老師您做生意。"
20052-CVGroup_UIEventShop_Idle2-2 = "哎呀～活久了什麼都能見到呢～"
20052-CVGroup_UIEventShop_Buy1-1 = "哦哦！眼光真不錯呢，老師！"
20052-CVGroup_UIEventShop_Buy1-2 = "那麼這件商品，可以的話要不要也考慮一下呀？"
20052-CVGroup_UIEventShop_Buy2-1 = "偷偷跟您說……"
20052-CVGroup_UIEventShop_Buy2-2 = "我在親眼確認成果物的瞬間……是最興奮的唷……！"
20052-CVGroup_UIEventShop_Buy3-1 = "知道嗎？老師。文化就是金錢。"
20052-CVGroup_UIEventShop_Buy3-2 = "也就是說，購買這個行為──"
20052-CVGroup_UIEventShop_Buy3-3 = "也能稱的上是一種文化活動。"
20052-CVGroup_UIEventShop_Buy4-1 = "品質我可以保證哦？"
