[translation]
23004-CVGroup_UITitle_Idle1-1 = "블루 아카이브."
23004-CVGroup_CharacterGet_Idle1-1 = "소녀를 아름답게 하는 것은 화장이 아니라 열정이지"
23004-CVGroup_Cafe_Idle1-1 = "…가짜 선생님 로봇을 만들면… 재벌이 될 수 있을지도."
23004-CVGroup_Cafe_Idle2-1 = "그러고 보니 헬기 정비도 슬슬 해야겠군."
23004-CVGroup_Cafe_Idle3-1 = "흐음… 전투 기능을 갖춘 비데는 어떨까."
23004-CVGroup_Cafe_Idle4-1 = "어째서 아무도 광학미채 속옷을 필요로 하지 않는 걸까… 자신작이었는데…."
23004-CVGroup_Cafe_Idle5-1 = "흐음…… 뭔가 수리가 필요한 거, 없으려나."
23004-CVGroup_WeaponGet_Idle1-1 = "내 손끝에서 이루어지는 기적. 설계와 제작.\n선생님. 앞으로의 나를 기대해줘."
