[translation]
23006-CVGroup_UITitle_Idle1-1 = "蔚藍檔案！"
23006-CVGroup_CharacterGet_Idle1-1 = "耶嘿嘿，我是節慶營運管理部的靜子～\n 之後請多指教囉，老師？咦？\n……啊啊，沒錯沒錯你說的對，這是營業用的台詞！"
23006-CVGroup_Cafe_Idle1-1 = "萌耶萌耶啾～\n…這樣對嗎？"
23006-CVGroup_Cafe_Idle2-1 = "為了下一個慶典，\n得徹底計畫一下才行。"
23006-CVGroup_Cafe_Idle3-1 = "百夜堂的新餐點，\n要推出什麼呢……？"
23006-CVGroup_Cafe_Idle4-1 = "在下次的慶典上做點大膽的嘗試…\n所有人穿成和服風的兔女郎…之類的？"
23006-CVGroup_Cafe_Idle5-1 = "這裡，很適合當作百夜堂的臨時店面呢！"
23006-CVGroup_WeaponGet_Idle1-1 = "這是無論在什麼慶典上都找不到的非賣品呢。\n耶嘿嘿，我會好好珍惜的。老師！"
23006-CVGroup_UIEventShop_Enter1-1 = "這裡是百夜堂的攤位！\n來吧主人，需要什麼東西呢？"
23006-CVGroup_UIEventShop_Enter2-1 = "啊，老師！歡迎光臨～"
23006-CVGroup_UIEventShop_Enter2-2 = "來來，請盡情參觀吧！"
23006-CVGroup_UIEventShop_Enter3-1 = "慶典雖然結束了，不過我們還沒打烊！"
23006-CVGroup_UIEventShop_Enter3-2 = "有句話說剩下的東西有福氣，來吧老師，請！"
23006-CVGroup_UIEventShop_Idle1-1 = "就算是慶典，不，正因為是慶典，百夜堂是不會停下腳步的！"
23006-CVGroup_UIEventShop_Idle1-2 = "……嘛，畢竟我們同時也是節慶營運管理部，這是理所當然的，耶嘿。"
23006-CVGroup_UIEventShop_Idle2-1 = "好，這種時候就……萌耶萌耶～啾♪"
23006-CVGroup_UIEventShop_Idle2-2 = "……咦？這個有點老套？是嗎！？"
23006-CVGroup_UIEventShop_Buy1-1 = "啊，那個……！沒，沒什麼沒什麼，\n請收下請收下。我也沒有想說要把剩下的都買下來…！"
23006-CVGroup_UIEventShop_Buy2-1 = "居然選了那個，不愧是老師！\n眼光果然厲害！"
23006-CVGroup_UIEventShop_Buy3-1 = "謝謝惠顧，主人♪"
23006-CVGroup_UIEventShop_Buy4-1 = "啊，果然會覺得那是好東西對吧？耶嘿嘿。"
