[translation]
23000-CVGroup_UITitle_Idle1-1 = "蔚藍檔案～"
23000-CVGroup_CharacterGet_Idle1-1 = "真高興能見到你，老師～\n老師喜歡哪種冰淇淋呢？"
23000-CVGroup_Cafe_Idle1-1 = "嗯～\n要吃什麼呢…"
23000-CVGroup_Cafe_Idle2-1 = "今天果然也要草莓＆薄荷～"
23000-CVGroup_Cafe_Idle3-1 = "冰～冰～冰淇淋～"
23000-CVGroup_Cafe_Idle4-1 = "放學後當然要吃甜點！"
23000-CVGroup_Cafe_Idle5-1 = "草莓和薄荷最棒了！"
23000-CVGroup_WeaponGet_Idle1-1 = "這個武器是……謝謝你，老師。\n雖然變強這件事讓我有點害怕……\n但是和老師一起的話，就沒問題了！"
23000-CVGroup_UIEventMission_Enter1-1 = "為了美味的甜點～今天也一起加油吧！"
23000-CVGroup_UIEventMission_Enter2-1 = "今天也會努力的！"
23000-CVGroup_UIEventMission_Idle1-1 = "耶嘿嘿，再多依賴我也沒關係唷～"
23000-CVGroup_UIEventMission_Idle2-1 = "耶嘿嘿，有點害羞呢，老師。"
23000-CVGroup_UIEventMission_Buy1-1 = "謝謝你，老師！"
23000-CVGroup_UIEventMission_Buy2-1 = "大家，加油喔！"
23000-CVGroup_UIEventMission_Interaction1-1 = "一直以來都很謝謝你～\n老師。耶嘿嘿。"
