[translation]
26001-CVGroup_UITitle_Idle1-1 = "Blue, Archive."
26001-CVGroup_CharacterGet_Idle1-1 = "Otose Kotama from Millennium Science School. I find you very intriguing."
26001-CVGroup_Cafe_Idle1-1 = "There's a wiretapping device in this cafe... Hmm, I see..."
26001-CVGroup_Cafe_Idle2-1 = "The signal is unstable."
26001-CVGroup_Cafe_Idle3-1 = "How odd. Sensei's GPS signal was detected nearby..."
26001-CVGroup_Cafe_Idle4-1 = "Look at the cafe's new dessert. Uploading to my blog now..."
26001-CVGroup_Cafe_Idle5-1 = "New Momo Friends merchandise. The time of reckoning...has arrived."
26001-CVGroup_WeaponGet_Idle1-1 = "Adjusting the hertz... Can you hear me?"
