[translation]
26005-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
26005-CVGroup_CharacterGet_Idle1-1 = "อย่าดูถูกว่าฉันตัวเล็กนะ! ถึงจะเล็กก็เล็กพริกขี้หนูแล้วกัน!"
26005-CVGroup_Cafe_Idle1-1 = "ฉันยังโตได้กว่านี้อีก... เชื่อกันบ้างสิ! ฮึ่ม!"
26005-CVGroup_Cafe_Idle2-1 = "ฮิฮิ นอนสักงีบแล้วค่อยไปต่อดีมั้ย?"
26005-CVGroup_Cafe_Idle3-1 = "(เฮ้อ... ทำไมคุณครูถึงไม่มีเซนส์เอาซะเลย)"
26005-CVGroup_Cafe_Idle4-1 = "อยากกินของหวานอร่อยๆ! อ๊ะ! นั่นคุณครูนี่นา!"
26005-CVGroup_Cafe_Idle5-1 = "ฮือ ฉันไม่ชอบนมจืด ยิ่งรู้ว่าต้องกินนมให้มากๆ ก็ยิ่งไม่ชอบ!\nหืม? นะ.. นมสตรอว์เบอร์รี่เหรอ?"
26005-CVGroup_WeaponGet_Idle1-1 = "ถ้ารับของแบบนี้มาละก็ คงจะต้อง...\nพยายามอย่างสุดขั้วไปเลยสินะ!"
