[translation]
26001-CVGroup_UITitle_Idle1-1 = "Blue Archive"
26001-CVGroup_CharacterGet_Idle1-1 = "โอโทเซะ โคทามะ จากโรงเรียนมิลเลเนียมค่ะ\nฉันได้ยินเสียงของคุณครู เลยมาที่นี่ค่ะ"
26001-CVGroup_Cafe_Idle1-1 = "ที่คาเฟ่นี้...มีอุปกรณ์ดักฟัง...\nอืม แบบนี้นี่เอง"
26001-CVGroup_Cafe_Idle2-1 = "การส่งสัญญาณไม่เสถียรเลยค่ะ"
26001-CVGroup_Cafe_Idle3-1 = "แปลกจังเลย\nเพิ่งตรวจเจอสัญญาณ GPS คุณครูที่ใกล้ๆ นี้เอง..."
26001-CVGroup_Cafe_Idle4-1 = "ดูขนมออกใหม่ของคาเฟ่...\nอัปโหลดขึ้นบล็อกส่วนตัว..."
26001-CVGroup_Cafe_Idle5-1 = "สินค้าใหม่ล่าสุดของ MOMO FRIENDS มา...แล้ว...สินะ..."
26001-CVGroup_WeaponGet_Idle1-1 = "กำลังปรับคลื่นความถี่... ได้ยินรึเปล่าคะ?"
