[translation]
26006-CVGroup_UITitle_Idle1-1 = "Blue, Archive!"
26006-CVGroup_CharacterGet_Idle1-1 = "Are you the one that I've been watching through my telescope? Ooh, I'm so excited!"
26006-CVGroup_Cafe_Idle1-1 = "Heehee. I found some cool furniture!"
26006-CVGroup_Cafe_Idle2-1 = "I wonder what's beyond..."
26006-CVGroup_Cafe_Idle3-1 = "If I don't escape from the Spec Ops..."
26006-CVGroup_Cafe_Idle4-1 = "The view here is spectacular!"
26006-CVGroup_Cafe_Idle5-1 = "I wonder where Sensei is...?"
26006-CVGroup_WeaponGet_Idle1-1 = "Thank you, Sensei! I'll treat it as preciously as this telescope!"
26006-CVGroup_UIEventShop_Enter1-1 = "Oh, Sensei? Did you bring something to eat?"
26006-CVGroup_UIEventShop_Enter2-1 = "Thank you so much for the supplies!"
26006-CVGroup_UIEventShop_Enter2-2 = "We'll find some way to repay you!"
26006-CVGroup_UIEventShop_Enter3-1 = "The festival is already halfway over."
26006-CVGroup_UIEventShop_Enter3-2 = "Well, we don't have anything to do with it anyways..."
26006-CVGroup_UIEventShop_Enter4-1 = "Looks like Ivan Kupala will be over soon too."
26006-CVGroup_UIEventShop_Enter4-2 = "If you find anything else that might be delicious or useful..."
26006-CVGroup_UIEventShop_Enter4-3 = "Please bring it to us!"
26006-CVGroup_UIEventShop_Enter5-1 = "It's the last day of the festival, Sensei. Anything you're forgetting?"
26006-CVGroup_UIEventShop_Enter6-1 = "The festival is over, but we still need all the supplies we can get!"
26006-CVGroup_UIEventShop_Idle1-1 = "Spec Ops No. 227 is always low on sweets..."
26006-CVGroup_UIEventShop_Idle2-1 = "When do you think we can return to the main institute...?"
26006-CVGroup_UIEventShop_Buy1-1 = "Wow! That looks so tasty!"
26006-CVGroup_UIEventShop_Buy2-1 = "Can we really eat it?"
