[translation]
26002-CVGroup_UITitle_Idle1-1 = "블루 아카이브~"
26002-CVGroup_CharacterGet_Idle1-1 = "게헨나 급양부의 주리라고 해요.\n배가 고프면 제게 꼭 말씀해 주셔야 해요?"
26002-CVGroup_Cafe_Idle1-1 = "음~ 달콤한 냄새…"
26002-CVGroup_Cafe_Idle2-1 = "이것도 먹을 수 있는 걸까요?"
26002-CVGroup_Cafe_Idle3-1 = "일단 한 번 튀겨볼까…"
26002-CVGroup_Cafe_Idle4-1 = "어머나. 정말 좋은 곳이네요."
26002-CVGroup_Cafe_Idle5-1 = "여기선 좋은 요리를 할 수 있을 거 같아요."
26002-CVGroup_WeaponGet_Idle1-1 = "후후, 이 총을 요리에 쓰면 고기의 식감이 훨씬 부드러워지네요!"
