[translation]
26007-CVGroup_UITitle_Idle1-1 = "Blue Archive!"
26007-CVGroup_CharacterGet_Idle1-1 = "I-I'm Okusora Ayane. H-How do I look? I feel kind of embarrassed."
26007-CVGroup_Cafe_Idle1-1 = "Wearing this makes me feel a little shy..."
26007-CVGroup_Cafe_Idle2-1 = "I wonder where everyone is...?"
26007-CVGroup_Cafe_Idle3-1 = "Let's see where I can relax..."
26007-CVGroup_Cafe_Idle4-1 = "Hmm? What's that...?"
26007-CVGroup_Cafe_Idle5-1 = "I feel good for some reason."
26007-CVGroup_WeaponGet_Idle1-1 = "Something so great, for me... I'm always receiving things from you. I'll do my very best to pay you back for everything!"
26007-CVGroup_UIEventLobby_Enter1-1 = "Welcome, Sensei. I'll prepare everything!"
26007-CVGroup_UIEventLobby_Enter2-1 = "I've been waiting for you, Sensei! Let's work hard together!"
26007-CVGroup_UIEventLobby_Idle1-1 = "Sensei...? What's going on...?"
26007-CVGroup_UIEventLobby_Idle2-1 = "Wh-What's wrong? Is there a bug somewhere?"
26007-CVGroup_UIEventLobby_Idle3-1 = "Hmm... Sensei, did you call me?"
26007-CVGroup_UIEventLobby_Idle4-1 = "S-Sorry. But when you look at me like that, I get embarrassed..."
26007-CVGroup_UIEventLobby_Enter3-1 = "Come on! Let's do our best!"
26007-CVGroup_UIEventLobby_Enter4-1 = "I think we just need to push a little harder. Let's do this, Sensei!"
26007-CVGroup_UIEventLobby_Enter5-1 = "Cleanup is also important. I'll help you!"
26007-CVGroup_UIEventMission_Enter1-1 = "I've put together a task list!"
26007-CVGroup_UIEventMission_Enter2-1 = "That's it for the task list."
26007-CVGroup_UIEventMission_Idle1-1 = "It's enjoyable to achieve your goals one by one."
26007-CVGroup_UIEventMission_Idle2-1 = "It's enjoyable just organizing lists with you for some reason."
26007-CVGroup_UIEventMission_Buy1-1 = "Yes, thank you for your hard work!"
26007-CVGroup_UIEventMission_Buy2-1 = "I knew I could count on you!"
26007-CVGroup_UIEventMission_Interaction1-1 = "All of today's goals have been completed! Thank you!"
