[translation]
10001-CVGroup_Battle_Buffed_1-1 = "ได้รับการสนับสนุนเพียงพอแล้ว"
10001-CVGroup_Battle_Defense_1-1 = "ไม่มีประโยชน์"
10001-CVGroup_Battle_In_1-1 = "เริ่มต่อสู้"
10001-CVGroup_Battle_In_2-1 = "จะบุกล่ะนะ... "
10001-CVGroup_Battle_Move_1-1 = "เท่านี้ก็... ปิดจ๊อบ?"
10001-CVGroup_Battle_Move_2-1 = "ศัตรูรายต่อไปอยู่ไหนกันนะ?"
10001-CVGroup_Battle_Recovery_1-1 = "โอ้... ขอบคุณนะ"
10001-CVGroup_Battle_TacticalAction_1-1 = "ไปแล้วนะ"
10001-CVGroup_Battle_Victory_1-1 = "คำนวณผลลัพธ์ได้รึยัง?"
10001-CVGroup_Battle_Victory_2-1 = "นี่เป็นชัยชนะของพวกเราละ"
10001-CVGroup_CommonSkill-1 = "เจอศัตรูแล้ว"
10001-CVGroup_ExSkill_1-1 = "เปิดใช้งานตัวแปลคำสั่ง เริ่มการวิเคราะห์"
10001-CVGroup_ExSkill_2-1 = "วิเคราะห์รหัสใหม่... ใช้งานเรียบร้อย"
10001-CVGroup_ExSkill_3-1 = "กำลังวิเคราะห์รูปแบบ "
10001-CVGroup_ExSkill_Level_1-1 = "เปลี่ยนเป็นโหมดป้องกัน"
10001-CVGroup_ExSkill_Level_2-1 = "ชินกับความเจ็บปวดแล้วละ"
10001-CVGroup_ExSkill_Level_3-1 = "ใช้งานสำเร็จ ตอนนี้ไม่เป็นไรแล้วละ"
10001-CVGroup_Formation_In_1-1 = "ภารกิจใหม่เหรอ?"
10001-CVGroup_Formation_In_2-1 = "ดีละ ให้เป็นหน้าที่ฉันเอง"
10001-CVGroup_Formation_Select-1 = "อืม..."
10001-CVGroup_Growup_1-1 = "ต้องใช้มันในการต่อสู้ใช่มั้ย?"
10001-CVGroup_Growup_2-1 = "บอกฉันหน่อยสิ"
10001-CVGroup_Growup_3-1 = "ฉันควรฝึกอะไรเพิ่มดีนะ"
10001-CVGroup_Growup_4-1 = "กำลังพัฒนาอยู่ละ"
10001-CVGroup_Relationship_Up_1-1 = "ถ้าเป็นคุณครูละก็ คงจะคอยช่วยระวังหลังให้ฉันได้แน่ๆ"
10001-CVGroup_Relationship_Up_2-1 = "สนใจปืนของฉันเหรอ?"
10001-CVGroup_Relationship_Up_3-1 = "ฉันชอบสิ่งที่คุณครูพูด เพราะมันเข้าใจง่ายดีน่ะ"
10001-CVGroup_Relationship_Up_4-1 = "การปกป้องคุณครูคือหน้าที่ของฉันนี่นา"
10001-CVGroup_Tactic_In_1-1 = "ถึงตาฉันออกโรงแล้วเหรอ"
10001-CVGroup_Tactic_In_2-1 = "แค่ปราบให้หมดก็พอใช่มั้ย?"
10001-CVGroup_Tactic_Victory_1-1 = "เป็นคำสั่งที่มีประสิทธิภาพมากเลยนะ คุณครู"
10001-CVGroup_Tactic_Victory_2-1 = "ปฏิบัติการเสร็จสิ้นแล้ว มีคำสั่งอื่นอีกรึเปล่า?"
