[translation]
10007-CVGroup_Battle_Buffed_1-1 = "It's my turn now!"
10007-CVGroup_Battle_Defense_1-1 = "Heehee! It's no use!"
10007-CVGroup_Battle_In_1-1 = "Time to show off my talent!"
10007-CVGroup_Battle_In_2-1 = "I'm making the world a happier place!"
10007-CVGroup_Battle_Move_1-1 = "Quick! We've got to tag something with our next graffiti masterpiece!"
10007-CVGroup_Battle_Move_2-1 = "Okay, advance! Advance!"
10007-CVGroup_Battle_Recovery_1-1 = "Ohh, I'll put this to good use!"
10007-CVGroup_Battle_TacticalAction_1-1 = "Formation change!"
10007-CVGroup_Battle_Victory_1-1 = "Amazing results! What do you think, Sensei?"
10007-CVGroup_Battle_Victory_2-1 = "Heehee! Nothing can stop an artist's soul."
10007-CVGroup_CommonSkill-1 = "Explode!"
10007-CVGroup_ExSkill_1-1 = "As expected, today was perfect!"
10007-CVGroup_ExSkill_2-1 = "Heehee! Another masterpiece!"
10007-CVGroup_ExSkill_3-1 = "Yes. Yes, I like that!"
10007-CVGroup_ExSkill_Level_1-1 = "Take this!"
10007-CVGroup_ExSkill_Level_2-1 = "It's a gift for you all!"
10007-CVGroup_ExSkill_Level_3-1 = "Ahahaha!"
10007-CVGroup_Formation_In_1-1 = "What's up? Is something fun happening?"
10007-CVGroup_Formation_In_2-1 = "Heehee, leave it to me."
10007-CVGroup_Formation_Select-1 = "Huh, wasn't it my turn?"
10007-CVGroup_Growup_1-1 = "Inspiration has struck!"
10007-CVGroup_Growup_2-1 = "Okay, great!"
10007-CVGroup_Growup_3-1 = "Will this also help increase my scores?"
10007-CVGroup_Growup_4-1 = "Ooh, I feel incredibly strong!"
10007-CVGroup_Relationship_Up_1-1 = "Ahaha. Thank you for always helping, Sensei."
10007-CVGroup_Relationship_Up_2-1 = "I want to try drawing your face at least once, Sensei."
10007-CVGroup_Relationship_Up_3-1 = "I-I-I wasn't looking at a picture of you or anything, Sensei!"
10007-CVGroup_Relationship_Up_4-1 = "When I'm with you, Sensei, inspiration strikes me all the time."
10007-CVGroup_Tactic_In_1-1 = "If I win, let's tag this cover with cool graffiti!"
10007-CVGroup_Tactic_In_2-1 = "Today's graffiti is... Yes, \"Veritas\" is perfect!"
10007-CVGroup_Tactic_Victory_1-1 = "We won! We won!"
10007-CVGroup_Tactic_Victory_2-1 = "Looks like I accomplished something today too!"
