[translation]
10000-CVGroup_Battle_Buffed_1-1 = "นี่แหละอำนาจ!"
10000-CVGroup_Battle_Covered_1-1 = "ยืนยันตำแหน่งโจมตี"
10000-CVGroup_Battle_Defense_1-1 = "ฮุฮุฮุ น่าเสียดายนะ"
10000-CVGroup_Battle_In_1-1 = "เอาละ ทุกคน ได้เวลาทำงานแล้ว"
10000-CVGroup_Battle_In_2-1 = "เริ่มภารกิจได้!"
10000-CVGroup_Battle_Move_1-1 = "นี่ เห็นรึเปล่า? ฉันทำภารกิจได้อย่างดีเลยนะ"
10000-CVGroup_Battle_Move_2-1 = "เอ้า จะลุยแล้วนะ"
10000-CVGroup_Battle_Recovery_1-1 = "ฮุฮุ การต้อนรับระดับ VIP งั้นเหรอ"
10000-CVGroup_Battle_TacticalAction_1-1 = "จะลุยแล้วนะ"
10000-CVGroup_Battle_Victory_1-1 = "ถ้าไว้วางใจให้ทางหน่วยรับจ้างสารพัดจัดการ\nจะสมบูรณ์แบบอย่างแน่นอน"
10000-CVGroup_Battle_Victory_2-1 = "ฮุฮุ! ภารกิจเสร็จเรียบร้อย!"
10000-CVGroup_CommonSkill-1 = "เตรียมตัวไว้ได้เลย"
10000-CVGroup_ExSkill_1-1 = "หืม~ เจอเป้าหมายแล้ว"
10000-CVGroup_ExSkill_2-1 = "ยิงเข้าเป้าด้วยวมือเดียวได้สบายๆ"
10000-CVGroup_ExSkill_3-1 = "แค่นี้ก็เพียงพอแล้วละ"
10000-CVGroup_ExSkill_Level_1-1 = "ปิดฉากกันได้แล้ว"
10000-CVGroup_ExSkill_Level_2-1 = "ฮ่าฮ่าฮ่า! เข้าเป้า!"
10000-CVGroup_ExSkill_Level_3-1 = "เป็นไง สุดยอดเลยใช่มั้ยล่ะ?"
10000-CVGroup_Formation_In_1-1 = "ฮุฮุฮุ เลือกได้ดีเลยนี่"
10000-CVGroup_Formation_In_2-1 = "ให้เป็นหน้าที่ของฉันเอง!"
10000-CVGroup_Formation_Select-1 = "ฮุฮุ ถ้าต้องการ ฉันจะช่วยเอง"
10000-CVGroup_Growup_1-1 = "สมกับที่เป็นฉันจริงๆ"
10000-CVGroup_Growup_2-1 = "ฮุฮุฮุ คอยดูฉันให้ดีๆ ล่ะ!"
10000-CVGroup_Growup_3-1 = "คอยดูตัวตนที่แท้จริงของฉันให้ดีล่ะ!"
10000-CVGroup_Growup_4-1 = "ฮุฮุฮุฮุ... แข็งแกร่งขึ้นอีกแล้วสินะ"
10000-CVGroup_Relationship_Up_1-1 = "ฮุฮุ คุณครูโชคดีมากนะ\nเห็นแบบนี้ ฉันก็เป็นคนใหญ่คนโตเหมือนกันนะ!"
10000-CVGroup_Relationship_Up_2-1 = "การได้ใกล้ชิดกับลูกค้าแบบนี้...\nปะ... เปล่านะ! คุณครูเป็นลูกค้าประจำนี่ ไม่เป็นไรหรอก!"
10000-CVGroup_Relationship_Up_3-1 = "ถ้าเป็นคำขอจากคุณครูละก็... \nไม่ว่าจะเป็นเรื่องอะไร... ฉะ...ฉันจะทำให้ทุกอย่างเลย!"
10000-CVGroup_Relationship_Up_4-1 = "ขอบคุณนะคุณครู\nฉันกลายเป็นคนที่ยอดเยี่ยมแบบนี้ได้เพราะคุณครูเลย"
10000-CVGroup_Tactic_In_1-1 = "สิ่งที่ฉันเชี่ยวชาญคือการทำธุรกิจและการนำกองกำลัง"
10000-CVGroup_Tactic_In_2-1 = "ผู้นำ! เป็นตำแหน่งที่เหมาะสำหรับคนที่เป็นประธานอย่างฉันจริงๆ!"
10000-CVGroup_Tactic_Victory_1-1 = "ฮุฮุ แค่นี้ง่ายจะตายไป"
10000-CVGroup_Tactic_Victory_2-1 = "เป็นไง! คุณครู? ความแตกต่างมันเป็นแบบนี้แหละ"
