[translation]
10010-CVGroup_Battle_Buffed_1-1 = "嗯，謝謝。"
10010-CVGroup_Battle_Covered_1-1 = "掩蔽物，確保。"
10010-CVGroup_Battle_Defense_1-1 = "……沒用的。"
10010-CVGroup_Battle_In_1-1 = "用隊形B上吧。"
10010-CVGroup_Battle_In_2-1 = "維持住陣形前進。"
10010-CVGroup_Battle_Move_1-1 = "記得這附近應該有銀行……"
10010-CVGroup_Battle_Move_2-1 = "是個騎行的好地方呢。"
10010-CVGroup_Battle_Recovery_1-1 = "嗯，謝謝。"
10010-CVGroup_Battle_TacticalAction_1-1 = "移動吧。"
10010-CVGroup_Battle_Victory_1-1 = "是戰術的勝利。"
10010-CVGroup_Battle_Victory_2-1 = "Clear。"
10010-CVGroup_CommonSkill-1 = "要上囉……！"
10010-CVGroup_ExSkill_1-1 = "……狀態良好。\n要上囉。"
10010-CVGroup_ExSkill_2-1 = "……單元啟動。"
10010-CVGroup_ExSkill_3-1 = "無人機開始運作。"
10010-CVGroup_ExSkill_Level_1-1 = "開始火力支援。"
10010-CVGroup_ExSkill_Level_2-1 = "目標，設定完畢。"
10010-CVGroup_ExSkill_Level_3-1 = "支援攻擊。"
10010-CVGroup_Formation_In_1-1 = "準備好了唷。"
10010-CVGroup_Formation_In_2-1 = "OK。我參戰。"
10010-CVGroup_Formation_Select-1 = "唔嗯……"
10010-CVGroup_Growup_1-1 = "能感受到訓練的成果。"
10010-CVGroup_Growup_2-1 = "謝謝你，老師。"
10010-CVGroup_Growup_3-1 = "好像成長了。\n這也是老師的功勞。"
10010-CVGroup_Growup_4-1 = "能知道自己正在成長。"
10010-CVGroup_Relationship_Up_1-1 = "真奇怪。悸動的感覺停不下來。"
10010-CVGroup_Relationship_Up_2-1 = "只要跟老師待在一起……就莫名有種不可思議的感覺。"
10010-CVGroup_Relationship_Up_3-1 = "老師，告訴我吧。\n我所不知道的、各式各樣的事，再告訴我更多……"
10010-CVGroup_Relationship_Up_4-1 = "從見到老師的那個瞬間開始……\n這裡對我來說就成為了更加特別的地方。"
10010-CVGroup_Tactic_In_1-1 = "發現敵人。請下指示！"
10010-CVGroup_Tactic_In_2-1 = "老師，請下達出擊命令！"
10010-CVGroup_Tactic_Victory_1-1 = "有備無患。這是很單純的道理。"
10010-CVGroup_Tactic_Victory_2-1 = "是場精采的指揮，老師。"
