[translation]
10016-CVGroup_Battle_Buffed_1-1 = "謝謝。"
10016-CVGroup_Battle_Covered_1-1 = "在這裡掩蔽。"
10016-CVGroup_Battle_Defense_1-1 = "都快擦到了……！"
10016-CVGroup_Battle_In_1-1 = "組隊遊玩的基本就是團隊合作。"
10016-CVGroup_Battle_In_2-1 = "唔嗯，這種事其實姐姐比較擅長的。"
10016-CVGroup_Battle_Move_1-1 = "前進～！"
10016-CVGroup_Battle_Move_2-1 = "想趕快回去玩遊戲……"
10016-CVGroup_Battle_Recovery_1-1 = "感謝支援。"
10016-CVGroup_Battle_TacticalAction_1-1 = "進行移動！"
10016-CVGroup_Battle_Victory_1-1 = "Clear。移動到下一個關卡吧。"
10016-CVGroup_Battle_Victory_2-1 = "是我們的勝利。"
10016-CVGroup_ExSkill_1-1 = "唉……輸了。\n真沒辦法！"
10016-CVGroup_ExSkill_2-1 = "有點……懊悔。\n那麼，來試試看吧。"
10016-CVGroup_ExSkill_3-1 = "呼……約定就是約定。"
10016-CVGroup_ExSkill_Level_1-1 = "雖然無冤無仇，還是做好覺悟吧。"
10016-CVGroup_ExSkill_Level_2-1 = "像點畫一樣縝密……"
10016-CVGroup_ExSkill_Level_3-1 = "連續射擊！開始！"
10016-CVGroup_Formation_In_1-1 = "明白了。我去吧。"
10016-CVGroup_Formation_In_2-1 = "啊，是。我會盡最大努力。"
10016-CVGroup_Formation_Select-1 = "唔嗯……咦？"
10016-CVGroup_Growup_1-1 = "想畫得更好，也想幫上老師更多的忙。"
10016-CVGroup_Growup_2-1 = "努力能獲得回報，真的是件開心的事。"
10016-CVGroup_Growup_3-1 = "我想變得更加成熟。\n那樣就能幫上大家跟老師……更多忙了才對。"
10016-CVGroup_Growup_4-1 = "謝謝你，老師。\n今後我也會……盡自己最大的努力。"
10016-CVGroup_Relationship_Up_1-1 = "老師總是很溫柔呢。"
10016-CVGroup_Relationship_Up_2-1 = "今後也跟遊戲開發部一起創造美好回憶吧。\n然後……跟我也……沒，沒什麼！"
10016-CVGroup_Relationship_Up_3-1 = "遊戲做好之後，我想最先給老師看。"
10016-CVGroup_Relationship_Up_4-1 = "偶爾……我會不想跟姐姐一起，而是由我一個人獨佔老師。\n那個……可，可以牽你的手嗎？"
10016-CVGroup_Tactic_In_1-1 = "既然接受就會認真完成。"
10016-CVGroup_Tactic_In_2-1 = "保持冷靜，向前邁進吧。"
10016-CVGroup_Tactic_Victory_1-1 = "大家都辛苦了！"
10016-CVGroup_Tactic_Victory_2-1 = "Clear，相當精采。"
10016-CVGroup_CommonSkill-1 = "我來幫忙！"
