[translation]
10027-CVGroup_Battle_Buffed_1-1 = "ขอบคุณสำหรับเจ้านี่นะ...!"
10027-CVGroup_Battle_Covered_1-1 = "พบสิ่งกีดขวาง"
10027-CVGroup_Battle_Defense_1-1 = "ถ้ายิงไม่โดนก็ไร้ความหมาย"
10027-CVGroup_Battle_In_1-1 = "นอกจากการยิงสนับสนุน ฉันก็ไม่ค่อยคุ้นกับการเป็นแนวหน้าเท่าไร\nแต่ก็ไม่เป็นไร... ให้เป็นหน้าที่ฉันเอง"
10027-CVGroup_Battle_In_2-1 = "ฉันจะพิสูจน์ให้เห็นว่าการยิงสนับสนุน ไม่ใช่สิ่งเดียวที่ฉันทำได้\nคอยดูให้ดีล่ะ คุณครู"
10027-CVGroup_Battle_Move_1-1 = "เริ่มเคลื่อนย้ายได้ ขอคำสั่งด้วย คุณครู"
10027-CVGroup_Battle_Move_2-1 = "เคลื่อนย้ายไปพื้นที่ต่อไปกันเลย"
10027-CVGroup_Battle_Recovery_1-1 = "ขอบคุณที่สนับสนุนค่ะ"
10027-CVGroup_Battle_TacticalAction_1-1 = "ไปสถานที่ต่อไป"
10027-CVGroup_Battle_Victory_1-1 = "ภารกิจสำเร็จ ขอบคุณที่เหนื่อยนะ\nการสั่งการของคุณครูก็สมบูรณ์แบบ"
10027-CVGroup_Battle_Victory_2-1 = "ภารกิจเสร็จสิ้น... ทั้งหมดเป็นเพราะการสั่งการของคุณครูเลยนะ"
10027-CVGroup_CommonSkill-1 = "ลุยกันเลย!"
10027-CVGroup_ExSkill_1-1 = "จุดที่น่าสงสัยเป็นพิเศษ...\n...! เจอเป้าหมายแล้ว!"
10027-CVGroup_ExSkill_2-1 = "สำหรับตอนนี้...\nอื้ม...! เจอตัวแล้ว!"
10027-CVGroup_ExSkill_3-1 = "เป้าหมาย... เจอแล้ว!"
10027-CVGroup_ExSkill_Level_1-1 = "ไม่ปล่อยให้หนีไปหรอก!"
10027-CVGroup_ExSkill_Level_2-1 = "ย้าก!"
10027-CVGroup_ExSkill_Level_3-1 = "ยิงงงง!"
10027-CVGroup_Formation_In_1-1 = "อื้อ ฉันคิดว่าเลือกได้ดีมากเลยละ"
10027-CVGroup_Formation_In_2-1 = "จะไม่ทำให้ผิดหวังเลย"
10027-CVGroup_Formation_Select-1 = "อย่างนี้นี่เอง..."
10027-CVGroup_Growup_1-1 = "ขอบคุณนะคุณครู\nฉันจะไม่ทำให้คุณครูเสียใจที่เลือกแบบนี้"
10027-CVGroup_Growup_2-1 = "จะตอบแทนความคาดหวังด้วยผลลัพธ์ให้ดู"
10027-CVGroup_Growup_3-1 = "ยอดเยี่ยมมาก...\nถ้ามีสิ่งนี้ ฉันจะสู้ต่อได้แน่"
10027-CVGroup_Growup_4-1 = "ฉันมักได้รับความช่วยเหลือจากคุณครูเสมอเลยนะ\nบุญคุณในครั้งนี้ ฉันจะตอบแทนในสักวัน..."
10027-CVGroup_Relationship_Up_1-1 = "ความรู้สึกนี้...\nปะ... เปล่า... ไม่มีอะไรหรอก"
10027-CVGroup_Relationship_Up_2-1 = "ฉันรู้สึกขอบคุณคุณครูอยู่เสมอเลยนะ\nฉันพูดจริงนะ ไม่ได้พูดเล่นเลย"
10027-CVGroup_Relationship_Up_3-1 = "ฉันไม่ค่อยชินกับการแสดงออกด้วยคำพูดสักเท่าไร...\nแต่สิ่งที่ฉันพูดกับคุณครูก็มาจากใจจริงทั้งหมดนะ"
10027-CVGroup_Relationship_Up_4-1 = "ฉันอยากตอบแทนคุณครู...\nแต่สำหรับฉันในตอนนี้ สิ่งเดียวที่ทำได้คือทำภารกิจให้สำเร็จ..."
10027-CVGroup_Tactic_In_1-1 = "งั้นก็เริ่มกันเลยดีกว่า"
10027-CVGroup_Tactic_In_2-1 = "ไม่มีปัญหา ไปกันเถอะ"
10027-CVGroup_Tactic_Victory_1-1 = "ไม่ใช่เรื่องน่าตกใจอะไรสักหน่อย ผลมันก็แน่นอนอยู่แล้ว"
10027-CVGroup_Tactic_Victory_2-1 = "ขอบคุณนะ คุณครู\nเป็นการสั่งการที่ยอดเยี่ยมมาก"
