[translation]
10027-CVGroup_Battle_Buffed_1-1 = "고맙다, 이것으로……!"
10027-CVGroup_Battle_Covered_1-1 = "엄폐물 발견."
10027-CVGroup_Battle_Defense_1-1 = "맞지 않으면, 의미는 없어."
10027-CVGroup_Battle_In_1-1 = "화력지원이 아니라, 전선에 서는 것은 조금 익숙하지 않지만.\n……괜찮아. 맡겨만 줘."
10027-CVGroup_Battle_In_2-1 = "화력지원만이 능사가 아니라는 걸, 증명하겠다. 지켜보고 있어. 선생님."
10027-CVGroup_Battle_Move_1-1 = "이동을 개시한다. 선생님, 지시를."
10027-CVGroup_Battle_Move_2-1 = "다음 구역으로 이동한다."
10027-CVGroup_Battle_Recovery_1-1 = "지원에 감사한다."
10027-CVGroup_Battle_TacticalAction_1-1 = "다음 장소로."
10027-CVGroup_Battle_Victory_1-1 = "작전 성공, 수고했다. 선생님의 지휘도 완벽했다."
10027-CVGroup_Battle_Victory_2-1 = "미션 컴플리트, 이것도 선생님의 지휘 덕분이야."
10027-CVGroup_CommonSkill-1 = "간다!"
10027-CVGroup_ExSkill_1-1 = "특별히 수상한 점은……. ……! 목표 발견!"
10027-CVGroup_ExSkill_2-1 = "지금으로서는……. ……아니! 발견했다!"
10027-CVGroup_ExSkill_3-1 = "목표는…… 찾았다!"
10027-CVGroup_ExSkill_Level_1-1 = "놓치지 않는다!"
10027-CVGroup_ExSkill_Level_2-1 = "하압!"
10027-CVGroup_ExSkill_Level_3-1 = "파이어!"
10027-CVGroup_Formation_In_1-1 = "응, 탁월한 선택이라 생각한다."
10027-CVGroup_Formation_In_2-1 = "후회시키지는 않아."
10027-CVGroup_Formation_Select-1 = "과연……."
10027-CVGroup_Growup_1-1 = "고마워, 선생님. 이 선택, 후회하게 만들지 않을 테니까."
10027-CVGroup_Growup_2-1 = "기대에는, 결과로 보답하겠다."
10027-CVGroup_Growup_3-1 = "훌륭해……. 이걸로, 좀 더 싸울 수 있겠어."
10027-CVGroup_Growup_4-1 = "선생님에겐, 항상 이렇게 도움을 받기만 하는군.\n이 은혜는, 어떤 형태로든 반드시……"
10027-CVGroup_Relationship_Up_1-1 = "이 기분은……. 아, 아니…… 아무것도 아니야."
10027-CVGroup_Relationship_Up_2-1 = "선생님에겐, 언제나 감사하고 있어. 정말이다. 빈말이 아니야."
10027-CVGroup_Relationship_Up_3-1 = "나는, 말로 표현하는 것엔 익숙하지 않지만…….\n그래도 이렇게 선생님에게 하는 말은, 전부 진심이다."
10027-CVGroup_Relationship_Up_4-1 = "뭔가 보답하고 싶지만…….\n지금의 내겐, 우선 작전을 성공시키는 것밖에……."
10027-CVGroup_Tactic_In_1-1 = "작전을 시작하지."
10027-CVGroup_Tactic_In_2-1 = "문제없다. 가자."
10027-CVGroup_Tactic_Victory_1-1 = "놀랄만한 일이 아니야. 당연한 결과다."
10027-CVGroup_Tactic_Victory_2-1 = "수고했다. 선생님. 훌륭한 지휘였다."
