[translation]
10036-CVGroup_Battle_Buffed_1-1 = "很有幫助，非常感謝……！"
10036-CVGroup_Battle_Covered_1-1 = "噫呀！？請，請放棄吧……！"
10036-CVGroup_Battle_Defense_1-1 = "沒，沒用的！"
10036-CVGroup_Battle_In_1-1 = "那個，那個……！"
10036-CVGroup_Battle_In_2-1 = "我，我會努力的！"
10036-CVGroup_Battle_Move_1-1 = "還，還要繼續嗎……！？"
10036-CVGroup_Battle_Move_2-1 = "什，什麼時候才會結束呢……？"
10036-CVGroup_Battle_Recovery_1-1 = "非，非常感謝……！"
10036-CVGroup_Battle_TacticalAction_1-1 = "呀！"
10036-CVGroup_Battle_Victory_1-1 = "成，成功了……我辦到了！"
10036-CVGroup_Battle_Victory_2-1 = "我，我難道，做得挺好的嗎……！？"
10036-CVGroup_CommonSkill-1 = "嗚嗚……！"
10036-CVGroup_ExSkill_1-1 = "結果變成這樣了呢……"
10036-CVGroup_ExSkill_2-1 = "別無他法……"
10036-CVGroup_ExSkill_3-1 = "要恨的話，就請恨我吧……"
10036-CVGroup_ExSkill_Level_1-1 = "對，對不起……！"
10036-CVGroup_ExSkill_Level_2-1 = "不好意思……！"
10036-CVGroup_ExSkill_Level_3-1 = "可，可能會痛……！"
10036-CVGroup_Formation_In_1-1 = "咦，我，我嗎……！？"
10036-CVGroup_Formation_In_2-1 = "那個……我真的，能派上用場嗎……？"
10036-CVGroup_Formation_Select-1 = "緊，緊張起來了……！"
10036-CVGroup_Growup_1-1 = "好，好像湧出了力量……！"
10036-CVGroup_Growup_2-1 = "現，現在的話，感覺什麼都能做到……！"
10036-CVGroup_Growup_3-1 = "這樣一來，就能更好地……！"
10036-CVGroup_Growup_4-1 = "謝，謝謝您！老師……！"
10036-CVGroup_Relationship_Up_1-1 = "非，非常感謝……！"
10036-CVGroup_Relationship_Up_2-1 = "呀啊哇！？\n原，原來是老師啊……嚇我一跳，啊哈哈……"
10036-CVGroup_Relationship_Up_3-1 = "這份恩情，日後必定會報答……！"
10036-CVGroup_Relationship_Up_4-1 = "有朝一日，當我也能對老師有所回報時……"
10036-CVGroup_Tactic_In_1-1 = "肯，肯定會有辦法的……！\n對吧……？"
10036-CVGroup_Tactic_In_2-1 = "嗚嗚，開始緊張了……"
10036-CVGroup_Tactic_Victory_1-1 = "呼……太好了……"
10036-CVGroup_Tactic_Victory_2-1 = "這都多虧了老師。\n非常感謝……！"
