[translation]
10030-CVGroup_Battle_Buffed_1-1 = "ฉันจะตอบแทนความคาดหวังให้ได้ค่ะ"
10030-CVGroup_Battle_Covered_1-1 = "กำบังตัวแล้วค่ะ"
10030-CVGroup_Battle_Defense_1-1 = "ไม่มีประโยชน์หรอกค่ะ!"
10030-CVGroup_Battle_In_1-1 = "แม้จะต้องอยู่แนวหน้า สิ่งที่ต้องทำก็ไม่เปลี่ยนแปลงค่ะ"
10030-CVGroup_Battle_In_2-1 = "การได้มาสนับสนุนในตำแหน่งนี้ มันรู้สึกแปลกๆ นิดหน่อยค่ะ"
10030-CVGroup_Battle_Move_1-1 = "ไปกันเถอะค่ะ"
10030-CVGroup_Battle_Move_2-1 = "รุดไปข้างหน้าด้วยความไม่ประมาทนะคะ"
10030-CVGroup_Battle_Recovery_1-1 = "ขอบคุณสำหรับการสนับสนุนค่ะ"
10030-CVGroup_Battle_TacticalAction_1-1 = "จะไปเดี๋ยวนี้ค่ะ"
10030-CVGroup_Battle_Victory_1-1 = "ขอบคุณทุกคนมากค่ะ"
10030-CVGroup_Battle_Victory_2-1 = "ไปต่อกันทั้งอย่างนี้เลยค่ะ"
10030-CVGroup_CommonSkill-1 = "สัญญาณชีพไม่มีปัญหาค่ะ! ลุยต่อได้เลยค่ะ!"
10030-CVGroup_ExSkill_1-1 = "จริงๆ เลยเชียว..."
10030-CVGroup_ExSkill_2-1 = "เจอตัวแล้วค่ะ..."
10030-CVGroup_ExSkill_3-1 = "เฮ้อ..."
10030-CVGroup_ExSkill_Level_1-1 = "ช่วยไม่ได้นะคะ"
10030-CVGroup_ExSkill_Level_2-1 = "ไปกันเลยค่ะ"
10030-CVGroup_ExSkill_Level_3-1 = "ให้เป็นหน้าที่ของฉันเองค่ะ"
10030-CVGroup_Formation_In_1-1 = "ถ้าเพื่อคุณครูแล้วละก็ ฉันจะคอยสนับสนุนตลอดเลยค่ะ"
10030-CVGroup_Formation_In_2-1 = "ค่ะ ไว้ใจฉันได้เลยค่ะ คุณครู"
10030-CVGroup_Formation_Select-1 = "อะ... อืม คือว่า...?"
10030-CVGroup_Growup_1-1 = "ขอบคุณเสมอๆ เลยนะคะคุณครู"
10030-CVGroup_Growup_2-1 = "ฉันจะตอบสนองความคาดหวังของคุณครูให้ได้ค่ะ"
10030-CVGroup_Growup_3-1 = "ดีใจจังเลย... แต่ฉันเริ่มคุมสติไม่ได้แล้ว..."
10030-CVGroup_Growup_4-1 = "ทำไมถึงทำกับฉันแบบนี้ล่ะคะ...?"
10030-CVGroup_Relationship_Up_1-1 = "ถ้าเปลี่ยนชุดจะส่งผลต่ออารมณ์ด้วยรึเปล่าคะ\nรู้สึกลำบากใจจังเลยค่ะ..."
10030-CVGroup_Relationship_Up_2-1 = "ขอพักผ่อนแบบนี้ต่อ... อีกสักหน่อยได้รึเปล่าคะ?"
10030-CVGroup_Relationship_Up_3-1 = "ฉันรู้ว่าไม่ควรขี้เกียจมากไปกว่านี้\nแต่พออยู่กับคุณครู ฉันก็เผลอไปโดยไม่รู้ตัว..."
10030-CVGroup_Relationship_Up_4-1 = "คุณครูได้พักผ่อนเพียงพอรึเปล่าคะ?\nพักสักหน่อยคงไม่เป็นไรหรอกค่ะ มาพักผ่อนด้วยกันมั้ยคะ?"
10030-CVGroup_Tactic_In_1-1 = "จะเริ่มแล้วนะคะ"
10030-CVGroup_Tactic_In_2-1 = "ไม่ต้องกังวลหรอกค่ะ มีฉันอยู่ด้วยทั้งคนนี่คะ"
10030-CVGroup_Tactic_Victory_1-1 = "นี่เป็นผลจากการเตรียมตัวที่รัดกุมค่ะ"
10030-CVGroup_Tactic_Victory_2-1 = "ต้องขอบคุณการสั่งการของคุณครูเลยนะคะ ขอบคุณค่ะ"
