[translation]
10034-CVGroup_Battle_Buffed_1-1 = "Heehee. Thank you."
10034-CVGroup_Battle_Covered_1-1 = "It's safe here."
10034-CVGroup_Battle_Defense_1-1 = "*sigh* Somehow, it worked out!"
10034-CVGroup_Battle_In_1-1 = "I will lead, for now at least."
10034-CVGroup_Battle_In_2-1 = "It's also the duty of a wife to eliminate any threats before they can even manifest. Now, shall we begin?"
10034-CVGroup_Battle_Move_1-1 = "Everyone all right? Good, then let's keep going."
10034-CVGroup_Battle_Move_2-1 = "It's all right. I can still fight...!"
10034-CVGroup_Battle_Recovery_1-1 = "Ah, thank you."
10034-CVGroup_Battle_TacticalAction_1-1 = "Moving out."
10034-CVGroup_Battle_Victory_1-1 = "How is it, Sensei? I tried my best."
10034-CVGroup_Battle_Victory_2-1 = "Heehee, Sensei. Will you praise me?"
10034-CVGroup_CommonSkill-1 = "I've prepared a bento!"
10034-CVGroup_ExSkill_1-1 = "Now, everyone, please gather here!"
10034-CVGroup_ExSkill_2-1 = "Shall we rest?"
10034-CVGroup_ExSkill_3-1 = "Oh right! I've prepared something..."
10034-CVGroup_ExSkill_Level_1-1 = "Heehee. Is everyone here now?"
10034-CVGroup_ExSkill_Level_2-1 = "I've prepared quite a bit!"
10034-CVGroup_ExSkill_Level_3-1 = "Everyone, eat well, and let's give it our all!"
10034-CVGroup_Formation_In_1-1 = "Me...? Yes, if that's what you want, of course."
10034-CVGroup_Formation_In_2-1 = "Yes, I'll help you. Just leave it to me."
10034-CVGroup_Formation_Select-1 = "Heehee, Sensei. Is there something I can do?"
10034-CVGroup_Growup_1-1 = "Ah, I see... So this kind of training also exists."
10034-CVGroup_Growup_2-1 = "Fighting isn't my forte, but I still want to become stronger for you, Sensei."
10034-CVGroup_Growup_3-1 = "Even though I'm still weak... No, it's because I'm still weak that I can become even stronger in the future."
10034-CVGroup_Growup_4-1 = "The path of training is still rough... But I'll continue onward. For me, and for you."
10034-CVGroup_Relationship_Up_1-1 = "Our bond... It's getting deeper, Sensei."
10034-CVGroup_Relationship_Up_2-1 = "With this, I can be even closer to you... Ah, no. Nevermind..."
10034-CVGroup_Relationship_Up_3-1 = "This emotion that burns in my chest... I don't know how to describe it. But I can say...I'm grateful Sensei is by my side."
10034-CVGroup_Relationship_Up_4-1 = "I didn't think you'd treat me as so precious... Thank you, Sensei. ...Could I hold your hand, for just a while?"
10034-CVGroup_Tactic_In_1-1 = "I'll show you the results of my training."
10034-CVGroup_Tactic_In_2-1 = "I will do my best to be of help to you, Sensei."
10034-CVGroup_Tactic_Victory_1-1 = "I'm really happy I could do something for you, Sensei."
10034-CVGroup_Tactic_Victory_2-1 = "Was I helpful? Heehee, I'm glad if that's the case."
