[translation]
10046-CVGroup_Battle_Buffed_1-1 = "วิถีนินจาอิซุนะ วิชาการขอบคุณ! ฉบับฤดูร้อน!"
10046-CVGroup_Battle_Covered_1-1 = "วิถีนินจา! วิชาการอำพรางตัว!"
10046-CVGroup_Battle_Defense_1-1 = "ไม่มีประโยชน์หรอกค่ะ!"
10046-CVGroup_Battle_In_1-1 = "อิซุนะจะนำทางให้เองค่ะ!"
10046-CVGroup_Battle_In_2-1 = "ว่องไวดุจนินจา! จะเริ่มภารกิจแล้วนะคะ!"
10046-CVGroup_Battle_Move_1-1 = "ไปที่ต่อไปกันเลยค่ะ! นายท่าน!"
10046-CVGroup_Battle_Move_2-1 = "จะไปแล้วนะคะ ย้าา!"
10046-CVGroup_Battle_Recovery_1-1 = "อ๊ะ! ขอบคุณค่ะ!"
10046-CVGroup_Battle_TacticalAction_1-1 = "ฟึ่บฟึ่บฟึ่บ"
10046-CVGroup_Battle_Victory_1-1 = "ชนะแล้วค่ะ! นายท่าน! ชัยชนะของพวกอิซุนะละค่ะ!"
10046-CVGroup_Battle_Victory_2-1 = "ฮิฮิฮิ! เป็นยังไงบ้างคะ นายท่าน!\nอิซุนะพยายามสุดๆ เลยนะคะ!"
10046-CVGroup_CommonSkill-1 = "วิถีนินจา! วิชาฟองเดือดพล่าน!"
10046-CVGroup_ExSkill_1-1 = "ย้าาา! อิซุนะ! จะลุยแล้วนะคะ!"
10046-CVGroup_ExSkill_2-1 = "นี่คือวิถีนินจาอิซุนะ!"
10046-CVGroup_ExSkill_3-1 = "วิถีนินจา! วิชานินจาวอลเลย์บอลชายหาด!"
10046-CVGroup_ExSkill_Level_1-1 = "ลูกตบพลังเดือด-!"
10046-CVGroup_ExSkill_Level_2-1 = "นี่คือพลังทั้งหมดของอิซุนะค่ะ!"
10046-CVGroup_ExSkill_Level_3-1 = "ฉันจะให้นายท่านได้เห็นอิซุนะในฤดูร้อนเองค่ะ!"
10046-CVGroup_Formation_In_1-1 = "ค่ะ! นายท่าน! อิซุนะจะลุยแล้วนะคะ!"
10046-CVGroup_Formation_In_2-1 = "ถึงตาอิซุนะแล้วสินะคะ!"
10046-CVGroup_Formation_Select-1 = "ในฤดูร้อนนี้ ไม่ว่าเรื่องไหนก็สั่งอิซุนะมาได้เลยค่ะ! นายท่าน! นินนิน!"
10046-CVGroup_Growup_1-1 = "สิ่งนี้... มอบให้อิซุนะเหรอคะ...?\nขอบคุณค่ะ นายท่าน!"
10046-CVGroup_Growup_2-1 = "อิซุนะพัฒนาขึ้นแล้วละค่ะ!\nเพราะงั้น... ไปเที่ยวกันเถอะค่ะ! นายท่าน!"
10046-CVGroup_Growup_3-1 = "เท่านี้ก็อดทนต่อความร้อนในฤดูร้อนได้แล้ว...?!\nเพราะงั้นนายท่าน... ไปเล่นกันเถอะค่ะ!"
10046-CVGroup_Growup_4-1 = "อิซุนะแข็งแกร่งขึ้นได้แบบนี้เพราะนายท่านเลยค่ะ\nอิซุนะจะพยายามต่อไปเพื่อนายท่านค่ะ!"
10046-CVGroup_Relationship_Up_1-1 = "ได้ใช้เวลาในฤดูร้อนกับนายท่านแบบนี้ด้วย\nอิซุนะ! มีความสุขมากๆ เลยค่ะ!"
10046-CVGroup_Relationship_Up_2-1 = "นายท่าน! นายท่าน! นาย~ท่าน~!\nฮิฮิฮิ! ไม่รู้ทำไม แค่เรียกนายท่านแบบนี้ก็มีความสุขแล้วค่ะ!"
10046-CVGroup_Relationship_Up_3-1 = "มีเรื่องอะไรงั้นเหรอคะ...?\nอ๊ะ เปล่าค่ะ ตอนนี้อากาศดีมากก็จริง แต่ถ้าเพื่อการคุ้มกันนายท่านแล้ว\nถึงร้อนแค่ไหนก็ไม่หวั่นหรอกค่ะ!"
10046-CVGroup_Relationship_Up_4-1 = "(พอเห็นนายท่านแบบนี้... ทำไมรู้สึกหน้าร้อนๆ ก็ไม่รู้...\nเพราะอะไรกันนะ?)"
10046-CVGroup_Tactic_In_1-1 = "คอยดูฝีมือของอิซุนะด้วยนะคะ! นายท่าน!"
10046-CVGroup_Tactic_In_2-1 = "อิซุนะจะแสดงวิชานินจาอิซุนะที่ก้าวหน้าขึ้น\nให้นายท่านได้เห็นเพื่อต้อนรับฤดูร้อนในครั้งนี้ค่ะ!"
10046-CVGroup_Tactic_Victory_1-1 = "ภารกิจเสร็จเรียบร้อยแล้วค่ะ!\nไปเล่นที่ชายหาดกันเถอะค่ะ! นายท่าน!"
10046-CVGroup_Tactic_Victory_2-1 = "ไม่มีศัตรูคนไหนที่วิชานินจาอิซุนะเอาชนะไม่ได้หรอกค่ะ! คิดว่าอย่างนั้นนะคะ!"
