[translation]
10042-CVGroup_Battle_Buffed_1-1 = "已確認支援，謝謝。"
10042-CVGroup_Battle_Covered_1-1 = "正在掩蔽。"
10042-CVGroup_Battle_Defense_1-1 = "沒用的。"
10042-CVGroup_Battle_In_1-1 = "嗯。"
10042-CVGroup_Battle_In_2-1 = "出發吧。"
10042-CVGroup_Battle_Move_1-1 = "進行移動。"
10042-CVGroup_Battle_Move_2-1 = "前進。"
10042-CVGroup_Battle_Recovery_1-1 = "謝謝。"
10042-CVGroup_Battle_TacticalAction_1-1 = "我過去那邊哦。"
10042-CVGroup_Battle_Victory_1-1 = "嗯……！"
10042-CVGroup_Battle_Victory_2-1 = "贏了。"
10042-CVGroup_CommonSkill-1 = "……被盯上了？"
10042-CVGroup_ExSkill_1-1 = "這樣啊，原來如此……"
10042-CVGroup_ExSkill_2-1 = "這，是為了我……"
10042-CVGroup_ExSkill_3-1 = "變成這樣了啊……"
10042-CVGroup_ExSkill_Level_1-1 = "那麼……我就不客氣了。"
10042-CVGroup_ExSkill_Level_2-1 = "那就拜託了。"
10042-CVGroup_ExSkill_Level_3-1 = "如果這樣能幫上忙的話。"
10042-CVGroup_Formation_In_1-1 = "理解了。"
10042-CVGroup_Formation_In_2-1 = "確認完畢。"
10042-CVGroup_Formation_Select-1 = "嗯？"
10042-CVGroup_Growup_1-1 = "重視我的這份心意，我也會珍惜的。"
10042-CVGroup_Growup_2-1 = "我曾以為自己並沒有被如此對待的價值。"
10042-CVGroup_Growup_3-1 = "你教導我的事情，我一直都記得。"
10042-CVGroup_Growup_4-1 = "又學到了一課。"
10042-CVGroup_Relationship_Up_1-1 = "你願意，溫柔對待我啊。"
10042-CVGroup_Relationship_Up_2-1 = "像這樣獲得的一切，會有能報答的那天嗎？"
10042-CVGroup_Relationship_Up_3-1 = "像這樣，更加……啊，沒事。什麼都沒有。"
10042-CVGroup_Relationship_Up_4-1 = "都是多虧了老師唷。\n那個，嗯……各個方面都是。"
10042-CVGroup_Tactic_In_1-1 = "攻擊開始。"
10042-CVGroup_Tactic_In_2-1 = "作戰開始。"
10042-CVGroup_Tactic_Victory_1-1 = "嗯，勝利了。"
10042-CVGroup_Tactic_Victory_2-1 = "贏了呢。"
