[translation]
10040-CVGroup_Battle_Buffed_1-1 = "가, 감사드려요!"
10040-CVGroup_Battle_Covered_1-1 = "숨었, 어요! 괜찮아요. 진짜예요…!"
10040-CVGroup_Battle_Defense_1-1 = "안 통해, 요!"
10040-CVGroup_Battle_In_1-1 = "이, 인법연구부의 이름을 걸고……! 힘낼게요!"
10040-CVGroup_Battle_In_2-1 = "닌자로서의 임무인 거네요……!"
10040-CVGroup_Battle_Move_1-1 = "이동, 하겠습니다!"
10040-CVGroup_Battle_Move_2-1 = "닌자는, 엄청 빠르니까요!"
10040-CVGroup_Battle_Recovery_1-1 = "고맙, 습니다!"
10040-CVGroup_Battle_TacticalAction_1-1 = "샤샤샥……이에요!"
10040-CVGroup_Battle_Victory_1-1 = "네? 혹시 이겼나요……? 와앗……!"
10040-CVGroup_Battle_Victory_2-1 = "승리, 인 거죠……? 이것도, 닌자의 힘……?"
10040-CVGroup_CommonSkill-1 = "수리검, 아플 거예요……!"
10040-CVGroup_ExSkill_1-1 = "츠, 츠쿠요, 류, 이, 인법……! 아앗?!"
10040-CVGroup_ExSkill_2-1 = "지금의 제게, 가능한 것을……! 앗!"
10040-CVGroup_ExSkill_3-1 = "훌륭한 닌자가 되기 위해서라면…! 햐앗?!"
10040-CVGroup_ExSkill_Level_1-1 = "인법! 변장의 술이에요……!"
10040-CVGroup_ExSkill_Level_2-1 = "이건, 특기, 예요……!"
10040-CVGroup_ExSkill_Level_3-1 = "지금의 저는, 나무, 누가 보더라도 나무……!"
10040-CVGroup_Formation_In_1-1 = "저, 저 말인가요……? 그, 히, 힘내겠습니다……."
10040-CVGroup_Formation_In_2-1 = "여, 열심히 하겠습니다. 후, 훌륭한 닌자가 되기 위해!"
10040-CVGroup_Formation_Select-1 = "그, 너무, 빤히 쳐다보지 말아주셨으면……"
10040-CVGroup_Growup_1-1 = "아, 저를 위해서……. 그게, 힘내, 겠습니다."
10040-CVGroup_Growup_2-1 = "힘내겠습니다. 훌륭한 닌자가, 되고 싶으니까……!"
10040-CVGroup_Growup_3-1 = "선생님의 기대에, 보답할 수 있도록……!"
10040-CVGroup_Growup_4-1 = "언젠가, 한 사람 몫을 할 수 있게 되어서……!"
10040-CVGroup_Relationship_Up_1-1 = "이런 저라도……. 선생님을 위해, 힘내고 싶어요……."
10040-CVGroup_Relationship_Up_2-1 = "선생님이, 계셔주셔서…… 저는, 이렇게……."
10040-CVGroup_Relationship_Up_3-1 = "에엣, 저, 말인가요?! 커다래서, 우연히 눈에 들어왔다…같은 게, 아니라?"
10040-CVGroup_Relationship_Up_4-1 = "선생님, 감사, 합니다…… 이런 저, 이지만……. 그래도……."
10040-CVGroup_Tactic_In_1-1 = "여러분, 다치지 않도록, 열심히 해요……."
10040-CVGroup_Tactic_In_2-1 = "이런 저라도 괜찮다면…… 네…."
10040-CVGroup_Tactic_Victory_1-1 = "혹시, 이긴 건가요……? 다행, 이에요……"
10040-CVGroup_Tactic_Victory_2-1 = "이것이야말로 닌자의 힘, 이에요! 네……!"
