[translation]
10054-CVGroup_Battle_Buffed_1-1 = "為了不辜負應援，我會努力的！"
10054-CVGroup_Battle_Covered_1-1 = "唔……！？"
10054-CVGroup_Battle_Defense_1-1 = "沒，沒有效的唷……！"
10054-CVGroup_Battle_In_1-1 = "抱持著運動家精神上吧！"
10054-CVGroup_Battle_In_2-1 = "打起精神上吧！"
10054-CVGroup_Battle_Move_1-1 = "前，前往下一條跑道吧……！"
10054-CVGroup_Battle_Move_2-1 = "請跟我來……！"
10054-CVGroup_Battle_Recovery_1-1 = "非常感謝。相當令人振奮。"
10054-CVGroup_Battle_TacticalAction_1-1 = "嘿……咻！"
10054-CVGroup_Battle_Victory_1-1 = "呼……總算結束了呢。"
10054-CVGroup_Battle_Victory_2-1 = "怎，怎麼樣呢……還好嗎？"
10054-CVGroup_CommonSkill-1 = "預備……咚！"
10054-CVGroup_ExSkill_1-1 = "請，請等一下哦……！"
10054-CVGroup_ExSkill_2-1 = "請，請稍等一下……！"
10054-CVGroup_ExSkill_3-1 = "啊……哇，哇啊……"
10054-CVGroup_ExSkill_Level_1-1 = "馬上拿給你哦。"
10054-CVGroup_ExSkill_Level_2-1 = "是，是！在這邊！"
10054-CVGroup_ExSkill_Level_3-1 = "請小心不要弄掉了唷。"
10054-CVGroup_Formation_In_1-1 = "我，我會盡己所能……！"
10054-CVGroup_Formation_In_2-1 = "好像緊張起來了……"
10054-CVGroup_Formation_Select-1 = "是，是……！？有什麼事嗎！？"
10054-CVGroup_Growup_1-1 = "雖然並不是很擅長運動……\n我會試著多加把勁的。"
10054-CVGroup_Growup_2-1 = "要是平常就有在體育課多努力就好了……"
10054-CVGroup_Growup_3-1 = "謝謝您，老師。\n我，會加油的哦！"
10054-CVGroup_Growup_4-1 = "只要有老師的應援，\n就會覺得自己彷彿什麼都做得到。"
10054-CVGroup_Relationship_Up_1-1 = "如果可以的話……老師要不要也一起運動呢？"
10054-CVGroup_Relationship_Up_2-1 = "被如此期待還是第一次……\n讓我有點緊張……"
10054-CVGroup_Relationship_Up_3-1 = "請再稍微多關注我一點，老師。"
10054-CVGroup_Relationship_Up_4-1 = "無論何時，我都想向老師展現自己最真實的模樣。"
10054-CVGroup_Tactic_In_1-1 = "堂堂正正，出發……！"
10054-CVGroup_Tactic_In_2-1 = "大家，一起加油吧！"
10054-CVGroup_Tactic_Victory_1-1 = "辛苦了。\n成績相當出色。"
10054-CVGroup_Tactic_Victory_2-1 = "這都要感謝大家的努力。"
