[translation]
10056-CVGroup_Battle_Buffed_1-1 = "現在有精神了。非常感謝！"
10056-CVGroup_Battle_Covered_1-1 = "躲藏起來！"
10056-CVGroup_Battle_Defense_1-1 = "呀啊！差點就出事了……"
10056-CVGroup_Battle_In_1-1 = "大家，出發囉！"
10056-CVGroup_Battle_In_2-1 = "開始吧！"
10056-CVGroup_Battle_Move_1-1 = "接下來該往哪裡呢？"
10056-CVGroup_Battle_Move_2-1 = "馬上過去！"
10056-CVGroup_Battle_Recovery_1-1 = "非常感謝！"
10056-CVGroup_Battle_TacticalAction_1-1 = "進行移動。"
10056-CVGroup_Battle_Victory_1-1 = "贏了！那麼，去分送禮物吧！"
10056-CVGroup_Battle_Victory_2-1 = "各位都辛苦了。\n真是個美好的聖誕節呢！"
10056-CVGroup_CommonSkill-1 = "這是禮物！\n希望你會喜歡……"
10056-CVGroup_ExSkill_1-1 = "愛正在蔓延。"
10056-CVGroup_ExSkill_2-1 = "期盼希望能隨著這股聲音，與各位同在。"
10056-CVGroup_ExSkill_3-1 = "別擔心，會順利的。"
10056-CVGroup_ExSkill_Level_1-1 = "願你的每個日子都充滿幸福。"
10056-CVGroup_ExSkill_Level_2-1 = "救護騎士團與你同在！"
10056-CVGroup_ExSkill_Level_3-1 = "期盼那份痛苦能被撫去。"
10056-CVGroup_Formation_In_1-1 = "呵呵，總覺得很開心呢。"
10056-CVGroup_Formation_In_2-1 = "願祝福與你同在……"
10056-CVGroup_Formation_Select-1 = "聖誕快樂！"
10056-CVGroup_Growup_1-1 = "嘗試扮演聖誕老人……也是個不錯的經驗呢。"
10056-CVGroup_Growup_2-1 = "謝謝你，老師。\n我非常開心……總是充滿了感激。"
10056-CVGroup_Growup_3-1 = "我，有稍微更像聖誕老人了嗎？"
10056-CVGroup_Growup_4-1 = "反而是我得到了幸福呢。"
10056-CVGroup_Relationship_Up_1-1 = "希望對大家而言，都能是個幸福的聖誕節……"
10056-CVGroup_Relationship_Up_2-1 = "那個……只當專屬於某人的聖誕老人也是可以的嗎……\n沒，沒什麼！"
10056-CVGroup_Relationship_Up_3-1 = "從老師那邊獲得的禮物，讓我的心情非常滿足……"
10056-CVGroup_Relationship_Up_4-1 = "我一直都很感謝你……是的，打從心底。"
10056-CVGroup_Tactic_In_1-1 = "你願意相信我嗎？"
10056-CVGroup_Tactic_In_2-1 = "我會盡可能努力的。"
10056-CVGroup_Tactic_Victory_1-1 = "太好了！大家都沒事呢。"
10056-CVGroup_Tactic_Victory_2-1 = "我，有派上用場嗎？"
