[translation]
10052-CVGroup_Battle_Buffed_1-1 = "ขอบคุณสำหรับคำแนะนำที่ถูกต้องนะคะ"
10052-CVGroup_Battle_Covered_1-1 = "ซ่อนตัวแล้วค่ะ"
10052-CVGroup_Battle_Defense_1-1 = "ฮุฮุ ไม่ใช่ทางนั้นหรอกนะคะ"
10052-CVGroup_Battle_In_1-1 = "บางครั้งพวกเรามาผ่อนคลายร่างกายสักหน่อยดีมั้ยคะ"
10052-CVGroup_Battle_In_2-1 = "งั้นจะเริ่มปฏิบัติการเลยนะคะ"
10052-CVGroup_Battle_Move_1-1 = "วันนี้จัดการเท่านี้ก่อนมั้ยคะ"
10052-CVGroup_Battle_Move_2-1 = "ข้างหน้าจะมีตัวแปรอะไรรออยู่กันนะคะ?"
10052-CVGroup_Battle_Recovery_1-1 = "ขอบคุณสำหรับการสนับสนุนค่ะ"
10052-CVGroup_Battle_TacticalAction_1-1 = "จะไปแล้วนะคะ"
10052-CVGroup_Battle_Victory_1-1 = "ขอสิ้นสุดการประชุมเท่านี้ค่ะ\nทำได้ดีมากค่ะ"
10052-CVGroup_Battle_Victory_2-1 = "สมบูรณ์แบบตามที่บันทึกไว้♪"
10052-CVGroup_CommonSkill-1 = "จะเข้าปราบปรามอย่างรวดเร็วค่ะ"
10052-CVGroup_ExSkill_1-1 = "ที่แท้... ตรงนั้นก็คือจุดอ่อนนี่เองสินะคะ?"
10052-CVGroup_ExSkill_2-1 = "เอ๋... น่าสนใจดีนะคะ"
10052-CVGroup_ExSkill_3-1 = "ฮุฮุ... ครั้งนี้เราโจมตีที่นี่กันมั้ยคะ?"
10052-CVGroup_ExSkill_Level_1-1 = "ขอเวลาสักครู่นะคะ จะเริ่มการจดบันทึกแล้วค่ะ"
10052-CVGroup_ExSkill_Level_2-1 = "ถ้าความรู้ของฉันเป็นประโยชน์ก็โล่งอกไปทีค่ะ"
10052-CVGroup_ExSkill_Level_3-1 = "ถึงจะพยายามซ่อนตัวก็หนีจากการบันทึกของฉันไม่พ้นหรอกค่ะ!"
10052-CVGroup_Formation_In_1-1 = "เป็นตัวเลือกที่สมเหตุสมผลมากเลยค่ะ"
10052-CVGroup_Formation_In_2-1 = "ครั้งนี้ก็ขอรบกวนด้วยนะคะ"
10052-CVGroup_Formation_Select-1 = "ฮุฮุ ถ้ามีไอเดียดีๆ ก็ขอรบกวนด้วยนะคะ"
10052-CVGroup_Growup_1-1 = "การเรียนรู้สิ่งใหม่ๆ เป็นเรื่องน่าสนุกเสมอๆ เลยค่ะ"
10052-CVGroup_Growup_2-1 = "ฮุฮุ เรื่องนี้คงสนุกไม่น้อยเลย..."
10052-CVGroup_Growup_3-1 = "สิ่งที่คุณครูสอนเข้าใจได้ง่ายมากเลยค่ะ"
10052-CVGroup_Growup_4-1 = "ฉันก็ยังฟันธงไม่ได้เหมือนกันค่ะ...\nแต่ฉันอาจจะเติบโตขึ้นจากเดิมนิดหน่อยก็ได้นะคะ ฮุฮุ"
10052-CVGroup_Relationship_Up_1-1 = "ฮุฮุ คำพูดของคุณครูเหมือนแสงแดดยามเย็นเลยนะคะ"
10052-CVGroup_Relationship_Up_2-1 = "ขอบคุณที่ช่วยฉันเสมอๆ นะคะ คุณครู"
10052-CVGroup_Relationship_Up_3-1 = "ยากที่จะจดบันทึกไว้นะคะ...\nแค่พูดว่ารู้สึกดีก็อาจยังไม่เพียงพอก็ได้"
10052-CVGroup_Relationship_Up_4-1 = "ความรู้สึกในตอนนี้... ฉันไม่อยากบันทึกเอาไว้น่ะค่ะ"
10052-CVGroup_Tactic_In_1-1 = "ยืนยันการปรากฏตัวของศัตรู\nรบกวนสั่งการด้วยค่ะ"
10052-CVGroup_Tactic_In_2-1 = "ฮุฮุ เรื่องหน้างานให้เป็นหน้าที่ฉันเองค่ะ"
10052-CVGroup_Tactic_Victory_1-1 = "โชคดีที่บันทึกภาพลักษณ์ใหม่ๆ ของคุณครูไว้...\nฮึ่ม... ขอโทษด้วยนะคะ ฉันได้เรียนรู้อะไรหลายๆ อย่างเลยค่ะ"
10052-CVGroup_Tactic_Victory_2-1 = "สั่งการได้ยอดเยี่ยมมากค่ะ\nหลังจากนี้ไปดื่มกาแฟสักแก้วกันมั้ยคะ?"
