[translation]
10050-CVGroup_Battle_Buffed_1-1 = "감사합니다!"
10050-CVGroup_Battle_Covered_1-1 = "숨을 거에요!"
10050-CVGroup_Battle_Defense_1-1 = "그게 전력인가요? 미숙하네요!"
10050-CVGroup_Battle_In_1-1 = "활기차게 가 볼까요!"
10050-CVGroup_Battle_In_2-1 = "저를 따라오세요!"
10050-CVGroup_Battle_Move_1-1 = "다음 지역으로 가 보죠!"
10050-CVGroup_Battle_Move_2-1 = "이 앞에는, 무엇이 있을까요?"
10050-CVGroup_Battle_Recovery_1-1 = "고마워요!"
10050-CVGroup_Battle_TacticalAction_1-1 = "이동하죠!"
10050-CVGroup_Battle_Victory_1-1 = "좋은 느낌이네요. 다음에도 잘 부탁드려요!"
10050-CVGroup_Battle_Victory_2-1 = "흐흥, 당연하죠! 이래 봬도 어엿한 교관이니까요!"
10050-CVGroup_CommonSkill-1 = "사탕이라면 많이 있다구요?"
10050-CVGroup_ExSkill_1-1 = "자, 채점할게요~!"
10050-CVGroup_ExSkill_2-1 = "오늘의 점수는~?"
10050-CVGroup_ExSkill_3-1 = "시험지 돌려드릴게요~!"
10050-CVGroup_ExSkill_Level_1-1 = "참 잘했어요!"
10050-CVGroup_ExSkill_Level_2-1 = "백 점, 만 점, 참 잘했어요!"
10050-CVGroup_ExSkill_Level_3-1 = "다음에도 이렇게!"
10050-CVGroup_Formation_In_1-1 = "나쁘지 않은 선택이네요!"
10050-CVGroup_Formation_In_2-1 = "이 코코나에게 맡겨주세요!"
10050-CVGroup_Formation_Select-1 = "……무슨 일이라도 있나요?"
10050-CVGroup_Growup_1-1 = "저는 이미 다 컸지만, 동시에 아직 성장기에요."
10050-CVGroup_Growup_2-1 = "조금은, 슌 언니처럼 됐을까요……?"
10050-CVGroup_Growup_3-1 = "저기, 그……. 고맙습니다. 선생님."
10050-CVGroup_Growup_4-1 = "인생은 배움의 연속……. 이라고 들은 적이 있어요!"
10050-CVGroup_Relationship_Up_1-1 = "저, 저는 어린애가 아니에요! 몇 번이나 말씀드렸잖아요……."
10050-CVGroup_Relationship_Up_2-1 = "저도 언젠가 선생님처럼……. 아, 아뇨! 아무 것도 아니에요!"
10050-CVGroup_Relationship_Up_3-1 = "신기해요. 선생님과 있으면……. 어쩐지 가슴이 따끈따끈해서……."
10050-CVGroup_Relationship_Up_4-1 = "저는 교관이지만……. 교관에게도 선생님은 필요한 거예요."
10050-CVGroup_Tactic_In_1-1 = "자아, 수업 시간이에요!"
10050-CVGroup_Tactic_In_2-1 = "교관으로서의 진수를 보여드리죠!"
10050-CVGroup_Tactic_Victory_1-1 = "흥흥~ 이 정도는 아무것도 아니라구요."
10050-CVGroup_Tactic_Victory_2-1 = "저는 이제 어엿한 어른이라구요!"
