[translation]
10067-CVGroup_Battle_Buffed_1-1 = "지원, 감사합니다."
10067-CVGroup_Battle_Covered_1-1 = "얍. 숨었습니다."
10067-CVGroup_Battle_Defense_1-1 = "거기입니까."
10067-CVGroup_Battle_In_1-1 = "콜사인 바니 제로포, 가도록 하죠."
10067-CVGroup_Battle_In_2-1 = "잠입을 시작합니다."
10067-CVGroup_Battle_Move_1-1 = "가죠. 고- 고-"
10067-CVGroup_Battle_Move_2-1 = "다음 타겟으로 이동합니다."
10067-CVGroup_Battle_Recovery_1-1 = "도움을 받았습니다."
10067-CVGroup_Battle_TacticalAction_1-1 = "이동하겠습니다. 뿅뿅."
10067-CVGroup_Battle_Victory_1-1 = "이번 미션도 성공적이었군요. 뿅뿅."
10067-CVGroup_Battle_Victory_2-1 = "뿅. 저는 최고의 에이전트니까요."
10067-CVGroup_CommonSkill-1 = "이런 건 어떨까요?"
10067-CVGroup_ExSkill_1-1 = "암 기어, 장착."
10067-CVGroup_ExSkill_2-1 = "대응하겠습니다."
10067-CVGroup_ExSkill_3-1 = "타깃, 포착."
10067-CVGroup_ExSkill_Level_1-1 = "파이어!"
10067-CVGroup_ExSkill_Level_2-1 = "풀 버스트……!"
10067-CVGroup_ExSkill_Level_3-1 = "전력으로 대응합니다."
10067-CVGroup_Formation_In_1-1 = "오늘의 임무는 무엇입니까?"
10067-CVGroup_Formation_In_2-1 = "알겠습니다. 준비하도록 하죠."
10067-CVGroup_Formation_Select-1 = "선생님, 명령을. 저는 무적의 바니걸이니까요."
10067-CVGroup_Growup_1-1 = "최고의 바니 에이전트가 되는 그날까지, 계속 정진하겠습니다."
10067-CVGroup_Growup_2-1 = "선생님의 호위는 제 몫입니다. 이것만은 양보할 수 없습니다."
10067-CVGroup_Growup_3-1 = "이 토끼 귀에게 부끄럽지 않도록, 최선을 다하겠습니다.\n네? 그건 아니라구요...?"
10067-CVGroup_Growup_4-1 = "잠입, 액션, 호위, 진입, 메이드, 바니걸.\n무엇이든지 지시해 주십시오."
10067-CVGroup_Relationship_Up_1-1 = "선생님은 제게 할애하는 시간을 늘려주셔야합니다.\n적어도 제가 선생님을 생각하는 시간만큼은."
10067-CVGroup_Relationship_Up_2-1 = "선생님과 함께 있으면 마음이 편안해집니다.\n심지어 깜빡 잠이 들 정도로요."
10067-CVGroup_Relationship_Up_3-1 = "언제든지 저를 의지해 주세요. 선생님이 원한다면, 얼마든지.\n...후후, 이런 대사, 한번쯤은 해보고 싶었어요."
10067-CVGroup_Relationship_Up_4-1 = "저에게는 선생님이 필요합니다. \n선생님한테 제가 필요하듯이.\n부끄러운 대사 금지, 라구요? 후후, 일부러 말했어요."
10067-CVGroup_Tactic_In_1-1 = "걱정하실 필요 없습니다. 바니니까요."
10067-CVGroup_Tactic_In_2-1 = "저한테 맡겨 주세요."
10067-CVGroup_Tactic_Victory_1-1 = "승리로군요. 이예-이."
10067-CVGroup_Tactic_Victory_2-1 = "당연한 결과입니다. 얏호-"
