[translation]
10068-CVGroup_Battle_Buffed_1-1 = "ขะ... ขอบคุณมากค่ะ..."
10068-CVGroup_Battle_Defense_1-1 = "ไม่มีประโยชน์หรอกค่ะ!"
10068-CVGroup_Battle_In_1-1 = "โอ้! ฉันเป็นกองหน้าเหรอคะ?"
10068-CVGroup_Battle_In_2-1 = "ไม่ต้องกลัว บุกไปข้างหน้าเลย!"
10068-CVGroup_Battle_Move_1-1 = "ยังต้องไปอีกไกลค่ะ!"
10068-CVGroup_Battle_Move_2-1 = "ไปต่อกันเลยค่ะ!"
10068-CVGroup_Battle_Recovery_1-1 = "เฮือก ขะ... ขอบคุณค่ะ...!?"
10068-CVGroup_Battle_TacticalAction_1-1 = "ฮึก-!!"
10068-CVGroup_Battle_Victory_1-1 = "อื้ม! ผลลัพธ์มันก็แน่นอนอยู่แล้วค่ะ!"
10068-CVGroup_Battle_Victory_2-1 = "ต่อไปค่ะ ต่อไป!"
10068-CVGroup_CommonSkill-1 = "ท่าไม้ตาย! ท่าโพสแห่งชัยชนะ!"
10068-CVGroup_ExSkill_1-1 = "ฮึดช่าาา-!!"
10068-CVGroup_ExSkill_2-1 = "ปรากฏตัวแล้ว!!"
10068-CVGroup_ExSkill_3-1 = "มาวัดดวงกันเลยค่ะ!!"
10068-CVGroup_ExSkill_Level_1-1 = "ฉันไม่ปล่อยให้หลุดมือหรอกค่ะ!"
10068-CVGroup_ExSkill_Level_2-1 = "รับหนังสือคำท้าไปได้เลยค่ะ!"
10068-CVGroup_ExSkill_Level_3-1 = "เตรียมตัวให้ดีนะคะ!!"
10068-CVGroup_Formation_In_1-1 = "ในที่สุดก็ถึงตาฉันออกโรงแล้วสินะคะ!"
10068-CVGroup_Formation_In_2-1 = "ค่ะ! ฉันพร้อมลุยเสมอเลยค่ะ!"
10068-CVGroup_Formation_Select-1 = "ให้เป็นหน้าที่ของอุซาวะ เรอิสะได้เลยค่ะ!"
10068-CVGroup_Growup_1-1 = "สะ... สิ่งนี้? ให้ฉัน... เหรอคะ?"
10068-CVGroup_Growup_2-1 = "ขอบคุณค่ะคุณครู! ฉันจะพยายามให้มากขึ้นค่ะ!"
10068-CVGroup_Growup_3-1 = "การเติบโตของอุซาวะ เรอิสะ ไม่มีที่สิ้นสุดค่ะ!"
10068-CVGroup_Growup_4-1 = "การเติบโตมาพร้อมกับความรับผิดชอบ! ฉันจะทำให้เต็มที่ค่ะ!"
10068-CVGroup_Relationship_Up_1-1 = "ถ้าคุณครูโอเคละก็...\nคือ... ฉันอยากคุ้มกันคุณครูต่ออีกสักหน่อยค่ะ...!"
10068-CVGroup_Relationship_Up_2-1 = "ฉันเผยให้คุณครูเห็นอะไรหลายๆ อย่างเกินไปแล้ว\nแต่ก็คงไม่เป็นไรหรอกค่ะ! เพราะเป็นคุณครูนี่นา!"
10068-CVGroup_Relationship_Up_3-1 = "สิ่งที่ทำให้ฉันมาถึงตรงนี้ได้ ทุกอย่างต้องขอบคุณคุณครูเลยนะคะ"
10068-CVGroup_Relationship_Up_4-1 = "ขอบคุณที่ดูแลมาจนถึงตอนนี้ จากนี้ไปก็ขอรบกวนด้วยนะคะ!"
10068-CVGroup_Tactic_In_1-1 = "ถ้าต้องการพลังของฉันละก็ ได้เสมอ!"
10068-CVGroup_Tactic_In_2-1 = "ทุกคนมาลุยไปพร้อมๆ กับอุซาวะ เรอิสะกันนะคะ!"
10068-CVGroup_Tactic_Victory_1-1 = "ฮู่ว! คว้าชัยชนะมาได้ง่ายๆ เลยค่ะ!"
10068-CVGroup_Tactic_Victory_2-1 = "ฮู่ว! ความยุติธรรมย่อมชนะเสมอค่ะ!"
