[translation]
10068-CVGroup_Battle_Buffed_1-1 = "가, 감사합니다……."
10068-CVGroup_Battle_Defense_1-1 = "소용없습니다!"
10068-CVGroup_Battle_In_1-1 = "오! 제가 선봉인가요?"
10068-CVGroup_Battle_In_2-1 = "두려워 말고, 앞으로!"
10068-CVGroup_Battle_Move_1-1 = "아직 멀었습니다!"
10068-CVGroup_Battle_Move_2-1 = "다음으로 넘어갑니다!"
10068-CVGroup_Battle_Recovery_1-1 = "헉, 가, 감사합니다……!?"
10068-CVGroup_Battle_TacticalAction_1-1 = "허앗-!!"
10068-CVGroup_Battle_Victory_1-1 = "음! 당연한 결과죠!"
10068-CVGroup_Battle_Victory_2-1 = "다음입니다, 다음!"
10068-CVGroup_CommonSkill-1 = "필살! 승리의 포-즈!"
10068-CVGroup_ExSkill_1-1 = "으랏차아-!!"
10068-CVGroup_ExSkill_2-1 = "여기 등장!!"
10068-CVGroup_ExSkill_3-1 = "승부입니다!!"
10068-CVGroup_ExSkill_Level_1-1 = "놓치지 않습니다!"
10068-CVGroup_ExSkill_Level_2-1 = "도전장을 받으세요!"
10068-CVGroup_ExSkill_Level_3-1 = "각오하세요!!"
10068-CVGroup_Formation_In_1-1 = "드디어 제가 나갈 차례군요!"
10068-CVGroup_Formation_In_2-1 = "네! 언제든지 갈 수 있습니다!"
10068-CVGroup_Formation_Select-1 = "우자와 레이사에게 맡겨 주세요!"
10068-CVGroup_Growup_1-1 = "이, 이거요? 저……한테요?"
10068-CVGroup_Growup_2-1 = "감사합니다, 선생님! 더욱 힘내겠습니다!"
10068-CVGroup_Growup_3-1 = "우자와 레이사의 성장에는, 끝이 없습니다!"
10068-CVGroup_Growup_4-1 = "성장에는 책임이 따르는 법! 열심히 하겠습니다!"
10068-CVGroup_Relationship_Up_1-1 = "선생님만 괜찮으시다면… 그, 선생님 호위를 더 하고 싶어요…!"
10068-CVGroup_Relationship_Up_2-1 = "선생님께는 이미 너무 많은 걸 보여드렸지만,\n뭐, 괜찮겠죠! 선생님이시니까요!"
10068-CVGroup_Relationship_Up_3-1 = "여기까지 올 수 있었던 것들, 모두 선생님 덕이에요."
10068-CVGroup_Relationship_Up_4-1 = "지금까지 그래주셨듯, 앞으로도! 잘! 부탁드립니다!"
10068-CVGroup_Tactic_In_1-1 = "제 힘이 필요하다면 어디든!"
10068-CVGroup_Tactic_In_2-1 = "모두와 함께, 우자와 레이사가 갑니다!"
10068-CVGroup_Tactic_Victory_1-1 = "휴! 낙승이었군요!"
10068-CVGroup_Tactic_Victory_2-1 = "후우! 정의는 반드시 이길 겁니다!"
