[translation]
10064-CVGroup_Battle_Buffed_1-1 = "支援，確認。"
10064-CVGroup_Battle_Covered_1-1 = "好……"
10064-CVGroup_Battle_Defense_1-1 = "游刃有餘。"
10064-CVGroup_Battle_In_1-1 = "今年也能有很多委託……"
10064-CVGroup_Battle_In_2-1 = "換個心情……要上囉。"
10064-CVGroup_Battle_Move_1-1 = "探索開始。"
10064-CVGroup_Battle_Move_2-1 = "目標，變更。"
10064-CVGroup_Battle_Recovery_1-1 = "我就感激地收下囉。"
10064-CVGroup_Battle_TacticalAction_1-1 = "移動地點。"
10064-CVGroup_Battle_Victory_1-1 = "真不走運呢。"
10064-CVGroup_Battle_Victory_2-1 = "新年，有成為好的起點嗎。"
10064-CVGroup_CommonSkill-1 = "呵呵，真可愛。"
10064-CVGroup_ExSkill_1-1 = "咳哼……來，是御守。"
10064-CVGroup_ExSkill_2-1 = "咳哼……這個，你願意收下嗎？"
10064-CVGroup_ExSkill_3-1 = "嗯……覺得怎麼樣？"
10064-CVGroup_ExSkill_Level_1-1 = "要是能獲得保佑就好了呢。"
10064-CVGroup_ExSkill_Level_2-1 = "惡靈退散……之類的。"
10064-CVGroup_ExSkill_Level_3-1 = "祝你有美好的一年。"
10064-CVGroup_Formation_In_1-1 = "輪到我了？\n……我知道了。"
10064-CVGroup_Formation_In_2-1 = "適合嗎？\n……太好了。"
10064-CVGroup_Formation_Select-1 = "……怎麼了？"
10064-CVGroup_Growup_1-1 = "那個……謝謝你。\n今年也會跟老師在一起，對吧。"
10064-CVGroup_Growup_2-1 = "雖然不知道能不能回應你的期待……我會努力的。"
10064-CVGroup_Growup_3-1 = "現在，該做出什麼表情才好？\n抱歉，這種狀況……我不是很熟悉。"
10064-CVGroup_Growup_4-1 = "總是一味接受老師的好處呢……\n雖然不知道能不能好好回報，但我會盡己所能的。"
10064-CVGroup_Relationship_Up_1-1 = "羈絆這種東西……真不可思議。\n越是累積，居然就越思念彼此。"
10064-CVGroup_Relationship_Up_2-1 = "那個，這種事情，我其實不常說出口的。\n有老師在真是太好了……我是這麼想的。"
10064-CVGroup_Relationship_Up_3-1 = "能跟老師一起迎接新年會是什麼樣的心情……我一直在思考這件事。\n這樣一來，我似乎多少明白了一點。"
10064-CVGroup_Relationship_Up_4-1 = "謝謝你，願意跟我說很適合我。\n雖然那八成是場面話就是了。\n……不是場面話？\n等，等等，老師。剛才那樣，太狡猾了……"
10064-CVGroup_Tactic_In_1-1 = "走吧。"
10064-CVGroup_Tactic_In_2-1 = "委託就該迅速執行。"
10064-CVGroup_Tactic_Victory_1-1 = "辛苦了，老師。\n衣服也沒弄髒呢……太好了。"
10064-CVGroup_Tactic_Victory_2-1 = "新年伊始，我希望能有個好兆頭。"
