[translation]
10074-CVGroup_Battle_Buffed_1-1 = "Thank you. I'll repay you later."
10074-CVGroup_Battle_Covered_1-1 = "I'll hide!"
10074-CVGroup_Battle_Defense_1-1 = "It's no use!"
10074-CVGroup_Battle_In_1-1 = "Time to splash around and have some fun! ♡"
10074-CVGroup_Battle_In_2-1 = "Heehee, let's go!"
10074-CVGroup_Battle_Move_1-1 = "That way!"
10074-CVGroup_Battle_Move_2-1 = "Not yet, there's still some left!"
10074-CVGroup_Battle_Recovery_1-1 = "Thank you! ♡"
10074-CVGroup_Battle_TacticalAction_1-1 = "Hi-ya!"
10074-CVGroup_Battle_Victory_1-1 = "Anyone else want to cool down?"
10074-CVGroup_Battle_Victory_2-1 = "What's wrong? It's just a regular water balloon. ♡"
10074-CVGroup_CommonSkill-1 = "Now then! ♡"
10074-CVGroup_ExSkill_1-1 = "Everyone! This way! ♡"
10074-CVGroup_ExSkill_2-1 = "Wet all over! ♡"
10074-CVGroup_ExSkill_3-1 = "Heehee. How's this?"
10074-CVGroup_ExSkill_Level_1-1 = "Don't run away! ♡"
10074-CVGroup_ExSkill_Level_2-1 = "So refreshing!"
10074-CVGroup_ExSkill_Level_3-1 = "This is how a summer should be! ♡"
10074-CVGroup_Formation_In_1-1 = "Oh my, are you trying to pick on me?"
10074-CVGroup_Formation_In_2-1 = "Heehee. This is going to be fun."
10074-CVGroup_Formation_Select-1 = "Ah...! A bit gentler over there..."
10074-CVGroup_Growup_1-1 = "This is...! Sensei's incredible...! Heehee, never mind, just joking."
10074-CVGroup_Growup_2-1 = "You never change. You're always helping me, Sensei!"
10074-CVGroup_Growup_3-1 = "You should also take care of yourself sometimes, Sensei."
10074-CVGroup_Growup_4-1 = "I've gotten another incredible thing."
10074-CVGroup_Relationship_Up_1-1 = "Since we're at the ocean, what do you say to making memories together?"
10074-CVGroup_Relationship_Up_2-1 = "The ocean is pretty. That's all I wanted to say about that. For now."
10074-CVGroup_Relationship_Up_3-1 = "You really make me think, Sensei."
10074-CVGroup_Relationship_Up_4-1 = "How do you feel right now, Sensei? ...Me, I'm happy. Genuinely."
10074-CVGroup_Tactic_In_1-1 = "Whoa. So...many...enemies!"
10074-CVGroup_Tactic_In_2-1 = "I'll join you too."
10074-CVGroup_Tactic_Victory_1-1 = "Heehee, that was quite a good experience! ♡"
10074-CVGroup_Tactic_Victory_2-1 = "Ah! That feels nice. Don't you think, Sensei?"
