[translation]
10070-CVGroup_Battle_Buffed_1-1 = "受人恩惠，必當湧泉相報。"
10070-CVGroup_Battle_Covered_1-1 = "進行掩蔽。"
10070-CVGroup_Battle_Defense_1-1 = "那樣就結束了嗎？"
10070-CVGroup_Battle_In_1-1 = "來吧，時間到了。"
10070-CVGroup_Battle_In_2-1 = "由我打頭陣吧。"
10070-CVGroup_Battle_Move_1-1 = "不有所行動的人，就沒有勝利。"
10070-CVGroup_Battle_Move_2-1 = "是那邊吧？"
10070-CVGroup_Battle_Recovery_1-1 = "感謝你。"
10070-CVGroup_Battle_TacticalAction_1-1 = "進行移動。"
10070-CVGroup_Battle_Victory_1-1 = "對朋友報以敬愛，對叛徒投以子彈……呵。"
10070-CVGroup_Battle_Victory_2-1 = "我不過是在咀嚼當下罷了……呵。"
10070-CVGroup_CommonSkill-1 = "重新出發吧。"
10070-CVGroup_ExSkill_1-1 = "呼……為了未來。"
10070-CVGroup_ExSkill_2-1 = "那麼……對手是哪位？"
10070-CVGroup_ExSkill_3-1 = "現在正是……起身之時。"
10070-CVGroup_ExSkill_Level_1-1 = "永別了。\n呼。"
10070-CVGroup_ExSkill_Level_2-1 = "該道別了。\n……呼。"
10070-CVGroup_ExSkill_Level_3-1 = "雨，就快來了啊。\n……哈。"
10070-CVGroup_Formation_In_1-1 = "我的生命，是否有意義呢。"
10070-CVGroup_Formation_In_2-1 = "我們不是還有未來嗎？"
10070-CVGroup_Formation_Select-1 = "我，我才不是小孩子！"
10070-CVGroup_Growup_1-1 = "感覺變強了……這也是多虧了老師嗎？"
10070-CVGroup_Growup_2-1 = "今天的我，與昨天的我相比有所成長……\n呵，就是這麼回事。"
10070-CVGroup_Growup_3-1 = "「為你的眼眸乾杯」──\n為什麼要在這種情況，是嗎……？\n連這個都不知道嗎？真拿你沒辦法──\n……抱歉。我只是順勢說出來而已。"
10070-CVGroup_Growup_4-1 = "我們只要有需要保護的東西，就能變得更強──\n問我那是什麼……？\n哎……！拜託別問那麼詳細！"
10070-CVGroup_Relationship_Up_1-1 = "獵鳥的時候必須非常慎重。無論太快或太慢都不行。\n為什麼是鳥……？誰，誰知道呢……"
10070-CVGroup_Relationship_Up_2-1 = "總有一天，我們也將面臨終結吧。\n在那之前，真希望能互通心意啊……\n唔～！連我自己都覺得這台詞真棒！"
10070-CVGroup_Relationship_Up_3-1 = "一步一步，慢慢縮短距離吧。\n那樣的話，總有一天……\n……會怎樣咧？"
10070-CVGroup_Relationship_Up_4-1 = "雖然有句話說「不該做不習慣的事」……\n不過，也有「有些事物必須經歷挑戰才能獲得」這麼一句話……\n唔，沒什麼，請你忘了吧。"
10070-CVGroup_Tactic_In_1-1 = "啊啊，夢終究會醒……是這麼回事嗎。"
10070-CVGroup_Tactic_In_2-1 = "不錯嘛，這是最棒的位置。"
10070-CVGroup_Tactic_Victory_1-1 = "命運，必須靠自己的雙手來爭取。"
10070-CVGroup_Tactic_Victory_2-1 = "應當時刻保持如此。\n因為我可不想被環境給左右啊。"
