[translation]
10080-CVGroup_CommonSkill-1 = "직접 움직이는 타입은 아니거든."
10080-CVGroup_ExSkill_1-1 = "흐응. 정말로 괜찮을까나?"
10080-CVGroup_ExSkill_2-1 = "이렇게까진 안하려 했는데……."
10080-CVGroup_ExSkill_3-1 = "정말이지, 어쩔 수가 없네~?"
10080-CVGroup_ExSkill_Level_1-1 = "결국 이렇게 될거잖아?"
10080-CVGroup_ExSkill_Level_2-1 = "그러니까, 말했잖아?"
10080-CVGroup_ExSkill_Level_3-1 = "마음대로 해보라구"
10080-CVGroup_Growup_1-1 = "나쁘지 않은걸? 대신…… 나는 뭘 해줄 수 있을까나?"
10080-CVGroup_Growup_2-1 = "빚 지고 사는 성격은 아닌데……. 기억해 둘게."
10080-CVGroup_Growup_3-1 = "머리가 좀 시원해지는 느낌이랄까?"
10080-CVGroup_Growup_4-1 = "힘을 쓰기가 수월해진 느낌이야. ……궁금해? 테스트 해 줄까?"
10080-CVGroup_Relationship_Up_1-1 = "당신은 다른 사람한테도 이런 식으로 굴어?\n우후훗...... 이건 분명 상당한 인기력일 거야."
10080-CVGroup_Relationship_Up_2-1 = "흐응…… 이것도 '선생님'이라서 그런가?"
10080-CVGroup_Relationship_Up_3-1 = "가끔은 머릿속을 읽어볼까 생각하긴 해. ……걱정 마. 아직 안 했으니까."
10080-CVGroup_Relationship_Up_4-1 = "잠깐… 외지인에게 너무 과한 것 아닐까?"
10080-CVGroup_Battle_Buffed_1-1 = "도움이 되는걸."
10080-CVGroup_Battle_Covered_1-1 = "어머나."
10080-CVGroup_Battle_Defense_1-1 = "부질 없는 짓을 하네~?"
10080-CVGroup_Battle_In_1-1 = "뭐, 어디까지나 도와주는 거니까."
10080-CVGroup_Battle_In_2-1 = "조금이지만, 움직여 볼까?"
10080-CVGroup_Battle_Move_1-1 = "아직 남았다고……?"
10080-CVGroup_Battle_Move_2-1 = "이게 끝이 아니라고~?"
10080-CVGroup_Battle_Recovery_1-1 = "고마워☆"
10080-CVGroup_Battle_TacticalAction_1-1 = "으읏!"
10080-CVGroup_Battle_Victory_1-1 = "그래도 꽤 여유력[力] 있는 싸움이었지?"
10080-CVGroup_Battle_Victory_2-1 = "도와준 빚은 나중에 다 받아낼 거니까~?"
10080-CVGroup_Formation_In_1-1 = "앞으로 나서는 타입은 아닌데."
10080-CVGroup_Formation_In_2-1 = "필요하다면, 해줄 순 있지만."
10080-CVGroup_Formation_Select-1 = "흐으으응~?"
10080-CVGroup_Tactic_In_1-1 = "어머, 이런 것도 해?"
10080-CVGroup_Tactic_In_2-1 = "오늘은 기분이 좋아서 다행이네?"
10080-CVGroup_Tactic_Victory_1-1 = "꽤 열심히 했는데… 뭔가 보상은 없나~?"
10080-CVGroup_Tactic_Victory_2-1 = "못한다고는 말하지 않았다구☆"
