[translation]
10086-CVGroup_Battle_Buffed_1-1 = "Thank you."
10086-CVGroup_Battle_Defense_1-1 = "It's no use."
10086-CVGroup_Battle_In_1-1 = "Let's go. There's only one thing to do."
10086-CVGroup_Battle_In_2-1 = "I'll clean this up before practice."
10086-CVGroup_Battle_Move_1-1 = "I should raise the tempo a little bit."
10086-CVGroup_Battle_Move_2-1 = "I can't be late."
10086-CVGroup_Battle_Recovery_1-1 = "Thanks."
10086-CVGroup_Battle_TacticalAction_1-1 = "Moving."
10086-CVGroup_Battle_Victory_1-1 = "Mission complete. ...I'm glad it went well."
10086-CVGroup_Battle_Victory_2-1 = "Ah... Yeah. Thanks."
10086-CVGroup_CommonSkill-1 = "I need to check before I practice."
10086-CVGroup_ExSkill_1-1 = "The melody I prepared for you..."
10086-CVGroup_ExSkill_2-1 = "I want to show you...what I've practiced."
10086-CVGroup_ExSkill_3-1 = "This might sound clumsy, but...to you, from the bottom of my heart...!"
10086-CVGroup_ExSkill_Level_1-1 = "I'm ready."
10086-CVGroup_ExSkill_Level_2-1 = "Here comes the real part."
10086-CVGroup_ExSkill_Level_3-1 = "I'll play with all I've got!"
10086-CVGroup_ExSkill_Level_4-1 = "Ma non troppo!"
10086-CVGroup_ExSkill_Level_5-1 = "But not too much!"
10086-CVGroup_ExSkill_Level_6-1 = "Free and vivid...!"
10086-CVGroup_ExSkill_Level_7-1 = "The finale!"
10086-CVGroup_ExSkill_Level_8-1 = "Elegante!"
10086-CVGroup_ExSkill_Level_9-1 = "This is the end...!"
10086-CVGroup_Formation_In_1-1 = "Yeah, I'm ready."
10086-CVGroup_Formation_In_2-1 = "I was waiting for your orders, Sensei."
10086-CVGroup_Formation_Select-1 = "Don't...stare too much at me."
10086-CVGroup_Growup_1-1 = "I was able to make it through another verse thanks to you, Sensei. ...Thank you."
10086-CVGroup_Growup_2-1 = "I can be here like this thanks to you, Sensei. I'm truly happy."
10086-CVGroup_Growup_3-1 = "I want to keep getting stronger so I can repay you. Would you watch me do that?"
10086-CVGroup_Growup_4-1 = "I want to grow and get stronger so Sensei can rely on me. That's all I can think about right now."
10086-CVGroup_Relationship_Up_1-1 = "You're the one who taught me that even someone like me can be of help. Thanks to you, Sensei... I can... Thank you, truly."
10086-CVGroup_Relationship_Up_2-1 = "Um... Wearing this, I think I'm more self-conscious than usual. It's okay if it's Sensei with me, though..."
10086-CVGroup_Relationship_Up_3-1 = "Is there really a place here for someone like me? ...Heehee, you really don't change, do you. Thank you."
10086-CVGroup_Relationship_Up_4-1 = "Sensei, would you grab onto my hand? That way... It might calm my nerves down a little bit."
10086-CVGroup_Tactic_In_1-1 = "Even if I'm in a dress, it doesn't change what I must do."
10086-CVGroup_Tactic_In_2-1 = "I trust in Sensei's orders."
10086-CVGroup_Tactic_Victory_1-1 = "As expected, Sensei's command is flawless."
10086-CVGroup_Tactic_Victory_2-1 = "It was a flawless victory. I've been taking the time to practice."
