[translation]
10089-CVGroup_Battle_Buffed_1-1 = "是筆不錯的投資呢。"
10089-CVGroup_Battle_Covered_1-1 = "以為能打倒我嗎？"
10089-CVGroup_Battle_Defense_1-1 = "哼～只有這點程度嗎？"
10089-CVGroup_Battle_In_1-1 = "來……讓我們開始吧。"
10089-CVGroup_Battle_In_2-1 = "大家，要上囉。"
10089-CVGroup_Battle_Move_1-1 = "這裡已經收拾乾淨了呢。"
10089-CVGroup_Battle_Move_2-1 = "還有殘黨。繼續前進吧。"
10089-CVGroup_Battle_Recovery_1-1 = "謝謝你。"
10089-CVGroup_Battle_TacticalAction_1-1 = "哈啊！"
10089-CVGroup_Battle_Victory_1-1 = "已經結束了？是個比想像中還簡單的委託呢。"
10089-CVGroup_Battle_Victory_2-1 = "呵呵，超乎預期了對吧？"
10089-CVGroup_CommonSkill-1 = "呵呵……啊，等等！？"
10089-CVGroup_ExSkill_1-1 = "這是來自社長的提案唷。"
10089-CVGroup_ExSkill_2-1 = "名字之類的，多少有聽過吧？"
10089-CVGroup_ExSkill_3-1 = "心懷感激地收下吧。"
10089-CVGroup_ExSkill_Level_1-1 = "有興趣的話就連絡我吧。"
10089-CVGroup_ExSkill_Level_2-1 = "便利屋68，好好記住吧。"
10089-CVGroup_ExSkill_Level_3-1 = "怎麼樣？是個不錯的提案吧？"
10089-CVGroup_Formation_In_1-1 = "呵呵……原來如此。"
10089-CVGroup_Formation_In_2-1 = "是個明智的判斷呢。"
10089-CVGroup_Formation_Select-1 = "找我有什麼……呀啊！？\n呼……"
10089-CVGroup_Growup_1-1 = "真有先見之明呢。\n……我向你約定，絕對不會讓老師失望。"
10089-CVGroup_Growup_2-1 = "居然被期待到這種程度……\n我也必須更加磨練自己才行呢。"
10089-CVGroup_Growup_3-1 = "放心吧。\n即使我變強了，也不會丟下老師的唷。"
10089-CVGroup_Growup_4-1 = "呵呵……將來也繼續期待我吧。"
10089-CVGroup_Relationship_Up_1-1 = "該對老師……坦白到甚麼程度好呢……\n真傷腦筋。"
10089-CVGroup_Relationship_Up_2-1 = "光用言語表達，雖然覺得有點不足……\n……我很感謝你哦，老師。"
10089-CVGroup_Relationship_Up_3-1 = "這種時候，應該說什麼好呢……\n……我也會有不清楚的事的啊。"
10089-CVGroup_Relationship_Up_4-1 = "老師，那個……\n不，沒什麼。"
10089-CVGroup_Tactic_In_1-1 = "這份委託，真適合我呢。"
10089-CVGroup_Tactic_In_2-1 = "不必擔心哦。包在我身上吧。"
10089-CVGroup_Tactic_Victory_1-1 = "既然有我出手，這種程度也是理所當然的。"
10089-CVGroup_Tactic_Victory_2-1 = "怎麼樣，有讓你滿足嗎？"
