[translation]
10098-CVGroup_Formchange1_Battle_Buffed_1-1 = "튼튼해진 것 같아~"
10098-CVGroup_Formchange1_Battle_Defense_1-1 = "막을 건데~?"
10098-CVGroup_Formchange1_Battle_In_1-1 = "각오해."
10098-CVGroup_Formchange1_Battle_In_2-1 = "엄호는 부탁할게."
10098-CVGroup_Formchange1_Battle_Move_1-1 = "아직 남은 걸까나."
10098-CVGroup_Formchange1_Battle_Move_2-1 = "앞장설 테니 걱정 마."
10098-CVGroup_Formchange1_Battle_Recovery_1-1 = "고마워~"
10098-CVGroup_Formchange1_Battle_TacticalAction_1-1 = "포지션 변경."
10098-CVGroup_Formchange1_Battle_Victory_1-1 = "이 정도는 끄떡없지~"
10098-CVGroup_Formchange1_Battle_Victory_2-1 = "이제 안심해도 돼."
10098-CVGroup_Formchange1_CommonSkill-1 = "새롭게 가 볼까나~."
10098-CVGroup_Formchange1_ExSkill_1-1 = "그럼, 아저씨 차례인가?"
10098-CVGroup_Formchange1_ExSkill_2-1 = "안 통한다구."
10098-CVGroup_Formchange1_ExSkill_3-1 = "불렀어?"
10098-CVGroup_Formchange1_ExSkill_Level_1-1 = "모두, 뒤로!"
10098-CVGroup_Formchange1_ExSkill_Level_2-1 = "내가 갈게!"
10098-CVGroup_Formchange1_ExSkill_Level_3-1 = "그게 다야? 아저씨 실망인데~"
10098-CVGroup_Formchange1_Formation_In_1-1 = "기합 넣고 가볼까."
10098-CVGroup_Formchange1_Formation_In_2-1 = "귀찮지만…… 뭐, 제대로 할 테니까."
10098-CVGroup_Formchange1_Formation_Select-1 = "으헤, 기다리는 것도 힘드네."
10098-CVGroup_Formchange1_Formchange-1 = "전위는 나한테 맡겨."
10098-CVGroup_Growup_1-1 = "오? 아저씨한테 주는 거야? 고맙네~."
10098-CVGroup_Growup_2-1 = "응, 확실히 받았어. ……그럼, 나쁜 녀석들을 혼내주러 가 볼까."
10098-CVGroup_Growup_3-1 = "이야, 또 받아 버렸네. 그래서, 이번엔 어디서 싸우면 돼?"
10098-CVGroup_Growup_4-1 = "으헤~ 이런 거 쑥스럽지만…….\n고마워, 선생. 선생을 위해서, 아저씨 싸울게."
10098-CVGroup_Relationship_Up_1-1 = "정말…… 아저씨, 부끄럽다구."
10098-CVGroup_Relationship_Up_2-1 = "만에 하나, 선생이 위험에 처한다면, 그땐…….\n……아니, 그런 일은 일어나게 두지 않아."
10098-CVGroup_Relationship_Up_3-1 = "으헤~ 선생과 순찰…… 다음은 언제일까~ 벌써 기대되네~"
10098-CVGroup_Relationship_Up_4-1 = "내가 이런 모습이어도, 선생은 믿어주는구나.\n으헤~ 뭔가 쑥스럽구만~\n……그리고, 기뻐."
10098-CVGroup_Formchange1_Tactic_In_1-1 = "날 따라와."
10098-CVGroup_Formchange1_Tactic_In_2-1 = "시작해 볼까나~."
10098-CVGroup_Formchange1_Tactic_Victory_1-1 = "당연한 결과랄까."
10098-CVGroup_Formchange1_Tactic_Victory_2-1 = "끝났어~. 그럼 좀 쉬어볼까."
