[translation]
10099-CVGroup_Formchange2_Battle_Buffed_1-1 = "ขอบคุณนะ"
10099-CVGroup_Formchange2_Battle_Defense_1-1 = "ไม่ได้ผลหรอก"
10099-CVGroup_Formchange2_Battle_In_1-1 = "ยืนยันเป้าหมาย"
10099-CVGroup_Formchange2_Battle_In_2-1 = "ฝากเรื่องแบ็กอัปด้วยนะ"
10099-CVGroup_Formchange2_Battle_Move_1-1 = "ควบคุมแอเรีย"
10099-CVGroup_Formchange2_Battle_Move_2-1 = "จะไปเดี๋ยวนี้ละ"
10099-CVGroup_Formchange2_Battle_Recovery_1-1 = "ฟื้นฟูสำเร็จ"
10099-CVGroup_Formchange2_Battle_TacticalAction_1-1 = "ไปต่อเลย"
10099-CVGroup_Formchange2_Battle_Victory_1-1 = "ยังสบายๆ อยู่เลย"
10099-CVGroup_Formchange2_Battle_Victory_2-1 = "หืม แค่นี้หรอกเหรอ?"
10099-CVGroup_Formchange2_CommonSkill-1 = "ฝากยิงคุ้มกันด้วย!"
10099-CVGroup_Formchange2_ExSkill_1-1 = "หนึ่ง สอง\nข้างหลัง..."
10099-CVGroup_Formchange2_ExSkill_2-1 = "ฉันไม่พลาดหรอก..."
10099-CVGroup_Formchange2_ExSkill_3-1 = "มันขวางกันนะ"
10099-CVGroup_Formchange2_ExSkill_Level_1-1 = "รีบไปเลยมั้ย?"
10099-CVGroup_Formchange2_ExSkill_Level_2-1 = "ตรงนั้นน่ะ หลบนะ"
10099-CVGroup_Formchange2_ExSkill_Level_3-1 = "ถ้าไม่ถอย ฉันยิงนะ"
10099-CVGroup_Formchange2_Formation_In_1-1 = "เป้าหมายล่ะ?"
10099-CVGroup_Formchange2_Formation_In_2-1 = "ไว้ใจลุงได้เลย"
10099-CVGroup_Formchange2_Formation_Select-1 = "เช็กกระสุน เช็กลำกล้อง... ฮ้าวว..."
10099-CVGroup_Formchange2_Formchange-1 = "เหมือนพลังยิงจะไม่พอแฮะ?"
10099-CVGroup_Formchange2_Tactic_In_1-1 = "ถึงตาลุงออกโรงแล้วเหรอ~"
10099-CVGroup_Formchange2_Tactic_In_2-1 = "เตรียมพร้อมแล้ว ลุยเลยมั้ย?"
10099-CVGroup_Formchange2_Tactic_Victory_1-1 = "อื้อ ไม่เลวเลยนะ"
10099-CVGroup_Formchange2_Tactic_Victory_2-1 = "ครูก็ทำได้ดีมาก~"
