[translation]
10091-CVGroup_Battle_Buffed_1-1 = "哦～！這是什麼！"
10091-CVGroup_Battle_Defense_1-1 = "就說沒用了。"
10091-CVGroup_Battle_In_1-1 = "啊～啊～麥克風測試……好。"
10091-CVGroup_Battle_In_2-1 = "那麼……開始吧！"
10091-CVGroup_Battle_Move_1-1 = "還沒完呢。"
10091-CVGroup_Battle_Move_2-1 = "還沒結束吧？"
10091-CVGroup_Battle_Recovery_1-1 = "Thank you～"
10091-CVGroup_Battle_TacticalAction_1-1 = "呼！"
10091-CVGroup_Battle_Victory_1-1 = "怎麼樣啊，老師？還不錯吧？"
10091-CVGroup_Battle_Victory_2-1 = "是場不錯的表演呢！\n……開玩笑的。"
10091-CVGroup_CommonSkill-1 = "我看看……嗯！很好！"
10091-CVGroup_ExSkill_1-1 = "呼……哈啊……"
10091-CVGroup_ExSkill_2-1 = "嗯！沒問題。"
10091-CVGroup_ExSkill_3-1 = "別擔心，我做了很多練習。"
10091-CVGroup_ExSkill_Level_1-1 = "跟我來吧。"
10091-CVGroup_ExSkill_Level_2-1 = "聽聽我們的歌吧！"
10091-CVGroup_ExSkill_Level_3-1 = "……要上囉！"
10091-CVGroup_Formation_In_1-1 = "要在這裡唱歌嗎……？"
10091-CVGroup_Formation_In_2-1 = "咦……這個地點對嗎？"
10091-CVGroup_Formation_Select-1 = "等，等等！老師……！\n又要更顯眼了！"
10091-CVGroup_Growup_1-1 = "好像能感覺到練習的成果。"
10091-CVGroup_Growup_2-1 = "技術，好像稍微有點進步了……？"
10091-CVGroup_Growup_3-1 = "總覺得，有種被經紀人跟著的感覺呢。\n啊，不是！剛才的當我沒說！忘了吧！"
10091-CVGroup_Growup_4-1 = "要是唸書也能學得這麼快就好了……哈哈。"
10091-CVGroup_Relationship_Up_1-1 = "好像……越來越在意了……\n啊，沒事！只是自言自語而已。"
10091-CVGroup_Relationship_Up_2-1 = "雖然沒有多大的意義……\n我曾說過「要是有什麼事隨時跟我說」。\n那還是有效的哦。"
10091-CVGroup_Relationship_Up_3-1 = "老師，今天有時間嗎？\n嗯？啊，不是，也沒什麼重要的事啦。"
10091-CVGroup_Relationship_Up_4-1 = "我偶爾，會覺得距離感是不是稍～微有點太近了……\n有時就會有這樣的想法……"
10091-CVGroup_Tactic_In_1-1 = "唔哇……還真多……"
10091-CVGroup_Tactic_In_2-1 = "演奏……似乎不是呢。"
10091-CVGroup_Tactic_Victory_1-1 = "……還要再叫我哦。"
10091-CVGroup_Tactic_Victory_2-1 = "還挺不錯的吧？"
