[translation]
10097-CVGroup_Battle_Buffed_1-1 = "อ๊ะ ขอบคุณนะ!"
10097-CVGroup_Battle_Covered_1-1 = "ฝากยิงคุ้มกันด้วย!"
10097-CVGroup_Battle_Defense_1-1 = "ถอยไป... บอกให้ถอยไปไง!"
10097-CVGroup_Battle_In_1-1 = "ฮิฮิฮิ... นานๆ จะได้ทำแบบนี้สักที กระหน่ำยิงกันเลยมั้ย?"
10097-CVGroup_Battle_In_2-1 = "อ่า... ความรู้สึกนี้ อดใจไม่ไหวแล้ว!"
10097-CVGroup_Battle_Move_1-1 = "ตรงนี้ไม่มีปัญหา"
10097-CVGroup_Battle_Move_2-1 = "จะไปแล้วนะ"
10097-CVGroup_Battle_Recovery_1-1 = "รับเสบียงเรียบร้อย!"
10097-CVGroup_Battle_TacticalAction_1-1 = "เคลียร์~"
10097-CVGroup_Battle_Victory_1-1 = "ดีละ... ดีๆ... สุดยอดเลย...!"
10097-CVGroup_Battle_Victory_2-1 = "แฮ่ก แฮ่ก... ระเบิดไปซะ...!"
10097-CVGroup_CommonSkill-1 = "จะลดการ์ดลงแค่เพราะมันเป็นลูกโป่งน้ำไม่ได้หรอกนะ"
10097-CVGroup_ExSkill_1-1 = "ยืนยันพิกัดเป้าหมาย... เพิ่มกำลังยิงสูงสุด!"
10097-CVGroup_ExSkill_2-1 = "RABBIT 3 ขออนุมัติการยิง!"
10097-CVGroup_ExSkill_3-1 = "มิสไซล์... อ่า... ปลิวไปซะ!"
10097-CVGroup_ExSkill_Level_1-1 = "ใกล้... ใกล้มากจนอันตรายเลย...!"
10097-CVGroup_ExSkill_Level_2-1 = "อัลฟ่า! ไมค์! ฟ็อกซ์ทรอต!"
10097-CVGroup_ExSkill_Level_3-1 = "วิเศษจริงๆ..."
10097-CVGroup_Formation_In_1-1 = "แล้วตอนนี้จะระเบิดที่ไหนต่อดีละ?"
10097-CVGroup_Formation_In_2-1 = "ฮิฮิฮิ... กำลังรออยู่เลย"
10097-CVGroup_Formation_Select-1 = "แฮ่ก แฮ่ก...\nถ้ามิสไซล์ของจริงขนาดเท่านี้ได้ก็คงดีนะ..."
10097-CVGroup_Growup_1-1 = "อืม อย่างนี้นี่เอง\nถ้าเอาตรงนี้มาต่อกับตรงนี้ก็จะระเบิดได้ใหญ่ขึ้น..."
10097-CVGroup_Growup_2-1 = "ฮิฮิฮิ... แบบนี้ก็จะระเบิดเป็นเสี่ยงๆ ได้เต็มที่เลยสินะ"
10097-CVGroup_Growup_3-1 = "ไม่ต้องห่วง ฉันเข้าใจหมดแล้ว!"
10097-CVGroup_Growup_4-1 = "แฮ่ก แฮ่ก... เผาให้หมด เผาให้หมด..."
10097-CVGroup_Relationship_Up_1-1 = "ถ้ามีอะไรมาขวางทางละก็ บอกฉันได้ตลอดเลยนะ\nฉันจะระเบิดให้กระจุยเลย ฮิฮิฮิ..."
10097-CVGroup_Relationship_Up_2-1 = "สักวันหนึ่ง ถ้าหลังชนฝาแล้วก็มาหาฉันได้นะ\nฉันจะทำลายล้างไปพร้อมๆ กับคุณเอง"
10097-CVGroup_Relationship_Up_3-1 = "ถ้าคุณครูมองอยู่แบบนี้\nเส้นแบ่งการทำลายล้างมันก็เลือนลางขึ้นเลย\nแย่เลยแฮะ..."
10097-CVGroup_Relationship_Up_4-1 = "ขอบคุณนะคุณครู ต้องขอบคุณคุณครูเลยนะ\nที่ทำให้ฉันได้รู้ว่าหัวใจของคนก็ระเบิดเหมือนระเบิดได้"
10097-CVGroup_Tactic_In_1-1 = "อืม~ มาผ่อนคลายร่างกายกันหน่อยดีมั้ย?"
10097-CVGroup_Tactic_In_2-1 = "การให้โอเปอเรเตอร์ออกมาแนวหน้า มันเกินไปนะ~"
10097-CVGroup_Tactic_Victory_1-1 = "เอ๋? จบแล้วเหรอ? ยังมีระเบิดเหลืออีกเยอะเลยนะ?"
10097-CVGroup_Tactic_Victory_2-1 = "ฮิฮิฮิ... ถ้าแก้ไขไม่ได้ด้วยระเบิดจำนวนนี้\nก็แค่เตรียมระเบิดมาให้เยอะกว่านี้ก็พอนี่นา?"
