[translation]
10095-CVGroup_Battle_Buffed_1-1 = "감사드립니다. 기운이 나네요."
10095-CVGroup_Battle_Covered_1-1 = "숨겠어요."
10095-CVGroup_Battle_Defense_1-1 = "그 정도로는 안 돼요!"
10095-CVGroup_Battle_In_1-1 = "청소를 시작하겠습니다."
10095-CVGroup_Battle_In_2-1 = "우선은 움직이죠. 할 일이 많아요."
10095-CVGroup_Battle_Move_1-1 = "이곳의 청소는 완료되었습니다."
10095-CVGroup_Battle_Move_2-1 = "그러면 다음 위치로."
10095-CVGroup_Battle_Recovery_1-1 = "고마워요. 기운이 났어요."
10095-CVGroup_Battle_TacticalAction_1-1 = "움직일게요."
10095-CVGroup_Battle_Victory_1-1 = "오늘의 업무는 이것으로 종료입니다. 어떠셨나요, 주인님?"
10095-CVGroup_Battle_Victory_2-1 = "해냈어요, 선생님! 정말…… 언니!"
10095-CVGroup_CommonSkill-1 = "청소는 꼼꼼히…… 응, 됐네요!"
10095-CVGroup_ExSkill_1-1 = "하나, 둘……! 좋아, 클리어!"
10095-CVGroup_ExSkill_2-1 = "여기, 그리고 여기……! 해냈어!"
10095-CVGroup_ExSkill_3-1 = "침착하게, 차근차근…… 좋았어!"
10095-CVGroup_ExSkill_Level_1-1 = "스코어 갱신! 선생님, 봐 주셨나요?"
10095-CVGroup_ExSkill_Level_2-1 = "기록 갱신! 선생님, 어때요?"
10095-CVGroup_ExSkill_Level_3-1 = "랭킹 사이트에 올려 볼까……"
10095-CVGroup_Formation_In_1-1 = "네, 선생님…… 아뇨, 주인님! 제 차례인 거네요."
10095-CVGroup_Formation_In_2-1 = "알겠습니다. 저로 괜찮은 거죠?"
10095-CVGroup_Formation_Select-1 = "히야앗?! 후우…… 위험했다."
10095-CVGroup_Growup_1-1 = "어때요, 주인님? 제가 조금은 성장할 수 있었을까요?\n학생으로서…… 그리고, 메이드로서."
10095-CVGroup_Growup_2-1 = "노력의 방향성은 물론 중요하지만……\n가끔은 노력하고 있다는 사실 자체가, 안정감을 주기도 하네요."
10095-CVGroup_Growup_3-1 = "저는……이렇게 힘을 주시는 분이 계셔서 정말 다행이라고 생각해요."
10095-CVGroup_Growup_4-1 = "항상 지켜봐 주셔서 감사합니다. 앞으로도 주인님과 함께…… 힘내겠습니다."
10095-CVGroup_Relationship_Up_1-1 = "선생님… 주인님…… 어느 호칭이 좋으세요?\n저는…… 주인님 쪽이려나요……?"
10095-CVGroup_Relationship_Up_2-1 = "저희 사이의 거리, 가까워졌을까요? 그렇다면…… 기쁘네요. 에헤헤."
10095-CVGroup_Relationship_Up_3-1 = "훌륭한 주인을 섬기는 것이야말로, 메이드의 기쁨이라고 하죠. 선생님은 저에게 있어서 그런 존재랍니다……"
10095-CVGroup_Relationship_Up_4-1 = "주~ 인~ 님~♪ 에헤헤. 불러보고 싶었을 뿐이에요."
10095-CVGroup_Tactic_In_1-1 = "선생님이…… 주인님이 보고 계시니까……!"
10095-CVGroup_Tactic_In_2-1 = "지금만큼은, 완벽한 메이드가 될 거예요!"
10095-CVGroup_Tactic_Victory_1-1 = "이겼네요! 다행이에요."
10095-CVGroup_Tactic_Victory_2-1 = "어떤가요……? 저 잘 해냈나요?"
