[translation]
10103-CVGroup_Battle_Buffed_1-1 = "What...is this power?"
10103-CVGroup_Battle_Covered_1-1 = "Stay in formation!"
10103-CVGroup_Battle_Defense_1-1 = "Unbreakable, like a diamond!"
10103-CVGroup_Battle_In_1-1 = "For the great Red Winter!"
10103-CVGroup_Battle_In_2-1 = "Forward, through all of Kivotos!"
10103-CVGroup_Battle_Move_1-1 = "Pursue the enemy!"
10103-CVGroup_Battle_Move_2-1 = "Charge! And charge again!"
10103-CVGroup_Battle_Recovery_1-1 = "Thank you for your cooperation."
10103-CVGroup_Battle_TacticalAction_1-1 = "There's no time to hesitate!"
10103-CVGroup_Battle_Victory_1-1 = "All the hard work paid off."
10103-CVGroup_Battle_Victory_2-1 = "The ultimate tactic: a charge!"
10103-CVGroup_CommonSkill-1 = "Ambush, success!"
10103-CVGroup_ExSkill_1-1 = "What...what in the world is this?!"
10103-CVGroup_ExSkill_2-1 = "Such a nice, quiet forest... A-A bee?!"
10103-CVGroup_ExSkill_3-1 = "No sign of bears... Uaaagh!"
10103-CVGroup_ExSkill_Level_1-1 = "There's a beehive in there!"
10103-CVGroup_ExSkill_Level_2-1 = "I-It's falling!"
10103-CVGroup_ExSkill_Level_3-1 = "Neutralize the threats immediately!"
10103-CVGroup_Formation_In_1-1 = "Hm, I'll do it myself!"
10103-CVGroup_Formation_In_2-1 = "It's easy to move!"
10103-CVGroup_Formation_Select-1 = "W-Wait! Isn't the slit in this skirt too much?!"
10103-CVGroup_Growup_1-1 = "This is rather refreshing. Not bad."
10103-CVGroup_Growup_2-1 = "(This book... Have I read it before?)"
10103-CVGroup_Growup_3-1 = "Oho, now this is interesting."
10103-CVGroup_Growup_4-1 = "No matter how hot it is, you can't slack on training."
10103-CVGroup_Relationship_Up_1-1 = "I'm know that my field of view is narrower than others... So please watch over me, Sensei."
10103-CVGroup_Relationship_Up_2-1 = "I don't usually care for such revealing clothes...but if you like it, I'm okay with it, Sensei."
10103-CVGroup_Relationship_Up_3-1 = "I wish I could repay you with more than just a medal, Sensei..."
10103-CVGroup_Relationship_Up_4-1 = "I...no, all of Red Winter will always believe in you, Sensei."
10103-CVGroup_Tactic_In_1-1 = "It's a complicated path..."
10103-CVGroup_Tactic_In_2-1 = "(I'm not too confident on unfamiliar routes...)"
10103-CVGroup_Tactic_Victory_1-1 = "Heehee. Did you see that? This is the power of Red Winter!"
10103-CVGroup_Tactic_Victory_2-1 = "There is no failure in Red Winter's future!"
