[translation]
10100-CVGroup_Battle_Buffed_1-1 = "แต้งกิ้ว"
10100-CVGroup_Battle_Defense_1-1 = "จั๊กจี้นะ"
10100-CVGroup_Battle_In_1-1 = "อื้อ ฉันจะนำให้เอง"
10100-CVGroup_Battle_In_2-1 = "อื้อ ตามมาเลย"
10100-CVGroup_Battle_Move_1-1 = "ต่อไปที่ไหนเหรอ?"
10100-CVGroup_Battle_Move_2-1 = "น่าเอาจักรยานมาด้วยนะ..."
10100-CVGroup_Battle_Recovery_1-1 = "ขอบใจนะ"
10100-CVGroup_Battle_TacticalAction_1-1 = "จะไปเดี๋ยวนี้ละ"
10100-CVGroup_Battle_Victory_1-1 = "อื้อ ตอนนี้วางใจได้แล้ว"
10100-CVGroup_Battle_Victory_2-1 = "ทำได้ดีมาก"
10100-CVGroup_CommonSkill-1 = "ถึงเวลาหยิบอันนี้มาแล้วสินะ"
10100-CVGroup_ExSkill_1-1 = "นี่มัน..... ขอบใจนะ"
10100-CVGroup_ExSkill_2-1 = "คุณครู? อื้อ เข้าใจแล้ว..."
10100-CVGroup_ExSkill_3-1 = "ให้ฉันเหรอ...? ดีละ วางใจได้เลย"
10100-CVGroup_ExSkill_Level_1-1 = "อื้อ ฉันชินแล้วละ"
10100-CVGroup_ExSkill_Level_2-1 = "เป้าหมายอยู่ข้างหน้า"
10100-CVGroup_ExSkill_Level_3-1 = "เริ่มยิงสนับสนุน"
10100-CVGroup_Formation_In_1-1 = "เตรียมพร้อมแล้ว ฉันจะช่วยเอง"
10100-CVGroup_Formation_In_2-1 = "อื้อ ฉันจะร่วมต่อสู้ด้วย"
10100-CVGroup_Formation_Select-1 = "มีอะไรจะบอกหรือเปล่า...?"
10100-CVGroup_Growup_1-1 = "ให้ฉันเหรอ? ฉันจะรักษาอย่างดีเลย"
10100-CVGroup_Growup_2-1 = "อื้อ อาจจะเพิ่มมากขึ้นก็ได้...\nหมายถึงส่วนสูงน่ะ"
10100-CVGroup_Growup_3-1 = "นี่มัน...\nอื้อ ได้รับมาแล้วละ ฉันจะพยายามช่วยเหลือเต็มที่นะ"
10100-CVGroup_Growup_4-1 = "ขอบคุณนะ คุณครู\nต่อไปก็... รบกวนด้วยนะ"
10100-CVGroup_Relationship_Up_1-1 = "คุณครู ขอยืมไหล่... หน่อยสิ"
10100-CVGroup_Relationship_Up_2-1 = "โล่งอกไปทีนะที่ฉันช่วยคุณครูได้"
10100-CVGroup_Relationship_Up_3-1 = "อืม... ฉันไม่รู้ว่าจะฟังดูเป็นยังไง\nแต่... พออยู่กับคุณครูฉันก็รู้สึกมั่นคงน่ะ"
10100-CVGroup_Relationship_Up_4-1 = "ฉันยังมีเรื่องที่ยังไม่รู้เยอะเลย...\nอืม คุณครูช่วยสอนหลายๆ อย่างให้หน่อยนะ"
10100-CVGroup_Tactic_In_1-1 = "เจอศัตรูแล้ว ฝากสั่งการด้วย"
10100-CVGroup_Tactic_In_2-1 = "ยิงเลยได้มั้ย?"
10100-CVGroup_Tactic_Victory_1-1 = "อืม เป็นไปตามที่คิดไว้เลย"
10100-CVGroup_Tactic_Victory_2-1 = "เพราะมีคุณครูอยู่\nผลลัพธ์ก็เลยแน่นอนแบบนี้ไง"
