[translation]
10119-CVGroup_Battle_Buffed_1-1 = "ฉันได้รับความเชื่อใจอยู่หรือเปล่านะ..."
10119-CVGroup_Battle_Defense_1-1 = "มีแค่นี้เหรอ?"
10119-CVGroup_Battle_In_1-1 = "ทุกคน ไปกันเถอะ"
10119-CVGroup_Battle_In_2-1 = "ฉันจะแสดงพลังของเฮียกกะเรียวรันให้ดูเอง"
10119-CVGroup_Battle_Move_1-1 = "อย่าการ์ดตกสิ"
10119-CVGroup_Battle_Move_2-1 = "ยังไม่จบแค่นี้หรอกนะ"
10119-CVGroup_Battle_Recovery_1-1 = "ขอบคุณนะ"
10119-CVGroup_Battle_TacticalAction_1-1 = "รวดเร็ว ว่องไว"
10119-CVGroup_Battle_Victory_1-1 = "ได้รับความเสียหายมากเลย"
10119-CVGroup_Battle_Victory_2-1 = "จะพอใจกับชัยชนะเล็กๆ น้อยๆ ไม่ได้หรอก..."
10119-CVGroup_CommonSkill-1 = "ดีละ สมบูรณ์แบบเลย"
10119-CVGroup_ExSkill_1-1 = "ถ้านั่นเป็นวิธีที่จะปกป้องทุกคนได้...!"
10119-CVGroup_ExSkill_2-1 = "ฉันก็จะแสดงต่อไป ฉันจะสวมบทเป็นโกเรียว นางุสะต่อ!"
10119-CVGroup_ExSkill_3-1 = "ถึงจะน่ากลัว แต่การสูญเสียทุกคนน่ากลัวกว่า!"
10119-CVGroup_ExSkill_Level_1-1 = "นี่คือทั้งหมดที่ฉันทุ่มเทให้ได้"
10119-CVGroup_ExSkill_Level_2-1 = "ฉันไม่ยอมถอยให้หรอก!"
10119-CVGroup_ExSkill_Level_3-1 = "ดวลกันอย่างสง่าผ่าเผย!"
10119-CVGroup_Formation_In_1-1 = "ให้ฉันไปดีมั้ย..."
10119-CVGroup_Formation_In_2-1 = "ฉันจะทำให้เต็มที่เลย"
10119-CVGroup_Formation_Select-1 = "ฮะ... เฮือก?! คุณครู... มีเรื่องอะไรน่ะ?"
10119-CVGroup_Growup_1-1 = "นี่คือพลังของฉันจริงๆ งั้นเหรอ? ขอบคุณนะคุณครู..."
10119-CVGroup_Growup_2-1 = "ฉันพัฒนาขึ้นงั้นเหรอ? ไม่รู้สิ... ฉันแค่ทำเต็มที่ในทุกครั้งน่ะ"
10119-CVGroup_Growup_3-1 = "ฉันก็มีศักยภาพแบบนี้สินะ ต้องขอบคุณคุณครูเลยนะ"
10119-CVGroup_Growup_4-1 = "หนทางยังอีกยาวไกลจริงด้วย\nฉันยังไม่เชี่ยวชาญจริงๆ ขอบคุณนะ คุณครู"
10119-CVGroup_Relationship_Up_1-1 = "หิมะย่อมละลายภายใต้แสงแดดอันอบอุ่น...\nถ้าฉันอยู่ข้างๆ คุณครูได้ ตอนจบแบบนั้นก็น่าจะไม่แย่นะ"
10119-CVGroup_Relationship_Up_2-1 = "ฉันมีดีอย่างเดียวที่ใบหน้าอันสะสวย\nแต่ทำไมคุณครูถึงทำดีกับฉันคนนี้ขนาดนี้ล่ะ?"
10119-CVGroup_Relationship_Up_3-1 = "เห็นอย่างนี้ ฉันก็สำนึกในบุญคุณอยู่เสมอนะ\nถึงจะดูไม่เป็นอย่างนั้น เพราะฉันเป็นสาวสวยที่แสดงสีหน้าไม่เก่ง"
10119-CVGroup_Relationship_Up_4-1 = "แต่ฉันก็ชอบมือที่อบอุ่นของคุณครูนะ"
10119-CVGroup_Tactic_In_1-1 = "มาถึงพื้นที่ปฏิบัติการแล้ว"
10119-CVGroup_Tactic_In_2-1 = "ถึงจะยังไว้ใจไม่ได้มาก แต่ก็อยากให้เชื่อใจฉันนะ"
10119-CVGroup_Tactic_Victory_1-1 = "ปฏิบัติการครั้งนี้สำเร็จได้ด้วยความพยายามของทุกคนเลย ขอบใจนะทุกคน"
10119-CVGroup_Tactic_Victory_2-1 = "มันก็แน่นอนอยู่แล้ว ต่อไปต้องทำได้ดีกว่านี้แน่ๆ"
