[translation]
10115-CVGroup_Battle_Buffed_1-1 = "If it's now, I really think I can get a 0.40 batting average!"
10115-CVGroup_Battle_Covered_1-1 = "Evasive maneuvers!"
10115-CVGroup_Battle_Defense_1-1 = "An infield fly!"
10115-CVGroup_Battle_In_1-1 = "In a way, this is its own form of training."
10115-CVGroup_Battle_In_2-1 = "I'm going to reform the baseball club one day..."
10115-CVGroup_Battle_Move_1-1 = "Are we switching?"
10115-CVGroup_Battle_Move_2-1 = "Moving!"
10115-CVGroup_Battle_Recovery_1-1 = "Thank you. That's much better."
10115-CVGroup_Battle_TacticalAction_1-1 = "Just like a base runner...!"
10115-CVGroup_Battle_Victory_1-1 = "Hiyah! How was my swing, Sensei?!"
10115-CVGroup_Battle_Victory_2-1 = "For a 0.30 batting average!"
10115-CVGroup_CommonSkill-1 = "I caught it!"
10115-CVGroup_ExSkill_1-1 = "Phew... Then... Whoa?!"
10115-CVGroup_ExSkill_2-1 = "Now... Come...! Ehh?!"
10115-CVGroup_ExSkill_3-1 = "Okay... Here it goes...! How?!"
10115-CVGroup_ExSkill_Level_1-1 = "Huh? Huuh? No helping it..."
10115-CVGroup_ExSkill_Level_2-1 = "Whoa?! For now...!"
10115-CVGroup_ExSkill_Level_3-1 = "C-Calm down! *sigh*"
10115-CVGroup_Formation_In_1-1 = "Nothing better than a home run."
10115-CVGroup_Formation_In_2-1 = "Look forward to it, Sensei!"
10115-CVGroup_Formation_Select-1 = "Heave...ho. And that's one out, I suppose?"
10115-CVGroup_Growup_1-1 = "The fruits of my training! Thank you for watching over me, Sensei."
10115-CVGroup_Growup_2-1 = "Did I become a better batter? Was I able to...become a better player?"
10115-CVGroup_Growup_3-1 = "I want to take whatever I do seriously. Whether it be baseball...or anything else."
10115-CVGroup_Growup_4-1 = "They say baseball is a sport where those who try the hardest aren't noticed. Like practicing your best to catch a fly ball. I like that part about baseball."
10115-CVGroup_Relationship_Up_1-1 = "I think determining what can and can't be done is important. But...I want to give Sensei all the home run balls I hit. Heehee."
10115-CVGroup_Relationship_Up_2-1 = "Data and statistics are important, even in baseball. But a lot of things in life can't be explained with just numbers. Um, for example, like Sensei...to me..."
10115-CVGroup_Relationship_Up_3-1 = "Home runs are my favorite part about baseball. Although I rarely... Actually, I've never...hit one before... But do you want to know something, Sensei? You're like a homerun to me. Heehee."
10115-CVGroup_Relationship_Up_4-1 = "Watching baseball when I was younger used to give me the confidence to try. And now...I think that's what you do for me too."
10115-CVGroup_Tactic_In_1-1 = "Let's begin, Sensei."
10115-CVGroup_Tactic_In_2-1 = "They say it's not over till it's over!"
10115-CVGroup_Tactic_Victory_1-1 = "There's a saying that says luck comes from preparation. Good work, Sensei."
10115-CVGroup_Tactic_Victory_2-1 = "I'm sure this goes for everyone, but I hate losing!"
