[translation]
10114-CVGroup_Battle_Buffed_1-1 = "힘이 나요! 여러분 덕분이에요!"
10114-CVGroup_Battle_Defense_1-1 = "아우! 큰일 날뻔했네요……"
10114-CVGroup_Battle_In_1-1 = "1번 테이블 손님, 조금만 기다려 주세요!"
10114-CVGroup_Battle_In_2-1 = "주문은 무엇으로 하시겠어요?"
10114-CVGroup_Battle_Move_1-1 = "조금만 기다려 주세요!"
10114-CVGroup_Battle_Move_2-1 = "네! 지금 갈게요!"
10114-CVGroup_Battle_Recovery_1-1 = "감사합니다!"
10114-CVGroup_Battle_TacticalAction_1-1 = "다, 다음 주문이, 그러니까……"
10114-CVGroup_Battle_Victory_1-1 = "무사히 해냈어요! 어어? 어디 가는 거야?!"
10114-CVGroup_Battle_Victory_2-1 = "모두 선생님 덕분이에요! 자, 잠깐! 기다려!"
10114-CVGroup_CommonSkill-1 = "주문하신 디저트! 나왔습니다!"
10114-CVGroup_ExSkill_1-1 = "그러면, 이걸로…… 에헤헤…… 어, 어어?"
10114-CVGroup_ExSkill_2-1 = "마지막으로 이걸…… 해냈어! 으아앙?!"
10114-CVGroup_ExSkill_3-1 = "조심조심…… 와아! 안 돼!"
10114-CVGroup_ExSkill_Level_1-1 = "아우, 아아아…… 어떡하지……"
10114-CVGroup_ExSkill_Level_2-1 = "진정해, 팬 쨩!"
10114-CVGroup_ExSkill_Level_3-1 = "그렇게 날뛰면 안 돼……"
10114-CVGroup_Formation_In_1-1 = "네! 기억해 주셔서 감사합니다!"
10114-CVGroup_Formation_In_2-1 = "찾으셨나요?"
10114-CVGroup_Formation_Select-1 = "꺄앗?! 많이 기다리셨죠? 파르페입니다!"
10114-CVGroup_Growup_1-1 = "감사합니다, 선생님! 저…… 조금이지만, 나아졌을까요?"
10114-CVGroup_Growup_2-1 = "열심히 할게요! 하나하나, 정성스럽게요!"
10114-CVGroup_Growup_3-1 = "언제나 지켜봐 주셔서 감사합니다.\n모두…… 모두, 정말로 선생님 덕분이에요……!"
10114-CVGroup_Growup_4-1 = "중요한 것은 손님을 기쁘게 하는 것이라고 생각해요.\n달리 말하면, 사람을 기쁘게 하는 것 말이죠."
10114-CVGroup_Relationship_Up_1-1 = "정말 제대로 된 요리를 할 수 있게 된다면, 선생님께 가장 먼저 드리고 싶어요!"
10114-CVGroup_Relationship_Up_2-1 = "지금은 할 수 있는 일에 최선을 다하려고 해요.\n선생님께서 같이 있어 주신다면…… 더 잘할 수 있을지도요?"
10114-CVGroup_Relationship_Up_3-1 = "선생님이 계셔서, 다행이에요.\n네. 저는 선생님이…… 서, 선생님이 계시다는 게, 정말 좋아요!"
10114-CVGroup_Relationship_Up_4-1 = "다른 요리들은…… 어…… 여러 가지, 있었습니다만……\n이 파르페는 어떻게든 성공한 것 같아요!\n맛있게 드셔 주신다면 감사하겠습니다!"
10114-CVGroup_Tactic_In_1-1 = "선생님. 지켜봐 주세요!"
10114-CVGroup_Tactic_In_2-1 = "오늘의 저는 웨이트리스랍니다!"
10114-CVGroup_Tactic_Victory_1-1 = "서비스는 만족하셨나요, 손님?"
10114-CVGroup_Tactic_Victory_2-1 = "찾아 주셔서 감사합니다. 다음에도 부탁드리겠습니다."
