[translation]
10113-CVGroup_Battle_Buffed_1-1 = "Thank you."
10113-CVGroup_Battle_Covered_1-1 = "Safety zone secured."
10113-CVGroup_Battle_Defense_1-1 = "It wasn't very effective."
10113-CVGroup_Battle_In_1-1 = "Let's say it's an emergency situation."
10113-CVGroup_Battle_In_2-1 = "Fashion's not important in emergencies."
10113-CVGroup_Battle_Move_1-1 = "Change of situation. Relocating."
10113-CVGroup_Battle_Move_2-1 = "I wonder what bodies...PATIENTS might be there."
10113-CVGroup_Battle_Recovery_1-1 = "Good treatment."
10113-CVGroup_Battle_TacticalAction_1-1 = "Over there."
10113-CVGroup_Battle_Victory_1-1 = "Case concluded. Let's head back, Sensei."
10113-CVGroup_Battle_Victory_2-1 = "Retrieval complete. Good work."
10113-CVGroup_CommonSkill-1 = "Nothing looks wrong. Good."
10113-CVGroup_ExSkill_1-1 = "The ocean... Hm? Please wait..."
10113-CVGroup_ExSkill_2-1 = "How refreshing... Huh? Ah, emergency..."
10113-CVGroup_ExSkill_3-1 = "Nice view... Huh? Leave it to me..."
10113-CVGroup_ExSkill_Level_1-1 = "Commencing response."
10113-CVGroup_ExSkill_Level_2-1 = "Do not worry."
10113-CVGroup_ExSkill_Level_3-1 = "There's a body...I mean an injured person."
10113-CVGroup_Formation_In_1-1 = "I'm off duty today, but I'm fine being here with you, Sensei."
10113-CVGroup_Formation_In_2-1 = "Did you call, Sensei? What's going on?"
10113-CVGroup_Formation_Select-1 = "Gun, check. Medical supplies, check. I'm ready."
10113-CVGroup_Growup_1-1 = "They say rest is good for growth. I think this would be a good case study."
10113-CVGroup_Growup_2-1 = "Thank you, Sensei. I don't always have the words to express it, but you're precious to me."
10113-CVGroup_Growup_3-1 = "Even more bodies...Time for an emergency response."
10113-CVGroup_Growup_4-1 = "I also believe I've grown as a person. And that's thanks to you too, Sensei."
10113-CVGroup_Relationship_Up_1-1 = "Lately, I've grown curious about what you do on your days off. I want to know, so I adjust my days off accordingly."
10113-CVGroup_Relationship_Up_2-1 = "I wish you would look at only me right now. And yes, that is selfish of me."
10113-CVGroup_Relationship_Up_3-1 = "You know, I don't get to see you as often as I'd like, Sensei. Why don't we meet up?"
10113-CVGroup_Relationship_Up_4-1 = "I've already fulfilled my goal by being here with you, Sensei. Why don't we take this chance to make future plans?"
10113-CVGroup_Tactic_In_1-1 = "By the way, what do you do on your days off, Sensei?"
10113-CVGroup_Tactic_In_2-1 = "I'm always ready, even on my days off."
10113-CVGroup_Tactic_Victory_1-1 = "It's finally over. Good."
10113-CVGroup_Tactic_Victory_2-1 = "How about we enjoy the rest of our time together?"
