[translation]
10120-CVGroup_Battle_Buffed_1-1 = "접수!"
10120-CVGroup_Battle_Covered_1-1 = "잠깐 쉬었다 갈까~"
10120-CVGroup_Battle_Defense_1-1 = "컷!"
10120-CVGroup_Battle_In_1-1 = "우리의 리듬을 보여줄 시간!"
10120-CVGroup_Battle_In_2-1 = "셈라를 향해!"
10120-CVGroup_Battle_Move_1-1 = "간다!"
10120-CVGroup_Battle_Move_2-1 = "더 빠르게!"
10120-CVGroup_Battle_Recovery_1-1 = "좋았어!"
10120-CVGroup_Battle_TacticalAction_1-1 = "하압!"
10120-CVGroup_Battle_Victory_1-1 = "자 선생님, 박수 쳐도 좋아."
10120-CVGroup_Battle_Victory_2-1 = "연주, 끝!"
10120-CVGroup_CommonSkill-1 = "달다……!"
10120-CVGroup_ExSkill_1-1 = "연주, 시작!"
10120-CVGroup_ExSkill_2-1 = "드럼, 발진!"
10120-CVGroup_ExSkill_3-1 = "가자……!"
10120-CVGroup_ExSkill_Level_1-1 = "이것이…… 록이다……!"
10120-CVGroup_ExSkill_Level_2-1 = "나의 연주를…… 보아라……!"
10120-CVGroup_ExSkill_Level_3-1 = "힘차게 가자!"
10120-CVGroup_Formation_In_1-1 = "필요한가? 나의 그루브가?"
10120-CVGroup_Formation_In_2-1 = "탁월한 선택!"
10120-CVGroup_Formation_Select-1 = "무대에 오른 기분인걸?"
10120-CVGroup_Growup_1-1 = "후후, 응원 고마워, 선생님."
10120-CVGroup_Growup_2-1 = "환호하라, 갈채하라……!"
10120-CVGroup_Growup_3-1 = "성장할수록 보이는 것은, 더 높은 봉우리뿐……!"
10120-CVGroup_Growup_4-1 = "어때, 나의 연주는? 선생님 덕에 여기까지 왔다고?"
10120-CVGroup_Relationship_Up_1-1 = "후후, 드럼, 가르쳐줄까?"
10120-CVGroup_Relationship_Up_2-1 = "오늘은…… 음악의 달콤함에 대해 이야기해 볼까?"
10120-CVGroup_Relationship_Up_3-1 = "가끔은, 이렇게 조용히 함께 있는 것도 좋네."
10120-CVGroup_Relationship_Up_4-1 = "선생님도 함께 연주할 수 있으면 좋을 텐데. ……둘이서 말이야."
10120-CVGroup_Tactic_In_1-1 = "적들은 어디에 있는가!"
10120-CVGroup_Tactic_In_2-1 = "연주를 시작해 볼까?"
10120-CVGroup_Tactic_Victory_1-1 = "훌륭한 합주였어."
10120-CVGroup_Tactic_Victory_2-1 = "연습은 배신하지 않지."
