[translation]
10123-CVGroup_Battle_Buffed_1-1 = "十分感謝。"
10123-CVGroup_Battle_Covered_1-1 = "就先到此為止吧。"
10123-CVGroup_Battle_Defense_1-1 = "那樣實在比不上呢。"
10123-CVGroup_Battle_In_1-1 = "大家，似乎都很期待呢。"
10123-CVGroup_Battle_In_2-1 = "跟平時的我可不一樣唷。"
10123-CVGroup_Battle_Move_1-1 = "這還真有趣呢。"
10123-CVGroup_Battle_Move_2-1 = "還覺得不夠滿足嗎？"
10123-CVGroup_Battle_Recovery_1-1 = "感謝你。"
10123-CVGroup_Battle_TacticalAction_1-1 = "呼。"
10123-CVGroup_Battle_Victory_1-1 = "這才是真正的我哦。"
10123-CVGroup_Battle_Victory_2-1 = "……砰！"
10123-CVGroup_CommonSkill-1 = "呵呵……喀擦！"
10123-CVGroup_ExSkill_1-1 = "不需要說明了呢。"
10123-CVGroup_ExSkill_2-1 = "看來是時候展現實力了。"
10123-CVGroup_ExSkill_3-1 = "所謂主角，就是在決定性的瞬間才會登場的人。"
10123-CVGroup_ExSkill_Level_1-1 = "所謂快樂的時光，就是會在轉瞬之間逝去的東西。"
10123-CVGroup_ExSkill_Level_2-1 = "是否有讓你感受到快樂呢？"
10123-CVGroup_ExSkill_Level_3-1 = "錯過這個瞬間的話，就再也聽不到了哦？"
10123-CVGroup_Formation_In_1-1 = "我來讓你涼快一下吧？"
10123-CVGroup_Formation_In_2-1 = "像這樣身處前線也不錯呢。"
10123-CVGroup_Formation_Select-1 = "哦……？看來頗有自信呢。"
10123-CVGroup_Growup_1-1 = "簡直，像是成為了脫離韁繩的駿馬一樣。\n變得越來越……"
10123-CVGroup_Growup_2-1 = "有機會的時候，就該盡情享受。"
10123-CVGroup_Growup_3-1 = "究竟能走得多遠……不覺得好奇嗎？"
10123-CVGroup_Growup_4-1 = "感覺又變得更加清爽了。"
10123-CVGroup_Relationship_Up_1-1 = "要不要一起去兜風？\n當然，駕駛會由我來負責。"
10123-CVGroup_Relationship_Up_2-1 = "似乎得到了正面的評價，真是萬幸。\n不然的話，我可是要哭了呢。"
10123-CVGroup_Relationship_Up_3-1 = "讓我招待你一點東西吧？\n不需要？呵呵，真有老師的風格呢。"
10123-CVGroup_Relationship_Up_4-1 = "那個反應……讓我越來越感興趣了。\n有機會的話，還想讓你看看更多不同種類的服裝。"
10123-CVGroup_Tactic_In_1-1 = "一起度過愉快的時光吧。"
10123-CVGroup_Tactic_In_2-1 = "該做的事似乎堆積如山呢？"
10123-CVGroup_Tactic_Victory_1-1 = "關於身分的事……能請你替我保密嗎？"
10123-CVGroup_Tactic_Victory_2-1 = "久違地讓我放縱了一下。"
