[translation]
10124-CVGroup_Battle_Buffed_1-1 = "ค่ะ ให้เป็นหน้าที่ฉันเองค่ะ!"
10124-CVGroup_Battle_Covered_1-1 = "ตรวจพบที่กำบังชั่วคราว"
10124-CVGroup_Battle_Defense_1-1 = "ทำเต็มที่แล้วงั้นเหรอคะ?"
10124-CVGroup_Battle_In_1-1 = "ฉันจะคุ้มกันอย่างรอบคอบค่ะ"
10124-CVGroup_Battle_In_2-1 = "เข้าใกล้กองกำลังศัตรูแล้ว เริ่มการเข้าปะทะค่ะ"
10124-CVGroup_Battle_Move_1-1 = "ทำลายศัตรูและเข้ายึดพื้นที่"
10124-CVGroup_Battle_Move_2-1 = "รักษาพื้นที่และมุ่งหน้าต่อไปค่ะ"
10124-CVGroup_Battle_Recovery_1-1 = "ขอบคุณที่สนับสนุนค่ะ!"
10124-CVGroup_Battle_TacticalAction_1-1 = "เคลื่อนย้ายไปยังเป้าหมาย"
10124-CVGroup_Battle_Victory_1-1 = "ตั้งแต่นี้เป็นต้นไป ขอประกาศยุติการปะทะค่ะ"
10124-CVGroup_Battle_Victory_2-1 = "ค่ะ ผลมันก็เห็นชัดอยู่แล้วค่ะ"
10124-CVGroup_CommonSkill-1 = "แตงโมก็เป็นผักนะคะ!"
10124-CVGroup_ExSkill_1-1 = "ถ้าใช้ใจมองเท่านี้ก็คง... อึก!!"
10124-CVGroup_ExSkill_2-1 = "ทางนี้แน่เหรอ? เอ๊ะ? จะซุ่มโจมตีแล้วค่ะ!"
10124-CVGroup_ExSkill_3-1 = "มือโปรจะต้องใช้เครื่องมือ... เครื่องมือ... เอ๊ะ!"
10124-CVGroup_ExSkill_Level_1-1 = "ถึงจะหลับตาก็เดาได้นะคะ"
10124-CVGroup_ExSkill_Level_2-1 = "ก็แค่เรื่องง่ายๆ ค่ะ"
10124-CVGroup_ExSkill_Level_3-1 = "เข้าเป้าตามที่คิดไว้เลยค่ะ"
10124-CVGroup_Formation_In_1-1 = "ไม่ว่าในสถานการณ์ไหนก็ต้องละเอียดเสมอ\nไม่มีข้อยกเว้นค่ะ"
10124-CVGroup_Formation_In_2-1 = "ดีเลยค่ะ ฉันไม่คิดที่จะปล่อยวันหยุดให้ผ่านไปชิลๆ อยู่แล้วค่ะ"
10124-CVGroup_Formation_Select-1 = "เรียกฉันเหรอคะ? ฉันจะรีบไปทันทีค่ะ"
10124-CVGroup_Growup_1-1 = "มีคำสอนใหม่ๆ ในสถานที่ที่ไม่คุ้นเคย\nขอบคุณสำหรับการสั่งการค่ะ"
10124-CVGroup_Growup_2-1 = "การพักผ่อนก็เป็นส่วนหนึ่งของการฝึกเช่นกัน\nฉันจะจำเอาไว้ว่าการปรับสมดุลความแข็งแกร่งเป็นสิ่งจำเป็นค่ะ"
10124-CVGroup_Growup_3-1 = "คะ? การสอนของวันนี้จบเพียงเท่านี้?\nถึงจะมาที่ทะเลทั้งทีก็เถอะ...\nถ้าอย่างนั้นไปเดินเล่นกับฉันมั้ยคะ?"
10124-CVGroup_Growup_4-1 = "ทุกช่วงเวลาที่ฉันได้ใช้ร่วมกับคุณครู ยิ่งนานวันก็ยิ่ง\nน่าจดจำมากขึ้นเรื่อยๆ จนรู้สึกเหมือนว่าในหนึ่งวันของฉัน\nจะเต็มไปด้วยช่วงเวลาดีๆ เลยค่ะ"
10124-CVGroup_Relationship_Up_1-1 = "คือว่า... ช่วยอยู่ด้วยกันกับฉันสักครู่ได้รึเปล่าคะ?\nค่ะ แค่นั้นก็เพียงพอแล้วค่ะ"
10124-CVGroup_Relationship_Up_2-1 = "ฉันรักษาทุกสิ่งที่ได้รับมาจากคุณครูไว้อย่างดีค่ะ\nทั้งสิ่งของ ทั้งคำพูดและความรู้สึกด้วย"
10124-CVGroup_Relationship_Up_3-1 = "ถ้าทำแบบนี้บ่อยๆ... ฉันจะเข้าใจผิดนะคะ\nอย่าทำให้ความปรารถนาของฉันเพิ่มไปมากกว่านี้เลยค่ะ"
10124-CVGroup_Relationship_Up_4-1 = "ถ้าให้ฉันโลภมากกว่านี้ได้อีกนิด...\nเปล่าค่ะ ไม่มีอะไรหรอกค่ะ แต่ว่าเป็นแบบนี้ต่อไปจะดีกว่า..."
10124-CVGroup_Tactic_In_1-1 = "เข้าพื้นที่ปฏิบัติการ กำลังรอคำสั่งอยู่ค่ะ"
10124-CVGroup_Tactic_In_2-1 = "ตอนนี้เข้าสู่โหมดปฏิบัติการค่ะ"
10124-CVGroup_Tactic_Victory_1-1 = "ในฐานะรองหัวหน้าชมรมทวงความยุติธรรมแล้ว\nรู้สึกอายนิดหน่อยค่ะ"
10124-CVGroup_Tactic_Victory_2-1 = "เสร็จสิ้นปฏิบัติการ แน่นอนว่าชนะอย่างขาดลอยค่ะ"
