[translation]
10120-CVGroup_Battle_Buffed_1-1 = "拿到了！"
10120-CVGroup_Battle_Covered_1-1 = "稍微休息一下吧。"
10120-CVGroup_Battle_Defense_1-1 = "卡！"
10120-CVGroup_Battle_In_1-1 = "來刻下節奏吧！"
10120-CVGroup_Battle_In_2-1 = "為了泡芙！"
10120-CVGroup_Battle_Move_1-1 = "邁向下一個小節！"
10120-CVGroup_Battle_Move_2-1 = "加快節奏吧！"
10120-CVGroup_Battle_Recovery_1-1 = "好耶！"
10120-CVGroup_Battle_TacticalAction_1-1 = "哈啊！"
10120-CVGroup_Battle_Victory_1-1 = "掌聲準備好了嗎？"
10120-CVGroup_Battle_Victory_2-1 = "全力以赴了……！"
10120-CVGroup_CommonSkill-1 = "好甜～！"
10120-CVGroup_ExSkill_1-1 = "一二三四！"
10120-CVGroup_ExSkill_2-1 = "配合我！"
10120-CVGroup_ExSkill_3-1 = "走吧……！"
10120-CVGroup_ExSkill_Level_1-1 = "這就是……搖滾……！"
10120-CVGroup_ExSkill_Level_2-1 = "沉溺在我的節奏裡吧……！"
10120-CVGroup_ExSkill_Level_3-1 = "盡情享受吧！"
10120-CVGroup_Formation_In_1-1 = "果然還是需要嗎？我的律動。"
10120-CVGroup_Formation_In_2-1 = "選得真好！"
10120-CVGroup_Formation_Select-1 = "感覺就像站上了舞台一樣。"
10120-CVGroup_Growup_1-1 = "呵呵，謝謝你的應援，老師。"
10120-CVGroup_Growup_2-1 = "喝采吧……！給予更多的喝采吧……！"
10120-CVGroup_Growup_3-1 = "我真可怕……因為我還會不斷成長……！"
10120-CVGroup_Growup_4-1 = "……怎麼樣，我覺得已經進步了哦。\n多虧有老師，我才能走到這裡。"
10120-CVGroup_Relationship_Up_1-1 = "呵呵，想觸碰鼓的深淵嗎？"
10120-CVGroup_Relationship_Up_2-1 = "話說……你知道什麼是甜美的音樂嗎？"
10120-CVGroup_Relationship_Up_3-1 = "偶爾一起放空也不錯呢。"
10120-CVGroup_Relationship_Up_4-1 = "要是能跟老師一起即興演奏就好了……\n節奏就交給我吧。"
10120-CVGroup_Tactic_In_1-1 = "敵人在哪裡～！"
10120-CVGroup_Tactic_In_2-1 = "Music Start！"
10120-CVGroup_Tactic_Victory_1-1 = "真是場精彩的即興演奏。"
10120-CVGroup_Tactic_Victory_2-1 = "練習不會背叛。"
