[translation]
10128-CVGroup_Battle_Buffed_1-1 = "I'll make sure to repay you for this...!"
10128-CVGroup_Battle_Covered_1-1 = "I barely managed to hide...!"
10128-CVGroup_Battle_Defense_1-1 = "Fu, fufu, a-an attack like this...!"
10128-CVGroup_Battle_In_1-1 = "Now then, shall we go in and win?"
10128-CVGroup_Battle_In_2-1 = "Don't worry about the supplies."
10128-CVGroup_Battle_Move_1-1 = "Let's go!"
10128-CVGroup_Battle_Move_2-1 = "Relax!"
10128-CVGroup_Battle_Recovery_1-1 = "Thank you, customer...!"
10128-CVGroup_Battle_TacticalAction_1-1 = "Eek!"
10128-CVGroup_Battle_Victory_1-1 = "It was a clean deal."
10128-CVGroup_Battle_Victory_2-1 = "Please leave us a good review."
10128-CVGroup_CommonSkill-1 = "Fufu, would you like to see the merchandise?"
10128-CVGroup_ExSkill_1-1 = "Shh, keep what you just saw a secret, okay?"
10128-CVGroup_ExSkill_2-1 = "How was it? Did I look cool?"
10128-CVGroup_ExSkill_3-1 = "Okay, let's slip out quietly."
10128-CVGroup_ExSkill_Level_1-1 = "Express delivery here!"
10128-CVGroup_ExSkill_Level_2-1 = "With speed and accuracy!"
10128-CVGroup_ExSkill_Level_3-1 = "Destination is the enemy territory! Delivery complete!"
10128-CVGroup_Formation_In_1-1 = "You will not regret that choice."
10128-CVGroup_Formation_In_2-1 = "Is the thing we need to deliver...victory itself?"
10128-CVGroup_Formation_Select-1 = "Fufu... Eek! Ugh..."
10128-CVGroup_Growup_1-1 = "Ooh, where did you get something like this...? Thank you, Sensei!"
10128-CVGroup_Growup_2-1 = "So much investment...! I won't let you down!"
10128-CVGroup_Growup_3-1 = "Doing this much for me...? ...Is there something you need me to procure, by chance?"
10128-CVGroup_Growup_4-1 = "Thank you, Sensei. I'll make sure to repay you for your generous investment...!"
10128-CVGroup_Relationship_Up_1-1 = "Media and art... Would you like to listen to my story?"
10128-CVGroup_Relationship_Up_2-1 = "How odd. I start talking a lot with you, Sensei."
10128-CVGroup_Relationship_Up_3-1 = "Um, do you like watching movies? Oh, no, I was just asking for artistic purposes...!"
10128-CVGroup_Relationship_Up_4-1 = "I wonder why it is that I want to have them by my side, when I can already see them whenever I want..."
10128-CVGroup_Tactic_In_1-1 = "Fufu, is this the new market?"
10128-CVGroup_Tactic_In_2-1 = "I wonder what kind of produce I need to win..."
10128-CVGroup_Tactic_Victory_1-1 = "Fufu, things went as I expected."
10128-CVGroup_Tactic_Victory_2-1 = "The product, named \"Victory,\" has been successfully delivered."
