[translation]
10126-CVGroup_Battle_Buffed_1-1 = "ฮิฮิ ขอบคุณนะ"
10126-CVGroup_Battle_Defense_1-1 = "แบร่"
10126-CVGroup_Battle_In_1-1 = "ฉันจะแสดงวิชาเล่นแร่แปรธาตุให้ดูเอง"
10126-CVGroup_Battle_In_2-1 = "โชคชะตา... จะนำทางพวกเรา"
10126-CVGroup_Battle_Move_1-1 = "สัมผัสได้ถึง... โชคชะตาจากทางนั้น"
10126-CVGroup_Battle_Move_2-1 = "เงียบ... เหมือนวิญญาณเลย..."
10126-CVGroup_Battle_Recovery_1-1 = "ร่างกาย... อบอุ่นขึ้นแล้ว"
10126-CVGroup_Battle_TacticalAction_1-1 = "สำ-เร็จ"
10126-CVGroup_Battle_Victory_1-1 = "ฮิฮิ นี่ก็คงเป็นโชคชะตาสินะ"
10126-CVGroup_Battle_Victory_2-1 = "ผู้ที่เชื่อในรหัสยศาสตร์จะเป็นผู้ชนะ"
10126-CVGroup_CommonSkill-1 = "ปัง~"
10126-CVGroup_ExSkill_1-1 = "ดื่ม... สักหน่อยมั้ย?"
10126-CVGroup_ExSkill_2-1 = "แนะนำ... อันนี้เลย"
10126-CVGroup_ExSkill_3-1 = "รับรองเลยว่าดีต่อสุขภาพแน่นอน..."
10126-CVGroup_ExSkill_Level_1-1 = "ฮิฮิ งั้นสินะ..."
10126-CVGroup_ExSkill_Level_2-1 = "อร่อยออก..."
10126-CVGroup_ExSkill_Level_3-1 = "ฉันต้องกินบ้างแล้ว..."
10126-CVGroup_Formation_In_1-1 = "ว่าแล้วเชียว... ต้องให้ฉันช่วยสินะ..."
10126-CVGroup_Formation_In_2-1 = "ในชาติที่แล้ว... ก็เลือกฉันเหมือนกันนี่นะ"
10126-CVGroup_Formation_Select-1 = "อิฮิฮิ..."
10126-CVGroup_Growup_1-1 = "อยากตัวสูงๆ จัง..."
10126-CVGroup_Growup_2-1 = "จิตวิญญาณกำลังเริงระบำ... ฮิฮิ"
10126-CVGroup_Growup_3-1 = "ความเป็นไปได้ของการเล่นแร่แปรธาตุ... เพิ่มขึ้นแล้ว"
10126-CVGroup_Growup_4-1 = "ลองทำการทดลองใหม่... ดีมั้ยนะ"
10126-CVGroup_Relationship_Up_1-1 = "อ๊ะ คุณครู! คาโนเอะดีใจจังเลย!\nเป็นไง? ฮิฮิ"
10126-CVGroup_Relationship_Up_2-1 = "ฮิฮิ... คุณครู... เหมือนกับ 'ตอนนั้น' เลยนะ"
10126-CVGroup_Relationship_Up_3-1 = "สะ... สำหรับฉันก็มีแค่คุณครูคนเดียวนี่...\nไม่ได้แสดงเลยนะ ฉันพูดจริงๆ ขะ... ขอบคุณนะ"
10126-CVGroup_Relationship_Up_4-1 = "ฮิฮิ... อิฮิฮิฮิ...!"
10126-CVGroup_Tactic_In_1-1 = "ฉันจะปกป้องคุณเอง\nเหมือนกับ... ในชาติก่อน"
10126-CVGroup_Tactic_In_2-1 = "ถึงมือฉันจะเย็น... แต่ฉันหัวร้อนนะ"
10126-CVGroup_Tactic_Victory_1-1 = "ผลลัพธ์เหมือนกับ 'ตอนนั้น' เลยนะ... ฮิฮิ"
10126-CVGroup_Tactic_Victory_2-1 = "ฮิฮิ ชัยชนะในครั้งนี้...\nก็ถูกโชคชะตากำหนดไว้แล้วเช่นกัน"
