[translation]
10131-CVGroup_Battle_Buffed_1-1 = "ขอบคุณที่กรุณาค่ะ"
10131-CVGroup_Battle_Covered_1-1 = "ต้องหาที่หลบแล้วละค่ะ"
10131-CVGroup_Battle_Defense_1-1 = "ขนาดนั้นเลยเหรอคะ?"
10131-CVGroup_Battle_In_1-1 = "มองตรงไปข้างหน้า ก้าวเดินอย่างสง่างาม\nเพราะบุคลิกย่อมสะท้อนถึงจิตใจของคนยังไงล่ะคะ"
10131-CVGroup_Battle_In_2-1 = "จุดเริ่มต้นที่ดี ย่อมนำไปสู่บทสรุปที่ดีค่ะ\nเหมือนกับนิยายยังไงล่ะคะ"
10131-CVGroup_Battle_Move_1-1 = "จุดจบก็คือจุดเริ่มต้นใหม่"
10131-CVGroup_Battle_Move_2-1 = "เมื่อย่อหน้าจบลง ประโยคใหม่ก็จะเริ่มต้นค่ะ"
10131-CVGroup_Battle_Recovery_1-1 = "ขอบคุณนะคะ"
10131-CVGroup_Battle_TacticalAction_1-1 = "ทางนั้นเหรอคะ?"
10131-CVGroup_Battle_Victory_1-1 = "เป็นตอนจบที่ให้ 5 ดาว... หรืออย่างน้อยก็ต้อง 4 ดาวเลยค่ะ"
10131-CVGroup_Battle_Victory_2-1 = "ขอสรรเสริญและมอบเกียรติยศให้ทุกคนที่ทุ่มเทสุดกำลัง"
10131-CVGroup_CommonSkill-1 = "นี่ค่ะ ฉันขอมอบให้ค่ะ"
10131-CVGroup_ExSkill_1-1 = "จริงๆ เลยเชียว...! ระวังหน่อยสิคะ!"
10131-CVGroup_ExSkill_2-1 = "ห้ามลืมนะคะ ต้องสง่างามอยู่เสมอ!"
10131-CVGroup_ExSkill_3-1 = "ไม่เป็นไรใช่มั้ยคะ? สง่างามทุกย่างก้าว!"
10131-CVGroup_ExSkill_Level_1-1 = "ใช้เจ้านี่สิคะ"
10131-CVGroup_ExSkill_Level_2-1 = "ไม่ต้องคืนหรอกค่ะ"
10131-CVGroup_ExSkill_Level_3-1 = "คราวหน้าก็ระวังด้วยนะคะ"
10131-CVGroup_Formation_In_1-1 = "การวิจารณ์ คือการมองให้ทะลุถึงแก่นแท้ของงานเขียนค่ะ"
10131-CVGroup_Formation_In_2-1 = "ค่ะ ถ้าเป็นเรื่องที่ฉันช่วยได้ละก็... ฉันยินดีทำทุกอย่างค่ะ"
10131-CVGroup_Formation_Select-1 = "กรี๊ด?! จริงๆ เลย... คราวหลังต้องรับผิดชอบให้ดีนะคะ"
10131-CVGroup_Growup_1-1 = "มนุษย์คือผู้ที่ต้องก้าวเดินต่อไปเพื่อวันพรุ่งนี้ที่ดีกว่า\nนั่นคือเหตุผลที่เราต้องหมั่นฝึกฝนอยู่เสมอ\nทั้งยังเป็นเหตุผลที่เราต้องหมั่นสำรวจตนเองยังไงล่ะคะ"
10131-CVGroup_Growup_2-1 = "ตราบที่ยังมีความเป็นไปได้ เราจะหยุดอยู่แค่นี้ไม่ได้นะคะ\nเอ้า ส่งมือมาสิคะ คุณครู มาก้าวไปข้างหน้าด้วยกันเถอะค่ะ"
10131-CVGroup_Growup_3-1 = "คนเราต้องรู้จักตัวเองให้ดีค่ะ แม้แต่จะเป็นนักวิจารณ์ก็ไม่มีข้อยกเว้น\nเพราะมีแต่ต้องทำแบบนั้น ถึงจะเติบโตขึ้นได้ค่ะ\nเหมือนกับในตอนนี้ไงล่ะคะ"
10131-CVGroup_Growup_4-1 = "คำว่าเนื้อคู่แห่งโชคชะตา อาจจะดูโบราณไปบ้าง\nแต่ตอนนี้ฉันอยากจะลองเชื่อในเรื่องนั้นดูค่ะ\nเพราะนั่นคือสิ่งที่จะช่วยนำทางให้เราทุกคนก้าวต่อไปได้"
10131-CVGroup_Relationship_Up_1-1 = "จู่ๆ ฉันก็คิดอะไรแบบนี้ขึ้นมาน่ะค่ะ ฉันอาจจะชินกับการวิจารณ์คนอื่น...\nแต่การได้ฟังคำวิจารณ์ที่มีต่อตัวเองก็ฟังดูน่าตื่นเต้นดีนะคะ\nเพราะงั้น... ถ้าเป็นคุณครูละก็จะวิจารณ์ฉันก็ได้นะคะ..."
10131-CVGroup_Relationship_Up_2-1 = "ที่จริงพอใช้ชีวิตไปนานๆ ฉันก็มักจะคิดว่าการจะหาสิ่งที่ถูกใจร้อยเปอร์เซ็นต์\nมันยากเหมือนกันค่ะ แต่ดูเหมือนว่าจะมีข้อยกเว้นอยู่เหมือนกันนะคะ\nส่วนสิ่งนั้นคืออะไรนั้น... ฉันขอเก็บไว้เป็นความลับค่ะ สำหรับในตอนนี้น่ะ"
10131-CVGroup_Relationship_Up_3-1 = "มีไม่กี่เรื่องหรอกค่ะที่จะทำให้ฉันตื่นเต้นได้ และการพบเรื่องราวดีๆ ก็เป็นหนึ่งในนั้น\nสำหรับฉันคนที่ยอดเยี่ยมก็เหมือนกับ... เรื่องราวที่ยอดเยี่ยมนั่นแหละค่ะ\nที่ฉันพูดไปเมื่อกี้คงไม่ค่อยเข้าใจสินะคะ?\nฮุฮุ... ได้ยินอย่างนั้นก็โล่งอกไปทีค่ะ สำหรับในตอนนี้น่ะ"
10131-CVGroup_Relationship_Up_4-1 = "บางครั้ง ฉันก็ลองจินตนาการถึงตัวเองในตอนที่ไม่ได้พบกับคุณครูดูค่ะ\nเรื่องราวตอนนั้นคงจะเป็นสีหม่น... และเป็นเรื่องที่จืดชืดไร้ชีวิตชีวาแน่ๆ ค่ะ\nหมายความว่ายังไงน่ะเหรอคะ? ฮุฮุ ไม่มีอะไรเป็นพิเศษหรอกค่ะ\nก็อาจจะนะคะ"
10131-CVGroup_Tactic_In_1-1 = "มาเริ่มก้าวแรกกันเลยค่ะ"
10131-CVGroup_Tactic_In_2-1 = "ทุกคนสบายดีรึเปล่าคะ?"
10131-CVGroup_Tactic_Victory_1-1 = "เป็นเรื่องราวที่มีประเด็นให้ต้องวิจารณ์อยู่ค่ะ"
10131-CVGroup_Tactic_Victory_2-1 = "ตอนจบที่สมหวังแม้จะดูเชยไปบ้าง แต่ก็เป็นการจบที่งดงามค่ะ"
