[translation]
13006-CVGroup_CommonSkill-1 = "I'm going to surprise you!"
13006-CVGroup_ExSkill_1-1 = "Ta-da! Let's start the fireworks show!"
13006-CVGroup_ExSkill_2-1 = "It's this heart-pounding moment!"
13006-CVGroup_ExSkill_3-1 = "Okay, let's gooo!"
13006-CVGroup_ExSkill_Level_1-1 = "Take this! Boom! Ahahahaha! This is fun."
13006-CVGroup_ExSkill_Level_2-1 = "Ahahaha! It's just like popcorn! "
13006-CVGroup_ExSkill_Level_3-1 = "Shoot away, and...Make it! Go! BOOM!"
13006-CVGroup_Growup_1-1 = "Okay, I'll live up to Sensei's expectations for sure!"
13006-CVGroup_Growup_2-1 = "Well? Do you appreciate me more now?"
13006-CVGroup_Growup_3-1 = "Heeheehee, feels like I've gotten stronger."
13006-CVGroup_Growup_4-1 = "To care about me this much... You must really like me! Right?"
13006-CVGroup_Relationship_Up_1-1 = "When I'm with Sensei, things are more fun than usual, for some reason."
13006-CVGroup_Relationship_Up_2-1 = "Maybe I should ask Sensei for a favor this time!"
13006-CVGroup_Relationship_Up_3-1 = "Heeheehee! I just want to run around holding onto you."
13006-CVGroup_Relationship_Up_4-1 = "It's fun to be around you, but I think there's more to it than that. Heehee!"
13006-CVGroup_Battle_Buffed_1-1 = "Heehee, thank you."
13006-CVGroup_Battle_Defense_1-1 = "It's no use!"
13006-CVGroup_Battle_In_1-1 = "Mm! Let's go for some fun!"
13006-CVGroup_Battle_In_2-1 = "Okay! I'm on commission!"
13006-CVGroup_Battle_Move_1-1 = "Ahaha! That was fun!"
13006-CVGroup_Battle_Move_2-1 = "I wonder what's over here."
13006-CVGroup_Battle_Recovery_1-1 = "Ahaha, thank you!"
13006-CVGroup_Battle_TacticalAction_1-1 = "Here I go!"
13006-CVGroup_Battle_Victory_1-1 = "Twirl! That was fun!"
13006-CVGroup_Battle_Victory_2-1 = "Ta-da! Victory, victory!"
13006-CVGroup_Formation_In_1-1 = "I'll be right there!"
13006-CVGroup_Formation_In_2-1 = "I'm on the clock as of now."
13006-CVGroup_Formation_Select-1 = "Heehee! So you need me after all?"
13006-CVGroup_Tactic_In_1-1 = "Yay! Shall we have some fun?"
13006-CVGroup_Tactic_In_2-1 = "This one? I'll take 'em out!"
13006-CVGroup_Tactic_Victory_1-1 = "You're done, right, Sensei! Let's play, let's play!"
13006-CVGroup_Tactic_Victory_2-1 = "Heeheehee... That was enjoyable."
