[translation]
13007-CVGroup_Battle_Buffed_1-1 = "Okay, great!"
13007-CVGroup_Battle_Covered_1-1 = "I'll hide!"
13007-CVGroup_Battle_Defense_1-1 = "That's all?"
13007-CVGroup_Battle_In_1-1 = "Okay, I'm going! "
13007-CVGroup_Battle_In_2-1 = "Let's wrap this up and get some food!"
13007-CVGroup_Battle_Move_1-1 = "*sigh* Now I'm hungry..."
13007-CVGroup_Battle_Move_2-1 = "I should've brought snacks..."
13007-CVGroup_Battle_Recovery_1-1 = "Thank you! I owe you one!"
13007-CVGroup_Battle_TacticalAction_1-1 = "Moving!"
13007-CVGroup_Battle_Victory_1-1 = "Heehee. Let's take a bite now... Huh?! Wh-Whyyyyy!"
13007-CVGroup_Battle_Victory_2-1 = "Tada! My last... H-Huuuuuh?!"
13007-CVGroup_CommonSkill-1 = "I won't forgive you!"
13007-CVGroup_ExSkill_1-1 = "Hm, hmm... Ehhh?! Waaah!"
13007-CVGroup_ExSkill_2-1 = "Dango, dango! Ehhh?!"
13007-CVGroup_ExSkill_3-1 = "Heehee... Huh? Ugh, seriously?! "
13007-CVGroup_ExSkill_Level_1-1 = "I didn't even get to taste this yet!!"
13007-CVGroup_ExSkill_Level_2-1 = "You jerks!"
13007-CVGroup_ExSkill_Level_3-1 = "I'll shred you!"
13007-CVGroup_Formation_In_1-1 = "Let's do this!"
13007-CVGroup_Formation_In_2-1 = "Leave it to me!"
13007-CVGroup_Formation_Select-1 = "L-Let me go!"
13007-CVGroup_Growup_1-1 = "I-I'm not small! I'm still growing. I'll grow even taller!"
13007-CVGroup_Growup_2-1 = "I don't really get why, but...I think I've gotten a bit stronger!"
13007-CVGroup_Growup_3-1 = "Let's chow down! And get stronger! And go out and have some fun! Sensei!"
13007-CVGroup_Growup_4-1 = "I'm still fine! I can eat so much more!"
13007-CVGroup_Relationship_Up_1-1 = "It's not like you can buy my admiration with food... I-I'm serious!"
13007-CVGroup_Relationship_Up_2-1 = "To buy me something tasty again... You're a good person, Sensei..."
13007-CVGroup_Relationship_Up_3-1 = "I don't hate hearing that I'm cute, but... N-Nevermind!"
13007-CVGroup_Relationship_Up_4-1 = "Um... Call me...if you need me. I-I'm always ready to help Sensei!"
13007-CVGroup_Tactic_In_1-1 = "I'll take point!"
13007-CVGroup_Tactic_In_2-1 = "If I win, I'll get to eat something tasty!"
13007-CVGroup_Tactic_Victory_1-1 = "A perfect victory, right?"
13007-CVGroup_Tactic_Victory_2-1 = "Sensei! You really are treating me to a meal, right?!"
