[translation]
13006-CVGroup_CommonSkill-1 = "一定會讓你嚇一跳！"
13006-CVGroup_ExSkill_1-1 = "鏘～開始放煙火吧！"
13006-CVGroup_ExSkill_2-1 = "令人怦然心動的時間到囉！"
13006-CVGroup_ExSkill_3-1 = "來，要上囉～！"
13006-CVGroup_ExSkill_Level_1-1 = "看招～蹦！\n啊哈哈哈哈！真有趣。"
13006-CVGroup_ExSkill_Level_2-1 = "呀哈哈哈！像爆米花一樣！"
13006-CVGroup_ExSkill_Level_3-1 = "盡情發射就會……\n爆！炸！開！來！"
13006-CVGroup_Growup_1-1 = "很好！\n一點一點回應老師的期待吧～！"
13006-CVGroup_Growup_2-1 = "怎麼樣呀？變得更想珍惜我了嗎？"
13006-CVGroup_Growup_3-1 = "咯呵呵呵，感覺變得更強了～"
13006-CVGroup_Growup_4-1 = "這麼珍惜我就代表……\n對我！抱有愛意對吧～！沒錯吧？"
13006-CVGroup_Relationship_Up_1-1 = "只要跟老師待在一起，總感覺比平時更開心。\n雖然不知道理由就是了。"
13006-CVGroup_Relationship_Up_2-1 = "下次要不要換我向老師提出請求呢～"
13006-CVGroup_Relationship_Up_3-1 = "咯呵呵～真想衝過去緊緊抱著呢。"
13006-CVGroup_Relationship_Up_4-1 = "本來以為只是因為開心才想待在一起。\n不過……並不是那樣。呀哈。"
13006-CVGroup_Battle_Buffed_1-1 = "啊哈，謝謝。"
13006-CVGroup_Battle_Defense_1-1 = "沒用沒用～"
13006-CVGroup_Battle_In_1-1 = "嗯，總之開心地出發吧！"
13006-CVGroup_Battle_In_2-1 = "好～開始執行委託吧！"
13006-CVGroup_Battle_Move_1-1 = "呀哈哈，真開心～"
13006-CVGroup_Battle_Move_2-1 = "這邊會有什麼呢？"
13006-CVGroup_Battle_Recovery_1-1 = "啊哈哈，謝謝～！"
13006-CVGroup_Battle_TacticalAction_1-1 = "要上囉～"
13006-CVGroup_Battle_Victory_1-1 = "轉圈圈～真好玩！"
13006-CVGroup_Battle_Victory_2-1 = "鏘鏘～！勝利勝利！"
13006-CVGroup_Formation_In_1-1 = "馬上過去！"
13006-CVGroup_Formation_In_2-1 = "委託的時間，開始囉！"
13006-CVGroup_Formation_Select-1 = "咯呵呵，果然需要我吧？"
13006-CVGroup_Tactic_In_1-1 = "哇～！來開心地玩樂吧？"
13006-CVGroup_Tactic_In_2-1 = "這傢伙？總之先解決掉吧～"
13006-CVGroup_Tactic_Victory_1-1 = "已經結束了對吧？老師！\n快點去玩吧，去玩！"
13006-CVGroup_Tactic_Victory_2-1 = "咯呵呵呵……真開心。"
