[translation]
13013-CVGroup_Battle_Buffed_1-1 = "ขะ... ขอบคุณค่ะ!"
13013-CVGroup_Battle_Covered_1-1 = "ฉันจะไปซ่อนค่ะ!"
13013-CVGroup_Battle_Defense_1-1 = "มะ... ไม่มีอะไรค่ะ!"
13013-CVGroup_Battle_In_1-1 = "มุ่งไปข้างหน้า... เหมือนตัวเอกในนิยาย!"
13013-CVGroup_Battle_In_2-1 = "ไม่เสียใจ... เหมือนตัวเอกในการ์ตูน!"
13013-CVGroup_Battle_Move_1-1 = "ไปละค่ะ!"
13013-CVGroup_Battle_Move_2-1 = "สถานที่ต่อไป... คือที่ไหนคะ?"
13013-CVGroup_Battle_Recovery_1-1 = "ขอบคุณนะคะ... ฉันมีแรงแล้วค่ะ!"
13013-CVGroup_Battle_TacticalAction_1-1 = "ฉันจะย้ายที่ค่ะ!"
13013-CVGroup_Battle_Victory_1-1 = "แหะๆ... รู้สึกเหมือนเจอหนังสือลับเลยค่ะ"
13013-CVGroup_Battle_Victory_2-1 = "ความรู้คือพลัง... ฉันจึงต้องปกป้องค่ะ"
13013-CVGroup_CommonSkill-1 = "ตรงนี้อ่านกี่รอบก็... แหะๆๆ..."
13013-CVGroup_ExSkill_1-1 = "ตอนอยู่ในห้องสมุด ต้องเงียบๆ...!"
13013-CVGroup_ExSkill_2-1 = "มันรบกวนการอ่านหนังสือนะคะ...!"
13013-CVGroup_ExSkill_3-1 = "กรุณาอย่าส่งเสียงดังนะคะ...!"
13013-CVGroup_ExSkill_Level_1-1 = "เบาๆ สิคะ...!"
13013-CVGroup_ExSkill_Level_2-1 = "เดี๋ยวโดนลงโทษนะคะ...!"
13013-CVGroup_ExSkill_Level_3-1 = "จริงๆ เลย ทำเกินไปแล้วนะคะ...!"
13013-CVGroup_Formation_In_1-1 = "ถ้าฉันช่วยคุณครูได้ละก็..."
13013-CVGroup_Formation_In_2-1 = "คะ... ค่ะ! วางใจฉันได้เลยค่ะ...!"
13013-CVGroup_Formation_Select-1 = "อ๊ะ คุณครูก็ลองอ่านดูมั้ยคะ?\nนี่เป็นหนังสือเล่มโปรดของฉันเลยค่ะ!"
13013-CVGroup_Growup_1-1 = "คุณครู! ดูสิคะ...!\nฉันพัฒนาขึ้นแล้วค่ะ!"
13013-CVGroup_Growup_2-1 = "ขอบคุณนะคะ คุณครู\nทั้งหมดนี้ต้องขอบคุณคุณครูเลยค่ะ!"
13013-CVGroup_Growup_3-1 = "ความรู้สึกตอนนี้... ถึงจะอธิบายเป็นคำพูดไม่ได้...\nแต่มันคล้ายกับตอนฉันเจอหนังสือที่ไม่ตีพิมพ์แล้วที่ตามหาอยู่ค่ะ..."
13013-CVGroup_Growup_4-1 = "การก้าวไปข้างหน้า... เป็นเรื่องสนุกแบบนี้เองสินะคะ\nแหะๆๆ... ดีใจจังเลยค่ะ"
13013-CVGroup_Relationship_Up_1-1 = "ฉันโชคดีจังเลยค่ะที่ได้เจอคุณครู\nเพราะถ้าไม่เป็นอย่างนั้น... แน่นอนว่าฉันคง..."
13013-CVGroup_Relationship_Up_2-1 = "ในตอนแบบนี้ ถ้าเป็นในการ์ตูนเรื่องนั้นน่ะ... แหะๆๆ...\nเฮือก?! มะ... ไม่นะคะ! ฉันยังไม่ได้คิดอะไรเลยค่ะ!"
13013-CVGroup_Relationship_Up_3-1 = "ปกติคุณครูชอบอ่านหนังสือแบบไหนคะ...? ฉันจะหาให้เองค่ะ! \nเอ่อ... แต่แค่ในขอบเขตที่ฉันหาได้นะคะ"
13013-CVGroup_Relationship_Up_4-1 = "ถ้าฉันได้อยู่กับคุณครู... ฉันจะรู้สึกมีพลังแปลกๆ ค่ะ\nถ้าเป็นตอนนี้ ฉันน่าจะทำได้หมดทุกอย่างเลยค่ะ...!"
13013-CVGroup_Tactic_In_1-1 = "จะเริ่มละนะคะ"
13013-CVGroup_Tactic_In_2-1 = "ขอให้ทุกอย่างเป็นไปได้ดีด้วยเถอะ"
13013-CVGroup_Tactic_Victory_1-1 = "ฮู่ว โล่งอกไปทีนะคะ..."
13013-CVGroup_Tactic_Victory_2-1 = "ต้องขอบคุณคุณครูที่อยู่ด้วยกันนะคะ..."
