[translation]
13014-CVGroup_Battle_Buffed_1-1 = "Mm! Perfect timing!"
13014-CVGroup_Battle_Covered_1-1 = "Don't you dare!"
13014-CVGroup_Battle_Defense_1-1 = "Haha! Slow!"
13014-CVGroup_Battle_In_1-1 = "Time for some youth activities, everyone!"
13014-CVGroup_Battle_In_2-1 = "Let's play in the water!"
13014-CVGroup_Battle_Move_1-1 = "That's next?"
13014-CVGroup_Battle_Move_2-1 = "Follow me!"
13014-CVGroup_Battle_Recovery_1-1 = "I'm overflowing with energy!"
13014-CVGroup_Battle_TacticalAction_1-1 = "Moving!"
13014-CVGroup_Battle_Victory_1-1 = "Fufu, this is the power of youth!"
13014-CVGroup_Battle_Victory_2-1 = "Leave it to me next time as well!"
13014-CVGroup_CommonSkill-1 = "Youth injection!"
13014-CVGroup_ExSkill_1-1 = "Waves of youth, go!"
13014-CVGroup_ExSkill_2-1 = "Are you ready to enjoy summer?"
13014-CVGroup_ExSkill_3-1 = "Out of my way!"
13014-CVGroup_ExSkill_Level_1-1 = "Haha, take this!"
13014-CVGroup_ExSkill_Level_2-1 = "Get swept!"
13014-CVGroup_ExSkill_Level_3-1 = "Youth cannon, fire!"
13014-CVGroup_Formation_In_1-1 = "Mm! It's my turn!"
13014-CVGroup_Formation_In_2-1 = "I'll show you the power of youth!"
13014-CVGroup_Formation_Select-1 = "Okay! Whatever it may be, you can count on me!"
13014-CVGroup_Growup_1-1 = "Th-Thank you, Mentor. I'm getting stronger thanks to you. Heehee."
13014-CVGroup_Growup_2-1 = "I feel even more youthful now! Let's do some youth activities together, Mentor!"
13014-CVGroup_Growup_3-1 = "Oh! I feel even stronger now. It's thanks to the training we've done, Mentor!"
13014-CVGroup_Growup_4-1 = "I feel like I've matured through the waves of life... This is also part of youth, right?"
13014-CVGroup_Relationship_Up_1-1 = "Ugh, how should I express this gratitude? I feel bad, always being on the receiving end."
13014-CVGroup_Relationship_Up_2-1 = "Wh-When I'm with you, Mentor, my heart feels tight for some reason. I think this feeling is— Gah! I have no idea!"
13014-CVGroup_Relationship_Up_3-1 = "This is a representation of your feelings... Then, one day, I too...!"
13014-CVGroup_Relationship_Up_4-1 = "Y-You want to do youth activities...? I'd like that too, w-with just us two!"
13014-CVGroup_Tactic_In_1-1 = "I'll show you the path to victory!"
13014-CVGroup_Tactic_In_2-1 = "I'm stronger than usual today!"
13014-CVGroup_Tactic_Victory_1-1 = "Aah, great direction, Mentor."
13014-CVGroup_Tactic_Victory_2-1 = "Huh? It's over? I've still got more in me!"
