[translation]
16009-CVGroup_Battle_Buffed_1-1 = "Ooh, well, I don't NOT feel stronger..."
16009-CVGroup_Battle_Defense_1-1 = "Aha, that kind of thing won't work!"
16009-CVGroup_Battle_In_1-1 = "Hm, hmm! Okay. Commence! Mission!"
16009-CVGroup_Battle_In_2-1 = "Umm, l-let's give it a try!"
16009-CVGroup_Battle_Move_1-1 = "Okay, let's go to the next one!"
16009-CVGroup_Battle_Move_2-1 = "Ugh, is it not over yet?"
16009-CVGroup_Battle_Recovery_1-1 = "Thank you for the help!"
16009-CVGroup_Battle_TacticalAction_1-1 = "Shubababa!"
16009-CVGroup_Battle_Victory_1-1 = "Behold, the power of the Ninjutsu Research Club!"
16009-CVGroup_Battle_Victory_2-1 = "Yeah! As expected, there's no blind spot to Michiru-Style Ninjutsu!"
16009-CVGroup_CommonSkill-1 = "I must recover my willpower with ninja merch first..."
16009-CVGroup_ExSkill_1-1 = "M-Michiru-Style Ninjutsu!"
16009-CVGroup_ExSkill_2-1 = "F-Fire release technique! I'll show you!"
16009-CVGroup_ExSkill_3-1 = "D-Don't underestimate the president of the Ninjutsu Research Cluuub!"
16009-CVGroup_ExSkill_Level_1-1 = "Whoa, hot!"
16009-CVGroup_ExSkill_Level_2-1 = "Ninjutsu! Ah, hot, hot, hot!"
16009-CVGroup_ExSkill_Level_3-1 = "Augh!! Hot-hot-hot!"
16009-CVGroup_Formation_In_1-1 = "Kya! Th-That surprised me. Guess it's time to go, huh? All right!"
16009-CVGroup_Formation_In_2-1 = "Heehee! My turn! ...Wait—is it? It is...right?"
16009-CVGroup_Formation_Select-1 = "Domo, Sensei. Michiru here. What are your orders?"
16009-CVGroup_Growup_1-1 = "Huh?! Is this really for me?! Wow, you really have an eye for talent, Sensei... I guess? Nyahahaha!"
16009-CVGroup_Growup_2-1 = "Oh! I got even stronger!"
16009-CVGroup_Growup_3-1 = "Well, um... Th-Thank you...?"
16009-CVGroup_Growup_4-1 = "Heehee! I'm finally here! And to live up to your expectations, I will work as if I have dozens of arms and legs!"
16009-CVGroup_Relationship_Up_1-1 = "Wh-Whoa! I need space, please! All this closeness is bad for my heart..."
16009-CVGroup_Relationship_Up_2-1 = "When I'm with you, Sensei... I have this weird feeling like I can do anything in the world..."
16009-CVGroup_Relationship_Up_3-1 = "Whoa! What's with the close up?! Is this a prank?! Where's the hidden camera?! I mean, I'm not complaining, but..."
16009-CVGroup_Relationship_Up_4-1 = "Wait—that's too close... Maybe I should...? Yeah, I can use my charms to—No! I can't do that! It's way too embarrassing!"
16009-CVGroup_Tactic_In_1-1 = "Ninjutsu Research Club, onward!"
16009-CVGroup_Tactic_In_2-1 = "Get ready! I'll show you what a real ninja is like!"
16009-CVGroup_Tactic_Victory_1-1 = "Mission complete! Boy, that was cool!"
16009-CVGroup_Tactic_Victory_2-1 = "This is nothing to the Ninjutsu Research Club! Easy peasy!"
