[translation]
16001-CVGroup_Battle_Buffed_1-1 = "Ah, it feels nice!"
16001-CVGroup_Battle_Covered_1-1 = "Heehee, what a thrill!"
16001-CVGroup_Battle_Defense_1-1 = "Ahaha, that doesn't hurt at all!"
16001-CVGroup_Battle_In_1-1 = "Everyone, battle formation! Let's do this in style!"
16001-CVGroup_Battle_In_2-1 = "I'll show you the power of a C&C agent!"
16001-CVGroup_Battle_Move_1-1 = "Cleaning is done! ♪ Let's move on!"
16001-CVGroup_Battle_Move_2-1 = "Yup, all clear! It's clean now! ♪"
16001-CVGroup_Battle_Recovery_1-1 = "This is the best! I like it!"
16001-CVGroup_Battle_TacticalAction_1-1 = "Heehee, okay, next! ♪"
16001-CVGroup_Battle_Victory_1-1 = "Heave-ho. I've warmed up a bit! Huh? Heehee."
16001-CVGroup_Battle_Victory_2-1 = "Heehee. That was amazing. ...Oh, did you just see that?"
16001-CVGroup_CommonSkill-1 = "Brace yourselves!"
16001-CVGroup_ExSkill_1-1 = "Asuna! On the way!"
16001-CVGroup_ExSkill_2-1 = "Heehee. That won't hurt me at all!"
16001-CVGroup_ExSkill_3-1 = "Not sure how it's going to turn out. But let's do this!"
16001-CVGroup_ExSkill_Level_1-1 = "No one can stop me now!"
16001-CVGroup_ExSkill_Level_2-1 = "It's showtime!"
16001-CVGroup_ExSkill_Level_3-1 = "Asuna! Has arrived!"
16001-CVGroup_Formation_In_1-1 = "It's Asuna! Sensei! Looking forward to working with you!"
16001-CVGroup_Formation_In_2-1 = "Heehee! So you do need me after all!"
16001-CVGroup_Formation_Select-1 = "Yahoo! Leave it to me!"
16001-CVGroup_Growup_1-1 = "Now the real game begins!"
16001-CVGroup_Growup_2-1 = "Huh? For some reason, I feel smarter!"
16001-CVGroup_Growup_3-1 = "No matter what happens, I'll live up to Master's expectations!"
16001-CVGroup_Growup_4-1 = "Heehee. What do you want from me, Master? The current me will make it happen!"
16001-CVGroup_Relationship_Up_1-1 = "You've taken a lot of interest in me, Master!"
16001-CVGroup_Relationship_Up_2-1 = "If Master needs my service, I'll do anything, anywhere, at anytime!"
16001-CVGroup_Relationship_Up_3-1 = "It's fun to be with Master! Let's look forward to more good times ahead!"
16001-CVGroup_Relationship_Up_4-1 = "Master! Don't worry! I'll stay right with you!"
16001-CVGroup_Tactic_In_1-1 = "Call Sign Zero-One, Asuna! On my way!"
16001-CVGroup_Tactic_In_2-1 = "Now, then! Let's get started on the mission!"
16001-CVGroup_Tactic_Victory_1-1 = "This atmosphere is the best! "
16001-CVGroup_Tactic_Victory_2-1 = "Good work, everyone! That was great!"
