[translation]
16001-CVGroup_Battle_Buffed_1-1 = "아, 왠지 좋은 느낌!"
16001-CVGroup_Battle_Covered_1-1 = "후훗, 스릴만점이네~♩"
16001-CVGroup_Battle_Defense_1-1 = "아하, 전혀 안 아픈데?"
16001-CVGroup_Battle_In_1-1 = "전원! 전투 배치로! 화려하게 가볼까!"
16001-CVGroup_Battle_In_2-1 = "C&C 에이전트의 힘을 보여줄게!"
16001-CVGroup_Battle_Move_1-1 = "청소 완료~♪ 다음, 가자!"
16001-CVGroup_Battle_Move_2-1 = "응, 올 클리어! 깨끗해졌네♪"
16001-CVGroup_Battle_Recovery_1-1 = "최고야! 좋아해!"
16001-CVGroup_Battle_TacticalAction_1-1 = "후훗, 자, 다음다음♪"
16001-CVGroup_Battle_Victory_1-1 = "웃챠. 몸 좀 풀었네! 어머? 후훗."
16001-CVGroup_Battle_Victory_2-1 = "후훗~ 엄청 좋았어. 어라라. 봤어?"
16001-CVGroup_CommonSkill-1 = "각오하라구!"
16001-CVGroup_ExSkill_1-1 = "아스나! 갑니다!"
16001-CVGroup_ExSkill_2-1 = "후훗. 전혀 안 맞는다구~"
16001-CVGroup_ExSkill_3-1 = "어떻게 될지 모르지만. 해볼까나!"
16001-CVGroup_ExSkill_Level_1-1 = "아무도 날 막을 수 없어!"
16001-CVGroup_ExSkill_Level_2-1 = "잇츠 쇼타임!"
16001-CVGroup_ExSkill_Level_3-1 = "아스나! 여기에 등장!"
16001-CVGroup_Formation_In_1-1 = "아스나야! 선생님! 잘 부탁해!"
16001-CVGroup_Formation_In_2-1 = "후훗! 역시 내가 필요한 거구나!"
16001-CVGroup_Formation_Select-1 = "야호! 맡겨 달라구~"
16001-CVGroup_Growup_1-1 = "이제부터 진짜라구!"
16001-CVGroup_Growup_2-1 = "어라? 어쩐지 머리가 좋아진 기분이 들어!"
16001-CVGroup_Growup_3-1 = "주인님의 기대에 나는 절대로 어떤 일이 있더라도 부응할 테니까!"
16001-CVGroup_Growup_4-1 = "후훗. 주인님은 나에게 뭘 바라고 있어? 지금의 나라면 이루어 줄게!"
16001-CVGroup_Relationship_Up_1-1 = "주인님은 나에게 관심이 많구나!"
16001-CVGroup_Relationship_Up_2-1 = "주인님이 내 봉사를 필요로 한다면 언제든 어디서든 뭐든지 할게!"
16001-CVGroup_Relationship_Up_3-1 = "주인님과 있는 거, 즐거워! 앞으로도 나랑 재미있게 보내자!"
16001-CVGroup_Relationship_Up_4-1 = "주인님! 걱정하지 마! 나는 계속 주인님 곁에서 떨어지지 않을 테니까!"
16001-CVGroup_Tactic_In_1-1 = "콜사인 제로원, 아스나! 갑니다!"
16001-CVGroup_Tactic_In_2-1 = "자아~ 그럼 임무를 시작해볼까!"
16001-CVGroup_Tactic_Victory_1-1 = "분위기 최고!"
16001-CVGroup_Tactic_Victory_2-1 = "모두 수고했어! 엄청 좋았어!"
