[translation]
16008-CVGroup_Battle_Buffed_1-1 = "……與其給我，不如給其他人吧？\n好吧，姑且還是感謝你。"
16008-CVGroup_Battle_Covered_1-1 = "哎呀。"
16008-CVGroup_Battle_Defense_1-1 = "哈哈，挺癢的嘛。"
16008-CVGroup_Battle_In_1-1 = "那麼，就好好做吧。"
16008-CVGroup_Battle_In_2-1 = "不用那麼急沒關係，差不多就行了～"
16008-CVGroup_Battle_Move_1-1 = "……是這邊？"
16008-CVGroup_Battle_Move_2-1 = "……咦？這邊對嗎？"
16008-CVGroup_Battle_Recovery_1-1 = "哦哦，謝啦。"
16008-CVGroup_Battle_TacticalAction_1-1 = "這個區域的巡邏結束，就是這樣。"
16008-CVGroup_Battle_Victory_1-1 = "勞動之後的咖啡跟甜甜圈……最棒了。"
16008-CVGroup_Battle_Victory_2-1 = "啊～累死了累死了……得補充糖分才行。"
16008-CVGroup_CommonSkill-1 = "……中了就當運氣好吧。"
16008-CVGroup_ExSkill_1-1 = "休息時間到了～"
16008-CVGroup_ExSkill_2-1 = "不好意思。我休息完再繼續吧。"
16008-CVGroup_ExSkill_3-1 = "甜甜圈時間到了。"
16008-CVGroup_ExSkill_Level_1-1 = "無論面對什麼情況，都不能喪失餘裕。"
16008-CVGroup_ExSkill_Level_2-1 = "嚼嚼……真好吃。"
16008-CVGroup_ExSkill_Level_3-1 = "也想來點咖啡啊～"
16008-CVGroup_Formation_In_1-1 = "……我說，有必要連我都去嗎？"
16008-CVGroup_Formation_In_2-1 = "真麻煩……"
16008-CVGroup_Formation_Select-1 = "好睏……"
16008-CVGroup_Growup_1-1 = "這個，要給我……？\n……為什麼？沒有給錯人嗎？"
16008-CVGroup_Growup_2-1 = "我其實覺得現在這樣就很夠了說……"
16008-CVGroup_Growup_3-1 = "好吧，老師的好意我就感激地收下吧。"
16008-CVGroup_Growup_4-1 = "要比現在更努力啊，唔嗯……\n甜甜圈之類的還有剩嗎？如果有的話應該勉強……"
16008-CVGroup_Relationship_Up_1-1 = "呵呵，老師要不要也跟我一起摸魚？"
16008-CVGroup_Relationship_Up_2-1 = "其實，我是不太喜歡休息被人打擾的……\n算了，老師的話也無所謂吧。"
16008-CVGroup_Relationship_Up_3-1 = "在這裡像這樣休息，總覺得很讓人安心啊～"
16008-CVGroup_Relationship_Up_4-1 = "老師，那個，啊……總之，要不要吃甜甜圈？"
16008-CVGroup_Tactic_In_1-1 = "咦？為什麼我是隊長……？"
16008-CVGroup_Tactic_In_2-1 = "……咦？我站前面……？你是認真的嗎？"
16008-CVGroup_Tactic_Victory_1-1 = "結束了？結束了對吧？\n好耶，收工收工。"
16008-CVGroup_Tactic_Victory_2-1 = "哎呀……沒想到真的會贏呢。"
