[translation]
16008-CVGroup_Battle_Buffed_1-1 = "ให้คนอื่นมากกว่าตัวเองเหรอ? ก็... ยังไงก็ขอบคุณนะคะ"
16008-CVGroup_Battle_Covered_1-1 = "ฮึบ"
16008-CVGroup_Battle_Defense_1-1 = "ฮ่าฮ่า จั๊กจี้นะ"
16008-CVGroup_Battle_In_1-1 = "เอาละ ไปด้วยความรู้สึกดีก็แล้วกัน"
16008-CVGroup_Battle_In_2-1 = "ไม่ต้องรีบร้อนก็ได้ ค่อยๆ ไปนะ~"
16008-CVGroup_Battle_Move_1-1 = "ทางนี้เหรอ...?"
16008-CVGroup_Battle_Move_2-1 = "เอ๋? ทางนี้ถูกมั้ยนะ...?"
16008-CVGroup_Battle_Recovery_1-1 = "โอ้ว ขอบคุณนะ"
16008-CVGroup_Battle_TacticalAction_1-1 = "ลาดตระเวนพื้นที่นี้เสร็จแล้วละ"
16008-CVGroup_Battle_Victory_1-1 = "กาแฟกับโดนัทหลังเลิกงาน... ยอดไปเลย"
16008-CVGroup_Battle_Victory_2-1 = "เฮ้อ เหนื่อยจัง เพลียร่างจัง... ต้องเติมน้ำตาลหน่อยแล้ว"
16008-CVGroup_CommonSkill-1 = "ถ้ายิงถูกก็ถือว่าโชคดีละนะ"
16008-CVGroup_ExSkill_1-1 = "ได้เวลาพักแล้ว~"
16008-CVGroup_ExSkill_2-1 = "โทษทีนะ มาพักกันหน่อยดีกว่า~"
16008-CVGroup_ExSkill_3-1 = "ได้เวลาโดนัทไทม์"
16008-CVGroup_ExSkill_Level_1-1 = "ไม่ว่าจะสถานการณ์ไหน ก็ต้องชิลเข้าไว้นะ"
16008-CVGroup_ExSkill_Level_2-1 = "ง่ำๆ... อร่อยจัง"
16008-CVGroup_ExSkill_Level_3-1 = "ถ้ากาแฟอร่อยด้วยก็ดีน่ะสิ"
16008-CVGroup_Formation_In_1-1 = "นี่... ฉันจำเป็นต้องไปด้วยเหรอ?"
16008-CVGroup_Formation_In_2-1 = "ขี้เกียจอะ..."
16008-CVGroup_Formation_Select-1 = "ง่วงจัง..."
16008-CVGroup_Growup_1-1 = "อันนี้ให้ฉันเหรอ?\nทำไมล่ะ...? ให้ผิดคนหรือเปล่า?"
16008-CVGroup_Growup_2-1 = "สำหรับฉัน ตอนนี้ก็โอเคแล้วนะ..."
16008-CVGroup_Growup_3-1 = "ฉันจะรับน้ำใจของครูไว้อย่างซาบซึ้งแล้วกัน"
16008-CVGroup_Growup_4-1 = "ถ้าให้หนักกว่านี้น่ะ อืม...\nมีโดนัทเหลือมั้ย? ถ้ามี ฉันก็น่าจะทำได้..."
16008-CVGroup_Relationship_Up_1-1 = "ฮุฮุ ครูก็มาโดดงานกับฉันมั้ย?"
16008-CVGroup_Relationship_Up_2-1 = "ที่จริงฉันไม่ชอบถูกรบกวนการพักผ่อน...\nแต่ถ้าเป็นครูก็ไม่เป็นไรหรอก"
16008-CVGroup_Relationship_Up_3-1 = "การพักผ่อนที่นี่แบบนี้ ก็สบายใจจังเลยนะ~"
16008-CVGroup_Relationship_Up_4-1 = "ครู เอ่อ... คือว่า... อ่า... กินโดนัทก่อนมั้ย?"
16008-CVGroup_Tactic_In_1-1 = "หืม? ทำไมให้ฉันเป็นหัวหน้าล่ะ...?"
16008-CVGroup_Tactic_In_2-1 = "หืม...? ให้ฉันไปก่อนเหรอ? จริงเหรอ?"
16008-CVGroup_Tactic_Victory_1-1 = "เสร็จแล้วใช่มั้ย? เสร็จหมดแล้วเนอะ?\nดีละ กลับกันเถอะ กลับๆ"
16008-CVGroup_Tactic_Victory_2-1 = "เฮ้อ... ไม่คิดเลยจริงๆ นะว่าจะชนะ"
