[translation]
16018-CVGroup_Battle_Buffed_1-1 = "哎呀，真不好意思。"
16018-CVGroup_Battle_Covered_1-1 = "想開槍就開吧！"
16018-CVGroup_Battle_Defense_1-1 = "頭盔可不是裝飾品哦！"
16018-CVGroup_Battle_In_1-1 = "我奉陪到底！"
16018-CVGroup_Battle_In_2-1 = "照順序上吧！我可沒空奉陪啊！"
16018-CVGroup_Battle_Move_1-1 = "閃開閃開！"
16018-CVGroup_Battle_Move_2-1 = "速速搞定吧！"
16018-CVGroup_Battle_Recovery_1-1 = "呼～就差一點呢……謝謝！"
16018-CVGroup_Battle_TacticalAction_1-1 = "往那邊走吧！"
16018-CVGroup_Battle_Victory_1-1 = "下次記得把同伴也帶來啊！"
16018-CVGroup_Battle_Victory_2-1 = "嗯，工作量也跟我們差不多吧？"
16018-CVGroup_CommonSkill-1 = "上吧！給我咬斷他！"
16018-CVGroup_ExSkill_1-1 = "頭盔團！準備好了嗎？"
16018-CVGroup_ExSkill_2-1 = "給我仔細看清楚哦！"
16018-CVGroup_ExSkill_3-1 = "頭盔團也被看扁了呢，挺有趣的嘛！！"
16018-CVGroup_ExSkill_Level_1-1 = "上肩投球！"
16018-CVGroup_ExSkill_Level_2-1 = "要上囉！咚哐──！"
16018-CVGroup_ExSkill_Level_3-1 = "俐落地解決吧！"
16018-CVGroup_ExSkill_4-1 = "頭盔團，突擊！"
16018-CVGroup_ExSkill_5-1 = "頭盔團！準備好了嗎？"
16018-CVGroup_ExSkill_6-1 = "打爛他們吧！"
16018-CVGroup_ExSkill_Level_4-1 = "可以把敵人揍得滿頭包！不過可別受傷了哦！"
16018-CVGroup_ExSkill_Level_5-1 = "不必手下留情，盡全力上吧！"
16018-CVGroup_ExSkill_Level_6-1 = "相信我就對了！"
16018-CVGroup_Formation_In_1-1 = "哼嗯，意思是可以盡情亂來對吧？"
16018-CVGroup_Formation_In_2-1 = "你們是我的同伴，感覺還真奇怪呢……啊哈哈……"
16018-CVGroup_Formation_Select-1 = "喂，快放我下來啦！旁邊還有人耶！"
16018-CVGroup_Growup_1-1 = "咦，要把這給我？\n這樣啊……謝啦！"
16018-CVGroup_Growup_2-1 = "真的要給我嗎……？之後說要還也不接受哦！"
16018-CVGroup_Growup_3-1 = "把我變得這麼強是想做什麼啊？\n要是變得無法挽回，我可不管哦！"
16018-CVGroup_Growup_4-1 = "呵呵，成長真不錯呢♪"
16018-CVGroup_Relationship_Up_1-1 = "等等……我是問題兒童這種事，你應該知道吧？"
16018-CVGroup_Relationship_Up_2-1 = "別太親近我哦……我會有點困擾。"
16018-CVGroup_Relationship_Up_3-1 = "被當成學生對待，已經相隔太久了……真是的……"
16018-CVGroup_Relationship_Up_4-1 = "喂！旁邊還有人啦！現在不要摸我的頭！"
16018-CVGroup_Tactic_In_1-1 = "交給我吧！"
16018-CVGroup_Tactic_In_2-1 = "算是輕鬆的暖身運動吧。"
16018-CVGroup_Tactic_Victory_1-1 = "少囂張了！給我滾遠一點！"
16018-CVGroup_Tactic_Victory_2-1 = "這是什麼，完全沒有手感嘛。"
