[translation]
16014-CVGroup_Battle_Buffed_1-1 = "헤헤, 고마워!"
16014-CVGroup_Battle_Covered_1-1 = "쉬잇! 숨을게!"
16014-CVGroup_Battle_Defense_1-1 = "어라? 이제 안 아파!"
16014-CVGroup_Battle_In_1-1 = "끝나고 선생님이랑 놀아야지~"
16014-CVGroup_Battle_In_2-1 = "이부키가 지나간다~!"
16014-CVGroup_Battle_Move_1-1 = "전진~"
16014-CVGroup_Battle_Move_2-1 = "와! 재밌겠다~!"
16014-CVGroup_Battle_Recovery_1-1 = "에헤헤, 고마워!"
16014-CVGroup_Battle_TacticalAction_1-1 = "이쪽이야~"
16014-CVGroup_Battle_Victory_1-1 = "있잖아있잖아! 이부키, 이겼어!"
16014-CVGroup_Battle_Victory_2-1 = "이겼어! 이부키, 잘했어?"
16014-CVGroup_CommonSkill-1 = "앗! 나쁜 사람이다!"
16014-CVGroup_ExSkill_1-1 = "좋아하는 거, 가~득~"
16014-CVGroup_ExSkill_2-1 = "이렇게, 이렇게 해서……짠!"
16014-CVGroup_ExSkill_3-1 = "됐다아!"
16014-CVGroup_ExSkill_Level_1-1 = "이거, 이부키가 그린 거야!"
16014-CVGroup_ExSkill_Level_2-1 = "다 같이 그림 그리자!"
16014-CVGroup_ExSkill_Level_3-1 = "이 색을 사용해서~"
16014-CVGroup_Formation_In_1-1 = "응! 이부키도 도와줄게!"
16014-CVGroup_Formation_In_2-1 = "에헤헤, 알았어!"
16014-CVGroup_Formation_Select-1 = "와아~ 이부키랑 놀아주는 거야~?"
16014-CVGroup_Growup_1-1 = "선생님 선생님! 이부키, 키가 큰 것 같아!"
16014-CVGroup_Growup_2-1 = "고마워 선생님! 앞으로도 많이 도와줄게!"
16014-CVGroup_Growup_3-1 = "이부키도 선배들처럼 커지고 싶어!"
16014-CVGroup_Growup_4-1 = "고마워 선생님! 여기! 답례로 이부키의 푸딩, 줄게!"
16014-CVGroup_Relationship_Up_1-1 = "…이부키의 비밀, 하나 알려줄께….\n있잖아, 이부키는! 선생님이랑 같이 있으면 정말 즐거워! 둘만의 비밀이야!"
16014-CVGroup_Relationship_Up_2-1 = "헤헤, 에헤헷...기뻐! 이부키, 더 착한 아이가 될게!"
16014-CVGroup_Relationship_Up_3-1 = "이부키도, 선생님같은 멋진 어른이 되고 싶어~!"
16014-CVGroup_Relationship_Up_4-1 = "이부키는 말야, 선생님 생각하고 있었어!\n선생님도 이부키 생각하고 있었어?\n에헤헷 이부키랑 선생님은 마음이 통하나봐!"
16014-CVGroup_Tactic_In_1-1 = "이부키, 갑니다!"
16014-CVGroup_Tactic_In_2-1 = "가르쳐 준 대로 열심히 할게!"
16014-CVGroup_Tactic_Victory_1-1 = "봐봐! 이부키, 이겼어~!"
16014-CVGroup_Tactic_Victory_2-1 = "이제 선생님이랑 놀 수 있는 거야?"
