[translation]
20009-CVGroup_CommonSkill-1 = "이 몸의 눈에서 벗어날 수 있을거라 생각했느냐!"
20009-CVGroup_ExSkill_1-1 = "이렇게 된 이상 섬멸이다!"
20009-CVGroup_ExSkill_2-1 = "숙청의 시간이다!"
20009-CVGroup_ExSkill_3-1 = "가라, 숙청군 1호!"
20009-CVGroup_ExSkill_Level_1-1 = "불순분자들을 모조리 쓸어버리는거야!"
20009-CVGroup_ExSkill_Level_2-1 = "위대한 수염의 이름으로!"
20009-CVGroup_ExSkill_Level_3-1 = "이 위력, 똑똑히 맛보거라!"
20009-CVGroup_Formation_In_1-1 = "후후, 이 몸에게 맡기거라."
20009-CVGroup_Formation_In_2-1 = "이 몸의 차례로군!"
20009-CVGroup_Formation_Select-1 = "좋아! 이대로 온천까지 진격이다!"
20009-CVGroup_Growup_1-1 = "후후. 보았는가, 콤라드? 눈이 휘둥그레질만한 이 몸의 성장을……!"
20009-CVGroup_Growup_2-1 = "충분한 휴식 또한 성장을 위한 지름길이지!"
20009-CVGroup_Growup_3-1 = "이 몸에게 어울리는, 좀 더 멋진 수염을 준비해야겠어."
20009-CVGroup_Growup_4-1 = "오오……! 이 몸의 성장 속도는 나 자신도 두렵게 느껴질 정도구나!"
20009-CVGroup_Relationship_Up_1-1 = "콤라드와 함께라면, 이번 겨울 휴가도 분명 최고일 거야!"
20009-CVGroup_Relationship_Up_2-1 = "……콤라드는 나를 배신하면 안 돼?"
20009-CVGroup_Relationship_Up_3-1 = "좋아, 콤라드에게 특별 훈장을 수여하지!"
20009-CVGroup_Relationship_Up_4-1 = "에헤헤…… 고마워. 콤라드."
