[translation]
20003-CVGroup_CommonSkill-1 = "剩下一個人。"
20003-CVGroup_ExSkill_1-1 = "裝填子彈，瞄準完畢。開始射擊。"
20003-CVGroup_ExSkill_2-1 = "已確認目標。進行排除。"
20003-CVGroup_ExSkill_3-1 = "目標已捕捉……距離十分充足。"
20003-CVGroup_ExSkill_Level_1-1 = "Fire。"
20003-CVGroup_ExSkill_Level_2-1 = "命中了。"
20003-CVGroup_ExSkill_Level_3-1 = "擊中。"
20003-CVGroup_Formation_In_1-1 = "我會盡力而為。"
20003-CVGroup_Formation_In_2-1 = "我會回應你的期待。"
20003-CVGroup_Growup_1-1 = "感謝支援。"
20003-CVGroup_Growup_2-1 = "能感受到強大的力量呢。"
20003-CVGroup_Growup_3-1 = "呼……戰意燃燒起來了。"
20003-CVGroup_Growup_4-1 = "我會為了正義而努力。"
20003-CVGroup_Relationship_Up_1-1 = "老師所擁有的正義……肯定是非常帥氣的正義吧。"
20003-CVGroup_Relationship_Up_2-1 = "假如老師犯下惡行的時候……\n不，那不可能。因為老師就是正義的化身。"
20003-CVGroup_Relationship_Up_3-1 = "跟老師一起度過的時間，總覺得比平時還短……"
20003-CVGroup_Relationship_Up_4-1 = "我很喜歡，真的……\n我，我指的當然是正義！"
