[translation]
20010-CVGroup_CommonSkill-1 = "這位客人，有甚麼讓您困擾的事嗎？"
20010-CVGroup_ExSkill_1-1 = "這是227號溫泉浴場的會席料理！"
20010-CVGroup_ExSkill_2-1 = "這是我們自豪的料理！"
20010-CVGroup_ExSkill_3-1 = "放了很多豪華的食材！"
20010-CVGroup_ExSkill_Level_1-1 = "我會從肚子餓了的客人開始，按照順序發放！"
20010-CVGroup_ExSkill_Level_2-1 = "料理有很多！"
20010-CVGroup_ExSkill_Level_3-1 = "來，請慢慢享用！"
20010-CVGroup_Summon_Retreat_01-1 = "今天的營業就到此為止！"
20010-CVGroup_Summon_Retreat_02-1 = "不，不好意思！材料都用光了！"
20010-CVGroup_Formation_In_1-1 = "我會展現女將的真本事！"
20010-CVGroup_Formation_In_2-1 = "我，我會全力侍奉！"
20010-CVGroup_Formation_Select-1 = "剛洗完澡的老師……真是非常……咯呵呵……"
20010-CVGroup_Growup_1-1 = "呵呵，老師覺得怎麼樣呀？\n我的這股威嚴！"
20010-CVGroup_Growup_2-1 = "這樣一來，我也成為出色的女將了嗎？"
20010-CVGroup_Growup_3-1 = "為了溫泉浴場，得更努力才行……！"
20010-CVGroup_Growup_4-1 = "您平日對我們227號特別──\n更正，是對227號溫泉浴場的支援，真的非常感謝！"
20010-CVGroup_Relationship_Up_1-1 = "我隨時，都守望著老師唷……\n是的，就是隨時……！"
20010-CVGroup_Relationship_Up_2-1 = "呵呵，今天老師的神情也很閃亮呢，"
20010-CVGroup_Relationship_Up_3-1 = "喂了老師，我隨時都把最好的房間空著！"
20010-CVGroup_Relationship_Up_4-1 = "畢竟老師是我們溫泉浴場的VIP客人啊！"
