[translation]
20016-CVGroup_CommonSkill-1 = "공격."
20016-CVGroup_ExSkill_1-1 = "하아, 그러니까, 초무적철갑 토라마루… 출격합니다~"
20016-CVGroup_ExSkill_2-1 = "하아, 순찰이라도 할까요. 토라마루."
20016-CVGroup_ExSkill_3-1 = "초무적철갑 토라마루, 전진합니다. ……이름 부끄럽네요."
20016-CVGroup_ExSkill_Level_1-1 = "네네. 갑니다."
20016-CVGroup_ExSkill_Level_2-1 = "알겠다니까요. 정말……."
20016-CVGroup_ExSkill_Level_3-1 = "어쩔 수 없네요……."
20016-CVGroup_Formation_In_1-1 = "아…. 네, 알겠습니다."
20016-CVGroup_Formation_In_2-1 = "예상은 했습니다만……. 하아."
20016-CVGroup_Formation_Select-1 = "오? 저는 열외인가요?"
20016-CVGroup_Growup_1-1 = "농땡이, 치게 내버려 두진 않을 거 같네요……. 어쩔 수 없죠."
20016-CVGroup_Growup_2-1 = "……뭔가요. 제게 흥미라도?"
20016-CVGroup_Growup_3-1 = "헤에, 이렇게까지 해주시는 건가요?"
20016-CVGroup_Growup_4-1 = "감사합니다……. 뭔가요, 평범하게 감사 인사 정도는 한다구요."
20016-CVGroup_Relationship_Up_1-1 = "후후, 뭐어, 파장이 맞지 않는 건 아닌 모양이네요."
20016-CVGroup_Relationship_Up_2-1 = "뭐… 의지해주시는 게 싫지는 않습니다만……."
20016-CVGroup_Relationship_Up_3-1 = "그런 식의 적극적인 어프로치는, 조금……."
20016-CVGroup_Relationship_Up_4-1 = "마음이 통한다는 건, 이런 걸까요?"
