[translation]
20010-CVGroup_CommonSkill-1 = "손님, 어딘가 불편한 곳은 없으신가요?"
20010-CVGroup_ExSkill_1-1 = "227호 온천장의 가이세키 정식입니다!"
20010-CVGroup_ExSkill_2-1 = "자랑하는 요리입니다!"
20010-CVGroup_ExSkill_3-1 = "비싼 재료들로 잔뜩 준비했어요!"
20010-CVGroup_ExSkill_Level_1-1 = "배고프신 분부터 순서대로 나눠드릴게요!"
20010-CVGroup_ExSkill_Level_2-1 = "요리는 충분히 있으니까요!"
20010-CVGroup_ExSkill_Level_3-1 = "부디, 느긋하게 즐겨주세요!"
20010-CVGroup_Summon_Retreat_01-1 = "오늘의 영업은 이것으로 종료입니다!"
20010-CVGroup_Summon_Retreat_02-1 = "죄, 죄송합니다! 재료가 모두 떨어졌어요!"
20010-CVGroup_Formation_In_1-1 = "여주인의 진수, 보여드리겠습니다!"
20010-CVGroup_Formation_In_2-1 = "오, 온 힘을 다해 모실게요!"
20010-CVGroup_Formation_Select-1 = "목욕 후의 선생님을 이렇게 지켜보는 것도 꽤나…… 후후후……"
20010-CVGroup_Growup_1-1 = "후훗, 선생님 어떠신가요? 저의 이 관록이 붙은 모습!"
20010-CVGroup_Growup_2-1 = "이걸로 저도 훌륭한 여주인이 될 수 있을까요?"
20010-CVGroup_Growup_3-1 = "온천장을 위해서라도 좀 더 노력하지 않으면……!"
20010-CVGroup_Growup_4-1 = "언제나 저희 227호 특별반…….\n아니, 227호 온천장을 지원해주셔서 감사합니다!"
20010-CVGroup_Relationship_Up_1-1 = "언제나 선생님을 지켜보고 있으니까요. ……네. 언제나……!"
20010-CVGroup_Relationship_Up_2-1 = "헤헤, 오늘도 선생님의 얼굴은 눈부시네요."
20010-CVGroup_Relationship_Up_3-1 = "선생님을 위해 항상 제일 좋은 방은 비워두고 있으니까요!"
20010-CVGroup_Relationship_Up_4-1 = "선생님은 저희 온천장의 VVIP 손님이시니까요!"
