[translation]
20021-CVGroup_CommonSkill-1 = "치료가 필요한 분은 어디에 계신가요~?"
20021-CVGroup_ExSkill_1-1 = "모두를 위한 선물이에요!"
20021-CVGroup_ExSkill_2-1 = "오늘 하루는 제가 산타니까요!"
20021-CVGroup_ExSkill_3-1 = "모두에게 행복을 전해드릴게요!"
20021-CVGroup_ExSkill_Level_1-1 = "자, 선물 받으세요!"
20021-CVGroup_ExSkill_Level_2-1 = "받아주세요!"
20021-CVGroup_ExSkill_Level_3-1 = "마음에 드세요?"
20021-CVGroup_Formation_In_1-1 = "산타로서 열심히 할게요!"
20021-CVGroup_Formation_In_2-1 = "맡겨만 주세요!"
20021-CVGroup_Formation_Select-1 = "짜잔! 선생님을 위해 준비했어요!"
20021-CVGroup_Growup_1-1 = "산타할아버지는 정말 대단해요…….\n하지만 지금은 제가 산타니까, 진짜에 가까워질 수 있도록 노력할 거예요!"
20021-CVGroup_Growup_2-1 = "이 옷을 입은 이상 열심히 하겠습니다! 선생님도 도와주시겠어요?"
20021-CVGroup_Growup_3-1 = "진짜 산타는 될 수 없어도, 모두에게 행복을 전하고 싶어요!"
20021-CVGroup_Growup_4-1 = "언젠가 모두가 행복해지기를!"
20021-CVGroup_Relationship_Up_1-1 = "크리스마스에 중요한 것……? 그건 물론 사랑이죠!"
20021-CVGroup_Relationship_Up_2-1 = "선생님! 마하 2로 달리는 썰매에 관심 없으신가요?"
20021-CVGroup_Relationship_Up_3-1 = "지금의 저처럼, 모두가 행복해지기를."
20021-CVGroup_Relationship_Up_4-1 = "한 개만 선물을 받을수 있다면……\n저는 선생님과 함께 하는 시간이 좋아요!"
