[translation]
20028-CVGroup_CommonSkill-1 = "請收下吧！"
20028-CVGroup_ExSkill_1-1 = "風真舒服……啊！嗚啊啊……！？"
20028-CVGroup_ExSkill_2-1 = "風……呀啊！？請，請等一下！"
20028-CVGroup_ExSkill_3-1 = "哼哼～嗯……！？我，我的帽子……！"
20028-CVGroup_ExSkill_Level_1-1 = "請別輸給炎熱！"
20028-CVGroup_ExSkill_Level_2-1 = "要玩水嗎？"
20028-CVGroup_ExSkill_Level_3-1 = "說到夏天，就會想到這個呢！"
20028-CVGroup_Formation_In_1-1 = "是，需要我幫忙嗎？"
20028-CVGroup_Formation_In_2-1 = "該，該我出場了呢！我會加油的！"
20028-CVGroup_Formation_Select-1 = "這，這套泳裝……您覺得怎麼樣呢？"
20028-CVGroup_Growup_1-1 = "要，要把這個給我……！？\n真的，可以嗎……？"
20028-CVGroup_Growup_2-1 = "非常感謝您，老師！我會珍惜的。"
20028-CVGroup_Growup_3-1 = "我還不習慣受人恩惠……不過，我很開心。"
20028-CVGroup_Growup_4-1 = "我會更加努力的……！"
20028-CVGroup_Relationship_Up_1-1 = "嗚嗚……想不到感謝的話……"
20028-CVGroup_Relationship_Up_2-1 = "我，有確實幫上老師的忙嗎？"
20028-CVGroup_Relationship_Up_3-1 = "只要老師待在身邊，內心就會感到平靜……這是為什麼呢？"
20028-CVGroup_Relationship_Up_4-1 = "有什麼需要的話，請您儘管說哦……無論什麼都可以。"
