[translation]
20029-CVGroup_CommonSkill-1 = "請多吃一點哦。"
20029-CVGroup_ExSkill_1-1 = "嘿咻，嘿咻……\n老師，在這邊唷。"
20029-CVGroup_ExSkill_2-1 = "那麼，準備已經萬全……\n歡迎您的到來，老師。"
20029-CVGroup_ExSkill_3-1 = "真是美麗的大海呢……\n是的，已經恭候多時了。"
20029-CVGroup_ExSkill_Level_1-1 = "因為休息是很重要的。"
20029-CVGroup_ExSkill_Level_2-1 = "還請注意紫外線哦？"
20029-CVGroup_ExSkill_Level_3-1 = "大家，不介意的話請用。"
20029-CVGroup_Formation_In_1-1 = "是，老師。\n恭候多時了。"
20029-CVGroup_Formation_In_2-1 = "總覺得很期待呢……\n會有怎樣的夏天正等候著我們呢？"
20029-CVGroup_Growup_1-1 = "是夏日的修行呢……呵呵，真開心。"
20029-CVGroup_Growup_2-1 = "這……是修行的成果嗎？\n還是多虧了老師呢……？"
20029-CVGroup_Growup_3-1 = "多虧了老師的關照……\n我才能夠獲得如此成長。非常感謝您。"
20029-CVGroup_Growup_4-1 = "總覺得……非常期待。\n我，現在心情十分雀躍……也很幸福。"
20029-CVGroup_Relationship_Up_1-1 = "只要跟老師在一起……\n就有會發生好事的預感。"
20029-CVGroup_Relationship_Up_2-1 = "如果可以的話，真想在老師身後半步……\n哈嗚，要說出來真讓人害羞……"
20029-CVGroup_Relationship_Up_3-1 = "……真幸福。\n跟老師在一起的這段時光……"
20029-CVGroup_Relationship_Up_4-1 = "那個，老師……不，沒什麼。\n那個……請再稍等我一會。\n……再一會就行了。"
