[translation]
20036-CVGroup_CommonSkill-1 = "รับไปซะ!"
20036-CVGroup_ExSkill_1-1 = "ฮู่ว สนุกจัง... อ๊ะ อ๊า!?"
20036-CVGroup_ExSkill_2-1 = "คุณครู~! อ๊าย!?"
20036-CVGroup_ExSkill_3-1 = "ก็อาจจะไม่แย่... เท่าไรนะะะะ!?!?!?"
20036-CVGroup_ExSkill_Level_1-1 = "พลาดแล้ว ระวังนะ!!"
20036-CVGroup_ExSkill_Level_2-1 = "บินไปเลยยย!!"
20036-CVGroup_ExSkill_Level_3-1 = "หลบนะะะ!!"
20036-CVGroup_Formation_In_1-1 = "ไม่มีเวลามาลังเลแล้ว!"
20036-CVGroup_Formation_In_2-1 = "รีบๆ ไปกันเถอะ~!"
20036-CVGroup_Growup_1-1 = "เอ่อ... ฉันก็ชอบการเล่นสนุกหรอกนะ...\nแต่แบบนี้จะไม่เป็นไรจริงนะ...?"
20036-CVGroup_Growup_2-1 = "ดีละ ดีเลย~!\nครั้งนี้ฉันจะไม่ปฏิเสธเลยละ!"
20036-CVGroup_Growup_3-1 = "คุณครูก็อยากเล่นสนุกใช่มั้ยล่ะ?\nไม่ต้องพูด ฉันก็รู้น่า!"
20036-CVGroup_Growup_4-1 = "คิดจะจัดการแข่งขันปืนฉีดน้ำเหรอ?\nเข้าใจแล้ว! ฉันจะเก็บกวาดให้หมดเลย!"
20036-CVGroup_Relationship_Up_1-1 = "อืม ตอนนี้สนุกมากเลยละคุณครู"
20036-CVGroup_Relationship_Up_2-1 = "จะสนุกให้สุดเหวี่ยงเลย!\nถ้ามีเรื่องอะไร คุณครูก็มาบอกนะ!"
20036-CVGroup_Relationship_Up_3-1 = "ความรู้สึกแบบนี้... พอคิดดูแล้ว ก็เป็นครั้งแรกเลยละ"
20036-CVGroup_Relationship_Up_4-1 = "คะ... คุณครู เอ่อ... คือว่า...\nปะ... ไปว่ายน้ำ... ด้วยกันมั้ย...?"
