[translation]
20049-CVGroup_CommonSkill-1 = "호, 혹시나 해서 가져왔을 뿐이야!"
20049-CVGroup_ExSkill_1-1 = "어디…… 우왓?! 다행이야……"
20049-CVGroup_ExSkill_2-1 = "이러면…… 아앗?! 휴우……"
20049-CVGroup_ExSkill_3-1 = "다 됐나……? 안 돼! 무사했네……"
20049-CVGroup_ExSkill_Level_1-1 = "물놀이 시간."
20049-CVGroup_ExSkill_Level_2-1 = "물대포, 발사."
20049-CVGroup_ExSkill_Level_3-1 = "빠져 버리라고."
20049-CVGroup_Formation_In_1-1 = "바다……별로 재미없어."
20049-CVGroup_Formation_In_2-1 = "하아…… 책임져주는 거지?"
20049-CVGroup_Formation_Select-1 = "알았어……놀면 되는 거지?"
20049-CVGroup_Growup_1-1 = "딱히 즐기고 있는 게 아니야.\n선생님이 데려왔으니까, 책임지고 즐겁게 해 줘."
20049-CVGroup_Growup_2-1 = "날 이렇게 만든 건 선생님이잖아. ……제대로 끝까지 챙겨줘."
20049-CVGroup_Growup_3-1 = "이런 것도 나쁘지만은 않을지도…… ……거짓말이야, 잊어."
20049-CVGroup_Growup_4-1 = "뭘 힐끗힐끗 보는 거야……? 그러니까 즐기고 있는 게 아니라고."
20049-CVGroup_Relationship_Up_1-1 = "보지 마. 아니, 부끄러워하는 게 아니니까……!"
20049-CVGroup_Relationship_Up_2-1 = "알겠어……참. 이런 것도, 나쁘지 않네……자, 말했어."
20049-CVGroup_Relationship_Up_3-1 = "내일이……정말로 이렇게 나쁘지만은 않은 거라고 한다면……\n앞으로도, 계속 증명해 줘."
20049-CVGroup_Relationship_Up_4-1 = "나를 이렇게 만들어 놨으면서……. 책임질 생각 따위 없겠지.\n……'할 수 있는 거라면 뭐든 하겠다고'? 자, 자기가 무슨 소리를 하는 건지 알고 있어!?"
