[translation]
20051-CVGroup_CommonSkill-1 = "With love! And courage! And friendship power!"
20051-CVGroup_ExSkill_1-1 = "From feed ramp to chamber: six-groove, right-hand twist rifling magic!"
20051-CVGroup_ExSkill_2-1 = "Give me the strength to never falter!"
20051-CVGroup_ExSkill_3-1 = "This is who I am!"
20051-CVGroup_ExSkill_Level_1-1 = "Bolt forward! Thermite Pink!"
20051-CVGroup_ExSkill_Level_2-1 = "Justice is here!"
20051-CVGroup_ExSkill_Level_3-1 = "Twinkle! Bam-bam! Bang!"
20051-CVGroup_Formation_In_1-1 = "Thermite Pink is here!"
20051-CVGroup_Formation_In_2-1 = "Magical Vigilante Crew of Justice, mobilize!"
20051-CVGroup_Formation_Select-1 = "Uzawa Reisa! Also known as...Thermite Pink!"
20051-CVGroup_Growup_1-1 = "Can I really have something so...? Thank you!"
20051-CVGroup_Growup_2-1 = "I'll make sure to grow with this strength you've given me, Sensei!"
20051-CVGroup_Growup_3-1 = "I, Uzawa Reisa, will aim even higher!"
20051-CVGroup_Growup_4-1 = "If it's for you, I'm okay with 2 stages— No, 17 stages of transformation!!"
20051-CVGroup_Relationship_Up_1-1 = "The power of connection is strong! Yes, it's quite literally the strongest!"
20051-CVGroup_Relationship_Up_2-1 = "I look up to a hero's strength... But...I also look up to your kindness."
20051-CVGroup_Relationship_Up_3-1 = "You know how you compliment me a lot? That makes me so...happy!"
20051-CVGroup_Relationship_Up_4-1 = "I'll protect both you and peace!"
