[translation]
20052-CVGroup_CommonSkill-1 = "麻煩在這裡簽名。"
20052-CVGroup_ExSkill_1-1 = "感謝您的惠顧～呣呵呵♪"
20052-CVGroup_ExSkill_2-1 = "來來來，走過路過不要錯過～"
20052-CVGroup_ExSkill_3-1 = "承蒙您的惠顧。"
20052-CVGroup_ExSkill_Level_1-1 = "好的～務必務必！\n呣呵呵……"
20052-CVGroup_ExSkill_Level_2-1 = "這還真賺錢呢……"
20052-CVGroup_ExSkill_Level_3-1 = "銷量相當不錯……呣呵呵。"
20052-CVGroup_Formation_In_1-1 = "來開拓新的銷路吧。"
20052-CVGroup_Formation_In_2-1 = "這是……要大賺一筆的預感……！"
20052-CVGroup_Formation_Select-1 = "哎呀，您找我嗎？\n要簽約？事業擴大？是哪一個呢？"
20052-CVGroup_Growup_1-1 = "今天要好於昨天，明天要好於今天……\n日復一日的成長將指引我們走向更光明的收益……啊，失禮了。\n走向更光明的未來吧。"
20052-CVGroup_Growup_2-1 = "為了出版部的存續，身為部長的我也得變得更強才行……\n某個地方剛好躺著很優渥的契約之類的事……不會發生嗎……？"
20052-CVGroup_Growup_3-1 = "奇怪，莫名有種腦袋的轉速變快了的感覺呢。\n老師，如果您在尋找優秀的契約代理人的話……\n來來來，就在這裡哦～呣呵呵。"
20052-CVGroup_Growup_4-1 = "為了表達平日的感謝，我試著將自己的心意寫在這張紙上了～\n啊，想麻煩您在這裡幫我蓋個收件章～\n……文章是契約書的風格？是，是錯覺啦～！"
20052-CVGroup_Relationship_Up_1-1 = "呼呣……我和老師的「好感度」提升了，是這麼回事嗎？\n……感想？\n唔嗯……您問了很難回答的問題呢。"
20052-CVGroup_Relationship_Up_2-1 = "身為出版部的部長，居然會在表達上如此苦惱……\n呃，就是說，那個……\n這樣的心情，是我第一次感受到……"
20052-CVGroup_Relationship_Up_3-1 = "唉……乾脆直接一口氣說清楚，給自己一個痛快吧！\n所以說，老師，請稍微……\n啊，嗚嗚……沒什麼，如果能再給我一點時間的話……"
20052-CVGroup_Relationship_Up_4-1 = "契約書可以挖漏洞，但說謊是萬萬不可……唉，我就坦白說吧。\n能夠成為老師的學生，我真的感到很慶幸。\n託您的福，我的文章變得驚人地美麗……\n所以今後的……批改與校正，也要多多麻煩您囉？"
