[translation]
20051-CVGroup_CommonSkill-1 = "사랑과! 용기와! 우정 파워로!"
20051-CVGroup_ExSkill_1-1 = "피딩램프에서 챔버까지. 6조 우선의 마법이여!"
20051-CVGroup_ExSkill_2-1 = "흔들리지 않을 힘을!"
20051-CVGroup_ExSkill_3-1 = "이게, 저예요!"
20051-CVGroup_ExSkill_Level_1-1 = "볼트 포워드! 테르밋 핑크!"
20051-CVGroup_ExSkill_Level_2-1 = "정의의 편, 강림! 입니다!"
20051-CVGroup_ExSkill_Level_3-1 = "샤라랑-! 빠빠빠빰! 바바방!"
20051-CVGroup_Formation_In_1-1 = "테르밋 핑크, 등장입니다!"
20051-CVGroup_Formation_In_2-1 = "정의의 마법 자경단, 출동입니다!"
20051-CVGroup_Formation_Select-1 = "우자와 레이사! 다른 이름은~ 테르밋 핑크!"
20051-CVGroup_Growup_1-1 = "제가 이런 걸 받아도 괜찮나요……? 감사합니다!"
20051-CVGroup_Growup_2-1 = "선생님께 받은 이 힘으로, 꼭 성장 하겠습니다!"
20051-CVGroup_Growup_3-1 = "우자와 레이사는, 더욱 높은 곳을 향하겠습니다!"
20051-CVGroup_Growup_4-1 = "선생님을 위해서라면, 저! 2단 변신……아니, 17단 변신 하겠습니다!!"
20051-CVGroup_Relationship_Up_1-1 = "인연의 힘은 강해요! 네, 그야말로! 최강입니다!"
20051-CVGroup_Relationship_Up_2-1 = "히어로의 강함도 동경하지만……\n그……선생님의 자상함도, 동경하고 있습니다."
20051-CVGroup_Relationship_Up_3-1 = "선생님은 저를 자주 칭찬해 주시잖아요? 그게 무척…… 기쁩니다!"
20051-CVGroup_Relationship_Up_4-1 = "평화와 선생님 모두를 지키겠습니다!"
