[translation]
23004-CVGroup_CommonSkill-1 = "雷之玉座……戰鬥模式！"
23004-CVGroup_ExSkill_1-1 = "來，開始大鬧一場吧。"
23004-CVGroup_ExSkill_2-1 = "哼～真是個乖孩子。"
23004-CVGroup_ExSkill_3-1 = "準備完畢，運作開始。"
23004-CVGroup_ExSkill_Level_1-1 = "這就是千年的猛獸。"
23004-CVGroup_ExSkill_Level_2-1 = "驚異的技術力──\n好好烙印在眼底吧。"
23004-CVGroup_ExSkill_Level_3-1 = "這把椅子將使你們毀滅。"
23004-CVGroup_Formation_In_1-1 = "技術的優勢，才能決定勝利。"
23004-CVGroup_Formation_In_2-1 = "是個合理的選擇呢。"
23004-CVGroup_Growup_1-1 = "老師的關心，真讓人溫暖呢。"
23004-CVGroup_Growup_2-1 = "升級能夠提升人生的生活品質。\n而我的生活品質，也是如此。"
23004-CVGroup_Growup_3-1 = "操作機械的時間越多，似乎越能理解傾注在機械中的溫柔。"
23004-CVGroup_Growup_4-1 = "為了某個人製造某個東西──\n這就是身為巨匠的幸福。"
23004-CVGroup_Relationship_Up_1-1 = "因為總是待在工房做東做西的……\n我其實不太擅長對話，不過面對老師似乎不太一樣呢。"
23004-CVGroup_Relationship_Up_2-1 = "真不可思議啊……我指的是人類的心。\n雖然不知道結構如何，不過相當令人興奮。"
23004-CVGroup_Relationship_Up_3-1 = "儘管目前還只是接近浪漫的程度，但我希望有天能到宇宙去一趟。\n雖然想必並不容易，不過到時候……我會帶老師一起去的。"
23004-CVGroup_Relationship_Up_4-1 = "我隨時都在這間工房哦。\n有需要的時候……隨時都可以到這裡來。\n老師……"
