[translation]
23004-CVGroup_CommonSkill-1 = "Thundergun... Combat mode!"
23004-CVGroup_ExSkill_1-1 = "Now, go wild."
23004-CVGroup_ExSkill_2-1 = "Hm, what a good child."
23004-CVGroup_ExSkill_3-1 = "Maintenance complete. Activate."
23004-CVGroup_ExSkill_Level_1-1 = "This is the Millennium's beast!"
23004-CVGroup_ExSkill_Level_2-1 = "Get ready to see technique that's been honed for ages."
23004-CVGroup_ExSkill_Level_3-1 = "This chair will destroy you."
23004-CVGroup_Formation_In_1-1 = "Our superior skills will ensure our victory."
23004-CVGroup_Formation_In_2-1 = "It's a logical choice."
23004-CVGroup_Growup_1-1 = "Sensei, your consideration fills me with warmth."
23004-CVGroup_Growup_2-1 = "Upgrades improve quality of life. And it happened to me of all people!"
23004-CVGroup_Growup_3-1 = "The more you work with machines, the more you understand the kindness of their creators."
23004-CVGroup_Growup_4-1 = "Making something for someone else brings a meister joy."
23004-CVGroup_Relationship_Up_1-1 = "I'm usually making things at the workshop, so I'm not used to conversation. But...you're different, Sensei."
23004-CVGroup_Relationship_Up_2-1 = "The human mind is fascinating. I'm not sure what the mechanism is, but my heart is pounding."
23004-CVGroup_Relationship_Up_3-1 = "It's still more likely to happen in my dreams, but...I want to go to space one day. It'll be hard work, but when I do, I'll take you with me, Sensei."
23004-CVGroup_Relationship_Up_4-1 = "I'll always be here in this workshop. If you need help, come by anytime, Sensei..."
