[translation]
26006-CVGroup_CommonSkill-1 = "唔呵呵，全都被我看光了唷？"
26006-CVGroup_ExSkill_1-1 = "觀測準備完畢！"
26006-CVGroup_ExSkill_2-1 = "無法逃出我的視線！"
26006-CVGroup_ExSkill_3-1 = "我看看……？"
26006-CVGroup_ExSkill_Level_1-1 = "掃描完畢！"
26006-CVGroup_ExSkill_Level_2-1 = "找到了！"
26006-CVGroup_ExSkill_Level_3-1 = "呵呵……原來在這裡啊。"
26006-CVGroup_Formation_In_1-1 = "您，您，您願意相信我嗎？"
26006-CVGroup_Formation_In_2-1 = "如果像我這樣的學生也可以的話……"
26006-CVGroup_Growup_1-1 = "感覺眼睛突然變好了！"
26006-CVGroup_Growup_2-1 = "這樣一來……就能將老師的舉手投足，更詳細地……！"
26006-CVGroup_Growup_3-1 = "非常謝謝你，老師。\n今後我也會加油，完成更多更多觀察的！"
26006-CVGroup_Growup_4-1 = "只要繼續努力下去，總有一天能從特別班逃出來的對吧……？"
26006-CVGroup_Relationship_Up_1-1 = "耶嘿嘿……像這樣跟老師直接面對面說話……稍微，有點害羞呢。"
26006-CVGroup_Relationship_Up_2-1 = "只要跟老師在一起，就算在這片極寒之中也不會害怕。"
26006-CVGroup_Relationship_Up_3-1 = "我想更加……更～加了解老師！"
26006-CVGroup_Relationship_Up_4-1 = "老師，今晚……月色真美……對吧。"
