[translation]
26005-CVGroup_CommonSkill-1 = "這樣如何！？"
26005-CVGroup_ExSkill_1-1 = "看招！"
26005-CVGroup_ExSkill_2-1 = "哼！看我解決你！"
26005-CVGroup_ExSkill_3-1 = "覺悟吧！"
26005-CVGroup_ExSkill_Level_1-1 = "哈啊啊啊！"
26005-CVGroup_ExSkill_Level_2-1 = "這樣如何！？"
26005-CVGroup_ExSkill_Level_3-1 = "吃我這招！"
26005-CVGroup_Formation_In_1-1 = "感謝我的加入吧！"
26005-CVGroup_Formation_In_2-1 = "真拿你沒辦法，要出發囉！"
26005-CVGroup_Formation_Select-1 = "呀啊！？突，突然做什麼啦！？"
26005-CVGroup_Growup_1-1 = "謝……謝……謝謝！"
26005-CVGroup_Growup_2-1 = "哼哼！老師！\n多依賴我也沒關係唷！"
26005-CVGroup_Growup_3-1 = "很～好！我，這樣就變得更強了！\n肯定也長高了吧！？"
26005-CVGroup_Growup_4-1 = "…………謝謝你，老師。\n總有一天，會報答你的。"
26005-CVGroup_Relationship_Up_1-1 = "怎，怎麼說呢，那個……\n很，很羞恥耶！"
26005-CVGroup_Relationship_Up_2-1 = "今天……過得很開心。\n這，這不是謊話！"
26005-CVGroup_Relationship_Up_3-1 = "別，別誤會了！\n只是因為跟老師在一起的時間太開心了而已！\n啊！感覺好像說錯話了！？"
26005-CVGroup_Relationship_Up_4-1 = "謝……謝……謝謝你！\n現，現在，我能想到的就只有這句話。\n不過……下次就，那個……！"
