[translation]
26011-CVGroup_CommonSkill-1 = "H-How does it taste?"
26011-CVGroup_ExSkill_1-1 = "Wh-Whoa?! Wh-What's going on?!"
26011-CVGroup_ExSkill_2-1 = "Here it comes!"
26011-CVGroup_ExSkill_3-1 = "I knew it would come!"
26011-CVGroup_ExSkill_Level_1-1 = "For this... I do that!"
26011-CVGroup_ExSkill_Level_2-1 = "Haaaaap!"
26011-CVGroup_ExSkill_Level_3-1 = "Not a chance! Hah!"
26011-CVGroup_Formation_In_1-1 = "Whoa, can I go too?! Yay!"
26011-CVGroup_Formation_In_2-1 = "I'll give it my all!"
26011-CVGroup_Growup_1-1 = "I-Is this for me?! Thank you! I'll do my best!"
26011-CVGroup_Growup_2-1 = "I can't really explain it except to say... I feel stronger!"
26011-CVGroup_Growup_3-1 = "Whoa! I can feel power surging through my body! Is it always like this?!"
26011-CVGroup_Growup_4-1 = "Sensei! I feel like I can do anything right now!"
26011-CVGroup_Relationship_Up_1-1 = "I don't know what to say. A simple thanks feels so inadequate..."
26011-CVGroup_Relationship_Up_2-1 = "R-Really? For Me? Are you sure...?"
26011-CVGroup_Relationship_Up_3-1 = "I rely on you more and more, Sensei. Haha..."
26011-CVGroup_Relationship_Up_4-1 = "All the good and wonderful things that have happened since I got here... They're all thanks to you, Sensei."
