[translation]
40015-CVGroup_Battle_Buffed_1-1 = "Power up!"
40015-CVGroup_Battle_Defense_1-1 = "Dodged in the blink of an eye!"
40015-CVGroup_Battle_Recovery_1-1 = "Thank you for the recovery magic!"
40015-CVGroup_Summon_Retreat_02-1 = "Don't think this is over!!"
40015-CVGroup_CommonSkill_2-1 = "Here's my ultimate magic! This'll hurt!"
40015-CVGroup_Summon_Retreat_01-1 = "And a cool farewell! Whoosh! Sha-sha-sha!!"
