[translation]
8330028-CVGroup_Battle_Buffed_1-1 = "Support confirmed."
8330028-CVGroup_Battle_Defense_1-1 = "It's no use."
8330028-CVGroup_Battle_In_1-1 = "Entering combat as quickly as possible."
8330028-CVGroup_Battle_In_2-1 = "Let's do this."
8330028-CVGroup_Battle_Move_1-1 = "*sigh* What a bother..."
8330028-CVGroup_Battle_Move_2-1 = "The job never ends..."
8330028-CVGroup_Battle_TacticalAction_1-1 = "On the move."
8330028-CVGroup_Battle_Victory_1-1 = "Yep. That was the obvious outcome."
8330028-CVGroup_Battle_Victory_2-1 = "We won. Now what?"
8330028-CVGroup_ExSkill_1-1 = "Time to show off what I can do."
8330028-CVGroup_ExSkill_2-1 = "It's the perfect moment to use this."
8330028-CVGroup_ExSkill_3-1 = "Target confirmed."
8330028-CVGroup_ExSkill_Level_1-1 = "How long can you keep it up?"
8330028-CVGroup_ExSkill_Level_2-1 = "You won't be able to get away."
8330028-CVGroup_ExSkill_Level_3-1 = "You're not getting away!"
