[translation]
10009-700 = "คุณครู!"
10009-701 = "เมื่อวานฉันได้อ่านเรื่องสุดยอดในหนังสือ\nมาล่ะ!"
10009-702 = "เรื่องสุดยอดเหรอ?"
10009-703 = "ใช่! มันเป็นอัตชีวประวัติของนักกีฬาน่ะ..."
10009-704 = "ในนั้นบอกวิธีกินอาหารธรรมดาๆ ให้อร่อย\nขึ้นล่ะ!"
10009-705 = "วิธีกินอาหารธรรมดาๆ ให้อร่อยขึ้น?"
10009-706 = "นักกีฬาจะเขียนอะไรแบบนั้นทำไม...?"
10009-707 = "ในฐานะเจ้าหน้าที่แห่งชมรมชิมอาหาร\nฉันจะปล่อยผ่านไปไม่ได้"
10009-708 = "ไปลองกันดีกว่าคุณครู!"
10009-709 = "คุณครู! คุณครู!"
10009-710 = "ตั้งแต่วันนี้จะมีเทศกาลสตรีทฟูดที่จัตุรัส\nกลางของเกเฮนน่าล่ะ!"
10009-711 = "เธอดูตื่นเต้นมากเลยนะอิซุมิ"
10009-712 = "ใช่! ฉันเฝ้ารอวันนี้มาตลอด!"
10009-713 = "เห็นว่าวันนี้มีร้านพุดดิ้งเจ้าดังมาเปิดขาย\nด้วยล่ะ!"
10009-714 = "ต้องกินให้ได้เลย!"
10009-715 = "คุณครู! เห็นมีว่าร้านราเม็งมาเปิดใหม่ใน\nย่านการค้าเกเฮนน่าด้วยล่ะ!"
10009-716 = "ไปด้วยกันเถอะ!"
10009-717 = "ไปสำรวจตรวจตราล่วงหน้ากัน"
10009-718 = "ต้องเป็นทางการขนาดนั้นเลยเหรอ?"
10009-719 = "แฮ่ะๆ หมายถึงไปชิมน่ะ ^^;"
10009-100090010 = "นี่ๆ คุณครู...!"
10009-100090020 = "ฉันมีของที่อยากให้คุณครูดูด้วยละ"
10009-100090030 = "ไม่สิ มีของที่อยากให้คุณครูลองชิม\nด้วยละ!"
10009-100090040 = "ของที่อิซุมิอยากให้ชิมเหรอ? "
10009-100090050 = "อื้อ!"
10009-100090060 = "วันนี้พอมีเวลาว่างรึเปล่า?"
10009-100090070 = "อิซุมิขอมาทั้งที ต้องว่างอยู่แล้วสิ"
10009-100090080 = "ตื่นเต้นจัง!"
10009-100090090 = "ถ้างั้นจะรอก็แล้วกันนะ!"
