[translation]
10007-577 = "ขอโทษนะคุณครู... แต่พอมีเวลามั้ย?"
10007-578 = "ได้อยู่นะ"
10007-579 = "มีเรื่องอะไรเหรอ?"
10007-580 = "คือว่า... ช่วยออกมารับฉันหน่อยได้มั้ย?"
10007-581 = "พอดีว่าถ้าจะออกไปจากที่นี่ต้องมีคนมา\nยืนยันน่ะ แล้วฉันก็ไม่กล้าติดต่อสภานัก\nเรียน..."
10007-582 = "เอ่อ.. ที่นี่คือ... ป้อมตำรวจน่ะ"
10007-583 = "ป้อมตำรวจเหรอ?!"
10007-584 = "ขอบคุณที่ช่วยนะคุณครู"
10007-585 = "เกือบโดนลากไปที่สภานักเรียนมิลเลเนียม\nแล้วโดนบ่นเข้าแล้วไง"
10007-586 = "ต่อไปก็อย่าไปหาเรื่องใส่ตัวในเมืองล่ะ"
10007-587 = "อืม.. ต่อไปฉันจะไม่ไปพ่นกราฟิตี้ในที่\nสาธารณะอีก"
10007-588 = "แต่ว่าต้องทำตามสัญญานะ เราจะไปวาด\nรูปลงผ้าใบผืนใหญ่ด้วยกัน!"
10007-589 = "สัญญาต้องเป็นสัญญานะ"
10007-590 = "ได้ ครูสัญญา"
10007-591 = "วันนี้ขอบคุณมากนะคุณครู กลับดีๆ ล่ะ"
10007-592 = "มากิก็ด้วยนะ"
10007-593 = "คุณครู หลังเลิกเรียนวันนี้มีธุระอะไรเป็น\nพิเศษมั้ย?"
10007-594 = "หลังเลิกเรียนวันนี้ฉันมีธุระที่ตลาดมืด..."
10007-595 = "ไม่สิ มีธุระในเขตมินามิต่างหาก ไปก่อนนะ!"
10007-596 = "ตลาดมืดงั้นเหรอ?"
10007-597 = "เฮ้อ น่าเสียดายจัง นั่นคือโอกาสที่\nคนอื่นจะได้เห็นเสน่ห์ของ BOOM แท้ๆ"
10007-598 = "แต่การทำแบบนั้นมันรบกวนคนอื่นนะ"
10007-599 = "รู้แล้วแหละน่า ถ้าครูไม่สะดวกฉันก็จะไม่\nตื๊อหรอก..."
10007-600 = "ว่าแต่ คุณครูเคยเล่น BOOM มาก่อนมั้ย?"
10007-601 = "ไม่ล่ะ ครูไม่เคย"
10007-602 = "งั้นเอาไว้ฉันจะโหลดลงมือถือของคุณครู\nให้ แล้วเรามาเล่นโหมดสปีดด้วยกัน!"
10007-603 = "ฉันจะช่วยให้คุณครูผ่านได้ใน 3 นาทีเลย\nล่ะ!"
10007-604 = "เกมนั่นมันมีความหมายอะไรเป็นพิเศษ\nเหรอ...?"
10007-605 = "คุณครู เห็นข้อสอบรอบนี้หรือยัง?"
10007-606 = "ยากเกินบรรยายเลยล่ะ!"
10007-607 = "บอกแล้วไงว่าต้องฝึกและทบทวนให้มากๆ"
10007-608 = "มีข้อไหนที่ออกนอกเหนือขอบเขตด้วย\nเหรอ?"
10007-609 = "จริงๆ ก็แล้วแต่จะคิด..."
10007-610 = "ไม่สิ ฉันไม่ได้หมายความแบบนั้น..."
10007-611 = "เอาเถอะ! ถ้าขืนยังเป็นแบบนี้ฉันต้องไป\nเรียนเสริมแน่เลย~"
10007-612 = "คุณครูช่วยฉันหน่อยสิ~"
10007-613 = "ขอบคุณที่ช่วยสอนนะคุณครู "
10007-614 = "แล้วฉันจะทำคะแนนเต็มในการสอบครั้ง\nหน้าให้ได้ตามที่ครูคาดหวังเลยล่ะ!"
10007-615 = "แล้วครูจะรอนะ"
10007-616 = "ว่าแต่... คุณครู"
10007-617 = "คำอธิบายของช่วงเวลาคลายความตึง\nเครียดที่เขียนไว้หลังสมุดนั่น... มันจะ\nออกสอบวิชาไหนเหรอ?"
10007-618 = "เอาเป็นว่ามากิอ่านตรงที่จะออกสอบ\nให้เข้าใจก่อนแล้วกัน"
10007-619 = "คุณครู! ฉันสอบซ่อมได้คะแนนเต็มด้วย!"
10007-620 = "เพราะคุณครูช่วยสอนฉันไว้เมื่อคราวที่\nแล้วยังไงล่ะ "
10007-621 = "ดีใจด้วยนะ มากิเองก็พยายามได้ดีมาก"
10007-622 = "ฉันทำได้ดีใช่มั้ยล่ะ? งั้นชมกันอีกนิดสิ\nนะ นะ~!"
10007-623 = "งั้นครูจะซื้อไอศกรีมจากในเมืองให้\nเป็นของขวัญที่เธอตั้งใจอ่านหนังสือสอบ"
10007-624 = "จริงเหรอ? สัญญานะ!?"
10007-625 = "ฉันแคปข้อความไว้หมดแล้วนะ ห้ามเท\nกันล่ะ!"
10007-626 = "ขอบคุณที่ช่วยเก็บขยะนะคุณครู"
10007-627 = "แล้วก็ขอบคุณที่ทำเป็นไม่เห็นที่ฉันวาดรูป\nไว้ด้วยนะ"
10007-628 = "ก็ครั้งนี้เธอไม่ได้มีเจตนาไม่ดีอะไรนี่"
10007-629 = "อืม... แต่ถ้าตำรวจไปเห็นเข้าล่ะ?"
10007-630 = "ถ้าเป็นแบบนั้นจริงๆ คุณครูต้องช่วยพูด\nให้นะ ต้องมาช่วยฉันนะ!"
10007-631 = "ฉันมีข่าวดีมาบอกล่ะ!"
10007-632 = "ถ้าเห็นข้อความนี้ ช่วยมาที่กำแพงที่ฉัน\nไปทำกราฟิตี้ไว้คราวก่อนทีนะ"
10007-633 = "มีเรื่องอะไรเหรอ?"
10007-634 = "ถ้ามาก็รู้เองล่ะ!"
10007-635 = "จริงสิ! ใส่เสื้อผ้าที่เลอะได้มาล่ะ!"
10007-636 = "...?"
10007-637 = "ฮุฮุ วันนี้สนุกมากเลยที่ได้ทำกราฟิตี้กับ\nคุณครู"
10007-638 = "ครูก็สนุกมากเลย"
10007-639 = "แต่ครูวาดรูปไม่ได้เรื่องเลย เจ้าของ\nกำแพงจะไม่พอใจหรือเปล่า?"
10007-640 = "อะไรกัน? ยังสนใจอะไรแบบนั้นอยู่อีก\nเหรอ?"
10007-641 = "ไม่ต้องห่วงนะ กราฟิตี้คือศิลปะที่ถ่าย\nทอดอารมณ์ศิลปินแต่ละคนออกมา"
10007-642 = "แล้วกำแพงนั่นก็ถ่ายทอดอารมณ์ของคุณ\nครูได้ดีแล้ว"
10007-643 = "อยากให้เราได้สนุกกันแบบนี้อีกจัง~"
