[translation]
10012-872 = "Hello, Trainer."
10012-873 = "Do you have some time today?"
10012-874 = "Yeah, what's going on?"
10012-875 = "I'm not too busy."
10012-876 = "Okay, I just wanted to let you know..."
10012-877 = "I've prepared the training schedule that I mentioned earlier."
10012-878 = "If possible, I'd like you to check it out today. Can you come to the gym?"
10012-879 = "I'll be waiting for you."
10012-880 = "Trainer, are you busy this weekend?"
10012-881 = "Would you mind coming to the mall with me?"
10012-882 = "Not at all."
10012-883 = "What are you gonna buy?"
10012-884 = "Thank you, Trainer."
10012-885 = "I need protein supplements, and I wanted your input."
10012-886 = "Well, then, I'll be waiting for you at the mall."
10012-887 = "Trainer, I've prepared something special for you today."
10012-888 = "I'll see you at the gym this afternoon."
10012-889 = "Trainer."
10012-890 = "How are you feeling?"
10012-891 = "I'm okay."
10012-892 = "Ugh, my muscles..."
10012-893 = "As expected, you're pretty strong, Trainer."
10012-894 = "I guess the workout was a bit too much."
10012-895 = "Next time, I'll help you stretch."
10012-896 = "Oh yeah, by now, the protein supplements I sent you"
10012-897 = "should have arrived at your office."
10012-899 = "Please don't forget to have some four times a day."
10012-900 = "Trainer."
10012-901 = "If it's okay, can I see you a bit this weekend?"
10012-902 = "Eek! But my muscles are still..."
10012-903 = "I've been working out really hard!"
10012-904 = "Oh... That's not it, Trainer."
10012-905 = "This isn't about exercising."
10012-906 = "In that case, okay!"
10012-907 = "Got it."
10012-908 = "I'll see you then."
10012-10012010 = "Have you visited the new park next to Schale, Trainer?"
10012-10012020 = "No, not yet."
10012-10012030 = "Oh, I see."
10012-10012040 = "I had errands in the area, so I paid it a visit."
10012-10012050 = "It'd be a good place for a morning jog. The track was very well maintained."
10012-10012060 = "If you'd like"
10012-10012070 = "we could go for a jog there tomorrow morning?"
10012-10012080 = "As long as it's a LIGHT jog..."
10012-10012090 = "I promise, Trainer."
10012-10012100 = "In that case, I will see you tomorrow."
