[translation]
10017-100170010 = "ดีใจซะเถอะสหาย"
10017-100170020 = "พวกเราชาวสหภาพเรดวินเทอร์"
10017-100170030 = "ได้มอบ <เหรียญไมตรีนักเรียนพิเศษ>"
10017-100170040 = "เพื่อชมเชยในความสามารถของสหายล่ะ!"
10017-100170050 = "คราวก่อนก็ได้รับเหรียญนี้ไปแล้ว\nไม่ใช่เหรอ?"
10017-100170060 = "พูดอะไรน่ะ เหรียญที่ได้ไปคราวที่แล้ว\nคือ <เหรียญมิตรภาพนักเรียนพิเศษ>\nต่างหาก"
10017-100170070 = "นี่สหายสับสนกับประเภทของเหรียญ\nแล้วเหรอ?"
10017-100170080 = "แล้วเหรียญตรานี่มีกี่แบบกันล่ะ?"
10017-100170090 = "ที่สถาบันสหภาพเรดวินเทอร์\nจะมอบเหรียญเพื่อเป็นเกียรติแก่นักเรียน\nที่ทุ่มเทต่อการพัฒนาของสถาบัน"
10017-100170100 = "มีอยู่ทั้งหมด 247 แบบ"
10017-100170110 = "แล้วเชริโน่ได้เหรียญอะไรมาแล้วบ้าง?"
10017-100170120 = "หุหุ ถามอะไรโง่ๆ น่ะสหาย"
10017-100170130 = "เราได้มาทั้ง 247 แบบแล้ว!"
10017-100170140 = "ดูนี่สิสหาย เหรียญที่เราออกแบบขึ้น\nมาเอง!"
10017-100170160 = "หุหุ แค่ดีไซน์ก็กินขาดแล้วใช่มั้ยล่ะ?"
10017-100170170 = "สวยดีนะ"
10017-100170180 = "ไม่เคยเห็นเหรียญแบบนี้มาก่อนเลย..."
10017-100170190 = "ใช่มั้ยล่ะ? จะชื่นชมเราอีกก็ได้นะ!"
10017-100170200 = "เราคงมีความสามารถด้านการออก\nแบบที่ยอดเยี่ยมอยู่ในตัวก็ได้!"
10017-100170210 = "อืม..."
10017-100170220 = "สหายมีอาหารที่เลือกกินมั้ย?"
10017-100170230 = "ทำไมจู่ๆ ถึงมาถามล่ะ?"
10017-100170240 = "เราไม่ชอบกินพริกหวานน่ะ\nทั้งเผ็ด ทั้งขม แล้วก็รสจัดด้วย!"
10017-100170250 = "แหวะ... รสชาติแย่แบบนั้น ฉันว่ามัน\nคือพืชผลแห่งความตายเลยละ"
10017-100170260 = "การเลือกกินไม่ดีต่อร่างกายนะ"
10017-100170270 = "ไม่ได้เลือกกินซะหน่อย! คนที่ไม่ชอบ\nพริกหวานก็ต้องคิดแบบนี้ทั้งนั้นแหละ!"
10017-100170280 = "ทำไมไม่เข้าใจความเป็นจริงพื้นฐาน\nง่ายๆ เลยนะ..."
10017-100170290 = "หุหุหุ สหาย "
10017-100170300 = "ยังไม่ลืมสัญญาที่บอกว่าจะซื้อพุดดิ้ง\nให้ใช่มั้ย?"
10017-100170310 = "ไม่ลืมอยู่แล้ว"
10017-100170320 = "คิดไว้แล้วเชียว ต่างกับผู้ใหญ่คนอื่น\nที่ชอบสัญญาลมๆ แล้งๆ สมเป็นสหายจริงๆ"
10017-100170330 = "วันนี้เรางดกินของว่างตอนกลางวัน"
10017-100170340 = "เพื่อจะไปกินพุดดิ้งที่สหายจะซื้อให้\nจนพุงกางเลย"
10017-100170350 = "หลังเลิกเรียนวันนี้เราจะไปรออยู่หน้า\nร้านนะ ห้ามมาสายล่ะ!"
10017-100170360 = "เดี๋ยวสิ ไม่ได้บอกสักหน่อยว่าจะ\nซื้อพุดดิ้งให้หลายอันน่ะ..."
10017-100170370 = "สหาย มองออกไปนอกหน้าต่างสิ!"
10017-100170380 = "หิมะ! หิมะกำลังตก!"
10017-100170390 = "ที่ชาเล่ต์อากาศแจ่มใส ไม่มีเมฆเลยสักนิดเดียว"
10017-100170400 = "ถ้างั้นมาที่เรดวินเทอร์สิ!"
10017-100170410 = "ถ้ามาที่นี่ก็จะปั้นตุ๊กตาหิมะ\nหรือปั้นกระต่ายหิมะก็ได้"
10017-100170420 = "เสร็จงานแล้วจะไปหานะ"
10017-100170430 = "ไม่ได้! เราไม่รู้ว่าหิมะจะหยุดตกและ\nละลายไปตอนไหน เพราะงั้นจะมัวชักช้า\nอยู่ไม่ได้นะ!"
10017-100170440 = "ต้องมาเดี๋ยวนี้เลย!"
10017-100170450 = "สหาย สหายมีอะไรที่กลัวเป็นพิเศษ\nไหม?"
10017-100170460 = "ครูกลัวผี"
10017-100170470 = "ครูกลัวขนมมันจู"
10017-100170480 = "หุหุ กลัวผีเหรอ? สหายก็มีมุมที่เป็น\nเด็กเหมือนกันนะเนี่ย"
10017-100170490 = "ไม่ต้องกังวลนะสหาย ถ้าผีโผล่ออกมา\nละก็ เราจะจัดการมันให้เอง!"
10017-100170500 = "เอ๋? กลัวขนมมันจูที่หวานๆ น่ะเหรอ?\nหมายความว่ายังไง?"
10017-100170510 = "สหายชอบพูดอะไรที่เราไม่เข้าใจอยู่\nเรื่อย..."
10017-100170520 = "แล้วเชริโน่ล่ะกลัวอะไร?"
10017-100170530 = "ถามอะไรแบบนั้นกัน! เราไม่มีอะไรต้องกลัวหรอก!"
10017-100170540 = "คำว่ากลัวไม่มีอยู่ในพจนานุกรมของ\nผู้นำหรอกนะ!"
10017-100170550 = "ในฐานะของประธานสภานักเรียน\nเลขาธิการ หัวหน้าฝ่ายตกแต่ง\nและหัวหน้าฝ่ายทำความสะอาด\nเราไม่กลัวอะไรหรอก!"
