[translation]
10051-100510010 = "อ๊ะ แย่ล่ะ..."
10051-100510020 = "คุณครู เสื้อกาวน์ของฉันอยู่ที่ชาเล่ต์\nรึเปล่า?"
10051-100510030 = "เสื้อกาวน์สีขาวบนโซฟานี่น่ะเหรอ?"
10051-100510040 = "อื้อ คงจะใช่นั่นแหละ"
10051-100510050 = "ฉันคงจะถอดแล้วลืมทิ้งไว้น่ะ"
10051-100510060 = "ตอนนี้ต้องเริ่มทำงานแล้วด้วยสิ\nทำยังไงดีล่ะ?"
10051-100510070 = "ตัวอื่นก็เอาไปซักหมดแล้วด้วย..."
10051-100510080 = "ให้ครูเอาไปให้มั้ย?"
10051-100510090 = "ไม่ละ ไม่เป็นไร"
10051-100510100 = "เดี๋ยวฉันลองหาอะไรที่ใส่แทนได้ก็แล้วกัน"
10051-100510110 = "หลังจากเปิดตัวคุณสมบัติใหม่ล่าสุด\nของเจ้าสายฟ้าไปตอนงานกีฬา"
10051-100510120 = "เราได้รับคำขอจากหลายๆ บริษัท\nให้พัฒนาอุปกรณ์เชียร์แบบใหม่\nเข้ามาเยอะเลย"
10051-100510130 = "ถ้าสร้างอุปกรณ์เชียร์ทั่วๆ ไป\nมันก็ไม่ใช่เรื่องยากอะไร..."
10051-100510140 = "แต่นี่เป็นคำขอให้พัฒนาอุปกรณ์เชียร์\nที่ส่งมาถึงพวกเราทั้งที คงจะทำอุปกรณ์\nธรรมดาๆ ส่งไปไม่ได้หรอก"
10051-100510150 = "อุปกรณ์ทั่วไปก็น่าจะโอเคแล้วนะ?"
10051-100510160 = "ไม่ละ ทำแบบนั้นไม่ได้หรอก"
10051-100510170 = "ถ้าเป็นลูกค้าที่ส่งคำขอมาหาพวกเรา\nโดยตรง แทนที่จะซื้ออุปกรณ์ที่มีวางขาย\nทั่วไปแล้วละก็"
10051-100510180 = "พวกเขาคงคาดหวังว่าจะได้\nสิ่งประดิษฐ์ใหม่ที่พิเศษอยู่แน่ๆ"
10051-100510190 = "พูดโน้มน้าวใจเก่งมาก?!"
10051-100510200 = "เพราะงั้นคุณครู ช่วงบ่ายนี้มีเวลามั้ย?"
10051-100510210 = "ฉันอยากทดสอบอุปกรณ์เชียร์ที่สร้าง\nขึ้นมาหน่อยน่ะ..."
10051-100510220 = "ถ้าคุณครูมาช่วยตรวจสอบหน่อย\nก็คงดีนะ..."
10051-100510230 = "อึก... เรื่องใหญ่แล้วละ"
10051-100510240 = "มีเรื่องอะไรรึเปล่า?"
10051-100510250 = "จำได้มั้ยที่ฉันบอกว่ามีคำขอให้\nพัฒนาอุปกรณ์เชียร์แบบใหม่น่ะ?"
10051-100510260 = "ฉันลองสร้างหุ่นยนต์ที่มีข้อต่อหลายๆ ชิ้น\nเพื่อให้รับแรงเสียดทานได้เวลาเคลื่อนไหว\nด้วยความเร็วแสงน่ะ"
10051-100510270 = "แต่ดูเหมือนคงทำให้เสร็จสมบูรณ์\nทันกำหนดยากน่ะ..."
10051-100510280 = "เรื่องนี้มันยากเกินไปหน่อยรึเปล่า..."
10051-100510290 = "ขอโทษลูกค้า\nแล้วขอเวลาเพิ่มดีมั้ย?"
10051-100510300 = "ทำแบบนั้นก็ได้อยู่หรอก แต่ว่า..."
10051-100510310 = "เราจะทำให้ลูกค้าที่ไว้วางใจเรา\nรอนานกว่านี้ก็ไม่ได้หรอก"
10051-100510320 = "ถึงวิธีนี้จะไม่ใช่วิธีแก้ปัญหา\nแบบไมสเตอร์ก็เถอะ..."
10051-100510330 = "แต่คราวนี้ก็คงต้องใช้ร่างกายแก้ปัญหา\nแล้วละ"
10051-100510340 = "ใช้ร่างกายเรอะ?!"
10051-100510350 = "ขอโทษนะที่รบกวนคุณครูทั้งวันเลย..."
10051-100510360 = "เสียงเป็นยังไงบ้าง?"
10051-100510370 = "เสียงยังแหบอยู่เลย..."
10051-100510380 = "ฉันพยายามคุยกับสมาชิกคนอื่น\nแต่ก็ไม่มีเสียงเลย แบบนี้ลำบาก\nจริงๆ นะเนี่ย"
10051-100510390 = "เพราะงั้นฉันก็เลยกำลังประกอบ\nอุปกรณ์ใหม่ที่จะช่วยให้สื่อสารได้\nสะดวกขึ้นอยู่น่ะ"
10051-100510400 = "อุปกรณ์ที่ช่วยให้ได้ยินเสียง\nแม้คนพูดจะพูดเบาๆ"
10051-100510410 = "อุปกรณ์ที่จะตรวจจับและบันทึกเสียง\nที่ได้ยิน และปรับระดับเสียงให้ดังขึ้น"
10051-100510420 = "นั่นมัน...เครื่องขยายเสียงไม่ใช่เหรอ?"
10051-100510430 = "รู้สึกเหมือนช่วงนี้สมาชิกชมรมเรา\nดูไม่ค่อยมีแรงกันเลย"
10051-100510440 = "คุณครูพอจะเดาสาเหตุได้บ้างมั้ย?"
10051-100510450 = "ทำคะแนนสอบได้ไม่ดีรึเปล่า?"
10051-100510460 = "ช่วงนี้เป็นช่วงสอบนี่นา"
10051-100510470 = "งั้นเหรอ...?"
10051-100510480 = "คะแนนสอบคราวก่อนก็ไม่ได้แย่\nขนาดนั้นนี่นา..."
10051-100510490 = "แต่ก็นะ แต่ละคนก็อาจจะไม่พอใจ\nคะแนนของตัวเองก็ได้"
10051-100510500 = "ไม่มีวิธีให้กำลังใจทุกคนเลยเหรอ?"
10051-100510510 = "อืม..."
10051-100510520 = "เห็นทีหัวหน้าอย่างฉันคงจะต้อง\nออกโรงซะแล้ว"
