[translation]
10065-100650010 = "สวัสดีค่ะ คุณครู"
10065-100650020 = "อืม... สวัสดี... ว่าแต่เธอเป็นใครน่ะ?"
10065-100650030 = "อ๊ะ จริงด้วยค่ะ นี่เป็นครั้งแรกที่ฉัน\nมาทักทายแบบไม่เป็นทางการสินะคะ"
10065-100650040 = "คุวาคามิ คาโฮะ รองหัวหน้าชมรม\nหยินหยางของสหพันธ์เฮียกคิยาโค"
10065-100650050 = "และควบตำแหน่งหัวหน้าทีม\nประชาสัมพันธ์เชิงกลยุทธ์ของทีม\nสนับสนุนการประชาสัมพันธ์การท่อง\nเที่ยวและวัฒนธรรมเฮียกคิยาโคค่ะ"
10065-100650060 = "ต้องขอโทษด้วยที่แนะนำตัวช้าไปค่ะ\nยินดีที่ได้พบนะคะ คุณครูของชาเล่ต์"
10065-100650070 = "ทีมประชาสัมพันธ์... เชิงกลยุทธ์?"
10065-100650080 = "เอ่อ ยินดีที่ได้รู้จักนะ\nว่าแต่มีธุระอะไรรึเปล่า?"
10065-100650090 = "ฉันติดต่อมาคุยเรื่องที่เคยหารือไว้\nเมื่อครั้งที่แล้วน่ะค่ะ"
10065-100650100 = "หืม? เรื่องอะไรเหรอ?"
10065-100650110 = "ถ้าคุณครูสะดวก ฉันอยากจะขอไป\nที่ชาเล่ต์เพื่อหารือเรื่องนั้นต่อค่ะ\nคุณครูสะดวกหรือเปล่าคะ?"
10065-100650120 = "อ๋อ อื้ม วันนี้ได้นะ"
10065-100650130 = "ขอบคุณค่ะ ถ้างั้นฉันจะไปพบ\nที่ชาเล่ต์เดี๋ยวนี้เลยค่ะ"
10065-100650140 = "ตอนนี้เลยเรอะ...?!"
10065-100650150 = "ขออภัยอย่างสูงที่ฉันทำให้คุณครู\nเดือดร้อนโดยไม่ตั้งใจค่ะ"
10065-100650160 = "ฉันขอโทษจากใจจริงเลยค่ะ"
10065-100650170 = "หืม? ครูไม่ได้เดือดร้อนอะไรเลยนะ"
10065-100650180 = "ขอบคุณที่กล่าวเช่นนั้นค่ะ"
10065-100650190 = "แต่ฉันก็อยากกล่าวขอโทษคุณครู\nเรื่องที่สร้างความเดือดร้อนให้ วันนี้\nพอจะมีเวลาให้ฉันสักหน่อยมั้ยคะ?"
10065-100650200 = "ครูมีเวลาให้คาโฮะอยู่แล้วละ"
10065-100650210 = "ค่ะ ถ้างั้นฉันจะตั้งตารอพบคุณครู\nนะคะ"
10065-100650220 = "อื้อ ครูจะรีบไปนะ"
10065-100650230 = "คุวาคามิ คาโฮะผู้นี้... จะพาแนะนำ\nอย่างสมบูรณ์แบบเลยค่ะ"
10065-100650240 = "...เดี๋ยวนะ? แนะนำเหรอ?"
10065-100650250 = "คุณครู วันนี้พอมีเวลาว่างมั้ยคะ?"
10065-100650260 = "บอกแล้ว ครูมีเวลาให้คาโฮะเสมอนะ\nมีอะไรเหรอ?"
10065-100650270 = "ฉันอยากทำตามสัญญาที่ให้กับคุณครู\nเมื่อครั้งก่อนน่ะค่ะ..."
10065-100650280 = "เพราะงั้น..."
10065-100650290 = "ฉันจึงติดต่อมาหาใหม่เพราะอยากชวน\nคุณครูมาเที่ยวชมอีกครั้งค่ะ"
10065-100650300 = "เพราะงั้นแล้ว... ไม่ทราบว่าคุณครู\nจะพอมีเวลาหรือเปล่าคะ?"
10065-100650310 = "ได้เลย เดี๋ยวครูรีบไปหานะ"
10065-100650320 = "ค่ะ ขอบคุณค่ะ"
10065-100650330 = "ฉันจะตั้งตารอพบคุณครูนะคะ"
10065-100650340 = "ฮุฮุฮุ"
10065-100650350 = "คาโฮะ? มีเรื่องอะไรดีๆ งั้นเหรอ...?"
10065-100650360 = "หากได้ยินแล้วอย่าเพิ่งตกใจนะคะ"
10065-100650370 = "ในที่สุด..."
10065-100650380 = "ในที่สุดเหรอ...?"
10065-100650390 = "ในที่สุด... สินค้าสำหรับประชาสัมพันธ์\nเฮียกคิยาโคที่ชมรมหยินหยางจัดทำขึ้น\nใหม่รอบนี้ก็จัดส่งมาถึงแล้วละค่ะ!"
10065-100650400 = "โอ้ ดีใจด้วยนะ!"
10065-100650410 = "อะแฮ่ม ฉันอยากมอบให้คุณครูเก็บไว้...\nสนใจรับไว้สักชิ้นมั้ยคะ?"
10065-100650420 = "เอ่อ... หมายถึง... ถ้าคุณครู\nสนใจรับไว้นะคะ"
10065-100650430 = "ครูยินดีมากๆ เลย งั้นเดี๋ยวครูไปหานะ"
10065-100650440 = "ฮุฮุฮุ ฉันจะตั้งตารอพบคุณครู\nนะคะ"
10065-100650450 = "สวัสดีค่ะคุณครู คาโฮะค่ะ"
10065-100650460 = "ฉันทราบข่าวเรื่องที่คุณครูจะแวะมา\nทำธุระที่ชมรมหยินหยาง พรุ่งนี้แล้วค่ะ"
10065-100650470 = "อื้อ ใช่แล้วละ"
10065-100650480 = "ฮุฮุ ฉันดีใจที่จะได้เจอคุณครูอีกนะคะ"
10065-100650490 = "หลังเสร็จงานแล้ว แวะมาดื่มชาที่\nห้องพักผ่อนก่อนค่อยกลับดีมั้ยคะ?"
10065-100650500 = "ถ้าได้นั่งพักผ่อนในที่ที่สะอาดเรียบร้อย\nจะช่วยเพิ่มประสิทธิภาพการทำงาน\nได้นะคะ"
10065-100650510 = "คงไม่มีเหตุผลให้ปฏิเสธแล้วสินะ"
10065-100650520 = "ขอบคุณค่ะ"
10065-100650530 = "ถ้างั้นฉันจะรอนะคะ"
