[translation]
10119-101190010 = "Ah. Sensei."
10119-101190020 = "Apologies. You called?"
10119-101190030 = "Hi, Nagusa! I did!"
10119-101190040 = "You must've been busy!"
10119-101190050 = "I did not bring my phone with me to training."
10119-101190060 = "Anyways, is there a matter of concern?"
10119-101190070 = "Do you require my assistance?"
10119-101190080 = "Nothing urgent! I'm visiting Hyakkiyako tomorrow!"
10119-101190090 = "Let's discuss our collaboration with the Hyakkaryouran tomorrow!"
10119-101190100 = "Tomorrow...?"
10119-101190110 = "I could clear some time, but is that...truly okay?"
10119-101190120 = "Is what okay?"
10119-101190130 = "I am nobody."
10119-101190140 = "It would not be right for me to make decisions for the Hyakkaryouran."
10119-101190150 = "Huh? Nagusa! You're the Hyakkaryouran's representative!"
10119-101190160 = "Ah."
10119-101190170 = "Apologies. I forgot again."
10119-101190180 = "Understood. I shall await our meeting tomorrow."
10119-101190190 = "Sensei."
10119-101190200 = "There is a Market Alley Festival being held in Hyakkiyako this weekend. Will you attend? "
10119-101190210 = "Barring work, I'll be there!"
10119-101190220 = "The merchant guild asked me to be there!"
10119-101190230 = "I see."
10119-101190240 = "Then perhaps our paths will cross."
10119-101190250 = "The merchants requested my assistance."
10119-101190260 = "Awesome! What're you going to be doing?"
10119-101190270 = "I will be...grilling skewers at a food stall."
10119-101190280 = "They're apparently lacking in cooking staff."
10119-101190290 = "Oooh! Nagusa-grilled skewers! I need some!"
10119-101190300 = "They'll be selling a large variety of street food."
10119-101190310 = "I have high hopes that it will be an invigorating festival for all."
10119-101190320 = "And I hope you enjoy yourself as well, Sensei."
10119-101190330 = "Thank you, Sensei."
10119-101190340 = "Thanks to your efforts, I had an enjoyable time speaking with people in the shopping district."
10119-101190360 = "Sounds like it was a lot of fun!"
10119-101190370 = "Yes."
10119-101190380 = "I spoke from the heart, as you directed, and my words were well-received."
10119-101190390 = "In fact, they all burst into laughter as I spoke."
10119-101190400 = "Even though I did not tell a joke."
10119-101190410 = "What did you say?"
10119-101190420 = "I may appear to be a mysterious, cool, unapproachable beauty, but please treat me as you would anyone else."
10119-101190430 = "Nagusa."
10119-101190440 = "You're actually a very funny person. Did you know that?"
10119-101190450 = "Is...that so?"
10119-101190460 = "I may be imagining things"
10119-101190470 = "however it would appear the Mouryo have been operating at night, as of late."
10119-101190480 = "Maybe because it's been so hot!"
10119-101190490 = "Not even they can cause trouble in the heat!"
10119-101190500 = "...Perhaps."
10119-101190510 = "The streets echo abandoned under the moon's light as well,"
10119-101190520 = "allowing them to carry out their illicit activities with ease."
10119-101190530 = "To combat this, I intend to increase the frequency of night patrols."
10119-101190540 = "We cannot allow a student to harm themselves during the dark of night."
10119-101190550 = "The Hyakkaryouran sure has it rough."
10119-101190560 = "You have to be careful too, Nagusa!"
10119-101190570 = "Worry not."
10119-101190580 = "My nighttime vision is excellent."
10119-101190590 = "Sensei, have you yet heard tales of the snow maiden?"
10119-101190600 = "She is depicted as a blossoming beauty in many a folklore tale."
10119-101190610 = "I am curious as to why she's described that way."
10119-101190620 = "A lot of reasons...but I can think of one in particular."
10119-101190630 = "Maybe because \"beauty\" tends to draw people's attention?"
10119-101190640 = "Because \"beauty\" is appealing... I see."
10119-101190650 = "People will not fall for a trap with no honey. As such, a \"blossoming beauty\" would be an appropriate lure."
10119-101190660 = "I find myself grateful that I am not a youkai."
10119-101190670 = "I like that confidence!"
