[translation]
13002-1223 = "You know, I've been wondering... Why don't restaurants sell beef bowls larger than king size?"
13002-1224 = "Isn't king size big enough?"
13002-1225 = "No! I can never get full on one king-sized bowl."
13002-1226 = "Akari, why do you eat so much food at once?"
13002-1227 = "Heehee! What a silly question."
13002-1228 = "If I see food...I eat it! All of it!"
13002-1229 = "When you eat ramen, do you eat the noodles or drink the soup first?"
13002-1230 = "Noodles first."
13002-1231 = "Soup first."
13002-1232 = "So you care more about the noodles when it comes to ramen."
13002-1233 = "So you care more about the soup when it comes to ramen."
13002-1234 = "I prefer to start with the soup."
13002-1235 = "The thick soup of a bowl of ramen is its essence, containing its true flavor."
13002-1236 = "When you add the pungent taste of crushed garlic... Ooh, I can't stand how good it is!"
13002-1237 = "That sounds like something an old man would like..."
13002-1238 = "All-you-can-eat is such a great concept."
13002-1239 = "You can eat as much as you want without worrying about the cost..."
13002-1240 = "The person who came up with that idea must be a genius!"
13002-1241 = "And to the owner of the all-you-can-eat restaurant you visited the other day, you must have been a force of nature..."
13002-1242 = "It looks like the challenge for the next eating contest is to eat a lot of curry."
13002-1243 = "I'm not so confident about curry... I should practice."
13002-1244 = "What, there's food you don't like?"
13002-1245 = "It's not that I can't eat it, but there are certain foods that I can't eat a ton of."
13002-1246 = "For example, I drink a lot of water when I eat spicy foods like curry, so I get full really quickly."
13002-1247 = "But I can eat twice as much of foods I prefer, like sushi."
13002-1248 = "Gourmands have preferences too!"
