[translation]
16007-160070010 = "สวัสดีค่ะคุณครู"
16007-160070020 = "คือว่าถ้าไม่เป็นการเสียมารยาท\nฉันจะขอรบกวนเวลาช่วงบ่าย\nของคุณครูสักหน่อยได้ไหมคะ"
16007-160070030 = "ได้อยู่แล้ว มีอะไรเหรอ?"
16007-160070040 = "คือว่าฉันกำลังจะไปซื้อของใช้ที่จำเป็น\nสำหรับภารกิจของสำนักเลขาธิการ\nที่ใกล้ๆ ชาเล่ต์ค่ะ..."
16007-160070050 = "คือว่าฉันไม่ได้ออกมาจากเขตเรดวินเทอร์\nนานแล้ว ฉันเลยไม่ชินกับเส้นทางแถวนี้ค่ะ"
16007-160070060 = "ถ้าคุณครูสะดวก ฉันจะขอรบกวน\nคุณครูให้ไปด้วยกันหน่อยน่ะค่ะ"
16007-160070070 = "ได้สิ"
16007-160070080 = "ขอบคุณค่ะ คุณครู"
16007-160070090 = "ไว้ตอนบ่ายพบกันที่ด้านหน้าย่านการค้า\nนะคะ"
16007-160070100 = "คุณครูคะ ขออภัยที่ติดต่อ\nมากลางดึกนะคะ"
16007-160070110 = "คือว่าการจัดการรายงานการปฏิบัติการ\nของชาเล่ต์ที่เกี่ยวข้องกับทางสหภาพ\nเรดวินเทอร์ล่าช้าไปมากน่ะค่ะ"
16007-160070120 = "กำหนดการส่งรายงานคือวันนี้ค่ะ\nคุณครูไม่ได้ลืมใช่ไหมคะ?"
16007-160070130 = "ขอโทษนะ! ครูลืมไปสนิทเลย!"
16007-160070140 = "ครูจะทำให้เสร็จภายในพรุ่งนี้นะ!"
16007-160070150 = "ฮุฮุ ไม่ต้องรีบร้อนก็ได้นะคะ"
16007-160070160 = "ถ้าเป็นเรื่องที่เกี่ยวข้องกับสหภาพเรดวินเทอร์\nไม่ว่ายังไงฉันก็ \"เลื่อน\" ออกไปได้ค่ะ"
16007-160070170 = "นะ...น่ากลัวสุดๆ!"
16007-160070180 = "เมื่อไม่นานมานี้ เหมือนว่าจะมีพวกสื่อ\nโฆษณาชวนเชื่อเขียนเรื่องใส่ร้ายประธาน\nกระจายไปทั่วสหภาพเรดวินเทอร์เลยค่ะ"
16007-160070190 = "ดูเหมือนคงจะถึงเวลาที่จะจัด\n<การปราศรัยทั่วไปสัญจร> แล้วค่ะ"
16007-160070200 = "การปราศรัยทั่วไปสัญจร?"
16007-160070210 = "คุณครูสนใจการปราศรัยทั่วไป\nสัญจรของโรงเรียนเราเหรอคะ?"
16007-160070220 = "การกล่าวปราศรัยของสหภาพ\nเป็นกิจกรรมที่ช่วยเผยแพร่ความ\nยิ่งใหญ่ของท่านประธานค่ะ"
16007-160070230 = "แต่ว่าเขตปกครองของเรามีขนาดใหญ่\nดังนั้นถ้าจะไปให้ทั่วสหภาพล่ะก็\nคงต้องใช้เวลาสัญจรนานมากค่ะ"
16007-160070240 = "ถ้าคุณครูสะดวกละก็ สนใจเข้าร่วม\nการปราศรัยทั่วไปสัญจรครั้งนี้ไหมคะ?"
16007-160070250 = "ครูสะดวกอยู่แล้วละแต่ว่า..."
16007-160070260 = "ไม่ค่ะ ได้โปรดมาร่วมงานด้วยนะคะ"
16007-160070270 = "ยังมีเรื่องที่ยอดเยี่ยมของท่านประธาน\nเชริโน่มากมายที่ฉันอยากให้คุณครูฟังค่ะ!"
16007-160070280 = "บังคับเข้างั้นเรอะ!"
16007-160070290 = "คุณครูคะ ไม่ทราบว่าตอนนี้\nยุ่งอยู่หรือเปล่าคะ?"
16007-160070300 = "คือว่าฉันมีเรื่องที่อยากให้คุณครูช่วยค่ะ"
16007-160070310 = "อื้อ ได้อยู่แล้ว"
16007-160070320 = "มีเรื่องอะไรเหรอ?"
16007-160070330 = "คือว่าภารกิจใหม่ที่ท่านประธาน\nมอบหมายให้คราวนี้มันยากเกินไป..."
16007-160070340 = "ถึงขั้นว่าอาจจะโดนกวาดล้างได้เลยค่ะ"
16007-160070350 = "ครูขอไม่ยุ่งได้ไหม?"
16007-160070360 = "ไม่ได้ค่ะ! พอฟังแล้วก็คิดจะ\nหนีเลยเหรอคะ..."
16007-160070370 = "ถ้าฉันจะต้องถูกกวาดล้างขึ้นมา\nฉันจะซักทอดว่าคุณครูเป็นผู้ที่\nอยู่เบื้องหลังฉันค่ะ!"
16007-160070380 = "น่ากลัว!"
16007-160070390 = "คุณครูชอบดูหนังประเภทไหนเหรอคะ?"
16007-160070400 = "ครูชอบหนังอินดี้แบบเงียบๆ"
16007-160070410 = "ครูชอบหนังบล็อกบลัสเตอร์สนุกๆ"
16007-160070420 = "งั้นเหรอคะ ฮุฮุ สมกับเป็นคุณครูเลยนะคะ"
16007-160070430 = "แล้วโทโมเอะชอบหนังเรื่อง\nอะไรที่สุดเหรอ?"
16007-160070440 = "หนังที่ฉันชอบที่สุดงั้นเหรอคะ?"
16007-160070450 = "ฉัน..."
16007-160070460 = "ฉันชอบหนังเรื่อง <ผลงานของหนวดผู้ยิ่งใหญ่> ที่สุดเลยค่ะ"
16007-160070470 = "ไม่เคยได้ยินชื่อหนังเลยแฮะ"
16007-160070480 = "แน่นอนอยู่แล้วค่ะ"
16007-160070490 = "หนังเรื่อง <ผลงานของหนวดผู้ยิ่งใหญ่>\nเป็นหนังสารคดีเกี่ยวกับความชื่นชอบ\nและชีวิตประจำวันของท่านประธานค่ะ"
16007-160070500 = "แล้วก็เป็นหนังที่ฉันกำลังวางแผน\nที่จะถ่ายทำต่อจากนี้ด้วยค่ะ!"
16007-160070510 = "คุณครูคะ มาบันทึกผลงานที่ยิ่งใหญ่\nของท่านประธานร่วมกันกับฉันเถอะค่ะ!"
16007-160070520 = "บังคับกันอีกแล้วเรอะ?!"
