[translation]
20000-1298 = "Hey, Sensei. I haven't heard back from you since I called last time."
20000-1299 = "What's going on? Can I go to Schale?"
20000-1300 = "I couldn't reply because my cell phone was broken."
20000-1301 = "The connection is still pretty bad right now."
20000-1302 = "...What?"
20000-1303 = "...That's great."
20000-1304 = "Huh? Isn't that bad?"
20000-1305 = "You'll understand very soon."
20000-1306 = "What do you think about installing a self-destruct device in all your electronics?"
20000-1307 = "Like your TV, your refrigerator, your laptop..."
20000-1308 = "Maybe your microwave, vacuum cleaner, hair dryer... "
20000-1309 = "I can make them all self-destruct if you want."
20000-1310 = "...I'm just joking."
20000-1311 = "I was asked to create a fireworks machine."
20000-1312 = "If it's okay with you, can you come to Millennium and help me out?"
20000-1313 = "Fireworks?"
20000-1314 = "Do you think I'll be helpful?"
20000-1315 = "Yes."
20000-1316 = "I'll be so happy if you come with me."
20000-1317 = "I'm so glad no one got hurt. "
20000-1318 = "My life always feels so exciting...whenever I'm with you."
20000-1319 = "How did you feel about today, Sensei?"
20000-1320 = "It was fun."
20000-1321 = "I thought I was going to die."
20000-1322 = "Today was a complete mess, but maybe next time..."
20000-1323 = "I'll show you something even more amazing. Just watch."
20000-1324 = "Everyone is surprised to learn this, but the Millennium School has a baseball club."
20000-1325 = "They're famous for playing data-driven baseball, which is based on their scientific training..."
20000-1326 = "They might not be the strongest team, but I want to help them."
20000-1327 = "Are you going to be a cheerleader?"
20000-1328 = "Are you going to be their manager?"
20000-1329 = "A cheerleader? Well, I've always wanted to wear one of those uniforms."
20000-1330 = "But unfortunately, no."
20000-1331 = "I want to improve their training equipment."
20000-1332 = "Hm... The only way I can help someone..."
20000-1333 = "is through technology."
20000-1334 = "So, I have a favor to ask."
20000-1335 = "Can you come with me, Sensei?"
20000-1336 = "If I can help someone with something I made..."
20000-1337 = "That would make me so happy."
20000-1338 = "I took an impromptu nap today..."
20000-1339 = "I had a dream about you."
20000-1340 = "What kind of dream?"
20000-1341 = "Heehee. That's a secret."
20000-1342 = "But..."
20000-1343 = "It kind of made me miss you. "
20000-1344 = "I have a problem, Sensei."
20000-1345 = "The Knockout Pipes are flying off the shelves."
20000-1346 = "No way."
20000-1347 = "There were that many students suffering from insomnia?"
20000-1348 = "Yes!"
20000-1349 = "It was selected as a must-have item of the year for female high school students"
20000-1350 = "in some fashion magazine."
20000-1351 = "Now all the famous brands have started designing their own Knockout Pipes."
20000-1352 = "This came as a total shock to me..."
20000-1353 = "So if you see the students at Millennium carrying steel pipes around,"
20000-1354 = "don't be too surprised."
20000-1355 = "I get emotional sometimes."
20000-1356 = "Especially on rainy days."
20000-1357 = "I didn't expect that."
20000-1358 = "Rain seems to strike a chord in people's hearts."
20000-1359 = "Rude, much?"
20000-1360 = "Anyway, this is the perfect time for..."
20000-1361 = "Yeah."
20000-1362 = "Right."
20000-1363 = "I can't seem to control my emotions."
20000-1364 = "On days like this, instead of going to the workshop,"
20000-1365 = "I go somewhere to spend my time more meaningfully."
20000-1366 = "Maybe I should go to the library today?"
20000-1367 = "Your shoulder got all wet, Sensei."
20000-1368 = "Thanks for looking out for me..."
20000-1369 = "If we had brought two umbrellas, this never would have happened... Isn't psychology interesting?"
20000-1370 = "Your behavior is definitely affecting my heart."
20000-1371 = "We have an emergency, Sensei."
20000-1372 = "What's going on?"
20000-1373 = "Try to stay calm."
20000-1374 = "What should I do?"
20000-1375 = "I can't really explain this over text..."
20000-1376 = "Could you help me?"
20000-1377 = "I'll be right there."
20000-1378 = "Should I come to Millennium?"
20000-1379 = "Yes, please!"
20000-1380 = "I'm going to remember the view we saw...for a long time."
20000-1381 = "Thank you so much."
20000-1382 = "...Sensei."
20000-2000010 = "I finished the repairs on your bicycle, Sensei."
20000-2000020 = "Come pick it up, if you're free."
20000-2000030 = "Already? You really do work fast."
20000-2000040 = "I'll head over."
20000-2000050 = "Sounds good. I'll be working on another project in the meantime."
20000-2000060 = "Let me know when you're here."
