[translation]
20033-200330010 = "ในที่สุดก็ถึงเวลาแล้ว คุณครูจาก\nชาเล่ต์"
20033-200330020 = "...?"
20033-200330030 = "หึหึหึ ไม่ต้องตกใจหรอก"
20033-200330040 = "ตอนนี้เราเตรียมการทุกอย่าง\nเพื่อแผนการที่สมบูรณ์แบบของเรา\nไว้พร้อมแล้ว"
20033-200330050 = "นับตั้งแต่วันนี้ไป ท่านฮานุมะ\nมาโคโตะผู้นี้..."
20033-200330060 = "ไม่สิ นับเป็นจุดเริ่มต้นที่ยิ่งใหญ่\nของพวกเราต่างหาก!"
20033-200330070 = "...?"
20033-200330080 = "ถ้างั้น... คุณครูจากชาเล่ต์"
20033-200330090 = "เราจะรออยู่ที่แพนเดโมเนียม โซไซตี้\nก็แล้วกันนะ หึหึหึ"
20033-200330100 = "อืม จะให้ครูไปหาที่แพนเดโมเนียม\nโซไซตี้ใช่มั้ย...? ก็ได้ๆ"
20033-200330110 = "หึหึ สวัสดีคุณครู"
20033-200330120 = "อื้อ... ว่าไง มาโคโตะ "
20033-200330130 = "ได้รับข้อความจากท่านมาโคโตะผู้นี้\nแต่ก็ยังแสดงท่าทางที่นิ่งเฉยได้"
20033-200330140 = "สมแล้วที่เป็นผู้ที่เรานับถือ ถูกใจจริงๆ"
20033-200330150 = "เอ่อ... อืม ขอบใจนะ...?"
20033-200330160 = "เลิกคุยเรื่องไร้สาระเท่านี้ แล้วมา\nเข้าเรื่องกันเถอะ "
20033-200330170 = "เหตุผลที่เราติดต่อมาหาคุณครู\nในวันนี้"
20033-200330180 = "เดี๋ยวนะ...? เรามาถึงแล้วละ"
20033-200330190 = "โอ๊ะ? มาแล้วงั้นเหรอ?"
20033-200330200 = "อืม ไม่ใช่เรื่องใหญ่อะไร เราเพิ่งมาถึง\nด้านหน้าชาเล่ต์เมื่อครู่นี้"
20033-200330210 = "ว่าไงนะ...? อยู่ที่หน้าชาเล่ต์เหรอ?"
20033-200330220 = "คิคิกคิกคิก... ดีละ ถ้างั้นธุระที่ว่า\nเอาไว้คุยกันต่อหน้าก็แล้วกัน"
20033-200330230 = "นี่ เดี๋ยวก่อนสิ เดี๋ยวสิ มาโคโตะ?!"
20033-200330240 = "คิกคิกคิก คิคิ คิกๆๆๆ!!\nสมกับเป็นเราจริงๆ!"
20033-200330250 = "เราหาร้านผู้ผลิตที่บอกไปคราวก่อน\nได้สำเร็จแล้ว! อิโรฮะ!"
20033-200330260 = "นี่คือข้อพิสูจน์ชั้นยอดว่าไม่มีอะไร\nที่ท่านมาโคโตะผู้นี้ทำไม่ได้ยังไงล่ะ!"
20033-200330270 = "เอ้า! รีบหมอบและศิโรราบต่อความ\nยิ่งใหญ่ของเราซะสิ! "
20033-200330280 = "เอ่อ... โทษทีนะมาโคโตะ\nครูไม่เข้าใจที่พูดมาเลย"
20033-200330290 = "หืม...?"
20033-200330300 = "อ๊ะ แย่ล่ะ... "
20033-200330310 = "เจอปฏิกิริยาตอบสนองทั่วๆ ไปแบบนี้\nเราก็ตกใจเหมือนกันนะ"
20033-200330320 = "เดี๋ยวนะ... แชตของคุณครูนี่เอง"
20033-200330330 = "เราส่งข้อความผิดมาให้คุณครูแทน\nอิโรฮะสินะ"
20033-200330340 = "ปกติพวกเธอส่งข้อความ\nคุยอะไรกันเนี่ย?"
20033-200330350 = "ก็แค่คุยเรื่องทั่วไปในชีวิตประจำวัน"
20033-200330360 = "ยังไงเราก็ต้องขอโทษเรื่องที่ส่ง\nข้อความผิดด้วย"
20033-200330370 = "พอมานึกๆ ดูแล้ว สุดสัปดาห์นี้คุณครูก็\nหยุดสินะ"
20033-200330380 = "คิกคิก... ขอให้เป็นวันหยุดที่ดี"
20033-200330390 = "อื้อ ขอให้เป็นสุดสัปดาห์ที่ดี\nของมาโคโตะเหมือนกัน..."
20033-200330400 = "ในที่สุดก็ถึงเวลาแล้วละ คุณครู"
20033-200330410 = "แบบนี้มัน... เดจาวูชัดๆ"
20033-200330420 = "เหมือนเคยเห็นข้อความแบบนี้\nมาก่อนเลยแฮะ..."
20033-200330430 = "คิกๆๆ ไม่ต้องตกใจหรอก คุณครู"
20033-200330440 = "เมื่อครั้งที่แล้วเราแนะนำธุรกิจ\nที่ได้ริเริ่มไปอย่างง่ายๆ แล้ว"
20033-200330450 = "และวันนี้เพื่อฉลองความสำเร็จ\nของธุรกิจ..."
20033-200330460 = "เราเลยติดต่อมาเพื่อจะแสดง\nให้คุณครูเห็นไงล่ะ"
20033-200330470 = "เวลาผ่านไปขนาดนี้แล้วเหรอเนี่ย"
20033-200330480 = "ยังไงก็เถอะ วันนี้ว่างรึเปล่า?"
20033-200330490 = "ก็พอว่างอยู่นะ..."
20033-200330500 = "คิกคิกคิกๆ ดีละ ถ้างั้นเราจะไปรับ\nเดี๋ยวนี้เลย!"
