[translation]
20045-200450010 = "บอส!"
20045-200450020 = "ไม่สิ ท่านอาจารย์!"
20045-200450030 = "พีน่าเองนะคะ!"
20045-200450040 = "สวัสดี พีน่า ไม่ได้คุยกันนานเลยนะ"
20045-200450050 = "ค่ะ! พีน่ากลับมาแล้วค่ะ!"
20045-200450060 = "พีน่าได้เกิดใหม่อีกครั้งเหมือนนกฟีนิกซ์"
20045-200450070 = "ก็เลยติดต่อมาเพราะอยากอวด\nรูปลักษณ์ที่น่าภาคภูมิใจนี้ค่ะ"
20045-200450080 = "ถ้าวันไหนแวะมาเฮียกคิยาโค ก็มาหา\nพีน่านะคะ!"
20045-200450090 = "ต้องมาหากันนะ!"
20045-200450100 = "น่าเสียดายจัง..."
20045-200450110 = "นี่เป็นโอกาสที่จะแสดงให้เห็นถึงเสน่ห์\nของเฮียกคิยาโคแท้ๆ"
20045-200450120 = "น่าเสียดายที่ฉันแนะนำได้ไม่ดีเท่าไร\nเลยค่ะ!"
20045-200450130 = "พอคุณหมาน้อยไปเที่ยวเล่นที่อื่น\nก็สติเตลิดไปเลย..."
20045-200450140 = "ฉันใจร้อนไปหน่อย ก็เลยลืมคิดเรื่อง\nพื้นฐานไปเลยค่ะ..."
20045-200450150 = "แต่ครูว่าความตั้งใจของพีน่ายอดเยี่ยม\nไปเลยนะ"
20045-200450160 = "!!"
20045-200450170 = "น่าตื้นตันใจจังค่ะ คุณครู!!!"
20045-200450180 = "ฉันกลับมามีสติและใจเย็นได้อีกครั้ง\nเพราะได้คุณครูช่วยไว้เลยค่ะ"
20045-200450190 = "ไว้คราวหน้าฉันต้องพาไปชมอะไรที่\nไม่มีปัญหาแบบนี้แล้วละ"
20045-200450200 = "ฉันจะพยายามค่ะ!!"
20045-200450210 = "คุณครู! นี่พีน่าเองนะคะ!"
20045-200450220 = "วันนี้เรามีทัวร์รถบัสพร้อมไกด์ค่ะ"
20045-200450230 = "ยังมีที่นั่งว่างอยู่ที่หนึ่ง ฉันก็เลยมาชวน\nคุณครูค่ะ"
20045-200450240 = "พีน่าจะโชว์ความสามารถให้เห็นเอง!"
20045-200450250 = "วันนี้คิดว่าจะโชว์ความเพอร์เฟ็กต์\nของไกด์ให้คุณครูได้เห็นแล้วเสียอีก"
20045-200450260 = "ครั้งนี้พีน่าก็พลาดอีกแล้ว!"
20045-200450270 = "ต่อไปคงไม่มีหน้าไปเจอคุณครูแล้วค่ะ!!"
20045-200450280 = "แต่คุณครูก็ยังช่วยปกป้องพีน่าที่\nบกพร่องคนนี้..."
20045-200450290 = "พีน่าซึ้งจนน้ำตาไหลเลยค่ะ!!"
20045-200450300 = "พีน่าที่พูดอย่างตรงไปตรงมาแบบนี้\nยิ่งเท่เข้าไปใหญ่เลย"
20045-200450310 = "ครูได้เรียนรู้จากพีน่าเลยนะ"
20045-200450320 = "!!"
20045-200450330 = "เรียนรู้งั้นเหรอคะ!! พีน่าจะไปกล้าสอน\nท่านอาจารย์ได้ยังไง!!"
20045-200450340 = "แต่พอได้ยินคำว่าเท่... มันก็น่าดีใจอยู่\nนะคะ!"
20045-200450350 = "พีน่าจะเอากำลังใจจากคุณครูไปพัฒนา\nตัวเองต่อไปค่ะ!!"
20045-200450360 = "คุณครู พีน่าเองนะคะ!"
20045-200450370 = "วันนี้เป็นวันที่!"
20045-200450380 = "พีน่าจะแสดงฝีมือในฐานะผู้เชี่ยวชาญ\nได้อย่างมั่นใจค่ะ!"
20045-200450390 = "พีน่าอยากให้คุณครูได้เห็นภาพลักษณ์\nที่เปลี่ยนแปลงไปอีกขั้น!"
20045-200450400 = "แล้วพีน่าจะรออยู่ในหมู่บ้านสตูดิโอ\nภาพยนตร์นะคะ!"
20045-200450410 = "อ่า... หน้าฉันยังร้อนวูบวาบอยู่เลยค่ะ..."
20045-200450420 = "ต่อจากนี้ไปคงต้องรอบคอบให้มากกว่า\nนี้แล้ว..."
20045-200450430 = "แต่ทุกคนชอบนะ ไม่ต้องกังวลหรอก"
20045-200450440 = "ครูว่าดีแล้วนะที่พีน่ามีความสามารถ\nในการเป็นผู้นำ"
20045-200450450 = "!!"
20045-200450460 = "ถ้างั้นก็ค่อยยังชั่วหน่อย!"
20045-200450470 = "แหะๆๆ... ฉันจะเก็บความผิดพลาดนี้\nเป็นบทเรียนแล้วพัฒนาตัวเองต่อไปค่ะ"
20045-200450480 = "พีน่าเติบโตได้ด้วยคำสอนของคุณครูค่ะ!"
20045-200450490 = "ตอนนี้ฉันคือไกด์ผู้ผดุงความยุติธรรมที่\nภูมิฐานและไม่ทำผิดพลาดแล้วค่ะ!"
20045-200450500 = "วันนี้เป็นทัวร์ครั้งสุดท้ายแล้ว อยากให้\nคุณครูมาด้วยจังค่ะ!"
20045-200450510 = "แล้วเจอกันตอนนั้นนะคะ!"
20045-200450520 = "บอส"
20045-200450530 = "ไม่ใช่สิ"
20045-200450540 = "คุณครู พีน่าเองนะคะ"
20045-200450550 = "เท่านี้งานที่ย่านการค้าฝากฝังให้ทำก็\nเสร็จเรียบร้อยค่ะ!"
20045-200450560 = "เพราะมีคุณครูคอยดูแล ฉันถึงทำได้\nสำเร็จค่ะ"
20045-200450570 = "ต่อไปพีน่าอยากเป็นมากกว่าไกด์"
20045-200450580 = "พีน่าอยากเป็นเพื่อนร่วมเดินทาง"
20045-200450590 = "แล้วพาคุณครูท่องเฮียกคิยาโคด้วยกัน\nสองคนค่ะ..."
20045-200450600 = "มะ... ไม่สิ! ช่วยลืมที่พูดไปด้วยค่ะ!!"
20045-200450610 = "แบบนั้นก็น่าสนุกนะ"
20045-200450620 = "!!!"
20045-200450630 = "จะมาใช้เวลาร่วมกับพีน่าอีกเหรอคะ!!"
20045-200450640 = "ขะ... ขอบคุณค่ะ!"
20045-200450650 = "ถ้างั้นฉันขอตัวก่อนนะคะ!! บอส!!"
