[translation]
23004-1582 = "เมื่อกี๊ฉันเห็นคุณครูอ่านแคตตาล็อกขาย\nส่งของร้านเครื่องเขียนอย่างตั้งใจมากเลย..."
23004-1583 = "มีอุปกรณ์การสอนที่อยากซื้องั้นเหรอ?"
23004-1584 = "ว่าจะซื้อที่ใส่ดินสอหน่อยน่ะ"
23004-1585 = "ของง่ายๆ อย่างที่ใส่ดินสอนี้ใช้เครื่อง\nพิมพ์สามมิติทำเอาไม่เร็วกว่าเหรอ?"
23004-1586 = "ทำที่ใส่ดินสอจากเครื่องพิมพ์สาม\nมิติได้ด้วยเหรอ?"
23004-1587 = "ทำได้สิ แถมยังออกมาเบาและแข็งแรง\nกว่าที่ขายในร้านเครื่องเขียนซะอีก"
23004-1588 = "ฉันมีวัสดุอยู่พอดี ลองทำดูมั้ย?"
23004-1589 = "ดีเลย งั้นครูฝากด้วยล่ะ"
23004-1590 = "ได้ หนึ่งชั่วโมงหลังจากนี้ก็แวะมาเอาที่\nห้องปฏิบัติงานของชมรมวิศวกรรมนะ"
23004-1591 = "คุณครู ฉันว่าไฟในห้องน้ำของชาเล่ต์\nต้องเสียแน่ๆ"
23004-1592 = "กดสวิทช์ตั้งหลายครั้งแล้ว แต่ไฟก็ไม่\nติดเลย"
23004-1593 = "ไฟเสียเหรอ?\nงั้นต้องเรียกช่างมาซ่อม..."
23004-1594 = "ไม่เป็นไรหรอก แค่สายไฟถูกตัดเอง\nเราซ่อมมันเองได้ง่ายๆ"
23004-1595 = "มีคีมปอกสายไฟมั้ย? เดี๋ยวฉันซ่อมเอง"
23004-1596 = "ชาเล่ต์ไม่มีอุปกรณ์แบบนั้นหรอก..."
23004-1597 = "ที่ชาเล่ต์ไม่มีคีมซักอันเลยเหรอ...?"
23004-1598 = "จริงเหรอ...?"
23004-1599 = "คุณครู เย็นนี้ฝากกิจกรรมตัวแทนนักเรียน\nด้วยนะ"
23004-1600 = "ขอโทษนะ ครูมีงานด่วนเข้ามาน่ะ\nตอนเย็นคงจะไม่ได้อยู่ที่ชาเล่ต์"
23004-1601 = "งานด่วนเหรอ? ถ้างั้นก็ช่วยไม่ได้"
23004-1602 = "มีเรื่องอะไรให้ฉันทำระหว่างที่คุณครูไม่\nอยู่มั้ย?"
23004-1603 = "ช่วงเย็นจะมีพัสดุเข้ามาส่ง\nเธอช่วยรับไว้หน่อยนะ"
23004-1604 = "พัสดุอะไรเหรอ?"
23004-1605 = "ครูสั่งตุ๊กตาน้องหมาไว้น่ะ ว่าจะเอา\nมาวางในห้องนั่งเล่นของชาเล่ต์"
23004-1606 = "ตุ๊กตา... น้องหมาเหรอ?"
23004-1607 = "แต่ขอบอกไว้ก่อนนะ\nเธอห้ามแกะดูของก่อนเด็ดขาด"
23004-1608 = "อุทาฮะ...?"
23004-1609 = "คุณครู ฉันซ่อมล้อจักรยานที่ขอให้ช่วย\nคราวก่อนเสร็จหมดแล้ว"
23004-1610 = "คราวหน้าถ้ามาโรงเรียนมิลเลเนียมก็แวะ\nไปเอาที่ห้องชมรมวิศวกรรมนะ"
23004-1611 = "เสร็จเร็วกว่าที่คิดอีกแฮะ"
23004-1612 = "สมกับเป็นไมสเตอร์แห่งมิลเลเนียม!"
23004-1613 = "ชมอะไรขนาดนั้น งานซ่อมแบบนี้ไม่ใช่\nเรื่องยากหรอกนะ คนอื่นก็ทำได้"
23004-1614 = "ไว้คุณครูลองซ่อมดูเองก็จะรู้ว่าไม่ยากเลย"
23004-1615 = "แต่ครูอยากนั่งดูอุทาฮะซ่อมของ\nนู่นนี่นี่นา..."
23004-1616 = "ไม่ได้หรอก... เพราะในห้องชมรม\nวิศวกรรมมีของอันตรายเยอะเลย..."
23004-1617 = "อีกอย่างงานซ่อมก็ไม่ได้สนุกขนาดนั้นด้วย"
23004-1618 = "ครูจะนั่งเฉยๆ น่า~"
23004-1619 = "ตื๊อเหมือนเด็กเลย อายุเท่าไหร่แล้วเนี่ย?"
23004-1620 = "ตอนนี้ไม่มีอะไรให้ซ่อมหรอก... ต่อไป\nหากต้องซ่อมอะไรฉันจะบอกเอง"
23004-1621 = "จะว่าไป เมื่อกี้เหมือนเห็นเจ้าสายฟ้า\nล้มลงไปหมุนอยู่ในที่เก็บจักรยานเลย"
23004-1622 = "ว่าไงนะ เจ้าสายฟ้าเหรอ?!?!"
23004-1623 = "เหมือนว่า <เซอร์วัล> จะวางขายถุงมือ\nช่างแบบใหม่เลย"
23004-1624 = "ถุงมือที่ซื้อมาจาก <มานาซึรุ> คราวก่อน\nหนามากเลย ฉันกำลังหาถุงมือใหม่อยู่พอดี"
23004-1625 = "เพิ่งสังเกตว่าอุทาฮะสวมถุงมือช่าง\nอยู่ตลอดเวลาเลยนะ"
23004-1626 = "มีเหตุผลอะไรงั้นเหรอ?"
23004-1627 = "ไม่มีเหตุผลอะไรเป็นพิเศษหรอก... ก็แค่\nนิ้วของฉันไม่ค่อยสวยน่ะ"
23004-1628 = "มือฉันจับโลหะและน้ำมันมาตั้งแต่เด็กน่ะ\nปลายนิ้วเลยแตก แถมยังมีคราบน้ำมันอีก\nไม่น่าดูหรอก"
23004-1629 = "ก็เลยสวมถุงมืออยู่ตลอดน่ะ"
23004-230040010 = "คุณครู"
23004-230040020 = "วันนี้พอมีเวลาว่างรึเปล่า?"
23004-230040030 = "อื้อ ครูว่างนะ มีอะไรเหรอ?"
23004-230040040 = "พอดีฉันต้องไปซื้ออุปกรณ์นิดหน่อยน่ะ"
23004-230040050 = "มันมีร้านอุปกรณ์ที่มีแค่ฉันเท่านั้นที่รู้\nอยู่ร้านหนึ่ง"
23004-230040060 = "ถ้าคุณครูว่างก็อยากแนะนำร้านนั้นให้\nรู้จักน่ะ"
23004-230040070 = "ครูว่างเสมอแหละ!"
