[translation]
23008-230080010 = "ขอให้ความสงบสุขและความรื่นรมย์\nจงอยู่กับคุณ"
23008-230080020 = "ถ้าคุณมีสิ่งใดที่กวนใจอยู่ละก็\nโปรดมาพบกับซิสเตอร์ก่อนที่จะสาย\nเกินไปนะคะ"
23008-230080030 = "ถ้าคุณมาไม่ได้ ขอให้บอกฉันนะคะ ฉันจะไปพบคุณเองค่ะ"
23008-230080040 = "..."
23008-230080050 = "อ่า"
23008-230080060 = "ขอโทษด้วยค่ะ ฉันส่งข้อความผิดค่ะ"
23008-230080070 = "ครูไปหาได้มั้ย?"
23008-230080080 = "ไม่ต้องเป็นนักเรียนก็ไปหาซิสเตอร์ได้เหรอ?"
23008-230080090 = "อ่า"
23008-230080100 = "ใช่แล้วค่ะ แน่นอนสิคะ"
23008-230080110 = "ฉันจะรอพบคุณครูด้วยความยินดีค่ะ "
23008-230080120 = "ไม่เป็นไรใช่มั้ยคะคุณครู?"
23008-230080130 = "พอดีของตกแต่งมันตกลงมา ก็เลยตกใจน่ะค่ะ..."
23008-230080140 = "ถ้าร่างกายมีอะไรผิดปกติละก็\nบอกฉันทันทีเลยนะคะ ฉันจะได้ไป\nโรงพยาบาลกับคุณครู..."
23008-230080150 = "ไม่เป็นไรหรอก คงเป็นโทษทัณฑ์\nจากสวรรค์เฉยๆ น่ะ"
23008-230080160 = "แค่เท่านี้อย่าคิดว่าจะยอมแพ้ล่ะ"
23008-230080170 = "..."
23008-230080180 = "?"
23008-230080190 = "คะ...?"
23008-230080200 = "คุณครูคะ วันนี้คุณครูสบายดีรึเปล่าคะ?"
23008-230080210 = "ที่จริง ฉันยังกังวลเรื่องที่เกิดขึ้น\nเมื่อวันก่อนอยู่เลยค่ะ..."
23008-230080220 = "มารีไม่ต้องคิดมากเรื่องนี้หรอก"
23008-230080230 = "เรื่องเมื่อวันก่อน...? เรื่องที่ของตกแต่งตกลงมาน่ะเหรอ?"
23008-230080240 = "ไม่ใช่ค่ะ"
23008-230080250 = "ในฐานะผู้ที่จะเป็นซิสเตอร์แล้ว ฉันคงปล่อยผ่านไปไม่ได้หรอกค่ะ"
23008-230080260 = "ต่อไปฉันจะสวดภาวนาขอให้คุณครู\nปลอดภัยนะคะ"
23008-230080270 = "อืม..."
23008-230080280 = "พอมาคิดดูแล้ววันนี้ก็ไม่ได้มีตาราง\nงานอะไรที่วิหารเลยค่ะ"
23008-230080290 = "คือว่าถ้าคุณครูไม่ว่าอะไรละก็..."
23008-230080300 = "กลับถึงบ้านรึยังคะคุณครู?"
23008-230080310 = "วันนี้ขอบคุณที่คุณครูมาหานะคะ ฉันรู้สึกสบายใจขึ้นมากเลยค่ะ"
23008-230080320 = "ถึงฉันบอกว่าจะสวดภาวนาให้คุณครู\nแต่ที่จริงอาจเป็นการสวดภาวนาให้ตัวเอง\nก็ได้ค่ะ"
23008-230080330 = "ถ้าเป็นแบบนั้นจริงๆ ฉันหวังว่า\nคุณครูจะไม่คิดว่าแรงจูงใจของฉัน\nเป็นเรื่องที่ไม่บริสุทธิ์นะคะ"
23008-230080340 = "ครูคิดว่าไม่ใช่เรื่องที่ไม่บริสุทธิ์หรอก"
23008-230080350 = "ขอบคุณนะ ครูโล่งใจขึ้นเยอะเลยละ"
23008-230080360 = "จริงเหรอคะ?"
23008-230080370 = "ค่อยยังชั่วหน่อยค่ะ ฉันดีใจจริงๆ ค่ะ"
23008-230080380 = "ถ้าอย่างนั้น..."
23008-230080390 = "เอาไว้พบกันใหม่นะคะคุณครู"
23008-230080400 = "ขอให้ความสงบสุขและความรื่นรมย์\nจงอยู่กับคุณ"
23008-230080410 = "ถ้าคุณครูมีเรื่องไม่สบายใจละก็\nฉันจะภาวนาให้เรื่องไม่สบายใจของคุณครู\nหายไปโดยเร็วนะคะ"
23008-230080420 = "ต้องขออภัยด้วยนะคะ\nที่วันนี้ไปพบที่วิหารไม่ได้ค่ะ"
23008-230080430 = "มารี วันนี้ไม่ได้ไปที่วิหารเหรอ?"
23008-230080440 = "สงสัยวันนี้คงจะยุ่งสินะ"
23008-230080450 = "เปล่าค่ะคุณครู ไม่มีอะไรหรอกค่ะ"
23008-230080460 = "คือว่า... วันนี้ฉันไม่ค่อยสบาย..."
23008-230080470 = "ไม่สบายงั้นเหรอ!?"
23008-230080480 = "เป็นอะไรน่ะ? เป็นไข้หวัดเหรอ...?"
23008-230080490 = "อ่า ขอโทษด้วยค่ะ"
23008-230080500 = "ฉันไม่ควรบอกคุณครูเลย\nฉันไม่เป็นอะไรจริงๆ ค่ะ"
23008-230080510 = "ฉันแค่รู้สึกเพลียๆ พักสักหน่อย\nก็คงดีขึ้นค่ะ"
23008-230080520 = "ฉันลืมแล้วเผลอหลับไปเลยไม่ได้ทัน\nบอกคุณครูค่ะ"
23008-230080530 = "วันนี้ขอบคุณที่มานะคะคุณครู"
23008-230080540 = "ถึงฉันจะไม่มีอะไรที่จะตอบแทนคุณครูได้"
23008-230080550 = "ถ้างั้นฉันจะสวดภาวนาให้คุณครูเสมอๆ\nแทนนะคะ"
23008-230080560 = "เหมือนกับตอนนี้ค่ะ"
23008-230080570 = "สวัสดีค่ะคุณครู"
23008-230080580 = "คือว่า... คุณครูพอจะมีเวลาว่างรึเปล่า\nคะ? ฉันไม่ได้รบกวนคุณครูใช่มั้ยคะ?"
23008-230080590 = "ไม่เลยๆ มีอะไรรึเปล่า?"
23008-230080600 = "รบกวนอะไรกัน ไม่รบกวนสักนิดเลย"
23008-230080610 = "ค่อยยังชั่วหน่อยค่ะ"
23008-230080620 = "เอ่อ..."
23008-230080630 = "อืม... ขออภัยด้วยค่ะ ฉันไม่ค่อยคุ้นเคย\nกับสถานที่แบบนี้..."
23008-230080640 = "ถ้าคุณครูไม่ว่าอะไร ฉันจะขอนัดวันที่\nคุณครูสะดวกได้มั้ยคะ"
23008-230080650 = "อ่า... ไม่ใช่เรื่องไม่ดี หรือว่าเรื่องที่\nต้องกังวลหรอกค่ะ เผื่อคุณครูจะกังวล..."
23008-230080660 = "โชคดีจังที่คุณครูสะดวกนะคะ\nขอบคุณมากค่ะ"
23008-230080670 = "แล้วพบกันนะคะคุณครู"
23008-230080680 = "คุณครู ขอบคุณสำหรับเรื่องวันนี้นะคะ"
23008-230080690 = "ฉันไม่รู้ว่าคุณครูคิดยังไง\nแต่ฉันดีใจมากเลยค่ะ"
23008-230080700 = "ไม่รู้ว่าต่อไปจะขอให้คุณครูออกมาพบ...\nเพราะเรื่องแบบนี้ได้รึเปล่า"
23008-230080710 = "แต่ว่ายังไงก็ขอรบกวนด้วยนะคะ\nถ้างั้นวันนี้ขอตัวก่อนค่ะ"
23008-230080720 = "คุณครู..."
23008-230080730 = "ฉันแค่อยากเรียกดูก็เท่านั้นค่ะ..."
23008-230080740 = "สวัสดีค่ะคุณครู"
23008-230080750 = "ถ้าวันนี้คุณครูพอมีเวลา..."
23008-230080760 = "ครูมีเวลาให้มารีอยู่แล้ว"
23008-230080770 = "ให้ไปที่ไหนล่ะ?"
23008-230080780 = "ตะ... ตอบเร็วมาก..."
23008-230080790 = "คือว่าฉันต้องไปซื้อของใช้ของชมรม\nซิสเตอร์น่ะค่ะ"
23008-230080800 = "และคิดว่าแค่ฉันคนเดียวคงถือไม่ไหว..."
23008-230080810 = "ฉันรู้ค่ะว่ามันน่าละอายที่มารบกวน\nคุณครู..."
23008-230080820 = "เรื่องแบบนี้ครูถนัดเลยนะ"
23008-230080830 = "ให้ไปเจอที่ไหนล่ะ?"
23008-230080840 = "ขอบคุณเสมอๆ เลยนะคะคุณครู..."
23008-230080850 = "วันนี้ต้องขอบคุณคุณครูในหลายๆ เรื่อง\nเลยค่ะ"
23008-230080860 = "ทั้งเรื่องที่พามาส่ง แล้วก็เรื่องอาหาร..."
23008-230080870 = "ครูเสียดายนิดหน่อยที่ให้เครื่องประดับ\nเป็นของขวัญไม่ได้"
23008-230080880 = "ฮุฮุ ฉันไม่เสียดายอะไรเลยค่ะ"
23008-230080890 = "ขอบคุณคุณครูที่สละเวลาให้ฉันในวันนี้"
23008-230080900 = "ความรู้สึกที่อัดแน่นอยู่ภายในเข็มกลัด\nติดเสื้ออันนี้มีความหมายขึ้นเยอะเลยค่ะ"
23008-230080910 = "เท่านั้น... ก็เพียงพอแล้วค่ะ"
