[translation]
23006-2449 = "\"Momoyodou Pavilion x Kivotos Strawberry Heaven campaign begins!\""
23006-2450 = "\"Strawberry rice cakes! Strawberry bread! Strawberry pastries! Strawberry yatsuhashi! And strawberry anmitsu!\""
23006-2451 = "\"Taste Momoyodou's traditional strawberry-filled desserts from all around Kivotos!\""
23006-2452 = "\"One week from today! Come feast at the Strawberry Festival!\""
23006-2453 = "\"Show this text message for 10% off!\""
23006-2454 = "\"We'll be waiting for you at Momoyodou! Nyan!\""
23006-2455 = "Huh?"
23006-2456 = "Nyan...?"
23006-2457 = "Heeheehee! Sensei!"
23006-2458 = "There's an event at Momoyodou!"
23006-2459 = "I'm going to give you the best treat ever!"
23006-2460 = "Can you please come to see me?"
23006-2461 = "After I check my schedule..."
23006-2462 = "You're going to come, right?"
23006-2463 = "Well, if that's what you want, Shizuko."
23006-2464 = "Heeheehee. Yay! "
23006-2465 = "I'll be waiting!"
23006-2466 = "It didn't work out this time."
23006-2467 = "But I'm going to try again!"
23006-2468 = "With my scatterbrained charm!"
23006-2469 = "Is being scatterbrained charming?"
23006-2470 = "You just watch and see!"
23006-2471 = "Um... Okay..."
23006-2472 = "Sensei... "
23006-2473 = "I... I..."
23006-2474 = "I can't stand it anymore..."
23006-2475 = "You should go before it's too late."
23006-2476 = "Don't forget to wash your hands after you're done."
23006-2477 = "What? How can you say that to the mascot of Momoyodou?!"
23006-2478 = "Why would such a conversation even happen on MomoTalk?"
23006-2479 = "Huh? Oh, no..."
23006-2480 = "Hmm...Sensei...I..."
23006-2481 = "Want to start over?"
23006-2482 = "Ugh... Fine."
23006-2483 = "As president of the Festival Operations Department, I would like to make a request!"
23006-2484 = "Please come help us prepare for the festival!"
23006-2485 = "That's fine, but... What were you saying earlier?"
23006-2486 = "Then why did you say you can't stand it anymore?"
23006-2487 = "End of conversation!"
23006-2488 = "It's too embarrassing! Let's talk about something else!"
23006-2489 = "Sensei..."
23006-2490 = "What's wrong?"
23006-2491 = "Oh, never mind. It's nothing."
23006-2492 = "I'm sure you're busy today."
23006-2493 = "Heehee. Yes, let's work hard today!"
23006-2494 = "Heeheehee!"
23006-2495 = "Bahaha?"
23006-2496 = "Heehee...?"
23006-2497 = "I never laugh like that! I'm not an old man!"
23006-2498 = "It's written right up there! I wrote \"Heeheehee!\""
23006-2499 = "So what's up?"
23006-2500 = "You mentioned last time..."
23006-2501 = "To tell you when I'm having a hard time."
23006-2502 = "So there's something I need you to do today."
23006-2503 = "I'll be waiting for you at Momoyodou."
23006-2504 = "P.S. Please come to the back door. Not the front."
23006-2505 = "Hm?"
23006-23006010 = "Sensei! Sensei!"
23006-23006020 = "The Momoyodou's special seasonal event is starting!"
23006-23006030 = "It's the Apple Fair!"
23006-23006040 = "A banquet of fresh apple tea and other sweet desserts!"
23006-23006050 = "I can't miss out on this!"
23006-23006060 = "Fufufufu"
23006-23006070 = "Please come visit!"
23006-23006080 = "Of course, you can expect the best service when you do!"
