[translation]
23001-1449 = "I have a favor to ask, Sensei."
23001-1450 = "Do you have time today?"
23001-1451 = "Sure, no problem."
23001-1452 = "Yay!"
23001-1453 = "I'll wait for you at the student dining hall."
23001-1454 = "Thanks for your help today."
23001-1455 = "It was nothing."
23001-1456 = "I'll pay you back for today."
23001-1457 = "You won't be disappointed."
23001-1458 = "It's all done, Sensei."
23001-1459 = "Done? What's done?"
23001-1460 = "Come to the Gehenna student dining hall to find out!"
23001-1461 = "I'll show you the power of Fuuka!"
23001-1462 = "S-Sorry, Sensei."
23001-1463 = "I really wanted to give you something good to eat..."
23001-1464 = "I'm so sorry about today!"
23001-1465 = "Are you awake, Sensei? How are you feeling?"
23001-1466 = "Yes, I'm up."
23001-1467 = "I'm okay. I feel fine."
23001-1468 = "Phew, that's a relief."
23001-1469 = "I want to redeem myself for that failure from before."
23001-1470 = "I have a great idea..."
23001-1471 = "Can I see you this afternoon, Sensei?"
23001-1472 = "Of course."
23001-1473 = "Okay then, I'll be waiting!"
23001-1474 = "What did you think about the eel today?"
23001-1475 = "I hope it suited you."
23001-1476 = "I'll serve you something even better next time!"
23001-1477 = "I have a dish I made using a new recipe, Sensei."
23001-1478 = "I want you to try it!"
23001-1479 = "If you have time..."
23001-1480 = "A new menu item from Fuuka? I'm there!"
23001-1481 = "Heehee! Then I'll be waiting!"
23001-1482 = "Sensei."
23001-1483 = "You promised to help me during lunch today. You haven't forgotten, have you?"
23001-1484 = "I remember."
23001-1485 = "Did I say that?"
23001-1486 = "Oh, yeah. What a relief. ♪"
23001-1487 = "Oh, we must have miscommunicated."
23001-1488 = "I'm just joking."
23001-1489 = "Oh, it was a joke..."
23001-1490 = "Don't be like that..."
23001-1491 = "Are you trying to hurt my feelings?"
23001-1492 = "I'm sorry!"
23001-1493 = "Huh? It was a joke!"
23001-1494 = "You got me!"
23001-1495 = "Haha! That's enough fooling around for today."
23001-1496 = "I'll wait for you at the student dining hall!"
23001-1497 = "Sensei..."
23001-1498 = "What happened today..."
23001-1499 = "What happened?"
23001-1500 = "It was cute, Fuuka."
23001-1501 = "Please don't tell anyone! Please!"
