[translation]
26005-1699 = "Um, Sensei? Are you free right now? You are, right?"
26005-1700 = "I have a small favor. It's nothing super important!"
26005-1701 = "So it's okay if you're busy. It's nothing special."
26005-1702 = "I actually am a little busy."
26005-1703 = "Of course I'm free. I'm just a benchwarmer, after all."
26005-1704 = "I thought you might be..."
26005-1705 = "Okay. I won't bother you. Sorry."
26005-1706 = "What? That's not what I mean!"
26005-1707 = "You know what I meant!"
26005-1708 = "I'm just joking."
26005-1709 = "You're making fun of me again."
26005-1710 = "I'll make you pay someday..."
26005-1711 = "Anyway, so you can help me, right? You'd better make up for teasing me just now."
26005-1712 = "I'll meet you at Cafe Mille-Feuille."
26005-1713 = "And don't tell anyone about this."
26005-1714 = "I'll call you again later. It'll be my treat!"
26005-1715 = "Are you free right now, Sensei?"
26005-1716 = "You remember that we promised to meet, right? It's my treat this time."
26005-1717 = "Let me just inform you right now that you have no choice but to say yes."
26005-1718 = "...Hmm, that sounded really awkward."
26005-1719 = "What I'm trying to say is, I want to pay off my debt! Settle what I owe you! Nothing else!"
26005-1720 = "I wouldn't mind if it was something else."
26005-1721 = "I know. A promise is a promise."
26005-1722 = "Can you please stop saying things like that? It really gets my heart going."
26005-1723 = "Good. I'll be waiting for you, so don't be late!"
26005-1724 = "Don't tell anyone!"
26005-1725 = "Absolutely no one!"
26005-1726 = "And nuh uh, no BUTS!"
26005-1727 = "One word and you're dead!"
26005-1728 = "Do you have time to spare, Sensei?"
26005-1729 = "It's nothing serious, but I need some help."
26005-1730 = "What are we gonna eat this time?"
26005-1731 = "Do I look like a pig to you?"
26005-1732 = "Do you think all I do is eat all day?"
26005-1733 = "No, not at all! I just need your help!"
26005-1734 = "I'm asking you because you're my teacher."
26005-1735 = "I'm joking. Where do you want to meet?"
26005-1736 = "..."
26005-1737 = "You can't just say things like that and laugh it off..."
26005-1738 = "Anyway, thanks. I'll tell you where to meet me."
26005-1739 = "Thank you so much for today."
26005-1740 = "I'll give you a shout again, Sensei!"
26005-260050010 = "I really don't wanna go to class today..."
26005-260050020 = "Is there any way for me to get out of this, Sensei?"
26005-260050030 = "Today...? Is there something wrong?"
26005-260050040 = "Besides, you're asking me, your teacher? Haha"
26005-260050050 = "I know, I know. I shouldn't say things like that to you, Sensei."
26005-260050060 = "It's just that Cafe Mille-Feuille is supposed to unveil their newest item today..."
26005-260050070 = "The reveal happens during class, but it's not a big deal. Don't worry about it."
26005-260050080 = "Let's just focus on class for now."
26005-260050090 = "Oh, I see. I get you."
26005-260050100 = "Yeah, I'm sorry. You're right..."
26005-260050110 = "...?"
26005-260050120 = "Don't worry about it, it's just my typical nonsense... Anyway, I got it."
26005-260050130 = "Talk to you later! //(￣︶￣*))"
26005-260050140 = "That was the best!"
26005-260050150 = "Mille-Feuille never disappoints!"
26005-260050160 = "What did you think, Sensei? Did you like it? The Sunshine Mousse, I mean."
26005-260050170 = "Oh..."
26005-260050180 = "Never mind."
26005-260050190 = "Wait, don't say anything. Not a word."
26005-260050200 = "You're probably gonna say something weird again and ruin the moment."
26005-260050210 = "..."
26005-260050220 = "Heehee"
26005-260050230 = "See ya later, Sensei!"
26005-260050240 = "Ah."
26005-260050250 = "Right, Sensei. I've been thinking about it..."
26005-260050260 = "Do you have a cafe you want to go to?"
26005-260050270 = "You find a good cafe?"
26005-260050280 = "?"
26005-260050290 = "I haven't even said anything yet."
26005-260050300 = "I mean, it IS a cafe, but..."
26005-260050310 = "Haha"
26005-260050320 = "Well, I guess it's always like this when we talk."
26005-260050330 = "Ah."
26005-260050340 = "AHHH!!!"
26005-260050350 = "I'm pissed!"
26005-260050360 = "I'm so annoyed!!"
26005-260050370 = "Haha"
26005-260050380 = "Hahahaha"
26005-260050390 = "Hahahahahahahahaha!"
26005-260050400 = "To pretend to treat me...and then to eat it yourself..."
26005-260050410 = "How could you?! You devil!!"
26005-260050420 = "I don't wanna hear it."
26005-260050430 = "You had it coming."
26005-260050440 = "And..."
26005-260050450 = "Heehee"
26005-260050460 = "I'll treat you again."
26005-260050470 = "Try to actually get some next time, Sensei."
26005-260050480 = "Got it?"
