[translation]
10003-20 = "啊哈哈…雖然是有很多不足的我，\n不過請多多指教。"
10003-30 = "佩洛洛大人的周邊…"
10003-40 = "啊哈哈…\n如何呢。"
10003-50 = "下次和大家一起來\n好像也不錯。"
10003-60 = "這種東西\n似乎也很好玩呢。"
10003-70 = "嗯…\n怎麼樣呢…"
10003-80 = "老師，請多多指教。"
10003-90 = "啊，老師。\n你回來了嗎？"
10003-100 = "我會全力以赴的。"
10003-110 = "這個嗎？\n這是佩洛洛大人。"
10003-120 = "可愛吧？"
10003-130 = "…煩惱嗎？我想想…\n我那個，和其他人相比\n不覺得太平凡了嗎…？"
10003-140 = "有什麼我可以做的事嗎？"
10003-150 = "啊哈哈…就算那樣搖\n也不會跑出什麼啊…"
10003-160 = "被老師教導各種事\n我真的很幸福。\n我今後也會繼續努力！"
10003-170 = "因為這就是我能給老師的，\n最棒的禮物！"
10003-180 = "老師！\n謝謝你幫我慶祝生日！\n我，真的很開心！"
10003-190 = "新，新年快樂！\n我今年也會和老師一起…\n努力加油的！"
10003-200 = "聖誕快樂～\n是聖誕祭。"
10003-210 = "在三一是\n最特別的日子。"
10003-220 = "然後…\n對我也是，最特別的。"
10003-230 = "哇啊！\n嚇我一跳。"
10003-240 = "啊，原來今天是萬聖節呢。"
10003-260 = "接下來要去哪兒呢？\n那邊嗎？\n嗯～～這樣的話\n去那裡怎麼樣呢？"
10003-270 = "嗯，去哪裡都可以。\n只要跟老師在一起的話！"
10003-280 = "老師，請看那裡！\n那裡也，啊，還有這裡！"
10003-290 = "明明是平時看習慣的街道，\n為什麼變得這麼不一樣呢？"
10003-300 = "嗯？要在這裡休息到什麼時候呢？"
10003-310 = "來吧！\n再一起到處走走吧！"
10003-320 = "什麼？你說從那個角度看的\n景色很不錯嗎？"
10003-2600 = "這個……這個武器是……該不會！？\n這樣子我再稍微有自信一些也沒關係吧！？"
