[translation]
10007-20 = "呀，老師！要不要一起去塗鴉啊～？"
10007-30 = "如果在這裡的牆壁加上\n我的塗鴉的話，\n感覺會更棒！"
10007-40 = "這種輕飄飄的感覺\n該怎麼用噴漆來展現呢？"
10007-50 = "哎呀。\n注意不要沾到塗料，\n小心，再小心……"
10007-60 = "這裡再加點紅色怎麼樣？"
10007-70 = "…顏色真棒…"
10007-80 = "歡迎回來，老師。\n今天的時裝也很不錯呢！"
10007-90 = "真慢啊，老師！\n再讓我等下去的話…"
10007-100 = "老師的手機\n就會咚哐！爆炸唷。"
10007-110 = "我的臉上沾到什麼了嗎？"
10007-120 = "…嗯？塗料？"
10007-130 = "這個街頭塗鴉很棒對吧？\n是我畫的哦！"
10007-140 = "難得突破了保全，"
10007-150 = "如果沒有留下足跡的話，\n就沒有駭入的意義了吧。呵呵。"
10007-160 = "TANGO DOWN！"
10007-170 = "奇普托斯中央的\n聖所之塔的外牆，"
10007-180 = "如果畫滿塗鴉的話，\n該有多棒啊……？"
10007-190 = "老師，生日快樂！"
10007-200 = "嗯？\n為什麼我會知道？"
10007-210 = "哎呀，\n是還沒有公開的情報嗎？"
10007-220 = "問我想要什麼禮物，是嗎？"
10007-230 = "能在老師的衣服上，\n塗上我選的顏色嗎？"
10007-240 = "Happy New Year, 老師！"
10007-250 = "今年也畫很多\n閃閃發光的東西！"
10007-260 = "到處都是\n漂亮的燈飾……"
10007-270 = "可以把這個景象\n直接畫在牆上嗎？"
10007-280 = "為了這次的萬聖節，\n我從上個月就開始準備服裝了。"
10007-290 = "呵呵，敬請期待！"
10007-310 = "好，這樣\n感覺不錯吧？\n從老師來看，如何？"
10007-320 = "咦咦…為什麼反應\n那麼平淡？"
10007-330 = "再多燃燒點藝術魂\n來看嘛！"
10007-340 = "老師你畫了什麼？\n我看看…"
10007-350 = "啊哈哈！這是什麼，\n真有趣！"
10007-360 = "你問我這麼高\n不會怕嗎？\n沒事，\n因為有老師在身邊啊。"
10007-370 = "有需要的話隨時叫我。\n牆壁也好，老師也好，\n我都會塗上不錯的色彩！"
10007-2600 = "我要用這把槍，\n讓世界染上繽紛的色彩！"
