[translation]
10006-20 = "你就是老師嗎？從今天開始我會陪你的。\n任務的話，就交給我吧。"
10006-30 = "嘿～感覺不錯嘛。"
10006-40 = "稍微休息一下再走吧。"
10006-50 = "實現正義部的傢伙們真令人頭痛…"
10006-60 = "真是的，沒辦法了。\n我幫你吧。"
10006-70 = "唉，怎麼會變成這樣。\n算了…這樣也不錯。"
10006-80 = "呀，歡迎回來。\n老師，今天的任務是什麼？"
10006-90 = "別想偷懶哦，\n我會一直看著你的。"
10006-100 = "……不，不是那種奇怪的意思！"
10006-110 = "我稍微有點時間……\n就幫你一下吧。"
10006-120 = "喜歡惹事的傢伙\n怎麼會這麼多。"
10006-130 = "嘛，我也不會說\n一定要遵守規矩。"
10006-140 = "只是不遵守的話，\n就需要負起責任。"
10006-150 = "沒有所有人都能\n接受的規則。"
10006-160 = "所以才有\n強制執行的必要。"
10006-170 = "老師，\n我相信你的指揮能力哦。"
10006-180 = "嗯！？什，什麼？\n今天是你的生日嗎？"
10006-190 = "真，真拿你沒辦法。\n今天，那個，\n不管什麼任務，\n我都會幫忙的！"
10006-200 = "謝謝你的祝福。"
10006-210 = "我也多少成長了一點……\n今後要不要再試著\n稍微認真一點呢……？"
10006-220 = "老師，\n新的一年也一起加油吧。"
10006-230 = "聖誕節啊。\n雖然現在已經\n失去原本的意義了。"
10006-240 = "不過現在這樣也不錯。"
10006-250 = "Trick or Treat，是嗎。\n嘛，是個有意思的日子。"
10006-260 = "怎麼樣，老師？\n要不要一起到外面看看？"
10006-280 = "怎樣，你那個表情。\n該不會在想奇怪的事吧？"
10006-290 = "要看到什麼時候？\n快點。"
10006-300 = "嗯…嗯唔，\n哈唔…"
10006-310 = "你問我是不是很痛？\n格，格黑娜的風紀委員\n才不會因為這點程度\n就感覺到痛好嗎！"
10006-320 = "只是…有點，\n癢而已。"
10006-330 = "你在做什麼，\n繃帶都鬆掉了。"
10006-340 = "如果是老師的話…\n被手觸碰這種程度\n我不介意。"
10006-350 = "好好，\n做到最後。"
10006-2600 = "用成果來報答。\n能證明我現在的心情的，\n只有這個方法了。"
