[translation]
10008-10 = "蔚藍檔案"
10008-20 = "啊啊？？？\n真是的，結果還是被找到了啊。\n事已至此，我也只能幫忙了啊。"
10008-30 = "嘿，\n是個好地方嘛。"
10008-40 = "什麼？\n你是在鼓勵我嗎？\n哈！真有趣。"
10008-50 = "最有趣的事？\n嘛，那就是打贏對方。"
10008-60 = "呃…所以說…\n笨，笨蛋！老師這個大笨蛋！"
10008-70 = "唔…雖然很羞恥，不過\n謝，謝啦！"
10008-80 = "吶…所以說那個…\n一，一起走吧！"
10008-90 = "呦，老師！\n真慢呢。"
10008-100 = "來吧，老師！\n今天也開心地過吧！"
10008-110 = "真是的，竟然讓我等，\n真是讓人傻眼。"
10008-120 = "那～麼，\n要不要去打掃一下？"
10008-130 = "跟最厲害的人一起工作的感覺，\n已經懂了吧？"
10008-140 = "工作要做確實哦。"
10008-150 = "需要幫忙的時候\n隨時告訴我吧。\n什麼都會幫你做的。"
10008-160 = "呦，老師。生日快樂！\n那個……我有個……\n不小心拿到的蛋糕……"
10008-170 = "……你要吃嗎？"
10008-180 = "哈哈，老師！\n知道今天是什麼日子嗎？\n其實不知道也沒關係。"
10008-190 = "我要收到禮物。\n現．在．立．刻！"
10008-200 = "呦，老師。新年快樂。\n今年也……就是……"
10008-210 = "啊啊真是的！請多多指教啦！！"
10008-220 = "呦，老師。\n聖誕快樂…對吧？"
10008-230 = "…沒有嗎？\n我是說禮物！"
10008-240 = "呦，老師。\n不給糖就搗蛋哦。"
10008-250 = "…啊？\n不知道什麼意思嗎？"
10008-270 = "歡迎，老師。\n只屬於我的特等席，\n歡迎你哦！"
10008-280 = "我喜歡這間學園。\n還有…這一瞬間。"
10008-290 = "你問不會怕嗎？完全不會。\n只是，會很興奮。"
10008-300 = "嘛，偶爾翹課也不錯啊。\n哈哈哈！"
10008-2600 = "鬼有金棒、龍有翅膀。\n而我有兩把衝鋒槍！"
