[translation]
10009-10 = "블루 아카이브~!"
10009-20 = "우와-!! 날 찾아준 거야?\n같이 맛있는 거 먹자!!"
10009-30 = "햄버거가 열리는\n나무가 있으면 좋겠어!\n언젠가 개발되지 않으려나?"
10009-40 = "좋아!\n음식을 찾아보겠어!"
10009-50 = "좋아,\n오늘도 힘내자!"
10009-60 = "특기가 뭐냐고?\n응! 먹는 거지!"
10009-70 = "식사 시간이면\n날 불러야지!"
10009-80 = "어서 와 선생님!\n기다리고 있었어!\n빨리 밥 먹으러 가자!"
10009-90 = "어… 일해야 한다고?"
10009-100 = "선생님!\n오늘은 무엇을 먹으러 갈까~"
10009-110 = "임무부터라고?"
10009-120 = "아니, 밥부터잖아!"
10009-130 = "나쁜 식당을 혼내주러\n가는 임무 없으려나."
10009-140 = "샬레 근처에 맛집은\n뭐가 있으려나?"
10009-150 = "트리니티 쪽 식당을\n털어본 적은 있는데…."
10009-160 = "아!\n이거 말하면 안 되는 거였나…?"
10009-170 = "응? 그 과자 주는 거야?"
10009-180 = "역시 선생님은 친절해!"
10009-190 = "(아까 그 문어 팬케이크….\n맛있어 보이던데….)"
10009-200 = "행복을 가져다 주는 파랑새…?"
10009-210 = "음… 치킨 맛이겠네."
10009-220 = "선생님! 생일이야?"
10009-230 = "그럼 카페를 전세내서\n하루종일 케이크를 먹자!"
10009-240 = "내가 하루종일 함께 있을게!"
10009-250 = "짜잔~\n오늘이 무슨 날인줄 알아?"
10009-260 = "엣헴!\n무조건 맛있는 걸 먹는 날이야~!"
10009-270 = "함께 케이크 먹자!\n특별히 나눠줄 테니까?"
10009-280 = "설날이야!\n어서 떡이랑 팥죽 먹어야지!"
10009-290 = "저쪽에 가면 감주도 준대!"
10009-300 = "크리스마스라…"
10009-310 = "칠면조와 생크림\n케이크가 맛있지~"
10009-320 = "두 개를 합쳐\n먹으면 더 맛있지~"
10009-330 = "안녕 선생님!\nTreat or Treat야!\n빨리 나가보자!"
10009-340 = "수박만한 사탕도 있대!"
10009-360 = "고, 고양이들이 하도\n맛있게 먹고 있다 보니,\n나도 모르게…!"
10009-370 = "후에에엥?!\n자, 잠깐만 할퀴지 마아!"
10009-380 = "왜애~!?\n고양이들이 습격해온다~!"
10009-390 = "하, 하지만!\n엄청 맛있어 보였는걸!"
10009-400 = "그, 그리고! 나,\n미식연구회의 일원이니까!"
10009-410 = "신경 쓰인 건\n일단 먹어보지 않으면……!"
10009-420 = "더군다나 이거\n<참치맛>, <고급> 이라고\n쓰여 있었고……!"
10009-430 = "이런 좋은 걸\n너희들끼리만\n먹다니 용서 못 해!"
10009-440 = "맛있는 건\n같이 나눠 먹어야지!"
10009-450 = "아얏! 그, 그러니까\n미안하다니까!"
10009-460 = "하지만, 이미\n먹어버린 건\n어쩔 수 없지……?"
10009-470 = "후에에!\n깨물지 마아~!"
10009-2600 = "맛있는 걸 먹기 위한 도구가\n또 하나 늘어나 버렸어!\n물론 젓가락 같은 그런 거랑은 다르지만…….\n이걸로 이것저것 잔뜩 또 먹자, 선생님!"
