[translation]
10017-20 = "赤冬聯邦學園書記長大駕光臨！\n這是你的榮幸，同志！"
10017-30 = "唔呣，很好很好。\n書記長很滿意。"
10017-40 = "唔呣，沒有異常。"
10017-50 = "耶嘿，書記長\n大駕光臨哦。"
10017-60 = "今天也很和平，非常好！\n這都是多虧了咱啊！"
10017-70 = "（鬍子……\n沒有掉下來吧？）"
10017-80 = "等你很久囉，同志！\n要做的事情堆積如山！\n絕不允許偷懶！"
10017-90 = "你來啦，同志！\n必須一起處理的任務有很多，\n做好心理準備吧！"
10017-100 = "你叫咱嗎，同志？"
10017-110 = "今天也和咱一起，\n發起革命吧！"
10017-120 = "終於理解咱的權威了嗎？"
10017-130 = "放心，沒什麼好怕的。\n咱可是很寬容的！"
10017-140 = "嗯？\n鬍子掉下來了……？"
10017-150 = "噫啊啊！？不，不行！\n咱的權威啊……！？"
10017-160 = "……什麼嘛，黏得好好的不是嗎！\n再這樣一直開玩笑的話，\n咱要肅清了喔！？"
10017-170 = "呵呵呵，呵呵呵呵……\n沒想到今天也能一整天\n都和同志待在一起呢。"
10017-180 = "生日？\n是今天嗎？"
10017-190 = "好，那麼就把同志出生的\n這一天訂為赤冬的紀念日！"
10017-200 = "啊，唔……\n總覺得有點害羞呢……"
10017-210 = "如果被祝福的話，\n權威就……"
10017-220 = "不，不是，當然很開心！\n謝謝你啦，同志！"
10017-230 = "新年快樂，同志。\n今年的計畫訂好了嗎？"
10017-240 = "如果還沒的話，\n就和咱一起決定吧！"
10017-250 = "今天是聖誕節！\n聽說留著大鬍子的紅色老人\n會分送禮物……"
10017-260 = "真不錯！\n咱也想要禮物！"
10017-270 = "大家都穿著華麗的裝扮……\n原來如此，是萬聖節啊。"
10017-280 = "嗯？不對，這個鬍子\n可不是萬聖節的裝扮！"
10017-290 = "再，再捉弄咱的話，\n要肅清了喔！？"
10017-300 = "等你很久囉，同志！\n要做的事情堆積如山！\n絕不允許偷懶！"
10017-310 = "你來啦，同志！\n必須一起處理的任務有很多，\n做好心理準備吧！"
10017-320 = "你叫咱嗎，同志？"
10017-330 = "今天也和咱一起，\n發起革命吧！"
10017-340 = "終於理解咱的權威了嗎？"
10017-350 = "放心，沒什麼好怕的。\n咱可是很寬容的！"
10017-360 = "呵呵呵，呵呵呵呵……\n沒想到今天也能一整天\n都和同志待在一起呢。"
10017-370 = "這，這種放鬆的狀態，\n只會出現在同志面前喔！"
10017-380 = "別，別捉弄咱！\n要肅清了哦！？"
10017-390 = "差，差不多該\n讓咱戴上鬍子了……"
10017-400 = "維持這樣總覺得\n有點害羞……"
10017-410 = "生日？\n是今天嗎？"
10017-420 = "好，那麼就把同志出生的\n這一天訂為赤冬的紀念日！"
10017-430 = "啊，唔……\n總覺得有點害羞呢……"
10017-440 = "如果被祝福的話，\n權威就……"
10017-450 = "不，不是，當然很開心！\n謝謝你啦，同志！"
10017-460 = "新年快樂，同志。\n今年的計畫訂好了嗎？"
10017-470 = "如果還沒的話，\n就和咱一起決定吧！"
10017-480 = "今天是聖誕節！\n聽說留著大鬍子的紅色老人\n會分送禮物……"
10017-490 = "真不錯！\n咱也想要禮物！"
10017-510 = "啊哈哈哈哈！\n……嗯，還不夠呢！\n再堆得更大更大吧！"
10017-520 = "哈，哈……哈啾！\n……嗚。"
10017-530 = "哎咿，別在意！\n咱現在正在集中精神！"
10017-540 = "你說……會不會冷？\n你還真弱呢，同志！\n對咱來說這種程度不算什麼！"
10017-550 = "咱還可以\n再玩3小時呢！"
10017-560 = "咱想到一個好主意，\n同志你在那裡堆個雪人吧！"
10017-570 = "然後把咱在這裡做的\n放在它的旁邊！"
10017-580 = "嗯？你說為什麼？\n你不覺得很好嗎？"
10017-590 = "……然後在兩個雪人中間\n再做個小的雪人吧……"
10017-600 = "啊，當，當然也要\n同志你也覺得好才行哦！？"
10017-2600 = "咱很喜歡哦……這正是\n咱的權威！咱的力量！咱的鬍子！\n漸漸變得令人畏懼了呢……\n不過不用擔心，同志。\n咱永遠都是，你的同伴！"
