[translation]
10012-20 = "Weight training is a science. This is where Millennium's advanced theories are put to the test."
10012-30 = "Hmm..."
10012-40 = "Is there somewhere we can train...?"
10012-50 = "These look like they could make for great free weights."
10012-60 = "Huh? You wanna stretch with me?"
10012-70 = "What? You also want to go on a run later...?"
10012-80 = "Welcome, Trainer. Let's work hard today."
10012-90 = "I've been waiting for you. Let's start training."
10012-100 = "The world itself can look different when you change your perspective."
10012-110 = "Take those stairs for example. They'd make for great training equipment."
10012-120 = "Let's start off with a nice run."
10012-130 = "Huh? Why don't I wear my school uniform?"
10012-140 = "Training in it is uncomfortable."
10012-150 = "Weight training is all the rage among the students these days."
10012-160 = "...Yeah, I know. I wish that were the truth."
10012-170 = "Think of you calves like another heart. You have to train them."
10012-180 = "Happy birthday, Trainer. I got you something..."
10012-190 = "Huh? Did you not want a dumbbell?"
10012-200 = "Thank you for remembering."
10012-210 = "What do I want?"
10012-220 = "Hmm. The highest quality protein... Wait, no!"
10012-230 = "I-I want an adorable stuffed kitty!"
10012-240 = "If I had one wish, it'd be for everyone to be healthy this year."
10012-250 = "I was told Christmas is..."
10012-260 = "...the day a saint was born."
10012-270 = "I can't say I know much about him, but he must have been in great shape."
10012-280 = "Care for some protein candy, Trainer?"
10012-290 = "Huh? How's it taste?"
10012-300 = "...I remember when things like that mattered more to me than the nutrition."
10012-320 = "What did you think, Trainer? Do you enjoy your workout plan?"
10012-330 = "Can't you feel the burn?"
10012-340 = "O-Oh... Trainer, you're staring at me."
10012-350 = "(I know I look gross after working out...)"
10012-360 = "Wh-What...are you looking at?"
10012-370 = "Trainer, I have a favor to ask you."
10012-380 = "I want you to promise to keep training with me."
10012-390 = "I want you to stay healthy."
10012-400 = "Wh-Why? Th-That's because..."
10012-410 = "Heehee. Isn't it obvious?"
10012-2600 = "Being able to handle something like this is a result of training. However, I will not become complacent and will continue trying, Trainer."
