[translation]
10017-20 = "The Great Leader of Red Winter Academy is here! Feel honored, Comrade!"
10017-30 = "Hmm... I like it. The Great Leader is quite pleased."
10017-40 = "Hmm... I see everything is in order."
10017-50 = "Ahem. Her honorable-ness has arrived."
10017-60 = "What a peaceful day. And it's all thanks to me! Hahaha!"
10017-70 = "(Is my mustache on right...?)"
10017-80 = "There you are, Comrade! We have much to do and so little time!"
10017-90 = "You're here, Comrade! We've got a big day ahead! You'd best be ready!"
10017-100 = "Did you call me, Comrade?"
10017-110 = "You're with me today. It's time to partake in revolution, Comrade!"
10017-120 = "Can't you feel my authority?"
10017-130 = "Worry not, Comrade. You have nothing to fear. I am quite merciful."
10017-140 = "Huh? My mustache fell off?"
10017-150 = "Huh...? Nooooo! My authority..."
10017-160 = "What the heck? It's right where it's supposed to be! Is this a joke to you?!"
10017-170 = "Heehee... I'm glad we're together again, Comrade."
10017-180 = "It's your birthday? Really?"
10017-190 = "Very well. I shall create a new annual celebration to mark this day!"
10017-200 = "Um... I admit, I'm a little embarrassed..."
10017-210 = "My grand superiority feels somewhat lessened when you tell me happy birthday..."
10017-220 = "But thank you anyway, Comrade!"
10017-230 = "Happy New Year, Comrade! Are your resolutions for the new year in order?"
10017-240 = "If not, then I'd be happy to advise you!"
10017-250 = "Today's date is... Right, Christmas! That day when a fat, old man gives gifts to kids."
10017-260 = "That's amazing! I want a gift too!"
10017-270 = "Halloween... The masses always get so loud and annoying."
10017-280 = "Oh, my mustache...? It's not a Halloween costume!"
10017-290 = "Ask again, and you'll be purged, Comrade!"
10017-300 = "There you are, Comrade! We have much to do and so little time!"
10017-310 = "You're here, Comrade! We've got a big day ahead! You'd best be ready!"
10017-320 = "Did you call me, Comrade?"
10017-330 = "You're with me today. It's time to partake in revolution, Comrade!"
10017-340 = "Can't you feel my authority?"
10017-350 = "Worry not, Comrade. You have nothing to fear. I am quite merciful."
10017-360 = "Heehee... I'm glad we're together again, Comrade."
10017-370 = "O-Only you get to see my bare face, Comrade."
10017-380 = "Don't tease me, or I'll purge you!"
10017-390 = "*huff* I'm putting my mustache back on."
10017-400 = "I don't like showing my bare face!"
10017-410 = "It's your birthday? Really?"
10017-420 = "Very well. I shall create a new annual celebration to mark this day!"
10017-430 = "Um... I admit, I'm a little embarrassed..."
10017-440 = "My grand superiority feels somewhat lessened when you tell me happy birthday..."
10017-450 = "But thank you anyway, Comrade!"
10017-460 = "Happy New Year, Comrade! Are your resolutions for the new year in order?"
10017-470 = "If not, then I'd be happy to advise you!"
10017-480 = "Today's date is... Right, Christmas! That day when a fat, old man gives gifts to kids."
10017-490 = "That's amazing! I want a gift too!"
10017-510 = "Heeheehee. That won't be enough. A little bigger. Gotta make it bigger."
10017-520 = "Ah... Ah.. Achoo! *sniffle*"
10017-530 = "Bah, don't bother me! Can't you see I'm on high alert right now?"
10017-540 = "Am I cold? You are the one with the frail body, Comrade! This is nothing!"
10017-550 = "I could play for another three hours!"
10017-560 = "I got an idea, Comrade. You go build a snowman there!"
10017-570 = "We'll put what we made here, next to it!"
10017-580 = "Hmm? Why? Isn't it okay?"
10017-590 = "Should we build a small snowman between those two?"
10017-600 = "Ah! B-But only if you're okay with it, Comrade!"
10017-2600 = "I absolutely love it. My authority! My power! My mustache! It's almost enough to intimidate even myself... But don't worry, Comrade. I'll always be with you."
