[translation]
10025-10 = "Blue Archive!"
10025-20 = "Don't treat me like a child! I'm still everyone's favorite older sister at heart!"
10025-30 = "(Seeing the cafe from this perspective is interesting...)"
10025-40 = "Hmm. It would be uncomfortable for anyone at this height."
10025-50 = "(Just a little more... If I stretch just a little more!)"
10025-60 = "*yawn* So sleepy..."
10025-70 = "Since I'm just a kid, it's okay if I take a nap, right?"
10025-80 = "Welcome, Sensei. Looking forward to today's class!"
10025-90 = "*yawn*..."
10025-100 = "A strawberry chocolate with rum raisin..."
10025-110 = "O-Oh! Sensei?"
10025-120 = "I-I wasn't dozing off!"
10025-130 = "I'll be a good kid and wait patiently!"
10025-140 = "Yes, it's yours truly! Shun!"
10025-150 = "Sensei, Sensei! Someone gifted us Roy's rum raisin chocolate!"
10025-160 = "Can I try one right now?"
10025-170 = "I can't have a snack because it'll spoil my appetite?"
10025-180 = "But they look so good..."
10025-190 = "Can't I have just one?"
10025-200 = "Happy birthday to you! Happy birthday to you! ♬"
10025-210 = "Happy birthday dear..."
10025-220 = "Ah! I bit my tongue..."
10025-230 = "Today's my birthday?"
10025-240 = "Oh, my. I completely forgot about it."
10025-250 = "Wait. Then how old am I technically?"
10025-260 = "Happy New Year, Sensei! Let's hurry over to the temple and drink gamju!"
10025-270 = "I knew it. I'm still too old for Santa to leave me gifts..."
10025-280 = "But that's okay. I'm spending this Christmas with you, Sensei!"
10025-290 = "That means the current me is okay with receiving candy!"
10025-310 = "Heehee. This place hasn't changed one bit."
10025-320 = "The promises I wrote to myself on the wall are still here."
10025-330 = "Those were the days..."
10025-340 = "Now that I look at them, I realize I managed to keep most of them."
10025-350 = "Should I write a new wish above them, then?"
10025-360 = "I-I can't tell you that. It's a secret!"
10025-370 = "Kids can't share their secrets with adults! Heehee."
10025-2600 = "It seems a little big for me now, but still, I'm most familiar with this weapon!"
