[translation]
10029-10 = "Blue Archive!"
10029-20 = "Hey, Sensei. I hope your day is sweet like candy!"
10029-30 = "Wonder if there's anything to munch on..."
10029-40 = "It's lively. I like it."
10029-50 = "B-o-r-e-d."
10029-60 = "Is Sensei here as well?"
10029-70 = "Oh, oh! That's...!"
10029-80 = "Welcome, Sensei. Would you like to eat something first?"
10029-90 = "Heeheehee. I've been waiting for you."
10029-100 = "What's wrong, Sensei? Is your tummy hungry? Should I get you something to eat?"
10029-110 = "I'm curious, Sensei. What do you usually like to munch on?"
10029-120 = "I don't only talk about snacks!"
10029-130 = "Sensei. Don't you know there's always room for dessert?"
10029-140 = "The philosophy behind this dessert..."
10029-150 = "Impressive, right?"
10029-160 = "Sensei's birthday!"
10029-170 = "It can't be helped. I'm paying today!"
10029-180 = "Sensei. Sensei. You...know what day it is today, right?"
10029-190 = "I've reaaally been looking forward to it, you know?"
10029-200 = "I wonder what this year will bring!"
10029-210 = "Let's go shopping together, Sensei!"
10029-220 = "Will Santa abandon me this year too?!"
10029-230 = "Or maybe you're my Santa!"
10029-240 = "Today I can get lots of candy...!"
10029-250 = "C'mon, Sensei. There's enough storage space around here to fit all the candy we'll buy!"
10029-270 = "Look, Sensei! Amazing... It's filled to the brim!"
10029-280 = "It's my first time seeing this! My first time seeing that!"
10029-290 = "So many snacks I've never laid eyes on before!"
10029-300 = "Whew. Sorry about that. It feels like my legs are going to give out all of a sudden."
10029-310 = "Thank you, Sensei."
10029-320 = "For coming with me."
10029-330 = "I'm really thankful."
10029-340 = "I'm so happy I got to make this discovery with you."
10029-2600 = "Amazing... You're certain, right? No refunds!"
