[translation]
10030-10 = "블루 아카이브."
10030-20 = "지나침은 모자람만 못한 법……\n오늘만큼은 일을 잊은 채\n저와 휴식을 즐기시는 게 어떠신가요?"
10030-30 = "몸이 조금\n따끈따끈하네요……"
10030-40 = "머릿속이\n개운해지는\n느낌입니다."
10030-50 = "이 차림, 어쩐지\n들떠 보이나요……?"
10030-60 = "모두들, 즐거워\n보이시네요."
10030-70 = "어딘가에\n앉아서\n쉴 만한 곳이……"
10030-80 = "어서 오세요, 선생님.\n기다리고 있었습니다."
10030-90 = "오셨군요, 선생님.\n우선 바이탈 체크부터 하시죠."
10030-100 = "휴식 중에는 업무를\n잊으려 노력하고 있습니다."
10030-110 = "하지만 그럴수록,\n머릿속에 일이 떠올라서……"
10030-120 = "왠지 여기서 이런\n옷을 입고 있으니, 뭔가……"
10030-130 = "살짝 긴장되네요."
10030-140 = "가끔은 휴식도 필요하다……\n저도 그렇지만 선생님께도\n전하고 싶은 말이네요."
10030-150 = "온천이라……\n저와는 연이 없는 곳이라\n생각하고 있었습니다."
10030-160 = "자신의 몸을 관리하는 것도\n엄연한 일의 일부지요."
10030-170 = "……조금 소홀히 하고\n있었을지도 모르겠습니다."
10030-180 = "생일 축하드립니다, 선생님.\n특별한 날인만큼, 그……"
10030-190 = "선생님께 도움이 된다면……\n뭐든지……"
10030-200 = "네……? 제 생일이요……?\n그렇군요……"
10030-210 = "선생님과 이렇게 뵐 수\n있는 것만으로도,\n제게는 충분한 선물입니다."
10030-220 = "올 한 해도 잘 부탁드립니다.\n선생님."
10030-230 = "앞으로도, 그……"
10030-240 = "함께해 주신다면 기쁠겁니다."
10030-250 = "크리스마스로군요.\n네? 춥지 않냐고요……?"
10030-260 = "후훗. 네, 몸은 따듯하니,\n괜찮습니다."
10030-270 = "떠들썩한 날이네요. 선생님."
10030-280 = "사탕은 없습니다만……\n온천 계란은 어떠신가요?"
10030-300 = "이렇게 호화로운 온천을\n둘이서만 쓸 수 있다니……\n인생, 무슨 일이 일어날지\n모르는 거네요."
10030-310 = "언젠가는……\n어쩌면 이런 미래도……"
10030-320 = "아, 아, 아뇨!\n신경 쓰지 말아 주세요……!"
10030-330 = "그러니까, 만약 정말로\n언젠가 그렇게 된다면……"
10030-340 = "그런 분에 넘치는 나날을\n상상하지 않은 것은,\n아닙니다만……"
10030-350 = "선생님과 학생으로도, 지금은\n지나칠 정도로 충분히\n행복하네요. 정말로……"
10030-2600 = "이 무게감, 책임을 느낍니다.\n제대로 보답할 수 있도록,\n최선을 다하겠습니다."
