[translation]
10039-10 = "B-Blue...Archive..."
10039-20 = "Th-This is SRT Academy. RABBIT Squad's Kasumizawa Miyu... Umm... May I please...go b-back...?"
10039-30 = "Oh, um..."
10039-40 = "(I want to start a conversation first...but I'm scared...)"
10039-50 = "(I want a cup of hot chocolate...)"
10039-60 = "(I knew a useless crybaby like me didn't belong here...)"
10039-70 = "Wh-What about the cover...?"
10039-80 = "Th-Thanks for your hard work, Sensei..."
10039-90 = "Please tell me when a good time is... I-I'm really good at waiting..."
10039-100 = "Um, Sensei... D-Do you remember me?"
10039-110 = "It's always h-hard for me to make new f-friends..."
10039-120 = "I wish the RABBIT Squad members got along b-better..."
10039-130 = "I w-wish I was stronger...like th-the others..."
10039-140 = "I'm as useless as a p-pebble on the street..."
10039-150 = "I-I don't know how I even g-got into SRT Academy..."
10039-160 = "S-Sensei... Today's your b-birthday..."
10039-170 = "I'm homeless, so I couldn't g-get you anything..."
10039-180 = "B-But... Happy Birthday...!"
10039-190 = "H-Huh? My b-b-birthday?"
10039-200 = "H-How...did you remember that...? Wow..."
10039-210 = "Th-Thank you... I'm so happy...!"
10039-220 = "I w-wanna go home...back to the SRT this year..."
10039-230 = "I-I heard Santa Claus...doesn't give bad kids p-presents..."
10039-240 = "S-Santa Claus probably forgot I exist..."
10039-250 = "I w-wore a ghost costume at a Halloween festival once..."
10039-260 = "B-But no one cared I was there..."
10039-280 = "Phew... Take a breath..."
10039-290 = "Focus on the target..."
10039-300 = "The distance is 1,150 meters...wind is from the northeast, fifteen knots."
10039-310 = "If I correct the error caused by temperature and humidity..."
10039-320 = "U-Um... Sensei. S-Stop playing around...p-please..."
10039-330 = "That's...! I can't focus on aiming..."
10039-340 = "...Oh. I-It's not interference?"
10039-350 = "Y-You're training me for a-actual combat..."
10039-360 = "I think w-we did this at SRT..."
10039-370 = "E-Eek...?!"
10039-380 = "S-Sensei...! Y-You're b-b-breathing in m-my ear...!!"
10039-390 = "(Sensei's breath is...so close...!)"
10039-400 = "(I-I can't aim...)"
10039-2600 = "RABBIT Type 39 rifle received. H-Heavy..."
