[translation]
10038-10 = "Blue Archive"
10038-20 = "สึคิยูกิ มิยาโกะ\nจากกองทหาร RABBIT\nสถาบันพิเศษ SRT ค่ะ\nขอคำสั่งด้วยค่ะ คุณครู"
10038-30 = "ฉันเจอพวก...\nของตกแต่งน่ารักๆ ด้วยค่ะ"
10038-40 = "ถ้าเป็นพื้นที่แค่นี้ละก็\nฉันสามารถลอบเข้าไป\nคนเดียวได้สินะคะ..."
10038-50 = "ในที่แบบนี้...\nจุดลอบยิง..."
10038-60 = "กำลังรับข้อมูล...\nการตอบสนองเป็นไปได้ด้วยดี"
10038-70 = "มีเรื่องอะไรเหรอคะ?"
10038-80 = "ชะ...เชิญเลยค่ะคุณครู"
10038-90 = "ฉันกำลังรอรับคำสั่งต่อไป\nอยู่ที่นี่แล้วค่ะ"
10038-100 = "ยินดีที่ได้พบกันอีกครั้งนะคะ\nคุณครูมีงานอะไรรึเปล่าคะ...?"
10038-110 = "กองทหาร RABBIT\nพร้อมออกปฏิบัติการทุกเมื่อค่ะ"
10038-120 = "จู่ๆ ฉันก็เกิดสงสัยขึ้นมาค่ะ..."
10038-130 = "น้องกระต่ายส่งเสียงร้องยังไงเหรอคะ?"
10038-140 = "ร้อง \"ฟี้ ฟี้...?\"\nแบบนี้รึเปล่านะ?"
10038-150 = "เวลาที่เจอศัตรูที่จัดการยาก\nเรียกฉันได้เลยนะคะ"
10038-160 = "สัญลักษณ์ของกองทหาร RABBIT..."
10038-170 = "น่ารักดีไหมคะ?"
10038-180 = "สุขสันต์วันเกิดค่ะ คุณครู"
10038-190 = "เพื่อทำให้วันเกิดของคุณครู\nเป็นวันที่สมบูรณ์แบบ"
10038-200 = "วันนี้ฉันจะอยู่ข้างๆ\nคอยปกป้องคุณครูเองค่ะ"
10038-210 = "พอนึกดูแล้ววันนี้...\nเป็นวันเกิดของฉันจริงๆ ด้วยค่ะ"
10038-220 = "ไม่ต้องซื้อของขวัญให้ฉันก็ได้ค่ะ"
10038-230 = "แค่คุณครูปลอดภัย\nฉันก็ดีใจแล้วค่ะ"
10038-240 = "ปีนี้สถาบัน SRT...\nจะเปิดทำการใหม่ได้รึเปล่านะ...?"
10038-250 = "ซานตาคลอส…"
10038-260 = "เป็นคนที่ฉัน...\nอยากเผชิญหน้า\nและต่อสู้ด้วยสักครั้งค่ะ"
10038-270 = "ถ้าพวกผีสาง\nยังกลัวปืนละก็...\nก็คงไม่น่ากลัวเท่าไรหรอกค่ะ"
10038-290 = "สวยจังเลย..."
10038-300 = "วิวตอนกลางคืนสวยมาก\nจนฉันเกือบจะลืม...\nเรื่องภารกิจไปเลยค่ะ"
10038-310 = "ฮิฮิ... ถึงการเผลอลืมตัว\nระหว่างปฏิบัติภารกิจ...\nจะเป็นสิ่งที่ไม่ควรทำก็ตาม..."
10038-320 = "อา... คือฉัน...ถึงจะกะทันหัน\nไปสักหน่อยนะคะแต่ว่า...  คุณครู..."
10038-330 = "คือว่า... คุณครู...\nคอยอยู่กับฉันเสมอ...\nขอบคุณนะคะ"
10038-340 = "ถ้าเกิดว่า...\nไม่มีคุณครูละก็..."
10038-350 = "ทั้งฉันและกองทหาร RABBIT...\nคงพัฒนามาถึงขั้นนี้\nไม่ได้หรอกค่ะ"
10038-360 = "เพราะงั้นคราวหน้า...\nถ้าคุณครูไม่ว่าอะไร...\nก็ขอให้.."
10038-370 = "เอ๊ะ...? มีสายเข้า..."
10038-380 = "อย่างนั้นเหรอคะ\nจากตรงนี้อีก 500 เมตร..."
10038-390 = "ค่ะ มีสายแจ้งเตือนเข้ามา\nให้เตรียมพร้อมสำหรับปฏิบัติการค่ะ"
10038-400 = "คุณครูคะ กรุณาสวมสายรัด...\nและเข็มขัดโรยตัวด้วยค่ะ"
10038-410 = "คะ...? ไม่รู้วิธีใช้งานงั้นเหรอคะ...?\nงะ... งั้นเหรอคะ..."
10038-420 = "ไม่เป็นไรค่ะ งั้นรบกวนรออยู่ที่นี่นะคะ\nฉันจะรีบจัดการให้เสร็จ แล้วรีบกลับมาค่ะ"
10038-430 = "พอกลับมาแล้ว ฉันอยากจะ\nนั่งชมวิวสวยๆ แบบนี้\nพร้อมกับคุณครูอีกค่ะ"
10038-2600 = "ได้รับปืน\nRABBIT Type 31 Submachine Gun แล้วค่ะ\nน่ารักจังเลย..."
