[translation]
10032-10 = "Blue Archive!"
10032-20 = "Hahaha! Hi, Sensei! We're going to play together lots this year, right?!"
10032-30 = "I want to get together with everyone and play hanetsuki!"
10032-40 = "What should I play with Sensei? ♪"
10032-50 = "If you laugh, blessings will come your way! ♪"
10032-60 = "Found a toy! ♪"
10032-70 = "Hmm. Maybe I can get Sensei to spoil me and give me some New Year's cash!"
10032-80 = "Hey, Sensei! It's a new year and you're already hard at work!"
10032-90 = "Welcome, Sensei! I've been waiting for you this whole time! ♥"
10032-100 = "Sensei, what should we play today?"
10032-110 = "Rock, paper, scissors? Kick the can? Or..."
10032-120 = "Hide. And. Seek?"
10032-130 = "Oh, right. You're an adult, Sensei. You can just play all day, yeah?"
10032-140 = "I've got an idea..."
10032-150 = "I can help!"
10032-160 = "Maybe it's because I'm wearing this, but I feel like I have more energy than usual!"
10032-170 = "Come on, Sensei, you can do this! Let's finish work quickly and have lots of fun!"
10032-180 = "I can't believe I spent this much time playing with you..."
10032-190 = "Maybe it's fate?!"
10032-200 = "Happy birthday, Sensei! Of course I remembered!"
10032-210 = "I could never forget your birthday or your promise to play with me everyday! Heeheehee! ♪"
10032-220 = "You want to wish me a happy birthday?"
10032-230 = "Heeheehee! I wonder what my gift is!"
10032-240 = "Let's go out and play pranks! It'll be so much fun together!"
10032-250 = "Happy New Year, Sensei! Happy New Year! Bonne Année! Guten tag!"
10032-260 = "What? The last one is wrong? Oh, you're right!"
10032-270 = "It's almost the new year. Merry Christmas, Sensei!"
10032-280 = "Heeheehee. I want to play with you today!"
10032-290 = "Trick or treat! I'm going to E-A-T you, Sensei! ♪"
10032-300 = "What? I can't eat you?"
10032-320 = "Oh, what a shame. I win, Sensei!"
10032-330 = "Heh heh heh. I admit you put up a good fight..."
10032-340 = "...but defeat is bitter pill to swallow no matter what. Now take your medicine. Heehee! ♪"
10032-350 = "So, what should I draw? A circle? An X? Or do you have a better idea?"
10032-360 = "Now's your chance, Sensei. I'll take any request."
10032-370 = "Actually, I change my mind. Something that easy won't do..."
10032-380 = "Instead, I'll draw all over your face! Every bit of it!"
10032-2600 = "Hahaha, okay, okay! This could be a little bit of fun!"
