[translation]
10030-10 = "Blue Archive."
10030-20 = "Overworking can backfire. How about relaxing today and enjoying a break with me?"
10030-30 = "My body feels nice and warm..."
10030-40 = "My head feels clear and at ease."
10030-50 = "My outfit... Do I seem excited?"
10030-60 = "Everyone looks like they're having fun."
10030-70 = "Is there somewhere to sit and rest?"
10030-80 = "Welcome, Sensei. I've been waiting for you."
10030-90 = "You're here, Sensei. Let's check your vitals first."
10030-100 = "During breaks, I try to forget about work."
10030-110 = "But the more I do that, the more my mind wanders."
10030-120 = "I don't know why, but since I'm wearing something like this here, I'm..."
10030-130 = "I'm a bit nervous."
10030-140 = "Sometimes you need a break... You say it so much that I've always wanted to say it back to you."
10030-150 = "A hot spring... I never thought I'd find myself in such a place."
10030-160 = "Self-care is also important."
10030-170 = "I've perhaps been a bit neglectful."
10030-180 = "Happy birthday, Sensei. Since it's a special day..."
10030-190 = "...if there's anything you need... Anything at all."
10030-200 = "Huh...? My birthday...? I see..."
10030-210 = "Seeing you like this is more than enough of a gift."
10030-220 = "I look forward to working with you this year, Sensei."
10030-230 = "In the future..."
10030-240 = "If we could be together then too, I'll be happy."
10030-250 = "It's Christmas. Huh? Am I not cold...?"
10030-260 = "Heehee. I'm fine. My body is warm."
10030-270 = "It's a busy day, Sensei."
10030-280 = "I don't have any candy, but would you like some hot spring boiled eggs?"
10030-300 = "I can't believe we are the only two using this luxurious hot bath. I suppose you never really know what can happen in life."
10030-310 = "Maybe someday... A future like this..."
10030-320 = "N-N-No! It's nothing!"
10030-330 = "If it, somehow, were to really happen someday..."
10030-340 = "I would be happy beyond what I deserve, but..."
10030-350 = "Even if we are just teacher and student, right now, I'm really happy. Truly..."
10030-2600 = "I feel a great burden of responsibility on my shoulders. I will do my best not to forget this weight."
