[translation]
10048-10 = "蔚藍檔案"
10048-20 = "我是奧利斯小隊的沙織。\n…受到了老師，很多關照。\n至少會做與其等價的工作。請多指教。"
10048-30 = "呼呣…"
10048-40 = "這種地方\n沒辦法習慣呢…"
10048-50 = "這是，什麼…？"
10048-60 = "無法理解…"
10048-70 = "原來如此，\n這是那種東西啊…"
10048-80 = "準備已經完成。\n有什麼事就說吧，\n老師。"
10048-90 = "我正在等你，老師。"
10048-100 = "……那是什麼反應。"
10048-110 = "我，有幫上忙嗎？"
10048-120 = "……那就好。光是那樣，\n我就能繼續待在這裡。"
10048-130 = "明明一切都是徒勞，\n為什麼我們還活著呢……"
10048-140 = "我還未知曉那個答案。"
10048-150 = "我……今後也\n必須繼續掙扎。"
10048-160 = "對我下令吧，老師。\n我就是為了這個，\n才會在這裡的。"
10048-170 = "我還能，繼續活下去嗎……"
10048-180 = "……聽說今天，\n是老師的生日。"
10048-190 = "抱歉，\n我不知道這種時候\n該做些什麼。"
10048-200 = "只不過……要是沒有你，\n我現在也不會在這裡了。"
10048-210 = "所以，老師。\n再次感謝你。"
10048-220 = "……我至今為止，\n幾乎沒有慶祝過生日。"
10048-230 = "所以還不清楚\n該怎麼接受那句話。"
10048-240 = "以及是否有那個資格。"
10048-250 = "我總有一天，\n也能發自內心地\n慶祝這一天嗎……"
10048-260 = "一年的結束嗎……嗯。\n雖然這世界的每一天\n依然冰冷痛苦……"
10048-270 = "即便如此，\n時間也會流逝啊。"
10048-280 = "平安夜嗎……沒事，\n我沒有任何感想。"
10048-290 = "我不認為，\n這世界的痛苦\n會因此減少。"
10048-300 = "……全都只是徒勞而已。"
10048-310 = "看來似乎是慶典……\n沒什麼興趣呢。"
10048-320 = "只不過是徒勞而已。"
10048-330 = "準備已經完成。\n有什麼事就說吧，\n老師。"
10048-340 = "我正在等你，老師。"
10048-350 = "……那是什麼反應。"
10048-360 = "我，有幫上忙嗎？"
10048-370 = "……那就好。光是那樣，\n我就能繼續待在這裡。"
10048-380 = "明明一切都是徒勞，\n為什麼我們還活著呢……"
10048-390 = "我還未知曉那個答案。"
10048-400 = "我……今後也\n必須繼續掙扎。"
10048-410 = "對我下令吧，老師。\n我就是為了這個，\n才會在這裡的。"
10048-420 = "我還能，繼續活下去嗎……"
10048-430 = "……聽說今天，\n是老師的生日。"
10048-440 = "抱歉，\n我不知道這種時候\n該做些什麼。"
10048-450 = "只不過……要是沒有你，\n我現在也不會在這裡了。"
10048-460 = "所以，老師。\n再次感謝你。"
10048-470 = "……我至今為止，\n幾乎沒有慶祝過生日。"
10048-480 = "所以還不清楚\n該怎麼接受那句話。"
10048-490 = "以及是否有那個資格。"
10048-500 = "我總有一天，\n也能發自內心地\n慶祝這一天嗎……"
10048-510 = "一年的結束嗎……嗯。\n雖然這世界的每一天\n依然冰冷痛苦……"
10048-520 = "即便如此，\n時間也會流逝啊。"
10048-530 = "平安夜嗎……沒事，\n我沒有任何感想。"
10048-540 = "我不認為，\n這世界的痛苦\n會因此減少。"
10048-550 = "……全都只是徒勞而已。"
10048-560 = "看來似乎是慶典……\n沒什麼興趣呢。"
10048-570 = "只不過是徒勞而已。"
10048-590 = "老師，你怎麼會在這裡……？"
10048-600 = "呃……哈啊……"
10048-610 = "……別擔心，\n這是常有的事。"
10048-620 = "我只是在最後關頭，\n鬆懈了……"
10048-630 = "明明什麼都沒改變……\n是我誤會了。"
10048-640 = "咳咳，咳咳……！"
10048-650 = "不要露出那種表情，\n我已經習慣疼痛了。"
10048-660 = "和以往沒什麼不同。\n事到如今也不值一提了。"
10048-670 = "現在這樣就行了……"
10048-680 = "再稍微，維持這樣……"
10048-2600 = "你……為什麼可以信賴我？\n明明發生了那種事……\n遭到背叛，也無所謂嗎？\n雖然我還有很多不懂的事，\n即便如此……我還是會，竭盡全力。"
