[translation]
10056-10 = "Blue Archive."
10056-20 = "Merry Christmas! I'm Serina of the Remedial Knights! I hope you have a very special Christmas!"
10056-30 = "Be sure not to catch a cold!"
10056-40 = "Is a first aid kit an appropriate gift...?"
10056-50 = "What kinds of gifts do good children like?"
10056-60 = "Don't push yourself too hard. Health always comes first."
10056-70 = "I wish you the best of health!"
10056-80 = "Welcome, Sensei! I'm Santa today! Heehee."
10056-90 = "You're back, Sensei! Merry Christmas!"
10056-100 = "Have you thought about what to get the children this year?"
10056-110 = "We can figure it out together. Heehee."
10056-120 = "Santa is an important tradition, for the children's sake."
10056-130 = "If... If I was the real Santa..."
10056-140 = "Perhaps I could be more helpful to you."
10056-150 = "You called? It's me, Serina!"
10056-160 = "I'm Santa today."
10056-170 = "Let me know anytime."
10056-180 = "I'm always ready..."
10056-190 = "Happy birthday, Sensei!"
10056-200 = "I hope you're excited to open your gift."
10056-210 = "M-My birthday...?"
10056-220 = "Oh, gosh. I've been so busy lately it slipped my mind. Thank you!"
10056-230 = "It feels as though Christmas just passed...but it's already New Year's Eve."
10056-240 = "Happy New Year."
10056-250 = "Other people's smiles bring me joy."
10056-260 = "It's Christmas! How do I look?"
10056-270 = "People thought I was dressed for Halloween when I was walking around."
10056-280 = "It's not a Halloween costume though..."
10056-300 = "S-Sensei? Are you sure I can have this scarf?"
10056-310 = "B-But... I'm meant to be Santa today."
10056-320 = "I'm the one who should be giving you a gift..."
10056-330 = "To receive one instead..."
10056-340 = "Huh? Even Santa deserves to be rewarded?"
10056-350 = "Well... If you say so..."
10056-360 = "Heehee."
10056-370 = "Thank you, Sensei. I'll cherish it."
10056-2600 = "Oh, thank you. But, Sensei, haven't you heard that Santa doesn't give presents to children who cry? So, no crying!"
