[translation]
10053-10 = "Blue Archive!"
10053-20 = "Haha... All preparations complete. There won't be a single error in my calculations today!"
10053-30 = "I'm feeling a little drained... I wonder if now's a good time for a break."
10053-40 = "If you don't start taking care of your physical fitness..."
10053-50 = "This is an interesting cafe. Also, very unexpected."
10053-60 = "I already knew this, but wow... Exercise is not easy..."
10053-70 = "As long as we don't go completely bankrupt, we'll be fine. I hope."
10053-80 = "Welcome, Sensei. I've been waiting for you."
10053-90 = "Come now! There's a mountain of work that needs doing!"
10053-100 = "You're late!"
10053-110 = "..."
10053-120 = "I'll let you off the hook... But only this once!"
10053-130 = "You have to arrive on time from now on, got it?"
10053-140 = "I've heard that sometimes all it takes to change your mood is a different outfit."
10053-150 = "I'm not actually sure of that, but..."
10053-160 = "...While I have it on... What do you think about this outfit?"
10053-170 = "As a treasurer, and as an athlete..."
10053-180 = "...all I can do is my best."
10053-190 = "This outfit...is a refreshing look?"
10053-200 = "Wh-Where did that come from?!"
10053-210 = "Well, um... Thank you..."
10053-220 = "You like my ponytail?"
10053-230 = "Y-You're always just...saying things like that!"
10053-240 = "...Doesn't mean I don't appreciate hearing it, though..."
10053-250 = "When you really think about it..."
10053-260 = "Physical education is just another STEM subject that can be scientifically analyzed."
10053-270 = "Although, that's hard to do in the middle of a run..."
10053-280 = "Sensei. Happy birthday."
10053-290 = "If we take your date of birth and just do a little math, you're..."
10053-300 = "Haha. Don't worry, I'll stop there."
10053-310 = "Sensei... Do you remember?"
10053-320 = "Today is my birthday."
10053-330 = "I left my schedule empty for today."
10053-340 = "What about you, Sensei? What does your schedule look like today?"
10053-350 = "Happy New Year, Sensei!"
10053-360 = "Here's to another great year together."
10053-370 = "I was wondering... Do you want to start off the year with a run?"
10053-380 = "I don't really understand why some people get so excited for Christmas..."
10053-390 = "But thinking of a Christmas with you, Sensei..."
10053-400 = "It starts to make sense."
10053-410 = "A day of costumes, tricks, treats, and..."
10053-420 = "Calories!"
10053-430 = "I-I'm not going to let down my guard just because I'm wearing workout clothes!"
10053-450 = "*pant* *pant*"
10053-460 = "I can't believe I've become so unfit after just a few months..."
10053-470 = "To ensure that I don't embarrass myself at the Kivotos Halo Festival..."
10053-480 = "I'm going to have to double down on my training."
10053-490 = "Oh, Sensei. You want water too?"
10053-500 = "Sure, here..."
10053-510 = "S-Stop right there, Sensei! I-I mean, um, maybe now isn't...a good time to drink water?"
10053-520 = "(If Sensei drinks from the bottle I've been drinking from...)"
10053-530 = "(I-It'd be an indirect ki—)"
10053-540 = "(No, no! It doesn't matter what the circumstances are...)"
10053-550 = "(Such shamelessness can never, absolutely never be tolerated!)"
10053-560 = "(That being said, if it's Sensei...)"
10053-570 = "...One sip... You can have just one sip, okay?"
10053-2600 = "This is surprisingly...suitable and reasonable for exercise. Thank you, Sensei."
