[translation]
10063-10 = "Blue! Archive!"
10063-20 = "Is there anything fun going on? I, Kurosaki Koyuki, am here! Yahahaha!"
10063-30 = "Wow, there are a lot of interesting things here!"
10063-40 = "Th-This is a safe zone, right?! No one can get me here, can they?!"
10063-50 = "Oh, this place is the infamous..."
10063-60 = "By any chance...are loud people not allowed here?"
10063-70 = "*gasp* ...! I'm hungry."
10063-80 = "You came, Sensei!"
10063-90 = "I've been waiting for you for so long!"
10063-100 = "Yahahaha, Sensei!"
10063-110 = "...Huh? No, I didn't touch anything."
10063-120 = "Maybe...?"
10063-130 = "Can I help you with anything?"
10063-140 = "Or should I just help you by not doing anything?"
10063-150 = "Calculations?"
10063-160 = "They're easy! Not that I like doing them, though."
10063-170 = "Did you call me to find a password, by any chance?"
10063-180 = "I'm not your notepad!"
10063-190 = "Oh, did you tell my upperclassmen that I'm here?"
10063-200 = "If I don't let them know, they'll scold me later..."
10063-210 = "Huh? I'm not bored."
10063-220 = "...Huh? I don't know. Why?"
10063-230 = "Happy birthday, Sensei!"
10063-240 = "I'll do anything for you today, Sensei."
10063-250 = "Yup! Today's my birthday!"
10063-260 = "Yahahaha! I hope I'm lucky today. Otherwise, I'll be in trouble!"
10063-270 = "Happy New Year!"
10063-280 = "Argh! It's already the New Year!"
10063-290 = "Hmm? When the sun rises in the New Year, is it a new sun? Or is it just the same old sun from last year?"
10063-300 = "Merry Christmas! We can play all we want today!"
10063-310 = "Right?"
10063-320 = "A lot of people are wearing strange outfits today."
10063-330 = "...Me? I-I've never..."
10063-340 = "I don't know if I have, or...have I...? Yahahaha...?"
10063-360 = "Wow, Sensei! An actual four-leaf clover!"
10063-370 = "What happened?! It wasn't there just a moment ago!"
10063-380 = "Is it possible... Could it have just appeared?"
10063-390 = "No, that doesn't make sense..."
10063-400 = "Did I not see it...?"
10063-410 = "When did you spot it?"
10063-420 = "How's this possible...?"
10063-430 = "It's such perfect timing!"
10063-440 = "...!!!"
10063-450 = "Yes, yes! I see!"
10063-460 = "Yay!"
10063-470 = "You'd better think so, because..."
10063-480 = "It'll be more fun!"
10063-2600 = "No, um... Huh? Eh? Is this okay? Is it really okay? Sensei...do you...really trust me...?"
