[translation]
10069-10 = "蔚藍檔案"
10069-20 = "我的名字叫做朱城瑠美。\n在山海經高級中學的玄武商會擔任會長。\n隨意叫我瑠美就行囉。"
10069-30 = "這裡的裝潢…\n要不要試著在\n商會活用呢。"
10069-40 = "這裡的茶點，\n值得參考呢。"
10069-50 = "這麼悠閒的時間，\n時隔多久了呢…？"
10069-60 = "還是避免在這裡\n和玄龍門的孩子們戰鬥吧。"
10069-70 = "真和平啊…\n嗯，是件好事。"
10069-80 = "什麼嘛，原來是老師啊。"
10069-90 = "我還以為你忘記\n要來這裡了呢，哈哈。"
10069-100 = "歡迎你來，老師。"
10069-110 = "居然敢讓玄武商會\n的會長等你，\n你的膽子還挺大的嘛？"
10069-120 = "這裡就是夏萊…\n啊啊，抱歉。"
10069-130 = "我很久沒有\n離開廚房了，\n稍微嚇了一跳。"
10069-140 = "對料理人來說，\n廚房就是戰場…"
10069-150 = "既然如此，這裡\n就是老師的戰場，嗎？"
10069-160 = "這裡應該還是有\n簡單的廚具吧？"
10069-170 = "不是，我只是想做點料理。"
10069-180 = "吃飯是很重要的唷？老師。"
10069-190 = "不能不吃飯，\n或者隨便亂吃。\n知道了嗎？"
10069-200 = "喜歡料理的理由？\n這個嘛…\n因為料理很單純吧？"
10069-210 = "只要下功夫\n就會變美味，\n只要願意研究，\n就會增加可能性。"
10069-220 = "跟老師…\n或許有點像呢。"
10069-230 = "哈哈，我記得喔，\n今天是老師的生日對吧？"
10069-240 = "所以，我做了長壽麵。\n還有水蜜桃當作甜點。\n要努力全部吃完哦？"
10069-250 = "我的生日…？\n謝謝你，老師。"
10069-260 = "好久沒有\n被人祝福了呢。"
10069-270 = "商會長當久了，\n常常會感覺不到\n日子的流逝。"
10069-280 = "新年快樂！\n今年也請多指教哦！"
10069-290 = "說到新年就是要吃餃子對吧！\n我準備了鏡餅、燉魚、\n年糕湯，還有…"
10069-300 = "嗯？\n全部吃完的話，\n肚子可能會炸開…？"
10069-310 = "聖誕節啊…\n雖然不是很熟悉，不過\n是個很有氣氛的好節日呢。"
10069-320 = "我今天打算來做\n糖葫蘆。如何？"
10069-330 = "萬聖節啊…\n雖然不太熟悉，不過\n我知道是什麼節日哦。"
10069-340 = "那，來做個\n南瓜餡的月餅吧？"
10069-360 = "啊…這樣啊。\n有點透是嗎？"
10069-370 = "嘛，不用在意哦。\n反正也沒什麼損失。"
10069-380 = "…早知道會這樣的話，\n就穿更可愛的內衣來了。"
10069-390 = "好像，有點可惜？"
10069-400 = "哈哈，移開視線了。\n我一點都不在意哦？"
10069-410 = "老師你意外地還有這一面呢…\n呵呵，我喜歡。"
10069-420 = "反正事已至此，要不要\n讓你更為難一點呢…？"
10069-2600 = "我認為順手的道具是很重要的。\n不管是廚具或槍都是。"
