[translation]
10068-10 = "블루! 아카이브!!"
10068-20 = "왔습니다, 왔습니다!\n모두의 슈퍼스타, 우자와 레이사의 등장입니다!"
10068-30 = "사, 사람 많아……."
10068-40 = "어디 있으면 되지……."
10068-50 = "아니, 오히려\n이럴 때일수록\n평소대로…!"
10068-60 = "여, 역시 그만두자.\n이상한 사람으로\n보일 거야."
10068-70 = "마음이 놓이는 장소에요!"
10068-80 = "오셨습니까, 선생님!"
10068-90 = "우자와 레이사.\n대기하고 있었습니다!"
10068-100 = "선생님의 '등장'이로군요!!"
10068-110 = "그럼, 오늘은 뭘 할까요!"
10068-120 = "부르셨습니까, 선생님!\n뭐든 말씀만 해주세요!"
10068-130 = "아, 혹시 목소리가\n좀…… 컸나요?"
10068-140 = "울렸을지도…….\n죄송합니다……."
10068-150 = "음… 신기해요."
10068-160 = "여기에 오면,\n조금 힘이 풀린다고 할까……."
10068-170 = "시, 심부름 같은 거\n시키실 일 없나요?"
10068-180 = "그냥 서 있기만\n하는 건 좀 어색한데……."
10068-190 = "앞으로 무슨 일이\n생겨도 걱정 마세요!"
10068-200 = "선생님 곁에는 저,\n우자와 레이사가 있으니까요!"
10068-210 = "생일 축하드려요 선생님!!!"
10068-220 = "굉장히 특별한 날이니,\n함께 순찰 같은 건 어떨까요!"
10068-230 = "앗, 제 생일이요? 고맙습니다!"
10068-240 = "요즘, 생일을 축하해 주시는\n분들이 많네요!"
10068-250 = "……오래 살고 볼 일이에요!"
10068-260 = "전 아직 15살이지만요!"
10068-270 = "새해 복 많이 받으세요, 선생님!"
10068-280 = "올해도 잘 부탁드립니다!"
10068-290 = "메리 크리스마스~!!"
10068-300 = "네? 선물 교환요?"
10068-310 = "아, 아앗…!? 잊고 있었어요…!"
10068-320 = "그다지 이런 것에는,\n익숙하지 않아서…!"
10068-330 = "사탕이 없으면 장난을\n받을 수 있는 날입니다!"
10068-340 = "……네?\n어딘가 이상한 해석이라고요?"
10068-360 = "……뭔가,\n신기한 기분이네요.\n이렇게……."
10068-370 = "누군가와 같이,\n해 뜨는 걸 보는 건\n처음이라서……."
10068-380 = "그러고 보니 누군가랑\n둘이서 보낸 시간도……."
10068-390 = "어쩌면 이번이\n제일 길었을지도…….\n하하."
10068-400 = "으음……. 또 이상한\n말을 해버린 것 같네요……."
10068-410 = "실은 지금도 좀 졸려서…….\n제가 무슨 말을\n하고 있는지 잘……."
10068-420 = "그, 그래도 선생님은…….\n뭐든지 알아주시니까……."
10068-430 = "이번에도…… 언제나처럼,\n알아주세요. 헤헤……."
10068-440 = "음……. 좋네요……."
10068-450 = "선생님…….\n감사합니다…….\n히히……."
10068-2600 = "사실, 아직 실감이 안 납니다.\n저는……. 정말 선생님께\n도움이 되고 있는 것일까요…….\n그랬으면 좋겠다고,\n항상 진심으로 바라고 있습니다."
