[translation]
10070-10 = "蔚藍，檔案。"
10070-20 = "我是山海經高級中學所屬，\n玄龍門的執行部長，近衛美奈。\n妨礙我等前進的事物，全部都由我來處理吧！"
10070-30 = "對迷路的船來說，\n作為依靠的燈塔是必要的。\n所以，老師…那個…\n果，果然還是請你假裝沒聽見吧！"
10070-40 = "有股清幽的茶香…\n雖然還不是很擅長，\n不過真不錯啊。"
10070-50 = "能夠感受到孤寂律動\n的地方…指的應該\n就是這裡吧。"
10070-60 = "山海經的咖啡廳\n其實比較接近茶館吧…"
10070-70 = "味道真香…\n稍微放鬆一下\n肩膀好了。"
10070-80 = "啊啊，是老師啊，\n居然能在這種地方見到你，\n世界還真小呢……"
10070-90 = "嗯？\n你說這裡是夏萊\n所以很正常……？"
10070-100 = "說，說的也是。"
10070-110 = "我在等你哦，老師。"
10070-120 = "今天又會是怎樣的世界\n在迎接我們呢？\n真讓人興奮不已。"
10070-130 = "人是無法\n獨自生活的…"
10070-140 = "雖然這句話很老套，\n不過，我並不討厭。"
10070-150 = "人類是一種會\n警戒他人的生物…\n不過，也同樣會信任他人。"
10070-160 = "我，該信任老師嗎，\n還是…"
10070-170 = "不用那麼緊張的，老師。\n等到明天，一切都會好起來的。"
10070-180 = "電影是個好東西。\n能附上名為歲月\n的品質保證書的話，\n那就更棒了。"
10070-190 = "並非因為是名作\n才活了下來，\n而是因為活了下來，\n才會被稱為名作。"
10070-200 = "有時，我也會\n想要成為別人。"
10070-210 = "無論是誰都好，\n只要是比現在的自己\n更加優秀的──"
10070-220 = "是嗎…所以\n才是「電影」啊。"
10070-230 = "恭喜你，老師。\n問我為什麼？\n當然是老師你的生日囉。"
10070-240 = "至於禮物──\n就是我嚴選的\n十大黑色電影！"
10070-250 = "來，我們一起去看吧！"
10070-260 = "呼…\n收到老師的\n生日祝福的感覺，\n還挺不賴的嘛。"
10070-270 = "一整天都坐在\n辦公桌前，\n對身體不太好吧？"
10070-280 = "今天一整天，\n就請你陪我吧！"
10070-290 = "新年啊…\n祝你新年快樂，老師。"
10070-300 = "老師你，\n已經決定好\n今天的目標了嗎？"
10070-310 = "我的話當然是…\n朝著更加冷硬派的\n人生前進，吧。"
10070-320 = "聖誕節……是慶典嗎？"
10070-330 = "其實慶典這個詞\n包含許多意義。"
10070-340 = "…為什麼要用那種眼神看我？\n我沒有什麼特別的意思。"
10070-350 = "萬聖節嗎…\n是小孩子們\n忙碌的時期呢。"
10070-360 = "是不是該久違地\n去一趟梅花園\n發點糖果呢…"
10070-370 = "不介意的話，老師\n要不要一起去？"
10070-390 = "這個嘛…\n我喜歡雨天的景色。"
10070-400 = "許多事物看起來\n都單純許多。"
10070-410 = "白與黑──\n黑色電影的世界。"
10070-420 = "這個世界，是由過於\n耀眼的光彩所構成。"
10070-430 = "然而，人們卻沒有\n認知到這個事實… "
10070-440 = "即便是我也不例外。"
10070-450 = "但黑色電影的世界不一樣。"
10070-460 = "至少…很簡單明瞭。"
10070-470 = "不過…也對。至少\n雨傘這樣的東西…"
10070-480 = "為了避免迷路，\n還是亮色的比較好吧。"
10070-2600 = "太棒了…\n實在太適合我了，簡直像從一開始\n就是我的一樣…\n呵，我準備好了。\n來，我們出發吧。"
