[translation]
10076-10 = "Blue~! Archive!"
10076-20 = "ถ้าต้องการคำอธิบายและเสียงเชียร์ละก็\nไว้ใจฉันได้เลยค่ะ!"
10076-30 = "โอ้ คนเยอะ\nแบบนี้เลยเหรอเนี่ย!"
10076-40 = "ถ้าเป็นที่นี่ละก็\nอาจจัดงานบรรยาย\nได้เลยนะ!"
10076-50 = "สไตล์การตกแต่ง\nของคุณครูเนี่ย...\nน่าสนใจดีจังเลยค่ะ!"
10076-60 = "เอ๋... นั่นมัน...!"
10076-70 = "ไหนๆ ก็เป็นแบบนี้แล้ว\nไปหาแท่นยืนเชียร์\nกันดีมั้ยคะ?"
10076-80 = "มาแล้วเหรอคะคุณครู!\nวันนี้ก็สู้ๆ นะคะ!\nสู้ๆ...! นะคะ!"
10076-90 = "กำลังรออยู่เลยค่ะ คุณครู!\nอยากได้เสียงเชียร์จากฉัน\nมั้ยคะ?"
10076-100 = "ยะ...อยากได้ใช่มั้ยคะ?"
10076-110 = "หืม? ชุดนี้น่ะเหรอคะ?"
10076-120 = "เป็นยังไงบ้างคะ?\nสวยดีใช่มั้ยล่ะคะ?"
10076-130 = "อ่า อืมมม...\nถึงจะไม่ค่อยเข้าใจ\nเหตุผลเท่าไร"
10076-140 = "แต่ว่า... ฉันรู้สึก\nเขินนิดหน่อยค่ะ..."
10076-150 = "ยะ...อย่าเอาแต่มองฉัน\nแบบนั้นสิคะ ช่วยพูดอะไร\nสักหน่อยสิคะ!"
10076-160 = "ตอนนี้ฉันมาเข้าเวรตัวแทน\nที่ชาเล่ต์ เพราะงั้นจะส่งเสียง\nเชียร์เพื่อคุณครูคนเดียวค่ะ!"
10076-170 = "คุณครูรู้ที่มาของ\nเชียร์ลีดเดอร์หรือเปล่าคะ?"
10076-180 = "อ๊ะ... อย่างนั้นเหรอคะ"
10076-190 = "สุขสันต์วันเกิดนะคะ\nคุณครู!!"
10076-200 = "ฉันจะแสดงการแสดงพิเศษ\nให้สมกับที่วันนี้เป็นวันพิเศษ\nเลยค่ะ!"
10076-210 = "วะ...วันเกิด... ฉันเหรอคะ!?\nคะ...คิดไม่ถึงเลยค่ะว่าคุณครู\nจะจำวันเกิดของฉันได้แบบนี้..."
10076-220 = "ดีใจจังเลยค่ะ ฮิฮิฮิ..."
10076-230 = "ขอให้มีความสุขมากๆ\nในวันปีใหม่นะคะ!"
10076-240 = "เวลาที่คุณครูลำบาก\nฉันจะคอยส่งแรงเชียร์\nให้เสมอเลยค่ะ!"
10076-250 = "เมอร์รีคริสต์มาส!!\nอ๊ะ ขอบอกไว้ก่อนนะคะ\nว่าต้นกำเนิดของคริสต์มาสน่ะ..."
10076-260 = "ว้าว ข้างนอกเสียงดังกัน\nสุดๆ ไปเลยนะคะ!"
10076-270 = "อืม~ ทุกคนรู้หรือเปล่านะ\nว่าวันฮาโลวีนเป็นวันแบบไหน\nกันคะ?"
10076-290 = "อะ... เอ๋...?"
10076-300 = "อืม อื้อออ...\nต้องยืดแขนไป\nแตะให้ถึง...?"
10076-310 = "อะไรกัน...!\nถ้าออกแรงตรงนี้ขึ้น\nอีกละก็...!?"
10076-320 = "ฮึก...!?\nอะอะอะ...อ๊าย...!"
10076-330 = "ปะ... แปลกจังเลยนะคะ...!\nฉะ...ฉันก็ทำตาม\nที่อ่านมาแท้ๆ...!"
10076-340 = "ฉันรู้ว่าคนเราแต่ละคน\nมีความยืดหยุ่นไม่เท่ากันก็จริง\nแต่ว่า... ไม่คิดว่าจะเป็นแบบนี้..."
10076-350 = "ขะ... ขอลองใหม่อีกที...\nอะ... อ๊าาา...! โอ๊ย…!"
10076-360 = "มะ... มากกว่านี้ คงไม่ไหว...\nฮือออ... คะ... คือว่า...\nคุณครูคะ... นี่มัน…"
10076-370 = "ฉันไม่ได้ตั้งใจที่จะ...\nให้คุณครูเห็นสภาพแบบนี้\nหรอกนะคะ..."
10076-380 = "หมายถึงให้เห็นภาพลักษณ์\nที่ดูไม่ดีแบบนี้น่ะค่ะ..."
10076-390 = "ฮือออออ..."
10076-2600 = "ฉันอธิบายเรื่องปืนนี้ให้ฟังมั้ยคะ?\n...ฮิฮิ ล้อเล่นค่ะ คุณครูรู้อยู่\nแล้วนี่คะ ...ถ้าเรื่องแบบนี้\nเพิ่มขึ้นเรื่อยๆ ละก็ สักวันหนึ่ง..."
