[translation]
10071-10 = "蔚藍檔案。"
10071-20 = "這裡是RABBIT1。已換裝完畢。\n從現在起，開始潛入作戰。"
10071-30 = "（雖然…想沖個澡…）"
10071-40 = "從某處傳來\n好吃的味道…"
10071-50 = "（…要是有穿更可愛\n　的泳裝就好了）"
10071-60 = "這裡是，老師的…\n我剛才在想什麼…"
10071-70 = "…老師…\n會在哪裡呢…"
10071-80 = "歡迎回來，老師。"
10071-90 = "準備非常萬全。\n無論是什麼樣的命令，\n都能完美地執行。"
10071-100 = "你好，老師。\n我一直在等你。"
10071-110 = "咦……？\n問我穿著泳裝等\n會不會冷，是嗎？"
10071-120 = "沒有問題。\n無論是什麼樣的服裝，\n等待的時間都並不辛苦。"
10071-130 = "那個……這套泳裝適合我嗎？"
10071-140 = "在這之前，我只穿過\nSRT特殊學園的指定泳裝，"
10071-150 = "所以這種可愛的設計……\n讓我有點靜不下來呢。"
10071-160 = "雖然不如咲希……\n不過我對游泳還算有自信。"
10071-170 = "現在並不是在執行作戰……\n因此作戰以外的事，\n我也能幫忙。"
10071-180 = "是因為兔子\n不喜歡水的關係嗎……"
10071-190 = "好像沒看過\n兔子圖案的泳裝……"
10071-200 = "相反的，\n或許是因為牛很會游泳，\n所以有看過有人在賣\n印有牛圖案的泳裝……"
10071-210 = "如果有兔子圖案的就好了。"
10071-220 = "請更輕鬆地吩咐我們吧。"
10071-230 = "我們隨時都會\n為了老師而待命。"
10071-240 = "祝你生日快樂，老師。"
10071-250 = "那個……因為\n實在沒什麼時間，\n所以沒能準備禮物……"
10071-260 = "作為代替，\n今天我什麼事都願意做。\n──請儘管吩咐。"
10071-270 = "我的生日……是嗎？"
10071-280 = "呵呵……"
10071-290 = "禮物的話，\n我已經收到了，\n所以沒關係的。"
10071-300 = "新年快樂，老師。"
10071-310 = "今年就算沒有作戰，\n也一起去海邊……"
10071-320 = "……失禮了。\n我什麼都沒說。"
10071-330 = "在今天這種日子裡，\n不太適合穿這套服裝呢。"
10071-340 = "下次要穿更適合的……"
10071-350 = "外面真吵鬧呢……"
10071-360 = "本來想珍惜地\n度過今天這段時間的。"
10071-380 = "早安。"
10071-390 = "老師也來進行\n早上的散步嗎？"
10071-400 = "作為平時慢跑的代替，\n我打算來游個泳。"
10071-410 = "難得能到海邊來，\n我認為做點和平時\n不一樣的事也不錯。"
10071-420 = "……一早就讓老師\n看到這副模樣，\n有點不好意思。"
10071-430 = "……哈啾。"
10071-440 = "好像，有點待太久了呢……\n身體開始覺得冷了。"
10071-450 = "……說的也是。"
10071-460 = "雖然說兔子\n不能進到水裡……"
10071-470 = "但是我，並不是兔子。"
10071-2600 = "RABBIT-31式短機關槍，我確實收到了。\n為了應對水中作戰，\n我替換了部分的內部零件，\n那個…是不是應該把外部的零件\n也換成更可愛的東西比較好呢…？"
