[translation]
10074-10 = "블루 아카이브~!"
10074-20 = "시원한 물을 맞으면, 기분까지 상쾌해져요♡\n선생님도… 물놀이… 어떠세요?"
10074-30 = "어머나,\n저 사람은……."
10074-40 = "또 이렇게\n귀여운 장소가……."
10074-50 = "여기서\n물놀이를 하면\n혼나겠네요."
10074-60 = "후후,\n뜨거운 시선이\n느껴집니다♡"
10074-70 = "더 가까이\n가도 될까요?"
10074-80 = "기다리고 있었어요,\n선생님."
10074-90 = "물론, 쭉 이 모습으로♡"
10074-100 = "오셨군요, 선생님.\n저랑 같이, 일 시작하기 전에\n산책이라도 나가실래요?"
10074-110 = "제가 생각해도,\n예전보다 조금\n심술궂어진 것 같아요."
10074-120 = "선생님이 상대일 때는,\n특히요."
10074-130 = "제가 할 수 있는 일이 있다면,\n뭐든지 말씀해 주세요."
10074-140 = "아아, 거기를 만지면…\n후후후♡"
10074-150 = "후후, 죄송해요.\n선생님을 곤란하게 할\n생각은 없었어요."
10074-160 = "음? 옷이요?\n이 정도면 많이 껴입었다고\n생각하는데요."
10074-170 = "분명히 오늘\n선생님 생일이었죠?"
10074-180 = "제 선물은… 우후후♡"
10074-190 = "제 생일…\n아, 그랬죠."
10074-200 = "선물…?"
10074-210 = "평소에,\n받고 있는 걸요?"
10074-220 = "새해 복\n많이 받으세요, 선생님."
10074-230 = "올해도 이 온화한 날들이\n계속되기를 바랄 뿐입니다."
10074-240 = "크리스마스……."
10074-250 = "이 차림으로 밖에 나가면\n모두의 놀란 얼굴을\n볼 수 있겠네요♡"
10074-260 = "오늘은 할로윈이에요.\n은근슬쩍 모두에게\n이 의상을 추천해 볼까 해요."
10074-280 = "용케도 여길 찾아오셨네요.\n아니면 우연이신가요?"
10074-290 = "선생님의 일이니까…….\n분명 어쩌다가, 겠군요."
10074-300 = "후후… 그렇게 당황하지 마세요.\n옷은 제대로 입고 있으니까요."
10074-310 = "물의 온도를,\n느끼고 싶었어요."
10074-320 = "선생님도…….\n이쪽으로 오실래요?"
10074-330 = "여긴… 트리니티의 분수 때와는\n정반대의 모습이니까요."
10074-340 = "사람 하나 없고,\n자연적인 풍경……."
10074-350 = "네. 아무것도 치장하지 않은,\n있는 그대로의 모습이죠."
10074-360 = "그러니까,\n그걸 같이\n느꼈으면 해서요."
10074-370 = "……선생님만\n괜찮으시다면."
10074-2600 = "살다 보면 여러 일이 있습니다만……\n지금의 저는, 예전의 저로서는\n상상도 못 했을 거예요.\n선생님 덕분입니다. 감사합니다."
