[translation]
10077-10 = "블루 아카이브~."
10077-20 = "어라, 데리러 와주신 검까? 말해줬으면 제가 갔을 텐데~\n다시 한번, 트리니티 종합학원 정의실현부의 이치카임다.\n잘부탁드림다!"
10077-30 = "오, 여김까?\n선생님의 카페!"
10077-40 = "과연. 이런\n취향이셨군요……"
10077-50 = "여긴\n평화로워서 좋네요!"
10077-60 = "편해진다……"
10077-70 = "정리라도\n좀 도울까요……"
10077-80 = "어서 오십쇼~ 선생님!\n오늘 하루도 힘내보겠슴다!"
10077-90 = "짜잔!\n이치카, 등장임다!"
10077-100 = "…가 아니라\n선생님의 등장임다!"
10077-110 = "이야~.\n여기 업무는 편하네요!"
10077-120 = "아. 쉽다는 뜻은 아니었고,\n방향성의 이야기였슴다."
10077-130 = "제일 힘든 건……\n싸움 말리는 일인 거 같슴다."
10077-140 = "오 선생님도요?\n동지네요."
10077-150 = "모두들 전력으로 하지 말고,\n적당히 하면 좋을 텐데…"
10077-160 = "저도 선생님처럼,\n짊어질 게 생긴다면…\n뭔가에 빠질 수 있는 검까?"
10077-170 = "부탁임까?\n뭐든지 하겠슴다!"
10077-180 = "시키는 대로 하는 건\n자신 있슴다!"
10077-190 = "생신 축하드림다,\n선생님!!"
10077-200 = "무슨 좋은 일 있었슴까?\n없었다면, \n지금부터 같이 만들러 가시죠!"
10077-210 = "…음, 생일에,\n굳이 여기까지 온 이유,\n말임까?"
10077-220 = "그러네요… \n생일이니까,\n와봤다…라든가? 히히."
10077-230 = "새해 복 많이 받으십쇼,\n선생님!"
10077-240 = "올해야말로,\n느긋하게 보낼 수 있으면\n좋겠슴다!"
10077-250 = "오늘은 아침부터\n정신이 없어서\n죄송함다!"
10077-260 = "정의실현부는\n여기저기서 불려 가는\n경우가 많아서…"
10077-270 = "눈이 핑핑 돔다~!"
10077-280 = "왠지 싫은 예감이 듬다…"
10077-290 = "근데 뭐,\n대충 괜찮지 않겠슴까?\n하하!"
10077-310 = "하하! 선생님,\n여김다! 여기!\n보이심까?"
10077-320 = "아─ 이건 그냥\n풍선임다만…"
10077-330 = "왠지, 이걸 가지고 있으면\n놀이공원에서 신난 아이처럼\n보이네요…하하."
10077-340 = "아! 제꺼 아님다!\n…그게, 어쩌다 보니,\n잠깐."
10077-350 = "아, 어……\n그렇긴합니다만…\n어떻게 알았슴까?"
10077-360 = "뭐지…?\n얼굴에 티가 났나…?"
10077-370 = "뭐 상관없지…\n이 각도에서 선생님을 보는 건,\n처음임다."
10077-380 = "시점이 다르면,\n보이는 방법도 달라지는 것\n같다고나 할까……"
10077-390 = "…왠지, 재밌네요."
10077-400 = "이 느낌, 마음에 듬다!\n하하!"
10077-2600 = "뭐랄까…… 참.\n이렇게 좋게 봐 주시는 건 당연히 감사함다만,제게 그럴 가치가 있는지는……\n그래도…… 기쁘네요. 정말로."
