[translation]
10072-10 = "Blue Archive."
10072-20 = "RABBIT 2, mission preparation completed. Remember your training, even at sea!"
10072-30 = "(This outfit really is uncomfortable to move around in, especially indoors...)"
10072-40 = "(Is...that edible...?)"
10072-50 = "Dressing like this for the next mission might not be a bad idea."
10072-60 = "Could that be...the weapon I saw in the manual...?"
10072-70 = "Nothing to report! Continue patrol!"
10072-80 = "Hello, Sensei. I was just cleaning my gun."
10072-90 = "Wh-Whoa! When did you get here?"
10072-100 = "I wasn't slacking off!"
10072-110 = "It's really hot again today."
10072-120 = "Are you making sure everyone is taking preventative measures against heat stroke?"
10072-130 = "We need to be careful about dehydration. Drinking water is very important."
10072-140 = "It's also important to get enough sodium."
10072-150 = "I really don't like the ocean much."
10072-160 = "Firearms malfunction more easily in that environment."
10072-170 = "But an SRT student should be prepared for any situation."
10072-180 = "I'm using a waterproof tactical map, meant to be used at sea."
10072-190 = "Moe said to just use some waterproofed GPS equipment, but..."
10072-200 = "I don't want to do that. A paper map has a value of it's own."
10072-210 = "(It would have been nice to come to the sea with everyone for a reason other than a mission...)"
10072-220 = "What did I do with my helmet?"
10072-230 = "This boonie hat is serving as my helmet."
10072-240 = "This actually happens to be made of bulletproof fiber!"
10072-250 = "Happy birthday, Sensei."
10072-260 = "I'll handle the busywork for today. Go home early and get some rest."
10072-270 = "If you end up working late even on your birthday... That's just kind of sad."
10072-280 = "...A birthday gift? I...don't really need anything..."
10072-290 = "If it's okay with you, let's have dinner together."
10072-300 = "I don't care what we eat. Even just convenience store food is fine."
10072-310 = "Happy New Year, Sensei! What's your resolution?"
10072-320 = "As for me... I want to eat fresh fish at least once a week..."
10072-330 = "I-I mean... I'll work hard to resurrect SRT Academy!"
10072-340 = "Oh, Sensei. If you have some time in the evening, please stop by Kousagi Park."
10072-350 = "Moe got a large turkey to celebrate Christmas, but..."
10072-360 = "It was way too big for RABBIT Squad to finish on our own."
10072-370 = "Having a BBQ at Schale might be difficult so...let's have a party at the park."
10072-380 = "Recently, I've noticed more pumpkin in the convenience store lunches other students throw away..."
10072-390 = "Does that mean...that the Halloween season I've heard so much about is upon us?"
10072-410 = "(Now, Sensei. Stay calm and keep your eyes on me.)"
10072-420 = "(Good, nice and slow. Inhale. Exhale. Slowly.)"
10072-430 = "(Heehee. You're a fast learner. I expected nothing less, Sensei.)"
10072-440 = "(...It feels strange.)"
10072-450 = "(Being in the water here with you, communicating with nothing but our eyes and hand gestures...)"
10072-460 = "(This is...)"
10072-470 = "(...Oh? I look like I'm running out of breath?)"
10072-480 = "(No, no. There's no problem. I'm fine!)"
10072-490 = "(But my breathing... It does feel a little...shaky.)"
10072-500 = "(Maybe... Diving with Sensei... Perhaps I wasn't ready...)"
10072-2600 = "RABBIT Type 26 Machine Gun, acquired. Fully waterproofed, this baby won't malfunction even on the high seas. Of course, I still need to clean and oil it after every battle..."
