[translation]
10084-10 = "블루, 아카이브."
10084-20 = "…여기에 계셨군요. 산이든, 바다든…\n선생님의 목소리는 어디서도 놓치지 않습니다."
10084-30 = "이것이… 요새\nSNS에서 화제가 된\n그 인테리어군요…"
10084-40 = "지금 흐르는 이 곡…\n곡 이름이…\n생각나지 않습니다."
10084-50 = "…분명 이 근처에\n두었을 텐데…"
10084-60 = "…녹음 완료했습니다."
10084-70 = "(으음…?\n방금 신경 쓰이는\n이야기를 들은 것\n같습니다만…)"
10084-80 = "아, 선생님.\n신발을 바꾸셨나 보군요."
10084-90 = "발소리가 달라져서\n깜짝, 놀랐습니다."
10084-100 = "앗, 선생님…\n어서 오십시오."
10084-110 = "따, 딱히…\n수상한 일을 하고\n있었던 건 아닙니다."
10084-120 = "서, 선생님을 위해\n의자를 따듯하게 덥히고\n있었을 뿐이니까요."
10084-130 = "이번 주말에는 따듯하게\n입는 것을 추천드립니다."
10084-140 = "한파로 기온이 급격히\n떨어진다고 하는군요."
10084-150 = "외출할 계획이 있는 건\n어떻게 알았냐고요…?"
10084-160 = "어, 그게 그러니까…"
10084-170 = "우연, 입니다."
10084-180 = "개인적으로는 겨울 산을\n좋아하는 편입니다."
10084-190 = "겨울에는 먼 곳의 소리도\n잘 들리거든요."
10084-200 = "그러니… 겨울 산에서\n대화를 할 때는\n부디 조심하시길."
10084-210 = "비밀스러운 이야기를\n나누기에는 적합하지 않거든요."
10084-220 = "어째서 대부분의 송신탑은\n산 위에 있는 걸까요…"
10084-230 = "아니, 이유는 알고 있지만…"
10084-240 = "접근하기가 어려워서\n매번 도청을 할 때마다\n애를 먹고 맙니다."
10084-250 = "…이 시기에는 붉은겨울 학원의\n선전 방송이 자주 혼선되네요…"
10084-260 = "이런 곳까지 전파를 보내다니…"
10084-270 = "그 학원의 선전은\n꽤나 골치가 아프군요."
10084-280 = "겨울 산에서는 야생동물…"
10084-290 = "그중에서도\n뱀을 조심하시길."
10084-300 = "항아리를 짊어지고 등산을 하다가\n뱀과 마주치는 바람에 등산을\n포기하게 된 사람들이\n꽤 있다고 합니다."
10084-310 = "생일 축하드립니다, 선생님."
10084-320 = "선생님의 편안한 숙면을 위해\n자작 ASMR 음성을\n준비했습니다."
10084-330 = "오늘 밤, 자기 전에\n꼭 한 번 들어봐 주시길."
10084-340 = "제, 제 생일 말인가요?"
10084-350 = "아… 추, 축하해 주셔서\n감사합니다."
10084-360 = "…방금 그 말, 다시 한번\n부탁드려도 괜찮을까요?"
10084-370 = "새해 복 많이 받으시길."
10084-380 = "…올해 첫 번째의 이 인사를\n선생님께 가장 먼저\n들려드릴 수 있어 기쁩니다."
10084-390 = "오늘 같은 날에 연인들이\n주고받는 달콤한 통화를\n듣고 있노라면,"
10084-400 = "왠지 모르게\n저도 감상적인\n기분에 들게 되네요…"
10084-410 = "…네? 그건\n도청 아니냐고요…?"
10084-420 = "그게 그러니까,\n어… 아닐 걸요…?"
10084-430 = "호박 깎는 소리가\n생각보다 듣기 좋아서…"
10084-440 = "정신을 차리고 보니\n호박 장식을 여러 개\n만들고 말았습니다."
10084-450 = "괜찮으시다면 하나,\n받아 가시겠어요?"
10084-470 = "선생님,\n목소리를 낮춰주세요."
10084-480 = "숨을 죽이고,\n나무에 다가가서…"
10084-490 = "안에서 들리는 소리에\n귀를 기울여 보세요."
10084-500 = "…들리시나요?"
10084-510 = "나무줄기를 타고\n물이 오르는 소리가."
10084-520 = "이 나무는 잎을 모두\n떨어뜨리고, 마치 삶의 의지를\n포기한 것처럼 보이지만."
10084-530 = "지금도 이렇게,\n힘차게 물을\n끌어올리고 있어요."
10084-540 = "언뜻 보기에\n고요해 보이는 이 숲도.\n실은 다채로운 울림으로\n가득 차 있기에…"
10084-550 = "…후후. 소리 때문에\n지루할 틈은 앞으로도\n없을 것 같네요."
10084-2600 = "총을 쏠 때마다 선생님의 목소리가\n들리게 된다면 좋을 텐데………\n진지하게 제작을 고민해 봐야겠습니다."
