[translation]
10085-10 = "블루, 아카이브."
10085-20 = "전파가 닿지 않는 이 상황…\n해커에게는 가혹한 환경이지만,\n베리타스의 멤버가 이 정도로 포기할 수는 없지."
10085-30 = "여기는\n따듯해서 좋네…"
10085-40 = "(저렇게 입으면…\n춥지 않으려나?)"
10085-50 = "요괴 MAX 한 잔.\n젓지 말고…\n흔들지도 말고."
10085-60 = "(편안하다…\n여기서 영원히\n나가고 싶지 않아…)"
10085-70 = "(이상한 이름의\n와이파이가 잔뜩…)"
10085-80 = "으윽…\n나가는 거야?\n지금?"
10085-90 = "좀 더 여기서 쉬고 싶은데…"
10085-100 = "기다리고 있었어, 선생님."
10085-110 = "…춥지?\n커피 한 잔 내려줄까?"
10085-120 = "최근에 나온 캠핑용 침대는\n꽤 괜찮은 게 많네…"
10085-130 = "하나 사서 부실에\n설치해 둘까…?"
10085-140 = "캠핑 장비들은 대부분\n설치가 간편해서"
10085-150 = "인도어파 학생들에게도\n꽤 수요가 있을 것 같아."
10085-160 = "물론 치우는 과정은\n몇 배로 더 귀찮겠지만…"
10085-170 = "캠핑장에서 먹는\n즉석 식품은 왜 그렇게\n맛있는 걸까…?"
10085-180 = "다음에 캠핑을 가게 된다면\n요괴 MAX를 종류별로\n챙겨 가서 시음해 봐야겠어."
10085-190 = "소란스러운 장소에서\n코딩을 하다 보면,"
10085-200 = "야영장의 정적이 조금\n그리워질 때가 있어."
10085-210 = "인터넷이 없던 시절에는\n어떻게 시간을 보냈던 걸까…"
10085-220 = "선생님, 오늘이 생일이었지?"
10085-230 = "선물이라기는 뭣하지만,\n원하는 정보가 있다면 말해줘."
10085-240 = "무엇이든 찾아줄게."
10085-250 = "나에 대한 정보라도…\n상관없지만."
10085-260 = "내 생일 선물…?\n일부러 챙겨주지 않아도\n괜찮은데…"
10085-270 = "그럼 카페라떼 한 잔만\n타 줄 수 있을까?\n연유를 잔뜩 넣어서 진하게."
10085-280 = "새해 복 많이 받아, 선생님."
10085-290 = "안 그래도\n밀레니엄 타워 앞에서\n감주를 나누어 주고 있더라고."
10085-300 = "꽤 달콤해서 맛있었는데…"
10085-310 = "감주 맛의 요괴 MAX가\n출시되어도 좋을 것 같네."
10085-320 = "사람들이 거리에 잔뜩…\n다들 이렇게 추운데도\n밖에 잘 나가네."
10085-330 = "크리스마스 이브를 가장\n제대로 즐길 수 있는 장소는\n푹신푹신한 이불 속인데…"
10085-340 = "……이상한 뜻이 아니거든!"
10085-350 = "할로윈에는\n무얼 할 예정이냐고?"
10085-360 = "군것질거리를\n잔뜩 사서 부원들과\n함께 게임을 할 거야."
10085-370 = "매년 이 시즌에 나오는\n좋아하는 호러 게임\n시리즈가 있거든."
10085-390 = "하늘에 빛이 가득해…"
10085-400 = "이렇게 반짝이는\n밤하늘은\n처음인 것 같아."
10085-410 = "저 빛나는 점 하나하나가\n방대한 정보를 담은\n노드라고 생각하면"
10085-420 = "새삼 경외감이 느껴질 정도네."
10085-430 = "내가 알고 있는 모든\n정보를 쌓는다 해도"
10085-440 = "저 빛에는 차마 닿지 못하겠지."
10085-450 = "…하지만 나는\n포기하지 않을 거야."
10085-460 = "진리는 언제나\n빛을 향하는 법이니까."
10085-470 = "하늘 위의 머나먼 별들에게\n경의를 담은 인사를."
10085-480 = "안녕하세요.\n잘 지내시나요?"
10085-2600 = "산을 오르면서 총이 얼마나\n무거운지 최근 새삼 깨닫게 되었어…\n다음번에는 경량 모델로 개조해 볼까."
