[translation]
10098-10 = "蔚藍檔案。"
10098-20 = "哎呀～事情大條了呢……\n這下……大叔我不得不出馬了呢。"
10098-30 = "（掩蔽物……確認。\n　出入口……確認）"
10098-40 = "總之，先\n確認彈藥吧。"
10098-50 = "唔嘿……\n有點靜不下來呢……\n這種時候，好像有點\n想見到老師……"
10098-60 = "這個髮型，確實是\n挺方便的沒錯……\n不會怪怪的嗎？"
10098-70 = "今天不太想睡午覺啊……"
10098-80 = "哦～老師，辛苦了～"
10098-90 = "來的路上還好嗎～？\n沒有人跟蹤你吧～？"
10098-100 = "老師～今天工作也加油哦～"
10098-110 = "大叔我會好～好\n看著你的唷？"
10098-120 = "咦，老師喜歡\n這種打扮嗎……"
10098-130 = "唔嗯……大叔我\n有點無法理解……"
10098-140 = "糖分是很重要的哦～\n所以我都會隨身帶著糖果～\n老師要不要也來一顆？"
10098-150 = "嗯～哈啊。"
10098-160 = "老師～不好意思，\n能請你幫我按摩一下嗎～？"
10098-170 = "打扮成這副模樣，\n肩膀很快就僵硬了。"
10098-180 = "背要緊貼牆壁。\n這是室內戰的基本哦～"
10098-190 = "沒錯，就是現在那個位置。\n還算是挺管用的，\n所以要記好喔～"
10098-200 = "老師今天也要加班嗎～？"
10098-210 = "來，熱咖啡。"
10098-220 = "用這個來迎接夜戰吧。"
10098-230 = "老師，生日快樂～"
10098-240 = "至於禮物嘛……唔嗯……"
10098-250 = "要不要摸摸看我的槍呀～？"
10098-260 = "啊啊，原來是我的生日嗎……\n其實我不是很在意的……"
10098-270 = "不過老師能夠記得……\n好像有點開心。"
10098-280 = "新年快樂，老師。"
10098-290 = "要是今年老師和我，\n都能悠悠哉哉的就好了～"
10098-300 = "聖誕禮物嗎……"
10098-310 = "如果能收到的話，\n槍的整備套裝好像不錯。"
10098-320 = "最近剛好想買套新的來換了～"
10098-330 = "唔嘿～今天的話，\n就算穿成這副模樣，\n看起來應該也很正常吧？"
10098-340 = "老師，要不要\n一起出去走走～？"
10098-350 = "哦～老師，辛苦了～"
10098-360 = "來的路上還好嗎～？\n沒有人跟蹤你吧～？"
10098-370 = "老師～今天工作也加油哦～"
10098-380 = "大叔我會好～好\n看著你的唷？"
10098-390 = "咦，老師喜歡\n這種打扮嗎……"
10098-400 = "唔嗯……大叔我\n有點無法理解……"
10098-410 = "糖分是很重要的哦～\n所以我都會隨身帶著糖果～\n老師要不要也來一顆？"
10098-420 = "嗯～哈啊。"
10098-430 = "老師～不好意思，\n能請你幫我按摩一下嗎～？"
10098-440 = "打扮成這副模樣，\n肩膀很快就僵硬了。"
10098-450 = "背要緊貼牆壁。\n這是室內戰的基本哦～"
10098-460 = "沒錯，就是現在那個位置。\n還算是挺管用的，\n所以要記好喔～"
10098-470 = "老師今天也要加班嗎～？"
10098-480 = "來，熱咖啡。"
10098-490 = "用這個來迎接夜戰吧。"
10098-500 = "老師，生日快樂～"
10098-510 = "至於禮物嘛……唔嗯……"
10098-520 = "要不要摸摸看我的槍呀～？"
10098-530 = "啊啊，原來是我的生日嗎……\n其實我不是很在意的……"
10098-540 = "不過老師能夠記得……\n好像有點開心。"
10098-550 = "新年快樂，老師。"
10098-560 = "要是今年老師和我，\n都能悠悠哉哉的就好了～"
10098-570 = "聖誕禮物嗎……"
10098-580 = "如果能收到的話，\n槍的整備套裝好像不錯。"
10098-590 = "最近剛好想買套新的來換了～"
10098-600 = "唔嘿～今天的話，\n就算穿成這副模樣，\n看起來應該也很正常吧？"
10098-610 = "老師，要不要\n一起出去走走～？"
10098-630 = "哎呀～時間都\n已經這麼晚了呀。"
10098-640 = "事到如今，\n也只能等到早上了呢。"
10098-650 = "……咦？"
10098-660 = "又來了又來了～\n跟這種大叔待在一起，\n其實一點也不有趣吧～"
10098-670 = "唔，唔嘿～那個設定，\n還要堅持下去嗎……？"
10098-680 = "對大叔我來說，\n負擔好像有點重呢～"
10098-690 = "……算了，如果老師\n願意擔任夥伴職位的話……\n我就配合一下吧。"
10098-700 = "那麼，英雄和夥伴\n就來吃點簡單的晚餐吧。\n……雖然只是緊急口糧。"
10098-710 = "這個嘛，雖然那麼說也沒錯～"
10098-720 = "大叔我就是喜歡這個。\n你就體諒一下吧～"
10098-2600 = "……如果需要大叔的力量的話，\n隨時要告訴我哦？\n因為老師的事對我來說，\n永遠是最優先的。"
