[translation]
10092-10 = "Blue Archive!!"
10092-20 = "Look forward to it, if you want— No! You should look forward to it...to my performance!"
10092-30 = "Pretty big... Maybe it'd be good for a performance."
10092-40 = "I wanted to get some practice done, but there's too many people..."
10092-50 = "I've got a craving. Is there anything sweet anywhere around here?"
10092-60 = "Maybe I'll rest for a little..."
10092-70 = "Wait. Weren't we supposed to meet up here?"
10092-80 = "S-Sensei?! When did you get here...?!"
10092-90 = "M-Me? I-I was just practicing a little..."
10092-100 = "Welcome, Sensei!"
10092-110 = "B-By any ch-chance..."
10092-120 = "Do you need...background music? Want to me to play...?"
10092-130 = "For some reason, I'm feeling more confident than usual about this."
10092-140 = "Wh-What's wrong?! Why are you staring at me like that...?"
10092-150 = "If there's something you want, then say it!"
10092-160 = "Maybe I should've brought something to eat..."
10092-170 = "Sensei, is there anything you've been craving?"
10092-180 = "I thought practice would be better than class..."
10092-190 = "...but it's pretty hard, if you're serious about it."
10092-200 = "Hm? Am I not busy with practice?"
10092-210 = "Th-That is true..."
10092-220 = "But why are you asking me that all of a sudden?! You're doing that on purpose, right?! So that you can say something cheesy!!"
10092-230 = "Happy birthday! Happy birthday to you! ♪"
10092-240 = "Why am I singing?!"
10092-250 = "D-Don't ask stupid questions!"
10092-260 = "H-Huh? My birthday...?"
10092-270 = "So you really did remember?"
10092-280 = "Happy New Year, Sensei!"
10092-290 = "Any song you wanna listen to?"
10092-300 = "It's Christmas!"
10092-310 = "Wh-What?! I'm not so young that I'd still believe in Santa, all right?!"
10092-320 = "It's pretty rowdy today! I don't hate it. It makes me want to do something."
10092-340 = "Phew... Phew... ...Y-Yes... I did it..."
10092-350 = "I-Is that so...? Sensei, it was like that to you too...?"
10092-360 = "You're not playing with me, right? This is...real, right?"
10092-370 = "It feels like... My heart is pounding..."
10092-380 = "It's my first time feeling something like this..."
10092-390 = "...Sensei... Thinking about it, I think I showed Sensei, for the first time..."
10092-400 = "How should I say it...? Um..."
10092-410 = "...A \"cool\" side of me... I should say..."
10092-2600 = "Sensei is always Sensei, no matter the situation. That's how it is. But you can always...just call me if you need me. I'll be there!"
