[translation]
10097-10 = "블루 아카이브!"
10097-20 = "RABBIT 3, 현장에 도착~\n쿠히히… 바다 위에서라면,\n마음껏 폭탄을 사용해도 괜찮겠지?"
10097-30 = "어딘가에 수류탄이\n떨어져 있지 않으려나…"
10097-40 = "하아… 지쳤다…"
10097-50 = "파멸의 향기가…"
10097-60 = "쿠히히… 이 버튼은\n어디에 연결되어\n있으려나…"
10097-70 = "이 카페의 방화벽은\n쓸데없이 튼튼하단 말이지…"
10097-80 = "어서 와. 선생님.\n오늘은 어느 해변을\n폭격하러 갈까?"
10097-90 = "아, 선생님. 지시를\n기다리고 있었어."
10097-100 = "언제든 터트릴 수 있도록\n폭탄을 잔뜩 설치했으니까."
10097-110 = "그런 지시 한 적 없다고…?"
10097-120 = "뭐 어때. 좋은 게\n좋은 거잖아. 쿠히히…"
10097-130 = "이 수영복, 조금 작아서\n아플 정도로 달라붙는단\n말이지…"
10097-140 = "하지만 그 점이 좋아…\n하아, 하아…"
10097-150 = "수영? 당연히 할 줄 아는데?"
10097-160 = "오퍼레이터라 해도,\n일단은 SRT의 일원이니까."
10097-170 = "깊은 바닷속을 보고 있노라면\n경이로움에 앞서\n공포가 느껴질 때가 있어."
10097-180 = "바닥이 보이지 않는\n저 심연에 떨어진다면,"
10097-190 = "얼마나 파멸적인\n기분이 들까… 하아, 하아…"
10097-200 = "으으, 배고파… 선생님,\n뭔가 달달한 거 없어?"
10097-210 = "쿠사야를 너무 많이\n먹었나… 입에서 비릿한 맛이\n사라지질 않아…"
10097-220 = "생일 축하해, 선생님."
10097-230 = "이번 생일에는\n촛불 대신 폭탄의 도화선을\n꺼보는 건 어때?"
10097-240 = "훨씬 더 자극적인\n추억이 될 거야. 쿠히히…"
10097-250 = "생일 선물로 받고 싶은\n물건이 있냐고?"
10097-260 = "음… 의류 수선권이려나."
10097-270 = "옷을 가슴둘레에 맞추어 사면\n언제나 소매는 길고\n허리는 짧아서 핏이 나빠지거든."
10097-280 = "새해 복 많이 받아 선생님.\n올해도 아낌없는 지원\n부탁할게. 후후…"
10097-290 = "선생님, 이번 크리스마스도\n괜찮으면 코우사기\n공원에 들러줘."
10097-300 = "바비큐 파티를 할 예정이거든."
10097-310 = "커다란 칠면조는 물론이고…\n특제 쿠사야도 준비했어."
10097-320 = "아, 물론 소대원들에게는\n비밀이지만."
10097-330 = "귀신 분장이 자주 보인다\n싶더니만, 벌써 할로윈\n시즌인가…"
10097-340 = "…응? 귀신이 무섭지 않냐고?"
10097-350 = "에이, 그럴 리가.\n이미 파멸해 버린 존재잖아?"
10097-370 = "으음, 아무리 봐도\n화력이 부족한 것 같은데…"
10097-380 = "뭐, 연기가 나고 있으니\n괜찮으려나."
10097-390 = "그러고 보니 이 냄새를\n맡는 것도 오랜만이네."
10097-400 = "SRT에 있었을 때……\n아니, 그보다 더 옛날이려나?"
10097-410 = "이 향기를 맡고 있으면 어쩐지,\n지나간 옛 여름이 생각나."
10097-420 = "참 신기하네."
10097-430 = "이 연기는 벌레들을 쫓는\n파멸의 향취일 텐데."
10097-440 = "어떤 사람에겐\n반가운 정취가 된다니……"
10097-450 = "사람이란 의외로\n파멸을 좋아하는 걸지도.\n쿠히히…"
10097-460 = "선생님, 조금만 더\n이쪽으로 와볼래?"
10097-470 = "선생님에게 나쁜 벌레가\n꼬이면 큰일이니까…"
10097-480 = "오늘 밤은 이걸\n잔뜩 쐬고 가자고."
10097-2600 = "RABBIT 224식 권총, 수령 완료.\n그나저나 나는 물에 들어갈 일도 없는데,\n방수 처리도 해야 하는 거야?\n귀찮게시리…"
