[translation]
10102-10 = "브, 블루 아카이브……!"
10102-20 = "헤, 헤헤, 결국 와 버렸네요……!\n여름, 바다…… 행복해요……!"
10102-30 = "여긴……\n뭐 하는 곳인가요?"
10102-40 = "헤헤……\n시원하네요……\n밖에 나가면\n다시 덥겠지만요……"
10102-50 = "사오리 언니는,\n지금쯤......."
10102-60 = "잡지 경품 응모 엽서,\n여기서 써도 될까요……?"
10102-70 = "수영복이 조금\n끼는 것 같은데……\n제 몸에 이상이 있는\n건 아니겠죠……?"
10102-80 = "아, 서, 선생님?\n오늘은, 물놀이\n안 하시나요……?"
10102-90 = "헤헤……\n오늘 당번인데요……\n신세 좀 지겠습니다……!"
10102-100 = "헤, 헤헤, 실례가\n안 된다면 아이스크림\n하나만……"
10102-110 = "네?! '히요리가 먹을\n줄 알고 사뒀다'……?"
10102-120 = "고맙습니다!\n역시 선생님이에요……!"
10102-130 = "샬레에 비치된 잡지도\n지지난달 거네요……!"
10102-140 = "역시 인생은\n괴로운 거네요……!"
10102-150 = "헤, 헤헤, 절망적인 사실을\n하나 가르쳐 드릴게요……."
10102-160 = "휴게실 냉장고에\n얼음이 동났어요......"
10102-170 = "역시 인생은\n괴로운 거네요……\n여름엔 더더욱이요."
10102-180 = "에헤헤…… 네, 네에? 이거요?\n음, 바다에서 같이 찍은\n사진인데요……"
10102-190 = "선생님도 보실래요?"
10102-200 = "헤헤,\n시원한 디저트가 잔뜩…….\n다음에는 스쿼드의 모두를\n데리고 와도 될까요?"
10102-210 = "생일 축하드려요……!"
10102-220 = "괴로운 인생이 시작된 날이지만,\n가끔은 즐기는 것도 좋겠죠……."
10102-230 = "제 생일……\n별다른 감흥은 없는데요……"
10102-240 = "하지만 선생님 말씀 덕분에, \n조금 특별한 날이 되어버렸네요."
10102-250 = "새해 복 많이 받으세요…….\n올해도 괴로운 일들이 많겠지만,\n또 계속 살아가야겠죠……."
10102-260 = "헤헤,\n올해도 잘 부탁드려요."
10102-270 = "크, 크리스마스 선물이에요……!\n보잘것없지만,\n요 밑 편의점에서 샀어요."
10102-280 = "그, 바, 받아주셨으면……\n하는데요. 헤헤."
10102-290 = "사, 사탕은\n가진 게 없는데요……\n대, 대신 장난을 치세요……."
10102-300 = "네? 선생님이 저한테\n주시는 거라고요?"
10102-310 = "헤, 헤헤헤,\n그럼 감사히 받겠습니다."
10102-330 = "아야야야…… 아파요오……."
10102-340 = "히엑?!\n제 아이스바가?!"
10102-350 = "망했어요! 완전 망했어요!\n한 입밖에 못 먹었는데\n모래투성이가 되다니……!"
10102-360 = "역시 저한테는 아이스바조차\n허락되지 않는 거네요……!\n완전히 버림받았어요……!"
10102-370 = "제 인생은 왜 이렇게\n고난으로 가득 차 있을까요?"
10102-380 = "다른 사람은 여름을\n즐기고 있는데……."
10102-390 = "아무리 노력해도,\n제게 있어서는 도달할 수 없는\n꿈 같은 거라니……."
10102-400 = "……네? 하나 더\n사 주신다고요?"
10102-410 = "그럼 떨어뜨린 아이스바가\n멀쩡했다면 두 배로\n먹을 수 있었겠네요……?"
10102-420 = "우아아앙!\n역시 망했어요!"
10102-2600 = "헤, 헤헤, 이런 귀한 물건을 저에게…….\n나, 나중에 돌려달라고 해도\n안 드릴 거니까요……!"
