[translation]
10103-10 = "Blue Archive!"
10103-20 = "ในฐานะสมาชิกคณะความมั่นคงของเรดวินเทอร์\nฉันจะแสดงให้เห็นถึงความกล้าหาญเอง!"
10103-30 = "นี่มันอะไรน่ะ...\nน่ารักจัง?"
10103-40 = "มะ... เมื่อกี้เหมือนจะ\nมีอะไรเย็นๆ\nลอดผ่านขาไปเลย..."
10103-50 = "ถ้าไม่แสดงภาพลักษณ์\nที่สง่างามกว่านี้\nให้เห็นละก็..."
10103-60 = "ฮ้าว...\nถึงจะอยู่เฉยๆ แบบนี้\nก็ยังเมื่อยนิดหน่อยแฮะ"
10103-70 = "(พวกนักเรียนคนอื่นไม่รู้สึก\nอะไรกับการใส่เสื้อผ้าบางๆ\nแบบนี้เลยงั้นเหรอ?)"
10103-80 = "กำลังรออยู่เลย ครู\nเอาละ บอกพิกัดการโจมตี\nครั้งต่อไปให้หน่อยได้มั้ย?"
10103-90 = "อืม อืมมม..."
10103-100 = "ว้าก? ครู!?\nมาตอนไหนเนี่ย...?"
10103-110 = "ฉะ...ฉันไม่ได้\nแอบงีบอยู่หรอกนะ!"
10103-120 = "ฉันได้ยินมาจากนักเรียนของซานไห่จิง\nถ้าฝึกศิลปะการต่อสู้ละก็จะสามารถ\nเคลื่อนที่ในระยะไกลได้ในพริบตาเลย..."
10103-130 = "เรื่องจริงรึเปล่านะ?"
10103-140 = "งั้นถ้าเรียนรู้เทคนิคพวกนั้นไว้...\nฉันก็จะบุกจู่โจมได้รุนแรงกว่านี้สินะ!"
10103-150 = "ได้ยินว่ามีร้านอาหารดีๆ\nอยู่ที่ย่านการค้าเทพเต่าดำด้วย..."
10103-160 = "ครู... จะไปด้วยกันมั้ย?"
10103-170 = "คือ... ถ้าไปคนเดียวละก็\nฉันอาจจะหลงทางได้น่ะ..."
10103-180 = "ได้ยินว่าหมีของซานไห่จิง\nเป็นพวกกินพืชน่ะ"
10103-190 = "พวกมันคงมีนิสัยอ่อนโยน\nและมีขนนุ่มนิ่มๆ น่าจับแน่ๆ เลย..."
10103-200 = "อยากลองจับดูสักครั้งจัง..."
10103-210 = "(ที่กระโปรงมันแหวกขึ้นมาแบบนี้...\nเป็นดีไซน์ที่ถูกแล้วใช่มั้ยนะ...?)"
10103-220 = "(คงไม่ได้โดนตั้งใจฉีก\nหรอกใช่มั้ย?!)"
10103-230 = "เห็นชุดที่นักเรียนที่นี่ใส่\nแล้วหนาวแทนเลย…\nรู้สึกแปลกๆ อย่างบอกไม่ถูกเลยแฮะ"
10103-240 = "ที่เรดวินเทอร์\nจะต้องใส่เสื้อผ้า\nหลายชั้นเลยน่ะ"
10103-250 = "เอาเถอะ ถึงยังไง\nก็คงไม่มีนักเรียนที่ใส่เสื้อผ้าบางๆ\nเดินบนธารน้ำแข็งหรอกมั้ง ฮ่าฮ่า!"
10103-260 = "วันนี้...\nเป็นวันเกิดครูเหรอ?"
10103-270 = "ที่นี่ไม่ใช่เรดวินเทอร์\nฉันเลยมอบเสบียง\nหรือเหรียญตราอะไรให้ไม่ได้..."
10103-280 = "อืม งั้นวันนี้ฉันจะทำตามคำสั่งครูก็แล้วกัน\nสั่งมาได้ทุกอย่างเลย!\nเพราะงั้นสั่งมาได้ตามต้องการเลยนะ ครู!"
10103-290 = "ต้องฉลองวันเกิดในเขตอื่น...\nรู้สึกเหงานิดหน่อยนะ"
10103-300 = "แต่ถ้าคุณครูเป็น\nเมดเวเดฟให้แทนละก็\nฉันอาจจะเหงาน้อยลงก็ได้"
10103-310 = "ขอให้มีความสุขในวันปีใหม่นะ ครู\nฉันตั้งตารอกิจกรรมที่โดดเด่น\nในปีนี้อีกเหมือนกันนะ"
10103-320 = "ฉันเข้าใจผิดว่าสมาชิก\nชมรมการแสดงงิ้วที่ใส่ชุดสีแดง\nเป็นซานตาคลอสน่ะ..."
10103-330 = "ฉันก็เผลอตื่นเต้นเกินไป\nโดยไม่รู้ตัวน่ะ..."
10103-340 = "ฉันกำลังตั้งตารอ\nของขวัญคริสต์มาสอยู่เลย..."
10103-350 = "เมื่อกี้โดนเด็กนักเรียน\nของสวนต้นบ๊วยแกล้งเอาน่ะ"
10103-360 = "แค่เพราะฉันไม่มีลูกอม\nก็เลยมาล้อเล่นเอาตามใจชอบ..."
10103-370 = "คิดแล้วเชียว\nฉันชอบฮาโลวีนไม่ลงจริงๆ!"
10103-390 = "บะ... แบบนี้? เอ๋?\nอ้าขาให้กว้างอีกหน่อย...\nแขนด้วย...?"
10103-400 = "อือ... เรื่องแบบนี้\nฉันไม่ชินเลย..."
10103-410 = "นี่... ครู...\nฉันในตอนนี้ดูเป็นยังไงบ้าง...?"
10103-420 = "เฮือก...? ดูมีเสน่ห์\nต่างจากตอนปกติเหรอ...?"
10103-430 = "บะ... บ้า!\nอย่ามาแกล้งพูดหน่อยเลย...!"
10103-440 = "พะ... พูดจริงเหรอ...?"
10103-450 = "รอรูปถ่ายอยู่ด้วยงั้นเหรอ...?"
10103-460 = "อึก...! วันนี้ครูก็...\nมีเจตนาไม่บริสุทธิ์อีกแล้วนะ..."
10103-2600 = "อ่า... บาลาไลกา ไม่มีอะไรดีกว่า\nปืนกลมือที่มีสลิงยึดจับเพื่อให้\nโจมตีได้อย่างมั่นคงแล้วละ\nแต่พอใส่ชุดแบบนี้ สายคล้องไหล่\nมันก็เสียดสีกับผิวจนเจ็บนิดหน่อยน่ะ..."
