[translation]
10118-10 = "Blue Archive!"
10118-20 = "Whether it be train operation or track installation, leave it to me! Pahyahya!"
10118-30 = "Ah, this is that one place? Heh..."
10118-40 = "Should I slack off here for today?"
10118-50 = "There's sooo much fun stuff here. I should've come to visit earlier."
10118-60 = "Where's Sensei? I had something to say... Ehhh, I forgot."
10118-70 = "Phew! I'm RELAXED! At this rate, maybe I'll just conk out? But that'd be a waste of time, right? Haha!"
10118-80 = "Huh, you're here now?"
10118-90 = "I was waiting! Pahyahya!"
10118-100 = "Sensei, you're late!"
10118-110 = "Making a student rep wait..."
10118-120 = "Well, I just got here too, though!!"
10118-130 = "So, what we doin'? You can assign me anything!"
10118-140 = "Ah. No paperwork, though."
10118-150 = "...In that case, there's nothing to do?"
10118-160 = "Sensei, you're busier than I thought."
10118-170 = "I'll feed you snacks then."
10118-180 = "Say, \"Ahhh!\""
10118-190 = "Pahyahya!"
10118-200 = "You've got a clumsy side, Sensei."
10118-210 = "To be specific..."
10118-220 = "There's no way I'd tell you! Pahyahya!"
10118-230 = "Hold on! Aren't you poking me too much?"
10118-240 = "You don't have anything else to do?"
10118-250 = "Since you provoked me, you're ready for the consequences, right?"
10118-260 = "Ugh... But I don't wanna do anything boooring."
10118-270 = "Today's your birthday, right? I already knew!"
10118-280 = "Happy birthday! But I didn't get you a present."
10118-290 = "Huh, me? What do you mean?"
10118-300 = "Hm? Why, why?"
10118-310 = "Birthday present? Really?"
10118-320 = "Pahyahya, thanks! Hikari and I will treasure it!"
10118-330 = "It's already the new year. What fun stuff's gonna happen this year?"
10118-340 = "Sensei, what's your new year's resolution?"
10118-350 = "For some reason, everything feels tingly at this time of year."
10118-360 = "Like...things are soft? Or something? Pahyahyahya!"
10118-370 = "Spending it with Sensei would be so much fun! Let's be together!"
10118-380 = "Ah! I forgot to bring candies!"
10118-390 = "Then I have no choice but to get tricked... What should I do?"
10118-410 = "You like the view?"
10118-420 = "It always looks great around this time of day."
10118-430 = "I like it. The sunset, I mean."
10118-440 = "Well, it does have an autopilot...but I don't use it too often."
10118-450 = "It's boring, you know? I've got to take driving into my own hands."
10118-460 = "Oh...would you like to give it a try, Sensei?"
10118-470 = "Pahyahya! I'm kidding!"
10118-480 = "Come on, Sensei, you need a license to drive a train."
10118-490 = "Like I'd just hand the controls to some total newbie."
10118-2600 = "Whoa, is this for me? Great! I'll wipe out all obstacles in the way with this! Pahyaha!"
