[translation]
10128-10 = "This is! Blue Archive!"
10128-20 = "Another great choice from our— No, I mean Sensei! ...Pardon my late introduction. I'm Wakasa Fuyu, a second-year at Wildhunt Art Academy. Make sure to remember me!"
10128-30 = "Huh, isn't this a really good spot for a business meeting?"
10128-40 = "If I were to install a screen, where would be best...?"
10128-50 = "(Aren't these beans decent? Should I try importing these too?)"
10128-60 = "But...I wonder if Sensei's going to come."
10128-70 = "(I-Is that the Prefectural Council? What should I do? Run away?!)"
10128-80 = "I've been waiting for you, Sensei!"
10128-90 = "Come take a seat, Sensei. Let's talk business."
10128-100 = "Hmm, so this is what office work is like..."
10128-110 = "Oh? Have you finally decided to become the Free Trade Cartel's advisor?"
10128-120 = "What a nice office."
10128-130 = "We can't...use it as the Free Trade Cartel's base, can we?"
10128-140 = "How comfortable..."
10128-150 = "Maybe I can relax here..."
10128-160 = "*yawn* "
10128-170 = "Um, if you keep poking me like that..."
10128-180 = "...I'll stick right next to you, okay?"
10128-190 = "Happy birthday, Sensei!"
10128-200 = "Um, I recorded a birthday video for you."
10128-210 = "W-Would you like to watch it...?"
10128-220 = "Birthday present... Something I want..."
10128-230 = "I don't think there is anything, but..."
10128-240 = "...could I ask for your time today instead?"
10128-250 = "Happy New Year, Sensei."
10128-260 = "This? It's a recording of a bell ringing on New Year's."
10128-270 = "What do you think? Can something like this also be \"art\"?"
10128-280 = "...Shall we take our time and talk about things?"
10128-290 = "I happened to rent a Santa outfit..."
10128-300 = "I-Is your curiosity piqued?"
10128-310 = "Please give me just a moment, Sensei. "
10128-320 = "I managed to get my hands on a delicious pumpkin!"
10128-340 = "We are behind the screens."
10128-350 = "Thus, behind the artwork..."
10128-360 = "A place where only the artist may enter."
10128-370 = "The only way to enter this place...is to get permission from me, the artist. "
10128-380 = "So, right now, in this place..."
10128-390 = "There's only you and...me..."
10128-400 = "Uh no no no no! Th-That's not what I meant...!"
10128-410 = "Anyway! I packed lunch..."
10128-420 = "Um, if you're fine with it..."
10128-430 = "...Would you like to have some?"
10128-2600 = "I'll absolutely repay you for this...! Because that's business! So... Until then, please stay by my side."
