[translation]
10121-10 = "Blue! Archive!"
10121-20 = "Hyakkaryouran Resolution Council, Kadenokouji Yukari... I am making my flashy summer debut! Please look forward to what I can achieve at the beach!"
10121-30 = "No matter the time or place, I shall take on everything with perfect form!"
10121-40 = "Ah! This must be what Sensei spoke about previously!"
10121-50 = "Is this...what they call the \"etiquette of the sea\"?"
10121-60 = "This outfit does invite the cold in... Achoo!"
10121-70 = "Hm, hmm. Super-invincible ship Yukari, sail out! ♪"
10121-80 = "Sensei!! The beach! It's the beach!!"
10121-90 = "After your walk, would you like to watch with me?"
10121-100 = "The islands shattered\nInto a thousand pieces\nThus comes summer sea"
10121-110 = "...Ah, Sensei! I was waiting for you!"
10121-120 = "As expected of you, Sensei! You retain your composure even before the great ocean..."
10121-130 = "...while I am too excited to remain still!"
10121-140 = "A valorous representation of adulthood! I must adopt this attitude as well!"
10121-150 = "Time slips through my fingers so very quickly while at the beach."
10121-160 = "Oh! Could this be the famed \"summertime\"?!"
10121-170 = "Heehee. ♪"
10121-180 = "Hm? I seem to be having fun, even while working?"
10121-190 = "Because I am with you, Sensei!"
10121-200 = "Focus, focus..."
10121-210 = "Aaah! I am so filled with merriment that focus is beyond me!"
10121-220 = "Sensei, what should I do...?!"
10121-230 = "E-Eek?!"
10121-240 = "I wasn't drowsing at all!"
10121-250 = "An elite such as myself would never tire from mere play on the beach!"
10121-260 = "Haaappy birthday! I'll be the first one to congratulate you this year, Sensei!"
10121-270 = "Aah! Could it be that I wasn't the first?"
10121-280 = "Even happier!"
10121-290 = "For that can only mean that many people care deeply for you, Sensei!"
10121-300 = "Ah, Sensei. You remembered my birthday."
10121-310 = "I have received birthday wishes from many people, and I feel very blessed."
10121-320 = "And you were the one I wanted to hear those words from, above anyone else."
10121-330 = "I truly am a greedy person, am I not?"
10121-340 = "It's a Happy New Year!"
10121-350 = "Here is my New Year's greeting!"
10121-360 = "I would love to spend the New Year with you, Sensei."
10121-370 = "However, people partake in debauchery during the festivities! It is a busy time at the Hyakkaryouran!"
10121-380 = "I unfortunately cannot be by your side today..."
10121-390 = "Regardless, let us have strength this year as well!"
10121-400 = "I will continue counting on you, Sensei!"
10121-410 = "Sensei! It's a Merry Christmas!"
10121-420 = "Experiencing the winter sea with you... What a wonderful ambience..."
10121-430 = "Naturally, it would not be ideal to enter these icy waters."
10121-440 = "However, all I require for happiness...is to be with you, just like this."
10121-450 = "Hmm! I learned of a new cultural tradition today!"
10121-460 = "Today is the day people dress up as monsters and receive candy in return!"
10121-470 = "Ack! Upon further reflection, this swimsuit is not a monster costume, is it?!"
10121-490 = "(Sensei! You found me under the sea!)"
10121-500 = "(I never expected to see such beautiful scenery...)"
10121-510 = "(...hidden under the water that I've only seen from afar.)"
10121-520 = "(And for me to be together with Sensei at such a place...)"
10121-530 = "(Aah, aren't I such a lucky girl?)"
10121-540 = "(Um, Sensei? Your face is uh, huh...?)"
10121-550 = "(Did I do something wrong?)"
10121-560 = "(Up? There's nothing up there but the sun...)"
10121-570 = "(What? That's not it?)"
10121-2600 = "This gift is our pledge, Sensei. I shall keep it with me always, and you will be on my mind whenever I gaze upon it. How truly mischievous of you."
