[translation]
10130-10 = "Blue Archive. Fufu."
10130-20 = "Kakehashi Subaru here. If you have any issues, I'll help you to the best of my abilities. Well, in the Arius way."
10130-30 = "A \"cafe\"... An expensive place."
10130-40 = "(This reminds me of...Water Time for some reason.)"
10130-50 = "I wonder...what that is."
10130-60 = "(It was hard for me to visit somewhere like this before.)"
10130-70 = "Working at a cafe... I wonder if they're hiring."
10130-80 = "Welcome, Sensei. I'm Kakehashi Subaru, Student Rep for today."
10130-90 = "I've been waiting for you. Do you have any orders for me?"
10130-100 = "What? \"For starters, just relax...?\""
10130-110 = "\"Snack as much as I want\"?"
10130-120 = "I-I can't! Even if I am the Student Rep!"
10130-130 = "..."
10130-140 = "Then, just a little bit..."
10130-150 = "I'm only saying this to Sensei,"
10130-160 = "but I also don't like the expression Arius \"Satellite School\"."
10130-170 = "Calling it \"satellite school\" makes it feel like it's under the main school... It gives off an impression of being isolated."
10130-180 = "...I'm sorry, I was thinking of everyone back in Arius."
10130-190 = "I need to do my best for them."
10130-200 = "...What? \"Do your best for yourself too\"?"
10130-210 = "Th-Thank...you..."
10130-220 = "Eh? Studying...? I-I'm studying properly."
10130-230 = "*sigh* But why do I have to do something that looks so useless..."
10130-240 = "\"You might not understand it now, but you'll find it useful one day\" ...you say."
10130-250 = "*sigh* Seriously... Yeah, yeah. I got it!"
10130-260 = "Uhm... Whenever I meet Sensei, I get this strange feeling."
10130-270 = "Until now, I haven't met an adult...who would do so much for me."
10130-280 = "Happy birthday, Sensei."
10130-290 = "Th-There's not much I can do for you, and saying happy birthday is the only thing I can offer..."
10130-300 = "What? You want to listen to me playing harmonica? Th-That's..."
10130-310 = "Ugh, okay. I'm only doing this for Sensei, okay?"
10130-320 = "My birthday... Thank you for celebrating my birthday, Sensei."
10130-330 = "In Arius, we treasure our birthdays."
10130-340 = "If we lose that too, then it feels like we're really going to lose something special."
10130-350 = "But still... We'd get scolded, so we couldn't throw grand celebrations."
10130-360 = "It's the day that marks the end of a year, and the start of a new one."
10130-370 = "How strange... Now, I don't think it's a bad thing."
10130-380 = "Happy New Year, Sensei."
10130-390 = "It's Christmas. I know the concept, at least."
10130-400 = "...We'd joke around and say let's be"
10130-410 = "Santa who gifts a bullet rain to Trinity and Gehenna."
10130-420 = "I don't really know what Halloween is..."
10130-430 = "But if you exclude... festival, tricks, and treats from it..."
10130-440 = "It feels somewhat like Arius in the past. ...The time when we had nothing but fear."
10130-460 = "It feels refreshing."
10130-470 = "This is my first time playing for a solo audience..."
10130-480 = "How was it?"
10130-490 = "Was it weird or anything...?"
10130-500 = "That... I can trust your words, right?"
10130-510 = "...Thank you."
10130-520 = "The thing is, I wish I could do more things..."
10130-530 = "But right now, this is about all I can do..."
10130-540 = "What? You'd love to see me practice and perform for you again?"
10130-550 = "Since I bought so many music sheets...?"
10130-560 = "Th-That's..."
10130-570 = "I'll... think about it again later."
10130-2600 = "It still doesn't feel real to me... It feels like everything's going to disappear like a dream when I wake up in the morning... Thank you, Sensei. I'll cherish it."
