[translation]
13009-10 = "블루… 아카이브……"
13009-20 = "꿈인 줄 알았어.\n지금 이 순간이…\n안녕. 선생님. 앞으로 잘 부탁해."
13009-30 = "왠지 잠이 올 것처럼\n편안한 공간이네~"
13009-40 = "꿈을 꾸는 기분이 들어.\n어째설까?"
13009-50 = "우하하하하!\n아… 웃으니까 졸리다."
13009-60 = "우와~ 여기라면\n푹 쉴 수 있을 것 같아~"
13009-70 = "우후후훗.\n새로운 베개가 도착할 거야.\n너무 기대돼."
13009-80 = "아하하하! 바, 방금…! 꿈에…\n선생님이…\n아 진짜 너무 웃겨 아하하"
13009-90 = "아하하하! 아 잘 잤다!\n응? 이런 모습 처음 본다고?"
13009-100 = "하암.\n좋은 아침… 선생님."
13009-110 = "응? 아니라고?"
13009-120 = "뭐 어때~"
13009-130 = "음냐. 선생님… 미안…\n좀만 더 잘게."
13009-140 = "선생님도… 여기 누울래?"
13009-150 = "후암… 어라?\n선생님. 왔어?"
13009-160 = "낮잠 자기 딱 좋은 시간인데…"
13009-170 = "일단 자고 일어나면…\n더 일이 잘되지 않을까?"
13009-180 = "밤에 뭘 하길래 그토록 졸리냐고?"
13009-190 = "후훗. 선생님에게는 알려줄까나~"
13009-200 = "후움…"
13009-210 = "자고 일어나\n가장 먼저 만나는\n사람이 선생님이라…"
13009-220 = "좋네."
13009-230 = "(이대로 시간이 멈췄으면 좋겠어.\n어쩐지, 편안한 느낌이야.)"
13009-240 = "생일 축하해 선생님."
13009-250 = "내가 무릎베개 해줄 테니…\n한숨… 잘래?"
13009-260 = "오늘이…\n내 생일이라고…?"
13009-270 = "기념 삼아 더 자야겠… 좋네."
13009-280 = "새해 복 많이 받아.\n올해는 좀 더 열심히 깨어날게."
13009-290 = "크리스마스는 좋아…"
13009-300 = "백귀야행에서는\n좀 낯선 축제지만"
13009-310 = "많은 사람들이\n행복해 하는…\n성스러운 밤이니까."
13009-320 = "오늘은 잠들기 아까운 날이네."
13009-330 = "거리로 나가자 선생님."
13009-340 = "깨어 있어도…\n꿈꾸는 듯한 기분이 들 거야."
13009-360 = "선생님…\n왔구나…."
13009-370 = "응…. 지금은 수행 중….\n참선하고 있었어…."
13009-380 = "그냥 조는 거 아니냐고…?"
13009-390 = "아니야….\n이것도 어디까지나\n수행의 일환이니까…"
13009-400 = "근처에 이렇게 수행하기\n좋은 장소가 있었을 줄이야…."
13009-410 = "행복해.\n마치 꿈을 꾸는 것\n같은 기분…."
13009-420 = "이 행복도 전부\n선생님 덕분인 걸까…?"
13009-430 = "으으응.\n저… 선생님도 거기서\n그러고 있지 말고."
13009-440 = "나랑 같이…."
13009-450 = "자자…?"
13009-2600 = "이 무기는… 꿈인가…\n그토록 바랬던 일이, 이루어졌네."
