[translation]
13005-20 = "我沒有在生氣，\n所以請不要誤會。老師。\n我經常被別人說我的臉很兇。"
13005-30 = "唉…真擔心。"
13005-40 = "哼嗯，稍微\n有點興趣了。"
13005-50 = "接下來的計畫是…\n算了，就這樣吧。"
13005-60 = "意外的…很可愛？\n哼，\n是無聊的玩笑…對吧。"
13005-70 = "嘛，臉很可怕這件事\n我也很清楚。"
13005-80 = "歡迎回來，老師。\n那麼就開始工作吧。"
13005-90 = "傳來下一個委託了。\n這種感覺，\n總覺得有點熟悉呢。"
13005-100 = "夏萊跟便利屋，\n能感覺到許多相似的地方。"
13005-110 = "有什麼事嗎？\n嘛，如果有問題的話\n我可以幫你解決哦。"
13005-120 = "…我知道。\n我的臉很可怕對吧。\n畢竟我常常被誤會。"
13005-130 = "很可…愛？\n別開玩笑了，老師。"
13005-140 = "我會幫助老師。\n因為這是約定。"
13005-150 = "我會盡全力完成委託哦。"
13005-160 = "因為這是專業人士應有的態度。"
13005-170 = "生日快樂，老師。"
13005-180 = "唔嗯，這種日子裡\n該說什麼才好呢…？"
13005-190 = "生日？那個。"
13005-200 = "不，被便利屋之外\n的人祝福，這還是第一次…"
13005-210 = "謝，謝謝…"
13005-220 = "新年啊…"
13005-230 = "今年，也請多指教。"
13005-240 = "聖誕快樂。\n是情人們的日子啊…"
13005-250 = "哼嗯…"
13005-260 = "街道上充滿了耀眼和\n甜蜜的東西。\n還有不太習慣的氛圍…"
13005-270 = "唔嗯，"
13005-280 = "不過，要不要\n一起到外面走走？"
13005-300 = "你真的沒必要\n跟我來這裡啊，老師。"
13005-310 = "現在，不在嗎…"
13005-320 = "我只是因為下雨，\n才來看看。"
13005-330 = "…應該，沒關係。\n這孩子一個人也能過得很好。"
13005-340 = "不被束縛\n且不會受傷\n固然好…"
13005-350 = "但是，一個人\n很寂寞…"
13005-360 = "…我沒辦法不管。\n就只是這樣。"
13005-370 = "除此之外沒有其他意思。\n懂了嗎，老師？"
13005-2600 = "雖然我對老師的決定沒有異議……\n唉……沒什麼。\n為了不辜負期待，我會努力的。"
