[translation]
13010-10 = "Blue Archive"
13010-20 = "The conditions have been met. You could call it destiny. Let's get down to business."
13010-30 = "Huh? I never realized that a place like this existed."
13010-40 = "We'll go bankrupt at this rate. We must cut down on spending."
13010-50 = "Huh? You need a short break? We have approximately 1,890 seconds to spare."
13010-60 = "I get the feeling today will be a fun day. It would surprise me if it wasn't."
13010-70 = "Sensei. I'll do everything I can to assist you today as well."
13010-80 = "Welcome, Sensei. Shall we begin reflecting on our mistakes?"
13010-90 = "Wait, where are you going?"
13010-100 = "Sensei! I need you to work harder!"
13010-110 = "Sensei. I have approximately 34 tips on how to improve your behavior."
13010-120 = "(...Though one of them isn't quite like the others.)"
13010-130 = "You have been striking me as more teacherly of late."
13010-140 = "Huh? You think it's because of me?!"
13010-150 = "I mean... O-Of course it is!"
13010-160 = "Sensei. Please plan an objective and course of action before you proceed."
13010-170 = "Happy birthday, Sensei."
13010-180 = "This marks...how many years since you were born? Let's see..."
13010-190 = "Huh? You don't want me to know?"
13010-200 = "Today is my birthday. Allow me to choose my own gift."
13010-210 = "Would going out be all right? It doesn't have to be anywhere fancy!"
13010-220 = "Even in math, the first step is crucial. Let's start this year on the right foot as well."
13010-230 = "Christmas Day... These sorts of holidays usually don't interest me."
13010-240 = "But I'm having fun this time because I'm with you."
13010-250 = "Calculating total candy distributed in Kivotos via population density..."
13010-260 = "...and the associated net calorie intake. *mumble*"
13010-280 = "Seriously... If you're an adult, you should know better than to make impulsive purchases."
13010-290 = "You're not like those kids who spend all their pocket money as soon as they get it, are you?"
13010-300 = "On top of that, I'm the only one who helps you sort your receipts like this..."
13010-310 = "If you keep this up, I'm not going to help anymore!"
13010-320 = "Convenience store chicken sandwich two weeks ago...500 yen. New manga volume...450 yen."
13010-330 = "Huh? You spent 20,000 yen at Club Smoochie the other night?"
13010-340 = "S-Sensei! Is this receipt what I think it is?!"
13010-350 = "You're a teacher! You're supposed to set an example for your students! How could you...?"
13010-360 = "Despicable! You're the absolute worst!"
13010-370 = "Huh? Club Smoochie is the name of a gacha game?"
13010-380 = "Geez. I thought you were visiting a..."
13010-390 = "Wait a minute! That doesn't excuse you blowing 20,000 yen in a night!"
13010-400 = "No more impulse purchases! You need to budget!"
13010-2600 = "This is a huge plus!"
