[translation]
13013-10 = "Blue. Archive."
13013-20 = "I'm Akiizumi Momiji from the Red Winter Federal Academy Knowledge Liberation Front. Let's work together to protect all the world's knowledge!"
13013-30 = "...There just may be a rare, undiscovered book somewhere around here..."
13013-40 = "This is a good place to read."
13013-50 = "Maybe I can sneak in a quick nap..."
13013-60 = "I was hoping to find the latest volumes..."
13013-70 = "This place seems like a good place to hide...doesn't it...?"
13013-80 = "Oh, Sensei! Heehee... I've been waiting for you!"
13013-90 = "Oh! Were you looking for me?"
13013-100 = "J-Just one more minute! Let me finish this page...!"
13013-110 = "I like pretty books. Just looking at them makes me happy."
13013-120 = "I like old and battered books too. They show the history the books have endured."
13013-130 = "What do I like more, reading books or collecting them?"
13013-140 = "Hmm... Do I have to choose just one...?"
13013-150 = "I requested a book from the Secretariat, but I was rejected..."
13013-160 = "But I won't give up...!"
13013-170 = "What an unexpected twist... Hmm..."
13013-180 = "Oh, Sensei?!"
13013-190 = "I-I'm sorry! I didn't notice you..."
13013-200 = "An ending that tugs at the heartstrings, a scene where dreams come true... Isn't it amazing?!"
13013-210 = "These things don't happen too often in real life..."
13013-220 = "Happy birthday, Sensei."
13013-230 = "I brought you a book I think you'll like."
13013-240 = "Will you read it with me?"
13013-250 = "Y-You remembered my birthday?!"
13013-260 = "Oh, but I don't have anything to give you in return...!"
13013-270 = "You mean... I don't have to give you anything in return...?"
13013-280 = "If you're sure... This is all so new to me..."
13013-290 = "Happy New Year, Sensei!"
13013-300 = "I-If...it's okay with you, why don't you spend New Years with the Knowledge Liberation Front?"
13013-310 = "Merry Christmas, Sensei!"
13013-320 = "If I could ask Santa for a Christmas gift..."
13013-330 = "It'd be for a first edition book that I've been searching for..."
13013-340 = "I've read about Halloween in a lot of manga."
13013-350 = "I guess that makes sense, since it's a day when all the monsters get together."
13013-370 = "Sensei! I finally found it!"
13013-380 = "No damage to the pages, and it even includes the special edition illustration!"
13013-390 = "An intact limited edition print!"
13013-400 = "Maybe...my whole life"
13013-410 = "has led up to this very moment. To finding this book."
13013-420 = "Heeheehee... This is all thanks to you coming with me, Sensei."
13013-430 = "As long as I'm with you...good things tend to happen."
13013-440 = "So... Um... Sensei."
13013-450 = "If it's all right with you... Um, even if it's not every day..."
13013-460 = "Even if it's just every now and again..."
13013-470 = "Please come visit the Knowledge Liberation Front..."
13013-2600 = "For you, Sensei, I'll use it. What should I make quiet down first...?"
