[translation]
13013-10 = "蔚藍，檔案"
13013-20 = "我是赤冬聯邦學園，知識解放戰線的秋泉，紅葉……\n為了守護全世界的知識……一起並肩作戰吧！"
13013-30 = "……也許這裡的某處，\n隱藏著從未面世的\n稀有書也說不定……"
13013-40 = "這裡，是個很\n適合讀書的地方呢。"
13013-50 = "可以稍微，\n睡一下嗎……"
13013-60 = "新刊……\n真想買……"
13013-70 = "這個地方……\n好像很適合窩著，\n又好像不太適合……？"
13013-80 = "啊，老師！\n耶嘿嘿……\n恭候多時了！"
13013-90 = "啊！老師你找我嗎？"
13013-100 = "再，再一分鐘就好！\n請讓我讀完這頁……！"
13013-110 = "我喜歡精美的書。\n光是看著就覺得幸福。"
13013-120 = "我也喜歡有\n翻閱痕跡的書哦，\n因為那代表\n書本經歷的歷史。"
13013-130 = "讀書跟集書，\n哪個比較喜歡，是嗎……？"
13013-140 = "嗚嗚……那個，\n一定要選嗎……？"
13013-150 = "向事務局提出的藏書申請\n又被駁回了……"
13013-160 = "不過，\n我不會放棄的……！"
13013-170 = "在這裡出現\n這樣的展開……？\n呣呣……"
13013-180 = "哈，老師！？"
13013-190 = "不，不好意思！\n我沒有注意到……"
13013-200 = "隨著感人的發展\n實現夢想的場景……\n不覺得很棒嗎！？"
13013-210 = "雖然在現實中，\n相當困難就是了……"
13013-220 = "祝你生日快樂，老師。"
13013-230 = "我為了老師……\n帶了推薦的書來。"
13013-240 = "要不要一起讀呢？"
13013-250 = "我，我的生日，\n老師你記得嗎！？"
13013-260 = "怎，怎麼辦！？\n我完全，沒有可以\n報答老師的東西……！"
13013-270 = "不，不對嗎？\n我只要收下就行了……？"
13013-280 = "或，或許是這樣沒錯，\n但那個，這種事，\n我是第一次遇到……"
13013-290 = "新年快樂，老師。"
13013-300 = "那個……可以的話，\n新年要不要和我們\n知識解放戰線一起過呢？"
13013-310 = "聖誕快樂，老師！"
13013-320 = "如果能向聖誕老人\n許願聖誕禮物的話……"
13013-330 = "希望能收到一直在找的\n那本書的初版……"
13013-340 = "萬聖節時常會成為\n漫畫的題材對吧。"
13013-350 = "果然幽靈聚集的日子，\n很容易被當成創作題材嗎？"
13013-370 = "老師！我終於找到了！"
13013-380 = "是沒有頁面受損，\n特典插畫也有\n隨附在內的，"
13013-390 = "限定版！"
13013-400 = "也許我……就是\n為了和這一本書相遇，"
13013-410 = "才會被引導到這裡也說不定。"
13013-420 = "耶嘿嘿……這也是，\n多虧老師在一旁\n守望著我呢。"
13013-430 = "只要和老師在一起……\n就會神奇地發生好事。"
13013-440 = "所以……\n那個……老師。"
13013-450 = "如果可以的話……那個，\n我不會說，每天都要……"
13013-460 = "偶爾，就可以了……"
13013-470 = "我們知識解放戰線，\n請你多來拜訪哦……"
13013-2600 = "我會為了老師……使用它的。\n……那麼，要先讓什麼安靜下來呢。"
