[translation]
13011-10 = "Blue Archive!"
13011-20 = "Wanna hear a fun story? Let me tell you!"
13011-30 = "Games! Games! I just want to play games!"
13011-40 = "Huh? I used to watch this series when I was young."
13011-50 = "Hmm... We don't have enough for everyone's snacks. Should I get a part-time job?"
13011-60 = "Oh! I just thought of a wonderful story idea!"
13011-70 = "Great! All clear!"
13011-80 = "Welcome, Sensei! Let's start a mission!"
13011-90 = "I'm all ready. Let's go! We've got quests to clear!"
13011-100 = "There's a difference between pro gamers and game lovers."
13011-110 = "Which one are you?"
13011-120 = "Oh! That new game is coming out today."
13011-130 = "I was supposed to go on a raid today! But I'm on the roster instead!"
13011-140 = "...I guess this isn't so bad, either."
13011-150 = "The mission can wait, Sensei. Let's play a game first!"
13011-160 = "You're so lucky, Sensei... You can buy any game, whenever you want."
13011-170 = "Happy birthday, Sensei! Let's go chow down with everyone from the club!"
13011-180 = "Sensei! Today's me and Midori's birthday!"
13011-190 = "Buy us a two-player game that we can play together!"
13011-200 = "Happy New Year! Let's play fun games this year!"
13011-210 = "Christmas... *sigh*"
13011-220 = "If you dress up in red and gift me a console, this'd be the best Christmas ever!"
13011-230 = "Wow! It's Halloween! I'm so excited, Sensei! C'mon, get me some candy!"
13011-250 = "Look, Sensei! I filled out this stamp card!"
13011-260 = "Now this quest is cleared! Yay!"
13011-270 = "I wasn't sure how it was going to go at first..."
13011-280 = "But you and I...we make a great team, Sensei!"
13011-290 = "Wooow! Sensei..."
13011-300 = "You're so sweaty! Are you okay?"
13011-310 = "Hahaha! I'm glad you said you're okay. I had lots of fun today thanks to you, Sensei!"
13011-320 = "If there's ever another event like this..."
13011-330 = "...we should go together again, Sensei!"
13011-2600 = "Th-This is exclusive equipment! I am now a proud, OP schoolgirl!"
