[translation]
16008-10 = "蔚藍……檔案……"
16008-20 = "咦，我？是不是找錯人了？\n像我這種生活安全局的懶惰蟲，\n會有什麼事需要我……？"
16008-30 = "哦，這個沙發\n還挺不錯的嘛？"
16008-40 = "真想在生活安全局\n的辦公室裡也擺一個。"
16008-50 = "我什麼都不想做了……"
16008-60 = "啊……感覺好像\n聽到了警報聲……"
16008-70 = "怎麼會，上面的\n大人物應該不會\n來這裡才對……"
16008-80 = "喔，是老師啊。"
16008-90 = "辛苦了，老師。"
16008-100 = "雖然我什麼\n都沒做就是了。"
16008-110 = "呼啊……\n好睏……"
16008-120 = "為什麼桐乃\n要那麼自討苦吃呢……"
16008-130 = "警察閒著沒事做\n就代表街上很和平……"
16008-140 = "反過來說，為了和平\n就該越懶越好！"
16008-150 = "歐菲香甜甜圈……\n雖然名字有點微妙，"
16008-160 = "但味道真是棒極了。"
16008-170 = "中間沒有洞的甜甜圈\n不能叫做甜甜圈……"
16008-180 = "只是個炸麵包而已吧……！"
16008-190 = "……嗯？\n今天是老師的生日？"
16008-200 = "啊～我沒有準備禮物耶……"
16008-210 = "……沒辦法了，\n今天老師就算做了什麼壞事，\n我都會特意當作沒看到。"
16008-220 = "明明是生日還要去學校，\n這不是很奇怪嗎？"
16008-230 = "想要祝福的話，\n我倒希望至少今天\n讓我休息……"
16008-240 = "今天午餐，\n我特別準備了……"
16008-250 = "……咦，御節料理？\n不，是「MasterDonut」\n的餐盒唷？"
16008-260 = "雖然我對聖誕節本身\n沒什麼興趣……"
16008-270 = "不過連假結束之後的\n特價蛋糕\n我絕對是敞開雙臂歡迎！"
16008-280 = "聽說市區裡有一群\n將怪物面具反著戴的蠢蛋\n在到處橫行霸道？"
16008-290 = "啊……來，這給你。\n打這通電話就能接到警備局，\n請他們處理吧。"
16008-310 = "啊啊……\n簡直是天堂……"
16008-320 = "坐在暖呼呼的引擎蓋上\n享用甜甜圈和咖啡……"
16008-330 = "哎呀，\n埋伏勤務萬歲！"
16008-340 = "啊，老師。\n要好好警戒\n四周才行哦。"
16008-350 = "在我們說話的時候，\n犯人也有可能會經過的。"
16008-360 = "（啊姆。嚼嚼嚼嚼……）"
16008-370 = "果然，\n搭配咖啡一起吃的話，\n還是歐菲香最棒了……\n呵呵。"
16008-380 = "嗯？怎麼了，老師？\n……要吃甜甜圈嗎？"
16008-2600 = "女武神警察學園的制式槍枝\n非常堅固耐用。\n但命中率差強人意就是了……"
