[translation]
16006-10 = "블루 아카이브!"
16006-20 = "여름! 여름이야. 선생님!\n이번 여름엔 나랑 같이,\n맛있는 거 잔뜩 먹으러 가자!"
16006-30 = "여름의 풍물시라면,\n빙수… 소면…\n은어 소금구이…\n츄릅…… 핫?!"
16006-40 = "다음번에 선생님이랑\n바다에 가면……\n타코야키 100개 먹기다앗…!"
16006-50 = "여름이라면 역시……\n야키소바, 자루소바,\n나가시소멘!"
16006-60 = "여기는 시원해서\n좋다아~"
16006-70 = "수영복 준비 오케이.\n아이스박스 채우기 오케이.\n여름 준비는 완벽해!"
16006-80 = "앗, 선생님이다!\n바다 가자!\n바다! 선생님!"
16006-90 = "일해야 한다고?\n그럼 끝날 때까지 기다릴래!"
16006-100 = "흥, 흐흥~\n어서 와, 선생님."
16006-110 = "난 끝났으니까.\n이제 선생님만 준비하면 돼."
16006-120 = "응? 무슨 소리냐고?\n당연히 바다에 갈 준비지!"
16006-130 = "여름하면\n당연히 바다의 집!\n이건 가볼 수밖에 없어!\n선생님!"
16006-140 = "빨강, 노랑, 초록…\n그리고 파랑…"
16006-150 = "선생님은 이 중에서\n어느게 제일 좋아…?"
16006-160 = "……응?\n빙수 시럽 이야기라구?"
16006-170 = "선생님, 바다에서\n수영을 하다보면\n금방 배가 고파지잖아?"
16006-180 = "그래서 내가 해결책을\n생각해 봤는데……"
16006-190 = "수영에도 쓸 수 있고,\n배고프면 그대로 먹을 수도 있는\n튜브를 사면 돼!"
16006-200 = "어때, 굉장한 생각이지?!\n엣-헴!"
16006-210 = "어?\n그런 튜브는 없어?\n…어째서?"
16006-220 = "생일 축하해! 선생님!"
16006-230 = "그럼 기념으로!\n오늘은 같이 샬레에서\n물장구를 치자!"
16006-240 = "짜잔~! 오늘은\n내 생일이야. 선생님!\n그러니까 자,\n수영하러 가자!"
16006-250 = "여름은 아직 조금 멀었지만.\n선생님이랑 같이 있는데\n어떻게 기다려~!"
16006-260 = "새해 복 많이 받아!\n선생님!"
16006-270 = "설날의 떡국도 물론 좋지만\n올해도 선생님이랑 같이,\n여름의 별미를 먹을 날이\n기대되네! 에헤헷!"
16006-280 = "메리 크리스마스~!\n크리스마스에도\n수영복이라니,\n춥지 않냐고?"
16006-290 = "괜찮아! 방금 막 따끈따끈한\n우동을 먹었으니까!"
16006-300 = "할로윈은 별나게\n꾸며입고 사탕을\n받는 날……"
16006-310 = "혹시… 지금의 나라면\n가능할지도?!"
16006-330 = "선, 선생님. 도와줘어……"
16006-340 = "으으, 느낌이 이상해애애……\n축축하고 미끈미끈해서,\n우에엥……!"
16006-350 = "저리 가아~!\n난 먹는 게 아니라구우~!"
16006-360 = "아직 못 먹어본\n음식도 많단 말이야아~!"
16006-370 = "히읏?!\n우으읏, 이대로\n당하고 있을 수만은……!"
16006-380 = "헉!\n이대로 문어에게 먹힐 바에는\n차라리 그전에……!"
16006-390 = "내가 먼저\n먹어버리면 될지도-?!"
16006-2600 = "여름 전용 장비?!\n날 위해 준비해준 거야?!\n우와아~! 기뻐라~!\n고마워-!"
