[translation]
16017-10 = "蔚，蔚藍檔案……這樣就行了嗎……？"
16017-20 = "我，我是高地人鐵道學園……\n內，內海青葉……\n不多指教，也沒關係的……"
16017-30 = "大，大家都帶著笑容……\n人生，快快樂樂的\n真不錯呢……"
16017-40 = "這裡……真寬廣呢……\n要是我們的值班室\n也能有這樣的空間……"
16017-50 = "我，我可以\n待在這裡嗎……？"
16017-60 = "（總覺得好像染上了\n油臭味……真是糟透了）"
16017-70 = "冷靜下來深呼吸……\n嘶，呼……"
16017-80 = "歡，歡迎回來，的說。\n老師。"
16017-90 = "有，有什麼工作嗎？"
16017-100 = "這間辦公室……\n感覺有股能讓人\n放鬆的味道……"
16017-110 = "啊，哈……！\n我，我只是在自言\n自語而已……！？"
16017-120 = "如果有能幫忙的事，\n請一定要跟我說……"
16017-130 = "有，有什麼希望\n我維修的東西嗎……？"
16017-140 = "修理的話，\n我是可以幫忙……"
16017-150 = "那個……\n請問放在茶水間的點心……"
16017-160 = "我，我可以吃嗎……？"
16017-170 = "在高地人是吃不到\n這，這種點心的……"
16017-180 = "嘿嘿……我要開動了！"
16017-190 = "那個……雖然文書之類的，\n我有點……但是……"
16017-200 = "只是簡單計算的話，\n應該……還能應付……"
16017-210 = "那，那個……"
16017-220 = "我從值班室帶了\n泡麵過來……"
16017-230 = "老，老師要一起……\n吃嗎……？"
16017-240 = "那個……今天，\n聽說是您的生日……"
16017-250 = "能，能送給您的\n就只有這個了……\n那個……"
16017-260 = "板手，請您收下！"
16017-270 = "祝您生日快樂……！"
16017-280 = "什麼！？\n咦！那個！"
16017-290 = "雖然是我的生日……\n沒錯……！"
16017-300 = "唔，唔唔……"
16017-310 = "要，要說沒有期待\n是騙人的，可是！"
16017-320 = "謝謝您……\n我真的……非常開心。"
16017-330 = "希望今年會是美好的一年……"
16017-340 = "只有一點點的話，\n期待一下也沒關係吧。"
16017-350 = "聖誕節……禮物……"
16017-360 = "不……那實在\n奢望過頭了……"
16017-370 = "抱有期待的話，\n之後只會失望而已……"
16017-380 = "還是別多想了吧……"
16017-390 = "變，變裝有點……\n不太……"
16017-400 = "那種事情，\n我覺得讓適合的人\n去做才對……"
16017-420 = "請，請不要過來這邊……\n的說……！"
16017-430 = "衣，衣服上……！"
16017-440 = "沾到了油的味道……\n不，不太好聞……"
16017-450 = "我，我馬上脫掉……\n請，請在那邊……\n稍等一下……！"
16017-460 = "咦？那是……\n什麼意思……？"
16017-470 = "啊……唔……"
16017-480 = "……啊啊啊！？\n那，那個！！"
16017-490 = "嗚，嗚哇啊啊啊啊！！"
16017-2600 = "如，如果有礙眼的人……\n只，只要用這個\n射穿他就行了吧……？"
