[translation]
16010-10 = "브, 블루 아카이브…!"
16010-20 = "선생님… 어, 어때…?\n치어리더 의상을 만들어본 건 처음이긴 한데…\n그렇게 나쁘지는… 않지?"
16010-30 = "응원이 필요한\n사람… 있어?"
16010-40 = "이런 떠들썩한\n분위기…\n나쁘진 않아."
16010-50 = "힘드네…\n조금 목이 탈지도."
16010-60 = "저 물건은…\n조금 개조해볼까?"
16010-70 = "여기쯤이 좋을까?\n아니면… 여기?"
16010-80 = "어서 와. 선생님.\n응원할래?\n개조할래?\n그것도 아니면…"
16010-90 = "기운내서 일하자, 선생님.\n만약 의욕이 떨어지면…\n언제든 얘기해."
16010-100 = "선생님…\n어쩐지 기운 없지 않아?\n응원 필요해? …필요하지?"
16010-110 = "선생님에게\n도움이 되고 싶으니까.\n기술 뿐만 아니라…\n여러가지 면에서."
16010-120 = "여기는 운동장이 아니니까…\n이 복장은 조금, 그게…"
16010-130 = "뭔가 이상하네."
16010-140 = "평소라면 이보다\n더 노출이 심한 복장도\n신경쓰지 않았을텐데…"
16010-150 = "(혹시 나…\n선생님을 의식하고\n있는 걸까.)"
16010-160 = "플레이, 플레이! 선생님!\n언제나, 고마워!\n선생님! 감사해!"
16010-170 = "…오늘은 특별한 날이니까.\n조금 의욕을 내봤어."
16010-180 = "응, 생일 축하해.\n선생님."
16010-190 = "오늘은 내 생일이야,\n선생님."
16010-200 = "그러니까 오늘은…\n선생님에게 응원, 받고 싶어."
16010-210 = "새해 복 많이 받아, 선생님.\n올해도 선생님을 위해\n열심히 응원할게."
16010-220 = "벌써 크리스마스네.\n새로운 디자인의 응원복을\n준비해야 할지도."
16010-230 = "아, 오늘 할로윈이구나.\n어쩐지… 밖이 좀\n요란스럽다고 생각했어."
16010-240 = "응…? 나?\n…이, 이 복장은\n그런 거랑 다른 거야…"
16010-260 = "플레이, 플레이…\n선생님!"
16010-270 = "싸워라, 이겨라.\n선생님…"
16010-280 = "응? 무어랑 싸워서\n이기라고 응원하는 거냐고?"
16010-290 = "글쎄… 선생님을\n괴롭히는 업무라든가.\n선생님으로서의\n책무라든가…"
16010-300 = "마음에 걸린다면 응원 문구를\n조금 바꿔볼까…?"
16010-310 = "힘내라, 힘내라…\n선생님!"
16010-320 = "(…뭔가 이상하네, 선생님이\n의욕을 내기는커녕, 오히려\n집중하지 못하는 것처럼 보여.)"
16010-330 = "(…어쩌면 지금의 나는\n꽤 터무니없는 짓을\n저지르고 있는 걸지도…)"
16010-2600 = "고마워, 선생님.\n그리고 앞으로 계속 보여줄게.\n…지금까지 보지 못했던\n새로운 광경을."
