[translation]
16013-10 = "B...Blue Archive!"
16013-20 = "ฉันมาเพื่อจับตาดูคุณครูโดยเฉพาะ!\nเรื่องลามกเป็นสิ่งต้องห้าม! ห้ามเด็ดขาด!\nฉันจะไม่ยกโทษให้อย่างเด็ดขาด...!"
16013-30 = "ฮือ...\nคนเยอะจัง..."
16013-40 = "นะ...นั่นมัน...!?"
16013-50 = "ระ...หรือว่ามีแค่ฉันที่\nแต่งตัวแบบนี้กันนะ...?!"
16013-60 = "คุณครู...อยู่ไหนน่ะ..."
16013-70 = "ฉะ...ฉันไม่ได้ใส่ชุดนี้\nเพราะชอบหรอกนะ!"
16013-80 = "กำลังรออยู่เลย คุณครู!\nวันนี้จะทำอะไรล่ะ?"
16013-90 = "มาสายนะ คุณครู!\nจริงๆ เลย... มัวทำอะไรอยู่น่ะ!?"
16013-100 = "เอ๋? ชะ...ชุดนี้...?"
16013-110 = "ทะ...ทำไมถึง\nมาถามเรื่องพวกนี้กันเล่า?\nห้ามคิดลามกนะ! เดี๋ยวจะโดน!"
16013-120 = "ทำงานเอกสาร?\nระ...เรื่องนั้นฉันทำไม่เป็นหรอก"
16013-130 = "อะ...เอาเป็นว่า\nฉันจะคอยดูแลที่นี่ให้เอง!"
16013-140 = "คุณครู...\nทำงานแบบนี้ตลอดเลยสินะ...\nดูน่าเหนื่อยจัง..."
16013-150 = "อยู่ที่นี่ต่อแบบนี้ ไม่เบื่อรึไง?\nไม่อยากไปทะเล หรือไปภูเขา\nบ้างเลยเหรอ?"
16013-160 = "ฮิฮิ คุณครู\nมีฉันอยู่ด้วยเลยอุ่นใจใช่มั้ย?"
16013-170 = "วันนี้วันเกิดคุณครูใช่มั้ย?\nมีของที่อยากได้หรือเปล่า?\nบอกมาได้ทุกอย่างเลย!"
16013-180 = "อ๊ะ... แต่เรื่องลามกไม่ได้นะ!"
16013-190 = "อ่า... วันเกิดฉัน...\nคุณครูจำได้ด้วยสินะ..."
16013-200 = "ฮุฮุ ขอบใจนะ"
16013-210 = "ขอให้มีความสุขในวันปีใหม่ค่ะ คุณครู!\nปีนี้ก็อยากไปทะเลอีกจัง... ฮุฮุ"
16013-220 = "คริสต์มาสแล้วสินะ..."
16013-230 = "เอ๋? ให้ออกไปข้างนอกเหรอ?\nด้วยชุดแบบนี้เนี่ยนะ!?"
16013-240 = "...คะ...คิดอะไรอยู่เนี่ย!\nโรคจิต! ต้องโดนลงโทษ!!"
16013-250 = "ชุดวันฮาโลวีน!?\nชุดว่ายน้ำเนี่ยนะ...!?"
16013-260 = "ไปคิดอีท่าไหนมันถึงกลาย\nเป็นแบบนั้นไปได้เนี่ย!?"
16013-280 = "...นี่..."
16013-290 = "...คุณครู...?\nจะนั่งอยู่แบบนี้จนถึงเมื่อไรน่ะ...?\nไม่เห็นเข้าใจเลยว่าทำไปทำไม..."
16013-300 = "งั้นเหรอ... อืม.."
16013-310 = "ถ้างั้นฉันกลับดีมั้ยนะ..."
16013-320 = "...เฮือก!!"
16013-330 = "(ไม่สิ ไม่ๆ ไม่ได้สิ!\nฉันคิดอะไรอยู่เนี่ย!)"
16013-340 = "(อันตรายจริงๆ! เกือบถูกคุณครู\nหลอกซะแล้ว)"
16013-350 = "(ดันเผลอไม่ระวังตัวไปซะแล้ว...\nไม่ได้... ไม่ได้เด็ดขาด!)"
16013-360 = "คิดจะทำให้ฉันประมาทงั้นเหรอ\nไม่ได้ผลหรอกน่า!"
16013-370 = "...ฮึ่ม!"
16013-2600 = "นะ...นี่มัน อืม... มะ...ไม่ได้สิ\nคงต้องพูดให้ถูกต้องแล้วละ...\nขะ...ขอบคุณนะ คุณครู! จากนี้ไป\nฉันก็จะพยายามให้มากขึ้น!\nคะ...แค่นี้ก็พอแล้วใช่มั้ย?\nฉันเองก็พูดคำว่าขอบคุณเป็น\nเหมือนกันแหละน่า!"
