[translation]
20008-10 = "Blue Archive"
20008-20 = "เจ้าหน้าที่อาวุโส สังกัดคณะกรรมการวินัยเกเฮนน่า อาโกะค่ะ\nจากนี้ไปก็ขอความร่วมมือด้วยนะคะ"
20008-30 = "อืม สิ่งอำนวยความสะดวกที่นี่\nก็ไม่แย่เท่าไรนะคะ"
20008-40 = "กำหนดการร่วมงาน\nกับทางชาเล่ต์ครั้งถัดไป..."
20008-50 = "ท่านประธาน\nจะได้ทานข้าวรึยังนะ?"
20008-60 = "ทุกอย่างดูสงบสุขมากเลยค่ะ\nถือว่าเป็นเรื่องดีนะคะ... "
20008-70 = "ยึดที่นี่เลยดีมั้ยนะ\nแต่ถ้าทำแบบนั้น\nท่านประธานจะลำบากสินะ\nงั้นก็ยกเลิกดีกว่าค่ะ"
20008-80 = "อ๊ะ คุณครูมาแล้วเหรอคะ\nถ้างั้นมาเริ่มงานกันเลยมั้ยคะ?"
20008-90 = "วันนี้ห้ามกลับบ้าน\nจนกว่าจะทำเสร็จนะคะ"
20008-100 = "อ๊ะ คุณครู...\nทำเสร็จเร็วกว่าที่คิดก็ได้นี่คะ\nถือว่าเป็นคำชมแล้วกันนะคะ"
20008-110 = "คุณครู... อู้งานอยู่เหรอคะ?"
20008-120 = "เฮ้อ ถ้าคุณครูอยู่ดึก ฉันก็จะ\nเลิกงานช้าไปด้วยนะคะ"
20008-130 = "งานดูไม่ค่อยคืบหน้าเลยนะคะ..."
20008-140 = "เฮ้อ... ช่วยไม่ได้นะคะ"
20008-150 = "ถ้างั้นฉันจะช่วยเองค่ะ"
20008-160 = "ตั้งแต่นี้ไปเวลาพักทานข้าว\nเวลาพักเบรก และพักเข้าห้องน้ำ\nฉันจะจัดตารางให้เองค่ะ"
20008-170 = "ไม่มีปัญหาใช่มั้ยคะ?"
20008-180 = "เอ๊ะ? พอจะทำก็ทำได้นี่คะ"
20008-190 = "เดี๋ยวนะคะคุณครู?\nหรือที่ผ่านมา...."
20008-200 = "ที่ผ่านมาแค่ทำตัว\nเอื่อยเฉื่อยเท่านั้นเหรอคะ...!?"
20008-210 = "ถ้ารู้สึกเหนื่อยก็บอกฉันได้นะคะ\nการดูแลเรื่องคุณครูเป็นหน้าที่ของฉันค่ะ"
20008-220 = "สุขสันต์วันเกิดค่ะ คุณครู\nฮุฮุ ฉันจัดตารางไว้ตั้งแต่อาทิตย์ก่อน\nเพื่อวันเกิดของคุณครูแล้วค่ะ"
20008-230 = "ฉันสัญญาว่าจะเป็นหนึ่งวัน\nที่สมบูรณ์แบบไม่เสียเปล่า\nแม้สักนาทีเลยค่ะ"
20008-240 = "วันเกิดฉันเหรอคะ?"
20008-250 = "เฮ้อ คุณครูมีตารางงาน\nที่สำคัญกว่าอยู่..."
20008-260 = "คะ? ไม่มีอะไรสำคัญ\nไปกว่าวันเกิดงั้นเหรอคะ?"
20008-270 = "ทำแบบนี้อีกแล้วนะคะ\nแต่ก็... ขอบคุณนะคะ"
20008-280 = "สวัสดีปีใหม่ค่ะ คุณครู"
20008-290 = "ถึงจะเป็นปีใหม่แต่ก็ยัง\nต้องทำงานเหมือนเดิมค่ะ\nฮุฮุ ฉันจะคอยอยู่ช่วยเองค่ะ"
20008-300 = "คุณครูอยากใช้เวลาใน\nคืนวันคริสต์มาสกับฉันมั้ยคะ?"
20008-310 = "หมายความว่าจนกว่า\nงานที่ค้างอยู่จะเสร็จ\nห้ามเลิกงานเด็ดขาดค่ะ"
20008-320 = "วันฮาโลวีนเป็น\nวันที่มอบขนมให้กันค่ะ"
20008-330 = "ในการทำงาน...\nการบริโภคน้ำตาลเป็นสิ่งจำเป็น\nคุณครูว่ายังไงคะ?"
20008-350 = "ฮือ.... ไม่อยากเชื่อเลย\nว่าจะเป็นแบบนี้..."
20008-360 = "ความอัปยศในตอนนี้\nฉันจะไม่มีวันลืมเลยค่ะ...!"
20008-370 = "อ๊ะ เดี๋ยวก่อนสิคะ?! แบบนี้มัน\nไม่เหมือนกับที่คุยกันไว้เลยนี่คะ!?"
20008-380 = "ปะ... ไปเดินเล่นเหรอคะ?\nตอนนี้เนี่ยนะ จะไปแบบนี้\nเลยเหรอคะ?"
20008-390 = "มันก็แน่อยู่แล้ว..."
20008-400 = "ขอโทษค่ะ...\nฉันดันเผลอเล่นสนุก\nตามอารมณ์เยอะไปหน่อยค่ะ"
20008-410 = "คะ... คือว่า... จะให้ฉันอยู่ท่านี้\nไปอีกนาน... แค่ไหนกันคะ?"
20008-2600 = "วิธีการพูดที่กล้าหาญแบบนี้...\nฮุฮุ ดีล่ะ ฉันก็จะแสดงให้ดูว่า\nนักเรียนตรงหน้าคุณครู\nมีความสามารถมากแค่ไหน"
