[translation]
20003-20 = "I'm Mashiro, first-year from the Justice Task Force. I may be inexperienced, but I'm here to help however I can."
20003-30 = "I doubt Tsurugi would like these kinds of decorations..."
20003-40 = "This furniture is fluffy like Hasumi's wings..."
20003-50 = "Tranquil like water..."
20003-60 = "Is Tsurugi's neck okay...?"
20003-70 = "I don't mind coming here every once in a while."
20003-80 = "How pretty... Heehee."
20003-90 = "Welcome, Sensei. Let's strive for justice again today."
20003-100 = "I've been awaiting your orders."
20003-110 = "Oh, are we mobilizing?"
20003-120 = "You called for me, Sensei?"
20003-130 = "The goal of the Justice Task Force..."
20003-140 = "...is to vanquish evil and establish justice."
20003-150 = "Justice—in this academy."
20003-160 = "I gave my word."
20003-170 = "I would endure brutal training and mind-numbing trials..."
20003-180 = "...so that I could protect justice."
20003-190 = "But the time I spent with my upperclassmen was so enjoyable..."
20003-200 = "Forgive me in advance. Everyone strays from justice from time to time."
20003-210 = "But I'm only saying this just in case..."
20003-220 = "What you're touching right now is not the operational console."
20003-230 = "Happy birthday, Sensei."
20003-240 = "I hope you feel righteous justice on your birthday."
20003-250 = "I see. So today is my birthday."
20003-260 = "It must have slipped my mind."
20003-270 = "Thank you for telling me."
20003-280 = "It's a new year. This year..."
20003-290 = "I will see injustice stopped once and for all."
20003-300 = "This is a holy day for Trinity."
20003-310 = "I wonder what sordid activities those Gehenna scum are up to on a day like this..."
20003-320 = "The festive day to celebrate all of Trinity's saints has come."
20003-330 = "Pumpkin ghost...? Did you have a nightmare?"
20003-350 = "Whew... It's unseasonably hot today."
20003-360 = "I can handle heat like this if that's what it takes to get the perfect shot."
20003-370 = "But I do hope...that I don't get too sweaty."
20003-380 = "I envy the other students' white uniforms on hot summer days like this."
20003-390 = "Sensei. You're staring at me."
20003-400 = "Shouldn't you keep your eyes out for the target?"
20003-2600 = "This is what you call true justice."
