[translation]
20000-20 = "이때쯤일 거라 예측하고, 기다리고 있었어.\n선생님이 내 이름을 불러주는… 바로 이 순간을."
20000-30 = "시간과 예산을 더 주신다면…?\n자신의 능력 부족에 대한 변명일 뿐이지."
20000-40 = "주어진 시간과 예산 내에서\n최선의 결과를 뽑는 것.\n그것이 마이스터라는 거야."
20000-50 = "여기에 선생님 동상을 세워보면 어떨까?\n팔다리의 관절이 움직이게 만들 수 있어."
20000-60 = "흐음… 내부의 몇 가지 항목에서\n수리와 개선 사항을 발견했…\n에? 수리하면 안 되는 거야?"
20000-70 = "원한다면 깜짝 놀랄만한 함정이라도\n설치해줄 수 있는데.\n응? 안된다고?"
20000-80 = "안녕 선생님.\n오늘의 임무목록을\n책상에 올려뒀어.\n확인해주면 좋겠어."
20000-90 = "흐음… 현재의 선생님의\n임무 진행은 다소 비효율적인\n상태라 생각해."
20000-100 = "더 나은 방향을 찾아볼게."
20000-110 = "이렇게 선생님과 있으니까…\n후후… 재미있어."
20000-120 = "선생님. 어때.\n나의 장비들……\n도움이 되었을까나?"
20000-130 = "유용한 것을 만드는 거?\n즐겁냐고?\n그렇기도 하지만…"
20000-140 = "이건 내 취미가 아니라,\n삶이야."
20000-150 = "정비는 좋아.\n죽어있던 기계의 심장이\n다시 뛸 때"
20000-160 = "무언가가 이루어진,\n그 감각을 사랑해."
20000-170 = "(선생님의 미소가…\n내게는 최고의 모티베이션이야.)"
20000-180 = "생일 축하해 선생님.\n선생님이 태어나서,\n그리고 우리에게 와줘서.\n…기뻐."
20000-190 = "선물로 받고 싶은거?\n없어."
20000-200 = "…이미, 잔뜩 받고 있으니까."
20000-210 = "새해 복 많이 받길 바라.\n올해는 보다 개선되고\n향상된 나를 보여줄게…"
20000-220 = "산타클로스가 단 하룻밤만에\n키보토스의 아이들에게\n선물을 주기 위해선…"
20000-230 = "그의 루돌프는 최소\n마하 4 이상의 속도를 내야 할 거야."
20000-240 = "할로윈 데이라…\n비과학적인 날이지만,\n어쩐지 설레는, 신기한 날이네."
20000-260 = "고마워 선생님.\n이 풍경은,\n선생님 덕분에 이루어졌어."
20000-270 = "아름답지?\n시간 맞춰 다행이야."
20000-280 = "응? 왜 이렇게까지…\n노력했냐고?"
20000-290 = "밀레니엄의 여학생들이, 안전하게.\n빛나는 밤거리를\n걷게 해주고 싶었으니까."
20000-300 = "내가 할 수 있는 건…\n이런 것밖에 없으니까."
20000-310 = "그리고 내게도…\n이런 순간은 이미 '선물' 그 이상이야."
20000-320 = "어때, 선생님?\n아직 시간이 있으니까…"
20000-330 = "좀 더…\n함께 있어줄래?"
20000-2600 = "더 많은 것을 만들고 싶어.\n그래서…… 좀 더 선생님의 힘이 되길 바라."
