[translation]
20016-10 = "Blue... Archive~"
20016-20 = "เฮ้อ ทำไมถึงกลายเป็นแบบนี้ได้คะ?\nแต่ในเมื่อเป็นแบบนี้แล้ว ก็คงต้องทำสินะคะ"
20016-30 = "สถานที่ที่จะอ่านหนังสือ\nได้อย่างเงียบๆ..."
20016-40 = "อา... ขี้เกียจจัง..."
20016-50 = "พวกเรื่องวุ่นวายต่างๆ\nมันค่อนข้าง..."
20016-60 = "สถานที่ที่จะซ่อนตัวได้..."
20016-70 = "ถ้าเป็นที่นี่คงไม่ถูกเจอตัวแน่ๆ"
20016-80 = "เฮ้อ อะไรกันคะ\nตัวแทนเข้าเวรเนี่ย..."
20016-90 = "ค่ะ... ในเมื่อได้รับคำขอร้องมาแล้ว\nฉันจะพยายามให้เต็มที่ค่ะ"
20016-100 = "เฮ้อ เชิญค่ะ คุณครู\nเอาละค่ะ มีงานที่น่ารำคาญ\nรออยู่เต็มไปหมดเลยค่ะ"
20016-110 = "เฮ้อ..."
20016-120 = "เราสองคนออกไปอู้งาน\nที่อื่นกันดีมั้ยคะ? "
20016-130 = "กำลังตั้งใจทำงานอยู่เหรอคะ?"
20016-140 = "น่ารำคาญจริงๆ...\nเฮ้อ ช่วยไม่ได้นะคะ..."
20016-150 = "มีอะไรคะ? งานที่ต้องทำ\nฉันทำเสร็จหมดแล้วค่ะ"
20016-160 = "คุณครูมาที่นี่มีอะไรรึเปล่าคะ?\nมีอะไรให้ฉันช่วยมั้ยคะ?"
20016-170 = "ไม่ต้องทำหน้าแบบนั้น\nฉันก็ทราบอยู่แล้วค่ะ\nว่าวันนี้เป็นวันเกิดของคุณครู"
20016-180 = "ช่วยไม่ได้นะคะ...\nฉันจะอวยพรให้ก็แล้วกันค่ะ"
20016-190 = "สุขสันต์วันเกิดค่ะ คุณครู"
20016-200 = "คะ...? วันเกิดฉัน...?\nทำไมถึงรู้เรื่องนั้นได้..."
20016-210 = "เปล่าค่ะ ฉันไม่ได้หงุดหงิด\nอะไรสักหน่อย"
20016-220 = "ช่วยถอยออกไปด้วยค่ะ\nตอนนี้อย่าเพิ่งรบกวนฉันนะคะ"
20016-230 = "ขอให้มีความสุขมากๆ\nในวันปีใหม่นะคะ"
20016-240 = "นั่นสินะคะ พรวันปีใหม่..."
20016-250 = "หวังว่าปีนี้ งานที่น่ารำคาญ\nจะลดลงบ้างนะคะ"
20016-260 = "ทุกคนดูสนุกกันมากเลยนะคะ"
20016-270 = "เปล่าหรอกค่ะ\nไม่ใช่ว่าฉันไม่ชอบหรอกนะคะ"
20016-280 = "แต่ฉันไม่อยากออกไปข้างนอก\nถ้างั้นฉันจะอยู่เป็นเพื่อนคุณครู\nแล้วกันนะคะ"
20016-290 = "เอาละ ส่งลูกกวาดหวานๆ\nมาให้ฉันสิคะ"
20016-300 = "หืม...? ให้ฉันขอดีๆ เหรอคะ?"
20016-310 = "ได้ค่ะ ทริก ออร์ ทรีต...?"
20016-330 = "ฮิฮิ เป็นสถานที่...\nที่ใช้ได้เลยใช่มั้ยคะ?"
20016-340 = "หมอนอิงสุดนุ่มกับขนม\nมากมายที่เตรียมเอาไว้"
20016-350 = "นอกจากนี้ก็ยังมีหนังสือ\nกับเกมต่างๆ อยู่เต็มไปหมด"
20016-360 = "ที่นี่เป็นฐานลับของฉัน...\nที่ฉันภูมิใจมากเลยค่ะ\nคุณครูคิดว่ายังไงคะ?"
20016-370 = "ฮิฮิ คุณครูจะชื่นชม...\nแล้วพูดชมฉันเยอะๆ ก็ได้นะคะ"
20016-380 = "ตอนนี้เราเป็นผู้สมรู้ร่วมคิดกันแล้ว\nถ้างั้นวันนี้พวกเรามาอู้งานด้วยกัน...\nเหมือนที่เคยทำดีมั้ยคะ? "
20016-390 = "ว่ายังไงคะ~?  คุณครู...?"
20016-2600 = "เฮ้อ จริงๆ เลย ถ้าแบบนี้...\nฉันก็คงจะต้องตั้งใจทำแล้วสินะคะ"
