[translation]
20010-10 = "블루 아카이브."
20010-20 = "227호 온천장에 어서 오세요, 선생님.\n이 노도카가, 온천장의 여주인으로서\n성심을 다해 모시겠습니다!"
20010-30 = "저희 온천장에도\n이런 가구를\n들여놓으면 좋겠네요."
20010-40 = "이 카페는 언제나\n사람이 많네요.\n비결이 뭘까요?"
20010-50 = "우아아……\n비싸보이는\n물건이……"
20010-60 = "(어라, 분명 이 근처에서\n조금 전까지 선생님이…)"
20010-70 = "(구교사로\n아직은 돌아가고\n싶지 않아…)"
20010-80 = "227호 온천장,\n지금부터 영업\n시작하겠습니다!"
20010-90 = "어서 오세요, 선생님.\n식사부터 하시겠어요,\n목욕부터 하시겠어요?"
20010-100 = "……어? 아, 저, 그게!"
20010-110 = "저희 온천장에서\n그런 서비스는\n조금……"
20010-120 = "선생님. 이 기모노,\n어떠신가요?"
20010-130 = "그게, 모처럼 힘을 내서\n빌린 것인데……"
20010-140 = "……잘 어울리나요?\n헤헤, 헤헤헤……"
20010-150 = "붉은겨울 학원 유일의\n온천장이라는 이름에\n부끄럽지 않도록\n최선을 다하겠습니다!"
20010-160 = "으헤, 으헤헤……"
20010-170 = "아, 그, 보,\n보고 있었던 거\n아니거든요?"
20010-180 = "선생님, 혹시 목욕하고\n싶어지시면 꼭 저희\n온천장을 이용해주세요.\n꼭이에요! 아시겠죠?"
20010-190 = "온천개발부 분들도 그렇고……\n어쩐지 게헨나에는 이상한\n학생들이 많은 것 같아요."
20010-200 = "생신 축하드려요, 선생님!"
20010-210 = "오늘 하루는 저희 온천장에서\n느긋하게 푹 쉬시는 건\n어떠신가요?"
20010-220 = "아, 그러고보니\n제 생일이네요……"
20010-230 = "그게, 그렇다면, 조금만……"
20010-240 = "오늘은 아주 조금만\n어리광을 부려도 괜찮을까요?"
20010-250 = "올해도 맛있는 음식을\n잔뜩 먹을 수 있기를……"
20010-260 = "가이세키 요리에\n크리스마스 케이크는\n역시 이상할까요…?"
20010-270 = "할로윈을 기념하여 저희\n227호 온천장에서는 특별히\n호박맛 <운메에봉>을\n드리고 있답니다!"
20010-290 = "하아…… 좋은 탕이네요.\n들어간 것만으로 통증이\n사라지는 것 같은 기분이에요."
20010-300 = "주위의 풍경도\n정말로 예쁘고……"
20010-310 = "정원도 잘 가꿔진 게,\n정말로 멋진 장소네요."
20010-320 = "지붕이 있어서,\n밤하늘이 보이지 않는 것은\n조금 아쉽지만……"
20010-330 = "……아니, 이걸로\n괜찮을지도 모르겠어요."
20010-340 = "선생님과 단둘이서\n온천을 즐길 수 있다니,\n이런 행복감은……"
20010-350 = "별님에게는\n비밀로 해야 할 테니까요."
20010-2600 = "솔직히 말하자면, 이 무기를 온천장에서\n사용할 일은 없었으면 좋겠습니다만…\n필요하다면, 써야겠지요!"
