[translation]
20022-10 = "Blue Archive."
20022-20 = "Did you have any New Year's Eve noodles? I hope everything goes well for us this year!"
20022-30 = "Precise measurements are important when cooking."
20022-40 = "This kimono...is pretty."
20022-50 = "What was my first dream of the New Year?"
20022-60 = "I hope we have a peaceful year..."
20022-70 = "Maybe I can take a little break here..."
20022-80 = "Oh, Sensei! Welcome."
20022-90 = "Are you hungry? Can I make you something?"
20022-100 = "Please come in! I'll warm up some food."
20022-110 = "I made it with love."
20022-120 = "Wh-What do you think of my kimono?"
20022-130 = "I hope you like it..."
20022-140 = "I was nervous about wearing a kimono in front of you, but..."
20022-150 = "Now I'm glad I did."
20022-160 = "Did you know your hard work is very inspiring to the students?"
20022-170 = "To me as well, of course. Heeheehee."
20022-180 = "Osechi is a lot of work to make."
20022-190 = "But that's what makes it worth it in the end."
20022-200 = "I feel so relaxed with I'm with you."
20022-210 = "I should get going, but..."
20022-220 = "Huh? You want to stay with me a little longer?"
20022-230 = "Today's your birthday, Sensei! Happy birthday!"
20022-240 = "I'm glad I got to celebrate with you!"
20022-250 = "What dish would you like today?"
20022-260 = "Wow... My birthday... You remembered."
20022-270 = "Thank you...!"
20022-280 = "Just hearing that from you makes me so excited!"
20022-290 = "Happy New Year, Sensei."
20022-300 = "It's New Year's Day, so I put on my kimono."
20022-310 = "I made osechi. Will you join me?"
20022-320 = "It's Christmas... The year is almost over already."
20022-330 = "I was thinking of hosting a small party... What do you think?"
20022-340 = "The Halloween season is so fun and energetic."
20022-350 = "I wish we could eat the jack-o-lantern later..."
20022-370 = "I'm just...so happy."
20022-380 = "Thank you, once again, Sensei."
20022-390 = "You always give me so much, Sensei."
20022-400 = "You always enjoy my food..."
20022-410 = "And that's the biggest gift anyone could give me."
20022-420 = "Therefore, Sensei..."
20022-430 = "I'll look forward to the next time we talk."
20022-2600 = "It's so strange. When I'm with you, I feel like I can do anything. I'll try my best again this year. Please watch over me."
