[translation]
20029-10 = "蔚藍檔案"
20029-20 = "夏天……大海……\n充滿著快樂呢，老師。\n當，當然我也沒有忘記修行唷。"
20029-30 = "來打造一個大家\n都能放鬆的地方吧？"
20029-40 = "是個涼快的地方呢。\n似乎能悠哉地休息。"
20029-50 = "大家好像都很\n享受……太好了。"
20029-60 = "椿醬和楓醬現在\n在做什麼呢……"
20029-70 = "不知不覺間就\n沸騰了……\n夏天……真可怕呢！"
20029-80 = "歡迎回來，老師。\n準備已經完成，\n請儘管吩咐吧。"
20029-90 = "啊，老師！\n不會，沒關係的……\n我已經很習慣等待了。"
20029-100 = "夏天、大海……\n真是魔法般的詞彙呢。"
20029-110 = "就連我都差點\n忘了修行……"
20029-120 = "用讀心術……\n來猜猜老師\n在想什麼吧？"
20029-130 = "老師……想和我\n一起共度時光吧？"
20029-140 = "怎麼樣？猜對了嗎？"
20029-150 = "明明今天是為了\n協助老師的工作而來……"
20029-160 = "真不應該呢，我。\n一直……心有旁騖。\n修行還是不夠呢……"
20029-170 = "要不要來點檸檬汽水？\n此外，還有方便食用的\n三明治……"
20029-180 = "我做了很多，\n不介意的話請用。"
20029-190 = "覺得熱的話……\n請來我的遮陽傘下吧。"
20029-200 = "那個……膝枕，\n之類的，怎麼樣呢？"
20029-210 = "老師的生日……\n真是個美妙的日子呢。"
20029-220 = "呵呵，祝您生日快樂。\n老師。"
20029-230 = "我的生日……\n您願意為我慶祝嗎？"
20029-240 = "好開心，真的……\n開心到無法言喻。"
20029-250 = "呵呵。禮物，\n已經收到了呢？"
20029-260 = "新年快樂，老師。"
20029-270 = "已經是新年了呢。\n要一起祈禱嗎？"
20029-280 = "我的願望，是嗎？\n呵呵……是祕密。"
20029-290 = "是聖誕節呢，老師。\n據說乖孩子\n會收到禮物……"
20029-300 = "所以……那個……\n您怎麼看呢，老師。\n我是……乖孩子嗎？"
20029-310 = "哇啊，是萬聖節呢。\n 糖果跟惡作劇\n都準備好了唷。"
20029-320 = "咦？不需要兩個\n都準備？說的也是……"
20029-340 = "真希望……\n這一刻能永遠\n持續下去。"
20029-350 = "就這樣，像照片或繪畫一樣\n將時間記錄下來──\n如此一來……"
20029-360 = "老師也是\n一樣的心情嗎？"
20029-370 = "那樣……好像有點難為情呢。"
20029-380 = "我今天……\n幸福到……\n足以忘記修行。"
20029-390 = "那個……老師。"
20029-400 = "之後還有機會……\n能共創這樣的時光嗎？"
20029-2600 = "居然能收到這麼棒的禮物……\n我心中滿溢的心情，\n雖然很想用言語來表達……\n卻有些，難以統整……\n那個……謝謝您，老師。"
