[translation]
20026-10 = "Blue, Archive."
20026-20 = "Civil engineering, construction, demolition... Contact us if you need workers. We'll even agitate for you!"
20026-30 = "The most important thing in the field is safety, above all else."
20026-40 = "The architecture here... I'll just say it's not bad."
20026-50 = "Leave it to our workers. This is nothing..."
20026-60 = "A 3-day work week... What a lovely phrase..."
20026-70 = "The pudding here seems...different from the pudding supplied by the secretariat."
20026-80 = "Stay safe today!"
20026-90 = "Let's aim for a new \"No Accident\" record in Schale!"
20026-100 = "You're late. This isn't sabotage, is it?"
20026-110 = "Sensei, I don't know what you're trying to prove"
20026-120 = "with this sabotage, but..."
20026-130 = "Safety, check! Confirmation, check! Accident-free, check!"
20026-140 = "When it comes to pudding, I love all flavors."
20026-150 = "Custard cream, chocolate, even fruit..."
20026-160 = "...just not water pudding."
20026-170 = "(What would be a good justification for our next coup d'etat...?)"
20026-180 = "Sensei, I think you've been working too late for too long..."
20026-190 = "You are getting overtime pay, right?"
20026-200 = "I wonder what our upperclassman is doing right now..."
20026-210 = "I hope our upperclassman is doing well."
20026-220 = "Congratulations, Sensei."
20026-230 = "Let us celebrate the birth of a new comrade today."
20026-240 = "Heehee... Sensei, do you know what today is?"
20026-250 = "Yes! It's a day that we should celebrate with our all!"
20026-260 = "On this day, the people rose up and demanded freedom!"
20026-270 = "Huh...? It's my birthday...?"
20026-280 = "...I totally forgot."
20026-290 = "This is the year we claim the Red Winter Academy Secretariat for the party."
20026-300 = "We'll create a paradise for workers...!"
20026-310 = "Only distributing gifts to good kids..."
20026-320 = "This Santa Claus sounds like a dirty capitalist to me."
20026-330 = "I once tasted a limited time Halloween pumpkin pudding..."
20026-340 = "It had a subtle sweetness that was oh, so luxurious..."
20026-350 = "I'd even work weekends for another taste of such a snack..."
20026-360 = "Eek! Wh-What am I saying...?"
20026-380 = "Hahaha... On a cold, brisk day like this, I can see forever."
20026-390 = "Sensei, don't just stand there. Come and take a look."
20026-400 = "There's nothing to worry about."
20026-410 = "This scaffolding is so sturdy it can hold an entire elephant."
20026-420 = "Come to think of it, this scaffolding"
20026-430 = "is a lot like the Labor Party."
20026-440 = "Construction is impossible without it, but"
20026-450 = "it must disappear like it never existed once the work is done..."
20026-460 = "Maybe that's why I love standing up here on the scaffolding"
20026-470 = "and looking down at the job site from the top of the world."
20026-480 = "This is proof of the hard work of everyone"
20026-490 = "who stood on the edge and build these walls with their own hands."
20026-500 = "...This proof, nowhere to be found on a finished building,"
20026-510 = "it what I wanted to share with you, Sensei."
20026-2600 = "Strong, trustworthy equipment is your best partner on a work site. In that sense... This rascal has never disappointed me."
