[translation]
20028-10 = "蔚藍檔案！"
20028-20 = "我，我叫若葉日向！\n我會努力的，請儘管吩咐！"
20028-30 = "這裡的裝潢，\n真是非常可愛呢…！"
20028-40 = "那個，\n要搬東西的話，\n我隨時奉陪！"
20028-50 = "咦？感覺好像\n有人在叫我的名字…"
20028-60 = "是個能放鬆的\n好地方呢。"
20028-70 = "老師…\n會在哪裡呢…？"
20028-80 = "辛，辛苦了，老師。"
20028-90 = "那個…一起去海邊散步，\n您覺得如何呢？"
20028-100 = "歡迎回來，老師。"
20028-110 = "希，希望今天\n也會是充滿\n愛與喜悅的一天。"
20028-120 = "老師的工作，\n請務必讓我幫忙！"
20028-130 = "喜不喜歡夏天，是嗎…？"
20028-140 = "嗯，當然！\n春天、秋天、冬天\n我也都很喜歡。"
20028-150 = "夏天獨有的樂趣，\n海邊獨有的樂趣，\n我想要好好珍惜它們。"
20028-160 = "嗯…老實說，\n穿著泳裝…\n有點，害羞。"
20028-170 = "就，就算身穿泳裝，\n也不會對祈禱造成妨礙！"
20028-180 = "祝您生日快樂，老師！"
20028-190 = "希望明年的今天，\n也能為老師獻上祝福。"
20028-200 = "啊，我的生日…\n您記得啊！"
20028-210 = "非常感謝…\n我真的很開心。"
20028-220 = "新年快樂，老師。"
20028-230 = "希望今年是健康的一年，\n我會打從心底為您祈禱。"
20028-240 = "是聖誕節呢！"
20028-250 = "對我們修女會來說\n是個特別的日子！"
20028-260 = "…服，服裝，\n沒有關係！"
20028-270 = "是萬聖節呢！\n鎮上充滿開心的笑容，\n讓我也不由得開心起來了！"
20028-290 = "嗯…嗯嗯…？\n哎呀…？"
20028-300 = "這裡…比想像中\n更能放鬆…"
20028-310 = "涼爽得恰到好處，\n卻不會太冷…\n臉也能躲在陰影下…"
20028-320 = "暖洋洋的…\n感覺躺著躺著\n就要睡著了。"
20028-330 = "話說回來，那個…\n明明在老師面前，\n卻只有我躺著…"
20028-340 = "感，感覺…\n有點不好意思…"
20028-350 = "我，我知道了。\n那麼，就承蒙您的好意…"
20028-360 = "放鬆下來…\n舒服地…"
20028-370 = "…呼…呣喵…\n呼嘿嘿…"
20028-380 = "…哈！？\n我，我剛才說了什麼…！？"
20028-390 = "請，請您忘了吧，\n請忘掉我剛才說的話！\n老師！！"
20028-2600 = "那個……該怎麼答謝才好呢……\n不，只靠言語是無法傳達的……\n這份恩情……\n我一定會用行動報答您，老師。"
