[translation]
20032-10 = "Blue Archive"
20032-20 = "It's much cooler than usual. Is that why my body feels so light?"
20032-30 = "With Himari gone..."
20032-40 = "It would be perfect if we had some shaved iced here."
20032-50 = "The AC power button..."
20032-60 = "The increase of occupants here is making it warmer."
20032-70 = "I would like to spend the rest of my life here."
20032-80 = "Welcome, Sensei. I've cooled the room for you."
20032-90 = "Great job, Sensei. Why do you appear surprised?"
20032-100 = "...Why am I still wearing this?"
20032-110 = "...Because I like it."
20032-120 = "It's...hot... Please... Please lower the thermostat."
20032-130 = "I will remove my jacket."
20032-140 = "Underwear is not appropriate. But swimsuits are?"
20032-150 = "How are the two different? Does the material make one more acceptable?"
20032-160 = "I found this magazine to be a great reference. I found it under the desk."
20032-170 = "...What's wrong, Sensei?"
20032-180 = "Happy birthday, Sensei. On this special day, I will try to wear an outfit you approve of."
20032-190 = "Do you have any requests?"
20032-200 = "You told me we would spend some time together."
20032-210 = "I've created a schedule to maximize our efficiency."
20032-220 = "I will not waste even one second of this day."
20032-230 = "Happy New Year, Sensei. I hope that my skills will improve to the point that I'll feel satisfied with myself this year."
20032-240 = "It's Christmas. I brought an appropriate outfit, so I'll change into it and..."
20032-250 = "...Or am I already in the holiday spirit?"
20032-260 = "I like Halloween. No one will blink an eye at whatever you wear."
20032-280 = "Hm? I'm not cold. I'm just fine."
20032-290 = "In fact, this temperature is absolutely perfect."
20032-300 = "It's nice... Want to come in, Sensei?"
20032-310 = "Aww. All right."
20032-320 = "I'll be out in just a moment. So please be patient, Sensei."
20032-2600 = "Regardless of the environment, with this, I can relax."
