[translation]
20031-10 = "블루 아카이브~"
20031-20 = "야호~ 선생님, 227호 온천장에 어서 와.\n나는 신경 쓰지 말고 편하게 있다 가라고."
20031-30 = "(어디선가 한기가\n느껴지는 걸……)"
20031-40 = "(이런 떠들썩함은\n오랜만이지만…… \n싫지는 않아.)"
20031-50 = "으음, 좋은 향기."
20031-60 = "어라?\n이거…… 상했나?"
20031-70 = "이 한 잔은……\n지나간 겨울을 위하여."
20031-80 = "227호 온천장, 영업 시작이야."
20031-90 = "어서 와, 선생님.\n웰컴 드링크, 한잔할래?"
20031-100 = "음…… 뜨거운 탕 안에\n있다 와서 그런가.\n몸이 조금 달아오르는 느낌이네……"
20031-110 = "최근에 알게 된 것인데,\n우유를 발효시켜도\n알코올이 만들어진다던데?"
20031-120 = "그렇다면 후르츠\n밀크를 이용해서……"
20031-130 = "그런 눈으로 쳐다보지 마.\n안 할 테니까."
20031-140 = "노도카는 대단하지.\n나한테 노도카와 같은 열정은\n존재하지 않을 거야."
20031-150 = "온천에서 곰과 마주치더라도\n너무 놀라지는 마.\n우리 직원이거든."
20031-160 = "......물론 농담이야."
20031-170 = "선생님, 무리는 하지 마.\n선생님이 아프면\n슬퍼할 아이들이 많거든."
20031-180 = "생일 축하해, 선생님.\n오늘을 위해 특별한 탕을 준비했어.\n나중에 같이 들어가자."
20031-190 = "에, 혼자서 즐기고 싶다고?"
20031-200 = "어~째~서~야~"
20031-210 = "맛있는 걸 사주겠다고?\n생일이니까?"
20031-220 = "후후, 뭘 부탁해 볼까……"
20031-230 = "뭐, 선생님이 사주는 거면\n뭐든지 괜찮아."
20031-240 = "……카레만 빼고."
20031-250 = "(올해도 작년과 마찬가지로\n변치 않는 한 해가 되기를.)"
20031-260 = "아, 선생님. 칠면조 구이에\n잘 어울리는 음료를 만들었거든.\n이따가 하나 챙겨가."
20031-270 = "아직 발효는……\n안 되었을 거야. \n아직은 말이지, 후후……"
20031-280 = "호박은 향도 좋고\n당분도 충분하니\n괜찮을 것 같은데……"
20031-290 = "아, 호박 주스의 이야기였어.\n신경 쓰지 마, 신경 쓰지 마."
20031-310 = "자, 선생님.\n이불 바깥은 춥지?"
20031-320 = "고집부리지 말고,\n이리로 와."
20031-330 = "이불도 푹신푹신하고,\n따듯하다구?"
20031-340 = "이 안이라면\n금방 잠들 수 있을 거야."
20031-350 = "혹시 이불을 덮어도\n춥다면……"
20031-360 = "내가 대신 탕파가\n되어줄 테니까."
20031-370 = "응? 원래 있던 탕파……?"
20031-380 = "그러니까……\n전부, 마셔버렸어."
20031-390 = "그게, 이불 안이 말이야,\n모르스를 덥히기에\n딱 좋은 온도여서."
20031-400 = "아까 일하던 중에 탕파의\n내용물을 특제 모르스로\n바꾸어 두었거든."
20031-410 = "그래도 어쩔 수 없잖아?\n이렇게 되었으니 몸을 덥힐 만한\n다른 수단도 없고 말이야."
20031-420 = "그러니까 오늘 밤은 선생님이\n탕파가 되어줘."
20031-2600 = "뭐, 무기를 쓰는 일은\n많지 않을수록 좋겠지만……\n필요하다면, 써야겠지."
