[translation]
20032-10 = "Blue Archive"
20032-20 = "รู้สึกตัวเบากว่าปกติแฮะ\nเพราะอากาศเย็นรึเปล่านะ?"
20032-30 = "อาศัยจังหวะที่\nรุ่นพี่ฮิมาริไม่อยู่..."
20032-40 = "ถ้าที่นี่มีน้ำแข็งไส\nก็จะสมบูรณ์แบบเลย"
20032-50 = "สวิตช์เปิดแอร์..."
20032-60 = "ร้อนขึ้นเรื่อยๆ เลย...\nเพราะคนเยอะรึเปล่านะ"
20032-70 = "ถ้าเป็นที่นี่ละก็\nฉันอยู่ได้\nตลอดชีวิตเลยละ"
20032-80 = "เข้ามาสิ คุณครู\nฉันทำห้องให้เย็นๆ ไว้แล้ว"
20032-90 = "ทำได้ดีมากเลยคุณครู\n...ทำไมถึงตกใจล่ะ?"
20032-100 = "ทำไมฉันถึง\nยังใส่ชุดนี้อยู่น่ะเหรอ?"
20032-110 = "...ก็เพราะฉันชอบน่ะ?"
20032-120 = "ที่นี่... ร้อนมากเลย...\nลดอุณหภูมิแอร์ได้มั้ย?"
20032-130 = "ว่าแล้วเชียว ถอดแจ็กเกตดีมั้ยนะ..."
20032-140 = "ใส่แต่ชุดชั้นในไม่ได้\nแต่ชุดว่ายน้ำไม่เป็นไรงั้นเหรอ...?"
20032-150 = "มันต่างกันยังไงเนี่ย?\nคุณสมบัติในการกันน้ำงั้นเหรอ?"
20032-160 = "ฉันเจอนิตยสารแบบนี้\nจากใต้โต๊ะน่ะ\nมีข้อมูลดีๆ เยอะเลย"
20032-170 = "เป็นอะไรน่ะคุณครู ตกใจอะไรเบอร์นั้น"
20032-180 = "สุขสันต์วันเกิดนะคุณครู\nวันนี้ฉันตั้งใจจะ\nใส่ชุดที่คุณครูชอบน่ะ..."
20032-190 = "มีอะไรที่อยาก\nรีเควสฉันมั้ย?"
20032-200 = "เห็นคุณครูบอกว่า\nจะอยู่เป็นเพื่อนกัน"
20032-210 = "ฉันเลยวางแพลนวันเกิด\nที่ยอดเยี่ยมที่สุดมาเลย"
20032-220 = "วันนี้ฉันไม่อยากเสียเวลา\nแม้แต่สักวินาทีเดียวเลย"
20032-230 = "สวัสดีปีใหม่นะคุณครู\nปีนี้ฉันอยากมีความสามารถ\nที่ตัวเองยอมรับได้จัง"
20032-240 = "คริสต์มาสนี่นา\nฉันเอาชุดที่เหมาะกับวันนี้มา\nงั้นไปเปลี่ยนชุด..."
20032-250 = "อืม ถูกใจชุดนี้\nที่สุดเหรอ...?"
20032-260 = "ฮาโลวีนนี่ดีจังเลย\nไม่ว่าจะใส่อะไร ทุกคนก็ชอบ"
20032-280 = "หืม?\nไม่หนาวหรอก ไม่เป็นไร"
20032-290 = "ตรงกันข้าม ตอนนี้มัน\nเย็นสบายกำลังดีเลยละ"
20032-300 = "อารมณ์ดีจัง...\nคุณครูก็ลงมาด้วยมั้ย?"
20032-310 = "ฮืม~ งั้นก็ไม่เป็นไร"
20032-320 = "แต่เดี๋ยวฉันจะขึ้นไป\nช่วยรอหน่อยนะ คุณครู"
20032-2600 = "ถึงชุดหรือสภาพแวดล้อมจะเปลี่ยน...\nแต่ถ้ามีสิ่งนี้ก็หายห่วง"
