[translation]
20035-10 = "蔚藍檔案～呼啊啊……"
20035-20 = "這次是導覽員哦……\n修行跟導覽，我都會努力的～\n呼啊……"
20035-30 = "大家……這邊唷……\n咦……只有我一個人？"
20035-40 = "為人們導覽的夢……\n原來不是夢嗎……？"
20035-50 = "聽說人……一生\n3分之1的時間\n都在睡夢中度過……"
20035-60 = "好好睡覺\n是很重要的唷……\n比想像中還重要……"
20035-70 = "如果是百鬼夜行\n的事……\n就交給我……"
20035-80 = "你好，老師……\n歡迎回來……"
20035-90 = "話說現在幾點……？"
20035-100 = "晚安……"
20035-110 = "既然打過招呼了，\n老師也一起睡吧。嗯……？"
20035-120 = "呼啊……沒有。\n我沒有在睡覺……"
20035-130 = "只是在測試夏萊是不是\n好睡的地方而已……"
20035-140 = "睡眠枕頭和棉被，\n眼罩和耳塞……\n全都準備好囉。"
20035-150 = "接著只要老師來就行了……"
20035-160 = "呵呵。總有一天單獨兩人，\n去某個地方旅行也不錯呢。"
20035-170 = "比如夢之國之類的……"
20035-180 = "導覽員必須具備的……\n我認為是說明的能力……"
20035-190 = "因為得要將\n自己知道的事\n好好告訴別人……"
20035-200 = "我也不是一直只想著\n睡覺的哦……？"
20035-210 = "唔嗯……比如\n跟老師見面的時候……"
20035-220 = "是生日呢，老師……"
20035-230 = "呵呵。恭喜恭喜。"
20035-240 = "作為禮物，今天\n直到睡著為止，\n我都會陪著你……"
20035-250 = "沒錯……\n今天是我的生日呢……"
20035-260 = "生日禮物果然……\n還是老師的膝枕最好……\n呼嚕……"
20035-270 = "新年到了呢。\n一年的開始……\n或者說一年的\n第一個早晨……"
20035-280 = "雖然我早上很沒精神，\n但我喜歡新年……"
20035-290 = "Merry～Christmas～"
20035-300 = "聽說在百鬼夜行外，\n會這樣打招呼？"
20035-310 = "萬聖節……"
20035-320 = "是能見到像夢一樣\n風景的日子呢……"
20035-330 = "呵呵。這種日子該對什麼，\n做什麼樣的導覽呢？"
20035-350 = "呼……腳好像有點痛。"
20035-360 = "因為這雙鞋還穿不太習慣。嗯。"
20035-370 = "怎麼了嗎，老師？\n一直盯著我這邊……"
20035-380 = "嗯？感覺我……\n看起來跟平常不太一樣……？"
20035-390 = "……真奇怪。"
20035-400 = "呵呵。\n不過老師能那樣\n看著我的話……\n好像也還不賴？"
20035-410 = "吶，老師。"
20035-420 = "要是今天我們兩個……\n都能做個好夢，就好了呢。"
20035-2600 = "謝謝你，老師……\n阻攔老師睡眠的敵人……\n就由我來打倒……"
