[translation]
20038-10 = "蔚藍檔案。"
20038-20 = "歡迎來到赤冬……不，歡迎來到山海經。\n為了不讓鬍子的權威蒙羞，\n我會誠心誠意，助您一臂之力。"
20038-30 = "呼……這裡\n很涼快真是得救了。"
20038-40 = "（不配果醬喝紅茶……？\n　真是獨特的喝法呢）"
20038-50 = "這個設計……我會\n當成製作潔莉諾醬\n周邊時的參考。"
20038-60 = "是因為身著輕裝\n的關係嗎？活動\n起來變得更方便了。"
20038-70 = "接下來，將為各位\n播報偉大的潔莉諾大人\n的最新情報！"
20038-80 = "歡迎光臨。\n請問要點什麼呢？"
20038-90 = "……我試著模仿了\n玄武商會的店員。\n您覺得如何呢？呵呵。"
20038-100 = "恭候多時了，老師。\n要來一杯清涼的茶嗎？"
20038-110 = "呼……這個熱度，\n要習慣可能\n還需要一點時間。"
20038-120 = "或許是因為山海經很\n重視教育，在自治區內\n時常會看見小孩子。"
20038-130 = "我很喜歡小孩子哦？\n畢竟他們可說是學園的未來。"
20038-140 = "京劇部的公演……\n成為了讓我重新思考\n話術也有許多種類的契機。"
20038-150 = "在下次的定期演說中，\n我會試著加入京劇的要素。\n呵呵。"
20038-160 = "玄武商會的料理\n雖然都是絕品，\n不過卻略顯油膩……"
20038-170 = "讓人對潔莉諾醬\n的營養均衡有點擔心。"
20038-180 = "我向玄龍門的門主大人\n送了鬍子作為禮物……\n可惜被鄭重地拒絕了。"
20038-190 = "感覺很適合他的說……"
20038-200 = "祝您生日快樂，老師。"
20038-210 = "我買了玄武商會的\n特製肉包過來。"
20038-220 = "那個……我的頭上\n沒有戴著肉包唷……？"
20038-230 = "……啊啊，話說\n是我的生日呢。\n太專注於工作，\n不小心就忘記了。"
20038-240 = "禮物的事請您不必掛心。"
20038-250 = "……如果您\n堅持說要的話……"
20038-260 = "午睡的時間，\n能請您在一旁陪我嗎？呵呵。"
20038-270 = "新年快樂，老師。\n有夢見初夢了嗎？"
20038-280 = "我的初夢……\n是被潔莉諾醬\n追過身高的惡夢……"
20038-290 = "在山海經的聖誕派對……\n實在很不錯呢。"
20038-300 = "沒有用槲寄生來裝飾\n倒是有點可惜。"
20038-310 = "作為萬聖節的變裝，\n我從京劇部借來了\n幾個面具。"
20038-320 = "畫著鬍子的面具\n還真多呢……"
20038-330 = "山海經的各位，或許\n其實喜歡鬍子也說不定？"
20038-350 = "涼爽的風……\n恰到好處的遮蔭……\n再用團扇消暑……"
20038-360 = "呵呵。這確實是\n不曾有過的經驗呢。"
20038-370 = "這一次又一次的經驗……\n能夠讓視野更加寬廣呢。"
20038-380 = "哎呀？或許那並不是\n多有趣的東西也說不定哦？"
20038-390 = "呵呵，老師。\n別在那種地方看著……\n請過來這邊。"
20038-400 = "來，我會為您用團扇搧風的。"
20038-2600 = "雖然有句話說言語更勝槍枝……\n……不過還是用槍說服比較快！"
