[translation]
20030-10 = "Blue Archive"
20030-20 = "The season of exercise...and appetite! There's a culinary feast to be enjoyed...and I have no choice but to take advantage of this opportunity."
20030-30 = "Let us now depart on a gastronomic adventure."
20030-40 = "So where should we head first...?"
20030-50 = "Eating is a noble pursuit."
20030-60 = "No amount of exercising will do you any good if you don't eat well."
20030-70 = "After we're done resting, shall we explore the street stalls?"
20030-80 = "Welcome, Sensei."
20030-90 = "Can I ask you about today's schedule?"
20030-100 = "I can't believe you made me wait..."
20030-110 = "But for you, Sensei, I'll wait as long as you need. Heehee..."
20030-120 = "I'm already in my gym clothes, and part of me does want to compete, but..."
20030-130 = "Going to the games, cheering for my friends, and eating something delicious..."
20030-140 = "What a perfect order of events."
20030-150 = "I feel somehow lighter dressed like this..."
20030-160 = "Gym clothes really are something special."
20030-170 = "I feel more at peace than usual."
20030-180 = "Could it be because of this outfit? Or perhaps because of Sensei...?"
20030-190 = "Heehee..."
20030-200 = "Sensei, after this, can you spare some time for me?"
20030-210 = "I'll take you to the best street stall."
20030-220 = "Yes, of course I remember."
20030-230 = "Today is your birthday, Sensei."
20030-240 = "This outfit is so comfy and easy to move in. Why don't we go out?"
20030-250 = "I can't believe you're wishing me a happy birthday..."
20030-260 = "Thank you. I know I've already received my gift, but..."
20030-270 = "Well, it's only once a year, so maybe it's okay if I'm a little greedy..."
20030-280 = "Sensei, would you join me on a stroll through the street stalls?"
20030-290 = "Happy New Year, Sensei."
20030-300 = "A day to celebrate the start of a new year..."
20030-310 = "And a great excuse to check out all the delicious offerings at the local food stalls."
20030-320 = "Shall we go take a look?"
20030-330 = "Spending Christmas together... Heehee, what a wonderful thought."
20030-340 = "I brought a dish that's just perfect for sharing."
20030-350 = "Let's dig in!"
20030-360 = "I guess...some people think this is my Halloween costume..."
20030-370 = "I found out there's a food stall nearby that sells pumpkin snacks."
20030-380 = "Shall we go check it out?"
20030-400 = "It was a heart-pounding and delicious match."
20030-410 = "My face got a little messy, but it was well worth it."
20030-420 = "In that uncharted territory of flour..."
20030-430 = "The act of finding candy using your senses..."
20030-440 = "Seemed quite similar to the exploration of gastronomy..."
20030-450 = "I found it very refreshing."
20030-460 = "Ah, I nearly forgot!"
20030-470 = "Sensei. Would you like this?"
20030-480 = "This candy I won... Would you like to share it together?"
20030-2600 = "I'll do my best. Especially for you, Sensei, since I know how much you care."
