[translation]
20045-10 = "Blue Archive~"
20045-20 = "백귀야행 연합학원,\n마츠리운영관리부 아사히나 피나!\n여러분을 안내해 드릴게요!"
20045-30 = "Wow~ 임협물의\n사무소 같아서\n멋집니다!"
20045-40 = "(이 TV……\n영화를 볼 수\n있습니다!)"
20045-50 = "이 분위기,\n어딘가에서 본 적\n있습니다!"
20045-60 = "멋진 분들이\n잔뜩……\n피나도 질 수 없습니다!"
20045-70 = "쉬는 모습을 보다 보니\n저도 낮잠이……"
20045-80 = "다 모였습니다,\n선생님!"
20045-90 = "선생님! 오늘은 피나가\nGuide입니다!"
20045-100 = "검은 옷을 입고,\n사람들을 이끄는 것……"
20045-110 = "이것도, 어찌 보면\n임협 아닐까요?!"
20045-120 = "백귀야행은 제 앞마당\n같은 곳입니다!"
20045-130 = "안내라면\n맡겨주세요!"
20045-140 = "우리의 방식으로\n맞이하겠습니다!"
20045-150 = "각오해 주세요!"
20045-160 = "선생님께서 함께라면\n무적입니다!"
20045-170 = "선생님,\nBirthday 이셨죠?"
20045-180 = "연회 준비라면\n문제없습니다!"
20045-190 = "오늘은 피나의\n생일입니다!"
20045-200 = "Happy birthday\nto me~!"
20045-210 = "Happy New Year!"
20045-220 = "새해 축하드립니다. 두목!"
20045-230 = "……아니, 선생님!"
20045-240 = "호호호\n메리 크리스마스입니다,\n선생님!"
20045-250 = "Trick or Treat!\nHalloween, 입니다!"
20045-270 = "우-웅-!! 하-!"
20045-280 = "어쩐지,\n긴장하고 있었나 봅니다."
20045-290 = "손님들과 함께 있을 때는\n열중하느라,\n눈치채지 못했는데……"
20045-300 = "이렇게 선생님과 함께 있으니,\n마음이 한결 놓입니다."
20045-310 = "날렵하기 위해서는\n스트레칭도 필수!\n다시 한번!"
20045-320 = "음, 음, 으-읏!"
20045-330 = "네? 릴렉스하는 모습이……\n좋은가요?"
20045-340 = "그…… 그게……\n가이드로서 기합과\n책임도 물론 중요하지만……"
20045-350 = "단둘이 있을 때에는……\n뭐랄까……"
20045-360 = "그,\n마음을 놓게 된달까요……"
20045-2600 = "한 단계, 아니. 500단계는 더 성장한 것 같습니다!"
