[translation]
20053-10 = "蔚藍～咳哼⋯⋯檔案？"
20053-20 = "老師大人～感覺怎麼樣呀？\n這次是潛入任務唷！請多指教啦！"
20053-30 = "呵呵……要是有人\n認出我該怎麼辦……？"
20053-40 = "這套禮服⋯⋯在這裡\n穿太超過了嗎……？"
20053-50 = "（禮服和咖啡……啊！\n這個點子好像能用……！）"
20053-60 = "有朝一日絕對……！\n要在這裡舉辦\n粉絲見面會……！"
20053-70 = "（好，總之……\n不吸引目光的地點\n在哪裡呢？）"
20053-80 = "老師大人，我在等你哦～！"
20053-90 = "月夜借了電捲棒給我……\n你知道怎麼用嗎？"
20053-100 = "恭候多時了，老師。"
20053-110 = "……不對。\n就算穿著禮服，\n這樣還是不對。"
20053-120 = "越漂亮的衣服，\n是不是就越不方便呢……"
20053-130 = "這套衣服……\n雖然動起來不方便，\n但能藏道具的地方\n很多這點還挺不錯的。"
20053-140 = "所謂的忍者，\n是寄宿於心裡的……！"
20053-150 = "所以就算穿著禮服，\n忍者依然是忍者！"
20053-160 = "雖然想吃拉麵……\n不過這副打扮實在……"
20053-170 = "這就是三千留流的\nDress code～！哼哼哼！"
20053-180 = "哼哼哼……\n今天我為了老師大人，\n特別打扮了唷！"
20053-190 = "……嗯？\n問我是不是禮物？ "
20053-200 = "才，才不是！\n不，雖然那也\n不是不行啦⋯⋯"
20053-210 = "啊，我不是那個意思！\n唔喵啊啊⋯⋯！！"
20053-220 = "啊，老師大人。\n今天有我的生日直播哦。"
20053-230 = "就當作是生日禮物⋯⋯\n能請老師大人，\n以特別來賓的身分出演嗎？"
20053-240 = "咦，可以嗎？那趕快！\n坐在這邊，然後看鏡頭！"
20053-250 = "新年快樂～老師大人♪"
20053-260 = "果然說到新年\n就會想到時代劇呢！"
20053-270 = "所以……要不要一起\n來場時代劇馬拉松呀？"
20053-280 = "老師大人，你知道嗎！？"
20053-290 = "聽說聖誕老人的真實身分……\n其實是變裝的忍者耶……！"
20053-300 = "嗯？這些菱角釘？"
20053-310 = "當然，是為了對付覬覦\n糖果之人的陷阱所──"
20053-320 = "……開，開玩笑的啦。\n只是菱角釘造型的糖果而已。"
20053-340 = "裡面是……戒指對吧！？"
20053-350 = "上面還有手裏劍的裝飾，\n感覺……不錯嘛！？"
20053-360 = "……咦？\n老師大人，\n要戴嗎……？"
20053-370 = "啊，不，我是無所謂啦……"
20053-380 = "（咦……？把戒指，\n　交給對方……？） "
20053-390 = "（這樣……不就像是\n　在告白嗎──！？）"
20053-400 = "先，先等一下，老師大人！"
20053-410 = "這真的不是我算好的……\n不過，那個……！ "
20053-420 = "嗚……嗚啊啊～～！"
20053-2600 = "可以嗎……？\n要給我，這麼棒的……！\n不過，既然是老師大人的判斷！\n嗯！謝謝你！"
