[translation]
20052-10 = "Blue Archive. Heh, heh, heh."
20052-20 = "Publish, print, distribute. That's the Publishing Department's motto. Hello, Sensei. I'm Aramaki Yakumo."
20052-30 = "Let's see... How best to optimize our revenue streams..."
20052-40 = "It's warm and cozy here..."
20052-50 = "What if I set up a sales booth there...? Heh, heh, heh."
20052-60 = "Nowadays, textual content is more of a business platform."
20052-70 = "I wonder how much this place makes daily...?"
20052-80 = "Wow, you're here, Sensei!"
20052-90 = "I was waiting so anxiously."
20052-100 = "Now then, shall we start a discussion about..."
20052-110 = "...our new business venture between the Publishing Department and Schale? Heh, heh, heh."
20052-120 = "I was waiting!"
20052-130 = "As I was standing here..."
20052-140 = "...I came up with a list of books that Schale might need."
20052-150 = "..If you want, I'll bring them right away. Heh, heh, heh."
20052-160 = "My hobby is writing business proposals, yeah."
20052-170 = "That's odd? Well, you could look at it that way..."
20052-180 = "But I like imagining the possibilities."
20052-190 = "Writing down your ideas is surprisingly fun, you know?"
20052-200 = "...That's not a collection of business proposals, but a scratchpad?"
20052-210 = "What do you mean?! This isn't some scratchpad!"
20052-220 = "It's different because... Well, um..."
20052-230 = "Negotiating the budget with the Office is always tough..."
20052-240 = "But...ultimately, all that matters is getting paid, right?"
20052-250 = "We overcome any deficits with the Publishing Department's business capability!"
20052-260 = "...And charge the Office again to earn twice as much. Heh, heh, heh."
20052-270 = "I rode multiple types of transportation to get to Schale."
20052-280 = "And I'm quite envious of your railroad system..."
20052-290 = "Well, that's not the only thing that I'm envious of..."
20052-300 = "The publishing industry is in a biiit of a squeeze nowadays."
20052-310 = "Especially with text being overrun by video platforms."
20052-320 = "Which is why I came to the following conclusion."
20052-330 = "The Publishing Department should also absorb various video platforms!"
20052-340 = "Ah. I'm serious about this."
20052-350 = "I want to become a transfer student at Schale."
20052-360 = "It's warm, the facilities are maintained, and there are plenty of business opportunities. You're here as well."
20052-370 = "I can't, since Schale is not a school?"
20052-380 = "Right... Reality is frequently bitingly cold..."
20052-390 = "Would you look at that, our star of the day is here."
20052-400 = "Happy birthday, Sensei. Here's a small gift from me."
20052-410 = "Here, it's a library card. I look forward to seeing you use it. Heh, heh, heh."
20052-420 = "Today is May 18th, you know?"
20052-430 = "Isn't there something you're forgetting? Don't you have something you should say to me?"
20052-440 = "As expected of you! I knew you'd remember my birthday!"
20052-450 = "It's the new year. Mmm..."
20052-460 = "Most businesses plan an event for every new year."
20052-470 = "It's a bit of a dilemma..."
20052-480 = "It doesn't make a big impact because everyone does it..."
20052-490 = "...but you'll fall behind if you don't bother..."
20052-500 = "They say Christmas season is the peak business season!"
20052-510 = "So many owners plan for the season, complacent and uninspired..."
20052-520 = "...thinking anything will sell this time of year."
20052-530 = "Today is Halloween."
20052-540 = "Oh, right. I've had this question ever since I met you."
20052-550 = "Getting a treat from you, or getting the freedom to trick you..."
20052-560 = "I wonder which one's better."
20052-580 = "Oh... It feels soft."
20052-590 = "This might be nice..."
20052-600 = "Why did saying that give me chills?"
20052-610 = "Achoo!"
20052-620 = "Did you get it? Now then, your turn."
20052-630 = "Huh? Did you really mean to make me do this by myself?"
20052-640 = "Dear, oh dear. I don't think that's very responsible of you, Sensei."
20052-650 = "Red Winter's cold is the same for everyone, you know? Heh, heh, heh."
20052-2600 = "They say it depends on how you use the tool, right? With this, I can \"guarantee\" that my contracts are upheld. Heh, heh, heh."
