[translation]
20052-10 = "블루, 아카이브. 힛. 힛. 히."
20052-20 = "출판, 증쇄, 유통. 그야말로 출판부의 모토죠.\n안녕하십니까, 선생님. 아라마키 야쿠모입니다."
20052-30 = "어디 봅시다……\n판로를 열려면……"
20052-40 = "따듯하고\n아늑한 장소네요……"
20052-50 = "저쪽에\n판매장을 만들면……?\n힛. 힛. 히."
20052-60 = "사실 요즘 텍스트는\n플랫폼 장사에 가깝죠."
20052-70 = "여기 일일 수익은\n얼마나 되려나요……?"
20052-80 = "이야~ 오셨군요,\n선생님."
20052-90 = "목 빠지게\n기다리고 있었다니까요."
20052-100 = "그러면 지금부터\n출판부와 샬레 사이의"
20052-110 = "새로운 사업에 관한\n논의를 시작해 볼까요?\n힛. 힛. 히."
20052-120 = "기다리고 있었습니다,\n선생님!"
20052-130 = "기다리는 사이에,\n샬레에는 어떤 책이\n더 필요할지"
20052-140 = "나름대로 리스트를\n작성해 보았는데,"
20052-150 = "……문의 주신다면,\n금방 가져오도록 하죠.\n힛. 힛. 히."
20052-160 = "사업 계획서 작성은,\n제 취미 같은 거죠, 네."
20052-170 = "별나다고요?\n그렇게 볼 수도 있겠지만……"
20052-180 = "가능성을 생각하는 걸\n좋아해서요."
20052-190 = "생각나는 대로\n적어나가는 건\n의외로 즐겁다구요?"
20052-200 = "……그건 기획서가 아니라\n망상 노트라고요?"
20052-210 = "무슨 소리세요!\n망상 노트랑은 다르다구요!"
20052-220 = "어디가 다르냐면……\n그러니까, 그게……"
20052-230 = "사무국과\n예산 협상을 하는 건,\n언제나 어려운 일이죠……"
20052-240 = "하지만…… 최종적으로\n예산을 확보하기만 하면 \n되는 것 아니겠습니까."
20052-250 = "모자란 부분은 출판부의\n사업적 역량으로 돌파한 다음!"
20052-260 = "……다시 그만큼을\n사무국에 청구하면, \n두 배로 벌 수 있다는 겁니다.\n힛. 힛. 히."
20052-270 = "샬레까지 오는 길에\n여러 교통편을\n이용했습니다만."
20052-280 = "역시 이 근처의\n철도 시설은 부럽네요……"
20052-290 = "사실 부러운 건\n그게 전부가\n아니긴 하지만요……"
20052-300 = "요즘 출판업계는\n조~금 힘들어서 말이죠."
20052-310 = "특히 텍스트는 영상 매체에\n밀려나고 있기도 하고요."
20052-320 = "그래서, 결론 내렸습니다."
20052-330 = "출판부가 영상 매체까지\n흡수해 버리면 된다고 말이죠!"
20052-340 = "아~아.\n이건 진심인데요."
20052-350 = "샬레로 전학하러\n와 버리고 싶네요."
20052-360 = "따듯하고,\n시설 관리 잘 돼 있고, \n사업거리도 많고.\n선생님도 계시고."
20052-370 = "샬레는 학교가\n아니라서 안 된다고요?"
20052-380 = "네…… 현실은 언제나\n이렇게 차가운 법이죠……"
20052-390 = "이게 누구야,\n오늘의 주인공 아닙니까."
20052-400 = "생일 축하드립니다, 선생님.\n저로부터 작은 선물을 하나."
20052-410 = "자, 도서권입니다.\n……이용을 기다리고\n있을 테니까 말이죠.\n힛. 힛. 히."
20052-420 = "오늘은 5월 18일인데요~?"
20052-430 = "잊고 계신 거 없으신가요~?\n뭔가 저한테\n말할 거 없으신가요?"
20052-440 = "역시 선생님!\n제 생일 기억해 주실 줄\n알았다니까요!"
20052-450 = "새해로군요. 으음……"
20052-460 = "대부분의 사업에서는\n새해마다 뭔가 이벤트를\n기획하는데요."
20052-470 = "이거, 일종의\n딜레마란 말이죠……"
20052-480 = "모두가 하기 때문에\n큰 효과는 없지만,"
20052-490 = "안 하면\n뒤처지는 그런 거……"
20052-500 = "크리스마스 앞뒤가\n사업의 대목이라고 하죠!"
20052-510 = "그런 때일수록 뭐든\n내놓으면 팔릴 거라는,"
20052-520 = "안일하고 밋밋한 기획이\n사업을 망치는 법이지만요."
20052-530 = "오늘은 할로윈이구만요."
20052-540 = "그런데 참, 선생님과\n만나고 나서부터 든\n의문인데요."
20052-550 = "선생님에게\n사탕을 받는 것과,\n선생님에게\n장난을 칠 권리를 얻는 것."
20052-560 = "어느 쪽이 이득이려나요~?"
20052-580 = "오오…… 왠지 포근하네요."
20052-590 = "나름 기분이\n좋은 것 같기도……"
20052-600 = "그렇게 말하자마자\n추워졌습니다."
20052-610 = "엣취!"
20052-620 = "다 되었나요?\n그러면 이제,\n선생님도 하시죠."
20052-630 = "어라, 이거 저에게만\n시킬 생각이셨나요?"
20052-640 = "저런, 저런. 그건\n너무 안일하다고\n생각하는데요, 선생님?"
20052-650 = "붉은겨울의 추위는,\n모두에게 공평한\n법이니까 말이죠?\n힛. 힛. 히."
20052-2600 = "도구는 쓰기 나름이라고 하잖습니까?\n이걸로 계약을 보다 '확실하게'\n지키도록 할 수 있겠네요.\n힛. 힛. 히."
