[translation]
20051-10 = "Blue! Archive!!!"
20051-20 = "I'm here, I'm here again! Uzawa Reisa, this time as a magical girl!"
20051-30 = "Th-There's so many people again today..."
20051-40 = "A-Act as natural as possible..."
20051-50 = "(Ah, I know that too!)"
20051-60 = "Everyone seems to be having fun!"
20051-70 = "(Aaah... My spot...)"
20051-80 = "Fufu, you're late, Sensei. No, please don't feel bad!"
20051-90 = "Because justice arrives faster than anyone else!"
20051-100 = "Please put Uzawa Reisa from the Vigilante Crew out of your mind..."
20051-110 = "Today, I am...Uzawa Reisa from the Supreme Magical Vigilante Crew!"
20051-120 = "I've come to answer your call...!"
20051-130 = "Thermite Pink has arrived!"
20051-140 = "What if the Vigilante Crew had a uniform?"
20051-150 = "And it was something cool like this one!"
20051-160 = "Bolt forward! Thermite Pink!"
20051-170 = "Ah! Hello, Sensei! I was practicing my lines..."
20051-180 = "Sensei, do you know the famous line from Magicaliber, season 3, episode 4?"
20051-190 = "They say, \"The hotter the friendship, the hotter the firepower!\" It's such a good quote!"
20051-200 = "I wish I had something to nibble on... Right!"
20051-210 = "Do you want, like, bread or anything, Sensei?"
20051-220 = "Sensei, happy birthday!"
20051-230 = "If I had actual magical powers, I would cast blessing magic on you! Heehee!"
20051-240 = "Birthday? Whose? Ah! Mine!"
20051-250 = "Thank you for celebrating my birthday! Heehee."
20051-260 = "Sensei, Happy New Year! May this year also be full of justice!"
20051-270 = "Magical Christmas!"
20051-280 = "Ah! It was \"merry,\" not \"magical\"!"
20051-290 = "Trick or magic! Happy Halloween!"
20051-300 = "My witch costume? No! I'm a magical girl!"
20051-310 = "Aren't witches and magical girls completely different things?"
20051-330 = "Safe!"
20051-340 = "Fufu... And the kite's peace has been preserved!"
20051-350 = "Just before it fell into the water! I caught it!"
20051-360 = "The Vigilante Crew never hesitates to help another!"
20051-370 = "Fire or water, wherever it may be, we'll jump in!"
20051-380 = "Eheehee..."
20051-390 = "A hero's outfit..."
20051-400 = "...only shines when doing a hero's work!"
20051-410 = "Also, this outfit is machine washable!"
20051-420 = "And I...learned something from you."
20051-430 = "That only those who act can protect the innocent! Eheehee!"
20051-440 = "Heehee, a-a... Achoo!!!"
20051-450 = "Ugh..."
20051-2600 = "Sensei, you're always so nice to me... When we're together like this...I feel like the strongest!"
