[translation]
23000-20 = "真高興能見到你，老師～\n老師喜歡哪種冰淇淋呢？"
23000-30 = "嗯～\n要吃什麼呢…"
23000-40 = "今天果然也要\n草莓＆薄荷～"
23000-50 = "冰～冰～\n冰淇淋～"
23000-60 = "放學後\n當然要吃甜點！"
23000-70 = "草莓和薄荷最棒了！"
23000-80 = "老師～歡迎回來。\n今天也會一起\n去吃甜點吧？"
23000-90 = "老師，你遲到了唷～"
23000-100 = "一起去買\n冰淇淋吃吧！"
23000-110 = "啦啦～\n最喜歡吃甜的了～"
23000-120 = "老師也喜歡吃\n冰淇淋吧？對吧？"
23000-130 = "放學後\n是甜點時間～"
23000-140 = "為了美味的甜點～\n今天也要一起加油吧！"
23000-150 = "嗯？老師，\n你的表情看起來\n有什麼煩惱呢。"
23000-160 = "這種時候就，來吧來吧！\n去吃好吃的甜點！\n一起去吧！"
23000-170 = "老師！\n祝你生日快樂！"
23000-180 = "我特別預約了\n好吃的甜點店唷！"
23000-190 = "來，快走吧！老師！"
23000-200 = "老師～\n今天是我的生日！\n一起去吃冰淇淋吧！"
23000-210 = "嗯？\n禮物嗎？"
23000-220 = "沒關係的～\n老師就是我的禮物！"
23000-230 = "老師～\n新年快樂～"
23000-240 = "今年也為了美味的甜點！\n一起加油吧～"
23000-250 = "哇～老師～！\n是聖誕節唷！"
23000-260 = "這種日子果然\n很適合吃冰淇淋呢！\n要不要一起去買呀？"
23000-270 = "嘿嘿，\n今天是萬聖節呢。"
23000-280 = "要不要一起Cosplay成妖怪\n去要甜食呢？"
23000-290 = "Trick or Treat～"
23000-310 = "謝謝你連我的份也買了，\n老師。"
23000-320 = "啊，好甜好好吃！"
23000-330 = "不在咖啡廳，而是\n在戶外吃的冰淇淋，\n感覺好像很久違了。"
23000-340 = "而且還是跟老師一起。\n耶嘿嘿。"
23000-350 = "不，不會，\n我完全不介意。"
23000-360 = "我反而覺得很懷念、很開心。"
23000-370 = "真的很開心，而且……"
23000-380 = "該怎麼說呢…\n四周也沒什麼人…"
23000-390 = "該說是，\n心臟砰怦跳個不停嗎…"
23000-400 = "……沒，沒事，\n什麼都沒有！"
23000-410 = "請忘記我剛剛說的話吧！"
23000-420 = "哈哈，啊哈哈……"
23000-430 = "……非常感謝，\n老師。"
23000-440 = "今天也託老師的福，\n度過了幸福的一天。"
23000-2600 = "這個武器是……\n謝謝你，老師。\n雖然變強這件事讓我有點害怕……\n但是和老師一起的話，就沒問題了！"
