[translation]
23003-20 = "ยินดีที่ได้รู้จัก\nฉันจะแสดงพลังแห่งมิลเลเนียมให้ดูเอง"
23003-30 = "เราทำให้มีแต่\nเครื่องดื่มชูกำลัง\nออกมาจากตู้กดน้ำได้มั้ยนะ?"
23003-40 = "อืม...\nเรามานอนพักสักงีบ\nแล้วค่อยทำต่อดีมั้ย?"
23003-50 = "ช่วงนี้ร่างกาย\nต้องการน้ำตาลน่ะ..."
23003-60 = "ต้องซ่อมตรงนี้\nแล้วก็ปรับตรงนี้อีกหน่อย...\nเอาล่ะ มาเริ่มสร้างกันเลย!"
23003-70 = "ว่าไงนะ...?\nฉันกำลังทำอะไรอยู่น่ะเหรอ?\nกำลังเล่นเกมที่เพิ่งเปิดตัวน่ะ"
23003-80 = "หวัดดีคุณครู\nดื่มกาแฟกันสักแก้วมั้ย?"
23003-90 = "มาแล้วเหรอ?\nมาเร็วกว่าที่คิดไว้\nตั้ง 43 วินาทีแน่ะ!"
23003-100 = "เห็นฉันเงียบๆ แบบนี้\nแต่ก็เล่นเกมเก่งนะ"
23003-110 = "คุณครูลองมาแข่งกับฉันมั้ยล่ะ?"
23003-120 = "โกงงั้นเหรอ...?"
23003-130 = "ถึงฉันจะเป็นแฮ็กเกอร์\nแต่ก็ไม่แฮ็กเกมหรอกนะ"
23003-140 = "ทำไมถึงคิดว่าแฮ็กเกอร์\nคือพวกที่ชอบโกงล่ะ?"
23003-150 = "ฉันแฮ็กเพราะอยาก\nเข้าถึงความรู้ต่างหาก"
23003-160 = "ประโยคนี้กินใจชะมัด"
23003-170 = "น้ำอัดลมหวานๆ\nคือเครื่องดื่มของคนฉลาด"
23003-180 = "สุขสันต์วันเกิดนะคุณครู"
23003-190 = "วันนี้คุณครูจะได้รับการคุ้มครองจากฉัน\nทำให้ไม่เจอบั๊กในการเขียนโค้ด 1 วัน!"
23003-200 = "อืม... พายราสเบอร์รี่ที่ฉันพูดถึง\nไม่ใช่อันนี้สักหน่อย..."
23003-210 = "แต่ก็ขอบคุณนะที่จำวันเกิดของฉันได้"
23003-220 = "สวัสดีโลกใบใหม่!"
23003-230 = "รู้อะไรมั้ยคุณครู?"
23003-240 = "ใน 1 ปีจะมีอยู่ \"อย่างนึง\"\nที่สำเร็จได้ในวันคริสต์มาส"
23003-250 = "ฮุฮุ สิ่งนั้นก็คือ...\nการแฮ็กไงล่ะ!"
23003-260 = "ทำไมฉันถึงไม่ออกไปสนุก\nกับบรรยากาศข้างนอกน่ะเหรอ?"
23003-270 = "ฉันก็สนุกกับฮาโลวีน\nผ่านทางมอนิเตอร์ก็ได้นี่"
23003-290 = "เฮ้อ...\nอยู่ๆ ฝนก็มาตกซะได้"
23003-300 = "ช่วงนี้ไว้ใจพยากรณ์อากาศ\nไม่ได้เลย ลำบากจริงๆ"
23003-310 = "งั้นตอนนี้จะทำอะไรกันดี?"
23003-320 = "(อืม... ที่เราพูดไปเมื่อกี้\nมันฟังดูแปลกๆ หรือเปล่านะ?)"
23003-330 = "(แต่ว่านี่เป็นครั้งแรกที่ได้มาร้านเน็ตแบบนี้\nใครจะไปรู้ล่ะว่าเค้ามาทำอะไรกัน...)"
23003-340 = "(อีกอย่างที่นี่มันก็แคบมาก...\nแล้วหน้าคุณครูก็ใกล้มากด้วย...)"
23003-350 = "หืม? จะไปอาบน้ำงั้นเหรอ?\nเดี๋ยวก่อน! คิดจะทำอะไรน่ะ?!"
23003-360 = "อ๋อ... เมื่อกี้โดนฝนเลยจะไป\nสระผมก่อนงั้นเหรอ?\nโทษที ไม่สิ ไม่ต้องใส่ใจหรอก"
23003-370 = "ในร้านเน็ตแบบนี้\nมีห้องอาบน้ำด้วยเหรอเนี่ย?"
23003-380 = "ดูนี่สิคุณครู เครื่องดื่มที่บาร์ฟรีด้วยล่ะ\nจะมีเครื่องดื่มชูกำลังมั้ยนะ?"
23003-390 = "ให้ใช้เน็ตได้ตามใจ\nแถมยังให้เครื่องดื่มฟรีอีก\nสุดยอดเลยนะ ที่นี่เหมาะกับ\nคนอย่างฉันที่สุดเลย ว่ามั้ยล่ะ?"
23003-400 = "ถ้าเป็นที่นี่ละก็\nจะอยู่นานแค่ไหนก็ได้"
23003-410 = "อ๊ะ... ฉันไม่ได้หมายถึง\nอะไรแปลกๆ หรอกนะ\nอย่าเข้าใจผิดซะล่ะ..."
23003-2600 = "ถึงจะเป็นอาวุธเก่า... แต่ว่าอาวุธนี่...\nก็เต็มไปด้วยความทรงจำที่ประเมินค่าไม่ได้"
