[translation]
26007-10 = "蔚藍檔案！"
26007-20 = "我，我是奧空綾音。\n怎，怎麼樣呢…這種穿著，\n有點害羞呢。"
26007-30 = "穿，穿成這樣在這裡，\n有點害羞呢…"
26007-40 = "咦，\n大家在哪裡…？"
26007-50 = "有沒有可以\n悠哉的地方…"
26007-60 = "嗯…？\n那是什麼呢…？"
26007-70 = "總覺得，\n變得開心起來了呢"
26007-80 = "啊，歡迎回來，老師！"
26007-90 = "老師，等您很久了。"
26007-100 = "那個…\n怎，怎麼了嗎…？"
26007-110 = "這，這個模樣嗎？"
26007-120 = "那，那個…\n想展現看看\n夏天的感覺…"
26007-130 = "怎，怎麼樣呢？\n適，適合我嗎…？"
26007-140 = "必須做那個，\n必須做這個，\n因為總是這麼想著…"
26007-150 = "總覺得這種\n悠閒的時光，\n很不可思議。"
26007-160 = "穿成這樣的話，\n總覺得\n會放鬆下來呢。"
26007-170 = "祝您生日快樂，老師！"
26007-180 = "和老師相遇，\n像這樣悠閒度過\n我真的很開心。"
26007-190 = "老，老師…那個…\n今，今天是，那個…"
26007-200 = "啊……非常謝謝您。\n光是像這樣在一起就很開心了，\n竟然連生日都讓老師慶祝……"
26007-210 = "真是奢侈的一天。"
26007-220 = "祝您新年快樂！"
26007-230 = "希望今年，也有很多\n開心的事！"
26007-240 = "聖誕快樂！\n不，不給一點反應的話\n很害羞…"
26007-250 = "原來如此，因為是萬聖節\n所以大家才變裝…"
26007-260 = "啊，不，我的這個是\n並不是那個意思…！？"
26007-280 = "那個，我只要，\n站在這旁邊\n就可以了嗎…？"
26007-290 = "像這樣，\n可以嗎…？"
26007-300 = "要，要怎麼做，\n才能更加強調直升機呢…？"
26007-310 = "對不起，\n我不太習慣做這種事…"
26007-320 = "那個…老師？\n既然是修理紀念照的話…"
26007-330 = "還是以直升機為中心來拍\n比較好吧…？"
26007-340 = "…咦，不是直升機，\n而是我的紀念照…？"
26007-350 = "原，原來是這樣嗎！？\n咦咦！？"
26007-360 = "這，這樣有點，不，\n我並不討厭…！"
26007-370 = "只，只是突然，\n覺得臉好燙…"
26007-2600 = "這麼厲害的東西，要給我……\n我總是從老師手中收到各種東西呢。\n為了盡可能地報答您，我會繼續努力！"
