[translation]
26006-20 = "망원경 너머로만 지켜보던\n그 선생님이 맞으신가요…?\n저, 감격했어요…!"
26006-30 = "후후,\n멋진 가구 발견!"
26006-40 = "저 너머에는\n뭐가 있으려나…?"
26006-50 = "빨리 특별반에서\n도망치지 않으면…"
26006-60 = "이곳의 풍경은\n아름답네요~"
26006-70 = "선생님은…\n어디 계시려나?"
26006-80 = "금방 돌아오실 줄 알았어요!"
26006-90 = "줄곧…\n지켜보고 있었거든요!"
26006-100 = "어라?\n선생님이 방금 전까지 여기에…"
26006-110 = "우앗, 깜짝이야!\n어, 언제 오셨나요?\n가, 가, 감시하고\n있었던 건 아녜요!"
26006-120 = "하아, 하아…\n역시 선생님을 지켜보는 게\n가장 즐겁네요."
26006-130 = "후후…\n선생님의 얼굴은 아무리 봐도\n질리지가 않아요!"
26006-140 = "웃…\n아무한테나 하악대는 게\n아니거든요?"
26006-150 = "이 드넓은 우주를\n보고 있노라면…"
26006-160 = "사람의 삶이란\n참으로 덧없는 것임을\n새삼 느끼네요."
26006-170 = "후후, 언젠가 선생님과 함께\n밤하늘을 같이 관찰하러\n가면 좋겠네요."
26006-180 = "생신 축하드려요,\n선생님!"
26006-190 = "오늘 하루는 나쁜 일이\n생기지 않도록 제가 열심히\n지켜봐 드릴게요!"
26006-200 = "선생님, 그거 아세요?\n제 생일날에 밤하늘을\n올려다보면"
26006-210 = "사이좋은 쌍둥이 별이\n남쪽 하늘을 지나가는 것을\n볼 수 있답니다.\n그날이 바로…"
26006-220 = "오늘이에요!"
26006-230 = "올해는 꼭,\n여기에서 벗어나\n본교사로 돌아가기를…"
26006-240 = "크리스마스의 야경은\n멀리서 바라보면"
26006-250 = "밤하늘처럼 반짝거려서\n예쁘답니다."
26006-260 = "이번 할로윈에는\n과연 저희한테도\n사탕이 보급될까요…"
26006-280 = "어머나, 별똥별이에요!\n앗… 저기도! 또 저기도!"
26006-290 = "하늘에 별똥별이 가득해요!\n정말 유성이 비처럼 내리네요!"
26006-300 = "이렇게 아름다운 광경을\n직접 눈으로 볼 수 있다니…\n정말 꿈만 같네요."
26006-310 = "소원이요?"
26006-320 = "아니…\n오늘은 괜찮아요."
26006-330 = "좋아하는 사람과\n아름다운 광경을\n함께 지켜볼 수 있는데,"
26006-340 = "여기서 더한 소원을 빌면\n어쩐지 별님에게\n혼이 날 것 같아서…"
26006-350 = "오늘은 이것으로\n만족할래요."
26006-2600 = "감사합니다, 선생님!\n이 망원경만큼이나\n소중하게 다룰게요!"
