[translation]
26009-10 = "블루…… 아카이브……"
26009-20 = "하나오카 유즈…… 예요.\n사정이 있어서… 지금은 이 모습을 하고 있어요.\n잘, 부탁드립니다……"
26009-30 = "지금의 나는 메이드니까...\n청소라도 해볼까…"
26009-40 = "게임을 만드는\n메이드…… 새로울지도?"
26009-50 = "으으……\n어디론가 숨고 싶어……"
26009-60 = "골판지 상자는……\n잠입의 필수품인데……"
26009-70 = "어서 오세요, 주인님.\n으으, 역시 부끄러워……."
26009-80 = "히얏!? 누, 누구!?"
26009-90 = "아, 선생님이셨군요.\n다행이다…… 어서 오세요."
26009-100 = "선생님, 기다리고 있었어요……"
26009-110 = "와 주셔서 기뻐요."
26009-120 = "청소는 그다지\n잘하지 못합니다만……"
26009-130 = "선생님의, 부탁이라면……"
26009-140 = "네? 어울린다구요?"
26009-150 = "정말…… 놀리지 마세요!"
26009-160 = "…본, 본심이라고 하시면,\n그건 그것대로……."
26009-170 = "왜 고양이 귀는\n메이드복에 어울릴까요?"
26009-180 = "고양이는 메이드라기보다\n주인님 쪽인 것 같은데……"
26009-190 = "이건……\n게임에 참고가 될지도."
26009-200 = "이 옷, 프릴이 많아서……\n부끄러워……"
26009-210 = "생, 생일 축하드려요, 주인님."
26009-220 = "한번 해봤어요……\n메이드니까요."
26009-230 = "생일, 기억해 주신 건가요?\n감사합니다."
26009-240 = "저기…… 특별히\n아무것도 하지 않아도, 괜찮아요."
26009-250 = "선생님…… 아니,\n주인님과 함께 있는 것이\n가장 큰 행복이니까요."
26009-260 = "이, 일단은 그런 설정이에요……!"
26009-270 = "새해 복 많이 받으세요, 주인님."
26009-280 = "……여, 역시 선생님이라고\n부르는 편이 좋을까요?"
26009-290 = "산타 할아버지는 굴뚝을\n통해서 오신다고 해요……"
26009-300 = "게임개발부에\n굴뚝은 없지만요……"
26009-310 = "기회가 된다면\n한번 들어가보고 싶어요."
26009-320 = "아담하고,\n아늑할 것 같아요……"
26009-330 = "할로윈……"
26009-340 = "할로윈 복장을 입은 사람들이 \n거리에 넘쳐나는 축제네요."
26009-350 = "저와는 관계가 없다고나 할까요……"
26009-360 = "게임 이벤트라면……\n자주 하지만요."
26009-380 = "저기, 그러니까……"
26009-390 = "자고 있는 사이에,\n들어와 버린 것 같아서……"
26009-400 = "그게…… 휴게실에는\n다른 분들도 계시니까……"
26009-410 = "앉아 있으면,\n말을 걸어오셔서……"
26009-420 = "'리본은 어디서 샀어?' 라던가, "
26009-430 = "'쉬는 날에는 뭐해?' 라던가……"
26009-440 = "여러 질문을 받는 사이에,\n무심코 도망쳐 버려서…"
26009-450 = "발견한 곳이,\n여기였어요……"
26009-460 = "설마……\n고양이 휴게소였다니……"
26009-470 = "히얏……?!\n자, 잠깐만 기다려 주세요!"
26009-480 = "나갈게요!\n지, 지금 나갈 테니까……\n간지러워요!"
26009-2600 = "이, 이렇게까지 해주시다니……\n그런…… 굉장히 기뻐요.\n……저, 더 열심히 할게요.\n……지켜봐 주세요, 선생님!"
