[translation]
26006-20 = "Are you the one that I've been watching through my telescope? Ooh, I'm so excited!"
26006-30 = "Heehee. I found some cool furniture!"
26006-40 = "I wonder what's beyond..."
26006-50 = "If I don't escape from the Spec Ops..."
26006-60 = "The view here is spectacular!"
26006-70 = "I wonder where Sensei is...?"
26006-80 = "I knew you'd be back soon!"
26006-90 = "I was... I was watching you!"
26006-100 = "Huh? But Sensei was here just now..."
26006-110 = "Ah! You scared me! When did you get here? I wasn't watching you!"
26006-120 = "*pant* *pant* ...I have the most fun when I'm watching you, Sensei."
26006-130 = "I never get sick of your face no matter how many times I look at it!"
26006-140 = "Ugh... You're not supposed to be like that with other people."
26006-150 = "When you're looking out at this big wide world..."
26006-160 = "...you realize that we're all so insignificant."
26006-170 = "I hope you and I can go stargazing one of these days."
26006-180 = "Happy birthday, Sensei!"
26006-190 = "I'll be watching to make sure nothing bad happens to you today!"
26006-200 = "Did you know, Sensei? If you look up at the stars on my birthday..."
26006-210 = "...you can see a pair of stars flying across the southern skies. That day is..."
26006-220 = "...today!"
26006-230 = "This year,I'm gonna get out of this place and go back to the main institute."
26006-240 = "If you look up at the night sky from far below on Christmas..."
26006-250 = "...all the stars shine so beautifully."
26006-260 = "I wonder if I'll get any candy this Halloween..."
26006-280 = "Wow, it's a shooting star! Oh... Over there! And over there!"
26006-290 = "The sky is full of shooting stars! Meteors are falling like rain!"
26006-300 = "I can't believe I'm seeing this with my own two eyes... It's like a dream."
26006-310 = "A wish?"
26006-320 = "No... I'm okay for today."
26006-330 = "I'm content enjoying this beautiful view with someone important..."
26006-340 = "If I wish for something more, the stars might grow angry with me..."
26006-350 = "I'm totally satisfied for now."
26006-2600 = "Thank you, Sensei! I'll treat it as preciously as this telescope!"
