[translation]
26005-20 = "작다고 얕보지 마!\n내 가능성은 엄청나게 크니까!"
26005-30 = "나의 성장판은 아직…\n끝나지 않았어! 믿어!"
26005-40 = "히힛.\n한숨 푹 자고 갈까나."
26005-50 = "하아… 선생님은\n왜 그렇게 눈치가 없는 걸까."
26005-60 = "맛있는 디저트가\n먹고 싶어!\n와앗! 선생님이다!"
26005-70 = "히잉. 흰 우유는 싫어.\n먹어야 된다는 점이\n특히 말야!\n응? 따, 딸기 우유라고?"
26005-80 = "머리 쓰다 듬지마아-!\n칫… 어린애 취급은 싫단말야."
26005-90 = "나도… 몇 년만 지나면…\n동생이 아니라 연인처럼 보일까?"
26005-100 = "우유라면 1L씩 마시고 있어.\n매일매일매일 말야!"
26005-110 = "다, 당번을 하면, 선생님과\n맛있는 과자를 먹는 시간도 있는 거지?"
26005-120 = "오늘도 열심히 해봐!\n내가 도와줄 테니까!"
26005-130 = "어라?\n선생님 안색이 안 좋은데?"
26005-140 = "마, 맛있는 디저트라도 먹으러 갈래?"
26005-150 = "흥! 내가 있는 이상\n농땡이 칠 계획은 포기하라구!\n자! 일할 시간이야! 임무를 시작하자!"
26005-160 = "생일 축하해 선생님!\n근처에 괜찮은 스위츠가 있어. 가자!"
26005-170 = "추, 축하해줘서 고마워."
26005-180 = "(몇 번의 생일이 지나야…\n곁에 있을 때, 어울린다는\n말을 들을 수 있을까?)"
26005-190 = "벼, 별로 아무 생각 안 했거든?\n왜 뚫어지게 쳐다보는 거야?!"
26005-200 = "새해 복 많이 받아!\n올해의 목표? 뻔하잖아!\n나이스 바디가 되는 거지!!"
26005-210 = "메리 크리스마스!\n나는 크리스마스가 좋아!\n내가 좋아하는 색이\n거리에 가득해지니까!"
26005-220 = "Trick or Treat~\n방과후 디저트부에게는\n더욱 특별한 할로윈이야!\n나가자!"
26005-230 = "유령에는 관심 없지만,\n사탕은 중요한 거니까!"
26005-250 = "정말이지, 선생님 때문에\n매번 놀란다고 해야 할까……."
26005-260 = "휘둘린다고\n해야 할까……."
26005-270 = "…응? 뭘 그렇게\n빤히 보는 거야?"
26005-280 = "저기, 설마 또\n이상한 생각 하고 있는 건\n아니겠지?"
26005-290 = "난 선생님의\n장난감이 아니라고."
26005-300 = "적당히 하지 않으면\n진짜로 화 낼 거야."
26005-310 = "…아니, 뭐. 그렇게까지\n싫다는 건 아니지만…"
26005-320 = "후후."
26005-330 = "(언젠가는…)"
26005-340 = "(언젠가는 이렇게 옆에서…….\n나란히 걷는 날도\n오지 않을까…?)"
26005-2600 = "이런 거 받아버리면…\n진심으로 노력할 수밖에 없잖아!"
