[translation]
26003-20 = "คนที่ได้รับบาดเจ็บอยู่ที่ไหนเหรอคะ?\nฉันจะไปดูแลเองค่ะ"
26003-30 = "ที่นี่มีใครได้รับบาดเจ็บมั้ยคะ?"
26003-40 = "แค่ได้เห็นที่นี่\nก็ทำให้รู้สึกอบอุ่นใจ\nขึ้นมากเลยค่ะ"
26003-50 = "ถ้าเป็นที่แบบนี้ล่ะก็\nผู้ป่วยจะต้องพักฟื้น\nแล้วหายได้เร็วแน่เลยค่ะ"
26003-60 = "บางครั้งได้สนุกกับเวลาว่างแบบนี้\nก็ไม่แย่เท่าไหร่นะคะ"
26003-70 = "อ่า... ประกายสีชมพูแสนสวย..."
26003-80 = "เชิญค่ะคุณครู\nวันนี้รู้สึกยังไงบ้างคะ?"
26003-90 = "ฉันกำลังรอคุณครูอยู่เลยค่ะ\nวันนี้เราก็มาพยายาม\nเพื่อโลกที่สงบสุขด้วยกันเถอะนะคะ!"
26003-100 = "อ๊ะ คนไข้คนใหม่หรือเปล่าคะเนี่ย?"
26003-110 = "ดูเหนื่อยมากเลยนะคะ...\nให้ฉันนวดไหล่ให้มั้ยคะ?"
26003-120 = "ความเหนื่อยล้าทำให้ล้มป่วยได้นะ\nอย่าฝืนเกินไปเลยนะคะ"
26003-130 = "พอคิดถึงคนป่วยแล้ว\nฉันมักจะรู้สึกเห็นใจพวกเขาค่ะ"
26003-140 = "ฉันจะไม่ยกโทษให้คนที่\nทำลายความสงบสุขเด็ดขาด!"
26003-150 = "สุขสันต์วันเกิดค่ะคุณครู!\nวันนี้ขอให้เป็นวันที่\nมีแต่ความสุขมากๆ นะคะ!"
26003-160 = "ขอบคุณที่อวยพรวันเกิดให้ฉันค่ะ\n...ของขวัญวันเกิดเหรอคะ?"
26003-170 = "แค่รอยยิ้มของคุณครูก็พอแล้วค่ะ!"
26003-180 = "ขอให้มีความสุขมากๆ ในวันปีใหม่\nนะคะ ใส่เสื้อผ้าหนาๆ ด้วยนะคะ\nจะได้ไม่เป็นหวัดรับปีใหม่ค่ะ!"
26003-190 = "เมอร์รี คริสต์มาสค่ะ คุณครู\nถ้าวันนี้ไม่มีการต่อสู้กัน\nและเป็นวันที่สงบๆ ได้ก็คงจะดีนะคะ"
26003-200 = "ฉันได้ลูกกวาดฮาโลวีน\nเป็นของขวัญมาด้วยค่ะ!"
26003-210 = "ลูกกวาดหวานอร่อยก็จริง...\nแต่ถ้ากินเยอะเกินไป\nก็จะทำให้ฟันผุได้นะคะ"
26003-230 = "จริงๆ เลยนะคะ คุณครูเนี่ย..."
26003-240 = "ตกใจจนพูดอะไรไม่ออกเลยละค่ะ"
26003-250 = "เพิ่งเคยรู้สึกแบบนี้เลยค่ะ"
26003-260 = "ฉันเพิ่งเคยได้รับอะไรแบบนี้ครั้งแรก\nต้องบอกว่ารู้สึกตกใจ\nนิดหน่อยละมั้ง..."
26003-270 = "จริงๆ เลย..."
26003-280 = "เพิ่งเคยเจอคนแบบนี้\nเป็นครั้งแรกเลยค่ะ"
26003-290 = "ขอโทษด้วยนะคะ เมื่อกี้...\nฉันยังไม่ค่อยมีสติเท่าไร..."
26003-300 = "ขอบคุณค่ะ\nฉันดีใจมากๆ เลยค่ะ!"
26003-310 = "เพราะคุณครูเลยนะคะ..."
26003-320 = "ฉันรู้สึกแบบนี้...\nเพราะคุณครูเลยค่ะ"
26003-2600 = "จะวิ่งหนีไป\nเพราะบอกว่าฉีดยาเจ็บไม่ได้นะคะ!"
