[translation]
26003-20 = "Is anyone in need of first aid? I would be happy to help."
26003-30 = "Does anyone need first aid?"
26003-40 = "It warms my heart just looking at this place."
26003-50 = "A patient would be able to make a speedy recovery in a place like this."
26003-60 = "I don't think it's a bad thing to relax like this every now and then."
26003-70 = "Oh... What a beautiful shade of pink."
26003-80 = "Welcome, Sensei. How are you feeling today?"
26003-90 = "I've been waiting for you, Sensei. As always, let's work toward creating a peaceful world together!"
26003-100 = "Oh, a new patient?"
26003-110 = "You look tired. Would you like me to massage your shoulders?"
26003-120 = "Fatigue is the root of many illnesses, so don't push yourself too hard."
26003-130 = "It always breaks my heart to think about the patients who are suffering."
26003-140 = "I can't forgive those who would trample on the peace we have!"
26003-150 = "Happy birthday, Sensei! I hope your day is filled with warmth and joy!"
26003-160 = "Thank you for remembering my birthday. Oh? A birthday gift?"
26003-170 = "Your smiling face is enough for me!"
26003-180 = "Happy New Year! Be sure to bundle up so you don't ring in the new year with a cold!"
26003-190 = "Merry Christmas, Sensei. Even if just for one day, I hope people can stop fighting and enjoy a wonderful peace."
26003-200 = "I got some Halloween candy!"
26003-210 = "I love sweets, but if I eat too many, I'll earn myself a trip to the dentist..."
26003-230 = "Honestly, Sensei..."
26003-240 = "I was just really surprised."
26003-250 = "I'm not sure how to react..."
26003-260 = "I've never received something like this... I feel a bit bashful about it. Is that normal?"
26003-270 = "Really..."
26003-280 = "I've never met anyone quite like you before."
26003-290 = "I'm sorry. To be honest, I'm at a loss for words..."
26003-300 = "All I can say is... Thank you! I'm so happy!"
26003-310 = "...I am truly grateful, Sensei."
26003-320 = "This feeling... It's all thanks to you."
26003-2600 = "Don't run away just because the shot hurts!"
