[translation]
26000-10 = "Blue Archive!"
26000-20 = "ถ้าคุณกลัวความลำบาก\nถ้าคุณกลัวความเลวร้าย\nฉันจะร่วมฝ่าฟันไปกับคุณเองค่ะ"
26000-30 = "คงจะต้องไปซื้อยา\nมาเก็บไว้เพิ่มแล้วล่ะ"
26000-40 = "อืม... ก็...\nไม่เลวเลยค่ะ"
26000-50 = "ดูสบายๆ ดีนะคะ"
26000-60 = "สุขอนามัยของที่นี่...\nดูดีเลยนะคะ"
26000-70 = "อุณหภูมิร่างกายปกติ\nชีพจรก็ปกติ\nอืม... แข็งแรงดีนะคะ"
26000-80 = "เชิญเลยค่ะคุณครู\nเอกสารที่รอให้คุณครูอนุมัติ\nจ่ายเงิน วางไว้ตรงนี้แล้วนะคะ"
26000-90 = "คณะกรรมการวินัยแค่ต้องการ\nความเป็นระเบียบเท่านั้นค่ะ\nชาเล่ต์เองก็เหมือนกันไม่ใช่เหรอคะ?"
26000-100 = "ฉันจะบอกความลับของฉันให้รู้นะ..."
26000-110 = "ฉันเองก็ไม่ชอบถูกฉีดยาหรอกค่ะ"
26000-120 = "ความซื่อบื้อมันรักษาไม่ได้หรอกนะ\nเรื่องแค่นี้ไม่รู้เหรอคะ?"
26000-130 = "คะ? อยากให้ฉันหัวเราะหน่อยเหรอคะ?"
26000-140 = "ได้อยู่นะคะ...\nถ้าอยู่กันแค่สองคน..."
26000-150 = "(ก่อนอื่นต้องทำให้สลบก่อน\nแล้วค่อยใส่เครื่องช่วยหายใจให้...)"
26000-160 = "(เรื่องนั้นไม่นับเหรอ...?)"
26000-170 = "คะ? ฉันคิดอะไรอยู่งั้นเหรอคะ?\nเอ่อ... ไม่มีอะไรหรอกค่ะ"
26000-180 = "สุขสันต์วันเกิดค่ะคุณครู\nวิตามินสำหรับฉีดอย่างดี\nเพิ่งส่งมาถึงเลยค่ะ"
26000-190 = "ถ้าพร้อมแล้วก็ถอดกางเกง..."
26000-200 = "เดี๋ยวค่ะ! ถอดแค่นิดเดียวก็พอ!"
26000-210 = "วันเกิดของฉันทั้งที\nวันนี้ฉันคงมีสิทธิ์ยึดคุณครู\nไว้เป็นของฉันคนเดียวสินะคะ"
26000-220 = "คุณครูช่วย... จับมือฉันหน่อยได้มั้ยคะ?"
26000-230 = "สุขสันต์วันปีใหม่นะคะ\nปีที่แล้วเกิดเรื่องวุ่นวายเยอะเลย..."
26000-240 = "แต่ก็เป็นปีที่ดี\nเพราะมีคุณครูอยู่ด้วยไงละคะ"
26000-250 = "ฉันชอบวันคริสต์มาสจัง\nมีสีแดงให้เห็นเยอะแยะเต็มไปหมดเลย\nคุณครูก็ชอบสีแดงด้วยมั้ยคะ?"
26000-260 = "ถึงจะพูดแบบนั้น...\nแต่ฉันก็ไม่ได้ชอบ\nสีเลือดหรอกนะคะ"
26000-270 = "ของสำหรับเรียกขวัญวันฮาโลวีนแบบนี้...\nเอาเป็นลูกกวาดดีมั้ยคะ?\nลูกอมชูการ์ฟรี ดีต่อสุขภาพนะคะ"
26000-290 = "ถะ...  ถึงฉัน... จะไม่ได้คาดการณ์\nถึงสถานการณ์นี้มาก่อน..."
26000-300 = "สถานการณ์แบบนี้ คือว่ามัน\nจะเรียกว่าล่อแหลมดีมั้ยคะ..."
26000-310 = "คือว่าคุณครูคะ...?\nถ้าคุณครูไม่พูดอะไรเลย\nคือว่า..."
26000-320 = "ถ้าคุณครูไม่พูดอะไรเลยแบบนี้\nบรรยากาศมันจะดูแปลกๆ..."
26000-330 = "เปล่าค่ะ... คือว่า...\nฉันไม่ได้อยากจะเร่งนะคะ...!\nคือ... ฉันไม่รู้ว่าควรพูดอะไรดี..."
26000-340 = "ในเวลาแบบนี้\nควรต้องทำยังไง..."
26000-350 = "เฮ้อ..."
26000-360 = "เปล่าค่ะ... ไม่เป็นไรค่ะ...\nค่ะ..."
26000-370 = "ฮุฮุ รู้สึกลำบากใจจังเลยค่ะ...\nจะว่ายังไงดีล่ะคะ แบบนี้น่ะ..."
26000-380 = "แค่ได้อยู่ด้วยกัน...\nกับคุณครูแบบนี้ รู้สึกว่า\nฉันไม่เป็นตัวเองเลย..."
26000-390 = "ฉัน... รู้สึกลำบากจริงๆ ค่ะ\nหลายๆ อย่างเลย…"
26000-2600 = "เรื่องที่เราจะต้องแข็งแกร่งขึ้น\nเพื่อที่จะรักษาคนให้ได้เยอะขึ้น\nเหมือนเรื่องตลกที่ขำไม่ออกเลยนะคะ\nแต่ถ้าเป็นเรื่องที่ฉันทำได้...\nฉันจะพยายามให้ถึงที่สุดค่ะ"
