[translation]
26006-20 = "是一直透過望遠鏡觀察的\n那個老師沒錯吧……？\n我非常感動……！"
26006-30 = "呵呵，\n發現了很棒的家具！"
26006-40 = "在另一邊\n會有什麼呢……？"
26006-50 = "得趕快離開\n特別班才行……"
26006-60 = "這裡真是\n漂亮的地方呢～"
26006-70 = "老師……\n在哪裡呢？"
26006-80 = "我就知道你很快就會回來！"
26006-90 = "因為我一直……\n一直都在守望著你！"
26006-100 = "咦？\n老師到剛才為止都在那裡…"
26006-110 = "哇啊，嚇，嚇我一跳！\n你，你什麼時候來的？\n沒，沒有，我沒有在監視你！"
26006-120 = "哈啊，哈啊……\n果然觀察老師\n最開心了。"
26006-130 = "呵呵……\n老師的臉\n不管怎麼看都不會膩呢！"
26006-140 = "唔……\n我可不是對任何人\n都會這樣的唷？"
26006-150 = "每當我看著\n這廣闊的宇宙……"
26006-160 = "都會讓我感受到\n人的一生\n是多麼的短暫而無常。"
26006-170 = "呵呵，希望有一天\n能和老師一起去觀察夜空呢。"
26006-180 = "祝你生日快樂，老師！"
26006-190 = "今天一整天，為了\n不讓不好的事情發生，\n我會好好守望著你的！"
26006-200 = "老師，你知道嗎？\n在我生日那天\n仰望夜空的話……"
26006-210 = "就能看到感情融洽的\n雙子星掠過南方的天空唷。\n那天居然就是……"
26006-220 = "今天！"
26006-230 = "希望今年\n能想辦法離開這裡，\n回到主校舍……"
26006-240 = "聖誕節的夜景，\n從遠處看的話……"
26006-250 = "就像夜空一樣\n閃閃發光，非常漂亮。"
26006-260 = "今年的萬聖節\n我們是否也能\n獲得補給的糖果呢……"
26006-280 = "唔哇，是流星！\n啊……那邊也有！\n那邊也有！"
26006-290 = "天空滿滿都是流星！\n流星真的像雨一樣落下了呢！"
26006-300 = "居然能親眼\n看到這麼漂亮的景象……\n真的好像作夢一樣。"
26006-310 = "願望嗎？"
26006-320 = "不用……\n今天，已經沒關係了。"
26006-330 = "可以和喜歡的人，\n一起仰望如此美麗的星空，"
26006-340 = "要是再許願的話，\n總覺得會被星星責罵……"
26006-350 = "今天光是這樣\n就很滿足了。"
26006-2600 = "謝謝你，老師！\n我會像這個望遠鏡一樣\n好好珍惜它的！"
