[translation]
26011-10 = "Blue Archive!"
26011-20 = "Hello, Sensei! I'm Saten Ruiko, a first-year student at Sakugawa Middle School! Pleased to meet you!"
26011-30 = "Oh, that's..."
26011-40 = "Whoa! This here! That's actually really amazing!"
26011-50 = "At first glance, it looks normal, but if you look closely, it's strange... How fun!"
26011-60 = "So this is what a cafe is like in another world..."
26011-70 = "I'm relieved. Heehee."
26011-80 = "Ah! Sensei, I've been waiting for you! What are you up to today?"
26011-90 = "Hello, Sensei! Is there anything I can do for you?"
26011-100 = "This world is so similar to my world, but it's also so different... It's interesting."
26011-110 = "Oh, you're going for a walk? ...I want to go too! Please take me along, Sensei!"
26011-120 = "From top to bottom, it sure is a funny world you've got here!"
26011-130 = "It may have been random chance, but I'm glad I'm here!"
26011-140 = "How about you, Sensei? Since we got here...are your days a little more fun?"
26011-150 = "Happy Birthday! I hope it's a great one, Sensei!"
26011-160 = "Is there anything you're wishing for?"
26011-170 = "Happy New Year, Sensei! Time sure does fly..."
26011-180 = "Thank you again this year, Sensei!"
26011-190 = "Do you have Christmas too?"
26011-200 = "In that case, will we get to see Santa fly across the sky?!"
26011-210 = "Halloween...! Sensei! We've got to—! C'mon, let's grab some costumes and get out there!"
26011-230 = "Well... It doesn't look that different from the other cages..."
26011-240 = "...Sensei, what's with the worried face? It's just a batting machine."
26011-250 = "Okay! Still, I'm sure I'll be fine."
26011-260 = "I'm pretty confident with a bat, after all."
26011-270 = "...And now you're giving me the most suspicious look."
26011-280 = "Why don't we make a bet?"
26011-290 = "If I don't hit the ball in three pitches, I'll step off the plate quietly."
26011-300 = "But if I hit even one ball, you've got to get me a drink from that vending machine!"
26011-310 = "What do you think? It's not a bad bet for you either, right?"
26011-320 = "...Heehee."
26011-2600 = "Is this...for me? It's a strange, strange feeling... Thank you. I-I'll do my best! ...I'm sorry, this is all I can say... Hahaha..."
