[translation]
9009001-10 = "ชะ...ชะ... เชิญเลยค่ะ!\nคุณครู!"
9009001-20 = "น่าเบื่อจัง...\nกะ...กรี๊ด!?\nมะ...มาตั้งแต่เมื่อไหร่คะ?"
9009001-30 = "เราเปิดตลอด 24 ชั่วโมง\nแวะมาได้ตลอดนะคะ\nที่นี่เป็นร้านสะดวกซื้อนี่นา"
9009001-40 = "ส่วนภารกิจ... คือว่า...\nนะ...หนูคิดว่าควรจะต้องเตรียมตัวให้พร้อมค่ะ!"
9009001-50 = "เพราะฉะนั้น... ซื้อไว้ให้พร้อม\nน่าจะดีกว่านะคะ! ถ้าซื้อของจากร้านของเรา\nยังไงก็มีประโยชน์อยู่แล้วค่ะ!"
9009001-60 = "คะ...คือว่า ถ้าจ้องกันแบบนั้น\nฉันรู้สึกกังวลนะคะ..."
9009001-70 = "อ๊ะ นะ...หน้าผาก\nอย่ามาแตะหน้าผากหนูนะ!"
9009001-80 = "บัตรของผู้ใหญ่...\nขะ...ขอดูหน่อยได้ไหมคะ?"
9009001-90 = "ตะ...แต่ว่าที่ร้านของเรา\nขายสินค้าในราคาย่อมเยานะคะ"
9009001-100 = "ขอบคุณมากค่ะ!"
9009001-110 = "แล้วแวะมาอีกนะคะ คุณครู"
