[translation]
9009001-10 = "어, 어, 어서 오세요!\n…선생님!"
9009001-20 = "심심해…\n…우, 우아아!?\n어, 언제 오셨어요?"
9009001-30 = "24시간! 언제든 방문해 주세요.\n편의점이니까요."
9009001-40 = "임무에는… 그러니까,\n추, 충분한 준비가 필요하다고 생각해요!"
9009001-50 = "그러니까… 잔뜩 사가시는게\n좋아요! 저희 가게 물건은 사면\n무조건 이득이라고요!"
9009001-60 = "저, 저기, 그렇게 빤히 바라보시면\n곤란한데…."
9009001-70 = "히익! 이, 이마는 만지지\n말아주세요!"
9009001-80 = "어른의 카드…\n구경 시켜 주실 수 있으신가요?"
9009001-90 = "그, 그치만… 저희 가게 정도면\n굉장히 양심적인 가격인걸요."
9009001-100 = "감사합니다!"
9009001-110 = "또 오세요, 선생님."
