[translation]
10001-10130 = "มาแล้วสินะคุณครู\nยินดีที่ได้พบกันอีกนะ"
10001-10140 = "ฮ้าว... ง่วงจัง..."
10001-10150 = "พอใส่เสื้อตัวนี้...\nแล้วหนาวรึเปล่างั้นเหรอ?"
10001-10160 = "นั่นสินะ\nฉันชอบที่มันระบายลมได้ดีน่ะ"
10001-10170 = "ชุดนี้ใส่สบายก็จริง\nแต่ว่ามันชอบม้วนกลับเข้าข้างในอยู่เรื่อย..."
10001-10180 = "แย่จัง..."
10001-10190 = "เสร็จเร็ว...\nกว่าที่คิดเอาไว้อีกนะ"
10001-10200 = "ยืนยันสำเร็จ"
