[translation]
10014-10 = "축제예요! 주군!\n자, 어디부터 놀러 가볼까요?"
10014-20 = "주군! 주군! 축제가\n정말 기대되네요!"
10014-30 = "이즈나!\n곁에서 따르겠습니다!"
10014-40 = "흥~ 흥흥흥~ 흥♪\n이즈나이즈나 캥캥~♪"
10014-50 = "앗? 이 기척은…\n주군이네요!"
10014-60 = "이즈나를 찾아주신 건가요?\n에헤헷!"
10014-70 = "경단, 센베이,\n오코노미야키…!"
10014-80 = "주군과 같이 먹고 싶은\n음식이 잔뜩이에요!"
10014-90 = "이즈나, 준비 만전!\n주군을 지켜드리면서,\n축제를 안내하겠습니다! 닌닌!"
10014-100 = "그때는 또 이즈나와\n어울려주세요! 주군!"
10014-110 = "흥~ 흥흥흥~ 흥♪\n이즈나이즈나 캥캥~♪"
10014-120 = "앗? 이 기척은…\n주군이네요!"
10014-130 = "이즈나를 찾아주신 건가요?\n에헤헷!"
10014-140 = "경단, 센베이,\n오코노미야키…!"
10014-150 = "주군과 같이 먹고 싶은\n음식이 잔뜩이에요!"
10014-160 = "이즈나, 준비 만전!\n주군을 지켜드리면서,\n축제를 안내하겠습니다! 닌닌!"
