[translation]
10017-10 = "The purge begins now!"
10017-20 = "Heehee. It's time for revolution!"
10017-30 = "Excited for Ivan Kupala's festival!"
10017-40 = "Hmm? Need my help, Comrade?"
10017-50 = "I can't believe there are students who still defy the authority of the mustache!"
10017-60 = "Purge them all!"
10017-70 = "For this year's Ivan Kupala, I've prepared a huge... uh... um..."
10017-80 = "Pudding! A huge pudding!"
10017-90 = "Once the purge is complete, we can share it among all who remain."
