[translation]
10022-10 = "歡迎你，老師。\n如你所見，夏季合宿的\n準備很完美。\n有問題儘管說。"
10022-20 = "啊啊，老師。\n合宿的行程表\n有仔細確認了嗎？"
10022-30 = "今天這麼熱，\n要注意補充水分哦。"
10022-40 = "夏天……\n又熱又濕又懶，\n做什麼都很麻煩……"
10022-50 = "不過這也是訓練\n的一環，沒有辦法。"
10022-60 = "海時常伴隨著危險。"
10022-70 = "不知何時何地\n會發生意外，\n要小心。"
10022-80 = "那個……\n有什麼事的話，\n可以叫我哦。"
10022-90 = "夏季訓練合宿。\n沒想到今年\n可以和老師一起……"
10022-100 = "……感覺有點新鮮。"
10022-110 = "這件泳裝只不過是\n為了訓練……"
10022-120 = "不買新的，"
10022-130 = "直接穿原本這件\n我覺得比較有效率……"
10022-330 = "從現在起開始\n夏季合宿的訓練。"
10022-340 = "雖然麻煩，\n但這也是訓練的一環。"
10022-350 = "好熱，好麻煩……"
10022-360 = "合宿好像有效果了。"
