[translation]
10026-10 = "เอาละ...!\nได้เวลาทำงานแล้วคุณครู!"
10026-20 = "ไม่มีเวลาพักแล้วนะ\nเริ่มเลยแล้วกัน!"
10026-30 = "มีงานอะไร\nที่จะให้ทำหรือเปล่าคุณครู?"
10026-40 = "วะฮ่าฮ่าฮ่า!\nไม่เลวเลยนี่!"
10026-50 = "ไม่มีเวลามาอืดอาดแล้วนะ"
10026-60 = "ทะ... ทำไมถึงจ้องกันแบบนั้นล่ะ?\nรีบทำงานกันได้แล้ว"
10026-70 = "วะฮ่ะฮ่ะฮ่า!\nไม่เลวเลยนี่!"
10026-80 = "ไม่มีเวลามาอืดอาดแล้วนะ"
10026-90 = "ทะ...ทำไมถึงจ้องกันแบบนั้นล่ะ?\nรีบทำงานกันได้แล้ว"
10026-550 = "เอาละ~\nไปทำความสะอาดกันเลยมั้ย?"
10026-560 = "รีบๆ เริ่มได้แล้ว"
10026-570 = "อะไรน่ะ มาให้กำลังใจฉันเหรอ?\nเฮอะ! บันเทิงชะมัด"
10026-580 = "ถ้าเป็นฉันละก็\nแค่นี้เรื่องกล้วยๆ!"
10026-590 = "หืม\nมีเซนส์เหมือนกันนะเนี่ย?"
10026-600 = "ทำงานก็ต้องทำให้มันชัดเจน"
