[translation]
10021-10 = "Ocean... Summer..."
10021-20 = "Hello? What are you looking at?"
10021-30 = "Welcome, Sensei. There's a lot to do."
10021-40 = "This swimsuit is very cute... Hee..hee..."
10021-50 = "S-Sensei? Were you staring at me?"
10021-60 = "S-Stop looking... I'm really not used to this."
10021-70 = "I-I'm fine... Don't mind me."
