[translation]
10025-10 = "What a nice day for a picnic!"
10025-20 = "I'll be guiding you through Shanhaijing today!"
10025-30 = "Wh-Where do you think Shun went?"
10025-40 = "(No one noticed...right?)"
10025-50 = "Sensei, over there! Look at those snacks!"
10025-60 = "(Haha. I guess this look isn't so bad...)"
10025-290 = "Welcome, Sensei. Looking forward to today's class!"
10025-300 = "Heehee. This size is convenient sometimes!"
10025-310 = "Mmm... I got sleepy..."
10025-320 = "Thank you!"
10025-330 = "Heehee. Thank you, Sensei."
