[translation]
10031-10 = "哎呀，老師。\n我在等你哦。"
10031-20 = "既然才剛過新年就發生了\n必須解決的事件……"
10031-30 = "呵呵，就請老師\n也幫個忙吧？"
10031-40 = "老師的手，\n摸起來真冷呢？"
10031-50 = "…就算工作很多，\n不好好休息也是\n不行的唷？"
10031-60 = "居然會演變成\n這麼大的騷動……\n唉，真是出乎我的預料……"
10031-70 = "……既然事已至此，\n我下定決心了。"
10031-80 = "我們便利屋68，\n事到如今就奉陪到最後吧！"
10031-90 = "啊，當然老師\n也會幫忙的對吧？"
10031-100 = "到頭來那個\n「KAITEN FX Mk.1」\n是什麼東西啊！？"
10031-110 = "已經無言到\n一句話都說不出來了……"
10031-120 = "唉……算了，\n對已經結束的事情\n再說三道四也沒用……"
10031-130 = "老師，反正也累了，\n等等一起去吃個飯怎麼樣？"
10031-140 = "我只是想在新年\n祈求便利屋68的事業\n鴻圖大展而已……"
10031-150 = "事情怎麼會變成這樣……"
10031-160 = "今年是我們便利屋68\n更加脫胎換骨的一年。"
10031-170 = "來，努力成就\n飛躍性的一年吧！"
10031-180 = "別擔心，老師。\n只要有我們\n便利屋68在，"
10031-190 = "不管面臨什麼障礙，\n我們一定都能克服。"
10031-200 = "……咦？計畫？不，那，\n那倒是還沒有……"
10031-210 = "呼，總覺得\n事情越來越嚴重了呢。"
10031-220 = "……我們的社員們\n應該沒有受傷吧？"
10031-560 = "歡迎你，老師。\n工作的準備非常完美唷。"
10031-570 = "我們便利屋68，\n為了新年做了各種準備。"
10031-580 = "慢慢挑選吧。"
10031-590 = "呼……亂哄哄的新年\n總算是平靜下來了呢。"
10031-600 = "呵呵，不過這裡\n依然還在營業中哦。"
10031-610 = "來，請冷靜地\n好好逛逛吧，老師♪"
10031-620 = "呵呵，怎麼樣呀？\n這些東西棒到\n讓人目不轉睛對吧？"
10031-630 = "要說這是我們\n便利屋68的實力\n也不為過哦♪"
10031-640 = "老師，有什麼\n特別吸引你的東西嗎？"
10031-650 = "……便利屋68的大家\n身穿和服拍的團體照？"
10031-660 = "才，才沒有那種東西！？"
10031-670 = "不愧是你，很有眼光呢，\n老師。真了不起。"
10031-680 = "哎呀，居然選了那個，\n真不愧是你呢。"
10031-690 = "因為是非常好的東西，\n還請好好使用哦？"
10031-700 = "居然選了那個，很有一套嘛老師。\n這才能稱得上是我的合夥人。"
10031-710 = "很棒對吧，那個東西！\n我也想自己買一個\n放在事務所裡……"
10031-720 = "啊，不是，我沒有\n強求你買的意思……！"
