[translation]
10040-200 = "忍術研究部，\n出動了……！"
10040-210 = "肯定會有辦法的\n……對吧？"
10040-220 = "這個事件，就由\n我們來解決……！"
10040-230 = "剛才那樣\n就決定了嗎……！"
10040-240 = "長得高大真是抱歉……"
10040-250 = "為什麼事情會\n變成這樣……"
10040-260 = "忍術研究部會解決\n給你看的……大概……"
10040-270 = "有什麼，我能做的嗎……"
10040-310 = "忍術研究部，\n出動了……！"
10040-320 = "肯定會有辦法的\n……對吧？"
10040-330 = "這個事件，就由\n我們來解決……！"
10040-340 = "剛才那樣\n就決定了嗎……！"
10040-350 = "看來，沒辦法\n輕鬆解決呢……\n我會，加油的……！"
10040-360 = "感覺好像，差不多\n平靜下來了……"
10040-370 = "這也是託大家\n和老師的福……"
10040-380 = "辛苦了，老師。\n我……有多少\n幫上一點忙嗎……？"
10040-390 = "長得高大真是抱歉……"
10040-400 = "為什麼事情會\n變成這樣……"
10040-410 = "忍術研究部會解決\n給你看的……大概……"
10040-420 = "有什麼，我能做的嗎……"
10040-630 = "忍具等等的物品，\n我準備了很多……請看。"
10040-640 = "有什麼需要的話，請來這裡。\n如果能幫上忙就好了……"
10040-650 = "事件雖然順利結束了……\n如果，還有什麼在意的事，嗯。\n現在，還來的及……"
10040-660 = "……？呃，我，那個，\n並不是商品……"
10040-670 = "難道，我很，礙事嗎？\n對不起，我馬上讓開……"
10040-680 = "是，我覺得是\n很棒的忍具……！"
10040-690 = "希望多少能\n幫上一些忙……"
10040-700 = "謝謝你，老師。"
10040-710 = "原來如此，還有，還有……\n不愧是老師，的說！"
