[translation]
10049-10 = "어서 와, 선생님.\n오늘도 잘 부탁해."
10049-20 = "자, 빨리 가자.\n할 일이 잔뜩이라고."
10049-30 = "응? 무슨 일이야?"
10049-40 = "걱정 안 해도,\n어디 안 간다니까."
10049-50 = "……간지럽다니까."
10049-60 = "아아~ 좀! 자! 자!\n일이나 해!"
10049-70 = "걱정 안 해도,\n어디 안 간다니까."
10049-80 = "……간지럽다니까."
10049-90 = "아아~ 좀! 자! 자!\n일이나 해!"
10049-100 = "보자, 뭐가 나올까?"
10049-110 = "자, 잔뜩 돌려볼까?"
10049-120 = "응? 내가 대신\n돌려도 돼?"
10049-130 = "선생님, 나 말고\n여기를 보라고."
10049-140 = "오…… 굉장한데,\n축하해."
10049-150 = "꽤 좋아 보이는데, 응."
10049-160 = "아, 뭔가 굉장해\n보이는 게……."
10049-170 = "아직 더 교환할 게\n없는지, 잘 봐 봐."
