[translation]
10046-100 = "นายท่าน~ ทางนี้~ ทางนี้ค่ะ~!\nที่ตรงนี้อิซุนะ\nจองไว้เรียบร้อยแล้วค่ะ!"
10046-110 = "อ๊ะ กำลังรออยู่เลยค่ะ! นายท่าน!\nอิซุนะเตรียมพร้อมแล้วค่ะ!\nสั่งการมาได้เลยค่า!"
10046-120 = "ร้านสาขาริมทะเล\nฐานทัพภารกิจครั้งนี้ค่ะ...!"
10046-130 = "พอเรียกว่าฐานทัพ...\nรู้สึกเหมือนเป็นนินจาเลยค่ะ!"
10046-140 = "ลั้ลลัลลา~ ที่ร้านริมทะเล\nมีอาหารเยอะแยะเลยค่ะ!"
10046-150 = "นายท่านชอบทานอะไรคะ?\nบิงซู? หรือว่าทาโกะยากิ?"
10046-160 = "อิซุนะน่ะ ถ้าได้กินกับนายท่านละก็\nอร่อยทุกอย่างเลยค่ะ~!"
10046-170 = "ไม่ว่าจะเจอเรื่องอันตราย\nหรือเรื่องลำบากแค่ไหน\nภาพของตัวฉันที่เผชิญหน้าต่อไป..."
10046-180 = "หรือว่าท่านชิซุโกะ\nจะเป็นนินจากันนะคะ?"
10046-190 = "ไม่ว่าเรื่องอะไร\nก็ออกคำสั่งมาได้เลยค่ะ!"
10046-200 = "เดี๋ยวฉันจะคลี่คลายแบบ\n\"ฉึบฉึบ\" เหมือนนินจาเลยค่ะ!"
10046-210 = "อิซุนะก็จะพยายาม\nเพื่อไม่ให้แพ้\nทุกๆ คนค่ะ นินนิน!"
10046-220 = "ฤดูร้อนคราวนี้มีเรื่องยิ่งใหญ่\nเต็มไปหมดเลยค่ะ! จนตาของ\nอิซุนะหมุนติ้วๆ ไม่หยุดเลยค่ะ"
10046-230 = "แต่ว่าอิซุนะเอง...\nก็สนุกในทุกๆ วันเลยค่ะ! ฮิฮิฮิ!\nขอบคุณค่ะ! นายท่าน!"
10046-240 = "ร้านสาขาริมทะเล\nฐานทัพภารกิจครั้งนี้ค่ะ...!"
10046-250 = "พอเรียกว่าฐานทัพ...\nรู้สึกเหมือนเป็นนินจาเลยค่ะ!"
10046-260 = "ลั้ลลัลลา~ ที่ร้านริมทะเล\nมีอาหารเยอะแยะเลยค่ะ!"
10046-270 = "นายท่านชอบทานอะไรคะ?\nบิงซู? หรือว่าทาโกะยากิ?"
10046-280 = "อิซุนะน่ะ ถ้าได้กินกับนายท่านละก็\nอร่อยทุกอย่างเลยค่ะ~!"
10046-290 = "ไม่ว่าจะเจอเรื่องอันตราย\nหรือเรื่องลำบากแค่ไหน\nภาพของตัวฉันที่เผชิญหน้าต่อไป..."
10046-300 = "หรือว่าท่านชิซุโกะ\nจะเป็นนินจากันนะคะ?"
10046-310 = "ไม่ว่าเรื่องอะไร\nก็ออกคำสั่งมาได้เลยค่ะ!"
10046-320 = "เดี๋ยวฉันจะคลี่คลายแบบ\n\"ฉึบฉึบ\" เหมือนนินจาเลยค่ะ!"
