[translation]
10052-160 = "เอาละ ถ้างั้นก็\nมาเริ่มเตรียมงาน\n<ฮาโลเฟสติวัล> กันค่ะ"
10052-170 = "ต้องรีบเตรียมตัวนะคะ\nจะได้ไม่สายในพิธีเปิดงานค่ะ!"
10052-180 = "นี่คืองานเทศกาลที่\nทั้งคิโวทอสให้ความสนใจ"
10052-190 = "ฉันจะพยายามให้เต็มที่\nเพื่อแสดงคุณค่าของ\nมิลเลเนียมออกมาค่ะ"
10052-200 = "ถึงฉันจะไม่ถนัด\nเรื่องพละกำลัง..."
10052-210 = "แต่นี่ก็เป็น\nงานของเซมิน่านี่คะ"
10052-220 = "(...ไม่ใช่ทุกคนสินะคะ\nที่กำลังตั้งตารอ\nงานเทศกาลนี้...)"
10052-230 = "ถ้ายูกะจังตื่นขึ้นมา\nก็คงจะบ่นนู่นนี่\nเยอะเลยใช่มั้ยคะ?"
10052-240 = "ฮุฮุ... อยากเห็นแล้วละค่ะ\nว่าสีหน้าตอนตกใจ\nของยูกะจะเป็นยังไง"
10052-250 = "ทำได้ดีมากเลยค่ะ คุณครู\nทุกคนช่วยกันออกแรง\nเตรียมงานนี้ขึ้นมา"
10052-260 = "<ฮาโลเฟสติวัล> ครั้งนี้ก็\nต้องสนุกเหมือนทุกครั้งแน่ค่ะ"
10052-270 = "นี่คืองานเทศกาลที่\nทั้งคิโวทอสให้ความสนใจ"
10052-280 = "ฉันจะพยายามให้เต็มที่\nเพื่อแสดงคุณค่าของ\nมิลเลเนียมออกมาค่ะ"
10052-290 = "ถึงฉันจะไม่ถนัด\nเรื่องพละกำลัง..."
10052-300 = "แต่นี่ก็เป็น\nงานของเซมิน่านี่คะ"
10052-310 = "(...ไม่ใช่ทุกคนสินะคะ\nที่กำลังตั้งตารอ\nงานเทศกาลนี้...)"
10052-320 = "ถ้ายูกะจังตื่นขึ้นมา\nก็คงจะบ่นนู่นนี่\nเยอะเลยใช่ไหมคะ?"
10052-330 = "ฮุฮุ... อยากเห็นแล้วละค่ะ\nว่าสีหน้าตอนตกใจ\nของยูกะจะเป็นยังไง"
10052-560 = "นี่คือรายการสิ่งที่จำเป็น\nในการเตรียมฮาโลเฟสติวัลค่ะ"
10052-570 = "มาได้จังหวะเลยค่ะ\nฉันมีเรื่องอยากขอร้อง\nคุณครูอยู่พอดีเลยค่ะ"
10052-580 = "คะ? มีเรื่องอะไรเหรอคะ?"
10052-590 = "ฮุฮุ ไม่ได้นะคะ\nตอนนี้ฉันกำลังยุ่ง...\nเดี๋ยวจะมาดูแลทีหลังนะคะ"
10052-600 = "สมกับเป็นคุณครูเลยนะคะ\nฉันได้เรียนรู้เยอะเลยค่ะ"
10052-610 = "จัดการได้เยี่ยมยอดเลยนะคะ\nประทับใจมากเลยค่ะ"
