[translation]
10066-10 = "老師，請加快動作！\n是活動唷，活動！"
10066-20 = "愛麗絲的話，隨時都OK！\n老師的準備完成了嗎？"
10066-30 = "雖然女僕克服等級\n還不高……"
10066-40 = "愛麗絲，會加油的！"
10066-50 = "老師，如果在哪裡\n發現了寧瑠前輩的話，\n請馬上通知哦。"
10066-60 = "絕對要哦？\n是和愛麗絲的約定！"
10066-70 = "料理、打掃、洗衣服！\n每個都是女僕的基礎！"
10066-80 = "老師也要\n參加任務嗎？"
10066-90 = "就，就算那樣戳\n也不會掉落\n任何東西喔……？"
10066-100 = "愛麗絲不是怪物！"
10066-110 = "絕對要哦？\n是和愛麗絲的約定！"
10066-120 = "料理、打掃、洗衣服！\n每個都是女僕的基礎！"
10066-130 = "老師也要\n參加任務嗎？"
10066-140 = "就，就算那樣戳\n也不會掉落\n任何東西喔……？"
10066-150 = "愛麗絲不是怪物！"
10066-500 = "歡迎光臨，老師！"
10066-510 = "女僕勇者\n要顧店也沒問題！"
10066-520 = "兌換道具的庫存，\n有非常多！"
10066-530 = "但如果是老師\n說不定能全都獲得。"
10066-540 = "活動雖然結束了，\n不過還在營業中。"
10066-550 = "因為是期間限定，\n還請不要忘記。\n是和愛麗絲的約定唷？"
10066-560 = "歡迎來到\n愛麗絲的道具店！"
10066-570 = "在這裡可以買到\n對冒險有幫助的\n道具和藥水唷！"
10066-580 = "嗯……老師，微笑是嗎？"
10066-590 = "知道了。桃井說過\n微笑是0信用貨幣！"
10066-600 = "乓啪喀乓！\n老師購買了道具！"
10066-610 = "送你高級微笑\n作為贈品！"
10066-620 = "齁齁……這位客人，\n眼光真不錯呢。"
10066-630 = "是這種時候要說的台詞！\n愛麗絲還記得！"
10066-640 = "旅人啊，\n這就是汝的選擇嗎……？"
10066-650 = "老師，怎麼樣呢？這句台詞，\n愛麗絲一直想說說看！"
10066-660 = "道具倉庫的管理\n也是女僕的工作！"
10066-670 = "愛麗絲，\n今天也會努力的！"
