[translation]
10064-560 = "Good job, Sensei. Nice to see you."
10064-570 = "Did you make a wish?"
10064-580 = "Things don't always turn out the way you want..."
10064-590 = "But I guess that's not a good reason to stop trying. Or something."
10064-670 = "I hope you have a happy, peaceful year."
10064-680 = "...Do I feel bad spending all the money I saved for a new album on an offering?"
10064-690 = "I guess I did go a little overboard, huh...?"
10064-700 = "Eh. It's worth it to see the boss smile."
10064-710 = "Haruka's seemed really overworked lately..."
10064-720 = "You think she's okay?"
10064-730 = "(...The Kurokame Gang. I have a bad feeling about this.)"
10064-1070 = "Good job, Sensei. Nice to see you."
10064-1080 = "Did you make a wish?"
10064-1090 = "Things don't always turn out like you want..."
10064-1100 = "But that doesn't mean you should stop dreaming. That's what I think, anyway."
10064-1110 = "This seems like trouble, right from the start..."
10064-1120 = "An offering thief..."
10064-1130 = "Ugh...this seems like a pain. I don't really wanna..."
10064-1140 = "But it's the boss' orders, so there's nothing I can do..."
10064-1150 = "Hah. Well, that was a disaster."
10064-1160 = "And I even had to face off against that weird robot..."
10064-1170 = "Oh well. At least it wasn't boring."
10064-1180 = "I hope you have a happy, peaceful year."
10064-1190 = "...Do I feel bad spending all the money I saved for a new album on an offering?"
10064-1200 = "I guess I did go a little overboard, huh...?"
10064-1210 = "Eh. It's worth it to see the boss smile."
10064-1220 = "Haruka's seemed really overworked lately..."
10064-1230 = "You think she's okay?"
10064-1240 = "(...The Kurokame Gang. I have a bad feeling about this.)"
10064-1420 = "Oh, Sensei. It's good you're here...I wanted to ask your help with something."
10064-1430 = "Sorry, I know it's annoying to be asking this right after New Year's, but...do you think you could make a little time?"
10064-1440 = "Haha, it's weird for Problem Solver to ask Sensei to do a job, and not the other way around, right?"
10064-1450 = "But this the whole thing is a bit weird."
10064-1460 = "Sorry. I'm not like Mutsuki... I'm really not used to this kind of place."
10064-1470 = "Um... I'm just not sure what kind of expression I should be making right now."
10064-1480 = "Thanks for your help. Here's your payment from Problem Solver 68."
10064-1490 = "Thanks, Sensei. You really saved us..."
