[translation]
10076-340 = "Leave the cheering—and explaining—to me!"
10076-350 = "Play, play, run and play! You can do it, go Sensei!"
10076-360 = "How was that? Did it give you a burst of energy?"
10076-370 = "Oh? What is it?"
10076-380 = "Do you have a question for me?"
10076-390 = "Then, I...!"
10076-400 = "I-If you keep poking me like that..."
10076-410 = "This is a bit embarrassing..."
10076-420 = "Eek! W-Was that you, Sensei...?"
10076-630 = "Leave the cheering—and explaining—to me!"
10076-640 = "Play, play, run and play! You can do it, go Sensei!"
10076-650 = "How was that? Did it give you a burst of energy?"
10076-660 = "Things are heating up! You can do this!"
10076-670 = "Almost there! I'll cheer you on until the very end!"
10076-680 = "Ugh! I'm exhausted."
10076-690 = "But I also feel...refreshed!"
10076-700 = "Oh? What is it?"
10076-710 = "Do you have a question for me?"
10076-720 = "Then, I...!"
10076-730 = "I-If you keep poking me like that..."
10076-740 = "This is a bit embarrassing..."
10076-750 = "Eek! W-Was that you, Sensei...?"
