[translation]
10073-10 = "여기에요, 선생님.\n조사 준비는\n다 해두었습니다."
10073-20 = "여름은 무덥고…….\n서 있는 것만으로,\n힘에 겨워요…."
10073-30 = "이제\n절반 정도 왔나……."
10073-40 = "곧 있으면, 이곳에서의\n조사도 끝이네요."
10073-50 = "마, 만약을 위해…\n확인해 보시죠."
10073-60 = "서, 선생님?\n왜, 왜 그러시죠?"
10073-70 = "제 얼굴에 뭔가\n묻어 있나요...?"
10073-80 = "갑자기\n그렇게 부르셔도……."
10073-90 = "필요한 게 있으시면,\n말로 해 주세요……."
10073-100 = "밖은,\n좋아하지 않아도……."
10073-110 = "단둘이 있을 수 있었고…\n나쁘지만은 않네요."
10073-530 = "그럼,\n조사 내용을 정리해 볼까요."
10073-540 = "여러가지, 알게 됐네요."
10073-550 = "음…\n아직 뭔가 더 조사하실 거라도?"
10073-560 = "저, 저를 조사해도,\n아무것도 안나와요…!"
10073-570 = "이건……. 의미가 있겠네요."
10073-580 = "역시, 선생님."
