[translation]
10105-10 = "Hello, Sensei."
10105-20 = "If you don't mind... Please watch me...on stage!"
10105-30 = "Are you ready, Sensei?"
10105-40 = "The concert will begin soon!"
10105-50 = "Let the concert continue!"
10105-60 = "Let's do our best for the second half of the concert!"
10105-70 = "Phew! That was refreshing!"
10105-80 = "How did you feel, Sensei?"
10105-90 = "Oh my, Sensei. What's happening?"
10105-100 = "W-Wait!"
10105-110 = "R-Right now, I'm, uh...sweaty..."
10105-120 = "Autograph...?"
10105-130 = "I-I never thought of something like that..."
10105-140 = "I'll put on a performance that I won't regret!"
10105-440 = "What are you looking for?"
10105-450 = "Please pick one to your liking! My recommendation is..."
10105-460 = "Please make sure that you didn't forget anything!"
10105-470 = "S-Sensei...?!"
10105-480 = "O-Over there... Not me..."
10105-490 = "Ahaha!"
10105-500 = "So that's what you chose. I think it's very cool!"
10105-510 = "Yes, I was looking at that one too."
10105-520 = "Would you like to go with that? Okay, here you go."
10105-530 = "This one. Okay, here you go."
