[translation]
10112-390 = "啊！老師！\n這邊唷～！"
10112-400 = "主人……不對，"
10112-410 = "老師！\n終於見到你了～！"
10112-420 = "呀齁！老師！\n玩得開心嗎～？"
10112-430 = "呵呵，要玩到\n最後一刻唷～！\n主人，不對，老師！"
10112-440 = "啊～結束了。\n真是一轉眼\n就過去了呢……"
10112-450 = "……當然！\n我非～～常開心唷！"
10112-460 = "老師，你有想\n去什麼地方嗎？\n我可以帶你去唷～"
10112-470 = "嗯？怎麼了？\n有事要拜託我嗎？"
10112-480 = "啊哈哈，好癢哦～！"
10112-490 = "難道老師，\n你想玩嗎？"
10112-500 = "那我也來對老師\n搔癢癢吧～！不會\n讓你逃走的唷～啊哈哈！"
