[translation]
10122-10 = "Yahoo! Are you having fun, Sensei?"
10122-20 = "Hmm. What would Sensei do...?"
10122-30 = "Things aren't going quite how I expected..."
10122-40 = "I'm sure it'll work out, one way or another!"
10122-50 = "I shouldn't let my guard down."
10122-60 = "There's no telling what'll happen next."
10122-70 = "Phew! Things wrapped up, somehow!"
10122-80 = "I wonder how it would've played out if you weren't here, Sensei."
10122-90 = "I don't even want to think about it..."
10122-100 = "I'm glad you were with me."
10122-110 = "I'm sure you already know this..."
10122-120 = "...but I can be a bit clumsy."
10122-130 = "Hm? Did something happen?"
10122-140 = "Something that may require my help?"
10122-150 = "Ahaha, th-that tickles, Sensei!"
10122-160 = "You sure about that? I might retaliate, you know!"
10122-170 = "Sensei...? I'm starting to wish...that you'd stop."
10122-180 = "Ah, I don't hate it! Not at all!"
10122-190 = "But...I might misunderstand."
10122-1220 = "Whoa, so much to do..."
10122-1230 = "You're working...at the beach...?"
10122-1240 = "What a bother..."
10122-1250 = "I could be convinced...with a reward!"
10122-1260 = "Fufu, Sensei..."
10122-1270 = "What do you think about playing hooky?"
10122-1280 = "Wow! I'd expect nothing less from you, Sensei!"
10122-1290 = "Okay, great! We're picking up the pace!"
