[translation]
10128-150 = "인사드립니다!\n특수교역부의 영업실장,\n와카사 후유입니다!"
10128-160 = "필요한 것이 있다면,\n부담 없이\n문의 바랍니다."
10128-170 = "후, 후후, 후……"
10128-180 = "이, 이런 일쯤은\n충분히\n대응 가능하다고요?"
10128-190 = "(왜 이렇게 됐지?\n뭘 잘못했지?)"
10128-200 = "(이거 망한 거죠?\n그렇죠?\n역시 그렇죠?!)"
10128-210 = "후…… 후후……\n당분간 이런 의뢰는\n피해야겠어요……."
10128-220 = "예, 맞아요.\n제가 바로 저희\n동아리의 얼굴이죠."
10128-230 = "접선하고,\n의뢰를 받고,\n고객을 응대하고……"
10128-240 = "예, 그게 저의\n역할이랍니다."
10128-250 = "물론 미요와 리츠 쨩의\n서포트가 없다면,"
10128-260 = "저는 그저\n평범한 예술학원 학생에\n지나지 않았겠죠."
10128-270 = "……예술이란,\n정말 쉽지 않네요."
10128-500 = "시간도 재고도\n충분하답니다.\n여유롭게 둘러보시길."
10128-510 = "찾으시는 물건이\n있으신가요?"
10128-520 = "폐점까지는\n시간이 좀 남았습니다.\n차분히 둘러보세요."
10128-530 = "따로 원하는 게\n있으시다고요?"
10128-540 = "……이쪽에서 한 번\n이야기해 보시죠."
10128-550 = "푸핫! 그, 그렇게\n찌르셔도 할인은\n안 된다고요?"
10128-560 = "세련된 안목이시군요."
10128-570 = "저도 눈여겨보던\n제품입니다."
10128-580 = "교환 및 환불은\n어렵답니다?"
10128-590 = "훌륭한 선택입니다.\n혹시 포장,\n필요하신가요?"
