[translation]
10128-150 = "Hello! I'm Wakasa Fuyu, the Sales Manager of the Free Trade Cartel!"
10128-160 = "If there's anything you need, please feel free to contact me."
10128-170 = "Fu, fufu, fu..."
10128-180 = "I-I can easily handle something like this, you know?"
10128-190 = "(How did things end up this way? What did I do wrong?)"
10128-200 = "(This is doomed, right? Right? Really is, right?!)"
10128-210 = "Fu... Fufu... I should avoid commissions like this one for a while..."
10128-220 = "Yes, you're right. I am the face of our club."
10128-230 = "Going to meetings, taking commissions, handling customers..."
10128-240 = "Yes, that is my role."
10128-250 = "Of course, without support from Miyo or Ritsu..."
10128-260 = "...I would've been just an ordinary art student."
10128-270 = "...Art really isn't easy at all."
10128-500 = "We're still open and have plenty of stock. Please take your time."
10128-510 = "Is there anything you're looking for?"
10128-520 = "The shop will stay open for a while longer. Please take your time."
10128-530 = "You have something specific you're looking for?"
10128-540 = "...We should talk about it over there."
10128-550 = "Pfft! E-Even if you poke me like that, you're not getting a discount!"
10128-560 = "You have sophisticated eyes."
10128-570 = "I also had my eyes on that product."
10128-580 = "Refunds and exchanges would be difficult, you know?"
10128-590 = "That's a great choice. Do you need it wrapped, by any chance?"
