[translation]
10132-180 = "คะ... คุณครู...?!\nชะ... ชุดนี้ มันดูแปลกๆ ใช่มั้ยคะ...?"
10132-190 = "มะ... มาแล้วเหรอคะ\nคุณครู...?"
10132-200 = "คะ... คือว่าชุดนี้... "
10132-210 = "อะ... อะไรกันคะเนี่ย...?\nนี่มันเกิดเรื่องอะไรขึ้น\nกันแน่คะ...?"
10132-220 = "ตอนอยู่บนเวที...\nมันแปลกๆ นะคะ"
10132-230 = "ทั้งที่ได้รับความสนใจ\nมากกว่าครั้งไหนแท้ๆ"
10132-240 = "แต่มันรู้สึกโดดเดี่ยว\nจนใจหายเลยค่ะ..."
10132-250 = "ทุกคน...!\nฉัน... กลับมาแล้วค่ะ...!"
10132-260 = "ตัวฉันน่ะ เหมาะกับชุดนี้\nจริงๆ เหรอคะ...?"
10132-270 = "มะ... มันดูเด่นเกินไปสินะคะ\nคุณครู...?"
10132-280 = "ฮือออ\nนินจาไม่ควรทำอะไร\nแบบนี้เลย..."
10132-290 = "สะ... สะ... สะ\nสวยงั้นเหรอคะ...?!"
10132-300 = "ฮึกกก..."
10132-310 = "ถะ... ถ้าคิดว่า"
10132-320 = "ชุดนี้เป็นส่วนหนึ่ง\nของวิชาแปลงกาย\nก็อาจจะไม่เป็นไร..."
10132-590 = "ฉะ... ฉันลองรวบรวม\nภารกิจที่ที่ต้องทำมาแล้วค่ะ"
10132-600 = "ไม่ใช่ภารกิจง่ายๆ เลย..."
10132-610 = "แต่คุณครูทำได้แน่นอนค่ะ!"
10132-620 = "ระ... รายการที่ฉันสรุปมา\nมีปัญหาตรงไหนรึเปล่าคะ...? "
10132-630 = "คะ? ระ... เรื่องแบบนี้\nไม่ได้มีอยู่ในภารกิจนี่คะ..."
10132-640 = "คะ... คิดแล้วเชียว...!"
10132-650 = "ว่าคุณครูจะต้อง\nทำสำเร็จจนได้!"
10132-660 = "สุดยอดเลยค่ะ! คิดแล้วเชียวว่าคุณครู\nมีพรสวรรค์ด้านนินจาจริงๆ ด้วย...! "
10132-670 = "ทะ... ทำได้ดีมากเลยค่ะ...!\nเป็นฟินาเล่ที่งดงามมาเลยค่ะ!"
