[translation]
13013-160 = "Welcome, Sensei!"
13013-170 = "Heehee. I've been waiting!"
13013-180 = "Hi, Sensei!"
13013-190 = "If there's anything I can do for you, just let me know."
13013-200 = "Seems like things are snowballing..."
13013-210 = "But I'm sure it'll be okay, right, Sensei...?"
13013-220 = "It's too late to turn back now."
13013-230 = "The Knowledge Liberation Front will push on!"
13013-240 = "Somehow, it's finally over... I'm just glad everyone's safe."
13013-250 = "Yes? Did you call me, Sensei?"
13013-260 = "I wonder what Meru is doing right now..."
13013-270 = "I just hope she's not going crazy somewhere..."
13013-280 = "I like reading just as much as I enjoy appreciating pictures."
13013-290 = "Manga can teach us so many things."
13013-300 = "S-Sensei? If you stare at me like that...it makes me feel shy..."
13013-310 = "Are you looking for something, Sensei? Take your time."
13013-320 = "I'm used to arranging and displaying things. Just leave it to me!"
13013-330 = "Look around as much as you'd like."
13013-340 = "I'd hate for you to get the wrong things."
13013-350 = "Managing the shop...?"
13013-360 = "This is nothing compared to managing the library."
13013-370 = "What if there's an out-of-print first edition book mixed in here somewhere...? What should I do...?"
13013-380 = "Oh! I-I'm not saying I'd snatch it up for myself...!"
13013-390 = "Oh, so you picked that one."
13013-400 = "Wait just a moment... Yes, here!"
13013-410 = "And...what's the line...?"
13013-420 = "\"Oh! You have great taste!\""
13013-430 = "Thank you so much!"
13013-440 = "I was so professional just now? Heehee..."
13013-450 = "Welcome, Sensei. What would you like?"
13013-460 = "Are you getting your fortune?"
13013-470 = "Can I watch from the side? Heehee."
13013-480 = "Is there something wrong?"
13013-490 = "Yes, Sensei? What's going on?"
13013-500 = "A little luck, just for you..."
13013-510 = "I've always wanted to say something like that!"
13013-520 = "Wow, you won! That's amazing, Sensei!"
13013-530 = "Sensei, you have really great luck! This is so great!"
13013-540 = "Can I see?"
13013-550 = "Hmm... This is pretty good!"
13013-560 = "Aah..."
13013-570 = "D-Don't be too sad. At least you have me, Sensei!"
