[translation]
13014-220 = "Blue sea! Blue sky! White clouds! The best sounds!"
13014-230 = "Fufu, victory is ours! You'll cheer for me, right, Sensei?"
13014-240 = "There's not much time left! Let's give it our all!"
13014-250 = "We can't let our guard down until the very, very end!"
13014-260 = "The festival's over...but our youth will live on!"
13014-270 = "Limited-edition summer youth activities! Mentor, I'm excited!"
13014-280 = "Mentor, do you want to swim with me?"
13014-290 = "Okay! Let's see who's faster!"
13014-300 = "Never let your guard down. Stay sharp."
13014-310 = "I'll be looking forward to your commentary, Mentor!"
13014-570 = "Mentor! It's a beach treasure hunt! I wonder what's hiding in there!"
13014-580 = "Treasure hunts are absolutely a youth activity! Let's hunt together!"
13014-590 = "Ah, that was fun. Let's do another one, next time."
13014-600 = "I made another precious memory. Thank you, Mentor."
13014-610 = "I see a lot of great treasure..."
13014-620 = "Hm? What's my most precious treasure?"
13014-630 = "Th-That's..."
13014-640 = "That's a secret! Secret! An absolute secret!"
13014-650 = "The youth I once dreamed of came to life again..."
13014-660 = "Thank you so much. Mentor..."
13014-670 = "Oh! Isn't this treasure?!"
13014-680 = "Mentor! I found a clue!"
13014-690 = "Treasure secured! Now, let's see what it is...!"
13014-700 = "As expected of Mentor! Your skills are amazing!"
13014-710 = "Let's go search for the next treasure!"
