[translation]
16007-100 = "붉은겨울 학원 사무국에\n오신 것을 환영합니다,\n선생님."
16007-110 = "학원 부지에서 체리노\n회장님의 특제 마트료시카를\n찾으셨나요?"
16007-120 = "이곳에서\n교환하실 수 있어요!"
16007-130 = "축제는\n즐겁게 즐기고 계신가요?"
16007-140 = "회장님의 마트료시카를\n찾으시면 언제든\n저를 찾아와주세요!"
16007-150 = "축제도 이제\n얼마 남지 않았네요…"
16007-160 = "아쉬워라…."
16007-170 = "오늘이 이반 쿠팔라\n축제의 마지막\n날이랍니다."
16007-180 = "잊고 가시는 물건이 없도록\n붉은겨울 학원을\n꼼꼼히 돌아보세요!"
16007-190 = "축제는 끝났지만\n남은 마트료시카는"
16007-200 = "여기서 얼마든지\n교환하실 수 있어요."
16007-210 = "그 회장님 모양의\n마트료시카는 제가\n디자인했답니다."
16007-220 = "후후…\n귀엽죠?"
16007-230 = "귀여운 마트료시카가\n쪼개지는 모습을\n보고 있노라면…"
16007-240 = "어쩐지 가슴이 아프네요."
16007-250 = "당첨입니다!\n축하드려요!"
16007-260 = "어머나, 당첨이네요!\n선생님도 운이 좋으시네요."
16007-270 = "후후, 좋은 물건을 뽑으셨네요.\n소중하게 사용해주세요!"
16007-280 = "체리노 회장님처럼\n귀여운 선물이네요!"
