[translation]
16005-200 = "S-Sensei, um... It's n-nice to meet you!"
16005-210 = "(I wonder what Sensei thinks about how I look...)"
16005-220 = "Wh-Whoa!"
16005-230 = "Oh... Um... Uh..."
16005-240 = "I...I'm ready, Sensei."
16005-250 = "(What to do, what to do... What am I going to do?!)"
16005-260 = "Ts-Tsurugi!"
16005-270 = "Let's go!"
