[translation]
16006-280 = "앗, 선생님이다!\n어서 오세요!\n바다의 집에 잘 왔어-!"
16006-290 = "앗, 선생님!\n기다리고 있었어!"
16006-300 = "이 바다의 집 영업 기간도,\n슬슬 절반이나 지났어!\n마지막까지 즐겨야지!"
16006-310 = "곧 마지막이네!\n힘내!"
16006-320 = "오늘이 마지막 날이야, 선생님!\n갖고 싶은 건 다 챙겼어?"
16006-330 = "영업 종료, 수고하셨습니다~~!"
16006-340 = "…라고 생각했어?\n후후, 실은 아직\n조금 시간이 남았대!"
16006-350 = "잊은 물건이 없는지,\n잘 확인해야 해?"
16006-360 = "응! 맘껏 둘러봐. 둘러봐!\n맛있는 것도 많으니까!"
16006-370 = "저기 선생님, 이거… 응?"
16006-380 = "진짜~ 나 말고\n상품을 보라구~!"
16006-390 = "우웅…\n그, 그렇게 콕콕 찔러도,\n공짜로 줄 순 없다구?"
16006-400 = "오오-!\n역시 선생님!"
16006-410 = "그걸로 고른 거야?\n응! 좋을지도!"
