[translation]
16010-250 = "이런 차림은\n조금 어색하지만…"
16010-260 = "그래도 <황륜대제>의\n성공을 위해서라면…"
16010-270 = "후후, 즐거운 축제가\n되었으면 좋겠네."
16010-280 = "히, 힘내라,\n힘내라… 선생님…!"
16010-290 = "내가 만든 옷이긴 하지만…\n다들… 신경 쓰이지\n않는 걸까…"
16010-300 = "이 옷의 꼬리 부분이\n신경 쓰인다고…?"
16010-310 = "지금은…\n말하기 곤란하지만…"
16010-320 = "나중에 몰래\n구조를 가르쳐 줄게…"
16010-330 = "역시 열정을\n불태우는 건…\n로망이야."
16010-340 = "이런 차림은\n조금 어색하지만…"
16010-350 = "그래도 <황륜대제>의\n성공을 위해서라면…"
16010-360 = "후후, 즐거운 축제가\n되었으면 좋겠네."
16010-370 = "(치어리딩은 아무리\n연습해도 좀처럼\n익숙해지질 않네…)"
16010-380 = "<황륜대제> 준비도\n거의 끝난 것 같아.\n조금만 더… 힘내자."
16010-390 = "도와줘서 고마워,\n선생님."
16010-400 = "본 경기에서도\n우리의 응원을 기대해줘."
16010-410 = "히, 힘내라,\n힘내라… 선생님…!"
16010-420 = "내가 만든 옷이긴 하지만…\n다들… 신경 쓰이지\n않는 걸까…"
16010-430 = "이 옷의 꼬리 부분이\n신경 쓰인다고…?"
16010-440 = "지금은…\n말하기 곤란하지만…"
16010-450 = "나중에 몰래\n구조를 가르쳐 줄게…"
16010-460 = "역시 열정을\n불태우는 건…\n로망이야."
16010-470 = "선생님, 어서 와.\n<황륜대제> 준비에 필요한\n자재를 모으는 중이야."
16010-480 = "<황륜대제> 준비에 필요한\n물자는 이쪽에 모아줘."
16010-490 = "수고 많았어, 선생님.\n혹시라도 남은 물자가 있다면\n내가 바꿔줄게."
16010-500 = "응?\n무슨 일이야?"
16010-510 = "저기… 응원이라면\n나중에 해줄게. 지금은 조금…"
16010-520 = "음, 좋은 물건이네.\n도와줘서 고마워."
16010-530 = "작은 성의지만… 도와준 답례야.\n받아주었으면 좋겠어."
16010-540 = "이거라면…\n모두가 좋아할 거야."
16010-550 = "큰 도움이 되었어.\n고마워, 선생님."
