[translation]
16012-120 = "Oh, you're here, Sensei! It's loud outside. Should we go check it out?"
16012-130 = "There are lots of extra-delicious foods on New Year's Day..."
16012-140 = "I always end up spending too much money..."
16012-150 = "Oh, what's up, Sensei? Oh... Did you wanna talk to me...by any chance?"
16012-160 = "Seriously, don't poke me like that! You're messing up my kimono."
16012-170 = "Cleaning it is not the problem!"
16012-180 = "Hakamas are better... They're way easier to move in."
16012-190 = "I have to braid up my hair too?!"
16012-200 = "I can't pull that off! There's no way..."
16012-210 = "I always end up spending too much money..."
16012-220 = "Oh, what's up, Sensei? Oh... Did you wanna talk to me...by any chance?"
16012-230 = "Seriously, don't poke me like that! You're messing up my kimono."
16012-240 = "Cleaning it is not the problem!"
16012-250 = "Hakamas are better... They're way easier to move in."
16012-260 = "I have to braid up my hair too?!"
16012-270 = "I can't pull that off! There's no way..."
16012-280 = "I feel like it'll be really annoying..."
16012-290 = "When it comes to bad luck...my intuition is dead on..."
16012-300 = "I had a feeling it would turn out this way..."
16012-310 = "But since you're with me, Sensei, I'm sure it'll work out somehow."
16012-320 = "Ugh, I'm so tired. I'm glad everything worked out."
16012-330 = "That osechi was good! I ate so much!"
16012-840 = "Is all this here for you, Sensei? You've got a lot of work ahead..."
16012-850 = "Well, let me know if you need help."
16012-860 = "Now's not the time to relax! Good luck, Sensei."
16012-870 = "Huh? Did you call? Are you gonna buy me something?"
16012-880 = "Heehee. Just kidding."
16012-890 = "It's not that I don't like loud environments. If I didn't, then I wouldn't be able to get along with the Gourmet Research Society."
16012-900 = "See? You can do it, too."
16012-910 = "Heehee. I've always wanted to say that."
16012-920 = "Honestly, I don't think I could've done it myself... Such is the power of an adult..."
16012-930 = "Not bad."
16012-940 = "Are we done for today?"
16012-950 = "Then let's go grab something delicious!"
