[translation]
16011-160 = "I've been waiting for you, Sensei. Are you ready?"
16011-170 = "The games are about to begin. Let's get going, shall we?"
16011-180 = "S-Sensei?"
16011-190 = "If you keep staring at me like that..."
16011-200 = "It's about time we started heading out..."
16011-210 = "Is there something you need?"
16011-280 = "I've been waiting for you, Sensei. Are you ready?"
16011-290 = "The games are about to begin. Let's get going, shall we?"
16011-300 = "Everything is in full swing."
16011-310 = "I think it's safe to call this Kivotos Halo Festival a success... Don't you agree?"
16011-320 = "We're entering the final stretch of the Kivotos Halo Festival."
16011-330 = "Let's make sure to finish strong."
16011-340 = "The Kivotos Halo Festival was a massive success thanks to you, Sensei."
16011-350 = "Thank you for all your hard work."
16011-360 = "S-Sensei?"
16011-370 = "If you keep staring at me like that..."
16011-380 = "It's about time we started heading out..."
16011-390 = "Is there something you need?"
16011-500 = "You want to take a look at the match records?"
16011-510 = "I have a summary right here. Feel free to peruse it."
16011-520 = "For now, this is all I have to show you..."
16011-530 = "Is there anything else you'd like to see?"
16011-540 = "Got it. What an excellent record."
16011-550 = "This... This might be a new record."
