[translation]
20005-140 = "Mmm... Refreshing ocean smell!"
20005-150 = "I hope it's a fun vacation!"
20005-160 = "I'm ready! I even brought a Peroro tube for swimming!"
20005-170 = "Oh? I swear I put the keys to the locker rooms here..."
20005-180 = "S-Stop looking at me! It's embarrassing!"
20005-190 = "We're finally here! Look, the ocean!"
