[translation]
20006-70 = "歡迎來到山海經\n高級中學，老師！"
20006-80 = "哼哼哼。\n今天的約定當然\n還記得吧，老師？"
20006-90 = "旬教官\n跑哪去了……？"
20006-100 = "哼哼哼。製作出不老不死\n靈藥的日子已經不遠了！"
20006-110 = "真奇怪……\n「回春秘藥」裡應該沒有\n加入什麼奇怪的東西才對……"
20006-120 = "……難道是\n在煮沸的時候，"
20006-130 = "飛在空中的\n根津助的毛\n混進去了嗎！？"
20006-140 = "歡迎來到我的\n校外研究所，老師！"
20006-150 = "如果有好的煉丹術材料，\n我會用高價收購！"
20006-160 = "這個校外研究所\n只不過是臨時的而已。"
20006-170 = "所以如果有什麼想要\n的材料，最好提早入手哦。"
20006-180 = "最近總覺得\n商會的氣氛很奇怪……"
20006-190 = "這個校外研究所，\n或許早點關門比較好呢。"
20006-200 = "校外研究所\n今天就結束營業了。"
20006-210 = "如果有需要的材料，\n早點交換比較好哦？"
20006-220 = "校外研究所，營業結束！"
20006-230 = "啊，可是，如果還有剩下\n的材料，請務必讓我看看！"
20006-240 = "存在於世界上的\n幾乎所有東西，\n都是煉丹術創造出來的！"
20006-250 = "唔嗯……關於老師說的\n那個「藍色的石頭」，\n我也不是很清楚……"
20006-260 = "是個不錯的選擇！"
20006-270 = "呵呵，謝謝你\n幫我收集好的素材。"
20006-280 = "哦哦，真是明智的選擇！"
