[translation]
20015-10 = "Welcome to the Hyakkiyako Movie Village! I'll be your guide, Sensei!"
20015-20 = "Oh, Sensei! What's going on? Are you gonna play in the Movie Village?"
20015-30 = "I wanna play with you too!"
20015-40 = "Oh, but I can't do that now..."
20015-50 = "The Inner Discipline Club has to help with the event this time..."
20015-60 = "Ugh... I just wanna play!"
20015-70 = "Huh? What? Is this like a poking game?"
20015-80 = "I'm not gonna lose! Hiii-yah! Hi-yah!"
20015-90 = "I know that helping like this is a part of my training, but..."
20015-100 = "...it's still so boring!"
20015-110 = "Hmm... I wanna go out and have fun..."
20015-120 = "Hmm... No. Being still is just so boring!"
20015-130 = "...Ah, I feel better after yelling."
20015-140 = "Huh? What? Is this like a poking game?"
20015-150 = "I'm not gonna lose! Hiii-yah! Hi-yah!"
20015-160 = "I know that helping like this is a part of my training, but..."
20015-170 = "...it's still so boring!"
20015-180 = "Hmm... I wanna go out and have fun..."
20015-190 = "Hmm... No. Being still is just so boring!"
20015-200 = "...Ah, I feel better after yelling."
20015-720 = "You can choose a card now! Why don't you go for it, Sensei?"
20015-730 = "All right, pick one! It's your turn. Draw!"
20015-740 = "Might as well pick all of them!"
20015-750 = "Maybe it'll be a rare card!"
20015-760 = "Ba-dump, ba-dump! What's it gonna be?"
20015-770 = "I hope it's a rare card!"
20015-780 = "It's sparkly and pretty. So exciting!"
20015-790 = "Whoa, this is an incredibly rare card!"
20015-800 = "Sensei! Amazing! This must be fate!"
20015-810 = "Oh, that's a good card! This must be...the power of an adult..."
20015-820 = "Oh, I see that one often. But I think it's still a pretty rare card!"
20015-830 = "So, um... D-Don't be disappointed, Sensei!"
20015-840 = "I'm sure you'll get something good next time! Maybe."
