[translation]
20021-110 = "선생님, 드디어\n크리스마스가 찾아왔습니다!"
20021-120 = "저도 크리스마스\n모드예요~!"
20021-130 = "선생님은 뭔가\n바라는 것이 있으세요?"
20021-140 = "제가 산타클로스께\n편지를 써 드릴게요!"
20021-150 = "선생님, 왜 그러세요?\n무슨 일이라도 있으신가요?"
20021-160 = "그렇게 계속\n바라보시면……"
20021-170 = "이 복장, 이상한가요?"
20021-180 = "왜 그러세요? 뭔가\n잊어버린 물건이라도……\n어, 아니라고요?"
20021-190 = "으우우……\n자꾸 쿡쿡 찌르시면……"
20021-200 = "저도 선생님을\n마구 찔러 버릴 거예요!"
20021-210 = "그렇게 계속\n바라보시면……"
20021-220 = "이 복장, 이상한가요?"
20021-230 = "왜 그러세요? 뭔가\n잊어버린 물건이라도……\n어, 아니라고요?"
20021-240 = "으우우……\n자꾸 쿡쿡 찌르시면……"
20021-250 = "저도 선생님을\n마구 찔러 버릴 거예요!"
20021-350 = "구호기사단이 주관하는\n자선 행사가 개최 중이에요!"
20021-360 = "앗, 선생님! 어서 오세요!\n제비뽑기는 어떠신가요?"
20021-370 = "자선 이벤트는\n종료되었습니다!"
20021-380 = "아직 추첨권을\n가지고 계신다면\n제가 교환해드릴게요!"
20021-390 = "네?\n무슨 문제라도 있으신가요?"
20021-400 = "오늘의 하나에 산타는\n행복을 전한답니다~!"
20021-410 = "우와, 당첨이네요!"
20021-420 = "후후, 제 선물이\n마음에 드셨으면 좋겠어요!"
20021-430 = "와아……!\n이런 것이 들어 있었다니…!"
20021-440 = "오늘 할 일은 이쪽이에요!"
20021-450 = "하나씩, 조급해하지 말고 진행하죠!"
20021-460 = "이 리스트, 여기 맞나?\n……어, 어느 쪽이지?"
20021-470 = "뭔가 일이 많네요……"
20021-480 = "이것도 수술해 버릴 수 있으면\n좋을 텐데요."
20021-490 = "대단해요! 역시 선생님이세요!"
20021-500 = "수고하셨어요, 선생님!\n저도 기뻐요!"
