[translation]
20020-10010 = "초현상특무부의 임무.\n시작해볼까요."
20020-10020 = "후훗. 기다리고 있었습니다,\n선생님."
20020-10030 = "……아. 지금 데이터를\n분석 중이니 잠시만\n기다려주세요."
20020-10040 = "과연, 흥미롭네요……"
20020-10050 = "이걸 이렇게 해서,\n흠……"
20020-10060 = "데카그라마톤……\n성가신 상대입니다."
20020-10070 = "리스크가 있을 것\n같지만……"
20020-10080 = "후훗. 그래서\n더욱 흥미롭네요."
20020-10090 = "새로운 데이터를\n확보했습니다."
20020-10100 = "그럼, 이번에는\n어떤 정보일지 확인해볼까요."
20020-10110 = "다음 목표가\n정해진 것 같네요."
20020-10120 = "자, 이제 다음 단계로\n넘어가도록 하겠습니다."
20020-10510 = "새로운 임무, \n그리고 새로운 환경……"
20020-10520 = "……자, 시작하죠. 선생님."
20020-10530 = "선생님, 도와주시겠어요?"
20020-10540 = "어머, 초천재 청초계 \n병약 미소녀라고 해도,"
20020-10550 = "도움은 필요하거든요?"
20020-10560 = "오셨나요, 선생님."
20020-10570 = "여기가 우리들의 \n새로운 기지랍니다."
20020-10580 = "조건의 증가를 확인했습니다."
20020-10590 = "어디까지 변수를 \n억제할 수 있을지…… \n신중하게 가 보도록 하죠."
20020-10600 = "정보는 많을수록 환영, \n이긴 하지만……"
20020-10610 = "너무 한꺼번에 주어지면, \n그건 그것대로 곤란하죠."
20020-10620 = "조금 피곤하네요…"
20020-10630 = "이럴 때 어리광을\n받아주는 선생님이 있다면\n너무 좋을 텐데요."
20020-10640 = "최고의 해커이자, \n최고의 미소녀인 저에게"
20020-10650 = "최고의 파트너가 부재하다니,"
20020-10660 = "중대한 사태입니다.\n그러니 선생님께 저의……"
20020-10670 = "아무것도 아니에요…… \n방금 얘기는 잊어주세요."
20020-10680 = "새로운 국면에 접어들었다… \n고 생각하면 될까요."
20020-11550 = "여기에서는,\n선생님이 모아 주신"
20020-11560 = "「물질」의 분석을\n하고 있습니다."
20020-11570 = "어서 오세요, 선생님.\n후우…… 기다리다 지쳤어요."
20020-11580 = "샘플 수집은 진행되었나요?\n이쪽에 부탁드릴게요."
20020-11590 = "항상 협조해 주셔서\n감사합니다, 선생님."
20020-11600 = "과연, 어떤 정보가 나올지."
20020-11610 = "덕분에 조사는 순조롭습니다.\n그렇다고는 해도,\n이 현상… 정말 흥미롭군요."
20020-11620 = "하아, 설마 분석이\n따라가지 못하고 있다니……."
20020-11630 = "이 얼마나\n사치스러운 환경인가요"
20020-11640 = "새로운 탐구란,\n언제나 즐거운 일이죠."
20020-11650 = "거기에 선생님께서\n함께 해 주신다면……\n더할 나위 없고요."
20020-11660 = "분석 완료입니다.\n편하게 가져가세요. 선생님."
20020-11670 = "해석 결과는\n마음에 드셨나요?\n후후, 다음에 또 오세요."
20020-11680 = "선생님을 위해\n정성껏 분석했습니다.\n네, 받아주세요."
20020-11690 = "……공, 공과 사는\n분리하고 있다구요, 그럼요."
20020-11700 = "선생님께서\n샘플을 모아주시고,"
20020-11710 = "우리는 그것을\n분석해서 전달한다……"
20020-11720 = "물물교환'의 성립이군요."
20020-11730 = "매번 감사합니다.\n……어떠셨나요?"
20020-11740 = "초천재청초계병약 미소녀의\n일일 점포 서비스는."
20020-12200 = "분석의 방향을\n조금 바꿔봤습니다."
20020-12210 = "우연과 필연,\n절대론과 상대론………."
20020-12220 = "매력적인 소재입니다.\n그렇게 생각하지 않으시나요?\n선생님."
20020-12230 = "선생님도 운을\n한 번 시험해 보시겠어요?"
20020-12240 = "점성술에 의하면\n오늘의 럭키 컬러는…."
20020-12250 = "…네? 그건 괜찮다구요…?"
20020-12260 = "확률이나 통계는\n사물의 대부분을 결정짓죠."
20020-12270 = "점성술은 물론,\n「뽑기」도…\n예외는 아닙니다."
20020-12280 = "모든 것은 통제되어야 한다…\n는 말에, 저는 반대합니다."
20020-12290 = "아직 보지 못한\n세계와의 조우야말로,"
20020-12300 = "가치가 있다고\n생각하기 때문에요."
20020-12310 = "미지의 영역……\n마음이 끌리는 법이죠."
20020-12320 = "과학에 의해서\n많은 수수께끼가\n밝혀졌다고 해도,"
20020-12330 = "미지의 영역이라는 것은,\n여전히 남아 있습니다."
20020-12340 = "……그렇지 않다면,\n지루해져 버릴 테니까요."
20020-12350 = "어느덧 우리는,\n목표 지점에 도달하고,"
20020-12360 = "그리고…… 한층 더 높은\n목표의 탄생을\n목격하게 되겠지요."
20020-12370 = "축하합니다, 선생님.\n결과를 예상할 수\n있었다고는 하지만,"
20020-12380 = "성과를 실감하는 순간은,\n기뻐해도 좋지 않을까요?"
20020-12390 = "어머, 이건\n소위 말하는 '당첨'이군요?"
20020-12400 = "통계학적으로 보면,\n당연한 결과라고 해도"
20020-12410 = "거기에서 기쁨을\n느끼는 것은 우리의 자유……"
20020-12420 = "훌륭합니다,\n선생님. 저도 기뻐요."
20020-12430 = "특별함'을 느낄 수 있는 건\n'보통'이 있기 때문이죠."
20020-12440 = "그러니 '보통'을\n소중히 여겨주세요. 선생님."
20020-12450 = "…하는 김에, 고생하고 있는\n초천재 청초계\n병약미소녀도요."
