[translation]
20025-740 = "老，老老老老，老師！？\n歡，歡迎回來！\n還有，對，對不起！"
20025-750 = "……嘿嘿……\n竟然會在這裡\n見到老師……"
20025-760 = "沒，沒有！\n我沒有什麼\n特別的意思……！"
20025-830 = "是，是！？\n怎，怎怎怎怎，\n怎麼了嗎，老師！？"
20025-840 = "咦……？只是……\n想叫叫看而已？"
20025-850 = "是，是這樣啊。\n耶，嘿嘿……"
20025-860 = "在新年……\n跟便利屋的各位…\n和老師像這樣……"
20025-870 = "耶嘿嘿……\n是種，有點\n特別的感覺。"
20025-880 = "老師。果然就算，跟，\n跟我這種人在一起……\n也不會多開心……"
20025-890 = "沒那種事……是嗎？\n這，這樣啊……"
20025-900 = "……謝，謝謝你。\n老師。"
20025-1250 = "老，老老老老，老師！？\n歡，歡迎回來！\n還有，對，對不起！"
20025-1260 = "……嘿嘿……\n竟然會在這裡\n見到老師……"
20025-1270 = "沒，沒有！\n我沒有什麼\n特別的意思……！"
20025-1280 = "雖然不是很清楚……\n好像變成非常\n嚴重的事情了呢……"
20025-1290 = "要，要全部破壞掉嗎？"
20025-1300 = "亞瑠大人他……\n好像很開心……"
20025-1310 = "太好了。\n嘿，嘿嘿……"
20025-1320 = "騷動似乎終於\n平息下來了…… "
20025-1330 = "那個，那部機器人……\n是怎麼回事呢……？"
20025-1340 = "是，是！？\n有，有有有有\n有什麼事嗎，老師！？"
20025-1350 = "咦……？只是……\n想叫叫看而已？"
20025-1360 = "是，是這樣啊。\n耶，嘿嘿……"
20025-1370 = "在新年……\n跟便利屋的各位…\n和老師像這樣……"
20025-1380 = "耶嘿嘿……\n是種，有點\n特別的感覺。"
20025-1390 = "老師。果然就算，跟，\n跟我這種人在一起……\n也不會多開心……"
20025-1400 = "沒那種事……是嗎？\n這，這樣啊……"
20025-1410 = "……謝，謝謝你，老師。"
