[translation]
20025-740 = "서, 서서서서, 선생님?!\n어, 어서 오세요!\n그리고, 죄, 죄송합니다!"
20025-750 = "……헤헤……\n여기서 선생님을\n뵙다니…"
20025-760 = "아, 아뇨! 특별히\n무슨 뜻이\n있는 게 아니라…!"
20025-830 = "네, 네엣?!\n무, 무무무무, 무슨\n일이신가요, 선생님?!"
20025-840 = "네…? 그냥…\n불러 보셨다고요?"
20025-850 = "그, 그런가요.\n에, 헤헤…."
20025-860 = "새해를 맞이해……\n흥신소의 여러분…\n선생님과 이렇게……"
20025-870 = "에헤헤……\n조금, 특별, 한\n기분이에요. "
20025-880 = "선생님, 역시 저, 저\n같은 거랑 있어도……\n그렇게 즐겁지는……"
20025-890 = "아니…… 라고요?\n그, 러신가요…."
20025-900 = "……가, 감사, 합니다.\n선생님."
20025-1250 = "서, 서서서서, 선생님?!\n어, 어서 오세요!\n그리고, 죄, 죄송합니다!"
20025-1260 = "……헤헤……\n여기서 선생님을\n뵙다니…"
20025-1270 = "아, 아뇨! 특별히\n무슨 뜻이\n있는 게 아니라…!"
20025-1280 = "잘 모르겠지만……\n엄청난 일이\n되어버린 것 같네요……"
20025-1290 = "……전부,\n부숴버릴까요?"
20025-1300 = "아루 님께선……\n즐거우신 것 같아요……"
20025-1310 = "그건, 다행이네요.\n헤, 헤헤……"
20025-1320 = "드디어 소동이 잠잠해진\n모양이에요…… "
20025-1330 = "저기, 그 로봇은……\n뭐였을까요……?"
20025-1340 = "네, 네엣?!\n무, 무무무무, 무슨\n일이신가요, 선생님?!"
20025-1350 = "네…? 그냥…\n불러 보셨다고요?"
20025-1360 = "그, 그런가요.\n에, 헤헤…."
20025-1370 = "새해를 맞이해……\n흥신소의 여러분…\n선생님과 이렇게……"
20025-1380 = "에헤헤……\n조금, 특별, 한\n기분이에요. "
20025-1390 = "선생님, 역시 저, 저\n같은 거랑 있어도……\n그렇게 즐겁지는……"
20025-1400 = "아니…… 라고요?\n그, 러신가요…."
20025-1410 = "……가, 감사, 합니다.\n선생님."
