[translation]
20037-150 = "Hey, Sensei, I see you've been working hard."
20037-160 = "The water park... I'd love it...if I wasn't working here!"
20037-170 = "Everyone's so full of energy. Is it because they're here to play?"
20037-180 = "Oh, yay! It's almost time to leave work!"
20037-190 = "We've had our ups and downs, but we made it through the day. You worked hard as well, Sensei."
20037-200 = "The water slide?"
20037-210 = "No, it's not that it's scary... It's more like...b-bothersome, I'd say..."
20037-220 = "It's so hot... Working on a day like this is the worst!"
20037-230 = "On a hot day like this, it's essential to keep your sugar levels up."
20037-240 = "Therefore, donuts are a must."
20037-250 = "Ack! E-Everything's under control at the scene! ...Huh, Sensei? You startled me."
20037-480 = "Are you here for an exchange? We have a variety of options, so feel free to have a look around."
20037-490 = "Ahh... It's so nice and cool. You should relax a little while longer."
20037-500 = "The shop is now closed. How about we go out for a little after-work get-together?"
20037-510 = "Even for you, Sensei, I can't give it away for free."
20037-520 = "Check out the products, not me!"
20037-530 = "Wow?! There's such a thing?"
20037-540 = "S-Sensei, you're luckier than I thought!"
20037-550 = "Congrats! You got first place!"
20037-560 = "Is this it? Wow, we both worked really hard."
