[translation]
20038-280 = "大規模的交流會，\n對赤冬事務局來說\n也是前所未有的嘗試。"
20038-290 = "我也非常期待。"
20038-300 = "老師，穿上\n旗袍的潔莉諾醬，\n您已經見過了嗎？"
20038-310 = "呵呵，不覺得\n非常可愛嗎？"
20038-320 = "啊……\n我也很適合是嗎？"
20038-330 = "……那真是，\n太感謝您了。"
20038-340 = "（山海經的黑色君主……\n是遠比想像中強大的人）"
20038-350 = "（並非只有可愛\n　呢。呵呵）"
20038-360 = "本以為已經對騷動\n感到習以為常……"
20038-370 = "在親眼目睹\n他校的情形後……"
20038-380 = "總覺得有股\n奇妙的感受。"
20038-390 = "交流會，真的非常開心。"
20038-400 = "下次一定要招待\n門主大人來我們\n赤冬才行。呵呵。"
20038-410 = "山海經的公園\n既寬廣又乾淨呢。"
20038-420 = "非常適合街頭演說。"
20038-430 = "若是在這裡宣揚\n潔莉諾會長的偉大……"
20038-440 = "會演變成\n外交問題的對吧……"
20038-450 = "改變與不變。"
20038-460 = "……真是難以抉擇呢。"
20038-470 = "……雖然赤冬聯邦學園\n隨時都在改變就是了。"
20038-480 = "剛才從瑠美會長手中，\n收到了帶有安眠效果的茶葉。"
20038-490 = "今晚我打算用這個，\n為潔莉諾醬泡杯奶茶。"
20038-500 = "「鍊丹術研究會」\n這個社團，似乎正在\n研究返老還童的藥。"
20038-510 = "這……必須得\n紀錄下來呢。"
20038-620 = "為了紀念交流會，\n正在舉行兌換券活動！"
20038-630 = "只要有門主大人的玩偶，\n就能換取獎品！"
20038-640 = "還可以進行\n玩偶的兌換唷。"
20038-650 = "為了避免忘記兌換，\n請盡早使用。"
20038-660 = "這個玩偶，\n是由我設計的。"
20038-670 = "平常製作潔莉諾會長\n玩偶的經驗能派上用場\n真是太好了。"
20038-680 = "明明是為了當成\n兌換券而製作的……"
20038-690 = "但不知什麼原因，\n想留在手邊的學生相當多，\n導致回收不太順利。"
20038-700 = "……是不是獎品\n有什麼問題呢？"
20038-710 = "恭喜！\n中獎了！"
20038-720 = "中獎了！\n老師的運氣真好呢。"
20038-730 = "這是……1等獎呢！\n真不愧是老師！"
20038-740 = "哎呀，這麼多……"
20038-750 = "我這就去拿獎品，\n還請您稍等。"
20038-760 = "您好，老師。\n交流會的日程表\n已經整理完畢了。"
20038-770 = "由於兩校的學生都集結於此，\n必須處理的工作也堆積如山。"
20038-780 = "有什麼事嗎？"
20038-790 = "不可以唷。\n現在您得專心工作才行。"
20038-800 = "真是出色。\n如果這裡是赤冬的話，\n就能獻上勳章了說……"
20038-810 = "非常感謝您的協助。"
