[translation]
20037-90 = "やぁ、先生。お疲れー"
20037-100 = "ウォーターパーク……\n仕事じゃなきゃ、\n好きな場所なのに……"
20037-110 = "ウォータースライダー？"
20037-120 = "いや、\n怖いというより……め、\nめんどくさいかなぁ……"
20037-130 = "あっつい……\nこんな日に仕事だなんて、\n最悪だよ～"
20037-140 = "こういう熱い日に\nこそ糖分補給は\n大事だからね。"
