[translation]
20048-200 = "คุณครู มาแล้วเหรอคะ?\nเชิญนั่งตรงนี้ก่อนค่ะ"
20048-210 = "แม้แต่การขี้เกียจก็ต้องอาศัย\nเคล็ดลับและความพยายาม"
20048-220 = "ฮุฮุ... ฉันจะช่วยสอนให้เองค่ะ"
20048-230 = "ฉันยังนึกถึงงาน\nที่ค้างอยู่ตลอดเลยค่ะ..."
20048-240 = "ต่อให้ฉันไม่อยู่\nก็จะไม่เป็นไรใช่มั้ยคะ...?"
20048-250 = "ชอบรู้สึกเหมือนจะเกิด\nปัญหาขึ้นอยู่เรื่อยเลย... "
20048-260 = "ฉันคงแค่คิดไปเองใช่มั้ยคะ...?"
20048-270 = "ถึงเวลาต้องกลับแล้วสินะคะ"
20048-280 = "การจากไปเพื่อให้ได้คิดถึง\nสถานที่แห่งนี้แล้วมาอีกครั้ง"
20048-290 = "มีเรื่องอะไรเหรอคะ คุณครู?"
20048-300 = "ร้อนจังเลยนะคะ..."
20048-310 = "ต้องมีเครื่องดื่มเย็นๆ แล้วละค่ะ"
20048-320 = "อืม ไม่เอาชาเย็นนะคะ"
20048-330 = "คุณครูก็สนใจ\nหนังสือเล่มนี้เหรอคะ?"
20048-340 = "คุณครู แสงแดดจ้าไปหน่อย\nว่ามั้ยคะ?"
20048-350 = "เข้ามาในร่มกันแดด\nของฉันสิคะ"
20048-1070 = "ค่อยๆ ดูได้เลยนะคะ"
20048-1080 = "ฉันเตรียมของไว้\nเหลือเฟือเลยค่ะ"
20048-1090 = "เป็นครั้งแรกเลยนะคะที่ได้ต้อนรับลูกค้า"
20048-1100 = "เพราะงั้นก็...\nขอฝากตัวด้วยนะคะ คุณครู"
20048-1110 = "พอใจกับการซื้อของมั้ยคะ?"
20048-1120 = "เอาละ ทีนี้ก็กลับด้วยกัน\nเถอะค่ะคุณครู"
20048-1130 = "การต้อนรับก็ถือเป็น\nงานทางการทูตเหรอคะ...?"
20048-1140 = "พอคิดแบบนั้น\nฉันก็เบาใจขึ้นมาเลยนะคะ"
20048-1150 = "เรียงของ คิดเงิน เข้าก่อนออกก่อน..."
20048-1160 = "วันนี้รู้สึกว่าคำที่คุ้นเคย\nกลับแปลกหูขึ้นมาเลยค่ะ "
20048-1170 = "ตาถึงมากเลยค่ะ\nคุณครู"
20048-1180 = "ช่วยรอสักครู่นะคะ\nฉันจะห่อสินค้าให้ค่ะ"
20048-1190 = "เอ๋ ให้เลือกของฉันด้วยเหรอคะ?"
20048-1200 = "ฮุฮุ ฉันขอรับไว้แค่\nน้ำใจแล้วกันค่ะ"
20048-1210 = "ฮุฮุ ตอนนี้ฉันชำนาญ\nขึ้นมาหน่อยแล้วมั้ยคะ?"
