[translation]
20051-180 = "선생님!\n여기예요, 여기!"
20051-190 = "후훗, 너무 빨라서\n놓치셨군요?"
20051-200 = "자경단의\n슈퍼 매지컬 워리어!"
20051-210 = "테르밋 핑크입니다!"
20051-220 = "우와아!\n손님들이 엄청 많네요!"
20051-230 = "후후후……아무도\n눈치채지 못한 것\n같네요……."
20051-240 = "평범한 제가,\n사실은 자경단의\n슈퍼 에이스이자,"
20051-250 = "마법소녀라는\n사실을……!"
20051-260 = "변신은 풀렸지만,"
20051-270 = "마법은 끝이\n아니라구요! 에헤헤!"
20051-280 = "네! 테르밋 핑크입니다!\n우자와 레이사로도\n알려져 있죠!"
20051-290 = "후훗, 계속 연습해 온\n변신 포즈를……"
20051-300 = "여기서 보여드리죠!\n일단……"
20051-310 = "히얏!?"
20051-320 = "바, 방금 아는\n사람하고 눈\n마주친 것 같은……."
20051-330 = "이거요? 테르밋 핑크의\n마법봉입니다!"
20051-340 = "공식 스틱은\n좀 비싸서……"
20051-350 = "그래서, 집에 있는 걸\n꾸며봤습니다!"
20051-360 = "테르밋 핑크! 변신!"
20051-370 = "자! 평화를 지키러 가죠!"
20051-470 = "슈루루-\n빠방빠밤!!!\n반짝!"
20051-480 = "마법 장터에 어서 오세요-!"
20051-490 = "반값 스티커는 없다구요!?\n여긴 슈퍼가 아니니깐요!"
20051-500 = "이 옷은 팔지 않습니다!\n여벌이 없거든요!"
20051-510 = "기념품 가게 같아서 좋네요!"
20051-520 = "거래……\n즉, 계약을 맺는 것!"
20051-530 = "이게 어른의 재력……!\n히어로 같아요!"
20051-540 = "왠지 마법 아이템 같네요!"
20051-550 = "매지컬 쇼핑! 이군요!"
20051-680 = "와앗! 이건!\n카드 뽑기네요!\n엄청 오래간만입니다!"
20051-690 = "메달을 넣어서,\n이렇게! 그르륵! 각!\n하면 됩니다!"
20051-700 = "아직도 이런\n기계가 남아있었네요!"
20051-710 = "자 선생님!\n어서 돌려보죠!"
20051-720 = "자, 남은 메달 다-\n넣고 돌려보죠!"
20051-730 = "뭐가 나올까요!\n기대되네요!"
20051-740 = "여기 정말 멋지네요!\n여기가 제 집이면\n좋을 텐데……!"
20051-750 = "아앗!! 그건,\n울트라 레어!?"
20051-760 = "저도 딱 한 번밖에\n뽑아본 적 없어요,\n초 레어 카드라구요!"
20051-770 = "오옷! 슈퍼 레어입니다!\n은근히 보기 힘들어요!"
20051-780 = "골드! 좋네요!\n반짝반짝합니다!"
20051-790 = "아앗, 아……."
20051-800 = "그건 꽝 카드네요!\n저도 실물은\n처음 봅니다!"
