[translation]
23006-170 = "Welcome to the Momoyodou shop! Now, Master, what do you need today?"
23006-180 = "Oh, Sensei. Welcome."
23006-190 = "Now, choose to your liking!"
23006-200 = "The festival is over, but we're still open."
23006-210 = "I'll personally bless the remaining items. Look around, Sensei!"
23006-220 = "Momoyodou won't be stopped, even if there is a festival!"
23006-230 = "Well, we are the Festival Operations Department after all. Heehee."
23006-240 = "Great. Here it's... Moe moe...kyun!"
23006-250 = "Huh? This looks old? How so?!"
23006-260 = "Oh, that! No, no. It's not like I was thinking about taking the leftovers!"
23006-270 = "Your choice... I knew you had good taste, Sensei!"
23006-280 = "As always, thank you, Master!"
23006-290 = "That's a good item, right? Heehee."
