[translation]
26006-290 = "เอ๋? คุณครูเหรอคะ?\nเตรียมพวกของกิน\nมาด้วยรึเปล่าคะ?"
26006-300 = "ขอบคุณมากค่ะ!\nพวกเราจะตอบแทนคุณครู"
26006-310 = "ให้สมกับที่คุณครู\nนำของมาสนับสนุนพวกเราค่ะ"
26006-320 = "งานเทศกาล\nผ่านมาครึ่งทางแล้วนะคะ"
26006-330 = "คือว่าที่จริงแล้ว...\nถึงมันจะไม่ใช่เรื่องที่เกี่ยวกับ\nพวกฉันตั้งแต่แรกก็เถอะค่ะ"
26006-340 = "งานเทศกาลอีวาน คูปาลา\nเหลือเวลาอีกไม่มากแล้วค่ะ"
26006-350 = "ถ้าคุณครูมีอาหารที่ดูน่าอร่อย\nหรือว่าอุปกรณ์ สิ่งของที่จำเป็น\nสำหรับการใช้ชีวิตที่นี่ละก็..."
26006-360 = "รบกวนเอามาให้พวกเราด้วยนะคะ!"
26006-370 = "วันนี้เป็นวันสุดท้ายแล้ว\nคุณครู... ไม่ได้ลืมอะไรใช่ไหมคะ?"
26006-380 = "ถึงงานเทศกาลจะสิ้นสุดลงแล้ว\nแต่ถ้าคุณครูยังมีของใช้เหลืออยู่ละก็\nนำมาแลกที่ฉันได้เลยนะคะ!"
26006-390 = "ที่ห้องพิเศษ 227 น่ะ\nมีของหวานไม่พอตลอดเลยค่ะ..."
26006-400 = "เมื่อไหร่จะได้กลับไป\nที่อาคารเรียนหลักกันนะ..."
26006-410 = "ว้าว...\nน่ากินจังเลย..."
26006-420 = "คะ? พูดจริงเหรอคะ?\nฉันรับไว้ได้จริงๆ เหรอคะ?"
