[translation]
26008-10 = "เชิญค่ะ คุณครู!\nยินดีต้อนรับสู่\nร้านเฮียกคิยาโค สาขาริมทะเลค่ะ!"
26008-20 = "คุณครู?! ตอนนี้\nยังเตรียมการ\nไม่เสร็จดีเลยนะคะ...?!"
26008-30 = "อะ...เอาเป็นว่า\nเชิญทางนี้ก่อนค่ะ!"
26008-40 = "หาของที่ต้องการ\nเจอแล้วหรือยังคะ?"
26008-50 = "ร้านเฮียกคิยาโคของเรา\nจะต้องรุ่งเรืองยิ่งขึ้นค่ะ\nเอาละค่ะ มาพยายามกันเถอะค่ะ!"
26008-60 = "จัดการร้านหลายๆ ร้านพร้อมกัน\nนี่ก็เป็นงานใหญ่เอาเรื่องอยู่\nเหมือนกันนะคะ..."
26008-70 = "แต่ว่ามันก็สนุกดีอยู่หรอกค่ะ!"
26008-80 = "เอ๋? คุณครู!\nฉันไม่ใช่ของขายนะคะ!"
26008-90 = "แล้วอีกอย่างตอนนี้...\nก็ไม่ใช่เวลาเปิดทำการด้วยค่ะ..."
26008-100 = "หาของที่ต้องการ\nเจอแล้วหรือยังคะ?"
26008-110 = "ร้านเฮียกคิยาโคของเรา\nจะต้องรุ่งเรืองยิ่งขึ้นค่ะ\nเอาละค่ะ มาพยายามกันเถอะค่ะ!"
26008-120 = "จัดการร้านหลายๆ ร้านพร้อมกัน\nนี่ก็เป็นงานใหญ่เอาเรื่องอยู่\nเหมือนกันนะคะ..."
26008-130 = "แต่ว่ามันก็สนุกดีอยู่หรอกค่ะ!"
26008-140 = "เอ๋? คุณครู!\nฉันไม่ใช่ของขายนะคะ!"
26008-150 = "แล้วอีกอย่างตอนนี้...\nก็ไม่ใช่เวลาเปิดทำการด้วยค่ะ..."
26008-480 = "ฉันเตรียมของหลายๆ อย่าง\nที่จะเป็นประโยชน์\nตอนอยู่ที่ทะเลมาด้วยค่ะ!"
26008-490 = "ถ้ามีสิ่งของที่ไม่ได้ใช้\nเอามาแลกได้นะคะ!"
26008-500 = "น่าเสียดาย แต่ว่าร้านริมทะเล\nปิดให้บริการแล้ว..."
26008-510 = "แต่ว่า...! ไม่เป็นไรหรอกค่ะ\nควาทรงจำที่สนุกสนาน\nจะอยู่กับเราตลอดไป!"
26008-520 = "ค่า ค่า~\nเรียกชิซุโกะเหรอคะ?"
26008-530 = "ของดีราคาถูกๆ!\nคือพื้นฐานของการขายของค่ะ"
26008-540 = "ขอบคุณที่มาใช้บริการค่า!"
26008-550 = "อ๊ะ เลือกได้ยอดเยี่ยมเลยค่ะ!\nฉันก็แนะนำชิ้นนั้นค่ะ"
26008-560 = "พอใจกับการเลือกซื้อสินค้ารึเปล่าคะ?\nการบอกปากต่อปากก็เป็นเรื่องสำคัญ\nช่วยพูดต่อเยอะๆ เลยนะคะ!"
26008-570 = "ค่า! นี่ค่ะ!\nขอบคุณมากๆ เลยค่า~!"
