[translation]
26012-260 = "어서 오세요! 선생님은\n슬라이드와 파도풀,\n어느 쪽이 좋으신가요?"
26012-270 = "나카츠카사 키리노,\n이번에는 라이프가드가\n되었습니다!"
26012-280 = "워터파크에 괴물체라니,\n말도 안 되는 일이……!"
26012-290 = "이번에야말로\n본관이 활약할\n차례군요!"
26012-300 = "선생님과 손님들의\n안전은 제가\n지키겠습니다!"
26012-310 = "걱정 많이 했는데,\n잘 끝났네요!\n수고하셨습니다!"
26012-320 = "수영복 착용을 위해서,\n맛집 탐방도 한동안\n참았습니다만……."
26012-330 = "정신을 차려 보니\n푸드코트 순례를\n하고 말았습니다……."
26012-340 = "워터 슬라이드는\n어떠신가요?"
26012-350 = "본관이 최고로 짜릿한\n슬라이드를 추천해\n드리겠습니다!"
26012-360 = "아이들이 노는 모습,\n귀엽네요!"
26012-370 = "네? 본관이 필요한\n일이 있나요?\n무엇이든 말해주세요!"
26012-570 = "오늘 할 일입니다!\n꽤 많지만 힘내볼까요!"
26012-580 = "하나씩 차근차근!\n본관도 힘내겠습니다, 선생님!"
26012-590 = "아하핫! 라이프가드를\n간지럽히는 건 금지입니다!"
26012-600 = "후후, 그렇게 보채지 않으셔도,\n본관이 도와드릴 테니까요!"
26012-610 = "역시 선생님이시네요! 대단합니다!"
26012-620 = "수고하셨습니다, 선생님!"
