[translation]
26010-270 = "히이…… 공포 소설 속에\n나오는 어촌 마을 같아……"
26010-280 = "빨리 학교로\n돌아가고 싶어……"
26010-290 = "아니, 저희 학교는\n이미 없어졌었죠……"
26010-300 = "이곳의 주민 여러분은\n너무 무서워서……\n조사를 위해\n이야기를 하다보면……"
26010-310 = "도, 도망치고\n싶어져요……"
26010-320 = "아까 선장님께\n따듯한 커피를\n받았어요."
26010-330 = "생각보다……\n그렇게 무서운 분은\n아니실지도……"
26010-340 = "이 마을도\n보다 보니 조금은\n정이 든 것 같네요."
26010-350 = "……그래도 역시 제게는\n코우사기 공원이\n제일 안심되는\n장소지만요."
26010-360 = "호, 호, 혹시 부르셨나요……?"
26010-370 = "(어쩌다가 이런\n외진 마을까지\n오게 되어버린 걸까……)"
26010-380 = "이 머리는 작전을\n나오기 직전에\n미야코 쨩이 땋아줬어요."
26010-390 = "후후…… 이거,\n귀여울지도……"
26010-400 = "참새도, 족제비도,\n갈매기도……"
26010-410 = "야생 동물들은\n어째서 제게 계속\n다가오는 걸까요……?"
26010-420 = "혹시…… 예쁜 돌이나 조개를\n찾으셨다면 제게 가져다주세요."
26010-430 = "아, 선생님.\n저와 함께 조약돌 수집……\n하지 않으시겠어요?"
26010-440 = "슬슬 돌아가야 할\n시간인 것 같지만……"
26010-450 = "앞으로도 종종……\n조약돌 수집, 같이 해 주세요."
26010-460 = "에, 그, 그러니까……"
26010-470 = "물론 제가 조약돌처럼\n존재감이 없기는 하지만……"
26010-480 = "그렇게 만져주셔도……\n제 존재감이 강해지지는\n않을 걸요……"
26010-490 = "이 조약돌……\n정말 예쁘네요……!"
26010-500 = "죄송합니다……\n이 정도밖에 드릴 수 없어서……"
26010-510 = "하얗고……\n반짝거려……"
26010-520 = "변변치 않지만, 이거라도……\n받아주시겠어요……?"
