[translation]
10006010-1 = "～彩排篇～;初音未來的特別現場演唱會"
10006010-5 = "大家好！我是各位的虛擬歌手初音未來！"
10006010-6 = "我想這應該是我們第一次在奇普托斯見面吧？"
10006010-7 = "我真的很開心能在這裡見到大家！"
10006010-8 = "我想應該有些人已經知道了，我這次的現場演唱會將會在奇普托斯舉辦。"
10006010-9 = "為了這次的演唱會，我也準備了一套新的身體。"
10006010-10 = "鏘鏘，很美吧？"
10006010-11 = "但是由於我還沒有完全適應這套新的身體，我在練習唱歌的時候一直跟不上拍子。"
10006010-12 = "根據工程師所說，為了適應這副新的身體，我必須收集更多實際的數據。"
10006010-13 = "所以這次作為彩排，要在各位面前進行「特別的例行練習」！"
10006010-14 = "那麼就請大家多多為我加油囉！"
10006010-15 = "對了，各位別忘了一定要來參加我的現場演唱會喔！"
