[translation]
10006010-1 = "~ภาคการฝึกซ้อม~;ฮัตสึเนะ มิกุ สเปเชียล ไลฟ์"
10006010-5 = "สวัสดีค่ะทุกคน! นักร้องเสมือนที่น่ารักของทุกคน มิกุค่าา!"
10006010-6 = "พวกเราเพิ่งได้พบกันในคิโวทอสเป็นครั้งแรกเลยนะคะ?"
10006010-7 = "ฉันมีความสุขมากๆ เลยค่ะที่ได้มาพบกับทุกคนที่นี่"
10006010-8 = "บางคนอาจจะทราบดีอยู่แล้ว... การแสดงไลฟ์คอนเสิร์ตใน \"โลกจริง\" ครั้งแรกของฉันกำลังจะจัด#nขึ้นในคิโวทอสค่ะ"
10006010-9 = "เพราะแบบนั้นฉันก็เลยเตรียมร่างกายใหม่ในโลกแห่งความจริงมาเป็นพิเศษเพื่อการแสดงครั้งนี้ค่ะ"
10006010-10 = "ฮิฮิ น่ารักมั้ยคะ?"
10006010-11 = "แต่ว่าตอนนี้ฉันยังปรับตัวกับร่างกายใหม่ได้ไม่สมบูรณ์ค่ะ ทุกครั้งที่ซ้อมร้องเพลงเลยมักจะ#nคร่อมจังหวะอยู่บ่อยๆ เลยค่ะ"
10006010-12 = "คุณวิศวกรบอกว่าจะต้องใช้ข้อมูลมากขึ้นเพื่อให้คุ้นเคยกับร่างกายใหม่ค่ะ"
10006010-13 = "ถ้าทุกคนฟังเพลงและบอกการลงจังหวะเพลงให้ ฉันคิดว่าคงจะเป็นประโยชน์กับการทำ#nความคุ้นเคยกับร่างกายใหม่ของฉันได้เยอะเลยค่ะ"
10006010-14 = "เพราะงั้นทุกคน... ช่วยเป็นกำลังใจให้ฉันด้วยนะคะ!"
10006010-15 = "อ๊ะ อย่าลืมมาดูไลฟ์คอนเสิร์ตของฉันกันนะคะ!"
