[translation]
1003706-1 = "保安委員長的誤會"
1003706-2 = "赤冬聯邦學園．第8地區郊外"
1003706-3 = "妳們，做出這種事以為會沒事嗎！"
1003706-4 = "回到事務局後，避免不了肅清哦！"
1003706-5 = "吵死了，閉嘴！"
1003706-6 = "好了啦給我老實點！！"
1003706-7 = "咕，就因為把學生證放著了……"
1003706-8 = "[s]「……這個，發生什麼事？」"
1003706-9 = "嗯……？你，是誰啊？"
1003706-10 = "竟然在這麼偏僻的地方，不是笨蛋就是間諜。"
1003706-11 = "讓我看可以證明身份的東西！不然的話，也將你做為間諜逮捕！"
1003706-12 = "[s]讓對方看身分證"
1003706-13 = "這是……什，夏萊的老師！？也就是那個書記長頻繁掛在嘴邊的[ruby=同志]「Товарищ」[/ruby]，指的就是你嗎……！？"
1003706-14 = "這，這真是失禮了。因為是這種偏遠地區，所以情報等等傳遞的也比較慢……第一次拜見了身姿。"
1003706-15 = "老師的活躍我在「赤熊」清楚知道。能見到您我很榮幸！"
1003706-16 = "[s1]「謝，謝謝。話說回來這個狀況是……」\n[s2]「為什麼瑪麗娜被拘捕了呢？」"
1003706-17 = "啊啊，這個自稱「保安委員長」的間諜嗎。"
1003706-18 = "啊啊，這個自稱「保安委員長」的間諜嗎。"
1003706-19 = "這個笨蛋間諜，沒有身分證就想進入限制區域。"
1003706-20 = "在這之上，還厚臉皮的說「自己是保安委員長」……"
1003706-21 = "我是真的保安委員長！為什麼不相信！"
1003706-22 = "閉嘴，妳這個可惡的間諜！妳怎麼可能是保安委員長啊！？"
1003706-23 = "「赤熊」的報導上寫著，「瑪麗娜保安委員長即使身高有點矮，卻纏繞著恐怖的氣勢，是不管什麼樣的猛獸都無法接近的豪傑」哦！"
1003706-24 = "說著「在散步中迷路了」，還被貓追著跑的笨蛋竟然是保安委員長，這怎麼可能啊！"
1003706-25 = "那，那是……"
1003706-26 = "說到「保安委員長」就是警備潔莉諾會長身邊的代表人物，明明是管理會長一舉一動的重責……"
1003706-27 = "然而妳，連潔莉諾會長的身高都沒辦法回答！"
1003706-28 = "像妳這樣的笨蛋竟然想自稱瑪麗娜大人，厚臉皮也要有個程度！"
1003706-29 = "真正的瑪麗娜保安委員長，是比妳還要更加偉大的人！"
1003706-30 = "……"
1003706-31 = "[s]「那個，其實那個……」"
1003706-32 = "……老師，沒關係。"
1003706-33 = "雖然感覺情報錯綜複雜……不過我沒辦法破壞在這種偏遠地區也在努力工作的，這些保安委員們的美夢……"
1003706-34 = "所以現在，裝作不認識我。拜託了……！"
1003706-36 = "（這之後，順利的說服保安委員，總算是解放了瑪麗娜）"
1003706-38 = "咕唔，這什麼醜態……"
1003706-39 = "那些保安委員，明明那麼的信賴身為委員長的我，關鍵的我卻是這個樣子……而且最終還被老師救出來……"
1003706-40 = "我已經沒有，再繼續當保安委員長的資格了。"
1003706-41 = "回去事務局，馬上向潔莉諾會長提出……"
1003706-42 = "[s3]「沒有那個必要吧。」\n[s4]「瑪麗娜確實是，出色的保安委員長唷。」"
1003706-43 = "……為什麼？"
1003706-44 = "……為什麼？"
1003706-45 = "我既贏不了流浪貓，也馬上就迷路。連對潔莉諾會長的個人資料都沒有自信。明明是那麼多缺點的保安委員長……"
1003706-46 = "就算是這樣的我，也能繼續自稱保安委員長嗎……？"
1003706-47 = "[s]「那是，那個……」"
1003706-48 = "不要在這裡語塞！！"
1003706-49 = "要替我應援的話，給我確實做到最後！至少提出我的一兩個優點啊！"
1003706-50 = "[s5]「瑪麗娜，會重視別人的心情和說的話之類的！」\n[s6]「因為瑪麗娜很會打掃廁所！」"
1003706-51 = "……那個和保安委員長的工作，有什麼關係？"
1003706-52 = "你說因為會確實聽取部下們說的話並相信，保安委員們也能安心行動……？"
1003706-53 = "確實……保安委員們在政變引起的時候也完全不抱怨，相信了我並跟著我……"
1003706-54 = "……那個和保安委員長的工作，有什麼關係？"
1003706-55 = "你說不管從哪種意義上都能保護學生，是貨真價實的保安委員會的活動……？"
1003706-56 = "原來如此……確實據我所知，赤冬聯邦學園在衛生面上幾乎沒有發生過事故。"
1003706-57 = "……哼，沒辦法呢。既然老師那麼說的話，現在就先把這個想法放一旁吧。"
1003706-58 = "能確實接任的後輩，似乎也還沒出現……也有說就算是猴子也會從樹上摔落一次嘛！"
1003706-59 = "今後我會以持續表現出的功績，挽回今天的名譽的！"
1003706-61 = "（這之後，和步伐輕快的瑪麗娜一起回到了事務局）"
1003706-62 = "（然而那個歸路，也因為瑪麗娜滿滿的自信搞錯而迷路了……）"
