[translation]
1003506-1 = "นักแปลนิรนาม"
1003506-2 = "(คุณครูซื้อเครื่องดื่มและหมากฝรั่งแก้ง่วงจากร้านสะดวกซื้อแล้วไปที่ห้องสมุดเก่าตามคำขอของอุย)"
1003506-3 = "(ซื้อแผ่นแปะแก้ปวดคอมาให้ด้วยเพราะอุยเหมือนจะหักโหมมากเกินไป)"
1003506-5 = "ข้างในห้องสมุดเก่า"
1003506-8 = "หืม...? อะไรกัน..."
1003506-9 = "รู้ได้ไงว่าประตูเปิดอยู่... แล้วใครบอกให้เข้ามาตามใจชอบ..."
1003506-10 = "[s1] \"อุย...?\"\n[s2] \"เสียงฟังดูเหนื่อยเอามากๆ เลย...\""
1003506-11 = "...?"
1003506-12 = "...?"
1003506-13 = "อ๊ะ... คุณครูเองเหรอคะ ขออภัยด้วยค่ะ... ฉันขอให้คุณครูมาช่วยโดยที่ไม่เกรงใจเลย... ขอบคุณที่มานะคะ"
1003506-14 = "เชิญทางนี้สิคะ... "
1003506-17 = "― ขะ... ขอบคุณนะคะ... คุณครู[wa:4820] "
1003506-19 = "― ขอบคุณ... ที่ดูแลฉัน...[wa:1340] "
1003506-22 = "― อันนี้...ที่ฉันทำอยู่น่ะเหรอคะ?[wa:1240] "
1003506-24 = "― กำลังถอดความหนังสืออยู่น่ะค่ะ[wa:2780] "
1003506-27 = "― ที่ห้องสมุดเก่านี้..."
1003506-29 = "― มีหนังสือโบราณที่อ่านยาก อยู่ค่อนข้างเยอะเลยค่ะ[wa:1310] "
1003506-32 = "― เด็กๆ พวกนี้ก็คงจะอยากบอกสิ่งที่ตัวเองมี[wa:5300] "
1003506-34 = "― ให้ใครบางคนได้รับรู้แน่ๆ ค่ะ...[wa:10] "
1003506-37 = "― แต่ก็ไม่มีใครแวะมาอ่านเลยค่ะ... เพราะงั้นแล้วฉันก็เลย...[wa:2820] "
1003506-40 = "― ขอโทษนะคะ ฉันพูดอะไรไม่เข้าท่า ใช่มั้ยคะ?[wa:3680] "
1003506-43 = "[ns3] \"ไม่เลย ครูว่ามันจับใจดีออก\" \n[ns4] \"อุยเป็นเด็กที่วิเศษจังเลยนะ\""
1003506-46 = "― ......!! เอ่อ... คือว่า.. คือ...[wa:3760] "
1003506-48 = "― ถะ...ถ้ามาชมกันแบบนี้ละก็... คือว่า...[wa:2240] "
1003506-51 = "― ฉันไม่รู้ว่าต้องตอบยังไง..."
1003506-53 = "― คิดคำพูดไม่ออกเลยค่ะ... ฮือ...[wa:4650] "
1003506-56 = "ความรู้สึกนี้มัน... แปลกจังเลยนะคะ"
1003506-57 = "ฉันมานั่งถอดความแบบนี้ในทุกครั้งที่มีเวลาว่าง... แต่ไม่คิดเลยว่าจะได้ยินคำชมแบบนี้ค่ะ"
1003506-58 = "แถมยังได้ยินจากคุณครูอีก..."
1003506-59 = "ที่จริงฉันคิดว่าคนอื่นจะคิดว่าเป็นเรื่องไม่เข้าท่าค่ะ น่าจะมีหลายคนเลยที่คิดแบบนั้น..."
1003506-60 = "แต่ฉันก็ไม่สนใจเท่าไหร่ และคิดเสียว่าเป็นงานที่ฉันต้องทำ..."
1003506-61 = "[s5] \"ไม่หรอก ไม่ใช่งานที่ไม่เข้าท่าสักนิด\"\n[s6] \"ครูว่าสิ่งที่อุยทำจะมีค่าสำหรับบางคนนะ\""
1003506-62 = "คุณครู..."
1003506-63 = "คุณครู..."
1003506-64 = "[s7] \"พอได้เห็นแล้วครูมั่นใจขึ้นเลยล่ะ\"\n[s8] \"ว่าทำไมสมาชิกคนอื่นถึงเคารพอุยในฐานะหัวหน้าชมรม\"\n[s9] \"การทุ่มเททำเรื่องแบบนี้คนเดียวมาตลอดถือว่ายอดเยี่ยมมาก\""
1003506-65 = "ฮือ..."
1003506-66 = "ฮือ..."
1003506-67 = "ฮือ..."
1003506-68 = "......"
1003506-69 = "ขอบคุณนะคะ ฉันมีแรงทำต่อแล้วค่ะ"
1003506-70 = "ถ้าทุกคนในโลกใจดีเหมือนคุณครูกันหมด... ฉันก็คงคิดอยากออกไปท่องโลกข้างนอกบ้างค่ะ"
1003506-71 = "แต่ฉันก็รู้ดีค่ะว่าคนข้างนอกไม่ได้เย็นชาหรือเลวร้ายไปทั้งหมด"
1003506-72 = "ฉันรู้ดี... แต่ก็ไม่ใช่ว่ารู้จักแล้วจะดีไปทั้งหมดนี่คะ..."
1003506-73 = "ที่จริงสมาชิกชมรมที่น่ารักของฉันก็เน้นย้ำเรื่องนั้นกับฉันอยู่บ่อยๆ..."
1003506-74 = "ถึงฉันจะชอบพวกเขา แต่ลึกๆ แล้วฉันก็รู้สึกลำบากใจค่ะ อืม..."
1003506-75 = "จะว่าไป คุณครูไม่พูดอะไรแบบนั้นกับฉันเลยนะคะ"
1003506-76 = "แม้จะเป็นถึงคุณครูก็เถอะ..."
1003506-77 = "แถมยังมาช่วยใส่ใจฉันอีก... ไหนจะเรียกหนังสือว่า 'เด็ก' เหมือนกับฉัน..."
1003506-78 = "ฉันตกใจเอามากๆ เลยค่ะ นี่สินะคนที่เป็นคุณครู"
1003506-79 = "เพราะงั้นฉันก็เลยอยากพึ่งพิงคุณครูขึ้นมาค่ะ"
1003506-80 = "ถึงตอนนี้จะยังไม่ชัดเจนว่าอยากพึ่งพิงอะไรก็เถอะ..."
1003506-81 = "แต่ต่อไปในอนาคตคงได้คำตอบ... ถึงตอนนั้นฉันจะบอกคุณครูอีกที แบบนี้ได้มั้ยคะ?"
1003506-82 = "[s10] \"ได้อยู่แล้ว ไม่ต้องคิดมาก\"\n[s11] \"ไว้บอกครูตอนที่สะดวกใจก็ได้\""
1003506-83 = "ฮู่ว..."
1003506-84 = "ฮู่ว..."
1003506-85 = "ค่ะ ไว้ฉันจะมาบอก"
1003506-86 = "ขอบคุณมากนะคะคุณครู"
1003506-88 = "(จากนั้นคุณครูก็อยู่เป็นเพื่อนจนอุยถอดความหนังสือเสร็จ)"
1003506-89 = "(อุยหลับเป็นตายหลังจากทำงานเสร็จ คุณครูเลยห่มผ้าให้แล้วปิดประตูห้องสมุดเก่ากลับมายังชาเล่ต์)"
