[translation]
1003803-1 = "SRT to the Rescue!"
1003803-2 = "Downtown Kivotos"
1003803-3 = "Miyako looked to be deep in thought in front of a shop window."
1003803-4 = "..."
1003803-5 = "[s] \"Miyako?\""
1003803-6 = "Hmm..."
1003803-7 = "[s] \"Miyako!\""
1003803-8 = "Augh! Oh... Hello, Sensei."
1003803-9 = "Apologies. My head was in the clouds."
1003803-10 = "[s] \"What were you looking at?\""
1003803-11 = "Oh, these animals at the pet shop."
1003803-12 = "I like to stop by and see them when I'm dispatched in the area."
1003803-13 = "Look, they added some rabbits recently."
1003803-14 = "Don't you think rabbits are adorable?"
1003803-15 = "Those stubby little legs, their floppy ears... I could watch them all day."
1003803-16 = "[s] \"Why don't you adopt one?\""
1003803-17 = "That's..."
1003803-18 = "Welcome back, customer!"
1003803-19 = "Are you interested in adopting a rabbit?"
1003803-20 = "Wh-What? Oh, no... I just..."
1003803-21 = "Oh... I see. You stop by often to visit them, so I thought you were thinking of taking one home."
1003803-22 = "You always look at them with so much love. They're very friendly and easy to train. Why don't you consider adopting one?"
1003803-23 = "W-Well... I would like to... But I don't have the money or circumstances. It would be irresponsible..."
1003803-24 = "[s] \"We'd like the white one in the front.\""
1003803-25 = "Sensei?! What are you doing?"
1003803-26 = "A gift? I don't know if I'm ready for a pet..."
1003803-27 = "And the RABBIT Squad is operating out of a park right now... I wouldn't be able to give it a proper home."
1003803-28 = "[s1] \"Wouldn't it be better to be in the park than a cage?\"\n[s2] \"You're the most responsible person I know.\""
1003803-29 = "S-Sensei..."
1003803-30 = "It would almost be like a rescue operation."
1003803-31 = "S-Sensei..."
1003803-32 = "It is sad to see it living behind a store window."
1003803-33 = "Thank you, Sensei. Really."
1003803-34 = "I'll make sure to take good care of her."
1003803-36 = "Miyako looked happy as she returned with her new rabbit in her arms."
