[translation]
102-1 = "#title;물건 회수 특별의뢰"
102-2 = "#place;총학생회 상황실"
102-3 = "3;모모카;14;학생들 사이에서 <슬럼피아> 라고 불리는 그 폐허 단지는 원래 모모 그룹에서 <유토피아>라는 이름으로 건설한 테마 파크였어.\n#3;a\n#3;em;[음표]"
102-4 = "3;모모카;06;물론 경영 부진으로 반년도 안 되어 폐업해버렸지만. (와작)"
102-5 = "3;모모카;23;문제는…… 최근 요상한 괴담들이 떠돌기 시작해서 말이야."
102-6 = "3;모모카;18;전기도 끊긴 시설의 기구들이 밤이면 혼자서 움직인다거나, 가까이 다가간 학생들을 삼켜 버렸다거나…….\n#3;em;[반응]"
102-7 = "3;모모카;08;멋대로 돌아가는 놀이 기구야 아무래도 상관없지만, 학생들이 사라지는 건 큰 문제니까.\n#3;em;[속상함]\n#3;stiff"
102-8 = "3;모모카;05;선생이 가서 무슨 일이 일어나고 있는지 조사해줬으면 좋겠어."
102-9 = "3;모모카;19;뭐든 좋으니 혹시 단서를 발견하거든 바로 총학생회에 가져다줘.\n#3;em;[반응]\n#3;hophop"
