[translation]
102-1 = "ภารกิจพิเศษ รับของขวัญ"
102-2 = "ห้องยุทธการ องค์การนักเรียน"
102-3 = "ในหมู่นักเรียนมีการพูดถึงพื้นที่ร้างที่ชื่อว่า \"สลัมเพีย\" ที่แต่เดิมเป็นพื้นที่ที่ทางโมโมกรุ๊ป#nคิดจะสร้างเป็นสวนสนุกที่ชื่อว่า \"ยูโทเปีย\" อยู่ด้วย"
102-4 = "แต่เพราะการบริหารที่ไม่ดี ทำให้ที่นั่นเลิกกิจการมานานกว่าครึ่งปีแล้ว (ง่ำๆ)"
102-5 = "ปัญหาก็คือ... ไม่นานมานี้มีเรื่องเล่าแปลกๆ เกี่ยวกับที่นั่นด้วยน่ะ"
102-6 = "ทั้งๆ ที่อุปกรณ์ที่นั่นก็ไม่ได้เชื่อมต่อกับไฟฟ้าเอาไว้ แต่ว่าพอถึงตอนกลางคืน#nอุปกรณ์พวกนั้นจะเคลื่อนไหวได้ และคืบคลานเข้ามาหาพวกนักเรียน…"
102-7 = "ถ้าเป็นแค่เรื่องที่พวกเครื่องเล่นเคลื่อนไหวได้เองก็ไม่เป็นไรหรอก แต่ว่าการที่พวกนักเรียนหายตัวไป#nมันเป็นปัญหาใหญ่เลยล่ะ"
102-8 = "ฉันเลยอยากให้คุณครูไปตรวจสอบเรื่องที่เกิดขึ้นที่นั่นน่ะ"
102-9 = "ถ้าเจอเบาะแสก็รบกวนแจ้งทางองค์การนักเรียนทันทีเลยนะ"
