[translation]
12195-2 = "You know what, Hoshino."
12195-3 = "There's something I want to say."
12195-4 = "The first time I saw you, I kept pinching my cheeks, thinking I must be dreaming."
12195-5 = "Having someone as cute, strong, and reliable as you by my side...it made me so happy..."
12195-6 = "Ugh... I'm not smart enough to explain it properly, but..."
12195-7 = "Just being able to stand here and talk to you like this...feels like a miracle to me."
12195-8 = "...We see each other every day."
12195-9 = "I saw you yesterday, I saw you today, and I'll see you tomorrow too. What's the big deal?"
12195-10 = "Aw, well... I know that, but..."
12195-11 = "Miracles are supposed to be rare and extraordinary things."
12195-12 = "...Mmm. No, Hoshino. I think differently."
12195-13 = "I might be a fool...but I know this much for sure."
12195-14 = "One day, Hoshino, you're going to have cute underclassmen of your own. And when you do..."
12195-16 = "..."
12195-19 = "She should be on the other side!"
12195-20 = "It's not giving away. Try one more time..."
12195-22 = "A-Ayane?! How did you...?"
12195-23 = "I got on a helicopter on loan from Schale! Anyway, where's Hoshino?"
12195-24 = "Here! Help us get the door open!"
12195-25 = "Move aside!!"
12195-26 = "*BANG*"
12195-28 = "(What's going on...?)"
12195-29 = "(My body... I can move again... Is this a dream...?)"
12195-30 = "(I thought I could hear everyone's voices. I must be dreaming.)"
12195-31 = "(It sounded like...)"
12195-36 = "(This way...maybe...?)"
12195-37 = "(Even if it's just a dream... Just one last time... Let me hear them...)"
12195-40 = "*clunk*"
12195-42 = "Hoshino!!"
12195-46 = "Huh...? But how?"
12195-47 = "How come...? I thought I was..."
12195-50 = "[ns] \"Hoshino.\""
12195-52 = "Hoshino"
12195-53 = "...Oh."
12195-56 = "Hoshino"
12195-57 = "Now I get it. This must be Sensei's doing."
12195-60 = "Hoshino"
12195-61 = "The adult came through after all. Heh."
12195-66 = "Serika"
12195-67 = "[7cd0ff]Foreclosure Task Force[-]"
12195-68 = "W-Welcome back, Hoshino."
12195-71 = "Nonomi"
12195-72 = "[7cd0ff]Foreclosure Task Force[-]"
12195-73 = "Ah! Serika beat me to it! You said it was too embarrassing, and now look at you!"
12195-76 = "Serika"
12195-77 = "[7cd0ff]Foreclosure Task Force[-]"
12195-78 = "Sh-Shut up! It doesn't matter what the order is!"
12195-81 = "Shiroko"
12195-82 = "[7cd0ff]Foreclosure Task Force[-]"
12195-83 = "We're glad you're okay."
12195-86 = "Ayane"
12195-87 = "[7cd0ff]Foreclosure Task Force[-]"
12195-88 = "Yes! Welcome back!"
12195-91 = "Nonomi"
12195-92 = "[7cd0ff]Foreclosure Task Force[-]"
12195-93 = "Yup, yup! Welcome back!"
12195-96 = "Shiroko"
12195-97 = "[7cd0ff]Foreclosure Task Force[-]"
12195-98 = "Welcome back, Hoshino."
12195-102 = "Hoshino"
12195-103 = "[7cd0ff]Foreclosure Task Force[-]"
12195-104 = "...Ahaha."
12195-107 = "Hoshino"
12195-108 = "[7cd0ff]Foreclosure Task Force[-]"
12195-109 = "...What? Why are all of you looking at me like that?"
12195-112 = "Hoshino"
12195-113 = "[7cd0ff]Foreclosure Task Force[-]"
12195-114 = "Ohhh, now I get it. You want me to say the line, don't you?"
12195-117 = "Serika"
12195-118 = "[7cd0ff]Foreclosure Task Force[-]"
12195-119 = "Sh-Shut up! Don't keep us in suspense!"
12195-124 = "Hoshino"
12195-125 = "[7cd0ff]Foreclosure Task Force[-]"
12195-126 = "Heh!"
12195-129 = "Hoshino"
12195-130 = "[7cd0ff]Foreclosure Task Force[-]"
12195-131 = "I can't refuse a favor from my adorable ones..."
12195-134 = "I'm home."
