[translation]
1300702-1 = "誠實的獎勵"
1300702-2 = "（慵懶的午後時分，為了買點心去了一趟市區的甜點店）"
1300702-5 = "西式糕點店「L'Oiseau．Bleu」"
1300702-6 = "歡迎光臨「L'Oiseau Bleu」！"
1300702-7 = "[s] 「……淳子？」"
1300702-8 = "哦，老師？你怎麼會來這裡？"
1300702-9 = "你是來買點心的？喔……這間店的甜點都挺貴的耶……"
1300702-10 = "啊，對喔……因為老師有大人的卡片……"
1300702-11 = "大人真好～可以盡情地吃自己想吃的甜點～"
1300702-12 = "我？你問我在這裡做什麼？"
1300702-13 = "如你所見，我在這間店裡打工。"
1300702-14 = "早午晚三餐，還有飯後點心的餐費……開銷真的挺高的。"
1300702-15 = "為什麼高級食材都這麼貴呢？#n學生只靠零用錢根本買不起嘛！"
1300702-16 = "我也不想做打工這種麻煩事……但為了吃美食實在沒有辦法。"
1300702-17 = "[s] 「工作辛苦嗎？」"
1300702-18 = "嗯？不會喔。我又不需要親自去烤麵包。"
1300702-19 = "而且在「L'Oiseau．Bleu」這邊，員工可以把當天剩下來的甜點帶回家。"
1300702-20 = "居然能免費吃到平時買不起吃不了的甜點，光是這點就足夠說服我在這裡工作了！"
1300702-21 = "[s] 「有推薦的餐點嗎？」"
1300702-22 = "推薦餐點？這個嘛……"
1300702-23 = "雖然這間店的甜點都很好吃，不過我個人還是最推薦這道蒙布朗。"
1300702-24 = "雖然因為很貴，所以銷量不太好，不過濕潤柔軟的濃郁栗子泥，配上酥脆的蛋白霜簡直是人間極品！"
1300702-25 = "我之前有吃過一次賣剩的……那個味道真的是令人無法自拔！"
1300702-26 = "[s] 購買淳子推薦的甜點"
1300702-27 = "真是明智的決定，我保證你一定不會後悔！"
1300702-28 = "嗯？喜歡的甜點全都賣光的話，不就沒辦法把賣剩的帶回家，很可惜？"
1300702-29 = "好……好像耶？難道說我應該故意偷懶，讓甜點剩越多越好……"
1300702-30 = "但是！要是不把東西賣出去會領不到薪水，那樣就不能買好吃的東西吃了……！"
1300702-31 = "啊咧，那個……我該怎麼辦才好啊……？"
1300702-32 = "[s] 把購買的甜點遞給淳子"
1300702-33 = "咦……？這個，老師不是買來當作點心的嗎？"
1300702-34 = "送給努力工作的學生的禮物？ #n……謝，謝謝……"
1300702-35 = "確實，依賴他人的好意而故意偷懶是不好的。"
1300702-36 = "我今天也要努力工作！"
1300702-38 = "（之後，又買了幾個甜點當點心才回去夏萊）"
