[translation]
2000308-1 = "正義的實現"
2000308-2 = "三一．屋頂"
2000308-3 = "唔嗯……比預期的還晚了一點呢。#n但是應該差不多，會在這個時間點通過這裡才對……"
2000308-4 = "但是不能夠大意。#n能夠狙擊敵人的時機，往往就只有一瞬間而已。"
2000308-5 = "嗯？你說就算對方是罪大惡極的敵人幹部，直接開槍還是太過分了嗎……？"
2000308-6 = "請放心吧。這把槍裡頭裝的子彈，是只會讓對方睡著的麻醉彈。"
2000308-7 = "只要對方一倒下就立刻抓住他，接著由弦生部長來進行審問，就是這樣的作戰計畫。"
2000308-10 = "― 呼……今天特別熱呢。[wa:1560] "
2000308-13 = "― 如果是為了完美的狙擊的話，這種程度的炎熱完全是可以忍耐的。[wa:3840] "
2000308-16 = "― 不過會不會有點……汗臭味呢……？[wa:1500] "
2000308-19 = "― 每次遇到這種天氣，我都很羨慕其他學生們穿的白色制服。[wa:3120] "
2000308-22 = "― 老師……我怎麼覺得你的視線好像有點下流……[wa:2040] "
2000308-24 = "― 你有好好的盯著目標對吧？[wa:1440] "
2000308-27 = "（嘟嚕嚕嚕嚕）"
2000308-28 = "嗯？是實現正義部打來的……？"
2000308-29 = "麻白同學？#n你現在在哪裡做些什麼呢？"
2000308-30 = "昨天蓮實前輩跟我說會有黑市的幹部靠近學園……#n所以我正在附近的狙擊地點待命。"
2000308-31 = "什麼？這樣的話，你可能是白跑一趟了……"
2000308-32 = "咦？這是什麼意思？"
2000308-33 = "那個壞人，昨天已經被弦生前輩給抓住了……"
2000308-34 = "弦生前輩也真是的，竟然擅自展開襲擊……"
2000308-35 = "怎麼會……那我是為了什麼才……"
2000308-36 = "總之就麻煩先回到學校來吧，辛苦了。"
2000308-37 = "嗚嗚……我知道了。"
2000308-39 = "（之後，一邊安慰沮喪的麻白一邊回到了學校）"
