[translation]
2006105-1 = "#title;온천가의 카리스마"
2006105-2 = "#na;(카스미가 보낸 주소지로 찾아갔다.)"
2006105-6 = "#na;(분명, 묵고 있는 호텔이나 민박 주소라고 생각했는데…….)"
2006105-7 = "#st;[0,0];instant;1;"
2006105-9 = "2;카스미 수영복;02\n#2;em;[반응]\n#2;a\n#wait;1000"
2006105-10 = "2;카스미 수영복;03;오오, 선생님! 여기야, 여기!\n#2;em;[재잘]\n#2;hophop\n#2;m3"
2006105-11 = "2;카스미 수영복;01;꽤 복잡한 길인데, 헤매지 않고 잘 도착했네."
2006105-12 = "2;카스미 수영복;08;응? 왜 그러지? 신기한 거라도 본 듯한 눈으로.\n#2;em;[?]"
2006105-13 = "[s1] \"여기, 블랙마켓……?\"\n[s2] \"나는 분명 숙소에 오라는 줄…….\""
2006105-16 = "2;카스미 수영복;99;아아~ 과연."
2006105-17 = "2;카스미 수영복;01;일단, 선생님이 이해한 대로야. 나는 여기 머무르고 있어."
2006105-18 = "2;카스미 수영복;11;그야, 쫓기는 신세라고? 태연하게 호텔 예약이나 할 리가 없잖아."
2006105-19 = "2;카스미 수영복;03;뭐~ 그렇다고 길바닥에서 지내는 건 아니니까, 너무 걱정하지는 말고!\n#2;em;[음표]\n#2;jump"
2006105-20 = "2;카스미 수영복;10;이 바닥에는 이 바닥만의 생리가 있다는 거지."
2006105-21 = "2;카스미 수영복;11;그리고, 블랙마켓은, 뭐, 엄밀히 말하면 달라."
2006105-22 = "2;카스미 수영복;12;대부분 사람은 여길 블랙마켓이라 부르기야 하겠지만, 여기는 그냥 이름 없는 뒷골목일 뿐이야.\n#2;em;[반응]"
2006105-23 = "2;카스미 수영복;09;사람이 모이면 이런 음지는 반드시 생겨나지. 아마 선생님이 가본 장소에도 꽤……."
2006105-24 = "2;카스미 수영복;99;아아, 잡설이 좀 길었나."
2006105-25 = "2;카스미 수영복;10;모처럼 선생님 시간까지 빌렸는데, 허비하기에는 너무 아깝지!\n#2;em;[재잘]"
2006105-26 = "2;카스미 수영복;11;자자, 서둘러서…….\n#2;m4"
2006105-27 = "2;카스미 수영복;08;응? 목적지? 아, 내 정신을 봐라. 정작 용건에 대해 말하는 걸 깜빡했굼나."
2006105-28 = "2;카스미 수영복;99;그야 온천개발부 부장이 움직인다면야."
2006105-29 = "#st;[0,0];instant;1;"
2006105-31 = "2;카스미 수영복;01\n#2;d\n#wait;1500"
2006105-33 = "3;카스미 수영복;01\n#3;a\n#3;closeup\n#wait;1500"
2006105-34 = "3;카스미 수영복;10;뻔하지 않겠어?\n#3;em;[음표]\n#3;closeup"
2006105-38 = "3;정중한 블랙마켓 상인;00;……네, 방금 소개인하고 연락을 마쳤습니다.\n#3;em;…\n#3;a"
2006105-39 = "#st;[0,0];instant;1;"
2006105-41 = "3;정중한 블랙마켓 상인;00\n#3;greeting\n#wait;1200"
2006105-42 = "3;정중한 블랙마켓 상인;00;키누가와 카스미 님, 본인 확인했습니다. 그러면 거래 얘기로 들어갈까 하는데요.\n#3;em;[반응]"
2006105-43 = "3;정중한 블랙마켓 상인;00;그쪽의 어른은……?"
2006105-44 = "5;카스미 수영복;03;아아, 신경 쓰지 마.\n#5;em;[재잘]\n#5;al\n#3;m1"
2006105-45 = "3;정중한 블랙마켓 상인;00;즉, 거래 내용을 들려줘도 괜찮으신 분이라……?\n#3;stiff"
2006105-46 = "5;카스미 수영복;02;어? 표현이 좀 어려웠나?"
2006105-47 = "5;카스미 수영복;10;신경 쓰지 말라니까?"
2006105-48 = "#st;[0,0];instant;1;"
2006105-50 = "3;정중한 블랙마켓 상인;00\n5;카스미 수영복;10\n#3;em;…\n#3;h\n#5;h\n#wait;2500"
2006105-51 = "3;정중한 블랙마켓 상인;00;……실례했습니다. 그러면 물건 얘기입니다만.\n#3;greeting"
2006105-52 = "3;정중한 블랙마켓 상인;00;요청하신 자재는 즉시 납품 가능한 것들입니다만, 수량이 조금 많아서요. 바지선을 써야 할 거 같아요.\n#3;em;[반응]"
2006105-53 = "5;카스미 수영복;11;음, 음. 그러면 밤에 옮기겠네?\n#5;em;[?]"
2006105-54 = "3;정중한 블랙마켓 상인;00;정확합니다. 일자와 장소가 제한됩니다만, 그 점은……."
2006105-57 = "#na;(잠시 동안, 카스미와 상인이 '거래'에 관해 은밀한 대화를 주고받았다.)"
2006105-60 = "1;정중한 블랙마켓 상인;00\n5;카스미 수영복;01\n#5;a\n#1;a\n#1;h\n#5;h\n#wait;1200"
2006105-61 = "5;카스미 수영복;10;이야, 좋은 거래했네. 현지에는 아는 얼굴이 없어서 말이야.\n#5;em;[음표]"
2006105-62 = "1;정중한 블랙마켓 상인;00;저희 쪽이야 말로, 카스미 님을 알게 되어 영광이었습니다. 부디 다음번에도 찾아 주시길.\n#1;greeting"
2006105-63 = "5;카스미 수영복;01;아아, 물론이지."
2006105-64 = "#st;[0,0];instant;1;"
2006105-66 = "1;정중한 블랙마켓 상인;00\n5;카스미 수영복;01\n#5;m3\n#1;dl\n#1;h\n#5;h\n#wait;1300"
2006105-67 = "5;카스미 수영복;00;그럼 다음으로 갈까, 선생?\n#5;em;[?]"
2006105-68 = "[s3] \"저기 카스미…….\"\n[s4] \"조금 전 거래는……?\""
2006105-71 = "5;카스미 수영복;12;아아, 이상한 거 아니니까 오해하지 마."
2006105-72 = "5;카스미 수영복;01;우리가 쓰는 공사 자재가 다 어디서 나온다고 생각해?"
2006105-73 = "5;카스미 수영복;03;물론! 이런 거 하나하나 뒤에서 구하면 돈이 얼마가 있어도 못 버텨! 보통은, 평범한 루트로 구매하는데…….\n#5;em;[재잘]"
2006105-74 = "5;카스미 수영복;15;하필이면, 이번에는 선도부한테 물자를 전부 압수당했으니까."
2006105-75 = "5;카스미 수영복;10;양지의 루트를 쓰자니, 선도부가 눈에 불을 켜고 찾아대고 있으니까 사실상 자수하는 셈이지."
2006105-76 = "5;카스미 수영복;13;그래서 '존재하지 않는 돈'으로 '존재하지 않는 물건'을 사는 거야."
2006105-77 = "5;카스미 수영복;03;우리는 공익을 위해 일하는데, 선도부도 참 엄격하단 말이야! 와하하~핫!\n#5;em;[재잘]\n#5;hophop"
2006105-78 = "[s5] \"공익이란 도대체…….\"\n[s6] \"정말 공사 자재뿐이지?\""
2006105-81 = "5;카스미 수영복;11;내가 선생님에게 거짓말을 해서 얻을 게 뭐겠어?"
2006105-82 = "5;카스미 수영복;10;아니면…… 선생님 입장에서는, '블랙마켓에 오는 학생'은 그 시점에서 아웃이려나?"
2006105-83 = "5;카스미 수영복;08;응……? 평범……?\n#5;em;[?]"
2006105-84 = "5;카스미 수영복;07;아니, 평범하지는 않지 않나……?\n#5;stiff\n#fontsize;50"
2006105-85 = "5;카스미 수영복;00;뭐, 좋아! 다음 장소로 갈까!\n#5;m2"
2006105-86 = "#st;[0,0];instant;1;"
2006105-88 = "5;카스미 수영복;00\n#5;dl\n#wait;3000"
2006105-91 = "3;힙한 블랙마켓 상인;00\n#3;em;[반응]\n#3;a\n#wait;1000"
2006105-92 = "3;힙한 블랙마켓 상인;00;요~ 이게 누구야."
2006105-93 = "3;힙한 블랙마켓 상인;00;우리 큰누님 오셨네. 선도부에 잡혀 갔다면서."
2006105-94 = "5;카스미 수영복;03;풀려났어. 나 같은 모범수는 드물거든.\n#5;em;[음표]\n#5;al\n#3;m1"
2006105-95 = "3;힙한 블랙마켓 상인;00;푸하하! 그거 웃기네! 그거 웃겨.\n#3;em;[재잘]\n#3;hophop"
2006105-96 = "5;카스미 수영복;01;요즘 어때?"
2006105-97 = "3;힙한 블랙마켓 상인;00;늘 똑같지. 어디서 싸움 났다고 하면 발에 불나게 뛰어서, 가서 불발탄이나 탄피 좀 주워 오고, 건물에서 철골 빼 오고……."
2006105-98 = "3;힙한 블랙마켓 상인;00;완전 고철더미에서 산다니까. 뭐, 나야 그걸로 먹고 사는 놈이지만. 무슨 고철이 필요해?\n#3;em;[?]"
2006105-99 = "5;카스미 수영복;10;필요한 목록은 보여주는 게 빠르겠지. 자."
2006105-100 = "#st;[0,0];instant;1;"
2006105-102 = "5;카스미 수영복;01\n3;힙한 블랙마켓 상인;00\n#5;greeting\n#3;h\n#5;h\n#wait;1300"
2006105-103 = "5;카스미 수영복;01\n3;힙한 블랙마켓 상인;00\n#3;greeting\n#3;h\n#5;h\n#wait;1500"
2006105-104 = "3;힙한 블랙마켓 상인;00;휘유~ 역시 우리 큰손. 씀씀이가 화끈하다니까. 바로 준비할게.\n#3;stiff"
2006105-105 = "5;카스미 수영복;10;오, 땡큐~"
2006105-106 = "3;힙한 블랙마켓 상인;00;그래도, 역시 다시 생각해 보지 그래?\n#3;em;[?]"
2006105-107 = "5;카스미 수영복;08;음?"
2006105-108 = "3;힙한 블랙마켓 상인;00;거 내가 전에 말했던 사업 있잖아. 아직도 핫라인이 마구마구, 진짜로 훨씬 돈이 될 거라니까?"
2006105-109 = "5;카스미 수영복;99;말했잖아. 안 한다고.\n#5;em;[한숨]"
2006105-110 = "3;힙한 블랙마켓 상인;00;능력이 아까워서 그래, 능력이."
2006105-111 = "3;힙한 블랙마켓 상인;00;아니, 어쩌다 우리 누님은 그런 이상한 거에 꽂혀서…….\n#3;em;[속상함]"
2006105-112 = "5;카스미 수영복;02;응?"
2006105-113 = "3;힙한 블랙마켓 상인;00;아니, 그 온천인지 뭔지, 그거 사실 돈도 안 되잖아. 그딴 거보다 누님 솜씨면 훨씬 큰 물에서…….\n#3;stiff"
2006105-114 = "#st;[0,0];instant;1;"
2006105-116 = "3;힙한 블랙마켓 상인;00\n5;카스미 수영복;08\n#5;em;…\n#5;h\n#3;h\n#wait;2500"
2006105-117 = "5;카스미 수영복;99;있잖아."
2006105-118 = "#st;[0,0];instant;1;"
2006105-120 = "3;힙한 블랙마켓 상인;00\n5;카스미 수영복;01\n#5;m4\n#5;h\n#3;h\n#wait;1300"
2006105-122 = "3;카스미 수영복;10;선 넘네?\n#3;em;[?]\n#3;closeup"
2006105-123 = "#st;[0,0];instant;1;"
2006105-125 = "3;힙한 블랙마켓 상인;00\n#3;em;[!]\n#3;h\n#3;closeup\n#wait;1000"
2006105-126 = "3;힙한 블랙마켓 상인;00;오, 오오…… 미안.\n#3;stiff\n#3;closeup"
2006105-128 = "1;힙한 블랙마켓 상인;00\n4;카스미 수영복;03;아니, 뭘 또 쫄고 그래~\n#4;em;[재잘]\n#4;m5"
2006105-129 = "4;카스미 수영복;10;누가보면 내가 진짜 무서운 사람인 줄 알겠어. 우리 비즈니스잖아, 비즈니스. 웃어야지~"
2006105-130 = "1;힙한 블랙마켓 상인;00;으, 응. 물론이지.\n#1;em;[땀]"
2006105-131 = "4;카스미 수영복;00;물건 얘기로 돌아가서……."
2006105-134 = "#na;(그렇게 카스미의 '장보기'에 어울리며 시간을 보냈다.)"
2006105-137 = "3;카스미 수영복;99\n#3;em;[한숨]\n#3;a\n#wait;1000"
2006105-138 = "3;카스미 수영복;12;이야, 고마워~ 선생님. 덕분에 다음 공사도 수월하겠어."
2006105-139 = "#st;[0,0];instant;1;"
2006105-141 = "3;카스미 수영복;02\n#3;em;[반응]\n#3;h\n#wait;1000"
2006105-142 = "3;카스미 수영복;08;선생님? 왜 그래?"
2006105-143 = "[s7] \"아니, 요즘따라 특히 느끼지만…….\"\n[s8] \"카스미는 여러 모습을 갖고 있구나.\""
2006105-146 = "3;카스미 수영복;99;유리하니까."
2006105-147 = "3;카스미 수영복;15;굳이 '나'라는 도구를 안 쓸 이유가 있어?"
2006105-148 = "[s] \"그래도 괜찮아?\""
2006105-149 = "3;카스미 수영복;02;응? 무슨 뜻일까?\n#3;em;[?]"
2006105-150 = "[s9] \"모두에게 맞춘다는 것은…….\"\n[s10] \"언제나 진심이 아니란 거잖아.\""
2006105-153 = "[ns11] \"나라면 힘들 거라 생각해.\"\n[ns12] \"그래서 걱정하는 거야.\""
2006105-154 = "#st;[0,0];instant;1;"
2006105-155 = "#st;[0,0];instant;1;"
2006105-157 = "3;카스미 수영복;08\n#3;em;…\n#wait;2500"
2006105-158 = "3;카스미 수영복;07;……선생님 같은 소리.\n#3;stiff"
2006105-159 = "3;카스미 수영복;10;그렇게 말하고 싶은데, 진짜 선생님이 하니까 할 말이 없구만.\n#3;em;[음표]"
2006105-160 = "3;카스미 수영복;11;내가 들은 대로면, 마치 선생님 앞에서라도 진심을 드러내라고……."
2006105-161 = "3;카스미 수영복;99;뭐, 그런 가슴 따뜻한 격려인 거 같은데, 제대로 이해한 게 맞나?"
2006105-162 = "#st;[0,0];instant;1;"
2006105-164 = "3;카스미 수영복;01\n#3;d\n#wait;1500"
2006105-165 = "3;카스미 수영복;01\n#3;a\n#3;closeup\n#wait;1500"
2006105-166 = "3;카스미 수영복;15;……그래, 한 번 해보지, 뭐.\n#3;em;[반응]\n#3;closeup"
2006105-169 = "#st;[-1200,-530];serial;60;[wa:1900]― [log=카스미 수영복]알고 있겠지만……[/log]"
2006105-171 = "#st;[-1200,-630];serial;60;― [log=카스미 수영복]이 근방은 [wa:560]치안이 나쁘지.[/log]"
2006105-174 = "#st;[-1200,-530];serial;60;― [log=카스미 수영복]사람 한 명쯤 사라진다 한들…… [wa:1760]누가 알려나 모르려나?[/log]"
2006105-177 = "#st;[-1200,-530];serial;60;[wa:750]― [log=카스미 수영복]하나는 잘 아는데, [wa:1440]근데……[/log]"
2006105-179 = "#st;[-1200,-630];serial;60;― [log=카스미 수영복]어째 선생님, [wa:800]둘은 모르더라고? 응?[wa:830] [/log]"
2006105-182 = "#st;[-1200,-530];serial;60;[wa:580]― [log=카스미 수영복]선생님이 날[wa:1280] 도우려고 하면 할수록[wa:40] [/log]"
2006105-184 = "#st;[-1200,-630];serial;60;― [log=카스미 수영복]점점 나한테…… [wa:1610]유용해져. 그래, 유용하고말고.[/log]"
2006105-187 = "#st;[-1200,-530];serial;60;[wa:540]― [log=카스미 수영복]그리고, 사람이란 말이지, [wa:850]유용한 것은…… 전부,[wa:80] [/log]"
2006105-189 = "#st;[-1200,-630];serial;60;― [log=카스미 수영복]전부 자기 손에 [wa:1350]쥐고 있고 싶거든.[/log]"
2006105-192 = "#st;[-1200,-530];serial;60;[wa:510]― [log=카스미 수영복]내 본성이 [wa:1450]보고 싶다고 말하지 않았던가?[/log]"
2006105-194 = "#st;[-1200,-630];serial;60;― [log=카스미 수영복]감상이 궁금하네?[/log]"
2006105-197 = "#st;[-1200,-530];serial;60;― [log=카스미 수영복]이제 나는 선생님을 곱게, [wa:2690]보내줄 생각이 없는데.[/log]"
2006105-200 = "#st;[-1200,-530];serial;60;[wa:1900]― [log=카스미 수영복]……서프라이즈~ [/log]"
2006105-203 = "#st;[-1200,-530];serial;60;― [log=카스미 수영복]어때? 꽤 실감 났지?[/log]"
2006105-205 = "#st;[-1200,-630];serial;60;― [log=카스미 수영복]얼굴 풀어, 얼굴. 재미있잖아. [wa:2410]장난이야.[/log]"
2006105-208 = "3;카스미 수영복;99;뭐, 이런 상황도 있을 수 있다는 거야.\n#3;em;[한숨]\n#3;a"
2006105-209 = "3;카스미 수영복;10;혹시 모르잖아? 헤실헤실 웃고 있는 아이가, 실은 엄청난 어둠을 품고 있다든지?"
2006105-210 = "3;카스미 수영복;11;그러니까 함부로 파고 다니는 거 아니야."
2006105-211 = "3;카스미 수영복;03;뭐, 나야 보이는 그대로지만 말이야! 와하하핫!\n#3;em;[재잘]\n#3;hophop"
