[translation]
221110-1 = "#title;제11화;변심"
221110-2 = "3;미나토;21\n#3;a"
221110-3 = "#place;올림포스 호, 아일랜드 사관실"
221110-5 = "3;미나토;22;후우우…… \n#3;em;[한숨]"
221110-6 = "3;미나토;23;……새미 때문에 이게 무슨 난리인지. "
221110-7 = "[s] \"괜찮아, 미나토?\" "
221110-8 = "3;미나토;07;네, 괜찮습니다. 오디세이아 학원에서 물에 빠지는 일은 일상다반사니까요. "
221110-9 = "3;미나토;03;바닷물을 마신 것도 아니고, 젖은 옷도 곧바로 갈아입었으니 문제 될 것은 없습니다. "
221110-10 = "3;미나토;11;게다가…… 새미도 이렇게 무사히 데려올 수 있었으니까요. \n#3;greeting"
221110-11 = "3;미나토;11\n#na;새미;야옹. "
221110-12 = "3;미나토;11\n1;아미;19;새미, 오늘따라 왜 이렇게 말썽을 부리니? \n#3;m4\n#1;ar"
221110-13 = "1;아미;20;벌이야. 앞으로 1주일 간은 간식 없을 줄 알아— \n#1;m2"
221110-14 = "#st;[0,0];instant;1;"
221110-16 = "3;미나토;11\n1;아미;20\n#3;h\n#1;h\n#1;em;…\n#wait;2500"
221110-17 = "1;아미;18;……아니. 떠나는 마당에 의미 없는 소리를 해 버렸네.\n#1;em;[한숨]"
221110-18 = "3;미나토;11\n1;아미;18\n#na;새미;냐아?"
221110-19 = "#st;[0,0];instant;1;"
221110-21 = "3;미나토;11\n1;아미;18\n#3;h\n#1;h\n#3;d\n#1;d\n#wait;1000"
221110-22 = "3;가짜 총학생회장;01\n#3;a\n#wait;1000"
221110-23 = "3;가짜 총학생회장;02;생각보다 긴 작업이 되었네요. 모두 수고 많으셨습니다.\n#3;greeting"
221110-24 = "3;가짜 총학생회장;03;그럼 오전에 진행하지 못했던, 새미의 신변 인도 관련 서류에 서명을 부탁드립니다."
221110-25 = "3;미나토;15;…….\n#3;em;…"
221110-26 = "3;미나토;16;총학생회장님. 지금에 와서 드리기엔 무척 염치없는 말이라는 것을 알고 있습니다만……"
221110-27 = "3;미나토;17;새미를 육지로 내리는 일은 없었던 것으로 했으면 합니다."
221110-28 = "3;아미;11;……함장?!\n#3;shake\n#3;em;[?!]"
221110-29 = "3;가짜 총학생회장;04;……혹시나 해서 다시 한번 확인 차 말씀드리지만."
221110-30 = "3;가짜 총학생회장;07;새미의 하선 결정은 대외적으로 아일랜드의 요청에 총학생회가 응한 것이 아니라, 총학생회장의 판단으로 내린 '지시사항'으로 공표 되어 있습니다."
221110-31 = "3;가짜 총학생회장;04;이를 오디세우스의 함장께서 거부하겠다고 말씀하신다면, 여러모로 학원 내외에 파장이 있을텐데요."
221110-32 = "3;가짜 총학생회장;08;갑작스럽게 총학생회의 지시를 번복해야 할 만큼 중대한 사유가 있으신가요?\n#3;em;[?]"
221110-33 = "3;미나토;14;어제…… 아니, 오늘 오전 까지만 하더라도 저는 오랜 금기와 관습을 거슬러서는 안 된다고 생각하고 있었습니다."
221110-34 = "3;미나토;15;수백년 간 불문에 붙여 숨겨왔던 이 금기를 거스르고, 카펫 아래를 들추어 보는 순간— 제 힘 만으로는 감당할 수 없는 해묵은 업보들이 덮쳐올까 두려웠기 때문입니다."
221110-36 = "#na;미나토;……네. 저는 여전히 두려움에 떨고 있었어요."
221110-38 = "#na;미나토;하지만 제가 물에 빠졌을 때, 새미는 두려움 없이 제게 다가왔습니다."
221110-39 = "#na;미나토;고양이에게 사람의 관습이나 미신은 아무런 의미를 갖지 않기에, 새미는 순수하게 물에 빠진 오랜 벗을 걱정하는 마음 하나 만으로 저를 찾아왔지요."
221110-40 = "#na;미나토;그 눈을 마주하니, 저는 갑자기 부끄러움을 느꼈습니다."
221110-41 = "#na;미나토;오디세이아의 관습은 오랜 벗을 내쳐야 할 만큼 중요한 것인가."
221110-42 = "#na;미나토;그리고 오디세이아의 함장은 두려움조차 이겨내지 못할 만큼 나약하고 무능한 사람을 위한 자리인가."
221110-43 = "3;미나토;17\n#3;h\n#3;a"
221110-44 = "3;미나토;02;먼 옛날, 오디세이아의 첫 항해에는 지금보다 더 많은 두려움이 있었을 겁니다."
221110-45 = "3;미나토;15;튼튼한 선체도, 항로도, 목표도 알지 못하면서. 그저 바다 너머에 무엇이 있는지 알고 싶어 노를 저었던 선배들이 두려움 때문에 결정을 미루었다면."
221110-46 = "3;미나토;14;지금의 오디세이아 해양 학원은 존재할 수 없었겠죠."
221110-47 = "3;미나토;16;이 아이를 보내고 나면, 이후로는 그 어떤 것도 결정할 수 없게 되어버릴 것 같아서……"
221110-48 = "3;미나토;17;염치를 무릅쓰고 회장님께 어려운 부탁을 다시 드리고자 합니다."
221110-49 = "3;미나토;06;새미의 처우에 대해 재고를 부탁드립니다.\n#3;greeting"
221110-50 = "#st;[0,0];instant;1;"
221110-52 = "3;미나토;06\n#3;d\n#wait;1000"
221110-53 = "3;가짜 총학생회장;08\n#3;a\n#wait;1000"
221110-54 = "3;가짜 총학생회장;08\n#3;em;…\n#wait;2500"
221110-55 = "3;가짜 총학생회장;02;당신의 뜻이 그러하다면."
221110-56 = "3;가짜 총학생회장;99;네, 새미의 하선은 없던 일로 하시지요."
221110-57 = "3;가짜 총학생회장;99\n5;미나토;02;저, 정말로 그렇게 결정 하셔도 괜찮으신가요?\n#5;al\n#3;m2"
221110-58 = "3;가짜 총학생회장;02;혹시 우미지 함장께서는 오디세이아 학원에서 총학생회에 반기를 드는 그림을 희망하고 계셨던 건가요?"
221110-59 = "5;미나토;04;그, 그건 아니지만……\n#5;m4\n#5;em;[땀]"
221110-60 = "3;가짜 총학생회장;99;네, 괜찮습니다."
221110-61 = "3;가짜 총학생회장;02;오디세이아 학생들의 눈에는 총학생회의 결정이 다소 변덕스럽게 느껴지겠지만……"
221110-62 = "3;가짜 총학생회장;06;불가해라는 것이 본래 그런 법이니까요."
221110-63 = "5;미나토;07;……감사합니다."
221110-64 = "3;가짜 총학생회장;06\n5;미나토;07\n#na;새미;냐아—"
221110-66 = "4;미나토;15\n2;아미;06\n#2;h\n#4;h\n#2;a\n#4;a"
221110-67 = "2;아미;18;하아…… 결국은 원점으로 돌아가버렸네요.\n#2;em;[한숨]"
221110-68 = "2;아미;13;그래서, 새미가 불운을 불러온다고 여전히 믿고 있는 학생들은 어떻게 설득하실 생각이신가요?"
221110-69 = "4;미나토;14;계속해서 생각해 보았지만…… 역시 설득할 필요는 없지 않을까?"
221110-70 = "2;아미;11;네에?!\n#2;shake\n#2;em;[?!]"
221110-71 = "4;미나토;02;어쩔 수 없잖아. 평범한 학생이라면 이해할 수 없는 불가해 앞에서, 이성적으로 대처하라고 말해 봤자 반발심만 생기겠지만……"
221110-72 = "2;아미;11\n4;미나토;03;그에 비해 친구와 함께 있어 좋은 이유를 설명하는 건, 상대적으로 간단한 일이니까.\n#4;m3\n#2;dl"
221110-73 = "4;미나토;07;두렵고, 납득할 수 없는 일이 계속 진행되더라도, 품에 끌어안은 고양이가 얼마나 따스한 지 느낄 수만 있다면."
221110-74 = "4;미나토;11;현학적인 설명 없이도 벗이 있어 좋은 이유를 납득할 수 있을 테니까."
221110-75 = "#st;[0,0];instant;1;"
221110-77 = "4;미나토;11\n#4;d\n#wait;1000"
221110-78 = "3;아미;10\n#3;a\n#wait;1000"
221110-79 = "3;아미;10\n#3;em;[...]\n#wait;2500"
221110-80 = "3;아미;22;……얼마나 시간이 오래 걸릴지는 모르겠지만."
221110-81 = "3;아미;99;언젠가는 부디, 그렇게 되면 좋겠네요."
221110-84 = "3;가짜 총학생회장;10\n#3;h\n#3;a"
221110-86 = "[ns1] \"……무사히 설득할 수 있어서 다행이네.\"\n[ns2] \"상처받는 일 없이 해결될 수 있어서 다행이야.\""
221110-89 = "3;가짜 총학생회장;06;그렇네요. 이번 일로 손해를 본 건, 오디세이아 학원 내에서의 제 이미지 정도뿐인 것 같으니."
221110-90 = "[s3] \"아. 총학생회장이 상처받지 않았다는 뜻은 아냐!\"\n[s4] \"무, 물론 총학생회장의 기분도 중요하지만……\""
221110-93 = "3;가짜 총학생회장;09;후후, 변명하실 필요는 없답니다.\n#3;em;[음표]"
221110-94 = "3;가짜 총학생회장;03;미움 받는 역할을 먼저 자처한 건 저였으니까요."
221110-95 = "3;가짜 총학생회장;99;다만…… 듣자 하니 오디세이아 학원의 로컬 아이스크림 가게에는 D.U.에서 맛볼 수 없는 특별한 맛의 아이스크림을 팔고 있다고 하던데."
221110-96 = "3;가짜 총학생회장;02;선생님께서 제게 그 아이스크림을 하나 사주신다면 대강 수지타산이 맞을 것 같은데요. #n……어떻게 생각하시나요?\n#3;em;[?]"
221110-97 = "[s] \"그걸로 충분하겠어?\""
221110-98 = "3;가짜 총학생회장;09;충분하고 말고요.\n#3;em;[재잘]"
221110-100 = "#na;(……그 때만 하더라도, 오디세이아 학원에서 벌어진 고양이 소동은 이것으로 마무리되었다고 생각했었다.)"
221110-101 = "#st;[0,0];instant;1;"
221110-104 = "#na;(그 날 저녁, 갑자기 걸려 온 전화를 받기 전까지는.)"
221110-108 = "3;사나에;01\n#3;sig\n#3;a\n#wait;1000"
221110-109 = "3;사나에;02;선생님, 계십니까?\n#3;sig"
221110-110 = "3;사나에;03;늦은 시간에 실례했습니다. 지난 번에 인사드렸던 오디세이아의 선의, 후나모리 사나에입니다.\n#3;sig\n#3;greeting"
221110-111 = "3;사나에;02;잠시, 통화 괜찮으신지요?\n#3;sig\n#3;em;[?]"
221110-112 = "[s5] \"아, 사나에 쨩. 물론 기억하고 있지.\"\n[s6] \"갑자기 이 시간에 무슨 일이야?\""
221110-115 = "3;사나에;10;갑자기 전화를 드린 이유는 다름이 아니라……\n#3;sig\n#3;em;[...]"
221110-116 = "3;사나에;08;선생님께서 급히 봐주셨으면 하는 사안이 발생했기 때문입니다.\n#3;sig"
221110-117 = "[s] \"설마 아픈 학생이라도 생긴 거야?\""
221110-118 = "3;사나에;19;아픈 것은 맞지만…… 대상이 학생은 아닙니다.\n#3;sig"
221110-119 = "3;사나에;02;바로 단도직입적으로 말씀드리자면.\n#3;sig"
221110-121 = "#na;사나에;……선생님. 새미의 수명이 얼마 남지 않은 것 같습니다."
221110-123 = "#nextepisode;다음화;폭풍우 치는 밤에"
