[translation]
70012010-1 = "ON AIR: เกเฮนน่า 1"
70012010-3 = ""
70012010-4 = ""
70012010-5 = "แค่นี้มันยังไม่พอหรอก!"
70012010-6 = "อะไรเหรอ?"
70012010-7 = "ของที่มีประกายระยิบระยับน่ะสิ!"
70012010-8 = "อธิบายได้คลุมเครือมากเลยนะ..."
70012010-9 = "ยังไงพวกเราก็เป็นสมาชิกชมรมเปล่งประกาย ที่พูดมาเธอก็คงหมายถึงว่าพวกเราไม่ได้กระตือรือร้น#nทำกิจกรรมชมรมมากพอใช่มั้ยล่ะ?"
70012010-10 = "สมกับเป็นเอริกะจัง! ใช่แล้วละ ถูกต้องเลย ใช่เลย"
70012010-11 = "ช่วงนี้ไม่มีเรื่องที่น่าสนใจบ้างเลยรึไงนะ? ช่วงนี้เกเฮนน่าดูเงียบสงบเกินไปรึเปล่า?"
70012010-12 = "ถึงจะบอกว่า 'ช่วงนี้' ก็เถอะ แต่เมื่ออาทิตย์ก่อนอาคารหลักของชมรมก็เพิ่งโดนระเบิดไปเองนะ"
70012010-13 = "โธ่เอ๊ย มันผ่านมาตั้งหนึ่งอาทิตย์แล้วนี่นา คนเลิกพูดถึงเรื่องนั้นกันแล้ว ตัวอาคารหลักก็คงซ่อมเสร็จแล้วละมั้ง"
70012010-14 = "เฮ้อ~ ยังไงก็เถอะ ไม่มีเรื่องสนุกๆ น่าตื่นเต้นบ้างเลยรึไงนะ"
70012010-15 = "เรื่องที่จะทำให้คิราระจังตื่นเต้นได้ มันไม่ได้มีบ่อยๆ หรอก"
70012010-16 = ""
70012010-18 = ""
70012010-19 = "โอ๊ะ เอริจัง! ดูนั่นๆ"
70012010-20 = "หืม? มีอะไรเหรอ?"
70012010-21 = ""
70012010-23 = ""
70012010-25 = ""
70012010-26 = "ก็บอกแล้วไงคะว่าแค่นั่งเฉยๆ แล้วจะพูดอะไรก็ได้ แค่นั้นก็พอค่ะ"
70012010-27 = "เฮ้อ น่ารำคาญจัง"
70012010-28 = "ไปหาคนอื่นเถอะ ฉันต้องไปอุ่นแกงกะหรี่แล้ว"
70012010-29 = ""
70012010-31 = ""
70012010-32 = "เฮ้อ น่ารำคาญงั้นเหรอ"
70012010-33 = "มันก็ใช่อยู่หรอก... ฉันเองก็ยังรำคาญจนต้องมาหาคนช่วยแบบนี้เลยนี่นา..."
70012010-34 = ""
70012010-36 = ""
70012010-37 = "เดี๋ยวนะ"
70012010-38 = "นี่ฉันยอมลำบากเพื่อเลี่ยงงานที่น่ารำคาญอยู่รึเปล่านะ?"
70012010-39 = "ถ้าเอามาบวกลบกันก็ถือว่ามีค่าเท่ากันน่ะสิ...?"
70012010-40 = "......"
70012010-41 = "ไม่หรอก อย่าคิดมากเลยดีกว่า คิดไปก็ปวดหัวเปล่าๆ..."
70012010-42 = "ว่าแต่ว่าจะไปหาคนทำแทนจากที่ไหนกันล่ะ?"
70012010-43 = "ฉันไม่มีอะไรจะให้คนที่มาทำแทนด้วย... ของที่จะพอให้เป็นของขวัญได้ ก็น่าจะมีแต่ลายเซ็นจริง#nของรุ่นพี่มาโคโตะ แต่ก็คงไม่มีใครอยากได้ของพรรค์นั้นหรอก..."
70012010-44 = ""
70012010-46 = ""
70012010-47 = "นี่ๆ อิโรฮะ... จากแพนเดโมเนียม โซไซตี้ใช่มั้ย! ใช่อิโรฮะจังรึเปล่า? มีเรื่องอะไรเหรอ?"
70012010-48 = "ดูเหมือนต้องการคนช่วยอยู่เลย มีอะไรให้พวกเราช่วยรึเปล่า?"
70012010-49 = "พวกเธอคือ..."
70012010-50 = "......"
70012010-51 = "อ๊ะ!"
70012010-52 = "ดูเหมือนจะเจอคนเหมาะๆ แล้วละค่ะ"
70012010-54 = "ก่อนหน้านี้..."
70012010-55 = "คิกๆ ก็เป็นเช่นนั้นละ"
70012010-56 = "จู่ๆ ก็พูดเรื่องอะไรคะ จนถึงเมื่อกี้ยังไม่เห็นพูดอะไรเลยสักอย่าง"
70012010-57 = "เราก็แค่อยากพูดสิ่งที่สื่ออารมณ์แบบนั้นเฉยๆ บางครั้งก็รู้สึกแบบนี้กันไม่ใช่รึไง?"
70012010-58 = "อารมณ์ความรู้สึกของมนุษย์เราน่ะ เป็นสิ่งสำคัญกว่าที่เธอคิดอีกนะ อิโรฮะ"
70012010-59 = "ค่าค่า ก็คงจะเป็นอย่างนั้นละค่ะ"
70012010-60 = "คิกๆ ว่าแต่ว่า การจัดเตรียมการออกอากาศภายในที่แพนเดโมเนียม โซไซตี้เป็นผู้จัดขึ้น เป็นไปได้ด้วยดีหรือไม่?"
70012010-61 = "มีช่วงที่จะต้องอ่านเรื่องราวที่ส่งมาจากทั่วเกเฮนน่าด้วยสินะ"
70012010-62 = "นั่นสินะคะ ก็คงเตรียมการไปได้ด้วยดีมั้งคะ"
70012010-63 = "อ๊ะ แต่ฉันบอกไปแล้วนี่คะว่าอย่าเพิ่มช่วงอ่านบทกวีสรรเสริญที่รุ่นพี่แต่งเองเข้ามาน่ะ มันสิ้นเปลืองงบประมาณนะคะ"
70012010-64 = "ถึงยังไงก็คงไม่มีใครคิดจะฟังรายการเสียงตามสายในโรงเรียนอยู่แล้วละค่ะ"
70012010-65 = "อ่อนหัดจริงๆ เลยนะ อิโรฮะ แต่ก็ถือว่าเป็นเรื่องดีนั่นละ คิกๆ!"
70012010-66 = "เป็นเรื่องดียังไงเหรอคะ?"
70012010-67 = "การที่ไม่มีใครสนใจก็หมายความว่าเราจะทำอะไรก็ได้ตามใจชอบยังไงล่ะ"
70012010-68 = "อย่างเช่น ถ้าเนียนพูดเรื่องร่างงบประมาณที่จัดสรรใหม่ในรายการด้วย"
70012010-69 = "ก็จะอ้างได้ว่า 'ได้ประกาศแจ้งเรื่องการตัดงบประมาณของคณะกรรมการวินัยผ่านทางช่องทาง#nอย่างเป็นทางการของเกเฮนน่าไปแล้ว' อะไรทำนองนั้นน่ะ คิกๆๆ"
70012010-70 = "เป็นเหตุผลที่เห็นแก่ตัวและไร้สาระที่สุดเลยนะคะ "
70012010-71 = "ยังไงก็เถอะ! ข้อดีของรายการภายในก็คือเป็นสิ่งที่คนส่วนใหญ่ไม่สนใจยังไงล่ะ"
70012010-72 = ""
70012010-75 = ""
70012010-76 = "ขอรายงานค่ะ!"
70012010-77 = "นักเรียนที่รับผิดชอบจัดรายการเสียงตามสายภายในโรงเรียนลาออกกะทันหันค่ะ!"
70012010-78 = "ว่าไงนะ!! เพราะอะไรกัน?!"
70012010-79 = "ฉะ... ฉันก็ไม่ทราบเหมือนกันค่ะ! ฉันถามเหตุผลแล้ว แต่เด็กคนนั้นก็เอาแต่เหม่อลอยแล้วพูดซ้ำๆ ว่าเป็นเหตุผลส่วนตัว..."
70012010-80 = "ตอนนี้เรากำลังรีบหาคนมาทำหน้าที่แทนอยู่ แต่ว่ายังไม่เจอคนที่เหมาะสมเลยค่ะ!"
70012010-81 = "เกิดเรื่องไม่คาดคิดแบบนี้ขึ้นได้ยังไงกัน...!!"
70012010-82 = "เฮ้อ ช่วยไม่ได้นะคะ สงสัยต้องยกเลิกงานนี้แล้วละค่ะ"
70012010-83 = "อย่าพูดอะไรไร้สาระแบบนั้นนะ อิโรฮะ!!"
70012010-84 = "คะ? ถึงยังไงก็ไม่มีคนฟังอยู่แล้วนี่คะ รุ่นพี่ยังบอกว่าเป็นเรื่องที่ดีเลยนี่นา"
70012010-85 = "มันคนละเรื่องกันนะ!!"
70012010-86 = "เรื่องมีผู้ชมมากหรือน้อยมันไม่ใช่ปัญหา! แต่การไม่ออกรายการเลยแบบนี้มันคนละเรื่องกันเลย!"
70012010-87 = "นี่เป็นเรื่องสำคัญที่เกี่ยวพันกันกับศักดิ์ศรีของแพนเดโมเนียม โซไซตี้ และศักดิ์ศรีของเราเชียวนะ!!"
70012010-88 = "คงไม่มีใครสนใจเรื่องนั้นหรอกค่ะ"
70012010-89 = "รีบไปหาคนมาแทนด่วนๆ เลย!! เดี๋ยวนี้!!"
70012010-90 = "เดี๋ยวค่ะ เมื่อกี้ไม่ได้ฟังที่พูดเลยเหรอคะ ฉันจะไปหาคนที่เหมาะกับหน้าที่นี้มาจากไหนกันล่ะคะ? อย่างน้อยคนที่จะมาแทนก็ต้องมีประสบการณ์ด้านการทำรายการอะไรแบบนี้มาก่อน..."
70012010-91 = "เรื่องนั้นเราไม่รู้หรอก-!! ต่อให้ไม่มีประสบการณ์ก็ไม่มีปัญหา!!"
70012010-92 = "ขอแค่ให้ออกอากาศต่อไปได้ก็พอแล้ว!!!"
70012010-93 = "เลิกเอาแต่ใจสักทีได้มั้ยคะ!!!"
70012010-95 = "ระ... เรื่องมันเป็นแบบนี้เองสินะ..."
70012010-96 = "เฮ้อ... ค่ะ ทีนี้คงเข้าใจแล้วใช่มั้ยคะ ว่ามันเป็นงานที่ไม่มีความหมายอะไรเลย..."
70012010-97 = "น่าสนุกจัง~~!!"
70012010-98 = "......"
70012010-99 = "คะ??"
70012010-100 = "ใช่มั้ยล่ะ เอริจัง! เราไปลองทำดูกันมั้ย? ว่าไง ว่าไง?"
70012010-101 = "ถ้ามือสมัครเล่นทำได้ละก็ ฉันก็ไม่ติดอะไรนะ ได้ไปจัดรายการก็คงเป็นประสบการณ์ที่ดีเหมือนกัน"
70012010-102 = "พูดจริงเหรอคะ...?"
70012010-103 = "อื้อ!! ฉันต้องเตรียมตัวให้เสร็จภายในวันไหนล่ะ?!"
70012010-104 = "สำหรับฉัน... ยังไงก็ได้เลยค่ะ..."
70012010-105 = "ว่าแต่ว่า พวกคุณตกลงจะทำจริงๆ ใช่มั้ยคะ...?"
