[translation]
70012010-1 = "ON AIR: Gehenna 1"
70012010-3 = ""
70012010-4 = ""
70012010-5 = "There's just not enough!"
70012010-6 = "Not enough...what exactly?"
70012010-7 = "Twinkly things!"
70012010-8 = "And by that you mean..."
70012010-9 = "...that as the Twinkle Twinkle Club, there aren't a lot of activities for us to participate in?"
70012010-10 = "You always get me, Eri! That, that!"
70012010-11 = "I mean, like, literally nothing fun's happened lately! Why's Gehenna been so quiiiet?"
70012010-12 = "Didn't the Clubhouse get blown up last week?"
70012010-13 = "Yeah, LAST week! It only happened one time, and I'm pretty sure they've already fixed it."
70012010-14 = "*sigh* I wanna find something FUN to do."
70012010-15 = "Hah. Keeping you entertained is a tall order."
70012010-16 = ""
70012010-18 = ""
70012010-19 = "Oooh, Eri! Look over there!"
70012010-20 = "Huh? What is it?"
70012010-21 = ""
70012010-23 = ""
70012010-25 = ""
70012010-26 = "Look, just sit in there and say anything you want."
70012010-27 = "Ugh, what a pain."
70012010-28 = "Just find someone else. I've got curry waiting for me at home."
70012010-29 = ""
70012010-31 = ""
70012010-32 = "*sigh* Calling it a \"pain\"..."
70012010-33 = "...Eh, well. I can't blame them. It's because this whole thing is a pain that I'm trying to find someone else to do it for me..."
70012010-34 = ""
70012010-36 = ""
70012010-37 = "Wait."
70012010-38 = "By trying to avoid work, am I making more work for myself?"
70012010-39 = "So I end up in tedium no matter what I do?"
70012010-40 = "..."
70012010-41 = "Ugh. If I think too hard about it, I'm going to throw up."
70012010-42 = "But how am I going to find someone willing to do this in Gehenna of all places?"
70012010-43 = "I don't have any compensation to offer... Unless you count Makoto's \"autograph,\" but who in their right mind would want that?"
70012010-44 = ""
70012010-46 = ""
70012010-47 = "Hey, hey! You're...Iroha, right? From the Pandemonium Society!"
70012010-48 = "You're lookin' a little stressed out—anything we can do to help?"
70012010-49 = "You two are..."
70012010-50 = "..."
70012010-51 = "Ah!"
70012010-52 = "The answer to my prayers."
70012010-54 = "Earlier..."
70012010-55 = "Kihehehe. And that's how it is."
70012010-56 = "That's how WHAT is? You normally say that AFTER you make a point."
70012010-57 = "Well, I simply wanted to say that. Everyone feels that way sometimes."
70012010-58 = "Feelings hold much more value than you seem to think, Iroha."
70012010-59 = "Yeah, okay. Whatever you say, Makoto."
70012010-60 = "Kihehe. Speaking of! Give me an update on our campus broadcast: organized, directed, and produced by none other than US, the Pandemonium Society!"
70012010-61 = "I particularly like the segment where we read real stories from real Gehenna students!"
70012010-62 = "Yeah, it's going well. Great. Or something."
70012010-63 = "Ah, but that segment for \"Poetry Praising Makoto Recital\" should be cut. It's a waste of budget."
70012010-64 = "And no one listens to the broadcast anyway."
70012010-65 = "You have a long way to go, Iroha! That's precisely what's so wonderful about it! Kihehe!"
70012010-66 = "And what, exactly, is so great about having no audience?"
70012010-67 = "No audience means that there's no one to answer to! You can do or say WHATEVER you want!"
70012010-68 = "Like, say, casually slipping in budget reallocation announcements..."
70012010-69 = "You can claim \"the budget cut for the Prefect Team has already been announced through Gehenna's official routes.\" Kihehe."
70012010-70 = "How petty. And incredibly trivial. "
70012010-71 = "The POINT is that no one cares about the broadcast, and that's why it's an excellent tool for us! The Pandemonium Society!"
70012010-72 = ""
70012010-75 = ""
70012010-76 = "Report!"
70012010-77 = "The student running the campus broadcast just quit!"
70012010-78 = "WHAT DID YOU SAY?! Why??"
70012010-79 = "I-I tried to ask her, but she just kept saying, \"Personal reasons...\" and looked completely dissociated!"
70012010-80 = "We are, of course, looking for a replacement, but such casting may take time!"
70012010-81 = "N-No one could have predicted this!"
70012010-82 = "*sigh* There's no helping it. I guess we'll just have to cancel today's broadcast."
70012010-83 = "NO! No, we can't do that, Iroha!"
70012010-84 = "Eh, why not? Like you said, the best part is that no one even listens to it."
70012010-85 = "You keep missing my point!"
70012010-86 = "The audience is insignificant! But failing to produce the broadcast... That would be a disaster!"
70012010-87 = "This is a matter of grave importance, concerning the dignity of the Pandemonium Society, and, more importantly, ME!!"
70012010-88 = "No one's thinking that but you."
70012010-89 = "Find a replacement!! RIGHT NOW!!"
70012010-90 = "Are you serious? I can't just pluck someone out of a crowd. Where in Gehenna am I going to find someone else with broadcasting experience...?"
70012010-91 = "How am I supposed to know?! Why do they even need to have experience?! I don't care!"
70012010-92 = "Just don't let the show be cancelled!!"
70012010-93 = "This is incredibly unreasonable!!"
70012010-95 = "I-I see..."
70012010-96 = "*sigh* Do you understand my pain now? Wasting my time on stuff like this..."
70012010-97 = "That sounds like a BLAST!"
70012010-98 = "..."
70012010-99 = "What?!"
70012010-100 = "Don't you think so too, Eri? Should we do it? Should we?"
70012010-101 = "Well, they said you don't need experience. Sounds like it could be fun."
70012010-102 = "Really...?"
70012010-103 = "Yeah!! When do you need us to be ready by?"
70012010-104 = "I mean... You really don't need to prepare anything..."
70012010-105 = "But you two are really serious?"
