[translation]
83300400400-5 = "Ah, Head Prefect. Have you dealt with the troublemakers?"
83300400400-6 = "Yes. But whoever hired them was clever enough not to share any identifying information."
83300400400-7 = "I suppose it would be too convenient to solve this mystery by interrogating one group of troublemakers."
83300400400-8 = "Hmm. But if we're lucky, this is the last we'll hear of the matter."
83300400400-9 = "Please leave the cleanup to us."
83300400400-10 = "Thank you for your hard work today, Head Prefect."
