[translation]
83305100200-5 = "Hello, Head Prefect!"
83305100200-6 = "Ako. I asked to speak with you because I have a request to make."
83305100200-7 = "By request, you mean...?"
83305100200-8 = "I wish to put my full efforts into my piano recital."
83305100200-9 = "I want to be able to put my all into it. So..."
83305100200-10 = "Of course, Head Prefect. I'll handle your morning duties today."
83305100200-11 = "Ako..."
83305100200-12 = "The senior administrator supports the head prefect to her utmost ability."
83305100200-13 = "That's how I, Amau Ako, make a difference. So leave everything to me."
83305100200-14 = "...Thank you, Ako."
83305100200-15 = "Just like Sensei, I also... Well, I'll be there too."
83305100200-16 = "...Thank you. I'll see you soon."
