[translation]
84304100601-5 = "ถ้าสนใจในการออกกำลังกายก็มาบอกฉันได้ทุกเมื่อนะคะ!"
84304100601-6 = "ฉันรู้สึกว่าถ้าเราได้ออกกำลังกายด้วยกัน... ก็น่าจะสนุกมากๆ แน่ๆ ค่ะ!"
84304100601-7 = "พูดอย่างนั้นก็น่าซึ้งใจอยู่หรอกนะ..."
84304100601-8 = "ฉันแค่ถามเฉยๆ หรอกนะ นี่เธอไม่รู้ใช่มั้ยว่าฉันเป็นใคร?"
84304100601-9 = "อืม...? หมายความว่ายังไงคะ?"
84304100601-10 = "หรือว่าคุณเป็นเทรนเนอร์ที่เก่งกาจอยู่แล้ว...!!"
84304100601-11 = "ไม่หรอก ช่างมันเถอะ... ไม่ต้องใส่ใจหรอก"
