[translation]
84303400200-5 = "ฉันวิเคราะห์เกมที่เอามาเสร็จแล้ว"
84303400200-6 = "มันก็ไม่ได้อยู่ในระดับที่ยอดเยี่ยมขนาดนั้น แต่อย่างน้อยคนพวกนั้นก็มีทักษะที่เรียกว่าเป็น 'แฮ็กเกอร์' ได้ นักเรียนชมรมพัฒนาเกมไม่น่าจะสังเกตได้น่ะ"
84303400200-7 = "อย่างที่ฉันเคยบอกไว้ เกมนี้ถูกดัดแปลงอย่างตั้งใจและชาญฉลาด เพื่อให้ได้ผลลัพธ์ที่เลวร้ายที่สุด โดยที่ไม่ฝ่าฝืนกฎของโค้ด"
84303400200-8 = "โดยพื้นฐานแล้วเกมนี้เป็นเกมที่เล่นค่อนข้างยาก จะบอกว่าเกมนี้เป็นอาวุธที่ทำร้ายจิตใจมนุษย์ได้ก็ไม่#nแปลก"
84303400200-9 = "เวลาที่โค้ดถูกแทรกซึมก็ตรงกับคำให้การด้วย นี่ไม่ใช่ความผิดของชมรมพัฒนาเกม พวกเธอไม่มีความเกี่ยวข้องกับสถานการณ์นี้อย่างที่พวกเธอบอก"
84303400200-10 = "ฉันจะลองดูโค้ดเพิ่มอีกสักหน่อย..."
84303400200-11 = "ฉันรู้สึกว่าน่าจะหาอะไรได้มากกว่านี้น่ะ"
