[translation]
90000075-2 = "各位都沒事吧……"
90000075-3 = "嚇我一跳……那到底是什麼呢，部長？"
90000075-4 = "……我也是第一次看見。#n不過那個模樣……恐怕……"
90000075-5 = "是目前尚未掌握的新「預言者」呢……"
90000075-6 = "果然沒錯。突然跑出來真的嚇到我了。"
90000075-7 = "就是說啊……幸好能在沒有太大傷亡的情況下成功撤退。#n不過它和其他預言者不同，行動模式相當奇特呢。"
90000075-8 = "嗯。感覺就像是在阻止我們一樣。"
90000075-9 = "也就是說……"
90000075-10 = "十字神名真的就在那裡嗎？#n那個新的「預言者」是為了保護十字神名，所以才出現在我們面前……？"
90000075-11 = "嗯……"
90000075-12 = "也罷，反正只要直接確認就能知道了。"
90000075-13 = "說不定我們的任務，已經進入新的局面了呢。"
90000075-14 = "在那個被預言者守護的淹沒地區，是否真的存在不能讓我們看見的某樣東西……"
90000075-15 = "就用我們的雙眼直接確認吧。"
90000075-17 = "嗯，我知道了。#n看來之後會變得有點辛苦呢。"
90000075-18 = "是啊。接下來的任務是對那個廢墟淹沒地區進行徹底調查。"
90000075-19 = "雖然「預言者」多半會阻擋在我們面前……#n但這種程度的阻礙，我會賭上我的名號克服的。"
90000075-21 = "下一話;搜索作戰"
