[translation]
90000010-1 = "第2話;蒐集情報(1)阿拜多斯砂漠"
90000010-2 = "現在我們最需要的，是盡可能蒐集十字神名的情報。"
90000010-3 = "因此我們的第一個目標，是目前所知十字神名出現地點之一的「阿拜多斯砂漠」。"
90000010-4 = "雖然要找到「薇娜」或許有困難，不過那附近也有十字神名的部下正在徘徊……"
90000010-5 = "先一邊處理它們，一般蒐集情報吧。"
