[translation]
90000010-1 = "ตอนที่ 1; รวบรวมข้อมูล 1 - ทะเลทรายอะบิดอส"
90000010-2 = "สิ่งที่จำเป็นสำหรับเราที่สุดตอนนี้ก็คือการรวบรวมข้อมูลของเดคาแกรมมาทอนค่ะ"
90000010-3 = "เป้าหมายแรกของพวกเราก็คือหนึ่งในแหล่งกำเนิดของเดคาแกรมมาทอนที่ยืนยันได้ในปัจจุบัน นั่นก็คือทะเลทรายอะบิดอสค่ะ"
90000010-4 = "การค้นหาบีนาห์ที่นี่ก็ยากลำบากพอสมควร แต่ว่าใกล้บริเวณนั้นมีลูกสมุนของเดคาแกรมมาทอน ลาดตระเวนอยู่ "
90000010-5 = "ก่อนอื่นก็กำจัดเจ้าพวกนั้นและรวบรวมข้อมูลมาก่อนค่ะ"
