[translation]
90000020-1 = "ตอนที่ 2; รวบรวมข้อมูล 2 - เขตขุดค้น PMC"
90000020-2 = "สถานที่ต่อไปคือไซต์งานก่อสร้างที่ไคเซอร์ PMC สร้างขึ้นเพื่อขุดค้นหาบางอย่างอยู่ค่ะ"
90000020-3 = "พวกไคเซอร์ PMC อาจเข้ามาขัดขวางได้ ตอนที่ไปก็ระมัดระวังด้วยนะคะคุณครู"
