[translation]
92020-1 = "......"
92020-2 = "คะ... คือว่า... ฉะ... ฉันมาจับตัวพวกเด็กเกเร..."
92020-3 = "หน่วยรับจ้างสารพัด 68 เหรอ? อยู่ที่ไหนล่ะ? จากที่เห็น ดูเหมือนเธอกำลังประจัญหน้ากับทางชาเล่ต์#nมากกว่าเลยนะ"
92020-4 = "คะ? หน่วยรับจ้างสารพัด..."
